### ISSUE TITLE
Ripple with radius

### ISSUE THREAD

**Issue by sagevpremium** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1000]
Hi, 
I want to use Button inside the Border with radius ex. "10". But Ripple effect is without these radius, like normal Rectangle. Could you tell me how to style a Ripple for my control?

Regards

**Comment by Keboo** [comment]
@sagevpremium it would be good to get a better idea of what you are trying to achieve. You can see some usages of the Ripple control in the [button templates](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L28-L86). You may also take a look at the [ClipToBounds](http://drwpf.com/blog/2007/12/28/cliptoboundsmaybe/) property as well.

**Comment by sagevpremium** [comment]
Haha thank you :) Maybe any award; P I attached screenshot. It should be the best describe of my problem.
<img width="439" alt="rippletest" src="https://user-images.githubusercontent.com/19902705/43793765-ca358402-9a7c-11e8-8ee8-973140116123.png">

**Comment by sagevpremium** [comment]
Hi, I found solution :

`    <Grid Margin="20">
                    <Grid.OpacityMask>
                        <VisualBrush Visual="{Binding ElementName=Border}" />
                    </Grid.OpacityMask>
                    <Border x:Name="Border" CornerRadius="0,0,15,15" Background="Green" />
                    <Button Content="Test" Height="Auto" ClipToBounds="True" md:RippleAssist.Feedback="Yellow"/>
                </Grid>`

Thank you for tips.

Regards
