### ISSUE TITLE
ComboBox: empty ItemsSouce, first open

### ISSUE THREAD

**Issue by LiptonOlolo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1003]
Look this: https://giphy.com/gifs/AiTEOV11bXHlKN8E4S

**Comment by jespersh** [comment]
Please put some effort into your issue if you expect effort in return, starting with a minimal example to see where you're doing it wrong

**Comment by LiptonOlolo** [comment]
@jespersh ![image](https://i.imgur.com/ZJAYWv3.png)

**Comment by Keboo** [comment]
@jespersh what does the CPVValues.MyRoles properly look like? If it is being loaded asynchronously you will need to make sure that it is an observation collection to ensure that the UI updates.

Also what happens if you remove the Material Design Style and instead set it to null `Style={x:Null}`

**Comment by jespersh** [comment]
@LiptonOlolo, what @Keboo wrote towards me was meant for you

**Comment by Keboo** [comment]
@jespersh opps. Yes you are correct.

**Comment by Keboo** [comment]
Closing for now due to inactivity. If there is still an issue please re-open with details.
