### ISSUE TITLE
VS Live Visual Tree stuck at DialogHost (regression)

### ISSUE THREAD

**Issue by ondrasvoboda** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1005]
Hi,
there is a regression in the last version 2.4.1.

Original problem described and solved here #317 but reverted back in the last version in #772.

So again Live Visual Tree in VS doesn't work correctly.

**Comment by jespersh** [comment]
Reading this it sounds like we can either get Live Visual Tree or background fadeout?

**Comment by Keboo** [comment]
@jespersh just from reading those issue that is what it appears, however I suspect we can find a solution to fix both issue.

**Comment by Keboo** [comment]
For reference [here is an example project](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.WebBrowser) showing the issue (it includes a copy of the embedded DialogHost as well showing that it also has the issue until a window resize occurs). You can toggle the DialogHost style to test and compare differences.
