### ISSUE TITLE
Add .editorconfig file to repository

### ISSUE THREAD

**Issue by cjbush** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1009]
Just a thought, but it might make things a little easier to contribute if there was an .editorconfig file in the solution files. VS2017 supports them as a first class feature now.

**Comment by Keboo** [comment]
This would be a good addition. Currently we default to the common VS defaults. If you want to submit a simple .editorconfig we can get it added.

**Comment by cjbush** [comment]
I'll see what I can do. My settings are so completely different from the defaults because of the style I use at work, but I'm sure there's a default file floating around somewhere on the Internet. Give me a few minutes 😄

**Comment by cjbush** [comment]
I totally forgot, I've already got IntelliCode installed, so I just generated one by default. Seems to work ok. It's in PR #1010 if you want to take a look.
