### ISSUE TITLE
Button disabled - DialogHost & Calendar

### ISSUE THREAD

**Issue by R00iBaard** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1013]
Hi,

So for some reason I cannot get the button to be enabled. I am using the 2nd to last example within the  Pickers usercontrol.

<img width="641" alt="screen shot 2018-08-15 at 5 01 38 pm" src="https://user-images.githubusercontent.com/11412240/44155192-ecd038dc-a0ac-11e8-9872-9bc770b16db8.png">
As per image attached this is what I see when run the following code:

>  <StackPanel Orientation="Horizontal" Margin="0 25 0 15" HorizontalAlignment="Center" IsEnabled="True">
                    <TextBlock Foreground="{DynamicResource MaterialDesignBodyLight}" Text="{Binding Date, StringFormat=d}" VerticalAlignment="Center" FontSize="24" />
                    <Button Margin="8 0 0 0" Content="..."
                            IsEnabled="True"
                            materialDesign:DialogHost.DialogOpenedAttached="CalendarDialogOpenedEventHandler"
                            materialDesign:DialogHost.DialogClosingAttached="CalendarDialogClosingEventHandler"
                            Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}">
                        <Button.CommandParameter>
                            <Grid>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>
                                <Calendar x:Name="Calendar" Margin="-1 -4 -1 0" />
                                <StackPanel Grid.Row="1" Margin="8" HorizontalAlignment="Right" Orientation="Horizontal">
                                    <Button Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" IsDefault="True" CommandParameter="1" Style="{DynamicResource MaterialDesignFlatButton}">OK</Button>
                                    <Button Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" IsCancel="True" CommandParameter="0" Style="{DynamicResource MaterialDesignFlatButton}">CANCEL</Button>
                                </StackPanel>
                            </Grid>
                        </Button.CommandParameter>
                    </Button>

**Comment by R00iBaard** [comment]
I managed to find a workaround but still puzzled how the demo code works with button command parameters - https://stackoverflow.com/questions/51861636/button-disabled-dialoghost-calendar#51862497

**Comment by Keboo** [comment]
@R00iBaard is there a DialogHost somewhere in the element tree above that button?
