### ISSUE TITLE
DialogHost Shadow Incorrect

### ISSUE THREAD

**Issue by meromy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1014]
Version 2.4.0. (old)

![2 4 0](https://user-images.githubusercontent.com/42421153/44172818-daf77800-a110-11e8-9720-85b86a6b6a32.png)

Version 2.4.1 (new)

![2 4 1](https://user-images.githubusercontent.com/42421153/44172832-e2b71c80-a110-11e8-8242-0098d9b3fcdd.png)

**Comment by jespersh** [comment]
Could you also check with Master?

**Comment by meromy** [comment]
Version 2.4.1 (Master)Master

![Uploading MASTER.png…]()

**Comment by Keboo** [comment]
The fix for duplicate margins on card #948 appears to be the cause of this.

**Comment by Keboo** [comment]
When the double margin bug on cards were fixed it caused the shadow on dialogs to get cropped. Previously the default DialogMargin was 22, which when doubled left 44 units of space around the dialog's card (plesnty for the 35 needed by shadow Depth5). But when that was cut it half the shadow was then clipped. 

@meromy as a work around you can set the DialogMargin on your DialogHost to 35 and that should resolve the issue.

**Comment by bebenins** [comment]
Thanks Kevin,
But this shadow issue is going to be fixed in the release, correct?  At some point I mean.

**Comment by Keboo** [comment]
@bebenins yes, it is already fixed on the master branch and will go out with the 2.5.0 release. There are also 2.5.0 preview nugets you can test with now too.
