### ISSUE TITLE
Horizontal scrollbar location is different as I expected

### ISSUE THREAD

**Issue by hv0905** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1016]
I just created a Textarea Textbox with following code:
```xml
<TextBox Grid.Row="1" Margin="4" Style="{StaticResource MaterialDesignTextAreaTextBox}"
materialDesign:HintAssist.Hint="多条URL请用回车换行,支持:HTTP FTP"
TextWrapping="NoWrap" HorizontalScrollBarVisibility="Auto"
AcceptsReturn="True" VerticalScrollBarVisibility="Auto" HorizontalAlignment="Stretch"
VerticalAlignment="Stretch" />
```

Everything is ok, except the horizontal scrollbar.
When The text content can't fill all lines of the textbox, the horizontal scrollbar shows under the text , not  at the bottom of the textarea. like this image:
![old](https://user-images.githubusercontent.com/29349119/44276064-02695480-a279-11e8-92cb-7a219c8d7a60.png)
And this is what I expected:
![expected](https://user-images.githubusercontent.com/29349119/44276136-2f1d6c00-a279-11e8-91ef-39fbea465894.png)

Big thanks if you can fix this problem ,it should be just a simple problem.(╹ڡ╹ )

**Comment by jespersh** [comment]
What element are you using as a container? A full example might help here. 
Not all container elements supports this kind of fill height

**Comment by hv0905** [comment]
I have upload an example in Github.
See:
https://github.com/hv0905/MaterialDesignInXamlToolkit_Issues_1016
Thanks.

**Comment by hv0905** [comment]
@jespersh I tried Grid, Stackpanel and DockPanel. All of the scrollbars are at the wrong position.

**Comment by jespersh** [comment]
In this particular case, then you need to add `VerticalContentAlignment="Stretch"` to the TextBox

**Comment by hv0905** [comment]
@jespersh It works. Thanks.
