### ISSUE TITLE
Dialog inside dialog is small

### ISSUE THREAD

**Issue by cmeeren** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1017]
When I place a dialog inside another dialog, the inner dialog is really small:

![image](https://user-images.githubusercontent.com/7766733/44287208-43a73780-a26c-11e8-9b83-5da89552c27a.png)

(The "New Transaction" dialog is a UserControl that is within a DialogHost, and there's another DialogHost inside the UserControl that contains the smaller message.)

IMHO this is a usecase that should be supported, because you might have an editor (like above) that pops up as a dialog, and then a "confirm close" dialog when the cancel button is clicked if you've made edits.

It happens with both 2.4 and 2.5.

Let me know if you need a repro solution.

**Comment by Keboo** [comment]
@cmeeren yes if you could provide a small sample that reproduces the problem that would be wonderful.

**Comment by cmeeren** [comment]
Repro repo: https://github.com/cmeeren/MaterialDesignInXamlToolkit.Issue.1017

It seems to only happen when the inner dialog has `IsOpen = true` (either hardcoded or through binding) when the outer dialog's `IsOpen` is being changed from `false` to `true`. (If both dialogs are hardcoded to `true`, it works fine.)
