### ISSUE TITLE
"mD:DialogHost" Tag somehow prevent the designer to select elements inside

### ISSUE THREAD

**Issue by guo40020** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1018]
I updated to the latest version of MaterialDesignThemes on Nuget _(Version 2.4.1.1101)_. Then I found I could not select elements inside the <DialogHost> Tag but the Application is working fine. The only thing I could select is the DialogHost itself, until I downgraded to 2.4.0. I am kind of new to WPF, I don't know if i did something wrong.

**The Code to reproduce the problem is [HERE](https://github.com/guo40020/WalkmanManager/tree/6041f1dad297d9efb4de70fcbcde1172bbe500c5)**

_Development Environment
OS: Windows 10 x64
VisualStudio 2017 Community_

**Comment by sanke** [comment]
Can confirm we are having same issue (2.4.1.1101) and downgrade to 2.4.0.1044 helps.

**Comment by Keboo** [comment]
Should be fixed by #1045

**Comment by guo40020** [comment]
ありがと
