### ISSUE TITLE
Show Password

### ISSUE THREAD

**Issue by almas3s** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1023]
hi. please add Feature show password in passwordBox **MaterialDesignPasswordFieldBoxPasswordBox**

**Comment by MrSquirrely** [comment]
Here you go: https://gist.github.com/MrSquirrely/cea08b9a6a18058be51fdab188a26677
This is the only way I could find to do this.

**Comment by darcome** [comment]
Would it be possible to have this feature integrated in Version 5? Thanks in advance!

**Comment by Keboo** [comment]
Unfortunately this is not something that can be reasonably implemented within the library. The common implementations for doing this are exactly as  MrSquirrely posted above (have both a TextBox and PasswordBox and toggle between them). Directly implementing this in the library could raise a security concern. My recommendation would be for apps that want this functionality to make the determination themselves and implement something similar as they see fit.
