### ISSUE TITLE
Why MaterialDesignPasswordFieldBoxPasswordBox not available in version 2.4.1 ?

### ISSUE THREAD

**Issue by nolongerhesitate** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1024]
![e3 bqm efp r1h ha1fk2](https://user-images.githubusercontent.com/9473998/44517558-a54b2400-a6fa-11e8-92a1-70e72b042387.png)

![q8 1pkxejo_ 9l8b_x](https://user-images.githubusercontent.com/9473998/44517677-e8a59280-a6fa-11e8-8ad1-119e90f59973.png)

**Comment by jespersh** [comment]
Are you looking for a different answer than "Because it was added 7 days ago and 2.4.1 was released 26 days ago"?

**Comment by Keboo** [comment]
@nolongerhesitate 
@jespersh is correct, this is a new style that is being added for the 2.5.0 release. If you want to use it now, grab the latest preview nuget package.
