### ISSUE TITLE
Close all dialogs?

### ISSUE THREAD

**Issue by LiptonOlolo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1026]
how closing all opened dialogs?

**Comment by jespersh** [comment]
In codebehind: Then you need a reference to each open dialog and you get this reference by capturing the show dialog event. Then call the close for each reference. 
See more here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs#close-dialog-strategies

**Comment by LiptonOlolo** [comment]
I use MVVM

**Comment by Keboo** [comment]
@LiptonOlolo as @jespersh mentioned this is something that you would have to manage in your application. Whatever method (in addition to the docs above check out [this blog post on using dialogs] (https://intellitect.com/material-design-in-xaml-dialog-host/)) you are using to show the dialogs, will need to keep track of the dialogs that it has shown and close them
