### ISSUE TITLE
Emoji support 😋

### ISSUE THREAD

**Issue by Lorymi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1028]
hi, I'm building an Instagram for Windows with your library !
i need to supports of google emojis on my app.
can you help me? to display emoji.

![inked12211212_li](https://user-images.githubusercontent.com/22388644/44620680-f4858600-a8ad-11e8-9510-f6851f6960e5.jpg)

[this is my project](https://github.com/Lorymi/wingram)

Can you add support of emojis on textblock and textbox controls to this library ?
@ButchersBoy  @Keboo  ❤️😊

**Comment by Keboo** [comment]
Hi @Lorymi at this time this is outside of the scope of this library. Though it would be a nice feature, there are other more pressing issue. You might take a look at [Emoji.wpf](https://github.com/samhocevar/emoji.wpf) in addition to the ASCII option mentioned above.
