### ISSUE TITLE
Dialog closed when handover to other tabitem

### ISSUE THREAD

**Issue by 160384921** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1030]
I have tab control with two tabitem.
There is a DialogHost in the first tabitem and one dialog opend,when i clicked the second tabitem,the dialog will be closed.
Is there a solution to prevent closing this dialog?
I searched all Isssues but nothing founded.Pls tell me if you know about it,Thanks.

**Comment by Keboo** [comment]
@160384921 you likely want to move the tab control inside of the DialogHost so that the dialog wraps off of the content. You can find more information on the dialog host setup [here](https://intellitect.com/material-design-in-xaml-dialog-host/) and [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs).

**Comment by Keboo** [comment]
@160384921 ah I see the problem now. The key issue here is that the WPF TabControl only has a single panel for displaying the selected tab. So when you switch between tabs it destroys and re-creates the tab's view every time. To solve this you have a few options:
1. Persist the state of the view in some other class. In this simple example the only state that we need to persist is the IsOpened property of the DialogHost. In an [MVVM setup](https://intellitect.com/getting-started-model-view-viewmodel-mvvm-pattern-using-windows-presentation-framework-wpf/) you would do this by [binding the IsOpen property](https://intellitect.com/material-design-in-xaml-dialog-host/) of the DialogHost to a property in your view model. In this manner, the "state" is saved with the view model and will be restored when the tab is selected. Alternatively you could handle this directly in the `MainWindow.xaml.cs` using the `DialogOpened` and `DialogClosed` events and simply keeping track of the state of the dialog there. This would also mean keep track of the tab control's `SelectionChanged` event and properly re-showing the dialog if needed.
2. Disable the tab control's virtualization of the view. Depending on your application, this might be the "simplest" solution. The tab control recreating its views every time has been around for a while and people have created various solutions for solving it. Typically this involves either subclassing the TabControl or adding some attached property to it. You can see various solutions [here](https://stackoverflow.com/questions/9794151/stop-tabcontrol-from-recreating-its-children) and [here](https://www.ikriv.com/dev/wpf/PersistentTabControl/index).
