### ISSUE TITLE
Visual Error template background color

### ISSUE THREAD

**Issue by quicoli** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1032]
Hello friends,

I'm using version 2.4.1.1101 and when I apply validation, the background is black, shouldn't it follow the UI control backgroundcolor?

![image](https://user-images.githubusercontent.com/8388239/45088026-b5ea9980-b0ff-11e8-8eae-b9de19c902b9.png)

thanks

**Comment by Keboo** [comment]
@quicoli That color is controlled by the `ValidationAssist.Background` property. When it is not set, it [falls back](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml#L95-L98) to using the theme brush `MaterialDesignPaper`.

If you want it to use the same brush as your control, simply bind the `ValidationAssist.Background` property to your control's `Background` property.
