### ISSUE TITLE
Create SelecteTimeChanged event for TimePicker

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1033]
The TimePicker control do not have a SelecteTimeChanged event to correspond with its SelectedTime property. This should be added.

Add a new SelecteTimeChanged event to the TimePicker control. You can use the [ValueChangedEvent from the RatingBar control](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/RatingBar.cs#L54-L93) as an example.

- [ ] Add SelectedTimeChanged routed event to the TimePicker control
- [ ] Register for the event on one of the TimePicker control in the [demo app](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Pickers.xaml#L66). The event handler should just display using `Debug.WriteLine`

**Comment by LiryChen** [comment]
Hey, I am a first-timer looking for open source tasks to start off. I found this issue pretty interesting. Could I claim it? Is there anyone I can reach out to when I need help to understand the code and the issue?

**Comment by Keboo** [comment]
Hi @LiryChen. Welcome. Yes if you would like to claim this simply assign it to yourself. If you have any questions, feel free to post here and i will be happy to help.

**Comment by LiryChen** [comment]
Sounds great! I will look into the issue. I couldn't assign this to myself unless I create a pull request though, I think.

**Comment by Keboo** [comment]
@LiryChen sounds great. Looks like the assignment of issues is limited to just a couple people, so simply having your comment saying you are working on it will be good enough :). Let me know if you need any help.
