### ISSUE TITLE
UWP and Xamarin

### ISSUE THREAD

**Issue by pcouuy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1034]
hi. Does anyone help me to port this library to UWP and Xamarin?

**Comment by Keboo** [comment]
Hi @pcouuy at this point, I am not aware on anyone working on porting this library to UWP or Xamarin.Forms. 
If the community is interested in doing a port to UWP I am happy to assist, but I don't currently have the availability to do it. 
As for Xamarin.Forms I am a bit skeptical that a full port would be possible. At present the XAML stack in Xamarin.Forms does not fully support re-templating controls. This would mean custom renderers for all of the controls which would be a major time investment.
