### ISSUE TITLE
Button animation and control shadows not working when use AssemblyResolve to load dll

### ISSUE THREAD

**Issue by TGSAN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1040]
Button animation and control shadows not working when use AssemblyResolve to load dll。
I try to build a single file application, so i used AssemblyResolve to load dll. But i notice the button and all control shadows are missing.

Code in MyWPF.Program.Main:

    AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>

    {

        String resourceName = "MyWPF.Res." +

        new AssemblyName(args.Name).Name + ".dll";

        Console.WriteLine("Load Assembly: " + resourceName);

        using (var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceName))

        {

            Byte[] assemblyData = new Byte[stream.Length];

            stream.Read(assemblyData, 0, assemblyData.Length);

            return Assembly.Load(assemblyData);
        }

    };

**Comment by TGSAN** [comment]
[](url)

> Could you provide a small demo repo to showcase your issue? It would look like it isn't loading Generic.xaml that has the button ripple animation

This is my project: 
[https://github.com/TGSAN/CMWTAT_Digital_Edition](url)

**Comment by TGSAN** [comment]
In the latest version 2.5.0.1205, this issue is even more serious and obvious. Can't even pop up `<materialDesign:DialogHost.DialogContent>.`

**Comment by Keboo** [comment]
@TGSAN take a look at the [PR](https://github.com/TGSAN/Single_File_To_Load_MaterialDesignInXamlToolkit/pull/1) I opened

**Comment by TGSAN** [comment]
@Keboo Thanks for your PR, but it still not working. I noticed that it is loading an external .dll assembly file in release directory. if delete .dll files then you will find that the issue still exists. :(

**Comment by Keboo** [comment]
Fixed on remote [repo](https://github.com/TGSAN/Single_File_To_Load_MaterialDesignInXamlToolkit).
