### ISSUE TITLE
wpf button animation dont show 

### ISSUE THREAD

**Issue by meilleur102** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1042]
Hi! Ive try to find a solution over the internet and all the forum but I dnt find it. 

The animation of the button work fine if you hold down left click for a second but when you just click(normally) the application is too fast and we dont see the animation. 

thes's a way to access the proprity of the animation to let it finish before it continue the action? 

Thanks.

**Comment by jespersh** [comment]
Think I understand what he is trying to do with the button's Ripple effect.
Currently what he has: You got a button, you press it, the event fires which changes the UI to no longer include the button. 
One example coming to mind are the transition slides.

What you'd normally do is this:
1. Attach button click event
2. Press button to fire event
3. Find the doubleanimation and attach to the .Completed event (`doubleAnimation.Completed += (sender, eArgs) => Proceed();`)
4. Wait for .Completed event to fire to do the UI transition.

@meilleur102 would need to understand that the ripple takes 1.2s to complete and the user could press all sorts of buttons in the mean time.
