### ISSUE TITLE
Use of Name and Logo in other open source project.

### ISSUE THREAD

**Issue by abhi-cognitivo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1044]
Hi,

Great work on Material Design in XAM. I am creating an open source project [Cognitivo.Shop](https://github.com/Cognitivo/Shop) that will utilize your toolkit. Would it be alright if I mentioned MaterialDesignInXamlToolkit along with your logo in special thanks section?

Thanks

**Comment by Keboo** [comment]
@abhi-congnitivo Glad to hear you are enjoying the toolkit. Yes it is ok to reference the project and use the logo in your special thanks section
