### ISSUE TITLE
The buttons of PopupBox don't display in DialogHost

### ISSUE THREAD

**Issue by nolongerhesitate** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1048]
version: 1.2.0.31843

As shown in Illustration.I hope you can help me.

![gif](https://user-images.githubusercontent.com/9473998/46196630-39338f80-c33a-11e8-90e9-1e51914cce14.gif)

This is my code. It was opened by command.

![vja2k h 4 ud k2f i](https://user-images.githubusercontent.com/9473998/46197061-48670d00-c33b-11e8-9561-51876a1c874c.png)

**Comment by mgnslndh** [comment]
Is this because the `PopupBox` content opens under the dialog?

**Comment by lihongfang16** [comment]
I have the same issue , the first two can not display buttons ,but other will be ok!
