### ISSUE TITLE
Bottom bar navigation

### ISSUE THREAD

**Issue by univisionsrl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1051]
I am not able to find any button to show a [bottom bar navigation](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1qzBP48tarumddAHTFpA10I947_tqQQCA%2Flateral-bottom-nav.png), with icon highlight when selected. Is this feature implemented somewhere?

**Comment by Keboo** [comment]
The closest thing that is currently implemented is [with radio buttons](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Buttons.xaml#L571-L589).

![image](https://user-images.githubusercontent.com/952248/46360918-46de6300-c621-11e8-8616-1e59faf7c16f.png)

**Comment by mgnslndh** [comment]
Not sure how `MaterialDesignTabRadioButton` would look like with a `PackIcon` but I guess it wouldn't be too hard to make a new `MaterialDesignNavigationBarRadioButton` that looks like the bottom bar spec.

I also made a request for a navigation bar like control some time ago https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/652

**Comment by Keboo** [comment]
There is now also a navigation rail built into the library
