### ISSUE TITLE
WPF Transitions Nullreferenceexception

### ISSUE THREAD

**Issue by kembels** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1061]
Hi, I am working on a WPF application. Within this application I have a login window which should direct me to the next window (PPM) after bottom click event:

`PPM Overview = new PPM(pjtno);
            
            Overview.ShowDialog();`

This next window contains "dragablz:TabablzControl" with several tabitems. The point is that the transitioner is applied to second tabitem and not the first one. Here the problem occurs, i.e. once I click the button in original window the issue with Nullreferenceexception is thrown at "Overview.ShowDialog();" above. However, this problem does not occur if transitioner is applied at first tabitem.

Can you please help me advising how this problem can be solved. I need to have the transitioner at second tabitem.

Thank you very much.

**Comment by jespersh** [comment]
Only the visible tabitem exists (by default) in the visual tree (for loading speed).
Check the live visual tree inspector. 
You could change the visible tab first or move the dialog "out and further up" the tree.
It is a bit hard to help with a minimal example project. Just one that shows the structure is fine with the dialog.

**Comment by kembels** [comment]
ok, thank you ver ymuch for your feedback. You are right, I should have posted a larger piece of code. Prior to do so, let me ask a general question then. Is it possible to apply such transitions to several tabitems at the same time?
