### ISSUE TITLE
WPF - How to connect gauge with results of sql query?

### ISSUE THREAD

**Issue by kembels** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1071]
Hi everyone

in my wpf project I am working with a gauge chart from livecharts, see my XAML code:

`<lvc:Gauge x:Name="gauge1" Grid.Row="2" Grid.Column="0" Margin="5" From="0" To="5" Value="0" />`

The here shwon figures for the values "From", "To" & "Value" are set by default. However, I would like to replace those figures by results from a sql query. At the moment, my code behind for the value "To" looks like that:

`private void PPMRFQSOVERVIEW_Loaded(object sender, RoutedEventArgs e)

    {

        string connectionString = "SERVER=localhost;DATABASE=test;UID=root;PASSWORD=;sslmode=none";
        MySqlConnection connection = new MySqlConnection(connectionString);

        connection.Open();
        MySqlCommand cmd = new MySqlCommand("SELECT Count(test.projectrfqs.lotid) AS Count_lotid FROM test.projectrfqs INNER JOIN test.projectdetails ON test.projectdetails.PJTdetailsID = test.projectrfqs.PJTdetailsID WHERE test.projectdetails.PJTno = @PJTno", connection);
        cmd.Parameters.AddWithValue("@PJTNo", GlobalClass.PJTNo);
        MySqlDataReader myReader;
        myReader = cmd.ExecuteReader();

       /// what has to follow here?

        connection.Close();

    }`

I am missing that part, how to display the result of the COUNT query into the value "To" of the gauge1. Does anyone have an idea?

Any hint would be highly appreciated.

Thank you.

**Comment by SimoneDalka** [comment]
I suggest you use the [MVVM pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93viewmodel) and bind the value of "_**To**_"  to a property set in your view model. 
But despite this, if you want to set that value in code behind, since you already have set _x:Name_ for the gauge, you can simply do:
```
MySqlDataReader myReader = cmd.ExecuteReader();
DataTable dt = new DataTable();
dt.Load(myReader);

gauge1.To = dt.Rows.Count;

myReader.Close();
connection.Close();
```

**Comment by kembels** [comment]
Wow, great thank you very much. This was exactly what I was looking for. There is only one point. As the result of my sql query is COUNT, there will be one row in my datatable with the result of this query, i. E. When I apply
`gauge1. To = dt. Rows. Count` my gauge chart will show 1 as To value. However I need to have this result of COUNT, i. E. The result of my sql query. How shall I do that? Thank you very much.

**Comment by SimoneDalka** [comment]
I misunderstood you, sorry. In this case DataTable dt will have only one row (you can access it using dt.Rows[0]).
That row will have only one column called "Count_lotid".
You can achieve your goal doing something like this:
```
MySqlDataReader myReader = cmd.ExecuteReader();
DataTable dt = new DataTable();
dt.Load(myReader);

gauge1.To = dt.Rows[0]["Count_lotid"];

myReader.Close();
connection.Close();
```
