### ISSUE TITLE
Drawer open by code ?

### ISSUE THREAD

**Issue by bidasknakayama** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1073]
Is there any way to open drawer by code ?
I saw manual , but no description... 
I want to open like this , like dialog..
but No open function.

```

            var drawerView = new DeviceSettingDrawerView
            {
                DataContext = new DeviceSettingDrawerViewModel()
            };
            var result = await DrawerHost.open(  drawerView... )

```

**Comment by jespersh** [comment]
Tried to use the RoutedCommand?
`DrawerHost.OpenDrawerCommand.Execute(NamedDrawerHost, Dock.Left);`

**Comment by Keboo** [comment]
In addition to the above solution there is also `Is*DrawerOpen` boolean properties on the DrawerHost that you can simply toggle to open and close the drawers.

**Comment by SkyEngine-OSP** [comment]
Wondering if there's an updated snippet for version 4.6.1 since the parameter for the RoutedCommand got changed.

![image](https://user-images.githubusercontent.com/12471935/202122196-90b11d30-7ada-41e3-9a57-2d0418445fc5.png)

**Comment by Keboo** [comment]
@SkyEngine-OSP not sure what you mean. The DrawerHost does not accept the content being passed to it via the command. Rather the parameter can be a value from the `DockPanel.Dock` enum (so passed the name of the DrawerHost will not work). I do have a few examples of working with the DrawerHost [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DrawerHost)

Is it possible you are confusing this with the `DialogHost`?
