### ISSUE TITLE
RenderTransform in TransitioningContentBase

### ISSUE THREAD

**Issue by SimoneDalka** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1074]
Hi. I tried to use a _TransitioningContent_ setting a _TransitionEffect_ with _SlideInFromRight_ Kind as OpeningEffect.

If I set the BorderThickness on the _TransitioningContent_ the border does not animate and only the content slides in (because the RenderTransform is applied on the ContentPresenter). 

![transitioningcontent](https://user-images.githubusercontent.com/5476277/47154547-eb7bc880-d2e2-11e8-95aa-4e2599bbf60e.gif)

I don't know if there is a specific reason for this but I would apply the render transform directly on the Border root of the ControlTemplate

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8567c14b5aea924f5e6b64271cc5b20b7a5c76a0/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L879-L901

**Comment by Keboo** [comment]
@SimoneDalka You could always place a border around your content to get the behavior that you describe. I am thinking that the behavior as it is now is probably the most expected. I am open to more discussion on it. Would be interested if other people have other opinions on this.

**Comment by SimoneDalka** [comment]
Thank you. It was only to avoid a double border in the visual tree. Let's see what other developers think

**Comment by Keboo** [comment]
Closing for now. If anyone has opinions on how this should behave feel free to attach additional comments/feedback
