### ISSUE TITLE
Change Datepicker months names 

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1077]
How can i change the months names in DatePicker control to local name?
I changed the CultureInfo and it worked in default WPF styles, but in Material Design it not work.

[Default Mode Screenshot](https://www.dropbox.com/s/6egjivxgemuzg3p/Normal.PNG?dl=0)

[Material Mode Screenshot](https://www.dropbox.com/s/s4ii7p1kwvwf1j7/MD.png?dl=0)

**Comment by jespersh** [comment]
Wondering about these questions:
* Does it correct itself if you change month?
* When are you setting the application CultureInfo?
* How are you setting the CultureInfo?

**Comment by spiegelp** [comment]
@AmRo045 Have a look at [App.xaml.cs](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml.cs). The code in the comment shows how to set a CultureInfo. WPF apps usually run with the operation system's language. However you need to call `FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));` in order that WPF applies the language to string formats in XAML.

**Comment by AmRo045** [comment]
> @AmRo045 Have a look at [App.xaml.cs](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml.cs). The code in the comment shows how to set a CultureInfo. WPF apps usually run with the operation system's language. However you need to call `FrameworkElement.LanguageProperty.OverrideMetadata(typeof(FrameworkElement), new FrameworkPropertyMetadata(XmlLanguage.GetLanguage(CultureInfo.CurrentCulture.IetfLanguageTag)));` in order that WPF applies the language to string formats in XAML.

I used this code, but that thrown exception:

> Specified time is not supported in this calendar. It should be between 03/22/0622 00:00:00 (Gregorian date) and 12/31/9999 23:59:59 (Gregorian date), inclusive.

**Comment by spiegelp** [comment]
@AmRo045 `new CultureInfo("fa-Ir")` causes the issue: The styles and code do not support its `PersianCalendar`. The code assumes a `GregorianCalendar` which might cause wrong formatting and exceptions with valid `PersianCalendar` dates.

**Comment by Keboo** [comment]
Resolved by #1080
