### ISSUE TITLE
dialoghost, dialog not clickable

### ISSUE THREAD

**Issue by furesoft** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1078]
i open the dialog with DialogHost.Show(...) it works fine but nothing is clickable

**Comment by jespersh** [comment]
Also check your visual tree in the live visual tree inspector :-)

**Comment by furesoft** [comment]
`<material:DialogHost
                x:Name="dhost"
                DialogContent="{Binding DialogContent, Converter={c:DialogContentConverter}}"
                IsOpen="{Binding DialogOpened}">
                <ui:PageTransition
                    Name="pageContainer"
                    Margin="25"
                    TransitionType="SlideAndFade" />
            </material:DialogHost>`

the binding works. the content is set and dialog is opened.

**Comment by furesoft** [comment]
ive found the problem, the problem was a textbox was above the buttons in the dialog
