### ISSUE TITLE
Flat Button Shadow Effect 

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1081]
How can i add shadow effect to flat buttons?
Like this:
![Flat Button Shadow Effect](http://uupload.ir/files/y4_2018-10-22_10-55-13.gif)

**Comment by speedyalibaba** [comment]
Your Button looks more like the Button in issue #1075

**Comment by speedyalibaba** [comment]
That would be an workaround:
`<Button Margin="15" Content="ShadowButton" materialDesign:RippleAssist.Feedback="{DynamicResource PrimaryHueLightBrush}"
	Background="{DynamicResource MaterialDesignPaper}" Foreground="{DynamicResource PrimaryHueMidBrush}"
	materialDesign:ShadowAssist.ShadowEdges="None" materialDesign:ShadowAssist.ShadowDepth="Depth0">
	<Button.Style>
		<Style TargetType="Button" BasedOn="{StaticResource MaterialDesignRaisedButton}">
			<Style.Triggers>
				<Trigger Property="IsPressed" Value="True">
					<Setter Property="Effect" Value="{StaticResource MaterialDesignShadowDepth2}" />
				</Trigger>
			</Style.Triggers>
		</Style>
	</Button.Style>
</Button>`
