### ISSUE TITLE
Problems with Windows Scaling

### ISSUE THREAD

**Issue by JPierron** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1082]
Hi there,

I'm facing a couple difficulties with the Xaml toolkit when windows scaling is other than normal 100%.
I'm testing with a 150% scaling.

I'm using the version 2.5.0.1205

For instance, a hole appears in the combobox popup, as stated in issue 584.
**At 100**
![combobox_100](https://user-images.githubusercontent.com/2762791/47292555-a966c580-d607-11e8-9c15-7be8dd86c3dc.png)
**At 150**
![combobox_150](https://user-images.githubusercontent.com/2762791/47292537-9c49d680-d607-11e8-8c7b-0ad81400d40c.png)

Also, textbox cursor disappears randomly. In my case, it is not showing on focus, while the textbox is empty.
**At 100**
![empty_textbox_100](https://user-images.githubusercontent.com/2762791/47292670-08c4d580-d608-11e8-92cf-ad615c24e4e0.png)
**At 150**
![empty_textbox_150](https://user-images.githubusercontent.com/2762791/47292673-0d898980-d608-11e8-970e-35ec906a3cc4.png)

And, it appears/disappears kind of randomly while typing.
**At 100**
![textbox_100](https://user-images.githubusercontent.com/2762791/47292687-18441e80-d608-11e8-8e87-9378d28f451d.png)
**At 150**
![textbox_150](https://user-images.githubusercontent.com/2762791/47292697-1e39ff80-d608-11e8-8cd6-675bbb8d3b72.png)

Are you aware of these behaviors ?
Do you have any idea what's causing them ? Any advice on how to correct them ?

Thanks.

Bests

**Comment by MairwunNx** [comment]
@JPierron 

It is **not clear** that you have increased in the **screenshots**, you can **more data**? I doubt there is a problem in the library, my application **also uses** scaling gui, but I have not encountered such a problem. Check your **XAML markup**.

Or provide the code you use to **scale** the interface.

**Comment by JPierron** [comment]
@MairwunNx 

The scaling i'm talking about is the OS scaling (in windows settings).
My application adapts, and that's why it isn't clear to you.

Also, It seems, regarding the combobox, it is a problem others are facing as well :
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/584
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1011

**Comment by MairwunNx** [comment]
@JPierron hmm ... i also try use system scaling, i not see a problem 
![image](https://user-images.githubusercontent.com/39625750/47301780-66691a00-d628-11e8-8af1-1f5c81c3cbdc.png)

![image](https://user-images.githubusercontent.com/39625750/47301784-6bc66480-d628-11e8-9b17-9df4031b254c.png)
Also i not find problem with textbox. 

Also i test on 150% | All work normally

![image](https://user-images.githubusercontent.com/39625750/47301916-ca8bde00-d628-11e8-8daf-6f0ae5a1ba00.png)

![image](https://user-images.githubusercontent.com/39625750/47301927-d4154600-d628-11e8-9071-cf6ef83982bf.png)

![image](https://user-images.githubusercontent.com/39625750/47301935-e0010800-d628-11e8-943d-a7049426c7ee.png)

**Comment by MairwunNx** [comment]
But I noticed that the Selection cursor, has become much thinner, but it has not disappeared. Maybe I just got lucky? 😃

**Comment by JPierron** [comment]
Haha!
I sure hope i didn't just get unlucky, though.
Before testing it out, did you try to sign out and sign back in windows after setting the scaling to 150% ?
Often, this is needed for the switch to be fully applied.
Anyway, it seems several cases have been encountered.

I don't think i'm doing anything out of the ordinary with my textbox and combobox.

**ComboBox**
            <Grid Grid.Row="4" Margin="0 5 0 0">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="1*" />
                    <ColumnDefinition Width="2*" />
                </Grid.ColumnDefinitions>
                <TextBlock Grid.Column="0" VerticalAlignment="Bottom" HorizontalAlignment="Left" Margin="30 3 10 3" FontSize="28" TextWrapping="Wrap" Foreground="#1F6558" Text="Catégorie de local :"/>
                <ComboBox Grid.Column="1" VerticalAlignment="Bottom" materialDesign:HintAssist.Hint="Catégorie" materialDesign:HintAssist.IsFloating="False" Margin="30 3 30 3" HorizontalAlignment="Left"
                  MinWidth="72" MaxWidth="350" FontSize="24" Name="categorie" Style="{StaticResource MaterialDesignFloatingHintComboBox}" DisplayMemberPath="Value.DisplayIHM" SelectedValuePath="Value.IdCategorieLocalCentre"
                          ItemsSource="{Binding Source={x:Static businessService:TableRefManager.XamlTrCategorieLocal}, Mode=OneWay}" SelectedValue="{Binding Object.IdCategorieLocalCentre, TargetNullValue=-1, Mode=TwoWay}"/>
            </Grid>

**TextBox**
                <TextBox Cursor="IBeam" Height="70" Margin="15 0" Padding="10 0" materialDesign:HintAssist.Hint="Installation" materialDesign:HintAssist.IsFloating="True" TextChanged="Field_TextChanged"
                         FontSize="30" Name="FieldInstallation" Grid.Row="0" VerticalAlignment="Center" Background="White"
                         Text="{Binding TextInstallation, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" IsEnabled="{Binding TextInstallationEnabled}"/>

**Comment by MairwunNx** [comment]
Before testing it out, did you try to sign out and sign back in windows after setting the scaling to 150% ? - Fully sign out? (I.e turn off PC and turn on?) - No, but i reload utility. 

Try uncomment it lines, maybe it help you, (in app.manifest)

![image](https://user-images.githubusercontent.com/39625750/47302878-3f601780-d62b-11e8-8d2a-1c0eb148dc24.png)

**Comment by MairwunNx** [comment]
Ok, I'm sorry I could not help. Good luck!)

**Comment by JPierron** [comment]
Well, not really a fix, rather a workaround, but if anyone was to stumble upon this issue, be aware you can avoid it by setting the attribute materialDesign:ComboBoxAssist.ClassicMode to True

**Comment by M0n7y5** [comment]
I had this problem too … I am not sure, but it seems to be problem in WPF itself… I fixed it by updating my project to newest .Net Framework 4.7.2 ...

**Comment by Keboo** [comment]
The original issues with the combo box and text boxes appear to be fixed in the latest version of the code.
