### ISSUE TITLE
Use dynamic resource for MaterialDesignToolButton foreground

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1083]
The `Foreground` property of `MaterialDesignToolButton` should use a dynamic resource instead of a hardcoded color value.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/cf4f48b0193329aef8078e3aed38b21352f3b982/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L168

**Comment by Keboo** [comment]
There are actually 3 cases of this that I found.

MaterialDesigntoolButton (the one you mentioned):
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/bd6dc7d8c9e5a9b4051f5bd62acf99d9e9f64d0a/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L168

MaterialDesignToolPopupBox:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2740f14a814896d42032ae0013b765a8a0ec04c3/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L138

MaterialDesignFlatToggleButton:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2089f6f2627705d8ff6e167e686504b6a88f0aa0/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L172

Thoughts on simply creating a new brushin the [Light](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Light.xaml) and [Dark](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml) dictionaries called `MaterialDesignToolForeground`?

**Comment by mgnslndh** [comment]
Sounds good!

**Comment by jespersh** [comment]
For each of these cases then we've got the extended styles:
`MaterialDesignToolForegroundButton`
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/bd6dc7d8c9e5a9b4051f5bd62acf99d9e9f64d0a/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L190
`MaterialDesignToolForegroundPopupBox`
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2740f14a814896d42032ae0013b765a8a0ec04c3/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L143
`MaterialDesignFlatPrimaryToggleButton`
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2089f6f2627705d8ff6e167e686504b6a88f0aa0/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L259

I wouldn't be against a new solidcolorbrush here. Or do we have existing brushes, although I can't find any that would be good

**Comment by Keboo** [comment]
@jespersh yes I considered at as an option, however it still leaves a few cases uncovered since someone can just as easily derive from one of the base styles where the color is hard coded. Now, this does mean they could manually override the colors, but this is less than ideal when you consider an app that toggles between the dark/light themes.

**Comment by kevinmbuthi** [comment]
@Keboo could only find one for the ToggleButton please give examples if there is any other

**Comment by kevinmbuthi** [comment]
Yes I was referring to them, got slightly confused there. Probably make a PR but i think new brushes could still be okay in some cases except the ForegroundPopupBox where the style can be inherited but override the foreground with a dynamic resource value to handle when a app changes dark/light theme. Am i right @Keboo

**Comment by Keboo** [comment]
@kevinmbuthi yea that sounds right.
