### ISSUE TITLE
Set color of input to use PrimaryLight instead of PrimaryMid when selected?

### ISSUE THREAD

**Issue by JamesCoyle** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1084]
I'm trying to use text inputs on the dark theme background but the primary mid hue of the default color scheme is too dark. Is there a way to set the input to use the light variant of the color scheme when it's focused? Looking at the source it appears to be hardcoded.

**Comment by Keboo** [comment]
@JamesCoyle all of the brushes should be using DyanmicResources. So all you need to do is declare a resource with a matching key at the text box level and it will get used. In this case I suspect the resource you want to override is the `PrimaryHueMidBrush`. So something like this:
```XAML
<TextBox>
    <TextBox.Resources>
        <SolidColorBrush x:Key="PrimaryHueMidBrush" Color="{DynamicResource Primary200}" />
    </TextBox.Resources>
</TextBox>
```
Depending on which color theme you are using you may need to adjust which color resource you use, but most of them use Primary200 and the color for the `PrimaryHueLightBrush`

**Comment by JamesCoyle** [comment]
Ah of course! Thanks for the help!
