### ISSUE TITLE
Calendar spacing of months/years

### ISSUE THREAD

**Issue by jamesport079** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1092]
In calendar control, months/years view can be spaced out better... too much white space at the bottom of the control. 
![image](https://user-images.githubusercontent.com/36583787/47499631-b5998f80-d860-11e8-9b34-d2fe9818893d.png)
![image](https://user-images.githubusercontent.com/36583787/47499659-cb0eb980-d860-11e8-9157-8e3043f56532.png)

**Comment by Keboo** [comment]
Appears fixed in the latest version of the code.
![image](https://user-images.githubusercontent.com/952248/134783821-75e6c816-6f03-4342-a28e-408cd0dfb939.png)
![image](https://user-images.githubusercontent.com/952248/134783824-f3c4b0f2-b8ae-4abd-90a1-28719e2753e4.png)

**Comment by jamesport079** [comment]
This post is old and unrelated to the latest glitch in calendar (showing white space at the top). It was just only a suggestion, to move month and year numbers down to reduce the white space at the bottom of the calendar or space them out further vertically. 
![Inked2021-09-25 (2)_LI](https://user-images.githubusercontent.com/36583787/134784277-533d27b3-bcd2-4c07-ab51-8b8b723522a5.jpg)
.

**Comment by Keboo** [comment]
This would be ideal, however because this is the built-in WPF Calendar control we don't control the number of items that are displayed here. For that particular screen you can see that [it populates 4 columns and 3 rows worth of buttons for the years](https://source.dot.net/#PresentationFramework/System/Windows/Controls/Primitives/CalendarItem.cs,991), and then only ever [sets 1 decade worth of years into those buttons](https://source.dot.net/#PresentationFramework/System/Windows/Controls/Primitives/CalendarItem.cs,1983aa2fbe31d23c).

Without rolling our own calendar control I don't believe populating that empty space will be possible.

**Comment by jamesport079** [comment]
Maybe I did not explain myself properly. What I meant is not adding more items to display, but add more vertical padding to the numbers so that months and years are more evenly distributed.... I edited your image to get an idea of how more visually pleasing it can look with a little bit of added padding, apart from being more touch friendly.  
![Year](https://user-images.githubusercontent.com/36583787/134850592-d553ab38-dfbc-42fc-83a6-12ce9a17f4d7.png)
.

**Comment by Keboo** [comment]
Ah that makes more sense. Thank you. I think that is a good idea.

**Comment by Xaalek** [comment]
I just have a question. Why are there two dates that are not displayed?

![image](https://user-images.githubusercontent.com/54487782/181293191-b21f9d2f-f161-4b03-b290-66a92c3907d2.png)

**Comment by jamesport079** [comment]
> I just have a question. Why are there two dates that are not displayed?
> 
> ![image](https://user-images.githubusercontent.com/54487782/181293191-b21f9d2f-f161-4b03-b290-66a92c3907d2.png)

from what I understand, Calendar years are shown in groups of 10... 2020-2029, 2010-2019 etc which makes sense. Nothing to do with MaterialDesign as such. Remember MaterialDesign is a "skin" on top of the original controls, not replacing the controls altogether.

**Comment by Xaalek** [comment]
@jamesport079 
I think years are shown in groups of 12 like months.

![image](https://user-images.githubusercontent.com/54487782/181296200-ae4b4776-6311-46f8-b3fa-dbb80fa8d8e9.png)
I saw that here https://wpf-tutorial.com/misc-controls/the-calendar-control/
Maybe that's outdated.
