### ISSUE TITLE
It's not possible to base own styles on all materialDesign Styles, because not all have keys

### ISSUE THREAD

**Issue by speedyalibaba** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1093]
Example: default style of ColorZone
If you load the package from NuGet you dont have access to the default colorZone Style, so if you want to change something you have to copy the whole style and can not just base your style on the default one.

One possible solution would be, to add keys to all styles and add new styles without keys, that are based on the old styles but change nothing.
So the controls would still have default styles, but the user could also write own styles that are based on the default styles.

**Comment by mgnslndh** [comment]
There is only one style for the `ColorZone` control so you can just base your custom style on the default style like this:

```
<Style x:Key="MyColorZone" TargetType="materialDesign:ColorZone">
   <Setter Property="Mode" Value="Inverted"/>
   <Setter Property="Padding" Value="16"/>
</Style>
```
