### ISSUE TITLE
DialogHost refresh issue on some computers (Surface laptop in this example)

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1097]
It does not happen on my old ThinkPad but it does happen on 2 Surface laptops I've tried.

This is the example in video: https://photos.app.goo.gl/kJjbu4wraiRJFVWH7
And this is repo of a slimmed down app that you can download and try: https://github.com/bebenins/DialogRefreshIssue

I'm pretty sure this started happening with 2.5.0 release because I noticed this one some dialogs once I updated to 2.5.0:
![image](https://user-images.githubusercontent.com/16761301/47676924-3bd11100-db94-11e8-9ab0-00fc4a2de9d7.png)

**Comment by jespersh** [comment]
Could you try software rendering mode as a test?
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.renderoptions.processrendermode?view=netframework-4.7.2

Adding in app.xaml.cs
```
protected override void OnStartup(StartupEventArgs e)
{
    RenderOptions.ProcessRenderMode = System.Windows.Interop.RenderMode.SoftwareOnly;
}
```

**Comment by bebenins** [comment]
> Could you try software rendering mode as a test?
> https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.renderoptions.processrendermode?view=netframework-4.7.2
> 
> Adding in app.xaml.cs
> 
> ```
> protected override void OnStartup(StartupEventArgs e)
> {
>     RenderOptions.ProcessRenderMode = System.Windows.Interop.RenderMode.SoftwareOnly;
> }
> ```

Yep, that fixed it.  So is this something to keep in mind or is there a way to "build" it into this toolkit and no one has to think about it again?
Thanks!

**Comment by bebenins** [comment]
LOL, it works nicely for my example project but for some reason my actual application doesn't handle this code.  It builds fine but when I execute it, I don't see GUI on the screen...  I see the EXE in the tack manager but no GUI.  Any ideas?

**Comment by jespersh** [comment]
Sadly the issue is your hardware and/or drivers.
Mozilla maintains a public list of blocked hardware accelerated gpus. More details here: https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers
Disabling it for everyone just because it doesn't work on a few gpus isn't very reasonable

**Comment by bebenins** [comment]
There's still an issue with one type of dialog.  I just updated the repo to include it.  It's the 3rd button (Data Entry):
![image](https://user-images.githubusercontent.com/16761301/47745660-8f0d9700-dc5a-11e8-86e2-b00bdbfb270b.png)

Any ideas what makes this special?
Thanks!

**Comment by jespersh** [comment]
Your issue here is a rounding issue with the width
![rounding-issue](https://user-images.githubusercontent.com/1004198/47846112-2d1e7000-ddc7-11e8-81f2-227652681984.png)

If you in DialogDataEntry.xaml's UserControl add UseLayoutRounding="True" like this:
```
<UserControl x:Class="DialogRefreshIssue.DialogDataEntry"
             ...
             UseLayoutRounding="True">
```

Then it'll display it properly like this:
![rounding-issue2](https://user-images.githubusercontent.com/1004198/47846229-7d95cd80-ddc7-11e8-9741-0de0dc2ae72d.png)

And Snoop now:
![rounding-issue3](https://user-images.githubusercontent.com/1004198/47846296-a61dc780-ddc7-11e8-8486-14c120673d93.png)

**Comment by bebenins** [comment]
Thank you so much!  I've learned something new today!

**Comment by bebenins** [comment]
@jespersh Thank you again for helping with this.  I'm trying to learn Snoop and having issues focusing on the Dialog.  For some reason I don't see the same tree you are seeing even though the dialog is up.  Could you please tell me how you focused on the dialog so that your tre starts with "(PopupRoot) 59"?
Thanks!
![image](https://user-images.githubusercontent.com/16761301/47859104-e713dd00-ddc3-11e8-8180-4bc4eba89ff9.png)

**Comment by bebenins** [comment]
@Keboo Thanks!  Would have never guessed it

**Comment by jespersh** [comment]
@bebenins is there more you need help with here? :-)
