### ISSUE TITLE
Date/Time/Date Time pickers have "Cancel" and "OK" buttons in wrong order

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1098]
All examples from Google, etc. have "Cancel" on the left side and "OK" on the right side.
Also, may be a good idea to set Right and Bottom button container margin to 16 and Margin between 2 buttons to 8.
Should look something like this:
![image](https://user-images.githubusercontent.com/16761301/47748531-6ccb4780-dc61-11e8-87d5-ab8a19c1e921.png)
And instead it's this:
![image](https://user-images.githubusercontent.com/16761301/47748651-adc35c00-dc61-11e8-86ec-6c5953cf4b2c.png)

**Comment by bebenins** [comment]
This is the buttons spec and they all have Margin of 16 in the corner
https://material.io/design/components/buttons.html#hierarchy-placement

**Comment by Keboo** [comment]
Fixed by #1100
