### ISSUE TITLE
Control has a shadow after it is clicked

### ISSUE THREAD

**Issue by 160384921** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1099]
Control has a shadow after it is clicked
before:
![before](https://user-images.githubusercontent.com/14368102/47764253-4b209d80-dcff-11e8-85f9-273816f4fabe.png)
after:
![after](https://user-images.githubusercontent.com/14368102/47764252-4b209d80-dcff-11e8-9ef9-dbdab589f46c.png)

**Comment by 160384921** [comment]
Like this:
![pic](https://user-images.githubusercontent.com/14368102/47764575-c33b9300-dd00-11e8-846b-d74b5b6f752f.gif)

**Comment by Keboo** [comment]
@160384921 can you add a project/code the reproduces the issue?

**Comment by bebenins** [comment]
This looks very similar, if not identical, to Issue 1097
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1097

**Comment by jespersh** [comment]
Could you also try to set software rendering?
Hardware and drivers are not perfect

**Comment by 160384921** [comment]
> This looks very similar, if not identical, to #1097
Thanks and Yes,It's done.
I have followed this [Link:](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1097#issuecomment-434181412)

@Keboo  I think no sample code needed anymore.

**Comment by Keboo** [comment]
@160384921 yes, can you try to software rending that is mentioned in #1097 ?

**Comment by Keboo** [comment]
Closing for now due to inactivity. If this is still a problem after testing with the software rendering please re-open.
