### ISSUE TITLE
Change ListBox Selected Item Background

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1101]
How can i change the listbox control selected item background brush?
![listbox control selected item background](http://uupload.ir/files/4y8h_capture.png)

**Comment by Keboo** [comment]
@AmRo045 the list box uses the [foreground color with an opacity](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml#L260-L267) to pick the background color. You can kind of cheat and change that color, but there still will be an opacity applied. 
You can kind of cheat, using something like [this example](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/ListBox/ListBox.Colors) that searches the visual tree for the right element and modifies the background property.
