### ISSUE TITLE
InvalidOperationException on TextBox.GotFocus

### ISSUE THREAD

**Issue by glencel** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1104]
This occurs when a TextBox with Visibility initially set to Collapsed is focused.

### How to reproduce:
1. Create a TextBox with Visibility set to Collapsed.
2. Create a Button and on its Click event set TextBox.Visibility = Visible and call TextBox.Focus();

Please see [https://github.com/glencel/ScaleTransformNotFound](https://github.com/glencel/ScaleTransformNotFound)

### Thoughts:
I think the ScaleTransform is not loaded yet when the GotFocus event fires. This does not happen when a delay is added before calling TextBox.Focus();

**Comment by Keboo** [comment]
Likely related to #1089

**Comment by glencel** [comment]
This is for sure related to #1089. Sorry, I missed that when searching for similar issues.
I can confirm this is fixed on 2.5.1-ci1224. Thank you!
