### ISSUE TITLE
Invalid nuget package dependency on MaterialDesignColors >= 1.1.0

### ISSUE THREAD

**Issue by AntonPetrov83** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1105]
Environment:
Visual Studio Community 2017 Version 15.8.9

I am creating a simple WPF app following Getting Starting guide.
I reference the MaterialDesignThemes nuget package which is 2.5.0.1205
It has a dependency MaterialDesignColors (>= 1.1.0)

So Visual Studio pulls MaterialDesignColors automatticaly and it is 1.1.0 which has no resources mentioned in the Getting Starting guide. There are no `Themes/Recommended/Primary/...` or `Themes/Recommended/Accent/...` resources.

Referencing manually MaterialDesignColors 1.1.3 solves the problem.

**Comment by Keboo** [comment]
@AntonPetrov83 can you provide a project that reproduces this problem? When I create a new project following those steps version 1.1.1 works for me.

In addition if I look at the contents of the dll in the 1.1.1 I do see those resources.
![image](https://user-images.githubusercontent.com/952248/48142087-f0d48f00-e260-11e8-87aa-005ad76360a9.png)

**Comment by AntonPetrov83** [comment]
I can not reproduce this at my work station with VS 2017 Profesional Version 15.8.5
Will need some time to repro at home with Community Edition.

**Comment by Tornjk** [comment]
we currently in work also experience this issue after upgrading from 2.4 to 2.5
thanks antonpretrov83 for the workaround, if i find some time i try to reproduce this with a fresh project

**Comment by Tornjk** [comment]
i reproduced the issue with a fresh project:

Visual Studio Professional 2017 Version 15.8.9

I created a new WPF Project which generates me a ready set up wpf app with *.csproj in the old VS format.
I referenced MaterialDesignThemes via Nuget package manager and added 
```XAML
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!-- https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Getting-Started -->
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml"/>

                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Amber.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
```

like in the getting started wiki
Upon starting the Application I get a IOException which states

```
System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Set property 'System.Windows.ResourceDictionary.Source' threw an exception.' Line number '13' and line position '18'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

Inner Exception 1:
IOException: Cannot locate resource 'themes/recommended/primary/materialdesigncolor.blue.xaml'.
```

Visual Studio already reports this via intellisense and squigly lines before the application is run.
When I reference MaterialDesignColors directly via nuget, the application starts normal and also visual studio has nothing to complain anymore.

I also reproduced this with the new *.csproj Format, same issue.

The bin directory contains following MaterialDesignTheme libraries:

MaterialDesignThemes.Wpf.dll - Version 2.5.0.1205
MaterialDesignColors.dll - Version 1.0.0.234541

**Comment by jespersh** [comment]
I'm not able to reproduce it with VS 15.8.8 (haven't upgraded the minor version yet)
I created a new Wpf project targetting .Net 4.5.2, which I wonder if it matters. For app.config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
</configuration>
```


Waited for it to load, then I open the "Package Manager Console" and installed:
```
PM> Install-Package MaterialDesignThemes


Attempting to gather dependency information for package 'MaterialDesignThemes.2.5.0.1205' with respect to project 'WpfApp7', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 187,3 ms
Attempting to resolve dependencies for package 'MaterialDesignThemes.2.5.0.1205' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'MaterialDesignThemes.2.5.0.1205'
Resolved actions to install package 'MaterialDesignThemes.2.5.0.1205'
Retrieving package 'MaterialDesignColors 1.1.1' from 'NuGet Packages'.
Retrieving package 'MaterialDesignThemes 2.5.0.1205' from 'NuGet Packages'.
  GET https://api.nuget.org/v3-flatcontainer/materialdesigncolors/1.1.1/materialdesigncolors.1.1.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/materialdesigncolors/1.1.1/materialdesigncolors.1.1.1.nupkg 127ms
Installing MaterialDesignColors 1.1.1.
Adding package 'MaterialDesignColors.1.1.1' to folder 'C:\Users\jsh\source\repos\WpfApp7\packages'
Added package 'MaterialDesignColors.1.1.1' to folder 'C:\Users\jsh\source\repos\WpfApp7\packages'
Added package 'MaterialDesignColors.1.1.1' to 'packages.config'
Successfully installed 'MaterialDesignColors 1.1.1' to WpfApp7
Adding package 'MaterialDesignThemes.2.5.0.1205' to folder 'C:\Users\jsh\source\repos\WpfApp7\packages'
Added package 'MaterialDesignThemes.2.5.0.1205' to folder 'C:\Users\jsh\source\repos\WpfApp7\packages'
Added package 'MaterialDesignThemes.2.5.0.1205' to 'packages.config'
Successfully installed 'MaterialDesignThemes 2.5.0.1205' to WpfApp7
Executing nuget actions took 5,89 sec
Time Elapsed: 00:00:08.1633093
```

Which produced the packages.config file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MaterialDesignColors" version="1.1.1" targetFramework="net452" />
  <package id="MaterialDesignThemes" version="2.5.0.1205" targetFramework="net452" />
</packages>
```

It installed the versions:
MaterialDesignColors 1.0.0.14576 - a slightly different version than yours?
MaterialDesignThemes.Wpf 2.5.0.1205 - Same version as yours


Will upgrade, retry and retarget a higher .Net version

**Comment by jespersh** [comment]
Upgrading to 15.8.9 and targeting 4.7.1 in a new project also works.

**Comment by Tornjk** [comment]
I noticed that our adding of the Nuget package is different

When I add MaterialDesignThemes (either via explorer or like you through package command)
it does NOT produce a packages.config
instead it adds it to my *.csproj

```
PM> Install-Package MaterialDesignThemes
Restoring packages for C:\Users\cs\source\repos\WpfApp2\WpfApp1\WpfApp1.csproj...
Restoring packages for C:\Users\cs\source\repos\WpfApp2\WpfApp1\WpfApp1.csproj...
Committing restore...
Generating MSBuild file C:\Users\cs\source\repos\WpfApp2\WpfApp1\obj\WpfApp1.csproj.nuget.g.props.
Generating MSBuild file C:\Users\cs\source\repos\WpfApp2\WpfApp1\obj\WpfApp1.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Users\cs\source\repos\WpfApp2\WpfApp1\obj\project.assets.json
Restore completed in 13.03 ms for C:\Users\cs\source\repos\WpfApp2\WpfApp1\WpfApp1.csproj.
Successfully installed 'MaterialDesignColors 1.1.0' to WpfApp1
Successfully installed 'MaterialDesignThemes 2.5.0.1205' to WpfApp1
Executing nuget actions took 1.06 sec
Time Elapsed: 00:00:01.2822015
```

```
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes">
      <Version>2.5.0.1205</Version>
    </PackageReference>
  </ItemGroup>
```

I tried .NET 4.5.2 and 4.7.2 this does not seem to affect the process

**Comment by Keboo** [comment]
@Tornjk are you using the new .csproj format? I do not think [that is supported for WPF projects yet](https://github.com/dotnet/project-system/issues/1467).

**Comment by Tornjk** [comment]
we use the new format in work without any trouble

the test projects were in the old format

**Comment by kvpt** [comment]
Same problem for me, but resharper helped me to solve the issue.

The old link was : 
`pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Teal.xaml`

The new is :
`pack://application:,,,/MaterialDesignColors;component/Themes/materialdesigncolor.teal.xaml`

**Comment by jespersh** [comment]
> The old link was :
> `pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Teal.xaml`
> 
> The new is :
> `pack://application:,,,/MaterialDesignColors;component/Themes/materialdesigncolor.teal.xaml`

Those two files are for quite different things however. 
See:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignColors.Wpf/Themes/Recommended/Primary/MaterialDesignColor.Teal.xaml (which pulls the next one though)
and
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.Teal.xaml
