### ISSUE TITLE
Why the style of Expander  isn't same with demo's?

### ISSUE THREAD

**Issue by younibugudano** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1110]
my demo:
![image](https://user-images.githubusercontent.com/34259213/48310174-a5a1df80-e5c4-11e8-8c38-a1cdd006eb1c.png)

The official demo:
![image](https://user-images.githubusercontent.com/34259213/48310185-d255f700-e5c4-11e8-91b4-ad027e3760ae.png)
How can i do to change the style?

**Comment by younibugudano** [comment]
I have added it into App.Xaml，but it didn't work.Now I add it into UserControl.Xaml,it works !
thanks!

**Comment by jespersh** [comment]
To others having the idea of adding 
`<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />`
to a single usercontrol. Don't. It makes your program incredible slow as it includes all the substyles every time you want to use that usercontrol.
If anything add a single reference to the expander style:
`<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Expander.xaml" />`
And use the `MaterialDesignExpander` style on your expander (or use `<Style TargetType="{x:Type Expander}" BasedOn="{StaticResource MaterialDesignExpander}" />`)
