### ISSUE TITLE
link used in this repo are changed

### ISSUE THREAD

**Issue by ranjan-ranjan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1126]
https://materialdesignicons.com/ should be changed to https://material.io/design/iconography/

and http://www.google.co.uk/design/spec/style/color.html#color-ui-color-application should be changed to https://material.io/

**Comment by Keboo** [comment]
Fixed. Though the link for the icons is correct. We do use https://materialdesignicons.com/ as the source for the icons in this repository.

**Comment by ranjan-ranjan** [comment]
the website is not working. kindly check.

**Comment by ranjan-ranjan** [comment]
ok

I was saying that the official icon link would have been better
