### ISSUE TITLE
PasswordBox.Password loses its content

### ISSUE THREAD

**Issue by YoussefRaafatNasry** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1129]
PasswordBox.Password **loses** its content after using **NavigationService.Navigate()** and Navigating to a new page.

I know that this problem is related to the PasswordBox control itself, not the MaterialDesignInXamlToolkit, due to **security** issues.

Is there any other way to override those security issues? Like adding **PasswordChar** property to **TextBox** control _or any other minimal solutions for small projects_.

[Example Repo](https://github.com/MichaelSafwatHanna/fitness-and-weight-loss-app)

![fitness-app-25_11_2018-9_03_59-pm_trim](https://user-images.githubusercontent.com/41103290/48983427-534ddc00-f0f7-11e8-9892-5453050106dd.gif)

**Comment by jespersh** [comment]
Might be obvious to you why you're having issues when I ask this, but I don't see a model that you're binding your input data to? Consider making one and passing it to the navigation.

**Comment by YoussefRaafatNasry** [comment]
I am new to WPF, but I think it is hard to use data binding with PasswordBox as far as I know.

**Comment by MairwunNx** [comment]
@YoussefRaafatNasry Do not worry, this is not a problem! Firstly, there should be a loss of content in the passwordbox, I have never seen that the user could return his password, if he knows, he will enter it again, secondly, you can very simply save it in some variable and that’s all, it’s very simple especially you do not use the MVVM pattern, using the MVVM pattern, creating a persistent password may not be much more difficult, but if you have a good knowledge's pattern, it will not take long!

I also think that for your situation it is better to implement the system of accounts as in Google with a drop-down list of passwords and nicknames

**Comment by YoussefRaafatNasry** [comment]
Thanks @MairwunNx
