### ISSUE TITLE
Mahapps TabControl and MaterialDesignFont

### ISSUE THREAD

**Issue by ConiJB** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1131]
Hi,

not sure if this is a mahapps issue or a MaterialDesignInXamlToolkit issue:

I am using a simple MahApps.MetroWindow with only a TabControl in it. When I use
`FontFamily="{DynamicResource MaterialDesignFont}"` 
in the header, the application does not start, no error is thrown.
Removing the MaterialDesignFont from header solves it, the application starts normally. This happens only if a TabControl is in the view.

System:
VS2017
MaterialDesignThemes 2.5.0.1205
MaterialDesignColors 1.1.3
MaterialDesignThemes.MahApps 0.0.12
MahApps.Metro 1.6.5

Thanks!

**Comment by Keboo** [comment]
Hi @ConiJB can you post a sample project that reproduces the problem? Is there any information in the Visual Studio Output window?

**Comment by Keboo** [comment]
Hi @ConiJB thank you for the project. Sorry for the long delay, but I am not able to reproduce the issue from that project. Are you still experiencing it? 

![tabissue](https://user-images.githubusercontent.com/952248/49763307-1c440280-fc81-11e8-9181-1f16f68ce30c.gif)

**Comment by ConiJB** [comment]
Hi @Keboo , thanks for your reply. I am still experiencing it, but I found out it only happens to me in VS 2017, in VS 2015 it starts normally as you have shown. So I assume the issue is somehow connected to my Visual Studio installation.
As the workaround (just deleting the mentioned line) works fine for me, I think I can close this.
Sorry if I have wasted your time with this.
