### ISSUE TITLE
Material Design Styles for TabItems available?

### ISSUE THREAD

**Issue by DrKissko** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1135]
Hey guys, I got a short question.

I need for my application some Tab Items, but the standard C# WPF Style looks so bad beside my Material Design things. Is there already a Style for TabItems available? If yes, where can I find them?

Thanks for your help.

**Comment by Keboo** [comment]
Hi @DrKissko what you are looking for is [Dragablz](https://github.com/ButchersBoy/Dragablz)

**Comment by DrKissko** [comment]
Thanks a lot @Keboo . :)

**Comment by jespersh** [comment]
Otherwise see this gist: https://gist.github.com/jespersh/7a9d68b5e88057b2edb767a112e48c5a
It is something I should credit for someone else, but I forgot who
