### ISSUE TITLE
Slider visualizes selection range always in slider center

### ISSUE THREAD

**Issue by Maradaehne** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1137]
I tried to use a slider with the standard feature IsSelectionRangeEnabled="true". As long as I am not using material design package the selection range will be shown properly, but when I use material design the selection range color visualization is only in the middle of the slider, although the range ticks are shown correctly.

See following images
![defaultslider](https://user-images.githubusercontent.com/25588591/49584178-babb2580-f95a-11e8-8855-e27b883c75e2.PNG)
![slidermaterialdesign](https://user-images.githubusercontent.com/25588591/49584204-d1fa1300-f95a-11e8-881d-e8211abe197b.PNG)

 
How to reproduce. Use the following code in a view and use material design package.
 
```
         <Slider
            x:Name="PowerSlider"
            Margin="8"
            DockPanel.Dock="Left"
            IsSelectionRangeEnabled="True"
            Maximum="28.8"
            Minimum="0"
            SelectionEnd="22.3"
            SelectionStart="12.5"
            TickPlacement="BottomRight"/>
```

**Comment by Keboo** [comment]
MD specification [here](https://material.io/design/components/sliders.html)
