### ISSUE TITLE
Cannot derive PopupBox button Style

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1138]
The PopupBox includes [an alternate button style and template](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L72-L122).
The issue is that you cannot easily extend this style.

Consider the following example:
```XAML
<materialDesign:PopupBox>
    <StackPanel>
        <Button Content="Button 1" />
        <Button Content="Text 2">
            <Button.Style>
                <Style TargetType="Button" BasedOn="{StaticResource {x:Type Button}}">
                    <Setter Property="Foreground" Value="Red" />
                </Style>
            </Button.Style>
        </Button>
    </StackPanel>
</materialDesign:PopupBox>
```
Produces:
![image](https://user-images.githubusercontent.com/952248/49676765-f4119500-fa2f-11e8-80d7-ec8546d302f1.png)

To fix this issue:

- [ ] Extract the current [button style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L72-L122) and move it inside of the parent ResourceDictionary (the root resource dictionary in that same file). This style should be given the key `MaterialDesignPopupBoxButton`.

- [ ] Back inside of the `<wpf:Card.Resources>` (where the button style was originally), add a new implicit button style that is based on `MaterialDesignPopupBoxButton`. 
```XAML
<Style TargetType="Button" BasedOn="{StaticResource MaterialDesignPopupBoxButton}" />
```

- [ ] Add a couple buttons to [the bottom of the popup box in the demo application](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Buttons.xaml#L115-L155). One of these button should derive from the new `MaterialDesignPopupBoxButton` style. Something like this:
```XAML
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition />
        <ColumnDefinition />
    </Grid.ColumnDefinitions>
    <Button Content="_Cancel">
        <Button.Style>
            <Style TargetType="Button" BasedOn="{StaticResource MaterialDesignPopupBoxButton}">
                <Setter Property="Foreground" Value="Red" />
            </Style>
        </Button.Style>
    </Button>
    <Button Content="_Save" />
</Grid>
```

**Comment by federicodesia** [comment]
How can I solve that?

**Comment by federicodesia** [comment]
How I can solve that?

**Comment by Keboo** [comment]
@federicodesia there is an example of doing so [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Buttons.xaml#L428-L434)
