### ISSUE TITLE
Easier way to disable duplicate check in SnackbarMessageQueue

### ISSUE THREAD

**Issue by Tyrrrz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1140]
I would like to show notifications that may repeat but I don't want any of them ignored. Currently I can use one of the overloads of the Enqueue method but it's very inconvenient. I would prefer to be able to enable/disable on the queue itself.

**Comment by Keboo** [comment]
I am not opposed to this improvement if someone wants to implement it.
I see it needing the following:

- [ ] Add a new boolean property on SnackbarMessageQueue called `IgnoreDuplicate` 
- [ ] In `SnackbarMessageQueue.PumpAsync` check this new property just like we check the `IgnoreDuplicate` property on the `SnackbarMessageQueueItem`

**Comment by Tyrrrz** [comment]
Okay when I went to implement this, I realized my original problem was completely different!

So it appears that the duplicates are ignored even some time after the last message was shown (the duration is actually `_messageDuration` which is 1 sec by default I think).

So the following can happen:
1. Show notification "Hello world"
2. The notification shows
3. Some time passes
4. Notification hides
5. In the span of `_messageDuration` show the same notification again
6. Notification doesn't show even though nothing else is in queue.

I think it's a little counter-intuitive because in my app the message duration is set to 5 seconds and it's weird that during those 5 seconds duplicates are also ignored. I would imagine they should only be ignored as long as that message is currently being shown.

I tried to find something in material design specs regarding this but it looks like it doesn't touch this topic.
Do you agree this is an issue?

**Comment by Tyrrrz** [comment]
Here's the perpetrator: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/6e66b80e203cf25e5d66004484f56d33ab054125/MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs#L304

The `_latestShownItem` tuple contains the message itself and `DateTime` of when it was CLOSED. Which means this cheak -- `_latestShownItem.Item2 <= DateTime.Now.Subtract(_messageDuration)` will only be true if `DateTime.Now` is `_messageDuration` after the last message became invisible.

**Comment by Keboo** [comment]
-
