### ISSUE TITLE
Add Toast control

### ISSUE THREAD

**Issue by ElMaldithoDJ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1150]
I add a new Issue is because we've about all controls of Material Design and I have a cuestion **What we don't have a toast control in the library?**

**Comment by ahmedflix25** [comment]
try https://github.com/rafallopatka/ToastNotifications

**Comment by MairwunNx** [comment]
@ahmedflix25 he means toast control as:

![image](https://user-images.githubusercontent.com/39625750/50454324-d6ad5800-0957-11e9-9cf4-144f4988b6f0.png)

**Comment by ElMaldithoDJ** [comment]
Yes Some like that

**Comment by ElMaldithoDJ** [comment]
Sorry @ahmedflix25  https://github.com/rafallopatka/ToastNotifications I see the examples but that isn't the style I mean like @MairwunNx

**Comment by ElMaldithoDJ** [comment]
See here and the others [](https://materializecss.com/toasts.html#styling)

**Comment by ElMaldithoDJ** [comment]
Go to Materialize and see the example https://materializecss.com/toasts.html

**Comment by jespersh** [comment]
> Sorry @ahmedflix25 [rafallopatka/ToastNotifications](https://github.com/rafallopatka/ToastNotifications) I see the examples but that isn't the style I mean like @MairwunNx

Being WPF, weren't you able to style it?

**Comment by MairwunNx** [comment]
Yes, it easy to realization in WPF. But it be not bad if it be in library :). @jespersh

**Comment by Keboo** [comment]
@ElMaldithoDJ what we do have in this library is the [Snackbar control](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Snackbars.xaml) it is not a perfect comparison to the toast examples that you have listed there. I think to add something like that to this library I would prefer to see an alternate style for the snackbar control and message. If someone wants to submit a PR for it I am happy to help review so it gets merged.

**Comment by ElMaldithoDJ** [comment]
@Keboo Ok I'll go to try dev it

**Comment by Keboo** [comment]
Closing or now as this is not a desired control to add for now.
