### ISSUE TITLE
TimePicker shows "0" instead of "24" in minutes and seconds in Demo application

### ISSUE THREAD

**Issue by tejas-thakar** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1153]
In "Demo Application," every time picker shows "0" in the tooltip at a place of "24"
![image](https://user-images.githubusercontent.com/46129605/50420379-05460880-085c-11e9-9956-cf8718e52ffa.png)
![image](https://user-images.githubusercontent.com/46129605/50420398-2575c780-085c-11e9-89c3-7a14cd35b190.png)

**Comment by jespersh** [comment]
Noticed it was the same as https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/775
