### ISSUE TITLE
Window Title Bar & Selected Text highlight color

### ISSUE THREAD

**Issue by hxhgxy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1162]
Question 1: Where is Name Space for "controls: MetroWindow"? How can I customize my MainWindow title bar color and border color?

Question 2: How to customized the background color of selected text in textfield (textbox, combobox...)?

Thanks a lot!

Tiger

**Comment by MairwunNx** [comment]
Hello @hxhgxy,

You can customize the background color of selected text in textfield: `SelectionBrush="Aqua"`

**Comment by hxhgxy** [comment]
Thank you MairwunNx!

**Comment by MairwunNx** [comment]
No problem @hxhgxy!

**Comment by Keboo** [comment]
@hxhgxy in regard to your first question that MetroWindow comes from [MahApps](https://mahapps.com/). There is an [additional NuGet package](https://www.nuget.org/packages/MaterialDesignThemes.MahApps/) provided by this library that adds additional styling to the MahApps controls. This is what is being used in the MahApps demo.

**Comment by hxhgxy** [comment]
@Keboo Thanks! 
But it is a DLL? I cannot view the source code and learn how to make it?

**Comment by hxhgxy** [comment]
![nupkg](https://user-images.githubusercontent.com/37101628/51081016-ecc16380-1720-11e9-8511-afe28b79fae3.PNG)

**Comment by hxhgxy** [comment]
I downloaded "MahApps.Metro.2.0.0-alpha0186.nupkg" and find these - looklike MetroWindow is the key codes?

![nupkg](https://user-images.githubusercontent.com/37101628/51081153-17f98200-1724-11e9-83e6-8a81fc68949d.PNG)
![nupkg2](https://user-images.githubusercontent.com/37101628/51081155-18921880-1724-11e9-9ca7-552a08d28cb5.PNG)

**Comment by Keboo** [comment]
@hxhgxy [MetroWindow](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/MetroWindow.cs) comes from the [MahApps library](https://github.com/MahApps/MahApps.Metro) you can see the source code for MahApps on [that repository](https://github.com/MahApps/MahApps.Metro).

**Comment by hxhgxy** [comment]
@Keboo Do you know where is source code for ControlzEx.dll?
thanks a lot!

**Comment by hxhgxy** [comment]
@Keboo Thank you!
I downloaded the MetroWindow and ControlzEx source codes. Look forward to learn...
