### ISSUE TITLE
How to create rounded corner button

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1165]
How can i create rounded corner button based on material design styles?

like this:
![rounded corner button](https://raw.githubusercontent.com/dmytrodanylyk/circular-progress-button/dev/screenshots/usage-6.png)

**Comment by MairwunNx** [comment]
If you code with intellisence, try type "uni" or "corner", I 100% know what it exists, but I forgot property name.

**Comment by dhilmathy** [comment]
I believe, there is a no property exposed for this. It's set to `2` by default.

Button Style: [MaterialDesignTheme.Button.xaml#L56](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L56)

**Comment by AlbertAlonso** [comment]
With the addition of ButtonAssist.CornerRadius shouldn't this question be closed? Or at least updated?

**Comment by syserr0r** [comment]
Has `ButtonAssist:CornerRadius` not made it to the nuget release yet as I'm getting `The property 'ButtonAssist.CornerRadius' does not exist in XML namespace 'http://materialdesigninxaml.net/winfx/xaml/themes'.`?

**Comment by Keboo** [comment]
Sorry all, yes this will be fixed in the 2.6.0 release. I have adjusted the milestone. 

@syserr0r you can download the latest preview nuget packages to get access to the new ButtonAssist.CornerRadius

**Comment by syserr0r** [comment]
Wow, thank-you for that fast response -- I'd just checked the commits and figured that out at the same time you posted this.
