### ISSUE TITLE
Some resources are missing in latest version

### ISSUE THREAD

**Issue by Leisvan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1167]
Hi
In latest version (2.5.0.1205) my project can't resolve some resources. 
- MaterialDesignTextAreaTextBox
- MaterialDesignTextFieldBoxTextBox

Maybe there are other resources missing but these aren't present for me. Maybe the names changed?
Thanks for this amazing project

**Comment by Keboo** [comment]
Hi @Leisvan 
These should be:
- `MaterialDesignOutlinedTextFieldTextBox`
- `MaterialDesignFilledTextFieldTextBox`

For more details see PR #840

**Comment by Leisvan** [comment]
Thanks!
