### ISSUE TITLE
Can't Install  on WPF  project that use .net framework 4

### ISSUE THREAD

**Issue by li-zheng-hao** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1168]
![image](https://user-images.githubusercontent.com/22129824/51157135-7f950600-18b9-11e9-90e7-0058e7064e70.png)

Does it not support this version?（when i change to .net framework 4.5 ,it works well）

**Comment by Keboo** [comment]
@li-zheng-hao no .NET 4.0 is not supported. See the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Visual-Studio-Versions-&-.Net-4.0-Compatibility) for more details.
