### ISSUE TITLE
Wpf use in Winform

### ISSUE THREAD

**Issue by ByErdem** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1169]
Hello,
I'm using MaterialDesignThemes in Xaml  usercontrol and I want to add wpf to Windows Form. But I getting error associated with InitializeComponent. Also you can examine this example. Con you find a solution for me. Thank you in advance. https://drive.google.com/open?id=1_tSFFbSdYO8Yy69nHC9CvP33xkqxSV7q

**Comment by MairwunNx** [comment]
You can't use MDIX library in WinForms. It another technology with a different ui render
