### ISSUE TITLE
Create powershell script to display all control styles in markdown

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1174]
It would be nice to be able to simply run a script to generate a markdown file with all of the control styles. The output of the script should be a markdown file that could be included in the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki)

The script should parse all of the files inside of the [Themes directory](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MaterialDesignThemes.Wpf/Themes) and build up a list of styles and the corresponding control. When parsing it should only consider Style elements and ignore ControlTemplates. 
Ideally I would like it to provide an indication of "(default style)" meaning the style that is applied to the control by default. This is indicated by a Style tag that does not explicitly specify an `x:Key` attribute. 

I would expect the output to look something like this (this is just a snippet for the DialogHost and Slider controls):
```markdown
## DialogHost
- (default style)
- MaterialDesignEmbeddedDialogHost

## Slider 
- MaterialDesignSlider (default style)
- MaterialDesignDiscreteSlider
```

**Comment by stigrune** [comment]
I can do this :)

**Comment by dhilmathy** [comment]
I just tried this,

``` powershell
$directory = "\GitRepos\MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\Themes"
$mdFile = $directory + "\Test.md"
$files = Get-ChildItem $directory -Filter *.xaml

$filesDict = @{}
foreach ($file in $files) {
    $file = $directory + "\" + $file
    [xml]$xmldata = Get-Content $file

    $styles = New-Object System.Collections.ArrayList
    foreach($style in $xmldata.ResourceDictionary.Style){
        if($style.Key -ne $null){
            [void]$styles.Add($style.Key)
        }
        else{
            [void]$styles.Add($style.TargetType + " (default style)")
        }
    }
    $controlName = (Get-Item $file).BaseName
    $controlName = $controlName.Replace("$($controlName.split(".")[0]).", "")
    $filesDict.Add($controlName, $styles)
}

$counter = 0 # To differentiate first item
foreach ($item in $filesDict.Keys) {
    if($filesDict[$item].Count -eq 0) {
        continue
    }
    $header = if ($counter++ -eq 0) {"## $($item)`n"} else {"`n## $($item)`n"}
    $styleKeys = "- $($filesDict[$item] -join "`n- ")"
    Out-File -FilePath ($mdFile) -InputObject "$($header)`n$($styleKeys)" -Append
}
```
P.S. I am completely new to **PowerShell** scripting.
