### ISSUE TITLE
Add information to the wiki home page for downloading

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1175]
Some of this information already exists on the README, but I think it is important to including it on the [Home page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Home) of the Wiki as well.

- [x] Add links to the three NuGet packages (MaterialDesignThemes, MaterialDesignColors, MaterialDesignThemes.MahApps)
- [x] Add link to the [Releases page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases) along with a description indicating that this is where you can download a compiled version of the demo app.

**Comment by rgomez90** [comment]
I've edited the wiki home page. Hope it's ok so😄

**Comment by Keboo** [comment]
LGTM. Thanks
