### ISSUE TITLE
Add documentation for using PackIcon

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1176]
The current [Using icons page on the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Using-icons) is very old and outdated. The library supports using the `PackIcon` class for setting these icons in a much simpler manner.

- [ ] Create a new PackIcon page for the wiki. It should include both a XAML and C# example of how to set the icon using the `Kind` property.
- [ ] Add the new PackIcon page to the [wiki sidebar](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/_Sidebar/_edit)
- [ ] Delete the old Using icons page, and remove reference to it from the wiki sidebar.

**Comment by rgomez90** [comment]
So it's done. Please take a look and if OK remove the `Using icons` page in `Archive`. If not Ok, please let me know what to change 😄

**Comment by Keboo** [comment]
@rgomez90 looking really good. Just a few small changes:

- On the side bar lets move it from the Miscellaneous section to the Controls section
- In the first code-behind example, lets also include the `using MaterialDesignThemes.Wpf;`
- Just to alleviate any confusion, lets fully qualify the `Brushes.Red` to be `System.Windows.Media.Brushes.Red`

**Comment by rgomez90** [comment]
@Keboo Done!

**Comment by Keboo** [comment]
Great work!
