### ISSUE TITLE
Right to Left Bugs - Combobox Control

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1184]
The material design ComboBox control not work properly in RTL direction
How can i fix this?
![Material Desing Combobox Control Issue](http://uupload.ir/files/sidh_1.png)

**Comment by ahmedflix25** [comment]
i can't reproduce this with the latest commit from the master branch in the demo project could you create a test repository with the problem 

![image](https://user-images.githubusercontent.com/7858946/52214945-a6809f80-289b-11e9-8cff-a9b938a9b869.png)

![image](https://user-images.githubusercontent.com/7858946/52214953-a8e2f980-289b-11e9-84a1-ca3aa13f9fc7.png)

**Comment by AmRo045** [comment]
I create a repository to reproduce this issue:

**[Sample Repository](https://github.com/AmRo045/MD_RtlComboBoxBug)**

Preview:

![Image](https://github.com/AmRo045/MD_RtlComboBoxBug/blob/master/1.PNG?raw=true)

**Comment by jespersh** [comment]
Please try with the master branch on here. Seeing your packages.config is version 2.5.0.1205

**Comment by ahmedflix25** [comment]
> 
> 
> Please try with the master branch on here. Seeing your packages.config is version 2.5.0.1205

it also happens with the latest commit from the master and i think it happens because the first item (or selected one ) in the drop down list is empty with Transparent background to show what's behind it in the combobox

![image](https://user-images.githubusercontent.com/7858946/52271575-b5735a80-294c-11e9-8dbe-0736143ea897.png)

![untitled](https://user-images.githubusercontent.com/7858946/52271670-fff4d700-294c-11e9-97ee-d8852cdd0fbc.png)

![image](https://user-images.githubusercontent.com/7858946/52271692-0f742000-294d-11e9-91b9-1df781d784da.png)

sorry but i have to say it
it's a feature not a bug

**Comment by Keboo** [comment]
@AmRo045 thank you for the repo project.
I am not able to reproduce your exact issue but there is some issues here that should be addressed.

Reproduction steps (works on latest demo app as well)
1. Set `FlowDirection="RightToLeft"` on the window.
2. Set `FlowDirection="LeftToRight"` on the ComboBox

Observed: The selected item disappears from view when the ComboBox's popup is open.
![rtl](https://user-images.githubusercontent.com/952248/52541208-4ed4af00-2d47-11e9-98d5-1e5a4dc3a193.gif)

After a little digging it appears the issues is with the ComboBoxPopup.VisiblePlacementWidth getting set to 0. It appears that the hit testing being down is making some assumptions about the flow direction and needs to be updated to properly handle this case.

**Comment by Madcheese101** [comment]
> @AmRo045 thank you for the repo project.
> I am not able to reproduce your exact issue but there is some issues here that should be addressed.
> 
> Reproduction steps (works on latest demo app as well)
> 
> 1. Set `FlowDirection="RightToLeft"` on the window.
> 2. Set `FlowDirection="LeftToRight"` on the ComboBox
> 
> Observed: The selected item disappears from view when the ComboBox's popup is open.
> ![rtl](https://user-images.githubusercontent.com/952248/52541208-4ed4af00-2d47-11e9-98d5-1e5a4dc3a193.gif)
> 
> After a little digging it appears the issues is with the ComboBoxPopup.VisiblePlacementWidth getting set to 0. It appears that the hit testing being down is making some assumptions about the flow direction and needs to be updated to properly handle this case.

unfortunately this problem just occurred to me in the latest version and the fix you provided in your last comment did not work for me at all :'(
