### ISSUE TITLE
TimePicker Goes Back to AM from PM!

### ISSUE THREAD

**Issue by shakir820** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1185]
Suppose you have a page. On that page, you have 2 TimePickers. Both are 2 way binding to two different properties (type of **DateTime**). And suppose one is set to 2 PM and another is set to 8 PM. If I want to set one of then to null value from code behind another one goes back to AM. 

Suppose you have set 2 PM property to null value the 8 PM property goes back to 8 AM. 
This is a big problem. Please fix this issue.

**Comment by jespersh** [comment]
This is fixed in 2.5.1 
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1096

**Comment by shakir820** [comment]
Really?

**Comment by Keboo** [comment]
Closing for now, as this appears fixed the latest 2.5.1 betas. If there is a still a problem after testing with the 2.5.1 preview NuGet packages please re-open.
