### ISSUE TITLE
Button Style TargetType='Button' BasedOn="{DynamicResource MaterialDesignButton}"

### ISSUE THREAD

**Issue by TinoTC93** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1186]
When trying to create style triggers on buttons the following shows up
' A 'DynamicResourceExtension' cannot be set on the 'BasedOn' property of type 'Style'.'

Here is xaml of button

 <Button Content="Test">
      <Button.Style>
          <Style TargetType="{x:Type Button}" BasedOn="{DynamicResource MaterialDesignButton}"/>
      </Button.Style>
</Button>

The following has been defined in the app.xaml level as well as the window level under 'Window.Resources'

NOTE: Changed 'Dynamic Resource' to 'StaticResource' and nothing changed.

  <ResourceDictionary>
                <ResourceDictionary.MergedDictionaries>
                    <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Button.xaml" />
                </ResourceDictionary.MergedDictionaries>
            </ResourceDictionary>

**Comment by AlexejLiebenthal** [comment]
If your new style depends on a style you only can use a `StaticResource`.

As I know there is no style with the key `MaterialDesignButton`, that should be the reason, why also `StaticResource` fails. Maybe try `MaterialDesignRaisedButton` or `MaterialDesignFlatButton` instead. Or take a look [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Button-Styles) for a button style you like to overwrite.

**Comment by Keboo** [comment]
@AlexejLiebenthal is correct. You must use a static resource not a dynamic one to base your style on. You can also find all of the latest button styles [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml)
