### ISSUE TITLE
Dialog Host Background Color

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1193]
How can i change Dialog host background color?

**Comment by AlexejLiebenthal** [comment]
There is unfortunately no direct/easy way to do this.

You only can set the background via DialogTheme DP to `Light` or `Dark`.

If you like to apply a custom background color you'll need to overwrite the template.
A good quick start is to look how @Keboo did this on the default style/template [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/80aee475368e31c58bf8579a5397d9a9c316487d/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DialogHost.xaml#L18).
You can than ignore most of the code there. Only focus on the `x:Name="PART_PopupContentElement"` Control and apply your changes their.

**Comment by AlexejLiebenthal** [comment]
:man_facepalming:
There is actually a much easier way for background.

Put a `Panel` like a `Grid` to your `DialogContent[-Template]` and set the `Panel.Background` to your custom color.

PS:
As you originally asked for `DialogHost`. I assuming that you meant the dialog which is showed.
The host can't have any color, as it is a host for your normal app content and the dialog content. It also gives you the possibility to control a dialog (open/close etc.).

**Comment by Keboo** [comment]
@AlexejLiebenthal is correct, and without going to the effort of re-tempting this is the best solution. It is worth noting that due to the rounded corners setting the background of the content of the dialog may result in a few pixels around the edge showing the theme (light/dark) color.
There is a new `ThemeAssist.Theme` attached properties that you can set on the DialogHost to change it from Dark/Light theme.

**Comment by RaoHammas** [comment]
@Keboo hey ! can i set somehow back color to transparent ? i mean back color of content host always show white color even if i set transparent. Or can i change opacity of that black mask container of content ? Please help me. Thanks

**Comment by RaoHammas** [comment]
![image](https://user-images.githubusercontent.com/16499626/61995223-d5cfd680-b09e-11e9-81c8-a1c126f19bc9.png)
