### ISSUE TITLE
MaterialDataGridComboBoxColumn Not Working With ListCollectionView

### ISSUE THREAD

**Issue by Spuddish** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1197]
Very Simple Issue:

When using a MaterialDataGridComboBoxColumn and binding to a ListCollectionView instead of a standard list<T> or an observablecollection<T> all of the instances of the MaterialDataGridComboBoxColumn in that datagrid are not displaying the correct value and instead are all showing the same value. If you select a new value in that combobox for one row then all other rows are duplicating that value. I have attached the most barebones sample I could make. Its just one window, with a datagrid and a single MaterialDataGridComboBoxColumn. The MaterialDataGridComboBoxColumn should have the values "1", "2", "3" in the example three rows generated but instead shows just "3" for all three rows.

[MaterialDesignTest.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/2902537/MaterialDesignTest.zip)

**Comment by Spuddish** [comment]
Here's the XAML/code in since a ZIP file is undesirable:

<Window x:Class="MaterialDesignTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MaterialDesignTest"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <DataGrid ItemsSource="{Binding Items}" AutoGenerateColumns="False" CanUserAddRows="False" CanUserDeleteRows="False">
            <DataGrid.Resources>
                <local:BindingProxy x:Key="bpMain" Data="{Binding}" />
            </DataGrid.Resources>
            <DataGrid.Columns>
                <materialDesign:MaterialDataGridComboBoxColumn Width="1*" Header="The Value!" SelectedValueBinding="{Binding Value}" DisplayMemberPath="Value" SelectedValuePath="Value" ItemsSource="{Binding Path=Data.ValueChoices,Source={StaticResource ResourceKey=bpMain}}" />
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
</Window>

public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MainWindowViewModel();
        }
    }

    public class MainWindowViewModel
    {
        public MainWindowViewModel()
        {
            this.Items = new ObservableCollection<MainWindowItem>();
            this.Items.Add(new MainWindowItem() { Value = "1" });
            this.Items.Add(new MainWindowItem() { Value = "2" });
            this.Items.Add(new MainWindowItem() { Value = "3" });

            var choicesList = new List<MainWindowItemChoice>();
            choicesList.Add(new MainWindowItemChoice() { Value = "1" });
            choicesList.Add(new MainWindowItemChoice() { Value = "2" });
            choicesList.Add(new MainWindowItemChoice() { Value = "3" });

            CollectionView choicesView = new ListCollectionView(choicesList);

            this.ValueChoices = choicesView;
        }

        public ObservableCollection<MainWindowItem> Items { get; set; }
        
        public System.Collections.IEnumerable ValueChoices { get; set; }
    }

    public class MainWindowItem
    {
        public string Value { get; set; }
    }

    public class MainWindowItemChoice
    {
        public string Value { get; set; }
    }

    public class BindingProxy : System.Windows.Freezable
    {
        #region Overrides of Freezable

        protected override System.Windows.Freezable CreateInstanceCore()
        {
            return new BindingProxy();
        }

        #endregion

        public object Data
        {
            get { return (object)GetValue(DataProperty); }
            set { SetValue(DataProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Data.  This enables animation, styling, binding, etc...
        public static readonly System.Windows.DependencyProperty DataProperty =
            System.Windows.DependencyProperty.Register("Data", typeof(object), typeof(BindingProxy), new System.Windows.UIPropertyMetadata(null));
    }

**Comment by Spuddish** [comment]
Here's the XAML / Code from the ZIP since no one is replying:

`<Window x:Class="MaterialDesignTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MaterialDesignTest"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <DataGrid ItemsSource="{Binding Items}" AutoGenerateColumns="False" CanUserAddRows="False" CanUserDeleteRows="False">
            <DataGrid.Resources>
                <local:BindingProxy x:Key="bpMain" Data="{Binding}" />
            </DataGrid.Resources>
            <DataGrid.Columns>
                <materialDesign:MaterialDataGridComboBoxColumn Width="1*" Header="The Value!" SelectedValueBinding="{Binding Value}" DisplayMemberPath="Value" SelectedValuePath="Value" ItemsSource="{Binding Path=Data.ValueChoices,Source={StaticResource ResourceKey=bpMain}}" />
            </DataGrid.Columns>
        </DataGrid>
    </Grid>
</Window>`

public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MainWindowViewModel();
        }
    }

    public class MainWindowViewModel
    {
        public MainWindowViewModel()
        {
            this.Items = new ObservableCollection<MainWindowItem>();
            this.Items.Add(new MainWindowItem() { Value = "1" });
            this.Items.Add(new MainWindowItem() { Value = "2" });
            this.Items.Add(new MainWindowItem() { Value = "3" });

            var choicesList = new List<MainWindowItemChoice>();
            choicesList.Add(new MainWindowItemChoice() { Value = "1" });
            choicesList.Add(new MainWindowItemChoice() { Value = "2" });
            choicesList.Add(new MainWindowItemChoice() { Value = "3" });

            CollectionView choicesView = new ListCollectionView(choicesList);

            this.ValueChoices = choicesView;
        }

        public ObservableCollection<MainWindowItem> Items { get; set; }
        
        public System.Collections.IEnumerable ValueChoices { get; set; }
    }

    public class MainWindowItem
    {
        public string Value { get; set; }
    }

    public class MainWindowItemChoice
    {
        public string Value { get; set; }
    }

    public class BindingProxy : System.Windows.Freezable
    {
        #region Overrides of Freezable

        protected override System.Windows.Freezable CreateInstanceCore()
        {
            return new BindingProxy();
        }

        #endregion

        public object Data
        {
            get { return (object)GetValue(DataProperty); }
            set { SetValue(DataProperty, value); }
        }

        // Using a DependencyProperty as the backing store for Data.  This enables animation, styling, binding, etc...
        public static readonly System.Windows.DependencyProperty DataProperty =
            System.Windows.DependencyProperty.Register("Data", typeof(object), typeof(BindingProxy), new System.Windows.UIPropertyMetadata(null));
    }

**Comment by Spuddish** [comment]
This bug is a critical issue. Please respond.

**Comment by jespersh** [comment]
There is something weird going on when using MDIX's `MaterialDataGridComboBoxColumn` instead of `DataGridComboBoxColumn` here, but I am unable to tell you what it is

**Comment by strongbutgood** [comment]
I've just run into this issue myself and it is very odd indeed.

The classic WPF styling is

```
  <Style x:Key="{x:Static DataGridComboBoxColumn.TextBlockComboBoxStyleKey}" TargetType="{x:Type ComboBox}">
    <Setter Property="Template">
      <Setter.Value>
        <ControlTemplate TargetType="{x:Type ComboBox}">
          <ContentPresenter Margin="1,1,1,1" Content="{TemplateBinding SelectionBoxItem}" ContentTemplate="{TemplateBinding SelectionBoxItemTemplate}" ContentTemplateSelector="{TemplateBinding ItemTemplateSelector}" ContentStringFormat="{TemplateBinding SelectionBoxItemStringFormat}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}" HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}" IsHitTestVisible="False" />
        </ControlTemplate>
      </Setter.Value>
    </Setter>
  </Style>
```

The MDIX styling has the content presenter at its core, essentially the same.

```
<ContentPresenter x:Name="contentPresenter" ContentTemplate="{TemplateBinding SelectionBoxItemTemplate}" ContentTemplateSelector="{TemplateBinding ItemTemplateSelector}" Content="{TemplateBinding SelectionBoxItem}" ContentStringFormat="{TemplateBinding SelectionBoxItemStringFormat}" HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}" IsHitTestVisible="false" Margin="{TemplateBinding Padding}" SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}" VerticalAlignment="{TemplateBinding VerticalContentAlignment}"/>
```

I can replicate the same behaviour though by using a vanilla DataGridComboBoxColumn and setting the `ElementStyle` to `MaterialDesignDataGridComboBoxTemplate` so I think it sits in there.

**Comment by rzgthb** [comment]
This behavior is probably caused by a missing default property setting for the ComboBox: [IsSynchronizedWithCurrentItem](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.selector.issynchronizedwithcurrentitem?view=windowsdesktop-7.0).

In the base implementation for DataGridComboBoxColumn, this property is set to false. In MDIX' implementation, this property is not set, therefore null, causing all combo boxes sharing the same CollectionView to display the same values and passing them to their bound value properties.

I used the following code to set the property set to false (the other two properties are part of the MDIX DefaultElementStyle used for the DataGridComboBoxColumn overrides) :


```
<DataGridComboBoxColumn.ElementStyle>
    <Style
        TargetType="{x:Type ComboBox}"
        BasedOn="{StaticResource MaterialDesignDataGridComboBox}">
        <Setter
            Property="IsSynchronizedWithCurrentItem" Value="False"/>
         <Setter
            Property="Focusable" Value="False" />
         <Setter
            Property="IsHitTestVisible" Value="False"/>
    </Style>
</DataGridComboBoxColumn.ElementStyle>
```

IMHO, this property settings needs to be included in MDIX' MaterialDesignDataGridComboBox.

Regards

**Comment by nicolaihenriksen** [comment]
> IMHO, this property setting needs to be included in MDIX' MaterialDesignDataGridComboBox.

Would you be up for opening a pull request with the change?

Also, is this only needed on the `DataGridComboBoxColumn.ElementStyle` or is a similar change needed for the `DataGridComboBoxColumn.EditingElementStyle`?

**Comment by rzgthb** [comment]
I am pretty sure that the change needs to apply for the editing template, too. One could easily create a situation where multiple combo boxes are in edit mode at the same time, for example a custom row edit mode. 

Since both styles are derived from the same style (MaterialDesignDataGridComboBox), it should suffice to add the change there.
[01_MaterialDesignDataGridComboBox.patch](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/11578790/01_MaterialDesignDataGridComboBox.patch)

As for creating a pull request, i have not done so before on GitHub and am not familiar with any of the processes involved. I have, however, attached a patch file containing the change which is required in my opinion.

**Comment by nicolaihenriksen** [comment]
@rzgthb I added the PR based on your patch file. Feel free to edit the description or add comments as you see fit.

**Comment by rzgthb** [comment]
@nicolaihenriksen Thank you, i have added description.
