### ISSUE TITLE
Modify button corner radius 

### ISSUE THREAD

**Issue by dannythegreat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1200]
Hello, 
I have used this very useful library, but I need only one thing, change the border radius of my button.
I have tried by <style> in app.xaml but don't work.

For standard button, how can I reach the property "corner radius"? Am I wrong to write the style. Someone can help me?

```
  <Style x:Key="Button" TargetType="{x:Type ButtonBase}" BasedOn="{StaticResource Button}">
                <Setter Property="Template">                  
                    <Border CornerRadius="0" x:Name="border"/>  
                </Setter>
            </Style>
```

**Comment by Keboo** [comment]
Unfortunately the button really doesn't expose [that property](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L56). This really leaves you with only two choice.
1. Copy the [entire control style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L31-L99) into your project, and modify it to suit your needs.
2. After the control is loaded walk through the [VisualTree](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/trees-in-wpf#the-visual-tree) until you find the correct element and modify it. You can see an example of that [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Button/Button.CornerRadius)

**Comment by dannythegreat** [comment]
Thank you, but I tried your solution and I have these errors related to "value; resources; modifierColletion; Modifier" (in italian):

```
Error	XLS0415	La proprietà associabile 'Value' non è stata trovata nel tipo 'Modifier'.
Error	XDG0012	Il membro "Resources" non è riconosciuto oppure non è accessibile.
Error	XLS0415	La proprietà associabile 'Resources' non è stata trovata nel tipo 'Window'.
Error	XLS0414	Il tipo 'utilities:ModifierCollection' non è stato trovato. Verificare che sia presente un riferimento a un assembly e che tutti gli assembly di riferimento siano stati compilati.
Error	XLS0414	Il tipo 'utilities:Modifier' non è stato trovato. Verificare che sia presente un riferimento a un assembly e che tutti gli assembly di riferimento siano stati compilati.
```

**Comment by Keboo** [comment]
That example is leveraging some utility code that [is in this project](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Utilities/Utilities). It is basically just a XAML friendly way to parse the visual tree and make replacements.

**Comment by Keboo** [comment]
This is resolved with the `ButtonAssist.CornerRadius` attached property
