### ISSUE TITLE
How to save Theme, Accent in Settings WPF w Material Design

### ISSUE THREAD

**Issue by sammyas12** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1201]
WPF with Material Design use Theme and Accent Palette to change in runtime.
How can I save it?

**Comment by ahmedflix25** [comment]
in the demo app class PaletteSelectorViewModel there this methods "ApplyAccent(Swatch swatch)" and "ApplyPrimary(Swatch swatch)" that you can use with "swatch.Name" to get the current selected color

**Comment by Keboo** [comment]
There are now ITheme classes that you can access and serialize/restore to persist your desired theme settings.
