### ISSUE TITLE
PopupBox inside DataGridTemplateColumn CellTemplate

### ISSUE THREAD

**Issue by avechuche** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1204]
Hello, I have a popup box inside a cell that works correctly. 

This is my code.
```
<DataGridTemplateColumn.CellTemplate>
	<DataTemplate>
		<StackPanel Orientation="Horizontal"
					HorizontalAlignment="Center">
			<materialDesign:PopupBox StaysOpen="False" PlacementMode="BottomAndAlignRightEdges">
				<materialDesign:PopupBox.Style>
					<Style TargetType="{x:Type materialDesign:PopupBox}">
						...
					</Style>
				</materialDesign:PopupBox.Style>
					<StackPanel>
						<Button />
						<Button />
						<Button />
						<Button />
					</StackPanel>
			</materialDesign:PopupBox>
		</StackPanel>
	</DataTemplate>
</DataGridTemplateColumn.CellTemplate>
```

Now, I need to remove the focus of the button

![image](https://user-images.githubusercontent.com/11781418/53999935-2e202f00-4124-11e9-9538-ad5272b07714.png)

I follow this example
https://github.com/Keboo/MaterialDesignInXaml.Examples/blob/master/PopupBox/Popupbox.RemoveFocusVisual/MainWindow.xaml (If you download the example, you can see that it does not remove the focus and when you open the popup the content is not the real one.)

When I want to adapt the example to my code, nothing works. The focus is not removed, and when I click on the button, the popup opens, but as content it has a string with the complete path of the 'Modifier' assembly :(.  **materialDesign:PopupBox.Content** does not work? What is the problem? Thank you!

New code

```
<DataGridTemplateColumn.CellTemplate>
	<DataTemplate>
		<StackPanel Orientation="Horizontal"
					HorizontalAlignment="Center">
			<materialDesign:PopupBox StaysOpen="False" PlacementMode="BottomAndAlignRightEdges">
				utilities:Modifier TemplatePartName="PART_Toggle"
                                                            Property="{x:Static FrameworkElement.FocusVisualStyleProperty}"
                                                            Value="{x:Null}" />
				<materialDesign:PopupBox.Style>
					<Style TargetType="{x:Type materialDesign:PopupBox}">
						...
					</Style>
				</materialDesign:PopupBox.Style>
				<materialDesign:PopupBox.Content>
					<StackPanel>
						<Button />
						<Button />
						<Button />
						<Button />
					</StackPanel>
				</materialDesign:PopupBox.Content>
			</materialDesign:PopupBox>
		</StackPanel>
	</DataTemplate>
</DataGridTemplateColumn.CellTemplate>
```

**Comment by jespersh** [comment]
Remove or just hide?
`FocusVisualStyle="{x:Null}"` might hide it

**Comment by avechuche** [comment]
Thanks for the reply. I already tried that, but it does not work. Keebo gave me an explanation of why it does not work (I can not find it), that's why he created the example.

**Comment by Keboo** [comment]
@avechuche sorry, my initial sample was incorrect. The `Modifier` object is only expected to be used inside of the tree helper. I have [updated the example](https://github.com/Keboo/MaterialDesignInXaml.Examples/commit/ac27092af720db7df7d02e41e647b85740fa278d).

**Comment by Keboo** [comment]
Closing for now as there is an example working around to get the desired look.
