### ISSUE TITLE
Dialog Host - Update Content Issue after commit on Jan 20, 2019

### ISSUE THREAD

**Issue by Tide** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1212]
After the commit on January 20, 2019 I am having an issue with updating the content of the dialog host.

Here is a link to the [commit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/eb472bb8bce7cb7dad2d47a6314b8faa334514ee).

After I call `eventArgs.Session.UpdateContent(SomeViewModel);` it goes to the view but the ClosingEventHandler will not fire again after the update like it used to.

Is there a new way to update the content since this change so you get a closing event after you update or is this an issue to be resolved?

**Comment by Tide** [comment]
I have created a sample repo to illustrate the issue. Both projects are the same except one uses MaterialDesignThemes.Wpf.dll version 2.5.1-ci1286 and the other MaterialDesignThemes.Wpf.dll version 2.5.1-ci1292.

UpdateContentDemo - 2.5.1-ci1286 - Works as expected
UpdateContentDemo - 2.5.1-ci1292 - Does not work as expected

You can access the repo [here](https://github.com/Tide/UpdateContentDemo)

To use the demo:
1. Click the "Show Dialog" button to open the Main Dialog
          - On the next screen you have 2 options: Save or Close
          - In this example assume you are editing something and you have made changes.
          - If you save you just go back to the main screen.
          - If you close you will be asked to "Save Changes".
2. Click the "Close" button
          - You will now be asked to "Save Changes"
          - Click "Yes" and it will save and take you back to the main screen
          - Click "No" and it will just take you back to the main screen
          - Click "Cancel" and you will go back to the Main Dialog
3. Click the "Cancel" button to back to the Main Dialog
           - Now that you are back remember we still have unsaved changes
           - Here is where it breaks with the 2 examples
           - In step 4 we are going to click "Close" button again
           **- In the working example you will be asked to again save the unsaved changes.
           - In the broken example the MainDialog will just close and go back the Main Window**
           - It seems that the new way does not let my MainDialogClosingEventHandler fire after the first time.
4. Click the "Close" button
           - You will get different results with each demo

**Comment by Keboo** [comment]
@Tide thanks you for the reproduction projects and clean bug report. I also appreciate you testing the preview packages. This is very helpful.

The issue is actually the canceling of the dialog, not the updating of the content.

I have fixed the issue and added a unit test to ensure this does not happen again.
