### ISSUE TITLE
Add option to change the validation error message font size.

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1217]
Currently the validation error message are hard coded to a FontSize of 10. 
We should add a [ValidationAssist](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e44b53f693cf05e1776066fb59b572bb008ecc10/MaterialDesignThemes.Wpf/ValidationAssist.cs) attached property to allow this valid to be changed.

The following should be done:

- Create a new attached property in the [ValidationAssist class](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e44b53f693cf05e1776066fb59b572bb008ecc10/MaterialDesignThemes.Wpf/ValidationAssist.cs) called FontSize. Its default value should be 10.0.
- Apply this property to the [ValidationErrorTemplate](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e44b53f693cf05e1776066fb59b572bb008ecc10/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml). There are three places it should be applied.

**Comment by iinfernoz** [comment]
Hi, Thank you for you support. 

I've already done with your advice but it show error message "The property 'ValidationAssist.FontSize' does not exist in XML namespace 'http://materialdesigninxaml.net/winfx/xaml/themes'. Line 25 Position 17". How can I fix this?

Thank you

![ValidationRuleFontSize](https://user-images.githubusercontent.com/22215264/55371138-50407d80-5527-11e9-93f7-5e638a503ed7.PNG)

**Comment by Keboo** [comment]
@iinfernoz this is because `ValidationAssist.FontSize` does not exist yet. This issue is a request for it to be added.

**Comment by Mrxx99** [comment]
@Keboo Since #1218 is merged, I guess this issue can be closed.
