### ISSUE TITLE
Combobox item border

### ISSUE THREAD

**Issue by GAMP** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1219]
Can somebody point out why i see the border on right and bottom ?
Tried all kind of configuration and cant get rid of it.

![image](https://user-images.githubusercontent.com/4171664/55480832-c7f6d100-5629-11e9-9535-df00dadd4e41.png)

and the xaml

`       <ComboBox Grid.Row="0"
                                  IsEnabled="{Binding RequiresCash}"
                                  Margin="2"
                                  Background="{StaticResource PrimaryHueDarkBrush}"
                                  Foreground="{StaticResource PrimaryHueDarkForegroundBrush}"
                                  Style="{StaticResource MaterialDesignFloatingHintComboBox}"
                                  Padding="8"
                                  md:HintAssist.Hint="{lex:LocText Key=PRODUCT_ORDER_PAYMENT_METHOD}"
                                  md:HintAssist.FloatingScale="1"
                                  md:ComboBoxAssist.ShowSelectedItem="False"
                                  IsEditable="False"
                                  IsReadOnly="True"
                                  DataContext="{Binding Order}"
                                  SelectedValue="{Binding PaymentMethodId}"
                                  SelectedValuePath="PaymentMethodId"
                                  ItemsSource="{Binding PaymentMethods}">
                            <ComboBox.ItemsPanel>
                                <ItemsPanelTemplate>
                                    <VirtualizingStackPanel />
                                </ItemsPanelTemplate>
                            </ComboBox.ItemsPanel>
                            <ComboBox.ItemTemplate>
                                <DataTemplate>
                                    <Grid Cursor="Hand">
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="Auto" />
                                            <ColumnDefinition  />
                                        </Grid.ColumnDefinitions>
                                        <md:PackIcon Kind="CurrencyUsd" Visibility="Visible" VerticalAlignment="Center" HorizontalAlignment="Center" />
                                        <TextBlock Grid.Column="1"
                                                   VerticalAlignment="Center"
                                                   HorizontalAlignment="Left"
                                                   Style="{StaticResource MaterialDesignSubheadingTextBlock}"  
                                                   Text="{Binding LocalizedName}" />
                                    </Grid>
                                </DataTemplate>
                            </ComboBox.ItemTemplate>
                        </ComboBox>`

**Comment by Xaalek** [comment]
DUP https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2308
