### ISSUE TITLE
ComboBox erretic rendering of selected item on high DPI scaling (150%)

### ISSUE THREAD

**Issue by jamesport079** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1224]
I'm having an issue with combobox dropdown menu when I open the dropdown menu of the combobox and vertical screen real estate is limited... the selected item renders erratically, showing the background instead of the currently selected item as you can see in the image below. I reproduced the problem in the Demo app itself. I'm getting this in Windows 10 on 150% scaling. I can confirm I'm not getting this on 100% DPI scaling. 

![image](https://user-images.githubusercontent.com/36583787/55675436-c5fb6f00-58c2-11e9-88a5-7419355276c9.png)

**Comment by jespersh** [comment]
200 DPI or 200% DPI?

**Comment by jamesport079** [comment]
sorry my mistake. It's 150% DPI setting on Windows 10.

**Comment by sdc224** [comment]
Yes I am also facing the same issue. My display settings are
<img width="960" alt="github_issue_material_design" src="https://user-images.githubusercontent.com/33570719/56361117-3039db00-6204-11e9-8528-72690441848d.png">
