### ISSUE TITLE
change context menu language

### ISSUE THREAD

**Issue by sammyas12** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1226]
How can you change the context menu language?
Sorry I did not realize that the image was not public.
![sss](https://user-images.githubusercontent.com/47604186/55887257-cf126780-5b72-11e9-8670-0d24a237dc89.png)

**Comment by MairwunNx** [comment]
Image not available. You restricted access.

**Comment by Keboo** [comment]
@sammyas12 can you paste the image directly into the issue? We would also want to know which control this is referencing.
As for changing the language you typically change the language at the application level. You can see an example of doing that [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml.cs)

**Comment by sammyas12** [comment]
> @sammyas12 can you paste the image directly into the issue? We would also want to know which control this is referencing.
> As for changing the language you typically change the language at the application level. You can see an example of doing that [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml.cs)

My application already has this configured but still it keeps appearing as shown in the image

**Comment by MairwunNx** [comment]
@sammyas12 Hello, Friend, I ask you to note that localization works separately for each **thread**, make sure that you change it from the same **thread** to which you want to apply. I had a similar problem, but not with the option like yours.

**Comment by Keboo** [comment]
@sammyas12 that is being caused because of the way that this library handles the context menu. I have added some [documentation to the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/TextBox#localization-and-spell-checking) on how you can modify it.

**Comment by sammyas12** [comment]
> @sammyas12 that is being caused because of the way that this library handles the context menu. I have added some [documentation to the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/TextBox#localization-and-spell-checking) on how you can modify it.

It was solved with the information you gave me, thank you very much.
![ss](https://user-images.githubusercontent.com/47604186/55982637-f47c9f80-5c5e-11e9-873c-dd6ba4516085.png)
