### ISSUE TITLE
Typo in PopUpBox Closed event summary

### ISSUE THREAD

**Issue by Drise13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1233]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2a978a80737e99b8bb2069fb791c828afdf8837f/MaterialDesignThemes.Wpf/PopupBox.cs#L376

The summary says the event is fired when the popup is opened, even though it is a close event.

**Comment by sooraj19** [comment]
@Drise13 , @Keboo : Can you please take a look into my PR for this issue.. Thanks..
