### ISSUE TITLE
MaterialDesignCardFlipper is not displayed in certain environments

### ISSUE THREAD

**Issue by andreas49** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1236]
We use MaterialDesignCardFlipper in our application, in most cases/environments without any problems.
But in a terminal server environment there is nothing displayed (everything is white like the background). 
If I use "inspect.exe" to find something, I can find every element, a click e.g. on a button placed on this control works.
Compared a running environment against the problematic one (Microsoft Windows Server 2008 R2 Enterprise, mstsc version: 6.3.9600.16415 (winblue_gdr_oob.131001-0952)):
Using "Material Design in XAML Toolkit", MaterialDesignDemo.exe in version Demo.2.5.1:
It seems that only the three examples of MaterialDesignCardFlipper on the right side in "Cards" are "white".
See screenshot:

![MaterialDesignCardFlipper_bad](https://user-images.githubusercontent.com/49677875/56204325-77c73800-6047-11e9-9ad4-a1475414c4b2.png)

Any idea?

**Comment by Keboo** [comment]
@andreas49 can you provide a little more information on these machines. Are these running as VMs? If some how are they hosted (Azure, VMWare, Citrix, etc)?

**Comment by Keboo** [comment]
Testing in Azure.
![image](https://user-images.githubusercontent.com/952248/56231365-214ffe80-6033-11e9-90d0-7f4e6289f299.png)

**Comment by andreas49** [comment]
Hello, 
the machines are thin clients connected to a Microsoft Windows Server 2008 R2 Enterprise as terminal server (client version: mstsc version: 6.3.9600.16415 (winblue_gdr_oob.131001-0952)).

**Comment by andreas49** [comment]
Hello @Keboo , any news on this? What is the special thing in this control to explain the strange behaviour?

**Comment by jespersh** [comment]
I was able to reproduce it on one of our test machines. 

Took a few info screens, although not sure there's any correlation.
![image](https://user-images.githubusercontent.com/1004198/57508758-b5477a00-7302-11e9-8108-944d70ea4962.png)

![image](https://user-images.githubusercontent.com/1004198/57508946-39016680-7303-11e9-9489-104d402a772b.png)

**Comment by Keboo** [comment]
I suspect this is actually a VMWare issue. The flipper control relies of being able to render to a Direct3D surface. In many VMs this is disabled by default.

Some links that may be relevant:
- https://communities.vmware.com/thread/603081
- https://communities.vmware.com/thread/236340
- https://www.vmware.com/support/ws5/doc/ws_vidsound_d3d_enabling_vm.html
- https://pubs.vmware.com/ws6_ace2/ws/wwhelp/wwhimpl/common/html/wwhelp.htm?context=ws&file=ws_vidsound_d3d_enabling_guestos.html

**Comment by Keboo** [comment]
Closing for now as this appears to be an issue that is outside the control of this library.
