### ISSUE TITLE
Button with drop down

### ISSUE THREAD

**Issue by Tyrrrz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1241]
Hi guys :)

So I was looking for anything similar in specification and looks like it isn't mentioned. What I want is a button that looks like this (taken from Gmail)

![image](https://user-images.githubusercontent.com/1935960/56666514-bd71a980-66b4-11e9-9d37-75f62417abdd.png)
![image](https://user-images.githubusercontent.com/1935960/56666531-c6627b00-66b4-11e9-8339-7be861dc4534.png)

You can see how the Send button has an arrow you can press that provides alternative options. It's important to note that the Send button can also be pressed like a regular button, it's not required that the drop down is shown.

I wonder if it's possible to add support for something like this, given it's not in official specs, albeit IMO very useful. If not, do you know of any UI design pattern I can use to replace this?

**Comment by Keboo** [comment]
Hi @Tyrrrz I would have to spend some time playing with it, but you might be able to get something working with some theming work on a button and a PopupBox. I am flagging this as an enhancement since I think something like this could be a nice addition to the library.

**Comment by Mrxx99** [comment]
If it helps, the xceed extended wpf toolkit has such a control (in the free version): https://github.com/xceedsoftware/wpftoolkit/wiki/SplitButton

**Comment by MichelMichels** [comment]
This has been implemented. See the buttons page in the demo app for more information.
