### ISSUE TITLE
Clean up Buttons page in demo app

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1250]
The button's page in the demo app is getting pretty crowded with all of the elements being displayed. This should be broken up into several pages to help keep things focused and organized.

I would suggest the following changes.

- [ ] Move the Rating bar control to their own page
- [ ] Move the Toggle controls to their own page
- [ ] Group the PopupBox control together under their own header. The Green (+) one shows off the over eager default setting. It would be nice if there were no controls directly below it since it effectively covers those up.
- [ ] Ensure that there are no button controls that hidden by the default window size. Right now there are several that you have to expand the window horizontally to see.

Helpful information:
- The list of pages in the demo app is [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Domain/MainWindowViewModel.cs#L17-L198).
- You will want to make sure the documentation links make sense on each page.
- Right now some of the button styles are hidden because they extend too far horizontally. I don't mind the views needing to scroll but would prefer if it were only a vertical scroll that was needed to view all of the controls.

I am happy to accept partial pull requests as well that only address a portion of this issue.

**Comment by Tide** [comment]
That should do it for the first 2 changes for now.  

I will try and get to 3 at some point.

What do you mean "Ensure that there are no button controls"?

**Comment by Keboo** [comment]
Thanks @Tide. That was the typo on my part. I have updated the description. Let me know if you have any other questions.

**Comment by Tide** [comment]
@Keboo Can you close this.  It was taken care of in #1253.

**Comment by Keboo** [comment]
O yep, sorry this was my mistake
