### ISSUE TITLE
System input method window position is incorrect

### ISSUE THREAD

**Issue by tianyu94** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1251]
![issuedemo](https://user-images.githubusercontent.com/37231629/57591075-29cc2400-7562-11e9-8476-31ee49287339.png)

the "input method window" always shown at the bottom.

Is there any way to solve this problem? thx~

this is my code, I just create a new proj by [Super Quick Start](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start)

```xaml
<materialDesign:DialogHost>
    <materialDesign:DialogHost.DialogContent>
        <StackPanel />
    </materialDesign:DialogHost.DialogContent>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
        </Grid.RowDefinitions>
        <StackPanel Grid.Row="0">
            <Button
                Width="128"
                Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"
                Content="PASS VIEW">
                <Button.CommandParameter>
                    <StackPanel Margin="16">
                        <StackPanel>
                            <TextBox />
                            <TextBox />
                            <TextBox />
                        </StackPanel>
                        <Button
                            HorizontalAlignment="Center"
                            Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}"
                            CommandParameter="Sample2Cancel"
                            Content="CANCEL"
                            IsCancel="True"
                            Style="{StaticResource MaterialDesignFlatButton}" />
                    </StackPanel>
                </Button.CommandParameter>
            </Button>
        </StackPanel>
    </Grid>
</materialDesign:DialogHost>
```

**Comment by Keboo** [comment]
@tianyu94 I am not familiar with that input method window. It does not appear to be anything that is built into windows. I suspect that is a third party program that is providing that window. This is likely outside the scope of this library as I suspect you will see identical behavior with any `TextBox` in a WPF application.

You might try leveraging the [InputLanaugeManager](https://docs.microsoft.com/dotnet/api/system.windows.input.inputlanguagemanager) or the [InputManager](https://docs.microsoft.com/dotnet/api/system.windows.input.inputmanager) classes.

**Comment by tianyu94** [comment]
In fact, this is the Chinese input method in the Windows 10 multi-language input method(System Settings -> Time & Language -> Language -> Chinese -> Microsoft Pinyin(Keyboards)).

I will try the method you recommended, thank you, :)

**Comment by a1292999652** [comment]
> 其实这就是Windows 10多语言输入法中的中文输入法（系统设置->时间&语言->语言->中文->微软拼音（键盘））。
> 
> 我会试试你推荐的方法，谢谢，:)

请问你解决了吗？

**Comment by qz347655378** [comment]
请问有解决方案吗

**Comment by tianyu94** [comment]
> 请问有解决方案吗

不好意思，这个也是我很久以前的一个项目了，你可以先尝试 Keboo 的方法。
