### ISSUE TITLE
Add, use, fix latest text field style (filled background container)

### ISSUE THREAD

**Issue by mr-at0s** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1257]
The appearance of text fields changed lately as you can find here: https://material.io/design/components/text-fields.html#
(Old style: https://web.archive.org/web/20170128204710/https://material.io/guidelines/components/text-fields.html)

Most obvious aspect is the grey background container (but there are some more differences).

![image](https://user-images.githubusercontent.com/28776933/58259654-409a2400-7d75-11e9-9ad5-91f7a59798b5.png)

Currently, MaterialDesignInXamlToolkit has got the filled text field, which doesn't look correctly and the interactions/animations does not look accurately.

![style-comparison](https://user-images.githubusercontent.com/28776933/58324689-dee6c200-7e27-11e9-80b5-0cfb2f913469.png)

Official Material Design Animation: [interaction video/animation](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1V4TTJr8n_fpZkdk4qQIqXB9vJhMegre3%2Ftextfields-filled-motion2.mp4)
- A click into the field should not start any kind of ripple (or etc.) effect. Just animate the underline.

**Comment by Xaalek** [comment]
And the animation has been changed https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2750

I think the style is pretty close to the specs now.

https://user-images.githubusercontent.com/54487782/181506745-6dc78672-637f-4e43-bbdb-94e4e1515d87.mp4

We just need to correct the validation style and I think we will be good: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2596
