### ISSUE TITLE
Combobox display issue when there are no items

### ISSUE THREAD

**Issue by Tide** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1261]
When you have a combobox with no items there is an issue the first time you click the drop down.

The control will disappear.  Then you click somewhere else (combobox closes) and the combobox appears. 

Then you can click the drop down arrow and the control will act as normal.

To reproduce add a combobox to the window and maybe give it width and that is it.
Run the application and click the combobox drop down arrow.

I am not sure where to begin looking on this one so if anyone has suggestions I am willing to look into it.

**Comment by Tide** [comment]
![d1xD6rGC3x](https://user-images.githubusercontent.com/237330/58365430-40dc1180-7e92-11e9-9b7b-11d92b0ff6ad.gif)

**Comment by LogikozRC** [comment]
I do not have this problem '-'

**Comment by Keboo** [comment]
@Tide I am able to reproduce the issue on a new project with version 2.5.1. The first click does not appear to show the popup, but subsequent clicks show as expected.
The code in my MainWindow looks like this:
```XAML
<Grid>
    <ComboBox HorizontalAlignment="Center" VerticalAlignment="Center" MinWidth="200" />
</Grid>
```

Since the ComboBox [uses a custom popup](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml#L457-L474) I suspect the issue lives [there](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs). I suspect what is happening is the popup is actually displaying but due to the lack of items, likely displays either off screen or with a size of 0.

**Comment by Tide** [comment]
Okay @keboo I will dig around a little and see if I can find something out.  I was going to have this scenario in my application but have since changed the design.  I do have my test app from the Gif so I will use that for testing.  Thanks for looking at it.

**Comment by Tide** [comment]
So far I see that on the first click none of the Dependency Properties of the ComboBoxPopup are being called.  So it looks like somewhere between clicking the button and calling the popup that something is bugging out.

**Comment by Tide** [comment]
As usual it looks like you have me on the right path.

1.1.1-ci332 | 270 | 11/18/2015 (Bug happens)
1.1.1-ci325 | 623 | 11/13/2015 (Bug does not happen)

It appears it is this commit that changed things:

Revision: 7add3e7394481e2acf71f503037f0a7444d398f4
Author: Artur
Date: 11/16/2015 5:28:40 PM
Message: Merge remote-tracking branch 'refs/remotes/ButchersBoy/master' into FixVirtualizingComboBox

That is when the ComboBoxPopup was added.  Still not sure yet where the bug happens.

**Comment by Tide** [comment]
It appears everything pops up fine.  What is not happening is there is no shadow around the popup on the first open.  Not sure why yet.

**Comment by Tide** [comment]
![9Gju0f3uEM](https://user-images.githubusercontent.com/237330/58445335-4e7bdc00-80ca-11e9-80e9-71c2082c6639.gif)

**Comment by Tide** [comment]
The first method called on [ComboBoxPopup](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs) when you click the drop down is [ComboBoxCustomPopupPlacementCallback](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs#L220-L247).  This does not get called on the first click.  My guess is whatever is occurring is outside of [ComboBoxPopup](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ComboBoxPopup.cs) or in the [Style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml) (I have looked through the style and not found anything so far).

**Comment by Tide** [comment]
Adding something into the template to take up space makes it work.  It appears that for some reason without something in there it will not call the ComboBoxPopup part.

I added this to the style to test and it worked fine (Not a solution!!). 
```
                    <ContentControl>
                        <ScrollViewer MaxHeight="{TemplateBinding MaxDropDownHeight}"
                                      Background="{Binding Background, ElementName=PART_Popup}">
                            <Grid>
                                <!--Adding the line below to take up space to test bug-->
                                <Border Height="1" Background="Transparent"></Border>
                                <ItemsPresenter x:Name="ItemsPresenter" KeyboardNavigation.DirectionalNavigation="Contained" />
                            </Grid>
                        </ScrollViewer>
                    </ContentControl>
```
