### ISSUE TITLE
UI display Error

### ISSUE THREAD

**Issue by snowiceyeah** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1267]
![image](https://user-images.githubusercontent.com/43429385/58796924-25f76300-8631-11e9-921f-e3ef0cd6481b.png)
I use card, and it shows some issue on display.

**Comment by jespersh** [comment]
Hi and welcome,

See https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1097#issuecomment-434996088

**Comment by Keboo** [comment]
@snowiceyeah I believe @jespersh is correct, that looks like a LayoutRounding issue. Let us know if this does not resolve the issue.
