### ISSUE TITLE
Datagrid have a wrong indentation

### ISSUE THREAD

**Issue by flier268** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1272]
DataGrid sometimes happen this issue(not always),
It have a wrong indentation
![image](https://user-images.githubusercontent.com/19989232/59011286-b66ab900-8866-11e9-82e7-cb42ef69d82a.png)

xaml:
```xml
<DataGrid Name="DataGrid_MeasureMent" ItemStringFormat="0:##;; " Grid.Row="1" Width="{Binding ElementName=TabControl_RightDown,Path=ActualWidth}" ItemsSource="{Binding}" MouseLeftButtonUp="DataGrid_MeasureMent_MouseLeftButtonUp" MouseDoubleClick="DataGrid_MeasureMent_DoubleClick" AutoGeneratingColumn="DataGrid_MeasureMent_AutoGeneratingColumn" Sorting="DataGrid_MeasureMent_Sorting"  ColumnWidth="SizeToCells" VirtualizingPanel.IsVirtualizing="True" ScrollViewer.IsDeferredScrollingEnabled="True" VerticalScrollBarVisibility="Auto" IsReadOnly="True" CanUserSortColumns="False" Margin="0,14,0,0" HorizontalAlignment="Left"/>
```
MaterialDesignThemes 2.5.1
MaterialDesignColors 1.1.3
.Net Framework 4.7.2
Win10 x64

**Comment by jespersh** [comment]
I was also meeting this strange issue, but I had initially forgotten about it again. It seems like a binding sometimes fails.
I did find this which suggests it might not be a issue limited to MDIX: https://stackoverflow.com/questions/13383046/strange-wpf-datagrid-behavior-little-button-like-nubbies-indenting-some-rows-ap
