### ISSUE TITLE
Light Text style

### ISSUE THREAD

**Issue by marekbe** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1273]
I have a problem with Light style for text elements (e.g. TextBlock, TextBox) but only when elements are on TabablzControl. 
As you can see foreground and background have the same white color (TextBlock over the TabablzControl have correct style).
![Light](https://user-images.githubusercontent.com/29532981/59011765-f9f8ff00-8835-11e9-885f-dde0d7058f44.png)
![dark](https://user-images.githubusercontent.com/29532981/59011783-0a10de80-8836-11e9-9d5b-a2b59f83c0ad.png)

I attache project to reproduce problem. 
Could you please help me solve this problem?
[A00.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/3260267/A00.zip)

**Comment by Keboo** [comment]
@marekbe Thank you for the reproduction project! 
I will need to spend more time digging in to understand exactly why this is occurring, but as a quick work around, you can simply apply `TextElement.Foreground="{DynamicResource MaterialDesignBody}"` to your MainWindow as well as your TabItems to resolve the issue.
