### ISSUE TITLE
Migrate to MDC from MDL

### ISSUE THREAD

**Issue by Richienb** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1275]
This project's website is still using [MDL](https://getmdl.io/) which has been deprecated years ago.

Are there any plans to migrate it to [MDC](https://material.io/develop/web/)? I'd be happy to start working on a PR.

**Comment by Keboo** [comment]
Hi @Richienb yea the web site has certainly been neglected recently. If you would like to submit a PR for getting things updated we can certainly take a look at getting it merged.

**Comment by Richienb** [comment]
@Keboo Sure. Will do.

**Comment by Richienb** [comment]
@Keboo I've finished building the site. Where do I commit and PR it to?

**Comment by Keboo** [comment]
@Richienb the code for the web site is [here](https://github.com/MaterialDesignInXAML/Website). Let's migrate this issue, and PR over to that repo for now.
