### ISSUE TITLE
Update Icon Pack

### ISSUE THREAD

**Issue by HuggerCoursera** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1276]
Icon pack became partially incomplete and obsolete. For example, there is a remove filter icon, but no corresponding filter icon while that very one is available at [materialdesignicons.com](https://materialdesignicons.com)

**Comment by Keboo** [comment]
Hi @HuggerCoursera thanks for the update. We have a script that automatically builds up the pack icons. Unfortunately right now this is a manual process. I am putting this in the 2.6.0 milestone as a reminder to run the script prior to the release.
