### ISSUE TITLE
CheckBox resize check

### ISSUE THREAD

**Issue by boskokg** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1277]
Can you please extend CheckBox with a possibility to resize check?

In the touch screen app I must make a checkbox bigger. When I increase the font, only the text of the checkbox gets bigger.

I know there are several things that can be done to resize the check, but all of them are workarounds.

Currently, the most clean workaround is to put CheckBox inside ViewBox: [link](https://stackoverflow.com/a/56510133/3647184)

**Comment by AlbertAlonso** [comment]
This can be a good first issue: 

1. Go to MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.CheckBox.xaml
2.  Go to the Style `MaterialDesignCheckBox` (Line 48)
3. Add the setters for height and width with the current values
``` 
        <Setter Property="Height" Value="18"/>
        <Setter Property="Width" Value="18"/>
```
4.  In line 88 (90 after adding the setters), change the Viewbox width and Height so they are binded
`                        <Viewbox Width="{TemplateBinding Width}" Height="{TemplateBinding Height}"  VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                 FlowDirection="LeftToRight">`

Now you can change the size of the CheckBox
`<CheckBox Height="80" Width="80"/>`
without workarounds.

**Comment by boskokg** [comment]
Thanks for the answer.
Do you think that we should expose two properties for the size or it is better to have one "size" property?
Is it expected by Material design to have checkbox with different Height and Width?

**Comment by Keboo** [comment]
I don't think the above solution will work as it will give the check box portion of the control the entire size. As a comment on PR #1286 indicates this effectively leaves the content hidden.

I think for this we want to do the following:
- Add a new `CheckBoxAssist` class with an attached property of type `double` with the name `CheckBoxSize`. You can use the [ToggleButtonAssist](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ToggleButtonAssist.cs) as an example.
- In the `MaterialDesignCheckBox` style set the default value of the attached property to be "18" . You can see an example of setting an attached property in a setter [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L42)
- Use bindings on the ViewBox to apply `CheckBoxAssist.CheckBoxSize` to both the `Height` and `Width`. This will require using a `Binding` not a `TemplateBinding`. You can see an example of this [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L48)

**Comment by malixg** [comment]
I'm having the same problem where controls are too small in touch based applications and don't properly scale when setting the size. Is there any update on this? Thanks
