### ISSUE TITLE
Focus problem on dialog with textbox

### ISSUE THREAD

**Issue by greuelpirat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1281]
If you open a dialog with an input field and go to another application, to proceed with the app you need an additional click to reactivate the dialog. (Version MaterialDesignThemes 2.5.1)

you can reproduce this with the wpf-demo:
1. In the WPF-Demo-Applikation go to "Dialogs"
2. In the first sample click "Add Fruit"
3. Focus an other applikation
4. Click cancel in the "Add Fruit"-Dialog

Expected: Dialog closed
Actual: Textbox got Focus-Animation. Dialog still open. Second click on cancel closes the Dialog.

This focus issue does not appear on dialogs with no input fields. (like Sample 2 in the Demo)

**Comment by jespersh** [comment]
I seem to recall this has been up before in an issue. Anyone?

**Comment by cpyfferoen** [comment]
#1021 Is the same.

**Comment by greuelpirat** [comment]
Any chance for a fix?

**Comment by greuelpirat** [comment]
I continue this issue on #1021
