### ISSUE TITLE
The textbox width inside the MaterialDesignNumericUpDown is broken

### ISSUE THREAD

**Issue by ahmedflix25** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1285]
setting the `NumericUpDown` from MahApps `HorizontalContentAlignment` to Center will break the width for the textbox inside of it because it sets its width to auto making it unclickable by the mouse but you can still reach it with Tab 

you can test it in the demo app for MahApps

**Comment by AlbertAlonso** [comment]
@ahmedflix25 Sorry if I am wrong, but at setting the `HoritzontalContentAlignment`, isn't that the expected behaviour?

If you want to change the alignment of the text inside the `TextBox`, but not the `TextBox` itself, you should use `TextAlignment="Center"`.

**Comment by ahmedflix25** [comment]
yes, you are right and i need to get some sleep.
thanks
