### ISSUE TITLE
FontFamily in MetroWindow causes memory leak

### ISSUE THREAD

**Issue by ojanacek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1289]
I discovered that the memory footprint of my app based on MahApps in combination with Material Design is growing in time. Did some profiling and found that `UnamanagedMemoryStream` typed objects also grow in number. Googling revealed this [SO question](https://stackoverflow.com/questions/45297837/what-causes-unmanagedmemorystream-in-wpf-memory-leak) suggesting that it's a problem of a known FontFamily issue. Basically if not set to an absolute path or registered windows font directly it might cause memory leaks. 

Tried to remove the following from the MainWindow and it helped.
`FontFamily="{StaticResource DefaultFont}"`
Any suggestions how to preserve the styling but avoid leaking memory? Should be fixed in the MashUp demo.

**Comment by Keboo** [comment]
@ojanacek this appears to be the same issue as #746. Take a look at the details in there as it outlines options for mitigation

**Comment by ojanacek** [comment]
@Keboo Yes, sorry to create a duplicate. I actually tried searching before creating the post.
