### ISSUE TITLE
Styles for PackIcon is missing from the wiki page "ControlStyleList"

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1292]
Styles for `PackIcon` is missing from the wiki page https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/ControlStyleList

**Comment by Keboo** [comment]
For anyone who wants to work on this. The powershell that is used to generate that wiki page is located in `/Scripts/GenerateThemesWikiMarkdown.ps1`. No need to update the wiki directly as there is not an Azure pipeline that will take care of running the script and deploying any changes.

**Comment by dhilmathy** [comment]
@Keboo  There is no default `Style` defined for `PackIcon` under [Themes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MaterialDesignThemes.Wpf/Themes) folder. Thus, the [PS1](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/Scripts/GenerateThemesWikiMarkdown.ps1) script is not picking and adding the `Style` list in [Wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/ControlStyleList.md)

I could see `Style` for `PackIcon` were created inline in [MaterialDesignTheme.ListBox.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml#L169), [MaterialDesignTheme.Menu.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Menu.xaml#L83) and [MaterialDesignTheme.ToolBar.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToolBar.xaml#L131).

Do we need to create default `Style` for `PackIcon` under [Generic.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml)?

Something like,
```
<Style TargetType="{x:Type wpf:PackIcon}" >
    <Setter Property="Width" Value="22" />
    <Setter Property="Height" Value="22" />
</Style>
```

Your thoughts?

**Comment by Keboo** [comment]
@dhilmathy there is an [existing style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L835-L858) for the PackIcon in the Generic.xaml. So you shouldn't need to add one. I did not spend much time trying to figure out why it is being excluded from the output.

**Comment by dhilmathy** [comment]
@Keboo I see that now. Thanks for pointing that; I can check the script.
