### ISSUE TITLE
Selected item in ComboBox-dropdown is cut

### ISSUE THREAD

**Issue by greuelpirat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1299]
When selected item in ComboBox is too long for its size it is cut. But it is also cut, when the dropdown is shown, where other items are fully displayed:

![image](https://user-images.githubusercontent.com/16866222/60317209-556a6880-996e-11e9-944d-5f2625528922.png)

sample: https://github.com/greuelpirat/ComboBoxIssue.git

**Comment by Xaalek** [comment]
Can't replicate the bug. Maybe it has been patched since.

![image](https://user-images.githubusercontent.com/54487782/167881547-f8eb771a-ff8e-48d1-9b76-751b1f7d6220.png)

Moreover the sample no longer exists.
