### ISSUE TITLE
Breaking 3.0.0 changes

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1301]
This is an issue to keep track of breaking changes that I would like to see go into the 3.0.0 release.
I am open to additional suggestions as well:

- [x] Card defaults its VerticalAlignment to Top. Suggest defaulting to Stretch.
- [x] Flipper defaults its VerticalAlignment to Top. Suggest defaulting to Stretch.
- [x] Remove obsolete PalleteHelper methods. 
- [x] Remove obsolete members in SmartHint
- [x] Remove obsolete `DialogClosingEventArgs.Content`. Use `DialogClosingEventArgs.Session.Content` instead.
- [x] Remove unused `DialogClosingEventArgs` constructors
- [x] Rename `MaterialDataGridComboBoxColumn` to `DataGridComboBoxColumn`. Since using the custom column in an app will require specifying the namespace, having the Material prefix adds very little.
- [x] Vertical alignment of `Label`, `TextBlock` and `TextBox` should have VerticalAlignment=Stretch, and VerticalContentAlignment=Top
- [x] Source code is no longer included in the NuGet package.
- [x] `MaterialDesignToolBar` no longer sets FontFamily to `MaterialDesignFont`
- [x] Popup in default `DialogHost` template no longer sets FontFamily to `MaterialDesignFont`
- [x] MaterialDesignTitleTextBlock => MaterialDesignHeadline6TextBlock
- [x] MaterialDesignHeadlineTextBlock => MaterialDesignHeadline5TextBlock
- [x] MaterialDesignSubheadingTextBlock => MaterialDesignSubtitle1TextBlock
- [x] MaterialDesignDisplay4TextBlock => MaterialDesignHeadline1TextBlock
- [x] MaterialDesignDisplay3TextBlock => MaterialDesignHeadline2TextBlock
- [x] MaterialDesignDisplay2TextBlock => MaterialDesignHeadline3TextBlock
- [x] MaterialDesignDisplay1TextBlock => MaterialDesignHeadline4TextBlock

**Comment by ahmedflix25** [comment]
labels textboxs and textblocks have different VerticalAlignment by default  and if you put them in stackpanel next to each other they won't be in the same line 

```
<StackPanel Orientation="Horizontal">
        <Label Content="Label"/>
        <TextBlock Text="TextBlock"/>
        <TextBox Text="TextBox" Width="100"/>
</StackPanel>
```

![image](https://user-images.githubusercontent.com/7858946/60381275-41983280-9a52-11e9-92b2-e652614f6724.png)

**Comment by Keboo** [comment]
@ahmedflix25 I believe I have gotten it as close to "it just works" as possible.
This now has all three controls aligned vertically.
```
<StackPanel Orientation="Horizontal">
    <Label Content="Label"/>
    <TextBlock Text="TextBlock" Style="{StaticResource MaterialDesignTextBlock}"/>
    <TextBox Text="TextBox" Width="100"/>
</StackPanel>
```

I have created a new base styled for TextBlock, `MaterialDesignTextBlock`. Because the `TextBox` requires some internal padding to support things like the underline, we need to pad the other controls to match. So I adjusted the `Label`'s default padding from 5 to 4, and created a new style for `TextBlock` with the appropriate default padding. We can't universally apply this `TextBlock` style implicitly like we do so many other styles because `TextBlocks` are used internally inside of any content control that displays text. In fact it would then double the padding on the Label breaking the initial fix.

**Comment by Tyrrrz** [comment]
>Card defaults its VerticalAlignment to Top. Suggest defaulting to Stretch.

Wasn't this "by design" so as to avoid the common Material Design antipattern of using cards as a host for everything? I might be talking out of my ass but I seem to remember something like that.

**Comment by Keboo** [comment]
@Tyrrrz not sure if that was the original intent, but the default of Top is a bit of a confusing default since it no longer behaves like most content controls. With that said, I can understand the concern with people just throwing Cards everywhere, as they are a bit heavier than just a normal control control.

**Comment by MovGP0** [comment]
can I assume that the 3.0.0 release will support .NET Core 3.0?

**Comment by Keboo** [comment]
@MovGP0 yes .NET Core 3.0 support will be in the 3.0.0 release. It is there now if you download the latest 3.0.0 preview NuGet.

**Comment by csutcliff** [comment]
`Package 'MaterialDesignThemes.MahApps 0.1.1-ci653' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.`

The other packages seem to be built for .Net Core 3.0

**Comment by jespersh** [comment]
@csutcliff MahApps has not been updated to .NETCoreApp yet. MahApps' support for NETCoreApp is still in alpha.
Their project for 2.0.0 that adds that support is here: https://github.com/MahApps/MahApps.Metro/projects/3

**Comment by csutcliff** [comment]
> 
> 
> @csutcliff MahApps has not been updated to .NETCoreApp yet. MahApps' support for NETCoreApp is still in alpha.
> Their project for 2.0.0 that adds that support is here: https://github.com/MahApps/MahApps.Metro/projects/3

I'm using the 2.0.0 alpha of MahApps, but the package I'm talking about is from this repo, not MahApps

**Comment by jespersh** [comment]
@csutcliff you can't mix and match MahApps 2.0 and MaterialDesignThemes.MahApps which **should** only target MahApps 1.6.0

To say it in another way: No work has been put into MaterialDesignThemes.MahApps to update it to NetCoreApp or target MahApps 2.0

**Comment by MichelMichels** [comment]
@Keboo MaterialDataGridTextColumn also changed to DataGridTextColumn, maybe you should add it to the list

**Comment by philpowers** [comment]
Maybe also worth mentioning that the Hyperlink styles changed along with the TextBlock styles. For example, I had to change the following in some code of mine:

✔ MaterialDesignSubheadingHyperlink => MaterialDesignSubtitle1Hyperlink
✔ MaterialDesignDisplay1Hyperlink => MaterialDesignHeadline4Hyperlink

**Comment by HamidRezaAshkiyan** [comment]
Is there any other breaking change? since i updated my package MaterialMessageBox 1.0.0.11 does not work anymore and throw not implemented error. 
Is there any suggestion for fixing or replacing this library?

**Comment by Chumba** [comment]
"Remove obsolete PalleteHelper methods."

Apologies if this is covered elsewhere, I could not find any info on this. In 3.0.0+ what is the correct way to allow a user to change the theme, given that palletehelper as been axed?

**Comment by ahmedflix25** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/PaletteSelectorViewModel.cs

**Comment by Keboo** [comment]
@Chumba you can also find the docs on this in the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming)

**Comment by mgnslndh** [comment]
For anyone looking to upgrade from 2.6.0 to 3.x => The type `ThemeMarkupExtension` has been removed in v3.0.0.
