### ISSUE TITLE
CustomColorTheme does not exists

### ISSUE THREAD

**Issue by Ru4nGR** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1303]
im trying to set a custom color theme as follows:

<materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Accent="DarkGreen" />

but the compiler says that the CustomColorTheme does not exists

**Comment by Keboo** [comment]
Are you using the 2.6.0 preview NuGet package? This is a new feature that is coming in the 2.6.0 release and does not exist in 2.5.1

**Comment by Ru4nGR** [comment]
Ok, i downloaded the preview and now its working... but where am i supposed to put the materialdesign marker?

**Comment by Keboo** [comment]
@Ru4nGR it goes as a merged dictionary in your [App.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml#L20). You will also need to add the required [xmlns](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml#L5).

**Comment by Ru4nGR** [comment]
`<Application x:Class="Susan.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             xmlns:local="clr-namespace:Susan"
             StartupUri="MainWindow.xaml">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Accent="DarkGreen" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`
it is not a Dictionary, it is a atribute of materialDesign. Am i missing something?

**Comment by Keboo** [comment]
It is a [Markup Extension that returns a resource dictionary](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ThemeMarkupExtension.cs).

```XAML
<Application x:Class="MaterialDesignColors.WpfExample.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             StartupUri="MainWindow.xaml">
<Application.Resources>
    <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
            <materialDesign:CustomColorTheme BaseTheme="Light" Primary="Aqua" Accent="DarkGreen" />
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
</Application.Resources>
</Application>
```

**Comment by Ru4nGR** [comment]
im getitng "The value "MaterialDesignThemes.Wpf.CustomColorTheme" is not of the type"System.Windows.ResourceDictionary" and can't be used in this generic collection.
Nome do parâmetro: value"
error adapted from my vs in portuguese

**Comment by Keboo** [comment]
Here is a small [sample app](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Theming/Theme.CustomColors) that does it.

**Comment by Ru4nGR** [comment]
Thanks man, i got it, working very nicely!
