### ISSUE TITLE
Can't use FindResource or TryFindResource on some styles

### ISSUE THREAD

**Issue by SuhailAlhegry** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1308]
Some styles don't work with `FindResource ` (finds a resource in code), for example: the style `MaterialDesignScrollBarMinimal `.

**Comment by Keboo** [comment]
@SuhailAlhegry I am unable to reproduce this issue. Can you provide reproduction steps? Which version of the library are you using?

**Comment by SuhailAlhegry** [comment]
@Keboo, I created a repository to reproduce the issue at: https://github.com/SuhailAlhegry/MaterialDesignInXamlToolkit_1308

The version I'm using is 2.5.1 .

**Comment by SuhailAlhegry** [comment]
After trying to set the style in using other methods, it didn't crash, but it also didn't make a difference. Looks like the style doesn't exist in the build I'm using.

**Comment by Keboo** [comment]
Correct, this was a new style that was added in a later version. Let me know if there are still any issues.
