### ISSUE TITLE
ButtonAssist

### ISSUE THREAD

**Issue by IRHAMidIR** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1313]
.

**Comment by IRHAMidIR** [comment]
Hi All,
I'm having trouble with "materialDesign:ButtonAssist.CornerRadius" ,
 when i use it , i confronted  Error:
The name "ButtonAssist" does not exist it the namespace "https//materialdesignxaml.net/winfx/xaml/themes".
pls help

**Comment by IRHAMidIR** [comment]
Hi All,
I'm having trouble with "materialDesign:ButtonAssist.CornerRadius" ,
when i use it , i confronted Error:
The name "ButtonAssist" does not exist it the namespace "https//materialdesignxaml.net/winfx/xaml/themes".

And Local:ButtonAssist.CornerRadius dose not work

**Comment by IRHAMidIR** [comment]
Fixed Bug In materialDesign Local File

**Comment by Keboo** [comment]
@IRHAMidIR which version of the NuGet package are you using? That is a new class that will be in the 2.6.0 release. So you need to use the [latest preview NuGet packages](https://www.nuget.org/packages/MaterialDesignThemes/2.6.0-ci1558).
