### ISSUE TITLE
MahApps Dragablz Demo Needs a DataGrid

### ISSUE THREAD

**Issue by Tide** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1314]
The MahApps Dragablz demo needs a DataGrid added in order test all the MahApps brushes.

**Comment by Mrxx99** [comment]
I am working on this. Just wondering if there should be anything special for that DataGrid. Currently I have a Checkbox-, Text-, Combobox and NumericUpDownColumn. But the Checkbox and ComboBox look like WPF default. Should I put the DataGrid resource dictionary as resource into the page?

**Comment by Keboo** [comment]
@Mrxx99 sorry for the delay. That list of items look sufficient, even just simple text columns would probably exercise most of the MahApps brushes. 

I am not sure about needing to include the resource dictionary. Can you open a PR and I can take a look.

**Comment by Keboo** [comment]
@Mrxx99 are you still working on this?

**Comment by Mrxx99** [comment]
I opened the PR (#1348), but it had this theming issues. I didn't work any further on it yet, because you wanted to take a look at it

**Comment by Keboo** [comment]
@Mrxx99 o sorry, it was late and I missed the PR link above. Thanks!

**Comment by Keboo** [comment]
Merged in the current work for the data grid. The control now exists in the demo app but there are some issues as outlined in #1348
