### ISSUE TITLE
NotEmptyValidationRule doesn't make the property update on empty string

### ISSUE THREAD

**Issue by ahmedflix25** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1316]
open the demo app and start typing any character in the validated first textbox in there like a "g or e etc".
check the property in the viewmodel and it will update as well to that value
now remove the character the validation will kick in and tells you that the "Field is required" but the property in the viewmodel will not update to an empty string and it's value will be the same character you entered before
removing the validation rule will make it work as expected

**Comment by nmycue** [comment]
I ran into this same problem but was able to get around it by adding TargetNullValue and ValidationStep to the element declaration. Ex: 

````C#
// Namespace declarations
xmlns:sys="clr-namespace:System;assembly=mscorlib"
xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"		
...
<TextBox x:Name="Name" Style="{StaticResource MaterialDesignFloatingHintTextBox}" materialDesign:HintAssist.Hint="Name" DataContext="{Binding Person}">
    <TextBox.Text>
        <Binding Path="Name" UpdateSourceTrigger="PropertyChanged" Mode="TwoWay" ValidatesOnDataErrors="True" TargetNullValue="{x:Static sys:String.Empty}">
            <Binding.ValidationRules>
                <data:NotEmptyValidationRule ValidationStep="UpdatedValue" />
	    </Binding.ValidationRules>
        </Binding>
    </TextBox.Text>
</TextBox>
````

**Comment by ahmedflix25** [comment]
> 
> 
> I ran into this same problem but was able to get around it by adding TargetNullValue and ValidationStep to the element declaration. Ex:
> 
> ```cs
> // Namespace declarations (data is where my NotEmptyValidationRule lives)
> xmlns:sys="clr-namespace:System;assembly=mscorlib"
> xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"		
> ...
> <TextBox x:Name="Name" Style="{StaticResource MaterialDesignFloatingHintTextBox}" materialDesign:HintAssist.Hint="Name" DataContext="{Binding Person}">
>     <TextBox.Text>
>         <Binding Path="Name" UpdateSourceTrigger="PropertyChanged" Mode="TwoWay" ValidatesOnDataErrors="True" TargetNullValue="{x:Static sys:String.Empty}">
>             <Binding.ValidationRules>
>                 <data:NotEmptyValidationRule ValidationStep="UpdatedValue" />
> 	    </Binding.ValidationRules>
>         </Binding>
>     </TextBox.Text>
> </TextBox>
> ```
it does work but it disable the validation defeating it's purpose

**Comment by Keboo** [comment]
This is actually by design.
From the [WPF Docs](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview#validation-process)
>  if a validation error or other type of error occurs at any time during this process, the process is halted.

You can see several alternate ways of doing validation [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/MVVM/MVVM.Validation).

**Comment by ahmedflix25** [comment]
thanks that was very helpful
