### ISSUE TITLE
Obsolete Attribute breaking code

### ISSUE THREAD

**Issue by tlford83** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1325]
Please when using the Obsolete attribute, put in what it is being replaced with. I had to roll back to 2.5.1

**Comment by Gerardo-Sista** [comment]
I agree,
palettehelper.ReplacePrimaryColor is now obsolete for example and I don't know what's the correct way now.

**Comment by Keboo** [comment]
I have added documentation to the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming) explaining the new API. There is also a [youtube video](https://www.youtube.com/watch?v=1gHAKhFBcOU) showing how to upgrade an existing app.

**Comment by Gerardo-Sista** [comment]
Well done!! Thank you!

**Comment by Keboo** [comment]
Closing unless there are further issues.
