### ISSUE TITLE
MahApps integration theme switch not working properly

### ISSUE THREAD

**Issue by Gerardo-Sista** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1335]
Hello,
I have the standard App.XAML integration code, section "The App.XAML":
[https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/MahApps.Metro-integration](url)

I change the theme using this code:
`  
 public void SwitchTheme(bool IsDark, string SelectedPrimaryColor, string SelectedSecondaryColor)
        {
           IBaseTheme baseTheme = IsDark == true ? Theme.Dark : Theme.Light;
           Color  pColor =(Color)ColorConverter.ConvertFromString(SelectedPrimaryColor);
           Color  sColor = (Color)ColorConverter.ConvertFromString(SelectedSecondaryColor);
           ITheme theme = Theme.Create(baseTheme, pColor, sColor);
           ResourceDictionaryExtensions.SetTheme(Application.Current.Resources, theme);
        }
`
But theme doesn't change properly, obtaining a partial switch like this:

![Senza titolo](https://user-images.githubusercontent.com/34858800/61971031-44009480-afde-11e9-8947-430b5c783f85.png)

Am I doing something wrong or is this a bug? In another app it works fine. 
Thank you in advance for any help!

**Comment by Keboo** [comment]
@Gerardo-Sista that code looks like it should be correct. Can you check the versions of your nuget packages for:
MaterialDesignThemes, MaterialDesignColors, MaterialDesignThemes.MahApps, and MahApps.Metro.

I would also check to see if you have any resources with MahApps brush keys declared.

**Comment by Gerardo-Sista** [comment]
Hello, 
thank you for the support. 
MaterialDesignThemes **2.6.0** (current latest stable)
MaterialDesignColors **1.2.0** (current latest stable)
MaterialDesignThemes.MahApps **0.1.0** (current latest stable)
MahApps.Metro **1.6.5** (current latest stable)

No MahApps brush keys declared, only subtitution in App.Xaml
`    
            <SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentBaseColorBrush" Color="{DynamicResource Primary600}" />
            <SolidColorBrush x:Key="AccentColorBrush" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="AccentColorBrush2" Color="{DynamicResource Primary400}"/>
            <SolidColorBrush x:Key="AccentColorBrush3" Color="{DynamicResource Primary300}"/>
            <SolidColorBrush x:Key="AccentColorBrush4" Color="{DynamicResource Primary200}"/>
            <SolidColorBrush x:Key="WindowTitleColorBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentSelectedColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <LinearGradientBrush x:Key="ProgressBrush" EndPoint="0.001,0.5" StartPoint="1.002,0.5">
                <GradientStop Color="{DynamicResource Primary700}" Offset="0"/>
                <GradientStop Color="{DynamicResource Primary300}" Offset="1"/>
            </LinearGradientBrush>
            <SolidColorBrush x:Key="CheckmarkFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="RightArrowFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <SolidColorBrush x:Key="IdealForegroundDisabledBrush" Color="{DynamicResource Primary500}" Opacity="0.4"/>
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchBrush.Win10" Color="{DynamicResource Primary500}" />
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchMouseOverBrush.Win10" Color="{DynamicResource Primary400}" />
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.ThumbIndicatorCheckedBrush.Win10" Color="{DynamicResource Primary500Foreground}" />
`

**Comment by Gerardo-Sista** [comment]
Please check yourself. I prepared a very small app reproducing the issue:
[MaterialDesignXAML.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/3437970/MaterialDesignXAML.zip)

OUTPUT
**Before click:**
![image](https://user-images.githubusercontent.com/34858800/61991988-75b64180-b058-11e9-86ba-de49c9da1db4.png)



**After click:**
![image](https://user-images.githubusercontent.com/34858800/61991995-8f578900-b058-11e9-848b-ec19dd498aac.png)

**Comment by Keboo** [comment]
In the 2.6.0 release it is much simpler setting up your App.xaml. Here is a working version:
```xaml
<Application x:Class="MetroDesignXAML.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:MetroDesignXAML"
             xmlns:materialDesignMahApps="http://materialdesigninxaml.net/winfx/xaml/themes"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>

            <ResourceDictionary.MergedDictionaries>
                <!-- This should be all you need to setup the color theme -->
                <materialDesignMahApps:MahAppsBundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime"/>

                <!-- MahApps -->
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <!--<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />-->

                <!-- Material Design -->
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <!-- 
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
                -->

                <!-- Material Design: MahApps Compatibility -->
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Defaults.xaml"/>

                <!-- Not sure why these were being included, don't appear to be used -->
                <!--<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Flyout.xaml" />-->

            </ResourceDictionary.MergedDictionaries>

            <!-- MahApps Brushes -->
            <!--<SolidColorBrush x:Key="HighlightBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentBaseColorBrush" Color="{DynamicResource Primary600}" />
            <SolidColorBrush x:Key="AccentColorBrush" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="AccentColorBrush2" Color="{DynamicResource Primary400}"/>
            <SolidColorBrush x:Key="AccentColorBrush3" Color="{DynamicResource Primary300}"/>
            <SolidColorBrush x:Key="AccentColorBrush4" Color="{DynamicResource Primary200}"/>
            <SolidColorBrush x:Key="WindowTitleColorBrush" Color="{DynamicResource Primary700}"/>
            <SolidColorBrush x:Key="AccentSelectedColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <LinearGradientBrush x:Key="ProgressBrush" EndPoint="0.001,0.5" StartPoint="1.002,0.5">
                <GradientStop Color="{DynamicResource Primary700}" Offset="0"/>
                <GradientStop Color="{DynamicResource Primary300}" Offset="1"/>
            </LinearGradientBrush>
            <SolidColorBrush x:Key="CheckmarkFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="RightArrowFill" Color="{DynamicResource Primary500}"/>
            <SolidColorBrush x:Key="IdealForegroundColorBrush" Color="{DynamicResource Primary500Foreground}"/>
            <SolidColorBrush x:Key="IdealForegroundDisabledBrush" Color="{DynamicResource Primary500}" Opacity="0.4"/>
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchBrush.Win10" Color="{DynamicResource Primary500}" />
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.OnSwitchMouseOverBrush.Win10" Color="{DynamicResource Primary400}" />
            <SolidColorBrush x:Key="MahApps.Metro.Brushes.ToggleSwitchButton.ThumbIndicatorCheckedBrush.Win10" Color="{DynamicResource Primary500Foreground}" />-->

        </ResourceDictionary>
    </Application.Resources>
</Application>

```

**Comment by Gerardo-Sista** [comment]
Thank you very much for your attention and help.
It seems it works now perfectly both in demo app and production app. 
Also, it's more lightweight and straightforward code too: excellent improvement.
I **strongly suggest you to update the Wiki** (as you did for issue #1325)
since it seems waso only a bad Wiki code reference and not a true issue.
This way other people will not encounter the same issue.

I'm closing this as issue has been resolved. 
Thank you again.

Gerardo
