### ISSUE TITLE
WPF - Card - Flipper - Colors are not updated

### ISSUE THREAD

**Issue by JackDaniel91** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1341]
Hi, 

i have detected an issue in my application. I was able to  reconstruct the issue successfully in the MaterialDesignDemo application:

1. Start the Material Design in XAML Toolkit Application (MaterialDesignDemo)
2. **Change the primary color** via the color tool e.g. from **purple to red**.
3. Navigate to the View "Cards".
4. The color within the **flipper-component has not been updated**. All components within the flipper component **are still purple**.

Screenshot of the issue:
![Card_Flipper_ColorUpdate_Issue](https://user-images.githubusercontent.com/31038391/62188259-1dd74d80-b36c-11e9-8176-2d7e7a249728.png)

Installed packages:
- MaterialDesignColors v1.2.0
- MaterialDesignThemes v2.6.0
- MaterialDesignThemes.MahApps v0.1.0
- MaterialDesignThemes.Dialogshelper v1.0.2

Best regards
Daniel

**Comment by Keboo** [comment]
Thank you for the well written bug report. Currently this bug is being tracked with issue #694
