### ISSUE TITLE
Context Menu in ComboBox is not themed

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1343]
Reported by @ondrasvoboda on gitter.

Reproduction steps:
1. Create a combo box and set `IsEditable=True`
2. Right click on the editable text box in the combo box. 

Observed: The context menu is the default WPF context menu

Expected: It should be themed in the same way that the text box is.

You can also see this in the demo app:
![image](https://user-images.githubusercontent.com/952248/62228945-7fe78100-b373-11e9-88aa-02577f64ebe7.png)

**Comment by MichelMichels** [comment]
#1346

**Comment by ondrasvoboda** [comment]
@MichelMichels how it works when custom context menu is assigned to ComboBox? It seems that than there will be default menu for inner TextBox and custom menu if you click on ComboBox but outside of TextBox.
Wouldn't it be better to just bind inner TextBox.ContextMenu to ComboBox.ContextMenu (and set default menu to ComboBox.ContextMenu)?

**Comment by MichelMichels** [comment]
Is the ContextMenu of a ComboBox without focus on its inner TextBox expected to be the same as the ContextMenu of the inner TextBox? I was under the impression that there was no default ContextMenu for an unfocused ComboBox.

But I understand your point and if this is desired behaviour then I could make some changes to my PR.

**Comment by ondrasvoboda** [comment]
You are right, there is no default ContextMenu for an unfocused ComboBox. But if you set one, then you end up with  two ContextMenus on single control (user point of view).
I prefer ComboBox.ContextMenu to be used also for inner TextBox, then it can be easily customized. It doesn't matter to me if it is by default empty or not.

**Comment by MichelMichels** [comment]
I don't know if what you're asking is possible, because the ContextMenu is about the selected text in the editable ComboBox.
