### ISSUE TITLE
Set dialoge Host background to transparent 

### ISSUE THREAD

**Issue by RaoHammas** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1344]
hey ! can i set somehow back color to transparent ? i mean back color of content host always show white color even if i set transparent. Or can i change opacity of that black mask container of content ? I am loading user control as content of dialogHost . and trying to achieve something like Windows 10 Menu . Please help me. Thanks

![image](https://user-images.githubusercontent.com/16499626/61995223-d5cfd680-b09e-11e9-81c8-a1c126f19bc9.png)

_Originally posted by @RaoHammas in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1193#issuecomment-515685436_

**Comment by Keboo** [comment]
What I think needs to be done for this:

- [ ] Create a dependency property on the `DialogHost` control  of type `Brush` with name `OverlayBackground`. This property should have a default value of Black.
- [ ] Remove the `BlackBackground` resource from MaterialDesignTheme.DialogHost.xaml and replace its usage with bindings to the new property on the `DialogHost`.

**Comment by RaoHammas** [comment]
@Keboo  Hey thanks for response . So ill be seeing this feature in next update or what ?

**Comment by Keboo** [comment]
@RaoHammas yes this was added to the latest 3.0.0 release. It should be there if you update to the latest 3.0.0 preview NuGet package.

**Comment by RaoHammas** [comment]
@Keboo  Thanks a lot ! stay blessed :)

**Comment by ckyRoomee** [comment]
how about the back color of content host? it always show white color even if i set transparent.Thanks in advance

**Comment by ckyRoomee** [comment]
@RaoHammas please help me.Thanks
