### ISSUE TITLE
Add ColorChanged event to ColorPicker

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1356]
In 2.6.0 we added a new [ColorPicker control](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ColorPicker.cs). There is a Color dependency property that can be bound, but not event. We should create a new routed event that is raised when the color property changes. This event should pass through the new color as it changes.

You can reference the routed event that is used inside of the [RatingBar as an example](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/febc81efebebd54f322518d60c8934d5161a6d1d/MaterialDesignThemes.Wpf/RatingBar.cs#L71-L82).

**Comment by Mrxx99** [comment]
I guess this can be closed with #1362 beeing merged?

**Comment by Keboo** [comment]
@Mrxx99 yes, thank you for the help reviewing the backlog!
