### ISSUE TITLE
No text is displayed on typing in Textbox with style: MaterialDesignOutlinedTextFieldTextBox

### ISSUE THREAD

**Issue by Arunberlin** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1358]
This is the tag:

`<TextBox x:Name="textBox" Style="{DynamicResource MaterialDesignOutlinedTextFieldTextBox}"  HorizontalAlignment="Left" Height="46"  Text="hi" VerticalAlignment="Top" Width="200"  Margin="648,514,0,0"/>`

No text is displayed while typing. I've tried changing foreground color of text

**Comment by jespersh** [comment]
Try removing the height or adding more height. I think it takes a bit more than 46.

**Comment by Arunberlin** [comment]
> Try removing the height or adding more height. I think it takes a bit more than 46.

Yes, I've removed height and Text is displayed. Is there any way to adjust textbox height, without clipping Text inside it?

**Comment by jespersh** [comment]
I think the fix provided in #1347 could help you at least partially if you set the correct textbox properties. It is in the CI builds
