### ISSUE TITLE
Custom IconPack

### ISSUE THREAD

**Issue by No1e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1369]
Hello MDX Team,

Is there possibility to add custom IconPack?

Thanks and regards,
Novak

**Comment by Keboo** [comment]
@No1e it depends on what you mean by a custom IconPack. This library comes bundled with the material design icons. If you need something beyond this, the easiest option is to simply bring in another NuGet package like [MahApps.Metro.IconPacks](https://github.com/MahApps/MahApps.Metro.IconPacks). This NuGet also allows you to extend it with your own custom icon packs as outlined [here](https://jkarger.de/2019/04/02/how-to-create-a-new-iconpack-with-custom-svg-paths/).

**Comment by No1e** [comment]
@Keboo 

Thank you very much for the answer. That is exactly what I need. 

Best regards,
Novak
