### ISSUE TITLE
Support for NumericUpDown Control

### ISSUE THREAD

**Issue by No1e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1371]
Hello MDX Team,

Is there any plan for support for NumericUpDown control?

Thanks and best regards,
Novak

**Comment by Keboo** [comment]
@No1e no current plans to bring this directly. There is support for MahApps which does have a NumericUpDown control and there is also a community project [MaterialDesignExtensions](https://github.com/spiegelp/MaterialDesignExtensions) that contains a Number spinner that may help as well.

**Comment by No1e** [comment]
Ok. Thanks.
