### ISSUE TITLE
Flipper Margin and Padding don't match Card

### ISSUE THREAD

**Issue by Awsmolak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1374]
I can't seem to easily set the margins and paddings for flipper controls to match those set for Cards. So when cards and flippers are used alongside each other, it takes a lot of manual tweaking to get a uniform look. It would be nice if setting the margins and padding for both controls achieved the same appearance.

**Comment by laxmy** [comment]
Hi @Keboo ,
Can I pick this?

**Comment by Keboo** [comment]
@laxmy yes. I have not actually spent much time looking at the exact differences or what needs to change so if you have questions let me know.

**Comment by laxmy** [comment]
Not sure why Flippers have a border that is different from Card Borders in MaterialDesignCardFlipper.
Looks like if I can add the border like that of a card, it can be fixed. @Keboo ...pls give suggestions for the fix

**Comment by Keboo** [comment]
Looking through this, i am not sure it makes sense to try and make these match. The flipper is really a wrapper around a card. For now i think it is fine to leave them separate.
