### ISSUE TITLE
DialogHost not showing Dialog

### ISSUE THREAD

**Issue by No1e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1382]
Hi MDX Team,

I am using 2.6.0 version. I tried all ways of showing Dialog, but for some reason does not work.
I would share the code, but there is nothing special there.

Am I missing something? Some pre-configuration that is necessary or something else?

Best regards,
Novak

**Comment by No1e** [comment]
Hello MDX Team,

I know that did not gave you many Info here, but I need help from your side to resolve this.

Do you have any idea, where the problem can be?
I can provide you any information that might help, just let me know what do you need.

Thank you and best regards,
Novak

**Comment by jespersh** [comment]
Did you add a <DialogHost>..</DialogHost> within the xaml tree? 
And what does your Window.xaml look like

**Comment by No1e** [comment]
Hi Jespersh,

What do you mean by:
"Did you add a .. within the xaml tree?"

**Comment by jespersh** [comment]
Like this: 
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/367dbddedd859b9972c6243a9bbfa76f0ea212c3/MainDemo.Wpf/MainWindow.xaml#L38

**Comment by No1e** [comment]
Well, in your example DialogHost is in the root of the page. 

What I tried is both from xaml and code. The only way that it works is if I set it in the XAML, but only as a last child of WindowContent. For example, if I have Grid as root element of WindowContent, it works if DialogHost is in the last row and have maximum row and column span, that is configured in the Grid. Otherwise it does not work. Why, I have no idea.

**Comment by jespersh** [comment]
Could you show in code how are you're trying to use it?
Here's another example: 
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/367dbddedd859b9972c6243a9bbfa76f0ea212c3/MainDemo.Wpf/Dialogs.xaml#L152

You can pretty much place it anywhere, and the dialoghost will **fill** and be shown on top the child(rens) allocated space.

Because it is supposed to be used like this:
```xaml
<Window>
  <Grid>
    <DialogHost>
      ... Some elements...
    </DialogHost>
  </Grid>
</Window>
```

And for some reason then I think you're trying to use it incorrectly like this:
```xaml
<Window>
  <Grid>
    <4 grid row defs here...>
    <Grid Grid.Row="0">..More elements..</Grid>
    <Grid Grid.Row="1">..More elements..</Grid>
    <Grid Grid.Row="2">..More elements..</Grid>
    <DialogHost Grid.Row="3"/>
  </Grid>
</Window>
```

**Comment by No1e** [comment]
Hello jespersh,

You was right. Thanks for the answer. Somehow, I misread the docs. Sorry.

Best regards,
Nole

**Comment by Keboo** [comment]
@No1e you might also find [this blog post](https://intellitect.com/material-design-in-xaml-dialog-host/) helpful as well.
