### ISSUE TITLE
How to hide arrow in ComboBox

### ISSUE THREAD

**Issue by No1e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1384]
Hello MDX Team,

Is there any way to hide arrow in ComboBox?

Thanks and best regards,
Novak

**Comment by bebenins** [comment]
Please post questions in this chat:
https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit

What you reported is not an issue, it's a question.  Many people are signed up to get email alerts on Issue updates so it'd be nice not to get Q/A spam the mailbox.  Thanks.

Regarding your question, there's no setting to do it unless you restyle it yourself.

**Comment by No1e** [comment]
Hi Bebenins. 

Sorry, didn't know that I have to post question there.

Anyway, I found workaround for "hiding" arrow. Simply by setting the BorderBrush to the respective color that is used in theme. 

Best regards,
Novak
