### ISSUE TITLE
Dialoghost background does not fade out, disappears immediately

### ISSUE THREAD

**Issue by lloydkuijs** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1388]
I tested from version 2.6.0 and up of the pre-release 3.0 versions with a normal dialoghost setup and it seems that after **version 3.0.0-ci460** the dialoghost background disappears immediately without any fading.

Maybe this is related to issue #1364 ?

I have tried it with and without **CloseOnClickAway**, this does not seem to be the issue either. 

The test was done in a clean WPF project with only a dialoghost in the MainWindow after noticing the problem in a larger project.

**Comment by Mrxx99** [comment]
Seems like you are right, this seems to be related to #1364

**Comment by jespersh** [comment]
The fading background is getting a notorious reputation.
@Mrxx99 it was last fixed in pull #1045. You can figure out what does done there
