### ISSUE TITLE
TimePicker RTL Flips the clock 

### ISSUE THREAD

**Issue by thedude61636** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1400]
when setting the flow direction on the window TimePicker flips the clock horizontally, which isn't correct as all clocks have the 9 on the left and 3 on the right 
![image](https://user-images.githubusercontent.com/13031288/64247732-221cfa80-cf18-11e9-8f01-02e235bf1305.png)

Setting the flow direction to LTR on the widget itself fixes the clock but breaks the hint 
![image](https://user-images.githubusercontent.com/13031288/64247834-58f31080-cf18-11e9-9a3b-a08e0d9e16aa.png)

i think this is simple enough to fix by setting the flow direction of the clock popup to ltr

**Comment by Keboo** [comment]
In addition, setting RTL should not re-order the AM/PM buttons.
