### ISSUE TITLE
Cannot find resource named 'Primary200'.

### ISSUE THREAD

**Issue by Gaz83** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1401]
Just having a play and I seem to have an issue when using Custom Palette Hue's.
I took a look at the wiki

[https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Custom-Palette-Hues](url)

I copied and pasted the the code into my App.xmal and noticed all the brushes had intellisense issues with errors like "Resource 'Primary200' is not found.

Thought maybe it was resharper so tried running my app anyway and got this exception.

> Exception: Cannot find resource named 'Primary200'. Resource names are case sensitive.

So I created a brand new WPF app, copied the code from the link and still the same issue.
Running VS 16.2.3 and ReSharper 2019.2

**Comment by Mrxx99** [comment]
Does it only complain in the designer or does it fail at runtime?

**Comment by Gaz83** [comment]
As mentioned above, it happends in both the designer and runtime.

In the wiki it uses this,
 `<ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/MaterialDesignColor.Indigo.Named.xaml" />
                    </ResourceDictionary.MergedDictionaries>`

but if I change to this, it works fine.
 `<ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/themes/recommended/primary/materialdesigncolor.indigo.xaml" />
                    </ResourceDictionary.MergedDictionaries>`

So anything not in the 'Recommended' path seems to give me an issue.

**Comment by jespersh** [comment]
The wiki is mistaken here.

The files with the names matching like: `Themes/MaterialDesignColor.XXXXX.Primary.xaml` contains/sets the Primary200
Like Amber:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/4f86bb710deddabebd035a1a4000208caa00d12a/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.Amber.Primary.xaml#L7

If you import a recommended like Amber, then it imports the Primary theme like above:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/4f86bb710deddabebd035a1a4000208caa00d12a/MaterialDesignColors.Wpf/Themes/Recommended/Primary/MaterialDesignColor.Amber.xaml#L6

One last that contains sets Primary200 is in `Themes/MaterialDesignColor.XXXXXX.xaml`:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/4f86bb710deddabebd035a1a4000208caa00d12a/MaterialDesignColors.Wpf/Themes/MaterialDesignColor.Amber.xaml#L7

You can check https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MaterialDesignColors.Wpf/Themes

**Comment by Keboo** [comment]
@Gaz83 thank you for pointing this out. It is an issue with the documentation. With the 2.6.0 release we added more control over the theming APIs. Take a look at the [Advanced Theming wiki page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming) to see some examples. The goal was to make doing custom color themes easier.

**Comment by Gaz83** [comment]
Thanks for the info!

**Comment by MichelMichels** [comment]
Closed due to: original question answered.
