### ISSUE TITLE
Persian Calendar Support

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1403]
Hi.
I saw The library Demo App and try so much to figure is the Persian calendar supported or not and i think there is not! 

We use this library alot and we needed so please add Persian Calendar to the library.

**Comment by jespersh** [comment]
Keep an eye on #677 and you're free to make an attempt at a pull request. I don't have the understanding of how the Persian calendar works to create it, but you do ;-)

**Comment by Keboo** [comment]
@HamidRezaAshkiyan I think this was resolved by #1080 if there are still issues let me know.
