### ISSUE TITLE
xmlns:domain="clr-namespace:MaterialDesignColors.WpfExample.Domain"

### ISSUE THREAD

**Issue by spy0505** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1404]
xmlns:domain="clr-namespace:MaterialDesignColors.WpfExample.Domain"   is not found

**Comment by jespersh** [comment]
Please put some effort into creating an issue on here. No one has any idea what you're trying to do and when or where you're getting this error

**Comment by spy0505** [comment]
![5d00526b015715ef7860fcc205d6503](https://user-images.githubusercontent.com/28008268/64413672-7f55af00-d0c4-11e9-9c9c-97a08e4c9bbe.png)

**Comment by spy0505** [comment]
@jespersh

**Comment by jespersh** [comment]
@spy0505 Are you trying to build the MaterialDesignDemo project?
Please use the chat instead if you don't know how to use github https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit
