### ISSUE TITLE
Custom global styles for TextBox, Combobox , Button etc. in App.xaml not working

### ISSUE THREAD

**Issue by Gerardo-Sista** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1405]
Hello everyone!
I 'm using MahApps.Metro integration (and it works fine) with this new code:
[https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1335](url)
But when I want to set some **global styles in App.xaml**  some works and some doesnt work.
**This simple style, for label, works fine for example:**
`<Style TargetType="{x:Type Label}">
                <Setter Property="FontFamily" Value="Segoe UI" />
                <Setter Property="FontSize" Value="26" />
</Style>`
![image](https://user-images.githubusercontent.com/34858800/64424372-32181400-d0a9-11e9-9c30-6b3906de4e3a.png)
(in figure label is correct, and other controls have local settings, not styles)

But when I create the **same style for Button, TextBox, Combobox** etc. 
`<Style TargetType="{x:Type Button}">
                <Setter Property="FontFamily" Value="Segoe UI" />
                <Setter Property="FontSize" Value="26" />
</Style>`
control is no more rendered as materialdesign control but a very ugly gray standard element.
![image](https://user-images.githubusercontent.com/34858800/64424489-8ae7ac80-d0a9-11e9-9919-1efd00516abe.png)

Why only for label control this works? Is it a bug or am I doing something wrong?
Thank you.

**Comment by mgnslndh** [comment]
You need to base your style on the one you wish to override. Like this:

```
<Style TargetType="{x:Type Button}" BasedOn="{StaticResource MaterialDesignRaisedButton}>
    <Setter Property="FontFamily" Value="Segoe UI" /> 
    <Setter Property="FontSize" Value="26" />
</Style>
```

If you wish to override the [default style for `Button`](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/80e7aff8daf93de593aa48786aa435f5546bff48/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Defaults.xaml#L49) you basically needs to find out what *is* the default style and base your new default on the same base style.

**Comment by Gerardo-Sista** [comment]
Hello @mgnslndh ,
Thank you for your kind and fast support: it works everything as excpected now!!!
(I had 99.9% suspect I was doing something wrong.... now it's 100% clear it was my issue)

Thanks!  :)
