### ISSUE TITLE
Source Code how to open MainDemo.Wpf

### ISSUE THREAD

**Issue by spy0505** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1406]
I want to look demo,but i don't know how to open.I have vs2019

**Comment by jespersh** [comment]
Use the chat https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit 
Your questions are not issues

**Comment by Keboo** [comment]
See [this wiki page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source) for more details.
