### ISSUE TITLE
Obsolete Warnings in version 2.6v

### ISSUE THREAD

**Issue by AdarshRise** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1409]
These are the Warnings I got by compiling the MainDemo.wpf directly{ without any change}, I got this from the 2.6 release source code.
I believe you are already aware of this, and probably this{warnings} won't be there in the version 3.0v.

I am new to WPF, If this problem has already been solved, It would be good to give a 2.6.1v release just by fixing these 3 warnings. 

![image](https://user-images.githubusercontent.com/31347367/64490204-35152f00-d278-11e9-9d96-45cad27ce8c2.png)

Thanks, For the awesome Library =).

**Comment by ahmediddma** [comment]
it's going to be replaced in v3 you can try it right now by installing the prerelease nuget

**Comment by Keboo** [comment]
Will be handled by #1301
