### ISSUE TITLE
Group Box Header Template

### ISSUE THREAD

**Issue by No1e** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1410]
Dear MDX Team,

I am not sure if this is a bug/issue, so my apologies for writing this in the wrong place. 

I tried to customize the header of GroupBox. In the following picture you can see:
1. How it is by default
2. What I want to achieve
3. What I get
![image](https://user-images.githubusercontent.com/25526781/64518579-b8736680-d2f2-11e9-8f6a-d609ed57c236.png)

I tried also to look at forums, but did not found anything.

What I did in XAML, is set BorderBrush to 0 and defined a custom header template, but there is some margin coming from somewhere, and that is what I want to remove. I assume that you are using ColorZone here, but I am not sure. Anyway, the same I want to achieve for ColorZones.

Could you give me some info? Is this bug/issue or mistake from my side?

Best regards,
Novak

**Comment by Keboo** [comment]
Hi @No1e 

Yes, the GroupBox header [does use a ColorZone](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e4a345cb90a09d6a004a46f2ab834a94e898490e/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.GroupBox.xaml#L37). There is some default Padding that is getting applied [that defaults to 9 on all sides](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e4a345cb90a09d6a004a46f2ab834a94e898490e/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.GroupBox.xaml#L26). This property also propagates down [to the ColorZone](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e4a345cb90a09d6a004a46f2ab834a94e898490e/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L455) as well.

So in both cases you should simply be able to set the `Padding` property to 0 (or whatever size makes sense for your app).

**Comment by Keboo** [comment]
Closing for now. Let me know if there are any further questions.
