### ISSUE TITLE
VS Live Visual Tree stuck at DialogHost (re-regression)

### ISSUE THREAD

**Issue by jespersh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1412]
The issue reported in #317 and #1005 has made a return.
I suppose it was introduced by pull #1364 
Can we unittest our way out of this?

**Comment by Keboo** [comment]
@jespersh which version of the code are you seeing this on? Also which version of Visual Studio are you running?

I am not able to reproduce this with the [latest code](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/e4a345cb90a09d6a004a46f2ab834a94e898490e) on VS2019 16.2.3

**Comment by jespersh** [comment]
I'm testing on commit e4a345cb (same as your link) with 16.2.4

Here I'm trying to select the "Welcome to Material.." header
![image](https://user-images.githubusercontent.com/1004198/64758828-e3013180-d535-11e9-817a-d9a6a548790e.png)

This works if I pick the commit before (testing at 7f4ed582)
![image](https://user-images.githubusercontent.com/1004198/64759065-7a668480-d536-11e9-9f27-05f432528dd9.png)

**Comment by Keboo** [comment]
@jespersh I believe this is resolved now. I worked through it [on my live stream](https://studio.youtube.com/video/-e4CxKCP-rs/edit) last night (about the last hour of it). I am not sure there is a great way to unit test it, but I am open to suggestions.
