### ISSUE TITLE
MaterialDesignToolRadioButton isn't styled the same as ToolBar Button

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1413]
Inside ToolBar XAML there's a nice Button theme at the very bottom:
`<Style x:Key="{x:Static ToolBar.ButtonStyleKey}" TargetType="Button">`

MaterialDesignToolRadioButton style comes from RadioButton XAML and it's missing key settings:

- Padding (should be 16 to make the button square)
- CornerRadius (should be 2 to match ToolBar Button)

But there are more settings that don't match

Also, the un-checked radio button should **not** be grayed out.  It makes it look disabled.

Would it make more sense to relocate MaterialDesignToolRadioButton style to ToolBar XAML?  I have never seen standard RadioButtons in toolbars so I think it makes sense to make styling automatic if you add a RadioButton to a ToolBar.

In any case, the styling should be made consistent.

**Comment by nicolaihenriksen** [comment]
I believe this was fixed by #562. Closing issue; please re-open if you disagree.
