### ISSUE TITLE
Latest NuGet package throws warning NU1602

### ISSUE THREAD

**Issue by SirUppyPancakes** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1415]
This issue can be observed by creating an empty project and adding the latest NuGet package (2.6.0 at the time of this writing). The warning can then be observed in the Error List window:
```
MaterialDesignThemes 2.6.0 does not provide an inclusive lower bound for dependency MaterialDesignColors (> 1.1.3 && < 2.0.0). An approximate best match of MaterialDesignColors 1.2.0 was resolved.
```

Based on this StackOverflow post (https://stackoverflow.com/questions/46254362/how-to-correct-dotnet-restore-warning-nu1604-does-not-contain-an-inclusive-lowe) it would seem that the way to fix this would be to modify the current relevant portion of the NuSpec:
```
    <dependencies>
      <dependency id="MaterialDesignColors" version="(1.1.3, 2.0)" />
    </dependencies>
``` 
to include a inclusive lower bound (using the interval notation specified in the docs https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) like so:
```
    <dependencies>
      <dependency id="MaterialDesignColors" version="[1.1.3, 2.0)" />
    </dependencies>
```

This would also be a good time to change it to include `2.0` if that was the original intention as well.

Overall, not an issue that causes any real problems, other than driving you crazy by constantly popping up the Error List window in VS whenever you build 😉

**Comment by Keboo** [comment]
Good catch. This was a mistake on my part.
We actually want to set the _inclusive_ lower bound to be 1.2.0. I believe we want the upper bound to still be exclusive 2.0 since a major version rev will mean breaking changes.

**Comment by rgomez90** [comment]
@Keboo I've given it a try
