### ISSUE TITLE
Dark Theme ScollViewer WPF failed

### ISSUE THREAD

**Issue by kelvin1782** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1418]
how to fix scrollviewer wpf in dark theme of material design.
see attached image.

dark.xml
![darktheme](https://user-images.githubusercontent.com/54794393/65308467-b8118000-dbbc-11e9-8442-604350bc9e46.png)
![darkcode](https://user-images.githubusercontent.com/54794393/65308476-bcd63400-dbbc-11e9-82a1-79d9203aa11e.PNG)

light.xaml
![lighttheme](https://user-images.githubusercontent.com/54794393/65308488-c1025180-dbbc-11e9-8abc-c4b0c38f2f40.png)
![lightcode](https://user-images.githubusercontent.com/54794393/65308498-c52e6f00-dbbc-11e9-9398-455a11443699.PNG)

**Comment by Keboo** [comment]
Hi @kelvin1782 I am not able to reproduce your issue from that. 

- Which version of the library are you using?
- Do you have any other WPF theming libraries installed?
- Are those resource dictionaries in the App.xaml?

If you are able to provide a project that reproduces the project that would be the most helpful.

**Comment by kelvin1782** [comment]
Hi @Keboo,


I am using the latest version of the library.
Download the attached sample. 
[WpfApp1.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/3640346/WpfApp1.zip)

**Comment by Keboo** [comment]
@kelvin1782 there was an issue with the [getting started documentation](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started#configuring-your-windows) that did not make it obvious that you also need to set your Window brushes. I have updated the docs. What you need to do is setup a couple brushes on your window
```xaml
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        mc:Ignorable="d" 
        Background="{DynamicResource MaterialDesignBackground}"
        TextElement.Foreground="{DynamicResource MaterialDesignBody}"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <ScrollViewer HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">
            <Canvas Height="5000" Width="5000" Background="Black" Margin="50"/>
        </ScrollViewer>
    </Grid>
</Window>
```

**Comment by kelvin1782** [comment]
that works. thank you!
