### ISSUE TITLE
Snackbar should support at least two lines of text.

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1422]
From the [specification](https://material.io/components/snackbars/#specs):

> Snackbars contain a text label that directly relates to the process being performed. On mobile, the text label can contain up to two lines of text.

[Example](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1568406561463%2Fassets%2F1-xoqfCjbmAnpAKbFVG7AIjqShi_vq_AM%2Funderstanding-snackbars-text-2-lines.png)

The current issue appears to be the [hard coded MaxHeight](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Snackbar.xaml#L81). We should increase this so that at least two lines of text fit.

Also ensure that the action button remains centered inside of the message.

Finally add some example to the demo application showing off this functionality. Utilizing the existing snackbars is acceptable for this.

**Comment by rgomez90** [comment]
@Keboo I could work on this

**Comment by Keboo** [comment]
@rgomez90 Great! let me know if you need any assistance.

**Comment by rgomez90** [comment]
@Keboo done!

* Changed `MaxHeigth` to 72. This will allow up to 4 lines of text. After testing I think button remains centered without any changes.

* Changed wrap mode, since I think it's not good when cutting words by wrapping.

* Updated samples (Example 2)

**Comment by Taschenbuch** [comment]
Actually, it already supported 2 lines. When the text line was too long it wrapped the text into the 2nd line. My Problem was, that it did not support line breaks: for example to show a message like that:

**This path is invalid:
C:/bla/myFile.txt**

because this looks ugly, when you dont insert a line break after **invalid:**:

**This path is invalid: C:/bla
/myFile.txt**

**Comment by grafanauser** [comment]
Update:
I just noticed, that **this was working in version 2.6.0**. When I had a long line of text, it wrapped into the 2nd line. 

But now i use the preview version to fix some other issues. And now the snackbar does not wrap the text into the second line anymore. instead it cuts the end and adds ".." to stay in a single line.

So some changes between 2.6.0 and 3.xx broke it.

**Comment by vekanoid** [comment]
To make it working for arbitrary number of lines, just delete MaxHeight setter for ContentPresenter in SnackbarMessage style:

`MaxHeight="{Binding RelativeSource={RelativeSource AncestorType={x:Type wpf:Snackbar}}, Path=(wpf:SnackbarMessage.ContentMaxHeight)}"`
