### ISSUE TITLE
Snackbar should allow placing the action button on its own line.

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1423]
From the [specification](https://material.io/components/snackbars/#specs)

> If an action is long, it can be displayed on a third line.

[Example](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1568406561463%2Fassets%2F11e9M-CnUBfAefLLAMtckb_opQih-E3Gm%2Funderstanding-snackbars-text-2-lines-longer-action.png)

To do this we should do the following (this assumes #1422 has already been completed):
[ ] - Add a new enum dependency property to the Snackbar control. The enum should have the values `Inline`, `SeparateLine`, and `Auto`. The default of the property should be `Auto`.
[ ] - When the property is set to `Inline` the action button should display to the right of the message (as it works now).
[ ] - When the property is set to `SeparateLine` the action button should be moved below the message and right aligned.
[ ] - When the property is set to `Auto` we should put in a trigger that only moves the action button onto its own line when there are two or more lines of text. We can detect this case by simply watching the height of the Content.
[ ] - Ensure that an example of each is present in the demo application.

**Comment by rgomez90** [comment]
Actually working on #1422.

Can take a look at this when finished.

**Comment by christyjacob4** [comment]
Hey @Keboo  can I start working on this?

**Comment by Keboo** [comment]
@rgomez90 are you still planning on working on this one?

**Comment by rgomez90** [comment]
Yes! I was waiting for you to review #1432

**Comment by Keboo** [comment]
@christyjacob4 thanks, I think @rgomez90 has this one already

**Comment by christyjacob4** [comment]
Okay sure @Keboo thanks
