### ISSUE TITLE
Text with first underscore doesn't get populated in ComboBox

### ISSUE THREAD

**Issue by ranjan-ranjan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1427]
Text with first underscore doesn't get populated in ComboBox

Steps to reproduce: Populate a ComboBox with `8z_Without_CQG`, `8z_Without_CQG`, `7z_Without_CQG`, `6z_Without_CQG`, `5z_Without_CQG`, `4z_Without_CQG`, `3z_Without_CQG`...

When we click on ComboBox, it will show as follows:
![issue](https://user-images.githubusercontent.com/16834561/65515132-5161ce80-defc-11e9-906a-b83c5838cd9a.png)

Expected would be: `8z_Without_CQG`
Currently its showing: `8zWithout_CQG`

**Comment by jespersh** [comment]
This is most likely because how WPF is handling the first `_` as a accesskey.

There's various ways to fix it. Here's some material:
https://stackoverflow.com/questions/9403782/first-underscore-in-a-datagridcolumnheader-gets-removed
https://stackoverflow.com/questions/9684619/label-doesnt-display-character

**Comment by ranjan-ranjan** [comment]
Thanks a lot for prompt reply and correct answer.

**Comment by ranjan-ranjan** [comment]
Its still present for Combobox

**Comment by ranjan-ranjan** [comment]
@Keboo Kindly fix this issue in next release.

**Comment by deepakG86** [comment]
Similar issue exists when we use underscore in Category when using grouping in the combo box
![image](https://user-images.githubusercontent.com/6168432/189401616-a230169b-11dc-4fdd-8c91-caefd7cc5f8c.png)
notice how the underscore in Investigation_1 is missing in the UI
