### ISSUE TITLE
Icons don't seem to show in .net Core 3 app.

### ISSUE THREAD

**Issue by Gaz83** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1437]
I have been using the toolkit fine in a WPF app, but with .net core 3.0 being release I thought I would create my first app.

First issue I have noticed is that the icons are not showing. Is there an extra step required for .net core?

The only other difference in the app is the MVVM framework. WPF, I was using prism with unity and this app I am using MVVM light.

repo link with the issue.
[https://github.com/Gaz83/MaterialDesignIconIssue.git](url)

**Comment by jespersh** [comment]
This wasn't obvious, but you're using `System.Windows.Controls.MenuItem` instead of your own model
![image](https://user-images.githubusercontent.com/1004198/66024363-f62f6d80-e4f3-11e9-81e5-afa49cf0a0a6.png)

I changed it to `Model.MenuItem` and then the icons showed up

**Comment by Gaz83** [comment]
ah man! something so stupid. That is what happens when you copy and paste a class into the bottom of another class and then get ReSharper to move it into its own file. All just to save time on adding a new class in Visual Studio.

Thanks for the help and sorry for the waste of time.

**Comment by jespersh** [comment]
You can postfix your `MenuItem` class with `Model` to call it `MenuItemModel` to avoid this again
