### ISSUE TITLE
How to disable shadow globally

### ISSUE THREAD

**Issue by laolarou726** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1451]
Does MaterialDesignXamlToolKit support to disable the shadows for all controls? Because the shadow implement is not efficient enough. It will cause high memory consumption.

**Comment by mgnslndh** [comment]
I do not doubt you but I am interested in how you have confirmed that the shadows cause high memory consumption?

**Comment by laolarou726** [comment]
I'm not sure, but I got a relatively low fps for my application's animation.

**Comment by Keboo** [comment]
Currently there is not a "global" switch to disable shadows. On a case by case basis you can use the ShadowAssist.Depth property set to Depth0 to turn shadows off for a given style, but this would need to be applied to every style that is in use in your application.

**Comment by Keboo** [comment]
Closing for now as there are no plan to introduce a global switch for controlling all shadows.
