### ISSUE TITLE
Demo snackbar text black against a dark background

### ISSUE THREAD

**Issue by jespersh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1454]
Not sure when this happened:
![image](https://user-images.githubusercontent.com/1004198/66300158-15b00700-e8f5-11e9-90d1-0e6b4a2b8762.png)

Used to look like this:
![image](https://user-images.githubusercontent.com/1004198/66300262-3aa47a00-e8f5-11e9-9a6b-7ccea67c9fad.png)

**Comment by Keboo** [comment]
Thanks for logging this. Pretty sure I broke it with the typography changes
