### ISSUE TITLE
ComboBox flyout in GridView is transparent if focus is not at current row.

### ISSUE THREAD

**Issue by grandangelo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1459]
As per title, clicking on a ComboBox within a GridView row which is not in focus gives a transparent flyout background. Clicking twice removes transparency. Outside a GridView, behavior is as expected.
Minimum code (App.xaml, main view, view model) to reproduce is available at [StackOverflow](https://stackoverflow.com/questions/58298871/wpf-material-design-combobox-flyout-issue).

Thank you for this projects.

**Comment by Drewfyre** [comment]
I have the same issue on a DataGridComboboxColumn. First time the combobox is clicked it has a transparent background. The second time it renders correctly.

**Comment by KonradPsiuk** [comment]
same here, It seems to work ok once using materialDesign:DataGridComboBoxColumn

**Comment by grandangelo** [comment]
Closed with [3.1.0](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1576)

**Comment by X-elais** [comment]
It seems the problem still exists on 3.1.3.1513 version.

Using materialDesign:DataGridComboBoxColumn does not solve this issue for me.
