### ISSUE TITLE
TextFieldAssist.HasClearButton disable Focus for the button

### ISSUE THREAD

**Issue by Aurelio67** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1464]
Hi, 
When I'm inside a field, if I move with the tab the focus goes to the button and not to the next field, is it possible to disable the focus of the Clear button?

Thanks a lot
Aurelio

**Comment by ColossalMoose** [comment]
I assume that the fix for this would be to simply set Focusable="false" on the Part_button for the relevant styles? Would there be any reason to expose the property to be settable?

**Comment by Aurelio67** [comment]
Many Thanks Colossal Moose
