### ISSUE TITLE
Feature Request: Make Badged Size Configurable

### ISSUE THREAD

**Issue by wwarby** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1466]
The Badged control does exactly what I want. The only problem with it is I want to use it to adorn a poster image, and it looks a bit daft in that context because it's so small. I went looking for the option to make the font size bigger and found it's hardcoded to 11. I wonder if you'd consider making the font size and padding configurable parameters?

**Comment by Keboo** [comment]
@wwarby though I am not opposed to accepting some configuration on this, I am not sure it is needed. The `Badge` property itself allows for arbitrary content. So you can simply embed your own `TextBlock` control and change the FontSize there.

**Comment by wwarby** [comment]
ah - didn't realise that! I just started with the example in the demo that had a number in it and assumed that was pretty much all it could do - in that case, I'll do as you suggest - by all means disregard this request, and thanks very much for the prompt reply!
