### ISSUE TITLE
NumericUpDown from Mahapps has Mahapps validation Template 

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1473]
NumericUpDown from Mahapps has Mahapps validation Template and not the MaterialDesignInXamlToolkit one

**Comment by Keboo** [comment]
@ahmediddma what version of this library do you have installed? Which version of MahApps do you have installed? And are you targeting .NET Framework, or .NET Core?

**Comment by ahmediddma** [comment]
the latest MaterialDesignInXamlToolkit nuget preview build from azure  with mahapps 1.6.5
