### ISSUE TITLE
Chip mouse click event not bubbling

### ISSUE THREAD

**Issue by MovGP0** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1474]
## Current behavior

Given I have a Chip like: 

```xaml
<materialDesign:Chip 
    Content="{Binding Header}" 
    Command="{Binding Command}" 
    DeleteCommand="{Binding DeleteCommand}" 
    IsDeletable="True" />
```

When clicking the chip, the commands get executed. However, Given I have something like:

```xaml
<some:ParentControl Command="{Binding Command}" Click="OnClick">
    <materialDesign:Chip 
        Content="{Binding Header}" 
        DeleteCommand="{Binding DeleteCommand}" 
        IsDeletable="True" />
</some:ParentControl>
```

Then the command of the parent control and the click event does not trigger, besides there is no handler registered in the chip. 

## Expected behavior

The Chip should bubble the event to the parent element, when the click event is not handled and/or no handler is registered. 

## Version Info

- MaterialDesignThemes 3.0.0-ci663 (.NET Core 3.0)

**Comment by MovGP0** [comment]
See also: https://stackoverflow.com/questions/4698047/event-bubbling-for-custom-event-in-wpf

**Comment by MovGP0** [comment]
Apparently this is because this control derives from ButtonBase, and buttons prevent bubbling.

**Comment by JianpingCAI** [comment]
Hi,
Is there a solution to this issue?
