### ISSUE TITLE
Everything is bigger/more spaced in .NET Core 3

### ISSUE THREAD

**Issue by e-projectsrl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1477]
I'm trying to port my existing app from .NET Framework to .NET Core 3
I'm using the latest pre-release MaterialDesignThemes package, which supports .NET Core

The problem is that, while the app itself works, everything is bigger/more spaced in the .NET Core version.

Here is a side by side screenshot:

![image](https://user-images.githubusercontent.com/56260765/67094403-1463c180-f1b4-11e9-9e20-db751aca4079.png)

Why does this happen? The two apps' code is identical, only thing that changes is the framework and the version of the MaterialDesignThemes package.

**Comment by jespersh** [comment]
What is your screen DPI aware?

**Comment by e-projectsrl** [comment]
After some more testing, turns out the issue is this line in my App.xaml:

`<Style BasedOn="{StaticResource MaterialDesignBody1TextBlock}" TargetType="TextBlock" />`

which I was using to set the default appearence of text blocks (font, size, weight, etc.) in the entire app. Maybe the `MaterialDesignBody1TextBlock` changed in v 3.x?

Anyway, sorry for wasting your time, by removing that line and setting the style in each window it works correctly now, so this issue can be closed I think.

**Comment by jespersh** [comment]
> Maybe the style `MaterialDesignBody1TextBlock` changed in v 3.x?

Ya, see https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1301

**Comment by Keboo** [comment]
@e-projectsrl yea there are several typography changes in 3.0.0 to bring this library back in line with the latest material design specification. I don't have full release notes for 3.0.0 yet but [here is the commit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/974e65c7c4226a13856ba06c833597f5c9b6b953#diff-ee2f0330d7034037703b63cb07e52552) where the changes were made.

I suspect you just need to update your above style to either explicitly set a font size of 13, or switch out for something a little closer like `MaterialDesignBody2TextBlock`
