### ISSUE TITLE
Filled ComboBox is missing

### ISSUE THREAD

**Issue by mr-at0s** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1479]
Filled ComboBox is missing. It could look like this:

![filled-combobox](https://user-images.githubusercontent.com/28776933/67096702-f9478080-f1b8-11e9-8a43-aa31b14cfbd1.gif)

(sorry, gif has some artifacts)

**Comment by Keboo** [comment]
Docs for this here: https://material.io/components/text-fields/

**Comment by Keboo** [comment]
![FilledComboBox](https://user-images.githubusercontent.com/952248/77239296-6dd28100-6b96-11ea-820d-35565cba4859.gif)

**Comment by mr-at0s** [comment]
Just as an important note on pixel details: Margins and sizes are mostly incorrect. E.g., hint text should be centered vertically, "Some item" and "Item 2" are not aligned correctly on the left side, the arrow has to be centered, the arrow should change its direction on a click, overlay width is not correct (see left side), etc.

**Comment by Keboo** [comment]
Thanks @mr-at0s re-opening this issue to address those problems.

**Comment by Keboo** [comment]
@mr-at0s More updates here to try and get it closer to spec. 
![FilledComboBox](https://user-images.githubusercontent.com/952248/77864471-89b0d500-71dd-11ea-88d3-5c25b112f9a9.gif)
