### ISSUE TITLE
Error while build solution

### ISSUE THREAD

**Issue by insahamed** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1485]
'Unable to find project information for 'D:\SE Materials\Visual Studio\MaterialDesignInXamlToolkit-master\MaterialDesignThemes.Wpf\MaterialDesignThemes.Wpf.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.'

'The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.'

I'm getting these issues while build the solution.

**Comment by jespersh** [comment]
Did you install net core 3.0 sdk?
If you open cmd and enter `dotnet --info`

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
...
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
...
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by insahamed** [comment]
Yes. 3.0.100

**Comment by jespersh** [comment]
Could you navigate cmd into `D:\SE Materials\Visual Studio\MaterialDesignInXamlToolkit-master` and use 
```
dotnet build MaterialDesignToolkit.Wpf.sln
```

**Comment by insahamed** [comment]
That also same

D:\SE Materials\Visual Studio\MaterialDesignInXamlToolkit-master>dotnet build MaterialDesignToolkit.Wpf.sln

Welcome to .NET Core 3.0!
---------------------
SDK Version: 3.0.100

**Comment by Keboo** [comment]
@insahamed take a look at the [wiki page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source) for compiling from source code. Compiling this library from source code will typically require the latest version of Visual Studio along with the needed .NET Core and .NET Framework SDKs installed.
