### ISSUE TITLE
MultiBinding and MultiValueConverter

### ISSUE THREAD

**Issue by Exolithus** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1494]
I created the style as a copy of yours, but the error "I cannot set MultiBinding because I need to specify MultiValueConverter." Is returned to me, what should I do? If possible, please, in Russian, thanks

**Comment by Keboo** [comment]
Hi @Exolithus I would need more information on this. Which style are you trying to copy? What are your trying to do?
In WPF you [MultiBindings](https://docs.microsoft.com/dotnet/api/system.windows.data.multibinding?view=netframework-4.8) require either a StringFormat to be specified or a MultiValue converter added.
