### ISSUE TITLE
Radio button style same as toggle button

### ISSUE THREAD

**Issue by IRHAMidIR** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1503]
I wanna create radio button like "Material Design Action" style with grouping , and Just one of the radio button selected , In summary:‌ radio button with toggle button style and radio button behavior
i use DownCasting for this problem , but is smell code

            x.IsChecked =
                y.IsChecked =
                    i.IsChecked =
                      k.IsChecked = false;

            var toggleButton = (ToggleButton)sender;
            toggleButton.IsChecked = true;

Please Help

**Comment by jespersh** [comment]
Hi @IRHAMidIR, welcome! 

Could you possibly join our friendly chat with the issue? https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit
I am unsure how we can help here without asking 10 questions to get to the root of your issue and possibly why you're not using DataContext and a ViewModel

**Comment by Keboo** [comment]
Hi @IRHAMidIR you can see a sample of doing that [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/RadioButton/RadioButton.ToggleButtonStyle)
