### ISSUE TITLE
the property  "width"and "height" of {wpf:PackIcon} can not be found.

### ISSUE THREAD

**Issue by PuppyMeng** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1505]
![图片](https://user-images.githubusercontent.com/49509688/68456609-31caff00-0239-11ea-86a7-30fbfe55f2e1.png)
![图片](https://user-images.githubusercontent.com/49509688/68457064-55427980-023a-11ea-8f08-9e30b3ddea52.png)

the error means Unable to access or identify member”width“ /”height“。

**Comment by AmRo045** [comment]
Try this:
```xaml
<Style TargetType="{x:Type materialDesign:PackIcon}">
    <Setter Property="Control.Width" Value="24" />
    <Setter Property="Control.Height" Value="24" />
</Style>	
```

**Comment by PuppyMeng** [comment]
> 
> 
> Try this:
> 
> ```
> <Style TargetType="{x:Type wpf:PackIcon}">
>     <Setter Property="Control.Width" Value="24" />
>     <Setter Property="Control.Height" Value="24" />
> </Style>	
> ```

thanks a lot. That works！
