### ISSUE TITLE
If the leftdrawer contains treeviewer,how lets treeviewer srcoll when the treeview has toooo datas

### ISSUE THREAD

**Issue by Chinj123** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1507]
If the leftdrawer contains treeviewer,how lets treeviewer srcoll when the treeview has toooo datas

**Comment by jespersh** [comment]
Could you elaborate?

**Comment by Chinj123** [comment]
In the demo MainWindow has a leftdrawer which contains ListBox. In my program, i want use a treeview instead ListBox. when i add so many Nodes to the treeview, the bottom content of treeview is Incomplete display when ExpandAll.

**Comment by Keboo** [comment]
@Chinj123 the TreeView should have a built-in scroll viewer. Can you provide an example of what you are doing? Is the TreeView inside of a StackPanel?

**Comment by Chinj123** [comment]
you are right，-。-  thank you very much(i'm a rookie)

**Comment by Keboo** [comment]
@Chinj123 no problem, we were all rookies at some point.
