### ISSUE TITLE
Performance issues with DataGrid

### ISSUE THREAD

**Issue by Kryptolyser** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1510]
Hi there!
I really like your design and i'm using it for a bunch of my projects.
But recently I discoverd the following weird behavior:
The selection of cells in my DataGrid gets realy slow and laggy as soon as a popup (in this case tooltip or calendar popup) shows up. So you can use the DataGrid before you hover over one of my icon-btns or open the calender popup just fine. It is a really strange behavior that i never encountered before. I hope you can help me with this.
Thx for your time and work :)

### [Repository - Source Code](https://github.com/Kryptolyser/Dienstplan-2.0)

**Comment by mgnslndh** [comment]
Did you resolve your issue?

**Comment by Kryptolyser** [comment]
The problem just disappeared. Still don't know what caused it.

 
 

Gesendet: Montag, 02. Dezember 2019 um 16:44 Uhr
Von: "Magnus Lindhe" <notifications@github.com>
An: MaterialDesignInXAML/MaterialDesignInXamlToolkit <MaterialDesignInXamlToolkit@noreply.github.com>
Cc: Kryptolyser <yannik.dittmar@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [MaterialDesignInXAML/MaterialDesignInXamlToolkit] Performance issues with DataGrid (#1510)


Did you resolve your issue?
