### ISSUE TITLE
Window drag/resize is very laggy

### ISSUE THREAD

**Issue by braca** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1529]
Hi,

For some reason, our project is very laggy when moving or resizing the window.

I don't have any clue why it's happening, and the weirdest part is that if I change the text of a specific TextBlock (see Weird part steps :D above) it seems to fix the issue..

**Repro project:** https://github.com/braca/materialdesigninxaml-test

![slow](https://user-images.githubusercontent.com/800949/69443686-d58ed180-0d46-11ea-946b-f2018cc19fe1.gif)

**Steps to reproduce:**
1. Open and run the project
2. Move the window, or resize it
3. The move/resize is very laggy

**Workarounds**
I've found that if I set `TextOptions.TextFormattingMode="Display"` in our MainWindow it seems to minimize the issue

Another weird thing I've found is that if I change the text of a specific TextBlock (see Weird part steps :D above) it seems to fix the issue, to see this, follow these steps:

**Example:**
1. Open the project
2. Open View3.xaml
3. Comment line 19
4. UnComment line 21
5. Run the project
6. The move/resize should now work as expected

![fast](https://user-images.githubusercontent.com/800949/69443701-da538580-0d46-11ea-8e75-ef5405acb757.gif)

Thanks

**Comment by Keboo** [comment]
This looks like it is related to #746 
Switching to a local file for the font appears to help the issue

**Comment by Keboo** [comment]
@braca I believe this is fixed in the latest 3.0.0 release. Can you confirm by testing the following:
- Update to 3.0.0 release
- Change the FontFamily on your main window to use the new markup extension. ` FontFamily="{materialDesign:MaterialDesignFont}" `

**Comment by Keboo** [comment]
Closing for now as I believe this was addressed in the 3.0.0 release with the font changes. If this is not the case please let me know.
