### ISSUE TITLE
Support for mobile?

### ISSUE THREAD

**Issue by nkoteskey** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1535]
Love this toolkit and am recommending it to others but are there plans for cross platform mobile support through Xamarin forms?

**Comment by Keboo** [comment]
@nkoteskey currently no. I would like to expand onto other platforms but not likely to go to Xamarin.Forms simply because they have started to do material design with their visual feature, so there is less of a need there.

**Comment by nkoteskey** [comment]
Thanks for the prompt reply. I see, but I would argue what you are providing is far more extensive than what is being provided currently by Material Visual. I may be mistaken but besides your toolkit all icons have to be imported via another package/toolkit and that’s just the icons. It seems to me Material Visual is pretty bare bones but mostly can provide the basics, cross platform on mobile, in a consistent manner. Just a suggestion you pursue mobile support because I’m really admiring this toolkit. If you happen to change your minds I think there would be a lot of interest and in that case I’d love to be updated. Regardless, cheers and thanks for the reply. :)
