### ISSUE TITLE
MetroWindow Border has different color than the Title background

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1537]
MetroWindow Border has the accent color but the Title background has the primary color all should be the primary color

**Comment by Keboo** [comment]
This is the [default behavior of a MetroWindow](https://github.com/MahApps/MahApps.Metro/blob/87f40c57fb7b6a950fc6537f86cd9dd22ac57560/src/MahApps.Metro/Themes/MetroWindow.xaml#L560). For your app, you are free to override it to be the primary color if you wish.
On your Window you would set it up like (assuming MaterialDesign version 3.0.0 and MahApps version 2.0.0)
```XAML
<controls:MetroWindow ...
                      GlowBrush="{DynamicResource MahApps.Brushes.Highlight}"
                      BorderBrush="{DynamicResource MahApps.Brushes.Highlight}"
...>
```
