### ISSUE TITLE
The Hex Color Code is not right in Demo App

### ISSUE THREAD

**Issue by Noboroto** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1546]
I use Demo App to find colors and take its hex code, but many colors show the wrong code and I have used some alternative ways to get Hex Code, like this color, your app return **#0acc1** but the right code is **#00acc1**
<img width="43" alt="a" src="https://user-images.githubusercontent.com/48942146/70144220-09b3ac00-16d0-11ea-96e3-3b54752a108b.png">

**Comment by Keboo** [comment]
Can you please provide sample code or a reproduction project that shows what you are doing?

**Comment by Noboroto** [comment]
I used "Material Design in XAML Toolkit - Demo App" to get the Color Hex code, but many times, this code was wrong. In this picture, **#3a9f4** is wrong, and the right code is **#03a9f4**
![2019-12-05_LI](https://user-images.githubusercontent.com/48942146/70243621-86fd2080-17a5-11ea-9118-11d6b8d6dde0.jpg)

**Comment by jespersh** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/ea3c40b617fe955e5b8bbcb130382fb40b6a1940/MainDemo.Wpf/Converters/BrushToHexConverter.cs#L13

Change `X` to `X2`
