### ISSUE TITLE
 Prevent MaterialDesignThemes.MahApps from updating MaterialDesignThemes

### ISSUE THREAD

**Issue by Asugakoisi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1551]
When I updated MaterialDesignThemes in Visual Studio 2019 Community, the following error happened.

"Unable to resolve dependencies. 'MaterialDesignThemes 3.0.0' is not compatible with 'MaterialDesignThemes.MahApps 0.1.0 constraint: MaterialDesignThemes (> 2.5.1 && < 3.0.0)'."

**Comment by lwqwag** [comment]
I met the same error when i used MaterialDesignThemes.MahApps preview and mahapp preview packages

**Comment by Keboo** [comment]
This should be resolved in the latest preview NuGet packages.

**Comment by Asugakoisi** [comment]
> This should be resolved in the latest preview NuGet packages.

I tried that, but I was not able to update MaterialDesignThemes.MahApps.

Error message : 'Unable to find a version of 'MahApps.Metro' that is compatible with 'MaterialDesignThemes.MahApps 0.1.1-ci981 constraint: MahApps.Metro (>= 2.0.0 && < 3.0.0)'.

**Comment by Keboo** [comment]
You want to use https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.1.1-ci1232

**Comment by Asugakoisi** [comment]
> You want to use https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.1.1-ci1232

Thank you for this suggestion.
I was able to install https://www.nuget.org/packages/MaterialDesignThemes.MahApps/0.1.1-ci1232 by using Package Manager Console.
