### ISSUE TITLE
Can't set a background for DatePicker

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1552]
setting DatePicker background color to anything will have no effect and it will always be the default color

**Comment by Keboo** [comment]
I suspect this simply requires a [TemplateBinding](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/templatebinding-markup-extension) to be added to the `MaterialDesignDatePicker`.

**Comment by Tmus5** [comment]
I can take a look at this.
