### ISSUE TITLE
VS2019: Unable to load projects

### ISSUE THREAD

**Issue by burekas7** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1560]
Visual Studio 2019:
Trying to open this solution:
MaterialDesignToolkit.Wpf.sln
(Is it the right one or should I need to open another?)

Detailed Information:
Unable to locate the .NET Core SDK.
Check that it is installed and that the version specified in global.json (If any) matches the installed version.

* But it worked a few days before, so what could be changed?

In global.json:
```
{
  "sdk": {
    "version": "3.0.100-preview7-012821"
  }
}
```
![image](https://user-images.githubusercontent.com/13424257/70942783-1a610c00-2058-11ea-8571-8d43ac89b427.png)

**Comment by burekas7** [comment]
I have changed the global.json file content to be the same version as I have and it's working now:
```
{
  "sdk": {
    "version": "3.1.100"
  }
}
```

**Comment by jespersh** [comment]
You don't have 3.0.0 which it requires. I am guessing you're using a VS preview?

**Comment by Padanian** [comment]
Ssame problem here. Solved as per burekas suggestion. 3.1.1 is LTS .netcore release.

**Comment by Keboo** [comment]
Flagging this as something to update to. Given that 3.1 is the LTS version we should update the global.json file to support it.
