### ISSUE TITLE
DialogHost doesn't work in xaml designer

### ISSUE THREAD

**Issue by ahmediddma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1563]
An image from Dialogs.xaml in the demo app

![image](https://user-images.githubusercontent.com/51739190/71008562-7af05780-20f1-11ea-8bdd-99a6bf91387e.png)

**Comment by Keboo** [comment]
I believe this is not longer an issue with 3.0.0

**Comment by ahmediddma** [comment]
if you just opened the designer it will work but if you clicked any element in it it will throw the exceptions
![image](https://user-images.githubusercontent.com/51739190/71777627-30088800-2fab-11ea-91f8-82a08b029871.png)
