### ISSUE TITLE
WFP Demo App Issue

### ISSUE THREAD

**Issue by AmRo045** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1565]
Version: 3.0.0
[Preview](https://www.dropbox.com/s/qgajte2ibn0ikbz/p.mp4?dl=0)

**Comment by mgnslndh** [comment]
I can no longer reproduce this on the latest master.

**Comment by AmRo045** [comment]
As @mgnslndh mentioned, this issue can no longer reproduce in the latest version of the library. So I close the issue.
