### ISSUE TITLE
Empty ComboBox on first click not show popup

### ISSUE THREAD

**Issue by Pekshev** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1566]
If ComboBox have't items then ob first click PopUp not appears, but appears on second click. See gif
![ComboBoxBug](https://user-images.githubusercontent.com/12638819/71095527-d2f49000-21bd-11ea-84ac-2c84bed1fe9f.gif)

**Comment by jespersh** [comment]
Same as #1261
