### ISSUE TITLE
DatePicker Content Alignment

### ISSUE THREAD

**Issue by cdrfenix** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1568]
Using HorizontalContentAlignment in DatePicker control doesnt work.
I asked on the Gitter chat room and Keboo said it was probably a bug on this line:

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml#L376

Version: MaterialDesignThemes 3.0.0 
Framework: NetCore 3.0

Thanks !

**Comment by Keboo** [comment]
I suspect the fix is just a template binding to `HorizontalContentAlignment` on the linked line in the description.
