### ISSUE TITLE
Hardcode UniformCornerRadius in MaterialDesignToolToggleListBox Card

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1572]
In MD you should be able to do theming with one setting in Resources.
I'd like all my Cards to have a radius of 4 so I did this:
```
<Style TargetType="materialDesign:Card">
     <Setter Property="UniformCornerRadius" Value="4"/>
</Style>
```

But as a result it also propagated to `MaterialDesignToolToggleListBox` because the container is `wpf:Card`.
![image](https://user-images.githubusercontent.com/16761301/71421418-a969b780-2648-11ea-946a-c6326a6c3f65.png)

Since this is just a side effect and should never change anyway, could `UniformCornerRadius` be hardcoded for `MaterialDesignToolToggleListBox`?
While at it, please set it to 0 because this control is meant for a toolbar and buttons in the toolbar have radius of 0.

Thanks!

**Comment by Keboo** [comment]
It looks like this problem has been resolved. Checked it against the latest 3.1.0 preview NuGet. There is no Card inside of the visual tree on `MaterialDesignToolToggleListBox`

![image](https://user-images.githubusercontent.com/952248/77870055-42364300-71f5-11ea-819b-ea1db25e0d3a.png)
