### ISSUE TITLE
DialogHost Alignment doesn't work.

### ISSUE THREAD

**Issue by slad38** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1574]
Dialog Horizontal and Vertical Alignment changes doesn't work.
Dialog<materialDesign:DialogHost
  **HorizontalAlignment="Left"
  VerticalAlignment="Top"**
  IsOpen="{Binding IsSample4DialogOpen}"
  DialogContent="{Binding Sample4Content}"
  CloseOnClickAway="True"
  OverlayBackground="{DynamicResource PrimaryHueDarkBrush}">

![Dialog4](https://user-images.githubusercontent.com/36540486/71463968-1dcb6480-27c9-11ea-9220-7c7e4b6e9076.JPG)

**Comment by Keboo** [comment]
@slad38 `HorizontalAlignment` and `VerticalAlignment` apply only to the dialog host container itself not to the dialog. `HorizontalContentAlignement` and `VerticalContentAlignment` will re-position the dialog inside of the dialog host.

In that particular sample, the `DialogHost` is inside of a `XamlDisplay` control that is limiting its height. If you increase its height you will see the the `VerticalAlignment` change happen. As for he width, it is being controlled by a `ColumnDefinition`. If you increase the width there, you will see the `HorizontalAlignment` work as well.

**Comment by slad38** [comment]
Thanks. How to change Dialog Alignment?

**Comment by Keboo** [comment]
So there are only a few options for positioning it as it exists outside of the window (in a popup). There is a `DialogMargin` property which you can use to push it around.

**Comment by Keboo** [comment]
The other option is switch your DialogHost to use the `MaterialDesignEmbeddedDialogHost` and set the  `HorizontalContentAlignment` and `VerticalContentAlignment` properties to move it around. When using this optional style the dialog is part of the window, and thus cannot exceed the size of the parent window.
