### ISSUE TITLE
Method SetLightDark (Not works ?!)

### ISSUE THREAD

**Issue by Logikoz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1582]
After the last update this method and others were removed from "PaletteHelper", do you have any replacements?

**Comment by Keboo** [comment]
@Logikoz yes. In version 2.6.0 the theming API was updated and in 3.0.0 the obsolete methods were removed. See this wiki page for instructions on changing the theme at runtime. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Advanced-Theming#changing-the-theme

**Comment by Logikoz** [comment]
Thank you! ❤
