### ISSUE TITLE
ComboBox misclick

### ISSUE THREAD

**Issue by Waexu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1587]
If combobox is at the bottom of screen (so popup opens not under it but in front of it) mouse click automatically selects item under cursor. You can reproduce it even in demo app

**Comment by cpyfferoen** [comment]
I'm also experiencing this behavior
I have a datagrid with a combobox Column - and any Click that happens within the popup, but that popup is rendered over top of a ComboBox - triggers the ComboBox.

**Comment by jespersh** [comment]
Partially the same as issue #1684. See the comment about ClassicMode when placing comboboxes near the bottom of the application
