### ISSUE TITLE
DialogHost overlay margin not suitable for cards

### ISSUE THREAD

**Issue by Awsmolak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1592]
Maybe I'm taking the wrong approach or doing something outside of the "material" ethos. But when I use dialoghost at the card level, the "overlay" area of the UI encompasses the entire card along with the cards margin (ie. the paper underneath). It seems to me that it would look better and more correct to only have the area of the card surface grayed out.

I was attempting to do that and it seems like the only way would be to expose the margin property of **PART_ContentCoverGrid** in **MaterialDesignEmbeddedDialogHost** style. Is there an easy way to do that besides creating another wholesale copy of the style in my project or forking the code and adding a dependency property?

**Comment by Keboo** [comment]
Hi @Awsmolak 

Can you explain more about what you mean by "use dialoghost at the card level". 

To answer your other question, in WPF the only two options are full re-templating the control, or to modify the template at run-time. You can see an example of doing such a modification [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/b03dfedd1f9c06b9042f0b9dd2006faf1dd3555a/Utilities/Utilities).

**Comment by Awsmolak** [comment]
Well, if you wrap a card in a dialoghost you get something like this:
![Capture](https://user-images.githubusercontent.com/15197249/71906154-c6ad8400-3126-11ea-9fd9-17f48f2d7895.PNG)

Alternatively, if you use the dialoghost as the content inside the card you get this:
![Capture1](https://user-images.githubusercontent.com/15197249/71906227-e6dd4300-3126-11ea-9942-b8cea721dd20.PNG)

Of course, this is due to the margin/padding of the cards. (Which I have set to 16, like in the demo code). So, I could remove padding from all my cards and just set margins for the child content of each card to 16. Then host the content control _inside_ the card and not set its margin. But that seems a little unelegant.

**Comment by Awsmolak** [comment]
Bingo! Using the [runtime modifier classes](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/b03dfedd1f9c06b9042f0b9dd2006faf1dd3555a/Utilities/Utilities) along with the following code achieved what I was looking for:
```XAML
<materialDesign:DialogHost.Style>
<Style TargetType="materialDesign:DialogHost" BasedOn="{StaticResource MaterialDesignEmbeddedDialogHost}">
<Setter Property="commonUi:TreeHelpers.Modifiers">
	<Setter.Value>
		<commonUi:ModifierCollection>
			<commonUi:Modifier TemplatePartName="PART_ContentCoverGrid" Property="{x:Static Control.MarginProperty}">
				<commonUi:Modifier.Value>
					<Thickness>16,16,16,16</Thickness>
				</commonUi:Modifier.Value>
			</commonUi:Modifier>
		</commonUi:ModifierCollection>
	</Setter.Value>
</Setter>
</Style>
</materialDesign:DialogHost.Style>
```

I still think the argument could be made for adding a feature to make this more straightforward. 😉

**Comment by Awsmolak** [comment]
Update:
Weirdly, the above approach seems to work if I apply the style to a dialoghost within a control template setter in my app.xaml file. But if I try to apply the style to another dialoghost in my application it doesn't work! I have to explicitly put the setter into a style defined directly on the dialog host. 🤔

**Comment by Keboo** [comment]
@Awsmolak I would suggest that the best solution is to put the DialogHost inside of the card (that way the overlay properly gets clipped at the corners). I would then suggest that for the instances of this, you explicitly set the Padding on the card to 0 and simply set the padding on the DialogHost to 16.

Something like this:
```XAML
<materialDesign:Card Padding="0">
    <materialDesign:DialogHost Padding="16">
        <!-- Content here -->
    </materialDesign:DialogHost>
</materialDesign:Card>
```

**Comment by Awsmolak** [comment]
Thanks! That totally makes sense and seems kinda obvious now. It's easy to miss that kinda stuff when you're cranking away at 100 backlog items!

I rescind my argument for adding a cardhost margins attached property. However, it might be a good idea to start a wiki page for Cards to host tips like this...
