### ISSUE TITLE
MaterialDesignThemes.Mahapps package upgrade error

### ISSUE THREAD

**Issue by Swiftpaws** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1598]
When Uprading the MaterialDesignThemes.Mahapps packae from v0.1.1-ci873 to anyhting newer it fails with the message:

```
Detected package downgrade: MahApps.Metro from 2.0.0 to 2.0.0-alpha0660. Reference the package directly from the project to select a different version. 
 Okami.Ui -> MaterialDesignThemes.MahApps 0.1.1-ci879 -> MahApps.Metro (>= 2.0.0 && < 3.0.0) 
 Okami.Ui -> MahApps.Metro (>= 2.0.0-alpha0660)	Okami.Ui	C:\Users\kuglitsd\source\repos\Okami4\Okami.Ui\Okami.Ui.csproj	1	
```

The Dependency is set for MahApps.Metro from 2.0.0 but there is no 2.0.0 version of mahapps yet. Only the -preview 2.0 versions.

**Comment by ahmedflix25** [comment]
ignore the Dependency and it will work

**Comment by Swiftpaws** [comment]
Ignore dependency is a good tip, but not enough. For my project at least.

How to get it to work:
- Remove NU1605 from the "Treat warnings as errors" list in the Project settings (Build)
- Instal/Update-Package in the nuget console with args IncludePrerelease and IgnoreDependencies
