### ISSUE TITLE
TextBox Hint Customizing Problem

### ISSUE THREAD

**Issue by raimand13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1601]
Hi, i want make my Textbox Hint Horizontal Alignment to center, but i can't do it because of this lines in SmartHint.cs file. I try to copy all SmartHint templates and change this property but this code will change style properties after all XAML setters and i finally use an event trigger and storyboard to do this.

![image](https://user-images.githubusercontent.com/14857040/72070303-7721b080-32fe-11ea-8eb3-28f11f35374a.png)

My temporary solution is :

![image](https://user-images.githubusercontent.com/14857040/72070455-dd0e3800-32fe-11ea-8f9c-0874d3c94594.png)

**Comment by Keboo** [comment]
This will be fixed in tonight's 3.1.0 preview NuGet package.
