### ISSUE TITLE
Outline Combobox?

### ISSUE THREAD

**Issue by CodyWHageman** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1613]
So I have decided to go the route using outlined form fields. As of today this library only has Outlined/Filled features for Textboxes, PasswordBoxes and DatePickers. Is there anyway we could get one for ComboBoxes? I'm trying to do it custom myself but I'm just not quite advanced enough in XAML to quite figure it out :/. As of right now I just set BorderThickness to 2 and added some padding as well. It looks a little awkward with the Pretty outlined controls that already have the feature

**Comment by jespersh** [comment]
Suddenly found myself looking for this as well.

![image](https://user-images.githubusercontent.com/1004198/73937880-4ecda780-48e6-11ea-9112-3ea8b57c917e.png)
From https://material.io/components/menus/#exposed-dropdown-menu

**Comment by alekstrust** [comment]
I've created this file if you want to have the filled ComboBox style.

https://pastebin.com/8HW5pjfB

It is not perfect as I'm quite new to WPF.

**Comment by CodyWHageman** [comment]
As soon as I get time I will see what yours looks like. Thank you :)

**Comment by Keboo** [comment]
The Filled ComboBox is done in the 3.1.0 release. Updated the title to indicate that only the outline one remains.

**Comment by CorradoBarbero** [comment]
Please please somebody....

**Comment by Keboo** [comment]
Just barely got started on this, branch is [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/outlineComboBox) if anyone wants to help out. 

All that is done so far is to create a new template, copied from the existing one. Still need to actually create the outline stuff for it.
