### ISSUE TITLE
Remote Desktop Closes Dialogs

### ISSUE THREAD

**Issue by awebre** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1618]
This appears to be related to #299. 

I'm currently working on a project that makes heavy use of the DialogHost, specifically launching and listening to the dialog entirely from within the viewmodel (using `await DialogHost.Show(view, "dialogId")`). The issue we've come across is that when a Remote Desktop session is started on the machine where the app is running, the dialog closes and the task completes. This is particularly problematic because if a Remote Desktop session is interrupted while the user has a modal open, the modal is gone when they log back in and any "blocking" modals that should require user action will complete *without* any user action.

Apparently, the initiation of a Remote Desktop session causes the windows to be redrawn, which triggers the `Unloaded` and then the `Loaded` events of the dialog host. The current behavior (as I understand it) is to close the dialog host (allowing the dialog task to complete) on `Unloaded`, and then reload (but not reopen) the dialog host on `Loaded`.

In our case, we were able to modify the load/unload behavior such that the dialog host is reopened if it was "force-ably closed" (i.e. it was open when unload was called), without any negative side effects.

```csharp
        private void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
        {
            LoadedInstances.Add(this);
            if (_wasClosedOnUnloading)
            {
                SetCurrentValue(IsOpenProperty, true);
                _wasClosedOnUnloading = false;
            }
        }

        private void OnUnloaded(object sender, RoutedEventArgs routedEventArgs)
        {
            LoadedInstances.Remove(this);
            if (IsOpen)
            {
                _wasClosedOnUnloading = true;
                SetCurrentValue(IsOpenProperty, false);
            }
        } 
```
Note: we are using version 2.3.1, but this same behavior is present in the most recent version.

We also use the `_wasClosedOnUnloading` flag to stop the dialog task from being completed in a scenario where the dialog host was "force-ably closed". My changes to the dialog host are available [here](https://github.com/awebre/MaterialDesignInXamlToolkit/blob/40d3bf8cbebe4f0a8f29e01ec0819541c2f8ab6a/MaterialDesignThemes.Wpf/DialogHost.cs) (again, this v2.3.1, but the problem persists in the 3.0.1). I know this likely isn't an optimal solution for everyone, but I did want to bring some attention to it.

**Comment by Keboo** [comment]
Thank you for the clean write up. I have put it in the 3.1.0 milestone to take a closer look at the implications of making that change

**Comment by Keboo** [comment]
After some testing it appears that we don't actually need to set IsOpen to false on unloaded, so I have removed that line which I believe will also fix your issue.
