### ISSUE TITLE
Partial window freeze after monitor returns from sleep

### ISSUE THREAD

**Issue by dazzalogan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1620]
Hi,
I'm working on a wpf app. which employs your material design theme. VS2012 pro.
All is good until my monitor enters & then returns from either sleep or screensaver - after which my Window doesn't respond properly anymore.
If I then expand the window, the new areas are black & all MD-themed buttons don't respond, but other controls (e.g. image) which aren't themed still respond.

If I remove your theme, the app. works as it should after returning from monitor sleep or screensaver, so I'm pretty sure the issue is related to your theme.

Anyone else seen this?
Any work arounds/fixes?

Thank you

Regards,
D

**Comment by dazzalogan** [comment]
Hi,

Update on this:

If I have just a checkbox on a window, everything is fine.
If I then add a button, the Window corrupts after screensaver or monitor sleep.

So, it seems to be the MD-themed button causing the problems.

Regards,
D

**Comment by dazzalogan** [comment]
Hi,
I've tried the same project in VS2015 and VS2017. The issue prevails in both.

This is a tricky one because no exceptions are shown. Just the MD-themed controls seem to hang and the window becomes a little sluggish to drag around the screen.

This is quite a problem for me. I would really appreciate some help :-(

Thank you

**Comment by jespersh** [comment]
Could you try to set software rendering mode? Just to rule out your graphics card/drivers. Add this in your main/OnStartup
```C#
RenderOptions.ProcessRenderMode = RenderMode.SoftwareOnly;
```

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.renderoptions.processrendermode

**Comment by dazzalogan** [comment]
Hi Jespersh,

Oh, wow, that works!
I can't thank you enough - seriously. Been on this all day pulling my hair out.

But still, any idea why this happens?

**Comment by jespersh** [comment]
Hardware drivers/acceleration is outside my scope of knowledge. I only know they can be buggy around suspend/standby.

**Comment by ahmedflix25** [comment]
i saw this only with amd ryzen and windows 10

**Comment by dazzalogan** [comment]
Thanks again for your help, Jesper. I'm relatively new to WPF so I don't know these little secrets :-)

**Comment by foxiexianmo** [comment]
What a deep little secret ,I can't thank you enough!
