### ISSUE TITLE
Target Framework .Net 4.0 to make application running on Windows XP

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1621]
Dear all,

I'd like to use Material Design In XAML for an application running on Windows XP.
Is there a mean to recompile the library to target the .Net Framework 4.0 (or 4.1) which is the last .Net framework running on Windows XP ?

Thank you
Best regards

**Comment by Mrxx99** [comment]
There is an older net40 branch. I guess this is what you are looking for, I don't think the current version would be compatible

**Comment by gitjsdr26** [comment]
Dear @Mrxx99 ,
Do you know which branch I should use ?
[https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/branches/all](url)
Thank you.

**Comment by Mrxx99** [comment]
I meant this one: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/net40

**Comment by Keboo** [comment]
It is also worth noting that, they net40 branch is fairly old. I am happy for people to keep using it, but be aware that both Windows XP, and .NET 4.0 are no longer officially supported by both MS and this library.

**Comment by gitjsdr26** [comment]
Thank you all,
My application needs to support from Windows XP up to Windows 10.
I tried this branch with the demo on Windows XP, but it generates an error launching the .exe .
Thank you anyway.
Best regards.
