### ISSUE TITLE
ComboBox popup in ListView (GridView) is transparent

### ISSUE THREAD

**Issue by AgPeHaJIuH1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1624]
```
<ListView>

    <ListView.Items>
        <ListViewItem Content="1" />
        <ListViewItem Content="2" />
        <ListViewItem Content="3" />
    </ListView.Items>

    <ListView.View>
        <GridView>

            <GridViewColumn>
                <GridViewColumn.CellTemplate>
                    <DataTemplate>
                        <ComboBox Width="200">
                            <ComboBox.Items>
                                <ComboBoxItem Content="1" />
                                <ComboBoxItem Content="2" />
                                <ComboBoxItem Content="3" />
                            </ComboBox.Items>
                        </ComboBox>
                    </DataTemplate>
                </GridViewColumn.CellTemplate>
            </GridViewColumn>

        </GridView>
    </ListView.View>

</ListView>
```
Result

![image](https://user-images.githubusercontent.com/29563929/73359409-d34e7380-42b1-11ea-97df-a6574c818e95.png)

<PackageReference Include="MahApps.Metro" Version="2.0.0-alpha0660" />
<PackageReference Include="MahApps.Metro.IconPacks" Version="3.1.0" />
<PackageReference Include="MaterialDesignColors" Version="1.2.2" />
<PackageReference Include="MaterialDesignThemes" Version="3.0.1" />
<PackageReference Include="MaterialDesignThemes.MahApps" Version="0.1.1-ci858" />

**Comment by Keboo** [comment]
This should be fix in the 3.1.0 release. You can verify using the latest 3.1.0 NuGet package.
