### ISSUE TITLE
How can I add son control into the Card control

### ISSUE THREAD

**Issue by Stapxs** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1625]
Like the title said.How can I add son control into the Card control.

**Comment by jespersh** [comment]
Unfamiliar with "son control", but I assume you mean child control.

Just:
```
<Card>
  <Grid>
    ...
  </Grid>
</Card>
```

**Comment by Stapxs** [comment]
Sorry, I am not clear, I mean how to do it in the backend C # code.

Jesper Hansen <notifications@github.com> 于2020年1月30日周四 下午3:56写道：

**Comment by jespersh** [comment]
This is basically it:

```C#
Card somecard = FindSomeCard();
somecard.Content = new AnotherUserControl();
```

**Comment by Stapxs** [comment]
oh，Thank you very much.
