### ISSUE TITLE
Display Adorner error like MahApps does

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1626]
Dear All,
Is it possible to display TextBox Adorner error like MahApps does ?
See https://github.com/MahApps/MahApps.Metro/issues/3320

Thank you
Best regards

**Comment by Keboo** [comment]
@gitjsdr26 sorry for the long delay on this. I am not sure exactly what is being asked here. 
This library does support validation it appears different than the default MahApps validation because it is designed to confirm to Google's material design specification.

You can see an example in the [demo app](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Fields.xaml#L79-L89)

![image](https://user-images.githubusercontent.com/952248/77869251-b6231c00-71f2-11ea-9ac1-0868d8ea1c67.png)

**Comment by gitjsdr26** [comment]
@Keboo ,
Thank you for your reply.
I was wondering if it was possible for my purpose to display this kind of MahApps Adorner while using Material Design
![MahAppsAdronerLike](https://user-images.githubusercontent.com/60319431/78009812-d9101600-7341-11ea-8b4d-5c554e5c24fc.png)

Best regards.

**Comment by Keboo** [comment]
Hi @gitjsdr26 if you would prefer to turn off the material design validation template and switch back to the MahApps one, you can do something like this:
```xaml
 <TextBox Validation.ErrorTemplate="{StaticResource MahApps.Templates.ValidationError}">
```

**Comment by gitjsdr26** [comment]
Thank you @Keboo . I tried this but I get errors Resource not found despite having added
`<Source="pack://application:,,,/MahApps.Metro;component/Styles/ValidationErrorTemplate.xaml" />`
in my `ResourceDictionary`

Defining a new style also doesn't work
```C#
<Style x:Key="CustomTextBlock" BasedOn="{StaticResource MaterialDesignButtonTextBlock}" TargetType="{x:Type TextBlock}">
	<Setter Property="FontSize" Value="16"/>
	<Setter Property="FontWeight" Value="Regular"/>
	<Setter Property="Validation.ErrorTemplate" Value="{DynamicResource MahApps.Templates.ValidationError}" />
</Style>
```


Do you have an idea ?
Best regards

**Comment by Keboo** [comment]
@gitjsdr26 it looks like you are trying to define the style on `TextBlock` (which is readonly), and not on `TextBox`

**Comment by gitjsdr26** [comment]
Hi @Keboo ,
You are right.
I corrected my application ResourceDictionary like 
```
<!-- TextBox -->
<Style x:Key="CustomTextBox" BasedOn="{StaticResource MaterialDesignTextBox}" TargetType="{x:Type TextBox}">
	<Setter Property="Validation.ErrorTemplate" Value="{StaticResource MahApps.Templates.ValidationError}" />
</Style>
```
then my TextBox
`<TextBox Margin="0 0 0 0" Text="{Binding PCInterFrameDelay, NotifyOnTargetUpdated=True, NotifyOnSourceUpdated=True, UpdateSourceTrigger=PropertyChanged, Mode=TwoWay, NotifyOnValidationError=True, ValidatesOnDataErrors=True}" MaxLength="3" Style="{StaticResource CustomTextBox}"/>`

But when calling the error template, I get the error
`System.InvalidOperationException : ''{DependencyProperty.UnsetValue}' n'est pas une valeur valide pour la propriété 'ErrorTemplate'.'`

**Comment by Keboo** [comment]
Sorry for dropping the ball on this one. Based on the error message, it looks like it is failing to resolve the error template.

**Comment by gitjsdr26** [comment]
It's now working.
Thank you
