### ISSUE TITLE
Installing Material Design in UWP app

### ISSUE THREAD

**Issue by StephanBis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#163]
I've seen that this project contains a folder for an UWP app. But can't seem to get it working via nuget, is there a special way to get this working?

Thanks,
Stephan

**Comment by ButchersBoy** [comment]
It's not ready yet.

**Comment by StephanBis** [comment]
Ok, thanks you for the info.

**Comment by priombiswas89** [comment]
Please bring the hamburger menu with button animation like material design on UWP application

**Comment by McoreD** [comment]
This is somethiing I will be looking forward to!

**Comment by Unfinished-Code** [comment]
Has this been added? The thread seems old but i've had the same issue.

**Comment by tijmene** [comment]
When will this be ready?

**Comment by ButchersBoy** [comment]
Sorry, I can't give a timescale right now...

**Comment by madhanrifluxyss** [comment]
@ButchersBoy I can see only buttons and toggles for UWP project. how can I use other WPF control styles to UWP?

**Comment by AmitBhatnagar24** [comment]
Any update on any UWP support? This is badly needed for UWP apps!

**Comment by RRZandbergen** [comment]
@ButchersBoy Hi James, you did an awesome job for the WPF platform, but is there any work in progress for UWP support? It would be so sad if you stopped working on it. Are you able to give us an update?

**Comment by ButchersBoy** [comment]
Hi...so basically right now this is waiting for the "stars to align" with regards to my personal and professional situation so I can make more headway...can't really say much more than that just now...

**Comment by Keboo** [comment]
@Artaniis, sadly no. At present I am not aware of anyone working on this. I am happy to help if someone would like to start down this path, but it is a major undertaking, that I presently don't have the bandwidth to complete.

**Comment by ppetrov-dev** [comment]
Hello, any news?=)

**Comment by Keboo** [comment]
@ppetrov-dev currently I am only planning 1-2 releases out into the future. At least for the current roadmap this is not scheduled.

**Comment by Keboo** [comment]
Closing this for now. There is a desire to support additional platforms and I am happy to discuss more details on the [gitter chat](https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit) if anyone is interested in helping support these efforts.
