### ISSUE TITLE
FloatingHintTextBox wrong sample in Demo

### ISSUE THREAD

**Issue by schulz3000** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1635]
For the Hint in FloatingHintTextBox demo a Stackpanel is defined. This Stackpanel is not displayed but "System.Window.Control" as string.
As I understand only simple string values can be diplayed as Hint there.

![image](https://user-images.githubusercontent.com/1812705/73611111-d661a080-45de-11ea-8fde-a3fe2e2a8de5.png)

**Comment by jespersh** [comment]
Seems like an oversight from pull request #1580 
#1636 LGTM
