### ISSUE TITLE
Borders around elements visible on different type of screen resolution.

### ISSUE THREAD

**Issue by sekulicb** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1648]
Hi. I have interesting problem which I cannot reproduce. I have dialog which is created and opened in the C# code. The dialog content is separate UserControl with regular TextBoxes and TextBlocks. On my machine everything works fine and borders are not visible. I have 3 monitors (22 - 24") where screen resolution is set to max (1920 x 1080). But when the client runs the app on its own machine, borders are visible. Client mentioned that resolution used was 1900 x 1200. I don't know if that could be the problem ?

I'm using WPF in .NET CORE 3.1 and MaterialDesignThemes is 3.0.1

Showing Dialog:

![showDialog](https://user-images.githubusercontent.com/20758693/74143659-7cbf2e80-4bfb-11ea-98df-64f591cb8b9b.PNG)

Dialog that shows additional borders:

![clientDialog](https://user-images.githubusercontent.com/20758693/74143838-d162a980-4bfb-11ea-86ee-fa8fda359aaa.PNG)

Dialog Content:

`<UserControl.InputBindings>
        <KeyBinding Key="Escape" Command="{Binding CancelFilteringCommand}"/>
    </UserControl.InputBindings>

    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="../Style/ButtonStyle.xaml"/>
                <ResourceDictionary Source="../Style/ComboBoxStyle.xaml" />
                <ResourceDictionary Source="../Style/TextBoxStyle.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition />
        </Grid.RowDefinitions>

        <Border Background="#2F374A">

            <TextBlock Text="Filter Labels"
                       Margin="10 0 0 0"
                       VerticalAlignment="Center"
                       Foreground="#9DA5BE"
                       FontSize="14"/>
        </Border>

        <Grid Grid.Row="1"
              Margin="20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="150"/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>

            <TextBlock Text="Department"
                       Margin="10 10 0 10"
                       HorizontalAlignment="Left"
                       VerticalAlignment="Center" />

            <ComboBox Grid.Column="1"
                      Height="35"
                      Style="{StaticResource ComboBox}"
                      HorizontalAlignment="Left"
                      VerticalAlignment="Center"
                      IsEditable="False"
                      MaxWidth="300">
                <ComboBoxItem IsSelected="True">
                    Department A
                </ComboBoxItem>
                <ComboBoxItem>
                    Department B
                </ComboBoxItem>
                <ComboBoxItem>
                    Department C
                </ComboBoxItem>
                <ComboBoxItem>
                    Department D
                </ComboBoxItem>
                <ComboBoxItem>
                    Department E
                </ComboBoxItem>
                <ComboBoxItem>
                    Department F
                </ComboBoxItem>
                <ComboBoxItem>
                    Department G
                </ComboBoxItem>
            </ComboBox>

        </Grid>

        <Grid Grid.Row="2"
              Margin="20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="150"/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>

            <TextBlock Text="Line"
                       Margin="10 10 0 10"
                       HorizontalAlignment="Left"
                       VerticalAlignment="Center" />

            <ComboBox Grid.Column="1"
                      Height="35"
                      Style="{StaticResource ComboBox}"
                      HorizontalAlignment="Left"
                      VerticalAlignment="Center"
                      IsEditable="False"
                      MaxWidth="300">
                <ComboBoxItem IsSelected="True">
                    Line A
                </ComboBoxItem>
                <ComboBoxItem>
                    Line B
                </ComboBoxItem>
                <ComboBoxItem>
                    Line C
                </ComboBoxItem>
                <ComboBoxItem>
                    Line D
                </ComboBoxItem>
            </ComboBox>
        </Grid>

        <Grid Grid.Row="3"
              Margin="20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="150" />
                <ColumnDefinition />
            </Grid.ColumnDefinitions>

            <TextBlock Text="Article no"
                       Margin="10 10 0 10"
                       HorizontalAlignment="Left"
                       VerticalAlignment="Center" />

            <TextBox Grid.Column="1"
                     HorizontalAlignment="Left"
                     Width="300"
                     Style="{StaticResource TextBox}" />
        </Grid>

        <Grid Grid.Row="4"
              Margin="20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="150" />
                <ColumnDefinition />
            </Grid.ColumnDefinitions>

            <TextBlock Text="Person"
                       Margin="10 10 0 10"
                       HorizontalAlignment="Left"
                       VerticalAlignment="Center" />

            <TextBox Grid.Column="1"
                     HorizontalAlignment="Left"
                     Width="300"
                     Style="{StaticResource TextBox}" />
        </Grid>

        <Border Grid.Row="5"
                Height="50"
                Background="#F5F8FD"
                BorderBrush="#9DA5BE"
                BorderThickness="0 1 0 0"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Bottom">

            <StackPanel Orientation="Horizontal"
                        HorizontalAlignment="Right">

                <Button Content="Apply"
                        Command="{Binding CancelFilteringCommand}"
                        Style="{StaticResource ApplyDialog}"/>

                <Button HorizontalAlignment="Right"
                        Command="{Binding CancelFilteringCommand}"
                        Style="{StaticResource CloseDialog}"/>

            </StackPanel>

        </Border>

    </Grid>`

**Comment by Keboo** [comment]
This looks like it might be the same issue described here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs#dialog-content-shows-border-lines

**Comment by sekulicb** [comment]
Where should I place this attribute ? Thanks
