### ISSUE TITLE
dotCover reports WPF binding leak for bindings in SmartHint template

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1649]
The Binding on `FloatingOffset.X` and `FloatingOffset.Y` in the SmartHint template will cause dotCover to report a WPF binding leak.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/2740f14a814896d42032ae0013b765a8a0ec04c3/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SmartHint.xaml#L154-L171

This might not be a big issue but if we can come up with a nice solution I think it is good if remove even the small leaks so they do not cause too much noise when looking for the big ones.

However, I'm not sure what the the best solution would be. We could split the `FloatingOffset` into two properties, but that would be a breaking change. We could perhaps write a new converter for this scenario. Thoughts and ideas?

**Comment by Keboo** [comment]
@mgnslndh I assume there is a similar warning on the `FloatingOffset.Y` (line 166) as well. As for the fix the [docs](https://blog.jetbrains.com/dotnet/2014/09/04/fighting-common-wpf-memory-leaks-with-dotmemory/) do a pretty good job of explaining it. I am thinking that one possible fix would be to bind to the `FolatingOffset` directly, and use a value converter to grab the `X` or `Y` properties.

**Comment by mgnslndh** [comment]
Yes @Keboo, I've updated the description.

I think I was involved with the initial implementation of the floating offset but now I must admit that it seems to be an antipattern to have simple composite types like Point, Size and Rectangle as dependency properties. They will not play nice with bindings. Most often you will see values like size split into its parts much like the dependency properties ActualHeight and ActualWidth, which seems to be the way to do it.

**Comment by mgnslndh** [comment]
Perhaps we could have a converter that takes a scale and an offset and produces a TranslateTransform like this:

```
<TransformGroup>
    <TransformGroup.TranslateTransform>
        <MultiBinding Converter="{StaticResource FloatingHintTransformConverter}"> 
            <Binding Path="Scale" ElementName="ScaleHost"/> 
            <Binding Path="FloatingOffset" RelativeSource="{RelativeSource TemplatedParent}"/> 
        </MultiBinding> 
    </TransformGroup.TranslateTransform>    
</TransformGroup>
```

**Comment by Keboo** [comment]
@mgnslndh yea I like that solution.
