### ISSUE TITLE
Showing a Dialog box in main ViewModel constructor generates an Exception

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1660]
Hi All,

I'm trying to show a message dialog box in my application startup, but an Exception is raised in DialogHost.cs in method Show, because LoadedInstances.Count = 0

```csharp
public static Task<object> Show(object content, object dialogIdentifier, DialogOpenedEventHandler openedEventHandler, DialogClosingEventHandler closingEventHandler)
{
	if (content == null) throw new ArgumentNullException(nameof(content));

	if (LoadedInstances.Count == 0)
		throw new InvalidOperationException("No loaded DialogHost instances.");
	LoadedInstances.First().Dispatcher.VerifyAccess();

```
Trying to show the message box in a Loaded event don't solve the issue.
That's because the OnLoaded event is called after the Loaded event of the main Windows.
```csharp
private void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
{
	LoadedInstances.Add(this);
}
```

Is there a workaround to this ?

Thank you
Best regards

**Comment by Keboo** [comment]
This occurs when you do not have a DialogHost as part of the XAML in your main window. Have you added one?

You can read more about using the DialogHost in [the wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs) as well as [this blog post](https://intellitect.com/material-design-in-xaml-dialog-host/).

**Comment by gitjsdr26** [comment]
Yes I've one, with an IsOpen property binded to the ViewModel.
XAML :
```c#
<Grid>
	<materialDesign:DialogHost Identifier="RootDialog" IsOpen="{Binding IsMessageDialogOpen}" DialogContent="{Binding MessageDialogContent}" CloseOnClickAway="False">
		<materialDesign:DrawerHost Margin="0" BorderThickness="2" BorderBrush="{DynamicResource MaterialDesignDivider}" IsRightDrawerOpen="{Binding IsRightDrawerPanelOpen}">
```
Code ViewModel:
```c#
/// <summary>
/// Display modal message box
/// </summary>
private bool _isMessageDialogOpen;
public bool IsMessageDialogOpen
{
	get => _isMessageDialogOpen;
	set => this.Set(ref _isMessageDialogOpen, value);
}
```

**Comment by gitjsdr26** [comment]
I found a solution :
Please see #1661 
Hoping it can help the community.
Best Regards
