### ISSUE TITLE
Set Snackbar duration display

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1663]
Dear All,

Is there a mean to set the display duration for Snackbar ?

Thank you.
Regards

**Comment by jespersh** [comment]
The SnackbarQueueItem has a Duration you can set:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/SnackbarMessageQueueItem.cs#L27

And the Snackbar itself has these:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/54b70082c2be51920358c09fe58090e117eef870/MaterialDesignThemes.Wpf/Snackbar.cs#L104-L106

**Comment by Keboo** [comment]
I also have an example of setting the duration [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/SnackBar/SnackBar.AdjustTiming).

**Comment by gitjsdr26** [comment]
@Keboo thank you for your example.
But it seems that there is no way to set it in XAML ?

**Comment by Keboo** [comment]
@gitjsdr26 no there is not currently an API that would allow setting it in XAML. 
It is important to note that the `SnackBar` control itself does not actually have any concept of timing. It only knows if it has a message to display. It is the SnackBarMessageQueue that controls the timing. Right now the only places to set how long a message is displayed is within the SnackBarMessageQueue constructor (applied to all messages without an explicit override), or explicitly set for each message when you call Enqueue (like what is shown in the sample).
