### ISSUE TITLE
Dialog can't show when Combining multiple assemblies into a single EXE

### ISSUE THREAD

**Issue by starmelon** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1664]
Hi, I have Problem of Dialog , is it a bug?
I try to make all .dll into exe, it's a wpf app , there are two ways for me ,
1).Libz 
2).http://www.digitallycreated.net/Blog/61/combining-multiple-assemblies-into-a-single-exe-for-a-wpf-application (this is the way I use in my demo which I upload )

but they are all failed.

when I set the after build command 
[cd $(TargetDir)
del *.dll]
to del all .dlls

the dialog can't show , and the reason is  "No loaded DialogHost instances."

with the dll ,it works.

anyway to solve this problem? or any other way to hide dlls?

[dialog.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/4223002/dialog.zip)

**Comment by jespersh** [comment]
I wouldn't use that method today. 
Instead use what is available today. Example:
```
dotnet publish dialog.csproj -o _publish -r win-x64 -c Release /p:PublishSingleFile=true  /p:PublishTrimmed=true 
```

**Comment by starmelon** [comment]
> I wouldn't use that method today.
> Instead use what is available today. Example:
> 
> ```
> dotnet publish dialog.csproj -o _publish -r win-x64 -c Release /p:PublishSingleFile=true  /p:PublishTrimmed=true 
> ```

Thx for reply，I will try your way...and now I  have solved it with costura.

**Comment by jespersh** [comment]
Should be noted even Costura recommends the built in methods today too:
https://github.com/Fody/Costura#-read-this--package-is-in-maintenance-mode--read-this-

**Comment by starmelon** [comment]
> 应该注意的是，即使是Costura，今天也建议使用内置方法：[https](https://github.com/Fody/Costura#-read-this--package-is-in-maintenance-mode--read-this-) :
> [//github.com/Fody/Costura#-read-this--package-is-in-maintenance-mode--read-this-](https://github.com/Fody/Costura#-read-this--package-is-in-maintenance-mode--read-this-)

thx again! it is nice!
