### ISSUE TITLE
Update MahApps bushes

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1698]
Based on the latest MahApps, there are several brush changes: https://github.com/MahApps/MahApps.Metro/pull/3747

We need to update the integration package with these brush changes.
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.MahApps/MaterialDesignAssist.cs

**Comment by ShannonZ** [comment]
![capture-55](https://user-images.githubusercontent.com/7865691/77042799-47c2aa80-69f7-11ea-86a5-e9baf75d0411.gif)
The same problem with the UnderlineBrush
