### ISSUE TITLE
All Select button in DagaGrid dose not support Dark Theme

### ISSUE THREAD

**Issue by soi013** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1709]
When `HeadersVisibility` of a DataGrid is `All`, a button to select all rows and columns is displayed.
However, if I select Dark-Theme, the color of the button remains the same as Light-Theme.

At Dark-Theme
![スクリーンショット 2020-03-24 22 36 00](https://user-images.githubusercontent.com/23096880/77431954-c9b03a80-6e20-11ea-8481-b9476e9a9cb5.png)

At Light-Theme
![スクリーンショット 2020-03-24 22 36 19](https://user-images.githubusercontent.com/23096880/77431957-ca48d100-6e20-11ea-93d2-f62cb81b4dfb.png)

Sample code is here

```xaml
<Window
   x:Class="MaterialDesignDataGridTest.MainWindow"
   xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
   xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
   xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
   Width="300" Height="250">
   <Window.Resources>
      <materialDesign:BundledTheme BaseTheme="Dark"
         PrimaryColor="DeepPurple" SecondaryColor="Lime" />
   </Window.Resources>
   <DataGrid HeadersVisibility="All">
      <DataGrid.Columns>
         <DataGridTextColumn Binding="{Binding Text}" Header="Text" />
      </DataGrid.Columns>
      <TextBlock Text="AAA" />
      <TextBlock Text="BBB" />
      <TextBlock Text="CCC" />
   </DataGrid>
</Window>

```

**Comment by soi013** [comment]
#61 may be related to this Issue.
However, I'm not sure what #61 means.

**Comment by w-syss** [comment]
I am currently investigating

**Comment by w-syss** [comment]
I created a pull request which resolves this
