### ISSUE TITLE
Flyout error

### ISSUE THREAD

**Issue by mey1k** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1712]
When I use this code

<controls:Flyout x:Name="LeftFlyout" Position="Left" Header="Settings" wpf:FlyoutAssist.HeaderColorMode="Accent">
                <local:FlyoutContent />
</controls:Flyout>

I got a ArgumentNullException message.

why??

**Comment by soi013** [comment]
In my environment, the problem is not happen.

Did you add MahApps Compatibility ResourceDictionary in App.xaml?

```
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.MahApps;component/Themes/MaterialDesignTheme.MahApps.Defaults.xaml"/>
```

More information is needed.

**Comment by Keboo** [comment]
@mey1k can you provide the versions of these NuGet packages that you are using? 
- MahApps.Metro
- MaterialDesignThemes
- MaterialDesignThemes.MahApps

**Comment by mey1k** [comment]
@Keboo @soi013 Thank you for your comments!

I solves this problem.
I got a hint from your comments(dependencies).

Initially I installed it, ignoring the dependencies of the packages.
Since then, the dependency was set, but the error continued to occur.
So, I created a new project and after all the dependencies were set, it worked.
