### ISSUE TITLE
tab1.Visibility Hidden not work

### ISSUE THREAD

**Issue by mammadkoma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1713]
Hi and thank you
in this your sample visibility for TabItem by c# code not work : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/MainWindow.xaml

private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            tab2.Visibility = Visibility.Hidden; // not work
            tab3.IsSelected = true;
        }
How can we hide a TabItem by c# code?

**Comment by soi013** [comment]
It is Dragablz`s issue.

https://github.com/ButchersBoy/Dragablz/issues/239

https://github.com/ButchersBoy/Dragablz/issues/91

**Comment by Keboo** [comment]
Closing this issue since the problem is over in the Dragablz library.
