### ISSUE TITLE
[Feature Request] Hamburgermenu and Navigation rail

### ISSUE THREAD

**Issue by Rogardo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1718]
Hello 

I want to ask for a Hamburgermenu control for WPF. I know for UWP this is a build in control but it would be a much nicer UX to have a real Hamburgermenu than a "drawer" sidenavigation. A very good example is the navigation in Azure DevOps. 

![2020-03-31_09h26_35](https://user-images.githubusercontent.com/28587500/77998886-153b7a80-7332-11ea-9927-2f6cd9dac14b.png)

The secound Navigation control would be the Navigation rail known from Teams.
![2020-03-31_09h16_08](https://user-images.githubusercontent.com/28587500/77999122-77947b00-7332-11ea-8fcd-4ad7e26b981c.png)

There is already a nice implementation in the "Material Design Extensions"-Project.
https://github.com/spiegelp/MaterialDesignExtensions

Maybe the owner of the project would integrate it directly here

**Comment by Keboo** [comment]
What you are describing in the [Navigation rail](https://material.io/components/navigation-rail/). This is currently in beta, however I would not be opposed to a pull request if someone wanted to implement it.

Currently in this library there are some of the pieces that you are asking for. There is a hamburger toggle button as well as a drawer host. You can see both of these in the [demo application](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases).

**Comment by Keboo** [comment]
Navigation rail is now included in the library
