### ISSUE TITLE
DataGrid opacity issue when using dark theme

### ISSUE THREAD

**Issue by ColossalMoose** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1720]
When using dark theme with the datagrid you will notice that hovering over a selected row will result in the cells being a different colour to the row. 

To replicate:

1. Set the demo app to Dark theme in the pallette
2. Go to Grids in the demo app
3. Select a row in the grid
4. Hover over a row

After speaking about this on Gitter the issue seems to be with the MaterialDesignDivider brush using the opacity in the brush. There are 2 potential fixes for this:

1. Change the theme brushes so they no longer rely on alpha channel
2. A smaller change would be to apply the dynamic resource to the Tag property, and use a binding between the Tag and Background properties to apply the converter. But those kind of double hops can start to add up to perf hits.

You can use the code [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Converters/RemoveAlphaBrushConverter.cs) to get a new value for the brush.

Please note than when changing this brush it is used in several places so you will need to make sure that everywhere that uses it also works as this has the potential for several problems in different areas.

**Comment by Keboo** [comment]
I believe the correct fix is to adjust the theme brush so it no longer uses the alpha channel.

**Comment by greuelpirat** [comment]
I took a look at this. But I have a question.

Is the wanted result for a DataGrid to have a single color for a row (depending on its state)? Like it does for the light theme.

If so, would it be clearer to remove the triggers for the cell background here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/b45ee3deccf40b7be1531a1b94290a9afa22b24c/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L169

I tested this and it looks pretty good to me:
![grid-row-dark](https://user-images.githubusercontent.com/16866222/80277736-60f30100-86f1-11ea-91d3-588f6766b076.gif)

But I agree that the colors should be adjusted. Because in the light theme there is no visual difference between selected row and row with mouse over

**Comment by Keboo** [comment]
@greuelpirat That looks pretty good to me.

**Comment by Keboo** [comment]
Re-opening based on feedback from @Jesus805 on gitter

> #1720 broke the cell selection background. If I have a DataGrid with SelectionUnit Cell and SelectionMode Extended, selecting an array of cells shows no selected background. This was probably caused by removing the trigger

**Comment by Jesus805** [comment]
Here's a sample project that shows the problem
https://github.com/Jesus805/DataGridValidationSample
If you click and hold the mouse button, then drag your mouse to select a block of cells, there is no longer a selected background. (I bordered what I selected in green)
![bug](https://i.imgur.com/hkKW8po.png)
I was able to restore this functionality by re-adding the trigger that #1769 removed
```
<Style x:Key="{x:Type DataGridCell}"
           TargetType="{x:Type DataGridCell}"
           BasedOn="{StaticResource {x:Type DataGridCell}}">
    <Style.Triggers>
        <Trigger Property="IsSelected" Value="True">
            <Setter Property="Background" Value="{DynamicResource MaterialDesignSelection}"/>
        </Trigger>
        <Trigger Property="IsEditing" Value="True">
            <Setter Property="Background" Value="{DynamicResource MaterialDesignPaper}"/>
        </Trigger>
    </Style.Triggers>
</Style>
```

**Comment by greuelpirat** [comment]
I restored the cell triggers, and updated them to consider MouseOver its row.

See https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1809#issue-415226736 for visual.

I hope that is okay to keep cell selection but fixes this issue.

**Comment by Jesus805** [comment]
I'm honestly not a big fan of row highlighting on mouse-over in DataGrid. I feel that it causes confusion when you have an overlap of selected cells/rows and mouse-over highlighting. This confusion is more evident when you use a touch screen tablet like a Surface, the cursor is in an arbitrary location but not visible, so the row that it's over looks like it's selected.

**Comment by greuelpirat** [comment]
I would have no problem with that. I just try to fix the issue, with minimum changes. But if it is requested to remove the hover-effect at all, this will surely this issue as well.

I just thought about to make the Hover-Brush configurable. And when set to `Transparent` this would be gone. But I think that goes beyound this issue.
