### ISSUE TITLE
ComboBox - strange artifacts (3.1.0 release)

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1728]
You can see it without changing `MaterialDesignPaper` but I changed it to red to highlight the issue.

1. Vertical line.
2. Don't even know how to call these.  They are in all 4 corners... some sort of "notches" of 1 pixel perhaps.

Just FYI, I see it with Font 13 and 16, same on both.

![image](https://user-images.githubusercontent.com/16761301/78715532-8909f400-78eb-11ea-94e5-21ef7ca5edfc.png)

**Comment by soi013** [comment]
Did you use dialog?

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1199#issuecomment-467562715

**Comment by bebenins** [comment]
> Did you use dialog?
> 
> [#1199 (comment)](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1199#issuecomment-467562715)

Not sure what you mean.  I'm using a standard ComboBox.  
`UseLayoutRounding="True"` has been set in my apps since the very beginning.  This issue only showed up after upgrading to 3.1.0.

**Comment by soi013** [comment]
Probably, vertical line is deleted  in newest repository.
And other notches is fixed by my PR.
