### ISSUE TITLE
There are issue while i download the files from git hub

### ISSUE THREAD

**Issue by sycs1717** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1730]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	MaterialDesignThemes.Wpf.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'C:\Users\Komal D\Downloads\New folder (2)\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj'. Inside Visual Studio, this may be because the project is unloaded or not part of current solution. Otherwise the project file may be invalid or missing targets required for restore.	MaterialDesignColors.Wpf.Tests	C:\Users\Komal D\Downloads\New folder (2)\MaterialDesignInXamlToolkit-master\MaterialDesignColors.Wpf.Tests\MaterialDesignColors.Wpf.Tests.csproj	1

**Comment by Keboo** [comment]
@sycs1717 can you check which versions of the .NET Core SDK you have installed. You can get this information with:
```
dotnet --list-sdks
```

You should see some output similar to:
```
3.1.201 [C:\Program Files\dotnet\sdk]
```

To [compile the project from source](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source) requires having the .NET Core 3.1.

**Comment by sycs1717** [comment]
yes I see the same

**Comment by jespersh** [comment]
The line @sycs1717 actually needs is from `dotnet --info`:
```
Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Also remember to remove windows "this is a dangerous internet file" protection on the zip before extracting it
