### ISSUE TITLE
Resoure can't find

### ISSUE THREAD

**Issue by mey1k** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1731]
Hello :)

Git clone this project

Build, Run and everthing OK.  

But Some Styles and MaterialButton Show me. Resource can't find..

I want to del these message.

What should i do?

**Comment by Keboo** [comment]
It sounds like you may need to include additional resource dictionaries. See her. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#exception-cannot-find-resource-named-materialdesign
