### ISSUE TITLE
Persian Calendar Date Picker

### ISSUE THREAD

**Issue by RezaSkyFall** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1733]
hi,
I want to use date picker but unfortunately its dosnt support shamsi date (persian calendar),
if there is any way to fix it ill be happy to hear.

tanks for this awesome toolkit.

**Comment by Keboo** [comment]
Thank you for this report, however this is a WPF limitation right now (See: https://github.com/dotnet/wpf/issues/226).

We are tracking this with issue #677
