### ISSUE TITLE
ContentStringFormat not working with some button styles

### ISSUE THREAD

**Issue by jbooth88** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1737]
A previous change (see link below) added support for ContentStringFormat to the style: MaterialDesignRaisedButton.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1002

I just noticed that the other button stiles do not have this change. 
I think all that's required is to add _ContentStringFormat="{TemplateBinding ContentStringFormat}"_ to the Ripple control XAML?

**Comment by Keboo** [comment]
Yes I believe that is the correct fix.
