### ISSUE TITLE
Error XDG0062: TypeConverter cannot convert from System.String

### ISSUE THREAD

**Issue by netcorefan1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1743]
Hello to all and congratulation for this wonderful project!
I get this error on dialog host sample from the demo in the pickers section.
The affected lines are these:
materialDesign:DialogHost.DialogClosingAttached="CombinedDialogClosingEventHandler"
materialDesign:DialogHost.DialogOpenedAttached="CombinedDialogOpenedEventHandler"
The project compiles, runs and debug just fine, but it messes up the designer.

Visual Studio Enterprise 16.5.4
.Net Core 3.1

I uploaded a sample project here:
https://easyupload.io/td7n8q
As soon as you open mainWindow and compile, these errors appears..
Thanks

**Comment by Keboo** [comment]
Given that this is a designer error, I suspect this is a designer problem. It is likely the same issue here: https://developercommunity.visualstudio.com/content/problem/353064/bogus-xdg0062-on-xaml-designer-on-not-being-able-t.html

**Comment by netcorefan1** [comment]
Thanks for your response. There is also another report where are involved event handlers although I am not sure if it can be correlated with my specific report:
https://stackoverflow.com/questions/59052601/visual-studio-xaml-designer-error-xdg0062-using-eventsetter-in-net-core-wpf-app
If this is the case, then this bug has been fixed one month ago, in version 16.5.0
Another user has recently reported my exact problem:
https://stackoverflow.com/questions/60206612/typeconverter-cannot-covnert-from-system-string-in-dialogopenedattached
In the Microsoft forums I can't find any report like mine involving 16.5.0 and above, may be is better to check the library code before marking this as a VS bug?

**Comment by DMX-David-Cardinal** [comment]
I am getting the same issue in Visual Studio 16.8 and a .NET 5.0 project.

My use case is slightly different but the error is the same (code compiles and runs as intended, but the designer gives a XDG0062 error):

```
<!-- MainWindow.xaml -->
<local:SomeClass MyAction="MainWindow_Action"/>
-----------------------------------------------------
// SomeClass.cs
public class SomeClass
{
    public Action MyAction { get; set; }
}

// MainWindow.xaml.cs
private void MainWindow_Action() { ... }
```

**Comment by Keboo** [comment]
@DMX-David-Cardinal that looks like it is likely a designer bug. I would [submit a Visual Studio issue for it](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)

**Comment by DMX-David-Cardinal** [comment]
As suggested, I opened an issue here: https://developercommunity.visualstudio.com/content/problem/1304343/visual-studio-designer-typeconverter-cannot-conver.html

Will share any updates or fixes on the issue.

**Comment by DMX-David-Cardinal** [comment]
Thank you, seems I commented this in the wrong repo. My apologies
