### ISSUE TITLE
Add MoneyBag icon

### ISSUE THREAD

**Issue by seddik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1744]
Hello, moneybag icon is a must, the existing money (cash) icons aren't that significant. I suppose I can add that icon to the PackIconKind and also to demo.

**Comment by bebenins** [comment]
You should probably request it here instead since this is the source of all icons (automated process AFAIK)
https://materialdesignicons.com/

**Comment by seddik** [comment]
> You should probably request it here instead since this is the source of all icons (automated process AFAIK)
> https://materialdesignicons.com/

I didn't know that it was from MDI, until I've watched a live on twitch "Kevin B" , 

thank you, I've added a request :D
