### ISSUE TITLE
Disable window close button while using DialogHost

### ISSUE THREAD

**Issue by lmx01** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1752]
I am using DialogHost.Show() for showing a dialog,but the window of the dialog owner still can using the close button .How can I disable it? Thanks.

![image](https://user-images.githubusercontent.com/16526407/79844813-c5127e00-83ee-11ea-8473-dac426aac564.png)

**Comment by Keboo** [comment]
Hi @lmx01 unlike the Windows Forms `MessageBox`, the `DialogHost` in this library is intentionally async to avoid blocking the UI. This has the side affect of allowing the user to interact with the window elements. There is no built-in support for preventing a close, while a dialog is open; that is something you will need to add yourself. 

To do it, you would need to do something like this in your Window.
```C#
public MainWindow()
{
	InitializeComponent();
	Closing += OnClosing;
}

private void OnClosing(object sender, CancelEventArgs e)
{
    //Get the dialog host instance
    DialogHost dialogHost = ...;
    if (dialogHost.CurrentSession?.IsEnded == false)
    {
        //Prevent the window from closing
        e.Cancel = true;
    }
}
```

**Comment by lmx01** [comment]
OK，thanks




| |
fdsf
|
|
邮箱：lmxbeijing01@163.com
|

Signature is customized by Netease Mail Master

On 04/28/2020 12:01, Kevin B wrote:

Hi @lmx01 unlike the Windows Forms MessageBox, the DialogHost in this library is intentionally async to avoid blocking the UI. This has the side affect of allowing the user to interact with the window elements. There is no built-in support for preventing a close, while a dialog is open; that is something you will need to add yourself.

To do it, you would need to do something like this in your Window.

publicMainWindow()
{
	InitializeComponent();
	Closing+=OnClosing;
}

privatevoidOnClosing(objectsender, CancelEventArgse)
{
    //Get the dialog host instanceDialogHostdialogHost= ...;
    if (dialogHost.CurrentSession?.IsEnded==false)
    {
        //Prevent the window from closinge.Cancel=true;
    }
}
