### ISSUE TITLE
XDG0012	The member "XXX" is not recognized or is not accessible.

### ISSUE THREAD

**Issue by netcorefan1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1758]
To reproduce build the source project and then open Fields.xaml from MaterialDesignDemo project.
The errors shown in the picture will appears. The project compiles and runs just fine, but the errors breaks the designer.
VS 16.5.4
<img width="667" alt="MemberNotRecognized" src="https://user-images.githubusercontent.com/63934725/80099699-2feac300-856f-11ea-8103-55a143f000fd.png">

**Comment by soi013** [comment]
duplicate of #730

**Comment by Keboo** [comment]
Unfortunately this is a Visual Studio issue and not something easily solved in this library.
