### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by ddm4313** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1770]
`1>------ Build started: Project: MaterialDesignThemes.Wpf, Configuration: Debug Any CPU ------
1>Paket version 5.242.0
1>Paket version 5.242.0
1>C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\MahMaterialDragablzMashUp\obj\paket.processlock is locked by paket.exe (PID = 49492). Waiting...
1>Starting full restore process.
1>Something went wrong while downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Message: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>  ==> Trying again
1>Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\paket-files\paket.processlock is locked by paket.exe (PID = 49492). Waiting...
1>Not moving as 'C:\Users\DDM\.nuget\packages\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl\4.3.3\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg' already exists (maybe some other instance downloaded it as well)
1>Download of runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3 done in 1 second. (236 kbit/s, 0 MB)
1>Something went wrong while downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Message: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>  ==> Last trial
1>Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Not moving as 'C:\Users\DDM\.nuget\packages\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl\4.3.3\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg' already exists (maybe some other instance downloaded it as well)
1>Download of runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3 done in 361 milliseconds. (1184 kbit/s, 0 MB)
1>Performance:
1> - Disk IO: 21 milliseconds
1> - Average Download Time: 453 milliseconds
1> - Number of downloads: 2
1> - Average Request Time: 448 milliseconds
1> - Number of Requests: 2
1> - Runtime: 3 seconds
1>Paket failed with
1>-> PathTooLongException: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>-> PathTooLongException: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>-> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>Starting full restore process.
1>C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\Paket.Restore.targets(171,5): error MSB3073: The command ""C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\paket.exe" restore" exited with code 1.
1>Done building project "MaterialDesignThemes.Wpf.csproj" -- FAILED.
1>Something went wrong while downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Message: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>  ==> Trying again
1>Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Not moving as 'C:\Users\DDM\.nuget\packages\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl\4.3.3\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg' already exists (maybe some other instance downloaded it as well)
1>Download of runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3 done in 1 second. (276 kbit/s, 0 MB)
1>Something went wrong while downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Message: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>  ==> Last trial
1>Downloading runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3
1>Not moving as 'C:\Users\DDM\.nuget\packages\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl\4.3.3\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg' already exists (maybe some other instance downloaded it as well)
1>Download of runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.3 done in 358 milliseconds. (1194 kbit/s, 0 MB)
1>Performance:
1> - Disk IO: 9 milliseconds
1> - Average Download Time: 418 milliseconds
1> - Number of downloads: 2
1> - Average Request Time: 414 milliseconds
1> - Number of Requests: 2
1> - Runtime: 5 seconds
1>Paket failed with
1>-> PathTooLongException: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>-> PathTooLongException: Path too long: C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\packages\runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl\runtime.opensuse.13.2-x64.runtime.native.system.security.cryptography.openssl.4.3.3.nupkg
1>-> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\Paket.Restore.targets(171,5): error MSB3073: The command ""C:\Users\DDM\Desktop\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\paket.exe" restore" exited with code 1.
1>Done building project "MaterialDesignThemes.Wpf.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========`

**Comment by w-syss** [comment]
Hi,
see #1761. I think you ran into to the same issue.

**Comment by Keboo** [comment]
Hi @ddm4313 it looks like the issue you are running into is a PathTooLingException:
> PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Try moving the repository closer to the root of C:\ and that should resolve your issue.

**Comment by Keboo** [comment]
Paket has now been removed please see the latest requirements for compiling from source: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source
