### ISSUE TITLE
3.1.0 introduces a weird auto-sizing bug

### ISSUE THREAD

**Issue by BryceBarbara** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1775]
For some reason, it seems that DialogHost in v3.1.0 is causing some weird autosizing behavior that didn't occur in 3.0.1.

I've gone and [created a repository](https://github.com/BryceBarbara/DialogSizingError) with the minimum amount of code to see it in action.

Just open it up and run the project. It should look normal for a second then auto-size the width to be the full width of all your monitors. In my case, two 1080p monitors.

**Comment by Keboo** [comment]
Haven't tracked down the reason for this issue, but using git bisect, [this commit](238c24df19af85222766095be7f799da353f1545) is the culprit.

**Comment by greuelpirat** [comment]
238c24df19af85222766095be7f799da353f1545 was added with 3.1.1, but the sample project uses 3.1.0. But I will take a look.

**Comment by greuelpirat** [comment]
I delete previous comment. I was wrong. But I will look anyway.

**Comment by greuelpirat** [comment]
It is once again the `DashedLine`. The referenced issue #1642 is also back again.

I am recreating the DashedLine as an Adorner. First steps works an fixes both problems. But I need more time.
