### ISSUE TITLE
Validation red border around both cell and textbox

### ISSUE THREAD

**Issue by Jesus805** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1779]
This issue may be related to #1573
When I have a validation error with a `System.ComponentModel.DataAnnotations` attribute. Both the padded textbox and the surrounding cell get a red border. 
![image](https://i.imgur.com/qjRI29t.png)
I think the border should only be around the cell, even though DataGrids use a Textbox as their entry type, DataGrids seem more aligned with Material Data Tables, which unfortunately does not specify what a validation error should look like

**Comment by Keboo** [comment]
Yes these two issue look very similar/related. It appears to stem from the fact that we have not set a material design themes error template for these controls.

**Comment by greuelpirat** [comment]
@Jesus805 I am working on this and could fix some parts. But I can not reproduce the red outer border on whole cell. Can you provide an example project?

**Comment by Jesus805** [comment]
Yes I'll create a sample

**Comment by Jesus805** [comment]
https://github.com/Jesus805/DataGridValidationSample/tree/master/DataGridValidationSample
@greuelpirat I created a sample.
 
Very interesting, I realized that the cause of the cell border is a style I set.
https://github.com/Jesus805/DataGridValidationSample/blob/master/DataGridValidationSample/MainWindow.xaml#L17
I'm wondering if this is just a bug on my end

**Comment by greuelpirat** [comment]
I removed the cell border in `MaterialDesignDataGridCell`, that works now. I also made a small location fix, so that finally looks good to me:

![validation-sample-with-fixes](https://user-images.githubusercontent.com/16866222/80916482-41934e00-8d59-11ea-892a-93ae7f3e6f44.gif)

But there is one thing required. I needed to add two properties to your `DataGridTextColumn`s

```
ElementStyle="{StaticResource MaterialDesignDataGridTextColumnStyle}"
EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnEditingStyle}"
```

Only then, the column styles were applied. I tried so set them by default:

```
<Style TargetType="{x:Type DataGridTextColumn}" BasedOn="{StaticResource MaterialDesignDataGridTextColumn}" />

<Style x:Key="MaterialDesignDataGridTextColumn" TargetType="{x:Type DataGridTextColumn}">
  <Setter Property="ElementStyle" Value="{StaticResource MaterialDesignDataGridTextColumnStyle}" />
  <Setter Property="EditingElementStyle" Value="{StaticResource MaterialDesignDataGridTextColumnEditingStyle}" />
</Style>
```
But this did not work. May be someone has an idea?
