### ISSUE TITLE
Update discrete slider appearance to match latest material design specification

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1782]
Currently our discrete slider style does not match the [latest material design spec](https://material.io/components/sliders#discrete-slider).
![image](https://user-images.githubusercontent.com/952248/80629789-2f877780-8a08-11ea-8d9f-0b6bef75dfc7.png)

Specifically the popup that is shown as the value changes should be updated to match the new style.
This requires updating the existing `MaterialDesign*DiscreteSliderThumb` templates.

**Comment by jizc** [comment]
I have started working on this, hoping to submit a PR today. Should at least be before next week.
