### ISSUE TITLE
3.1.1 update not change the background on combobox

### ISSUE THREAD

**Issue by dannythegreat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1786]
Hello,
from version 3.0.1 I can't set custom background of Combobox and inner container items.
Before 3.0.1 it worked, now it just keeps only Default, Dark and Light color's presets.

How I can change this property?

**Comment by LCvanDinteren** [comment]
Check out the release notes for v1.3.0: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases/tag/3.1.0

I had the same issue, but the specified solution works like a charm for me.
