### ISSUE TITLE
Supporting UWP, Xamarin platforms,WindowsForms

### ISSUE THREAD

**Issue by AbdAlghaniAlbiek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1797]
Can you make this package works on UWP, Xamarin and Windows Forms by adding ".NET Standard"  to it

**Comment by Keboo** [comment]
It is unfortunately not that simple. We could change the NuGet package to be .NET Standard, but that would not add support for other platforms. We have been looking to expand into other platforms, specifically WinUI and Uno, but for now this project still only support WPF.
