### ISSUE TITLE
.NET Core 3.1 | FilterChipListBox not working properly

### ISSUE THREAD

**Issue by MovGP0** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1802]
There is an issue with the behavior of `MaterialDesignFilterChipListBox` ListBoxes. 

## Current Behavior

When using the `MaterialDesignFilterChipListBox` with data binding, there is a button blocking the click-behavior of the chips, besides no button was defined. 

When setting the `IsSelected` property to `true`, the button is highlighted in a darker grey, but the checkmark is not visible.

**Source code**

```xaml
<ListBox Style="{StaticResource MaterialDesignFilterChipListBox}" 
    MinHeight="32"
    ItemsSource="{Binding Roles}" >
    <ListBox.ItemTemplate>
        <DataTemplate>
            <ListBoxItem IsSelected="{Binding IsActive, Mode=TwoWay,  UpdateSourceTrigger=PropertyChanged}" IsTabStop="True">
                <TextBlock Text="{Binding Name, Mode=OneWay, UpdateSourceTrigger=PropertyChanged}" />
            </ListBoxItem>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

**Presentation**

![image](https://user-images.githubusercontent.com/83339/81283403-dbf6d880-905c-11ea-9b7b-58377c5b00eb.png)

As you can see, there is a button over the flip box (dark color), so the rendering in off. also the `ListBoxItem` does not react to mouse clicks, since it's captured by the button. The check only appears when clicking on the rounded corner, but not when clicking on the `TextBlock`. 

## Expected behavior

The default template should be replaced such that there is no button. The `IsSelected` property should bind to the visibility of the checkmark, rather than the button. 

Alternatively, it might be easier to provide a custom control. 

## Version Information

* TargetFramework: netcoreapp3.1
* MaterialDesignColors Version 1.2.4
* MaterialDesignThemes Version 3.1.1
* Windows 10 x64 (1909)

**Comment by Revolt27** [comment]
Hello!
You can solve your problem as follows:

```xml
<ListBox Style="{StaticResource MaterialDesignFilterChipListBox}"
         ItemsSource="{Binding Roles}">
    <ListBox.ItemContainerStyle>
        <Style TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource MaterialDesignFilterChipListBoxItem}">
            <Setter Property="IsSelected" Value="{Binding IsActive, Mode=TwoWay}" />
        </Style>
    </ListBox.ItemContainerStyle>
    <ListBox.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding Name}"/>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```
