### ISSUE TITLE
[FeatureRequest] HintAssist 'Background' attached property

### ISSUE THREAD

**Issue by tamper2** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1804]
It's currently not possible to set the **Background** property of a hint inside a TextBox, as it is set to MaterialDesignPaper (MaterialDesignTheme.TextBox.xaml - line 213).
It doesn't have an **attachable property**.

The only way I've found to change the background is to override the dynamic MaterialDesignPaper inside your TextBox style.

**Comment by Keboo** [comment]
To implement this we need to do the following.
- Add a new Background attached property to HintAssist (this is similar to the existing Foreground property that is there)
- Apply the new property to the SmartHint control in the [TextBox templates](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml) at the same points where HintAssist.Foreground is getting applied.
- Ensure that there is a default background set on the style to MaterialDesignPaper just like the Foreground has a default `<Setter Property="wpf:HintAssist.Foreground" Value="{DynamicResource PrimaryHueMidBrush}" />`
