### ISSUE TITLE
Can use wpf on framework 4.0?

### ISSUE THREAD

**Issue by siwakornapichit** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1805]
Dear All,

How to rebuild package on framework 4.0 because my project has run on old OS (XP and Windows 7) ?

Thank for advice
Siwakorn

**Comment by Keboo** [comment]
Hi @siwakornapichit unfortunately there is not a simple option here. There is an old `net40` branch that you can compile and use, however this branch is quite old and does not have the latest features.

**Comment by siwakornapichit** [comment]
Hi @Keboo 
Thank for your advice. I can compile on Net 4.0. But if I compile on Net 4.5. I found a problem about 
[gif:ImageBehavior.AnimatedSource].
