### ISSUE TITLE
Snackbar - "Auto" ActionButton placement doesn't always work 

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1812]
My app defaults it to `SeparateLine` because Snoop shows 51 on ActualHeight of SnackBar
Forced to Inline to show ActualHeight:
![image](https://user-images.githubusercontent.com/16761301/81430033-be913f80-912c-11ea-9955-d141697a759a.png)
This is when app defaults it to `SeparateLine`
![image](https://user-images.githubusercontent.com/16761301/81429888-7eca5800-912c-11ea-970b-edd2af5f6a26.png)

From Kevin:
"I think the issue is our 49 default is just a little too small and we need to bump it up a bit or revisit trying to make it a little more dynamic"

Forcing `materialDesign:SnackbarMessage.InlineActionButtonMaxHeight="51"` proves this theory

**Comment by greuelpirat** [comment]
I took the `49` from https://material.io/components/snackbars#specs as `48` is the minimum height for a single line message and above that the action button is moved on separate line. Seems that was only working for me. It would be no problem to set it to `58` or so.

But I found a potential dangerous loop with the dependency of the placement to the message size:
Take a text that is long enough to break on a second line but short enough for a single line when the action button is on a separate line. In that case it would change infinitely.

Also this image from the specs seems to recommend a separate line for the action button, when the button it self is wider:
![image](https://user-images.githubusercontent.com/16866222/81463079-00ff5e80-91b7-11ea-8637-ce76c131d747.png)

So may be a `SnackbarMessage.InlineActionButtonMaxWidth` with default `100` (about one third of min-width `288`) or so would be better.

Or even better a relative width-share to support wider snackbars like example 5 from Demo-App.
 `SnackbarMessage.InlineActionButtonMaxRelativeWidth` with default `0.33`

**Comment by greuelpirat** [comment]
Hm. Forget `ae2d71c`. this also can lead to layout loops.

I think only `SnackbarMessage.InlineActionButtonMaxWidth` with a default `100` or tell me what value you want here is stable.

**Comment by greuelpirat** [comment]
If no one has a better idea I stayed with the `InlineActionButtonMaxHeight` and increased the threshold to `55`.

This is better for wider snackbars (like example 5 in demo app) then using a discrete button width.

To avoid layout loops the value must stay below `94` (the height of single line message with button on separate line)

**Comment by bebenins** [comment]
Thank you very much for making this change.  I fully trust your judgement :)

**Comment by Keboo** [comment]
I think 55 is a reasonable default.
