### ISSUE TITLE
Datepicker underline would not disapear.

### ISSUE THREAD

**Issue by ironsnitra** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1813]
Hello, I've been trying to remove the underline in the datepicker but unfortunately it wouldn't.

**Comment by Keboo** [comment]
It looks like this is likely a bug with the current `MaterialDesignDatePickerTextBox`. Normally you should be able to set the `BorderThickness="0"` and `materialDesign:TextFieldAssist.DecorationVisibility="Collapsed"` to cause the underline to disappear, however it appears that the `BorderThickness` is not being properly propogated down to the `border` in the `MaterialDesignDatePickerTextBox` style.
