### ISSUE TITLE
Problem with binding to viewmodel inside of Materialdesign Flipper BackContent and ItemsControl DataTemplate

### ISSUE THREAD

**Issue by Dowlpack** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1832]
I have problem with Binding Text to Viewmodels property from DataTemplate of ItemsControl. I have problem Inside of Flippers BackContent but In FrontContent of flipper my Binding works correctly. Code where I have trouble:

`<TextBlock FontSize="22" Text="{Binding RelativeSource={RelativeSource AncestorType={x:Type Window}},Path=DataContext.VMProperty}"/>`

How can I solve the problem? Thanks in advance

I have a problem with correct code insert here. That's why 

[My github repository](https://github.com/Dowlpack/flipper)

**Comment by Dowlpack** [comment]
Hi! May be I should Paste code here or [My repository](https://github.com/Dowlpack/flipper) is enough?

**Comment by bombipappoo** [comment]
When binding `VMProperty`, `BackContent` does not seem to be part of the visual tree yet.
So, `RelativeSource` does not work properly.

You can use the object called "BindingProxy" for binding `VMProperty`.

**Comment by Dowlpack** [comment]
> When binding `VMProperty`, `BackContent` does not seem to be part of the visual tree yet.
> So, `RelativeSource` does not work properly.
> 
> You can use the object called "BindingProxy" for binding `VMProperty`.

bombipappoo, So thanks. It works as expected
