### ISSUE TITLE
DialogHost sizing issue with Transitioner items of diffrent sizes.

### ISSUE THREAD

**Issue by Proless** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1834]
i have a transitioner with two items/slides of different sizes, when the transitioner is put into a Dialog,
1 - The dialog doesn't change its size to fit the items when transitioning from one item/slide to another.

2- it is showing these dotted lines which corresponds the the textboxes and passwordboxes on the items/slides. I think this is the style when a textbox is disabled but why are they visible !
![](https://i.imgur.com/jrpDl7I.png)

I have created this sample [GitHub repo](https://github.com/Proless/MaterialDesignDialogHostTransitionerExample) on GitHub to demonstrate the issue. I hope this is clear enough.

**Update 1:**
with version 3.2.0-ci1494, the second issue is fixed .

**Comment by tensei** [comment]
this issue still exists on version 3.1.3

**Comment by Proless** [comment]
> 
> 
> this issue still exists on version 3.1.3
> nvm 3.2.0-xxx fixed this

with version 3.2.0-ci1494, i can confirm that the transparency/ dotted lines issue is fixed.

but the sizing issue of the DialogHost still exists.
