### ISSUE TITLE
Add style to menu and menuitem component

### ISSUE THREAD

**Issue by Failip420** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1837]
it would be nice if you added style to menu and menuitem :) right now it uses windows default

**Comment by Keboo** [comment]
Hi @filip123 

This should already be implemented. If you look in the demo app you will see this:
![image](https://user-images.githubusercontent.com/952248/82137509-c5275300-97cd-11ea-8d41-11817c770b80.png)

Perhaps you have custom styles on these types that [need to be based on](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#when-custom-style-is-applied-the-material-design-theme-is-lost) the material design ones?

**Comment by saulzetler** [comment]
How can I remove the padding around the menu items?

**Comment by Keboo** [comment]
This should be controllable with the Padding property on the MenuItem themselves.
