### ISSUE TITLE
PackIcon Size

### ISSUE THREAD

**Issue by mcobrahacker** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1839]
Hello! How can I make some height icon?

**Comment by Keboo** [comment]
Hi @mcobrahacker the PackIcon control is re-sizable but you will need to explicitly set the Width and the Height properties. Typically you want both of these sizes to be equal since the icons are designed to be square.

```xaml
<mdix:PackIcon Kind="Heart" Width="48" Height="48" />
```
