### ISSUE TITLE
Dialog host is transparent!

### ISSUE THREAD

**Issue by Redp87** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1840]
The dialoghost became transparent in version 3.1.2. Can you look into this please.
NB : actually this behavior is present when ever there is an overlay like an open drawer, dialoghost...

This is what I'm supposed to have (3.1.1)
![Screenshot (26)](https://user-images.githubusercontent.com/60324051/82187336-8b993980-98ec-11ea-8948-6f6029d8fd25.png)

This is what it becomes in 3.1.2
![Screenshot (28)](https://user-images.githubusercontent.com/60324051/82187406-a7044480-98ec-11ea-87cf-927592ac7d63.png)

**Comment by Keboo** [comment]
I am unable to reproduce this inside of the demo application can you provide reproduction steps or a sample showing the issue?

**Comment by Redp87** [comment]
When the dialog is on combobox or textbox, part of them show under the dialog. This behavior wasn't present in 3.1.1

**Comment by yosefmah** [comment]
This looks very similar to issue #1829 with the BottomLineDashedAdorner.
