### ISSUE TITLE
Remove DataGrid "Divider" Line

### ISSUE THREAD

**Issue by paypalsession** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1844]
Is there a way to remove this divider line which separates the column headers and the rows?

![datagrid](https://user-images.githubusercontent.com/57019717/82353813-d5bb1180-99f7-11ea-962a-eedcb92c2502.PNG)

**Comment by greuelpirat** [comment]
This is one of the issues I try to solve with #1838

**Comment by paypalsession** [comment]
How would I do it using your improvements?

**Comment by paypalsession** [comment]
I have the latest version downloaded and I tried doing that but it doesn't seem to work, it gets rid of the row lines, but not the specific line which I pointed out in the image above. Am I doing something wrong?

**Comment by greuelpirat** [comment]
[ci1494](https://www.nuget.org/packages/MaterialDesignThemes/3.2.0-ci1494) is the newest build, but it does not contain #1838. I do not know when the next release/prerelease will be available.

**Comment by paypalsession** [comment]
Ok will be looking out for it! Thanks anyways
