### ISSUE TITLE
3.1.2 Textbox coming through as dashed line in tabbed layout

### ISSUE THREAD

**Issue by cjmurph** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1846]
I have a strange issue in 3.1.2, In a tabbed interface, textboxs in other tabs are showing through as a dashed line. Reverting to 3.1.1 resolves the issue. Anyone else seeing this?

![weird_textbox](https://user-images.githubusercontent.com/2868949/82401575-be7a3380-9a8c-11ea-89ab-eae0cfdd689e.PNG)

**Comment by Keboo** [comment]
Yep same at #1840. Should be resolved in tonight's 3.2.0 preview release.
