### ISSUE TITLE
TrayIcon context menu children appear on opposite corner of screen 

### ISSUE THREAD

**Issue by dasjestyr** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#185]
Using NotifyIcon (defacto tray icon standard for WPF, as far as I know --> http://www.hardcodet.net/wpf-notifyicon), context menu children do not appear where you would expect them. In this example, I used no custom styling or anything. Just right out of the box on the toolkit and trayicon:

![image](https://cloud.githubusercontent.com/assets/3200529/12073688/9e794f12-b0e9-11e5-8293-cb52aadcdbb4.png)

**Comment by ButchersBoy** [comment]
Is this particular to MD Toolkit, or a NotifyIcon problem?  What's it like without the MD styles applied?

**Comment by dasjestyr** [comment]
Without the MDTK, it appears as a normal context menu right where it should be.

**Comment by ButchersBoy** [comment]
OK...any chance you can post a quick sample on GitHub?  Saves me 20 mins of setup...

**Comment by dasjestyr** [comment]
Yep: https://github.com/dasjestyr/NotifyIcon_MDProblem.git

Also, I found that the problem only seems to occur when the submenu items are bound. If you hard code the subitems, the problem doesn't seem to be there.

**Comment by dasjestyr** [comment]
Actually, you can disregard it being a problem with the taskbar icon. I just added another view to that sample project called NoTray.xaml. If you change the startup to load that instead, you'll say that it seems to apply to any bound menu item

**Comment by ButchersBoy** [comment]
Reminder to self: https://github.com/ButchersBoy/NotifyIcon_MDProblem

**Comment by NtFreX** [comment]
When I use the `TaskbarIcon` from hardcodet.net with an tooltip I have the same problem. The Tooltip is displayed in the top left corner of the screen the tray icon is in. It doesn't matter if you hardcode the `ToolTipText` property or if you bind it.

`<tb:TaskbarIcon  ToolTipText="My tooltip" />`

**Comment by LHeczko** [comment]
Hi! Any chance of getting it to work? I noticed that it happens when I add
 <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
to my app. Without tihs everything is ok

**Comment by ddddyyyy** [comment]
Hello!When I use TaskBarIcon from  `Hardcodet.Wpf.TaskbarNotification`  , I also fonud that the Toooltip disappeared.
@LHeczko 's methed works!
It seems that the reason is the customizing to  Notification by `MaterialDesignInXamlToolkit` .

**Comment by melcug** [comment]
I managed to show the tooltip for the notify icon (Hardcodet.Wpf.TaskbarNotification) using a custom appearance for it.

![tooltip](https://user-images.githubusercontent.com/8708178/108386614-7bb0dc00-7215-11eb-8a83-1a4a83618084.png)

`<tb:TaskbarIcon
            x:Name="NotifyIcon"
            IconSource="pack://application:,,,/Resources/app.ico"
            LeftClickCommand="{StaticResource ShowWindowCommand}"
            MenuActivation="RightClick">
            <tb:TaskbarIcon.TrayToolTip>
                <Border
                    Background="{DynamicResource MaterialDesignPaper}"
                    BorderBrush="{DynamicResource MaterialDesignShadowBrush}"
                    BorderThickness="1">
                    <TextBlock
                        Padding="8,4,8,4"
                        Foreground="{DynamicResource MaterialDesignDarkBackground}"
                        Text="My tooltip"
                        TextAlignment="Center" />
                </Border>
            </tb:TaskbarIcon.TrayToolTip>
...
 </tb:TaskbarIcon>`

**Comment by MichelMichels** [comment]
This seems completely fixed. I tested with following code:
```xaml
<tb:TaskbarIcon
            x:Name="myNotifyIcon"
            MenuActivation="LeftOrRightClick"
            PopupActivation="DoubleClick"
            ToolTipText="Fallback ToolTip for Windows xp"
            Visibility="Visible">
            <tb:TaskbarIcon.ContextMenu>
                <ContextMenu>
                    <MenuItem Header="Item 1">
                        <MenuItem Header="Sub item 1" />
                        <MenuItem Header="Sub item 2" />
                    </MenuItem>
                    <MenuItem Header="Item 2" />
                    <MenuItem Header="Item 3" />
                </ContextMenu>
            </tb:TaskbarIcon.ContextMenu>
        </tb:TaskbarIcon>
```

**Comment by VahidEra** [comment]
@MichelMichels Dear Michel, The context menu problem is solved, but the tooltip text is still displayed at the top of the screen. Do you have any suggestions to solve this problem, my friend?

![2023-02-24_171833](https://user-images.githubusercontent.com/27216710/221196349-d9016e06-fee8-4ddf-9f0d-09fffca753f4.png)

**Comment by MichelMichels** [comment]
@VahidEra you could try following code:

```xaml
          <tb:TaskbarIcon.TrayToolTip>
              <ToolTip Style="{x:Null}">
                  <TextBlock Text="Tooltip" />
              </ToolTip>
          </tb:TaskbarIcon.TrayToolTip>
```

I've not yet worked out why the placement is wrong.

**Comment by MichelMichels** [comment]
@VahidEra The problem is the `Placement` property on the default MaterialDesign tooltip style.

You can use following XAML to work around the issue:

```xaml
<tb:TaskbarIcon.TrayToolTip>
    <ToolTip Placement="Mouse">
        <TextBlock Text="{Binding Text}" />
    </ToolTip>
</tb:TaskbarIcon.TrayToolTip>
```
