### ISSUE TITLE
In case of ValidationError red Border is displayed arround the hosting control

### ISSUE THREAD

**Issue by DrCQ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1851]
I use the default ErrorTemplate for validation of the ComboBox Text property and in case of error the proper error message in red is displayed below the text border line.
` <ComboBox  IsEditable="True"  matD:HintAssist.Hint="Type text please ..." matD:HintAssist.IsFloating="True"
                   Text="{Binding ComboBoxText, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ValidatesOnDataErrors=True, ValidatesOnNotifyDataErrors=True}"/>
`
Unfortunately also a red border around  the hosting control is displayed too. I believe that this is some wrong property setting but cannot find anything solving my problem. Any help is really appreciated!

Regards,
Christoph

**Comment by greuelpirat** [comment]
The red border is the default error template. I guess there is an other component where you need to clear the `Validation.ErrorTemplate`
