### ISSUE TITLE
Circular Progress Indicator disappears when Value equals Maximum

### ISSUE THREAD

**Issue by adrianhara** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1854]
I'm trying to use a circular progress indicator  Style="{StaticResource MaterialDesignCircularProgressBar} and if Maximum is equals to Value, it dissapears. I can reproduce this in the WPF demo app if I go to e.g. the animated circular progress bar, disable the animation and simply set e.g. Maximum="10" Value="10". Is this a bug or am I missing something?

Thanks!

**Comment by greuelpirat** [comment]
I think this is a bug. An arc is used to draw the progress. And at 100 % the start point of the arc is identical to the end point. So nothing is drawn.

On https://material.io/components/progress-indicators#circular-progress-indicators the circular progress indicator also disappears when reached 100 %. But that would be an additional animation and requires an present circle to disappear.

I created #1857 to fix that.

**Comment by adrianhara** [comment]
Very nice work thanks! I figured out the problem was with the arc but I fixed it locally by drawing the arc minus 0.01 degrees if it was 360. Your solution is much better.
