### ISSUE TITLE
An error occurred while displaying the user interface

### ISSUE THREAD

**Issue by mincasoft** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1858]
![image](https://user-images.githubusercontent.com/42678520/82726533-060ff200-9d0f-11ea-832c-05c7ca445066.png)

I have a textbox set up with the attribute "Visibility = Collapsed"
I designed a button that performs a certain action. And without letting the user interact with the form while I wait, I set the IsEnabled = false property of usercontrol.
There is an error displayed as shown

**Comment by Keboo** [comment]
Can you test with the latest `3.2.0-ci1494` to see if this issue is resolved. This looks like it might be the same issues as #1840

**Comment by mincasoft** [comment]
Yes! version 3.2.0-ci1494 is OK

**Comment by Keboo** [comment]
Thanks, marking as resolved in 3.2.0
