### ISSUE TITLE
HintAssist "Background" is not working at PasswordBox

### ISSUE THREAD

**Issue by bezzad** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1860]
Why `HintAssist.Background` is not working at the `PasswordBox` element?
my **XAML** codes is like this:

```xaml
<PasswordBox x:Name="PassBox" 
     Margin="10" Padding="0 -5 0 0" VerticalContentAlignment="Center"
     materialDesign:TextFieldAssist.HasClearButton="True"
     materialDesign:ValidationAssist.Background="Transparent"
     materialDesign:HintAssist.Foreground="Gray"
     materialDesign:HintAssist.Background="Red"
     materialDesign:HintAssist.Hint="{x:Static shared:Resources.Password}" 
     materialDesign:HintAssist.FloatingScale="1"
     FlowDirection="{x:Static helpers:DesignerHelper.FlowDirection}"
     Style="{DynamicResource MaterialDesignOutlinedPasswordFieldPasswordBox}">
</PasswordBox>
```

But always the hint text background is `White`!

![image](https://user-images.githubusercontent.com/10928710/82735149-c2c87a00-9d34-11ea-8536-5d5358c83944.png)

**Comment by Keboo** [comment]
Looks like this is a bug. This property has not yet been implemented for the password box.

**Comment by bezzad** [comment]
No other way to change that hint background? I want to use `MaterialDesignOutlinedPasswordFieldPasswordBox` in my project password boxes in a dark theme!

**Comment by greuelpirat** [comment]
`HintAssist.Background` was moved with cf57a29 from Style to Template-Trigger. So it can not be overwritten any more. @Keboo do you know, why you changed that?

**Comment by Keboo** [comment]
@greuelpirat This looks like a mistake on my part. The only reason for setting the background is for when there is a floating hint and a border. The floating hint needs to cover the outline rather than be transparent.

**Comment by greuelpirat** [comment]
@bezzad I am working on this.

Currently you can work around this by overriding `MaterialDesignPaper` for your `PasswordBox`:

```
<PasswordBox ...>
  <PasswordBox.Resources>
    <SolidColorBrush x:Key="MaterialDesignPaper" Color="Brown" />
  </PasswordBox.Resources>
</PasswordBox>
```

**Comment by bezzad** [comment]
Thank you so much, that works perfectly.
