### ISSUE TITLE
Buttons have different appearance from demo app

### ISSUE THREAD

**Issue by midasw** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1863]
Issue:
------

Buttons have missing hover background color and outlined button has purple outline instead of gray.

Steps to reproduce:
---------------------
Using Visual Studio Community 2019:
- Follow [Super Quick Start guide](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start)
- Add button to main window with `MaterialDesignFlatButton` style
- Add button to main window with `MaterialDesignOutlinedButton` style

Result:
-------
![Capture](https://user-images.githubusercontent.com/58330002/82840927-9ba8ae80-9ed4-11ea-9cdd-b8e7ce65bc27.PNG)

XAML:
-------
```
<Grid>
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button Margin="0 10" Style="{StaticResource MaterialDesignFlatButton}">MaterialDesignFlatButton</Button>
        <Button Margin="0 10" Style="{StaticResource MaterialDesignOutlinedButton}">MaterialDesignOutlinedButton</Button>
    </StackPanel>
</Grid>
```

**Comment by greuelpirat** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start is outdated.

There were Theme-Changes with `3.0.0` documented here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started

Instead of ...
```
<ResourceDictionary.MergedDictionaries>
  <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
  <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
  <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
  ...
</ResourceDictionary.MergedDictionaries>
```
use:
```
<ResourceDictionary.MergedDictionaries>
  <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
  ...
</ResourceDictionary.MergedDictionaries>
```

The difference here is, that `materialDesign:BundledTheme` is setting some colors programmatically.  Without it, there are some colors and therefore some effects missing. I do not know a other way to set those colors.

**Comment by greuelpirat** [comment]
I just updated https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start.
I hope that is okay.

**Comment by midasw** [comment]
Thanks @greuelpirat! Completely overlooked that page of the documentation. It solves the problem nicely.

**Comment by midasw** [comment]
As for replicating the `MaterialDesignOutlinedButton` with grey outline, I defined a custom style like this:

```
<Style x:Key="MaterialDesignGreyOutlinedButton" BasedOn="{StaticResource MaterialDesignOutlinedButton}" TargetType="{x:Type ButtonBase}">
    <Setter Property="BorderBrush" Value="{StaticResource MaterialDesignFlatButtonClick}" />
</Style>
```

**Comment by greuelpirat** [comment]
I agree, that the grey button should be available.

In the specs https://material.io/components/buttons#outlined-button the border is in fact grey and not in primary color. So I think that style should be added or even be the default outline style. 

I think I will create pull request for that.

**Comment by midasw** [comment]
@greuelpirat  I agree!

Apparently it was the default style at some point. See this screenshot from an old version of the demo app.

![DemoApp](https://user-images.githubusercontent.com/58330002/83091280-20452980-a09b-11ea-8a6e-09534ff6f8fc.PNG)

**Comment by Codwy** [comment]
> 
> 
> https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start is outdated.
> 
> There were Theme-Changes with `3.0.0` documented here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started
> 
> Instead of ...
> 
> ```
> <ResourceDictionary.MergedDictionaries>
>   <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
>   <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
>   <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
>   ...
> </ResourceDictionary.MergedDictionaries>
> ```
> 
> use:
> 
> ```
> <ResourceDictionary.MergedDictionaries>
>   <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
>   ...
> </ResourceDictionary.MergedDictionaries>
> ```
> 
> The difference here is, that `materialDesign:BundledTheme` is setting some colors programmatically. Without it, there are some colors and therefore some effects missing. I do not know a other way to set those colors.

Why the demo app is still using the old way to define themes while the new one is commented out in [App.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml)?

**Comment by greuelpirat** [comment]
@Codwy I do not know :-)

**Comment by Keboo** [comment]
@Codwy the reason the demo app uses the old way was simply an artifact of age, it should probably get updated to show the preferred approach.
