### ISSUE TITLE
Spurious ResourceDictionary Warning 9 when unloading controls

### ISSUE THREAD

**Issue by TheMightyBorkon** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1867]
It appears that when controls are unloaded spurious warnings are being written to the Output window in VS. (I don't know where such warnings go in a Release build run outside of VS).

The warning text is this:

`System.Windows.ResourceDictionary Warning: 9 : Resource not found`

Note that the resource key is not given as part of the warning.

Here is a [GitHub repo](https://github.com/TheMightyBorkon/MaterialDesignWpfResourceWarning.git) that reproduces the problem. It basically consists of a single window with two buttons. The first button adds a TextBox to a Grid; the second button removes it. The warnings are output when the TextBox is removed.

Although the warnings don't seem to affect how the app works, there is a noticeable delay when many of them are written, as is the case when a Window may have many such controls and they are all unloaded suddenly (think: switching out one View for another, as in an MVVM framework).

Is there anything that can be done to prevent these warnings from being output?

---

Note that I only tested with a TextBox, but I presume the other controls such as ComboBox, etc will have a similar problem

**Comment by Keboo** [comment]
Thank you for the bug write up. Will need to spend some time looking at the root cause of this.

**Comment by greuelpirat** [comment]
This warning does not appear on current master. I tracked it down where they disappear to 736e7b32. So it seems that it is fixed with #1852. 

I guess the two warnings are about the two missing colors that were added.

**Comment by Keboo** [comment]
Thanks @greuelpirat

**Comment by TheMightyBorkon** [comment]
I can confirm that using the latest pre-release build fixed this problem in that the warnings were no longer displayed.

Thanks for looking into this.

**Comment by jamesport079** [comment]
I'm still receiving these warnings when closing tabs. I will look into the issue to see if Material Design is responsible.

**Comment by vsharma2430** [comment]
I'm also receiving the same warnings in WPF application.

**Comment by lxman** [comment]
Seeing the same with a MahApps WPF app.

```System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.IdealForeground'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.ThemeForeground'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.IdealForeground'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.ThemeForeground'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.IdealForeground'
System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MahApps.Brushes.ThemeForeground'```
