### ISSUE TITLE
DataGridNumericUpDownColumn is not support for MaterialDesignThemes3.1.3 with MahApps.Metro2.0.0

### ISSUE THREAD

**Issue by my522cn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1870]
before MahApps.Metro2.0.0, DataGridNumericUpDownColumn is shown well.
after MahApps.Metro2.0.0, it blank, white foreground and white background.

**Comment by Keboo** [comment]
I am not able to reproduce this with the MahApps demo application. Can you please post additional details; ideally a project that reproduces the problem.

**Comment by bombipappoo** [comment]
Launch the MahApps demo application and click MAHAPPS-NumericUpDown, nothing is displyed as below. Once change the theme on the PALETTE page, it will be displayed correctly.

![updown1](https://user-images.githubusercontent.com/66123786/84850812-9d106580-b093-11ea-974a-987f8c4158a5.png)

Add the following line to App.xaml, it will be displayed correctly.
```
  <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Purple.xaml" />
```

**Comment by Keboo** [comment]
I have a work in progress branch that I believe will resolve this. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/themeFixes

**Comment by bombipappoo** [comment]
Yes it's fixed.
