### ISSUE TITLE
MaterialDesignFloatingHintTextBox IsEnabled takes priority over Visibility state

### ISSUE THREAD

**Issue by jbooth88** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1871]
The MaterialDesignFloatingHintTextBox style (perhaps other similar styles) will prioritize the disabled visual state over the visibility state.

Meaning a textbox with Enabled = False and Visibility = Collapsed will display a disabled text box instead of hiding its visibility. I'm not sure if this is by design, but the default textbox style does not follow this behaviour. 

Repro xaml:

`   <TextBox Visibility="Collapsed" IsEnabled="False" Text="Testing"
             Style="{DynamicResource MaterialDesignFloatingHintTextBox}"
             Width="192" Height="48" HorizontalAlignment="Center" VerticalAlignment="Center" />`

**Comment by Keboo** [comment]
This appears to be resolved in the latest 3.2.0 preview packages.
