### ISSUE TITLE
Visual Studio 2019 is freezing when using custom colours

### ISSUE THREAD

**Issue by darth-den-007** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1875]
Hello,

My Visual Studio is freezing when I tried to use custom colours. Here is what I did. 

1. Use Visual Studio 2019 to create a new WPF App (.NET Core 3.1)
2. Install last version of MaterialDesignThemes and MaterialDesignColors
3. Follow the instructions from here: [https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Custom-Palette-Hues](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Custom-Palette-Hues)
4. Try to adjust the colour of PrimaryHueLightBrush to something else e.g. Primary300
5. Visual Studio is freezing

**Comment by vsuyi** [comment]
VS2019 stop response too when I try to "build" or "debug" solution on using PackIcon, it takes a while (minutes) and resume to OK.

**Comment by Keboo** [comment]
I am not able to reproduce this using Visual Studio 16.4.6.
I would suggest making sure you are on the [latest version of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2019).
If that does not address it, I would file a bug with Microsoft using the [Submit feedback feature](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) inside of Visual Studio.

**Comment by pressacco** [comment]
I too have observed Visual Studio 2019 (v16.8.5) responsiveness or "freezing" issues when using custom colors + 
MaterialDesignThemes 4.0.0.

It might be a coincidence, but I do not see this behavior when using MaterialDesignThemes v4.0.0-ci2347.
