### ISSUE TITLE
TextFieldAssist.HasClearButton changes size of control

### ISSUE THREAD

**Issue by lszczygielek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1883]
I found and issue with TextFieldAssist.HasClearButton="True". When my TextBox has it then when I type something and X icon appears, then control has a bigger height by 1 or 2 pixels. It makes size/location fluctuation on controls which are below.

This behavior is visible in demo application. Steps to reproduce:
Demo App > Fields > WiFi TextBox
1. Put value in TextBox.
2. Observe that controls below are moved a little bit down (all **Filled fields** section).

**Comment by Keboo** [comment]
I can confirm that there is a sizing change occurring, but it appears to be caused by the floating hint rather than the clear button.
![TextBoxSize](https://user-images.githubusercontent.com/952248/83606446-75b38780-a52e-11ea-80ac-160c005e0642.gif)
