### ISSUE TITLE
Validation message/popup overlapping Outlined TextBox

### ISSUE THREAD

**Issue by CorradoBarbero** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1898]
When using validation on an outlined TextBox, the message overlaps the border of the TextBox, as in the example here:
![image](https://user-images.githubusercontent.com/62978436/83960513-81070a00-a8c4-11ea-84aa-908874c9ec78.png)
The first TextBox uses the standard message, the second has 
`materialDesign:ValidationAssist.UsePopup="True"
materialDesign:ValidationAssist.PopupPlacement="Bottom"`
but in both cases the results looks visually broken.

Full code example available.

**Comment by Keboo** [comment]
I can see why this s happening. I think the question is what is the correct behavior in these situations?

I am open to suggestions here. My initial though is to simply move the validation message down so that it does not overlap with the outline. Thoughts?

**Comment by CorradoBarbero** [comment]
Yep, I think it makes perfect sense, just move it down so that that it does not overlap

**Comment by KHALED-LAKEHAL** [comment]
I think add Margin Property to <Border x:Name="DefaultErrorViewer"
                    Visibility="Collapsed"
                   Margin="0,3,0,0"
                    Background="{Binding ElementName=Placeholder, Path=AdornedElement.(wpf:ValidationAssist.Background)}">
