### ISSUE TITLE
Build error in VS2019 V16.6.1

### ISSUE THREAD

**Issue by nonokme** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1901]
# Build error in VS2019 V16.6.1
# Compiling From Source error,MaterialDesignThemes.MahApps has loaded successfully,but the output:
Error restoring nuget package: unable to load project MaterialDesignThemes.MahApps Details of, operation failed.
1> ------ rebuild all started: Project: MaterialDesignColors.Wpf , configuration: debug any CPU------
1>Paket version 5.242.0
1>Paket version 5.242.0
1>F:\Xuxiangyu\MaterialDesign\MahMaterialDragablzMashUp\obj\paket.processlock is locked by paket.exe (PID = 7252). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...
1>F:\Xuxiangyu\MaterialDesign\paket-files\paket.processlock is locked by paket.exe (PID = 6672). Waiting...

# error list:
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	
MSB3073	Commond “"F:\Xuxiangyu\MaterialDesign\.paket\paket.exe" restore” exited，code 1。	MaterialDesignThemes.Wpf	F:\Xuxiangyu\MaterialDesign\.paket\Paket.Restore.targets	171	

# I donnot know why,please help me,thank you very much!

**Comment by Lungbo** [comment]
Hi,
I'm facilitated, that someone else has the same problem. So as you can see you are not the only one with this problem. I don't know what to do also.
Best Regards

**Comment by nonokme** [comment]
Although it didn't solve the problem, thank you for your reply@Lungbo

**Comment by Keboo** [comment]
A couple things to try. First, since this is a `paket` restore issue, I would suggest simply closing Visual Studio (making sure all rouge MSBuild processes are terminated), then simply restart it. The other option would be to run the following from the root of the repository (ensure Visual Studio is not running).
```
> .\.paket\paket.exe restore
```

**Comment by pahibu** [comment]
In my case the folder name was too long. I moved the repository to c:\ and ran the program twice. Now it works :-)
Otherwise I only paid attention to [this page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source)

**Comment by wim07101993** [comment]
Same issue. Moved folder to C:// but did not work...

msbuild -t:restore output:
```
C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf>msbuild -t:restore
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 14/10/2020 19:30:25.
Project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" on node 1 (Restore target(s)).
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (1) is building "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (1:3) on node 1 (_GenerateRestor
eProjectPathWalk target(s)).
PaketRestore:
  dotnet paket restore --project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" --output-path "obj" --target-framework "net45;netcoreapp3.1"
  Run "dotnet tool restore" to make the "paket" command available.
C:\MaterialDesignInXamlToolkit\.paket\Paket.Restore.targets(218,5): error MSB3073: The command "dotnet paket restore --project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" --output-path "obj"
 --target-framework "net45;netcoreapp3.1"" exited with code 1. [C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj]
Done Building Project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (_GenerateRestoreProjectPathWalk target(s)) -- FAILED.

Done Building Project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (Restore target(s)) -- FAILED.


Build FAILED.

"C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (Restore target) (1) ->
"C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" (_GenerateRestoreProjectPathWalk target) (1:3) ->
(PaketRestore target) ->
  C:\MaterialDesignInXamlToolkit\.paket\Paket.Restore.targets(218,5): error MSB3073: The command "dotnet paket restore --project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" --output-path "ob
j" --target-framework "net45;netcoreapp3.1"" exited with code 1. [C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.72
```

The errors are the same for every project. Help?

**Comment by Keboo** [comment]
@wim07101993 it looks like you are trying to compile them using MSBuild. These projects use the latest version of .NET Core and you will need the [dotnet cli](https://docs.microsoft.com/en-us/dotnet/core/tools/) to compile them running `dotnet build`.

**Comment by wim07101993** [comment]
That was what i tried first but it gives roughtly the same error:
```
dotnet build .\MaterialDesignColors.Wpf\
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Run "dotnet tool restore" to make the "paket" command available.
C:\MaterialDesignInXamlToolkit\.paket\Paket.Restore.targets(218,5): error MSB3073: The command "dotnet paket restore --project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" --output-path "obj" --target-framework "net45;netcoreapp3.1"" exited with code 1. [C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj]

Build FAILED.

C:\MaterialDesignInXamlToolkit\.paket\Paket.Restore.targets(218,5): error MSB3073: The command "dotnet paket restore --project "C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj" --output-path "obj" --target-framework "net45;netcoreapp3.1"" exited with code 1. [C:\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\MaterialDesignColors.Wpf.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.39
```

**Comment by wim07101993** [comment]
Ok I ran the `dotnet tool restore` command and then the `dotnet build` command from the cli. Which seems to have fixed it. But perhaps it should come in the docs since they just say open solution and press F5, which I did first 😉.

**Comment by Keboo** [comment]
Paket has now been removed please see the latest requirements for compiling from source: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source
