### ISSUE TITLE
Bug in a hidden textbox

### ISSUE THREAD

**Issue by danielGarciaBezzier** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1911]
When a textbox has IsEnabled property set to false and Visibility = Hidden. The dotted underline is visible but the rest of the control dissappear correctly. Version 3.1.3
An example of my case:

`  <TextBox IsEnabled="False" Visibility="Hidden">
                            <materialDesign:HintAssist.Hint>
                                <StackPanel Orientation="Horizontal" Margin="-2 0 0 0">
                                    <materialDesign:PackIcon Kind="Camera" />
                                    <TextBlock xml:space="preserve"> Text</TextBlock>
                                </StackPanel>
                            </materialDesign:HintAssist.Hint>
                        </TextBox>`

**Comment by greuelpirat** [comment]
This is fixed with #1842

**Comment by Keboo** [comment]
You can test with the latest 3.2.0 preview NuGet packages to confirm this is resolved.
