### ISSUE TITLE
[Question] Changing title bar color?

### ISSUE THREAD

**Issue by MetalWing** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1912]
I am trying to convert an app that was designed using Mah.Metro to be completely MaterialDesign. I want no trace of MahApps. 

However, the main window XAML uses `WindowTitleBrush="{Binding StatusColour}"` which seems to only be available in `mah:MetroWindow`

Am I going to have to go with integrating MaterialDesign into the Mah.Metro app? Or is there a way to change window title bar in the toolkit?

**Comment by CorradoBarbero** [comment]
As far as I know WPF does not have any native way of interacting with the window chrome, so MaterialDesignInXAML simply cannot do it.
I use Syncfusion Chromeless Window.
HTH.

**Comment by Keboo** [comment]
Currently the only way to do that is with MahApps. The reason is because to control those colors you need to setup custom window's chrome to achieve that level of customization. We have never implemented that directly in the library because MahApps provides a good implementation for it. 

I am curious, why do you want to avoid MahApps?

**Comment by MetalWing** [comment]
@Keboo Thank you for the response! 

I have nothing against MahApps, I just figured if MaterialDesignInXaml does everything I need, I might as well lighten the project and remove unnecessary components. 

Given that MahApps allows me to have coloured title bar, I am likely going to have to keep both! :)

**Comment by CorradoBarbero** [comment]
For what is worth, also Material Design Extensions provides that feature, so there are actually several options.

**Comment by MetalWing** [comment]
@CorradoBarbero This might be what I am looking for! Thank you!
