### ISSUE TITLE
Changing the FontFamily of a TextBox will change the font of the floating hint

### ISSUE THREAD

**Issue by tarockx** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1914]
If I change the default font family for a textbox that has a floating hint, like this:

`<TextBox FontFamily="Courier New" materialDesign:HintAssist.Hint="Expected result"></TextBox>`

the font family also applies to the hint label:

![image](https://user-images.githubusercontent.com/10919460/84370217-40ff9a00-abd8-11ea-8f4e-a1a698fd971d.png)

as you can see, this makes the label ugly and difficult to read, since the font in question is not suitable for such a small size and becomes pixellated.

Is there a way to only change the font for the typed text and keep the default font on the hint label?

**Comment by Keboo** [comment]
By default the hint follows the font family of the TextBox. I think what we should do is to create a new HintAssist.FontFamily attached property to allow the font family of the hint to be controlled separately.
