### ISSUE TITLE
Is there a way to show several stacked Dialogboxes ?

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1924]
This is a question,
Is there a way to show several stacked Dialogboxes with `materialDesign:DialogHost` ?

Regards

**Comment by Keboo** [comment]
Currently, no. Each DialogHost can only show a single dialog at a time. However, you can have multiple DialogHosts, allowing you to effectively stack multiple dialogs.
