### ISSUE TITLE
Cannot scroll in Listview when items are expanders

### ISSUE THREAD

**Issue by Elsassma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1928]
I have a Scrollviewer which contains a listview where i had redefined the itemtemplate to be an extander.
However when I try to scroll up or down in my list with the mouse wheel, it doesn't work when the mouse is on one of the expanders (the scroll works when my mouse is not on the items).
It seems that the Expander in the list hijack the mouse wheel and prevent the control from scrolling.

I know there are similar issues ([#334](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/334) & [#342](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/342)) but the problem is always here for me.

**Comment by Keboo** [comment]
Can you provide some sample code showing the problem. I suspect the issue is that something is marking the mouse wheel event as handled before it reaches the list view.

**Comment by Elsassma** [comment]
Here is the xaml :

    <ContentControl>
         <Grid>
           [...]
            <ScrollViewer Grid.Row="1" VerticalScrollBarVisibility="Auto">
                    <ListView ItemsSource="{Binding DiagResult.DiagnosticResults}">
                        <ListView.ItemContainerStyle>
                            <Style TargetType="{x:Type ListViewItem}">
                                <Style.Triggers>
                                    <Trigger Property="IsMouseOver" Value="True">
                                        <Setter Property="Background" Value="{StaticResource PrimaryHueMidBrush}" />
                                        <Setter Property="BorderThickness" Value="0" />
                                    </Trigger>
                                </Style.Triggers>
                            </Style>
                        </ListView.ItemContainerStyle>
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <Border HorizontalAlignment="{Binding Path=HorizontalAlignment, RelativeSource={RelativeSource FindAncestor, AncestorType={x:Type ContentPresenter}}, Mode=OneWayToSource}"
                                        BorderBrush="{StaticResource PrimaryHueMidBrush}"
                                        BorderThickness="0,1,0,0">
                                    <Expander mde:ExpanderAssist.DownHeaderPadding="0 0 0 0"
                                              Background="Transparent"
                                              Foreground="{StaticResource ActiveForegroundBrush}">
                                        <Expander.Header>
                                            <Grid Margin="10">
                                                <Grid.ColumnDefinitions>
                                                    <ColumnDefinition Width="auto" />
                                                    <ColumnDefinition Width="*" />
                                                    <ColumnDefinition Width="2*" />
                                                </Grid.ColumnDefinitions>
                                                [...]
                                            </Grid>
                                        </Expander.Header>
                                        <StackPanel Orientation="Vertical">
                                            [...]
                                        </StackPanel>
                                    </Expander>
                                </Border>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>
                </ScrollViewer>
    [...]

**Comment by Keboo** [comment]
It looks like the issue is with the ListView inside of the ScrollViewer. Because the ScrollViewer allows the ListView to grow in size infinitely it doesn't show its own scroll bar (which it normally would). However, it still captures the mouse wheel events, and those don't propagate to the ScrollViewer.

Typically you should not put a list view inside of a ScrollViewer, or you should use an ItemsControl instead of the ListView.

**Comment by Elsassma** [comment]
You're right, it was the problem.
I changed the Listview for an ItemsControl and it works fine. Good to know.

Thank you for you help!
