### ISSUE TITLE
Password box hint slides out

### ISSUE THREAD

**Issue by ghost** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1940]
For the MaterialDesignFilledPasswordFieldPasswordBox style the hint will slides out if you have set font size for example on 16 and type a password in.

The problem can be solved by replace „Padding“ by „Margin“ at line 164 at MaterialDesignTheme.PasswordBox.xaml

**Comment by ruksarjk** [comment]
Hello,

I'm new here. Could I please work on this issue?
