### ISSUE TITLE
Open a drawer & Execute a Command at the same time 

### ISSUE THREAD

**Issue by HamzaIssam** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1941]
I wonder if it's possible to execute the Opendrawer Command & simultaneously another Command at the same time?

I can't call the Drawer command by c# code because the View and the ViewModel are bound through Dependency Injection using Prism. 

I tried to register both my command and the DrawerHost.OpenDrawerCommand in a Prism composite command and bound it to the button but the button is now greyed out as inactive.

Any help would be appreciated. Thank you very much.

```
            MultiCommand = new CompositeCommand();
            MultiCommand.RegisterCommand(DoneCommand);
            MultiCommand.RegisterCommand(DrawerHost.OpenDrawerCommand);
```

**Comment by bombipappoo** [comment]
You can set `DrawerHost.IsLeftDrawerOpen` etc. to true in your command, instead of using `DrawerHost.OpenDrawerCommand`.
For example, like this.

```
    class YourCommand: ICommand
    {
        public void Execute(object parameter)
        {
            ((DrawerHost)parameter).IsLeftDrawerOpen = true;
            ...
```
```
    <Button Command="{Binding YourCommand}"
            CommandParameter="{Binding RelativeSource={RelativeSource AncestorType={x:Type materialDesign:DrawerHost}}}"
            ...
```

**Comment by Keboo** [comment]
It is also worth noting that the [Prism CompositeCommand](https://prismlibrary.com/docs/composite-commands.html) is not expected to run the commands in parallel, rather 

> When the composite command is invoked, each of its child commands is invoked in turn.

I think the suggestion of using the Is*DrawerOpen properties is likely the best option.

**Comment by HamzaIssam** [comment]
Thank you guys for your help, using the DrawerOpen Property helped and works fine.
