### ISSUE TITLE
MaterialDesignThemes.MahApps 0.1.4 issue with .Net Framework

### ISSUE THREAD

**Issue by Mrxx99** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1942]
I added MaterialDesignThemes.MahApps 0.1.4 to a .Net Framework WPF app and copied the resource setup from the demo app:
![grafik](https://user-images.githubusercontent.com/33566379/85874399-df901b80-b7d2-11ea-9ceb-0f8527bfb4fa.png)
When I start I get an exception as soon as I start. The error in the screenshot is after upgrading MahApp.Metro to 2.1.0.

Also strange that the .Net Framework version depends on a preview of MahApps:
![grafik](https://user-images.githubusercontent.com/33566379/85874962-c50a7200-b7d3-11ea-8477-436961af9a61.png)

**Comment by Keboo** [comment]
@Mrxx99 I am not sure which resource dictionary is having that problem. From testing, it looks like it is probably one of the MahApps resources. If you comment out the MahApps resource dictionaries the warning goes away. I would log an issue of the the [MahApps repo](https://github.com/MahApps/MahApps.Metro).
