### ISSUE TITLE
TextBox lines from other tab shines through, when opacity is set to less then 1

### ISSUE THREAD

**Issue by TFTomSun** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1944]
I've created a popup with a tab control:
![image](https://user-images.githubusercontent.com/5387192/85909824-0e7eaf80-b81c-11ea-8142-1304f252d378.png)

When I switch to another tab, the lines of the textboxes of the first tab shine through as dashed lines:

![image](https://user-images.githubusercontent.com/5387192/85909848-33732280-b81c-11ea-9fd4-2378a61db72c.png)

Is that a known issue? Is there a simple workaround? I already tried to make the first tab content explicit invisible, without success.

**Comment by bombipappoo** [comment]
It looks similer to #1846.

**Comment by TFTomSun** [comment]
yes, thanks for the hint. I can confirm it's fixed with the latest prerelease.
