### ISSUE TITLE
Question: Is it possible to reduce the padding of a button, so that its icon fills out the whole button

### ISSUE THREAD

**Issue by TFTomSun** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1947]
When I put an icon into a button content, there a huge padding. Can I somehow decrease it?
When I set padding to 0, there's still some padding on the top of the icon:
![image](https://user-images.githubusercontent.com/5387192/85959788-ba500880-b99e-11ea-8e53-73a85f56d40a.png)

**Comment by AmRo045** [comment]
Try this:
```xaml
<Button
    Padding="0"
    Height="Auto"
    HorizontalAlignment="Center" 
    VerticalAlignment="Center">
    <md:PackIcon Kind="Tea"/>
</Button>
```

**Comment by TFTomSun** [comment]
@AmRo045 thanks alot Height="Auto" did it! :)
