### ISSUE TITLE
Can support WPF schedule control ?

### ISSUE THREAD

**Issue by zhaobingwang** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1948]
Can support WPF schedule control ? (Similar Microsoft Outlook Calendar)

**Comment by Keboo** [comment]
Currently no. This is a bit outside of the scope of this library. This is designed to bring Google's Material Design spec to WPF. Currently the closest thing to that is the calendar picker (which is pretty far from the full scheduling control).
