### ISSUE TITLE
ComboBox issue

### ISSUE THREAD

**Issue by theW01f** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1949]
I have the following ComboBox in XAML:

```
<ComboBox Grid.Row="1" Grid.Column="1" x:Name="Data" Width="175" Foreground="White" Cursor="Hand" SelectedItem="{Binding Path=SelectedData, Mode=TwoWay}" DisplayMemberPath="Tag" materialDesign:HintAssist.Hint="Seleccionar Celda" Margin="0 0 0 0">
```

![image](https://user-images.githubusercontent.com/56007963/86010565-f496c580-b9f1-11ea-880c-ecac769afac6.png)

How to remove the background line that it's showing inside the red loop?

**Comment by Keboo** [comment]
Appears to be the same issue as #916. Functionally the issue is that we try to draw a popup control with a "hole" in it to show the underlying control. However this is a bit problematic in some cases as that popup must be positioned exactly over the combo box control
