### ISSUE TITLE
Remove hardcoded Margin and Font size from MaterialDesignFilterChipCheckBox

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1952]
... and MaterialDesignFilterChipOutlineCheckBox

`        <Setter Property="FontSize" Value="13" />
        <Setter Property="Margin" Value="4" />
`

Not sure why it's there.  I have to manually set margin to -4 to align it with other controls.
Would be nice to inherit font as well.

**Comment by Keboo** [comment]
I agree with the proposal.

**Comment by Keboo** [comment]
Hi @NaamaBarIlan welcome!
Yes this is still available. 
If you have any questions please feel free to reach out.

**Comment by NaamaBarIlan** [comment]
#2047
