### ISSUE TITLE
about GetExtendedTheme() is error

### ISSUE THREAD

**Issue by myn724405566** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1965]
Why does the method GetExtendedTheme()  report an error 
![61DF321C-5CF9-427c-8E78-45524405A038](https://user-images.githubusercontent.com/23432448/86589043-7624bf80-bfbf-11ea-8a2d-12bd58579d04.png)

**Comment by bombipappoo** [comment]
`GetExtendedTheme()` is not a part of Material Design In XAML Toolkit, probably part of [Material Design Extensions](https://github.com/spiegelp/MaterialDesignExtensions).
In method `ResourceDictionaryExtensions()`, the `BindingFlags` for the private static property is incorrect.

**Comment by Keboo** [comment]
I believe that @bombipappoo is correct. `GetExtendedTheme` is not one of the APIs in this library.
