### ISSUE TITLE
Themed applications constantly consume CPU cycles even during idle

### ISSUE THREAD

**Issue by database64128** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1967]
Applications with Material Design Themes constantly consume CPU cycles even when minimized and idle. This behavior leads to a significant amount of CPU time being wasted on these idled apps over time. Both the Material Design In XAML Toolkit and [one project of my own using this theme](https://github.com/database64128/youtube-dl-wpf) have this issue. Can Replicate on my all 3 devices.

Attached is the data from VS performance profiler. It seems most of the activities are UI related. Shouldn't it stop updating the UI when minimized?
[vs_profiler_report_20200706.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/4879942/vs_profiler_report_20200706.zip)

**Comment by HClausing** [comment]
I've left my computer on during some hours with DemoApp running. When I came back, the app was frozen.

**Comment by Keboo** [comment]
Can you retest on `3.2.0-ci1755` or newer. Previously there were some long running tasks with snackbar message queue and I am curious if removing those will have any affect.

**Comment by database64128** [comment]
Just did a test with the latest commit. The performance issue is now gone, as confirmed by the [profiling data](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/4886049/Report20200708-0032.zip). Thanks!

**Comment by database64128** [comment]
After moving around in the demo app for a while, the issue appeared again. But the profiling data certainly looks different than before.
[Report20200708-0046.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/4886093/Report20200708-0046.zip)

**Comment by database64128** [comment]
Updated [my project](https://github.com/database64128/youtube-dl-wpf/tree/theme-test) to `3.2.0-ci1755` and it still has the issue.

**Comment by database64128** [comment]
I think I've found the culprit: `materialDesign:ButtonProgressAssist.IsIndeterminate`.

Previously `IsIndeterminate` was set to true and the indicator visibility was controlled by setting the variable `ShowIndicator`.

``` xaml
<Button
    materialDesign:ButtonProgressAssist.IsIndicatorVisible="{Binding ShowIndicator}"
    materialDesign:ButtonProgressAssist.IsIndeterminate="True"
    Command="{Binding SomeCommand}" />
```

Apparently even when `ShowIndicator` is false, the indicator animation is still being rendered, and it constantly consumes CPU time. The workaround is to also bind `IsIndeterminate` to `ShowIndicator`. This completely stops the animation rendering.

``` xaml
<Button
    materialDesign:ButtonProgressAssist.IsIndicatorVisible="{Binding ShowIndicator}"
    materialDesign:ButtonProgressAssist.IsIndeterminate="{Binding ShowIndicator}"
    Command="{Binding SomeCommand}" />
```

After applying the workaround in my project, idle CPU usage is now constant zero.

**Comment by database64128** [comment]
I tried to locate the bug in the code. But this behavior makes no sense to me.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/0854092258b885f9093890ad476b3adfb802070f/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ProgressBar.xaml#L206-L210

The animation should have stopped when `materialDesign:ButtonProgressAssist.IsIndicatorVisible` is `False`, because `IsVisible` returns true only when `Visibility` is `Visibility.Visible`, and `Visibility` binds to  `IsIndicatorVisible`.

https://github.com/dotnet/wpf/blob/41603ee46249029d2a8b6571eec0374f6b9cd76d/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/UIElement.cs#L3860

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/0854092258b885f9093890ad476b3adfb802070f/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L73

**Comment by bombipappoo** [comment]
What you are looking at is `MaterialDesignCircularProgressBar`, but in this case, what you should look at is `MaterialDesignLinearProgressBar`.

It seems that `IsIndeterminate` should be `False`, as you did, to avoid consuming CPU time when it is not visible.

**Comment by database64128** [comment]
Turns out the original issue is actually a WPF issue: `ProgressBar`'s animations won't stop rendering when it's not visible. See dotnet/wpf#1509.

Since it seems to be very unlikely to get a fix from the upstream, I wonder if it's possible to implement a workaround to stop the rendering of the animations when a `ProgressBar` element is not visible to the user.

Currently for the demo app, after navigating through pages containing the `ProgressBar` element, the app remains to consume a portion of CPU time because the `ProgressBar` animations never stopped. IMO it's necessary to address this, with either a workaround in the theme's implementation, or some little hacks in the demo app.

**Comment by bombipappoo** [comment]
How is it like [this](https://github.com/bombipappoo/MaterialDesignInXamlToolkit/tree/progress-bar-test)?
Currently only linear progress bar and button with progress are supported.

**Comment by database64128** [comment]
> How is it like [this](https://github.com/bombipappoo/MaterialDesignInXamlToolkit/tree/progress-bar-test)?
> Currently only linear progress bar and button with progress are supported.

Indeterminate progress bars now completely stops animations when switched away to another page, but not when the window is minimized. Looks good to me though.

**Comment by bombipappoo** [comment]
Well, I have no good ideas about the window is minimized.

**Comment by database64128** [comment]
> Well, I have no good ideas about the window is minimized.

There is certainly no easy fix. Probably just leave it to the upstream. 😅

**Comment by Keboo** [comment]
Closing for now, as this does not appear to be a problem that can be reasonably solved within this library.
