### ISSUE TITLE
Disabled Hint TextBox & ComboBox controls appear when inside a collapsed container [v3.1.2 & up]

### ISSUE THREAD

**Issue by SaviorXTanren** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1970]
Starting with nuget packet v3.1.2 & higher, I've noticed some of UIs now have an issue where hidden controls that are disabled are

![image](https://user-images.githubusercontent.com/752903/86876388-7c876a00-c099-11ea-929d-7611bc11363f.png)

Unfortunately I've had difficulty attempting to isolate what specifically might be causing this beyond the above statement, so I haven't been able to make a basic sample. Here's what I can identify at lesat:

- This seems to occur with TextBox or ComboBox controls that have the MaterialDesignFloatingHintTextBox or MaterialDesignFloatingHintComboBox styles
- These controls are inside of a grid or similar container that has the visibility of the container said to Collapsed

**Comment by marvac** [comment]
This is fixed with #1842, but you won't see it until the next release.
I'm sure we have quite a few people waiting on this release!
You can also implement the code from the commit yourself until then if it's a dire emergency

**Comment by SaviorXTanren** [comment]
Nah, it's all good. Our app was really far behind on updates, so we just updated to 3.1.1, which is perfectly fine. Thanks!
