### ISSUE TITLE
Sometimes the next button is appearing before cancel button in the first step of stepper control[ 1st image ] and this has a style applied to the next button whereas in second image the next button is after cancel but with no style applied. How to fix this issue? Thanks

### ISSUE THREAD

**Issue by Shreyasj96** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1974]
![CustomerStepper](https://user-images.githubusercontent.com/64590103/87182996-dd65ab00-c302-11ea-9e79-0990a9d5070f.png)
![CustomerDetailsStepper](https://user-images.githubusercontent.com/64590103/87183182-3df4e800-c303-11ea-8201-2570bb7ae6eb.png)

# PLEASE READ BEFORE POSTING AN ISSUE

# This is a place for issues and feature requests. Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. 

My time is limited and .Zip files, code snippets and partial examples are often a time sink.  GitHub also provides great communication and code review tools which can be utilised.

# HOW TO POST A GOOD SAMPLE.  Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc.  If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages".  If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward.  I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Comment by Keboo** [comment]
Can you post your XAML that shows the problem?

**Comment by Shreyasj96** [comment]
<controlsLib:Stepper x:Name="stepper" IsLinear="False" Layout="Horizontal" BlockNavigationOnValidationErrors="True" 
                              ContentAnimationsEnabled="True" 
    NavigationCanceledByValidation="Stepper_NavigationCanceledByValidation" StepNavigationCommand="{Binding StepNavigation}"
                              HorizontalAlignment="Stretch" VerticalAlignment="Stretch"  DoneIconTemplate="{DynamicResource MaterialDesignStepDoneIconTemplate}" ActiveStepChangedCommand="{Binding ActiveStepChanged}"
                              ValidationErrorIconTemplate="{DynamicResource MaterialDesignStepValidationErrorIconTemplate}" Margin="0 30 20 0">

                        <model:Step x:Name="stepCustomerDetails" >
                            <model:Step.Header>
                                <model:StepTitleHeader FirstLevelTitle="Customer Details"/>
                            </model:Step.Header>
                            <model:Step.Content>
                                <StackPanel>
                                    <GroupBox Style="{StaticResource MaterialDesignGroupBox}" VerticalAlignment="Top" Margin="0 0 0 0" materialDesign:ShadowAssist.ShadowDepth="Depth4" Background="{StaticResource MaterialDesignCardBackground}" Width="250" Height="330">
                                        <GroupBox.Header>
                                            <StackPanel Orientation="Horizontal" Margin="0 0 0 0">
                                                <materialDesign:PackIcon Kind="InformationCircle" Foreground="White" Width="25" Height="23"/>
                                                <TextBlock Text="Customer Details" FontSize="14" Margin="10 2 0 0" Foreground="{StaticResource MaterialDesignCardBackground}"/>
                                            </StackPanel>
                                        </GroupBox.Header>
                                        <materialDesign:Card HorizontalAlignment="Center" Width="230" Height="215" Background="White" Margin="0 0 0 0" UniformCornerRadius="3" materialDesign:ShadowAssist.ShadowDepth="Depth3" materialDesign:ShadowAssist.Darken="True" materialDesign:ShadowAssist.ShadowEdges="All">

                                            <StackPanel x:Name="stkPanelCustomerDetails" Width="300" Margin="10 0 0 10" HorizontalAlignment="Center" VerticalAlignment="Top">

                                                <TextBox x:Name="txtBoxPersonInContact" Style="{StaticResource MaterialDesignFloatingHintTextBox}" Width="200" Height="36" Text="{Binding PersonInContact,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged}" Margin="-12 30 0 0" MaxLength="30" materialDesign:TextFieldAssist.HasOutlinedTextField="True" materialDesign:TextFieldAssist.TextFieldCornerRadius="0"
                                                 Padding="0 -6 0 -2.8" materialDesign:TextFieldAssist.TextBoxViewMargin="4" FontSize="13" VerticalAlignment="Bottom"  materialDesign:TextFieldAssist.HasClearButton="True" CommandManager.PreviewCanExecute="TextBox_PreviewCanExecute"
                                                 materialDesign:HintAssist.HelperText="Ex: Lind L Taylor" Foreground="DarkBlue">
                                                    <materialDesign:HintAssist.Hint>
                                                        <StackPanel Orientation="Horizontal" Margin="-2 0 0 0">
                                                            <materialDesign:PackIcon Kind="ClipboardAccount" Height="22" Width="24" Foreground="DarkBlue"/>
                                                            <TextBlock VerticalAlignment="Center" Text="Person In Contact" Margin="5 0 0 0" Foreground="DarkBlue"/>
                                                        </StackPanel>
                                                    </materialDesign:HintAssist.Hint>
                                                </TextBox>

                                                <StackPanel Orientation="Horizontal" Margin="45 35 0 0">
                                                    <DatePicker x:Name="datePickerEnquiryDate" HorizontalAlignment="Left" Foreground="DarkBlue" Text="{Binding EnquiryDate,ValidatesOnDataErrors=True,Mode=TwoWay,UpdateSourceTrigger=PropertyChanged,Converter={StaticResource ComboBoxNullConverter}}" DisplayDateEnd="{x:Static System:DateTime.Now}" SelectedDateFormat="Short"
                                                        materialDesign:ValidationAssist.Background="Transparent"  FontSize="13" ToolTipService.Placement="Right" ToolTipService.HorizontalOffset="10" Width="200"
                                                        materialDesign:TextFieldAssist.TextFieldCornerRadius="0" materialDesign:HintAssist.HelperText="{Binding EnquiryDateHelperText,UpdateSourceTrigger=PropertyChanged,TargetNullValue='Ex: 10-05-2020'}" materialDesign:HintAssist.Hint="Enquiry Date">
                                                        <DatePicker.Style>
                                                            <Style TargetType="DatePicker" BasedOn="{StaticResource MaterialDesignFloatingHintDatePicker}">
                                                                <Setter Property="materialDesign:HintAssist.HelperText" Value="Ex: 10-05-2020"/>
                                                                <Style.Triggers>
                                                                    <Trigger Property="Validation.HasError" Value="true">
                                                                        <Setter Property="materialDesign:HintAssist.HelperText" Value="{x:Null}"/>
                                                                        <Setter Property="ToolTip" Value="{Binding RelativeSource={x:Static RelativeSource.Self},Path=(Validation.Errors)[0].ErrorContent}"/>
                                                                    </Trigger>
                                                                </Style.Triggers>
                                                            </Style>
                                                        </DatePicker.Style>
                                                    </DatePicker>
                                                    <AccessText Text="*" FontSize="22" Foreground="{StaticResource ValidationErrorBrush}"/>
                                                </StackPanel>
                                                <StackPanel Orientation="Horizontal" Margin="45 40 0 0">
                                                    <TextBlock Text="*" Style="{StaticResource MaterialDesignHeadline5TextBlock}" Margin="0 -5.5 0 0" Foreground="{StaticResource ValidationErrorBrush}"/>
                                                    <TextBlock Text="Mandatory Fields" Style="{StaticResource MaterialDesignCaptionTextBlock}" Margin="5 0 0 0" Foreground="{StaticResource ValidationErrorBrush}"/>
                                                </StackPanel>
                                            </StackPanel>
                                        </materialDesign:Card>

                                    </GroupBox>
                                    <controlsLib:StepButtonBar x:Name="btnStepButtonBar" HorizontalAlignment="Right" Continue="Next" Cancel="Cancel" Height="60" Margin="0,22,-0.4,10">
                                    </controlsLib:StepButtonBar>
                                </StackPanel>
                            </model:Step.Content>
                        </model:Step>

**Comment by Shreyasj96** [comment]
Hi, i have pasted the xaml code for first step, for second and third step, the styles are fine for the next and finish buttons. only for first step, im having this issue.

**Comment by bombipappoo** [comment]
Probably the Stepper control is part of [Material Design Extensions](https://github.com/spiegelp/MaterialDesignExtensions). Not a part of Material Design In XAML Toolkit.

**Comment by Shreyasj96** [comment]
@bombipappoo  yes you are right. But still other styles seems to be working just fine though and almost all of the styles available in Material Design are available in Material design extensions as well.

**Comment by bombipappoo** [comment]
Can you provide a project (not only XAML) that reproduces this problem?

**Comment by Shreyasj96** [comment]
@bombipappoo As this is a company project, it might not be possible to share the source code. If you want any other details that are required(relating to this stepper), i would like to know.
Even i tried styling the Next Button by overriding, but i wanted the original style itself.

**Comment by bombipappoo** [comment]
It seems that the order and style of the buttons depends on whether `Mode` property of `StepButtonBar` is `Horizontal` or `Vertical`.
See [StepperTemplates.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensions/Themes/StepperTemplates.xaml#L845).

**Comment by Shreyasj96** [comment]
@bombipappoo  Thank you for the quick response. From the link which you have shared, i can see that both are using MaterialDesignFlatButton as their stepbuttonbar button styles. This explains image 2 but not image 1. That's where im confused.

**Comment by bombipappoo** [comment]
It's a DataTrigger:
If Mode is Horizontal, Cancel(Flat) - Continue(Flat).
If Mode is Vertical, Continue(Raised) - Cancel(Flat).

I think that it will be solved if you specify `Mode="Horizontal"` to `StepButtonBar` explicitly.
Maybe this is a binding timing issue.

In any case, This is not a Material Design In XAML Toolkit issue.

**Comment by Shreyasj96** [comment]
@bombipappoo Great analysis by your end. Yes, setting the mode to vertical fixed the style.
I guess you can't help it. "People in general are awesome". Thanks for your time and quick response.
