### ISSUE TITLE
TextBox VerticalAlignment Bug

### ISSUE THREAD

**Issue by meromy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1979]
![01](https://user-images.githubusercontent.com/42421153/87238565-a2649400-c436-11ea-983d-4f9a7f724d0a.png)
![02](https://user-images.githubusercontent.com/42421153/87238569-a4c6ee00-c436-11ea-9401-0494ec62adab.png)
![03](https://user-images.githubusercontent.com/42421153/87238570-a5f81b00-c436-11ea-91f8-1745bb1d7757.png)

**Comment by bombipappoo** [comment]
If you increase the number of lines, it expands, but if you decrease the number of lines, it does not shrink. Is this what you mean?
If so, It seems #1900 have done so.

**Comment by lszczygielek** [comment]
I checked demo application with latest changes and control behavior from screenshots has been changed in comparison to previous version. It looks like regression.
