### ISSUE TITLE
Add MaterialDesignOutlinedTextFieldComboBox

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1980]
You can see a good, interactive, example in Google Contacts app.

![image](https://user-images.githubusercontent.com/16761301/87335543-7e748180-c50e-11ea-8437-60665f7e24b0.png)

And please make the default alignment, height, margins same as MaterialDesignOutlinedTextFieldTextBox so if you place them next to each other horizontally, outlines align.
Thank you!

**Comment by CorradoBarbero** [comment]
This is a duplicated of "Outline Combobox?" #1613

**Comment by bebenins** [comment]
> This is a duplicated of "Outline Combobox?" #1613

Yes I'm sorry I didn't see it.
Will close this one

**Comment by bebenins** [comment]
Dup of #1613
