### ISSUE TITLE
Leading icon for TextBox

### ISSUE THREAD

**Issue by lszczygielek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1984]
I would like to propose an enhancement.
It would be great to be able to set leading icon for TextBox like in Material Design guide:
https://material.io/components/text-fields

**Comment by MichelMichels** [comment]
I'm trying to implement this, but the spec is not really clear on certain points.
* Icon color
* Margins
* Size

I have something working but the positioning is off. Any thoughts?

![image](https://user-images.githubusercontent.com/6505319/105574266-a8cbb500-5d63-11eb-8042-615d0002b3e2.png)

![image](https://user-images.githubusercontent.com/6505319/105574271-b3864a00-5d63-11eb-8932-b44a79f2f6c8.png)

**Comment by Keboo** [comment]
Closed by #2221
