### ISSUE TITLE
paket.exe" restore" exited with code 1.

### ISSUE THREAD

**Issue by safvanak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1993]
Showing error while rebuild the solution , I am using visual studio 2019 version
![image](https://user-images.githubusercontent.com/24952773/88462927-b98e9180-cecc-11ea-91e9-a753df65cacd.png)

**Comment by bombipappoo** [comment]
Probably the same issue as #1761.

**Comment by Keboo** [comment]
More information on common causes in the [wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#project-fails-to-build-with-error-the-command-materialdesigninxamltoolkitpaketpaketexe-restore---references-file-materialdesigninxamltoolkitmaindemowpfpaketreferences-exited-with-code-1) as well

**Comment by Keboo** [comment]
Paket has now been removed please see the latest requirements for compiling from source: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source
