### ISSUE TITLE
Changing the ValidationError Color has no effect?

### ISSUE THREAD

**Issue by Gaheron** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#1997]
I changed the ValidationError Color like this.

```
            ITheme theme = paletteHelper.GetTheme();
            theme.ValidationError = (Color)ColorConverter.ConvertFromString("#01b02b");
            palletteHelper.SetTheme(theme);
```
Even though the ValidationError property is set, the displayed color is still the default red.

**Comment by bombipappoo** [comment]
It works as expected. Can you provide a project that reproduces it?

**Comment by Gaheron** [comment]
[ColorSwapTest.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/4999234/ColorSwapTest.zip)

It works as expected on the MainWindow and the UserControl in the MainWindow. Sorry about that, it did not occur to me that only parts of it could not work.

If you click the Button a Dialog will open. Thats where the color is still red
![image](https://user-images.githubusercontent.com/16191208/88888896-73745d80-d23f-11ea-9dcf-e228f7df35ea.png)

**Comment by bombipappoo** [comment]
I think maybe it can't.

Well, it's not completely impossible as below, but there may be a better way...
```csharp
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            await DialogHost.Show(new AlertDialogViewModel(), "ShellDialogHost", DialogOpenedHandler);
        }

        private static void DialogOpenedHandler(object sender, DialogOpenedEventArgs e)
        {
            var popup = typeof(DialogHost).GetField("_popup", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sender) as Popup;
            popup.Resources.SetTheme(Application.Current.Resources.GetTheme());
        }
```

**Comment by Gaheron** [comment]
Thank you!

It also works with the loaded event of the DialogHost 👍
