### ISSUE TITLE
The tag PackIcon does not exist in XML namespace "http://materialdesigninxaml.net/winfx/xaml/themes"

### ISSUE THREAD

**Issue by abrasat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2000]
After updating the MaterialDesignThemes to the latest version, my WPF application cannot be compiled anymore, as the PackIcon is not found anymore in the library.
Is there any workaround available for this?

**Comment by bombipappoo** [comment]
What version are you using? It can be compiled in my environment (latest master, v3.2.0-ci1798, v3.1.3).
Can you provide a project that reproduces the issue?

**Comment by Keboo** [comment]
Be aware that the PackIcon values are generated from https://materialdesignicons.com/. This library merely pulls in the latest changes so there may be breaking changes from these icons. You can see in the [release notes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/PackIcon-ReleaseNotes) the complete list of breaking changes, as well as icons that have had visual changes done.

**Comment by henrihein** [comment]
I had the same problem, even after updating my versions of the Material Design packages in NuGet. This was per 11/10/2020. I solved it by following these steps:
1. Close solution.
2. Manually remove the Material Design packages from packages.config.
3. Open solution.
3. Add Material Design packages with NuGet.
4. Rebuild solution.
Posting here in case this helps others out.

**Comment by Keboo** [comment]
Closing for now as this does not appear to be an issue with the library
