### ISSUE TITLE
Showing a Progress Bar while simultaneously querying data blocks the UI

### ISSUE THREAD

**Issue by HamzaIssam** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2001]
Im trying to show an indeterminate loading progress bar while simultaneously querying a database, after the user clicks the button the UI is blocked and only after the query returns then the Progress bar is shown but then its too late..

Im using this code            :

`  <ProgressBar Grid.Row="1"  Grid.ColumnSpan="2"
                         Height="150"
                         Width="150"
                         Style="{StaticResource MaterialDesignCircularProgressBar}"
                         Value="0"
                         Visibility="{Binding IsProcessing ,Converter={StaticResource BooleanToVisibilityConverter}}"
                         IsIndeterminate="True" />`

IsProcessing is a property that triggers the Notifypropertychanged event.. Im really stuck on this issue, I tried to run the query asynchronously but that didnt help much. 
Thank you in advance for any help

**Comment by Keboo** [comment]
@HamzaIssam it sounds like the database query is running on the UI thread and blocking the entire app. I would suggest moving the query inside of a `Task.Run` to perform the work on a background thread. You can see an example [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/ProgressBar/ProgressBar.BackgroundProcessing)
