### ISSUE TITLE
Add indeterminate Progress Ring

### ISSUE THREAD

**Issue by mytahir** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2006]
![Progress](https://user-images.githubusercontent.com/28863431/89098334-75c0ee00-d3de-11ea-8739-8cd0914253de.png)
Is it possible if we can have this Future like in ModerWpf Library?
I mean an Indeterminate Progress Ring.

**Comment by bombipappoo** [comment]
Use `ProgressBar` with `MaterialDesignCircularProgressBar` style. See demo app for detail.

**Comment by mytahir** [comment]
> Use `ProgressBar` with `MaterialDesignCircularProgressBar` style. See demo app for detail.

Ok, Thank You

**Comment by jespersh** [comment]
Sorry to say that is outside the Material Design spec

**Comment by mytahir** [comment]
Ok
