### ISSUE TITLE
Multiple pages in Transitioner show the textBox dashed line.

### ISSUE THREAD

**Issue by HenJigg** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2013]
Place multiple containers in Transitioner, add TextBox to the back container, but the textBox dash line in the back container appears in the first container.

![image](https://user-images.githubusercontent.com/42528522/89703697-a2957800-d97f-11ea-84e6-ae51a630ea71.png)

**Comment by Keboo** [comment]
This should already be addressed with the latest 3.2.0 preview NuGet packages.
