### ISSUE TITLE
Outlined TextBox has margin around text that is hard coded and too large

### ISSUE THREAD

**Issue by Kelb-Tansley** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2024]
I would like to be able to half the margin around the text. Or have a way of setting the margin.

**Comment by JustAnothaMike** [comment]
Try using the height and padding attributes to make the box smaller and have the text still show in it. There's a fix for the hint not following the offset you tell it to if you need to use hints on them as well.

**Comment by Keboo** [comment]
You can also set Padding to be a negative value as well. This will cause the text to shift closer to the outline as well. 

Be aware if you are also using a floating hint, you may need to use the `HintAssist.FloatingOffset` property to adjust the position of the floating hint to keep it positioned on the outline correctly.

**Comment by Bakaji** [comment]
same problem here, when I use Filled text box I can set margin as I want but when I use filled style something goes over the text
