### ISSUE TITLE
dragablz TabablzControl and controls "trails"

### ISSUE THREAD

**Issue by vicmic** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2032]
When i use dragablz TabablzControl and add some controls on some tab, when change tab at runtime, there are some "trails" of last previous tab on current tab.

A have attached full simple example that reproduce the issue, and also some images of the results.

![FirstTab](https://user-images.githubusercontent.com/4671775/90827984-7f82a500-e33d-11ea-9a9a-5ce9d0683f11.JPG)

![SecondTab](https://user-images.githubusercontent.com/4671775/90827978-7d204b00-e33d-11ea-88a6-3a2b848e847e.JPG)

[WpfApp2.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5105598/WpfApp2.zip)

**Comment by Keboo** [comment]
This should be addressed in the latest 3.2.0 preview NuGet packages
