### ISSUE TITLE
Default Context Menu of ComboBox is Hard to be Shown

### ISSUE THREAD

**Issue by cbfrank** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2035]
Hi
I find if the combobox is empty then it is hard to show the context menu by right click.
Repo https://github.com/cbfrank/ComboboxContextMenuBug

![image](https://user-images.githubusercontent.com/2193548/91057139-6b021d80-e659-11ea-8a5a-59d5d3b7cc87.png)

as shown by the demo pic, the context menu can be shown only when you right click inside the red region, there is no content menu when you click inside the yellow region.
Thanks

**Comment by Keboo** [comment]
Thank you for the bug report. 
Attaching a copy of the above repo for historical archiving.
[ComboboxContextMenuBug-master.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5118632/ComboboxContextMenuBug-master.zip)

**Comment by Lokixa** [comment]
Just cloned the repo, updated to 3.2.0 and the bug is gone.

**Comment by Keboo** [comment]
Also tested and confirmed. Updating to 3.2.0 resolves the issue
