### ISSUE TITLE
DialogHost control embedded in a drawer control shows weird behaviour

### ISSUE THREAD

**Issue by ben1976de** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2038]
1) When having a DialogHost embedded in a Drawer control a strange behaviour can be seen when both are opened. Please see attached image which was captured using the latest WPF demo project:

![grafik](https://user-images.githubusercontent.com/70279048/91322302-debe3a80-e7bf-11ea-8c11-233adbf339eb.png)

2) Next issue: when removing an user control which is holding an opened DialogHost from the visible tree the DialogContent is gone after putting the user control back on the drawing stack.
 Step 1) Go to the Dialogs menu and open any DialogHost control you prefer. Leave it open.

![grafik](https://user-images.githubusercontent.com/70279048/91409365-9a757d80-e845-11ea-8376-a1cf8bf8672a.png)

Step 2) Switch to a different menu via the Drawer.
Step 3) Get back to the Dialogs menu.

![grafik](https://user-images.githubusercontent.com/70279048/91409409-a8c39980-e845-11ea-82f9-5a21f6985e5f.png)

3) In a project I have the IsOpen state of the DialogHost is getting lost (it closes itself) when removing a UserControl (containing the DialogHost) from the drawing stack even if its state is set statically to True in XAML.

**Comment by visualczm** [comment]
@ben1976de 
soo do i ,  solved it?

**Comment by visualczm** [comment]
@ben1976de 
```cs 
 opLogin1.IsOpen = false; //fisrt set false
 opLogin1.IsOpen = true; 

when can be show~

**Comment by punker76** [comment]
@ben1976de @visualczm The reason for the first screenshot is, that the DialogHost uses a Popup to show the dialog. Popups are always on top of the window.

**Comment by visualczm** [comment]
@punker76  thank you for the answer

@ben1976de question  ie.
run demo app
setup1:
select dialogs page , click sample4 run like ie.
![image](https://user-images.githubusercontent.com/22953065/99358310-4b8d3080-28e8-11eb-8e83-29ac6b15a645.png)

setup2:
select others page , then go back , dialogs content lost, but dialogs exist ie.
![image](https://user-images.githubusercontent.com/22953065/99358971-4977a180-28e9-11eb-81b2-a2efa253d0a5.png)
 

my Temporary solution

```cs
 opLogin1.IsOpen = false; //first set false
 opLogin1.IsOpen = true; 
```

**Comment by Erapchu** [comment]
I think that when you switch between menus, dialog host (popup window) is totally vanishes and should be recreated.
May be just close all dialogs before switching to other menu?
