### ISSUE TITLE
Replace references to obsolete SecondaryAccent keys?

### ISSUE THREAD

**Issue by bender2k14** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2039]
Above the calls to `SetSolidColorBrush` that pass in `SecondaryAccentBrush` and `SecondaryAccentForegroundBrush` is a comment that says they will eventually be removed.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/5f972ca97b7adf4c83ca3a7f6703070e9a75d5e8/MaterialDesignThemes.Wpf/ResourceDictionaryExtensions.cs#L34-L36

Would it be helpful if I created a PR that replaces
- `SecondaryAccentBrush` with `SecondaryHueMidBrush`,
- `SecondaryAccentBrushColor` with `SecondaryHueMidBrushColor`,
- `SecondaryAccentForegroundBrush` with `SecondaryHueMidForegroundBrush`. and
- `SecondaryAccentForegroundBrushColor` with `SecondaryHueMidForegroundBrushColor`?

(So essentially replace `SecondaryAccent` with `SecondaryHueMid` in these four keys.)

**Comment by Keboo** [comment]
@bender2k14 yes I would be happy to accept a PR with those changes.
