### ISSUE TITLE
MaterialDesignInXamlToolkit` open "XamlDisplayEx" does not exist 

### ISSUE THREAD

**Issue by yaoganxingwei** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2045]
I downloaded MaterialDesignInXamlToolkit-master\MaterialDesignToolkit.Full.sln from github. After decompressing it on my computer and opening this file with the latest version of VS2019, there will be such an error, many similar errors. How can i solve it, thank you

The name "XamlDisplayEx" does not exist in the XDG0008 namespace "clr-namespace:MaterialDesignDemo". MaterialDesignDemo App.xaml 2
The name "XamlDisplayEx" does not exist in the XDG0008 namespace "clr-namespace:MaterialDesignDemo". MaterialDesignDemo App.xaml 2
The name "BundledTheme" does not exist in the XDG0008 namespace "http://materialdesigninxaml.net/winfx/xaml/themes". MaterialDesignDemo App.xaml 2
The name "XamlDisplayEx" does not exist in the XDG0008 namespace "clr-namespace:MaterialDesignDemo". MaterialDesignDemo App.xaml 2
The name "FontToLineHeightConverter" does not exist in the XDG0008 namespace "clr-namespace:MaterialDesignThemes.Wpf.Converters". MaterialDesignThemes.Wpf MaterialDesignTheme.TextBox.xaml

**Comment by LeiYangGH** [comment]
i met similiar issue(i can run the demo but opening xamls gave me errors and cannot preview the design). have you solved it? i cannot imagine such popular repo has such issue.

**Comment by Keboo** [comment]
Please see the documentation for [compiling from source](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source). From the description it sounds like it may be having trouble resolving dependencies.

It is also worth mentioning `XDG0008` is a designer error, not a compilation error.
