### ISSUE TITLE
Question : MaterialDesignChoiceChipAccentOutlineListBox FontSize 

### ISSUE THREAD

**Issue by hardiksarin** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2046]
Hey There I just Just Started out with using this package, can anyone help me identify how can i adjust the font size and make my chips larger?
![Capture](https://user-images.githubusercontent.com/45598950/91641591-1688e480-ea43-11ea-8aaa-d52934217f34.JPG)

  <StackPanel
                Grid.Row="1"
                Grid.Column="0"
                Grid.ColumnSpan="3"
                Margin="10">
                <Label
                    Height="80"
                    HorizontalAlignment="Left"
                    VerticalAlignment="Top"
                    Content="Q1. What is the Status Of Residence? "
                    FontSize="30"
                    FontWeight="UltraLight"
                    Foreground="Gray" />

                <ListBox
                    x:Name="RadioButtonGroupChoiceChipAccentOutline"
                    FontSize="50"
                    Style="{DynamicResource MaterialDesignChoiceChipAccentOutlineListBox}">
                    <ListBoxItem>
                        Owned
                    </ListBoxItem>
                    <ListBoxItem IsSelected="True">
                        Rented
                    </ListBoxItem>
                    <ListBoxItem>
                        Relative
                    </ListBoxItem>
                    <ListBoxItem IsEnabled="True">
                        Other
                    </ListBoxItem>
                </ListBox>
            </StackPanel>

**Comment by Keboo** [comment]
Looks like this is a bug, the font properties are being passed. This should be fixed in tonight's release.
