### ISSUE TITLE
i want to use treeview binding IsSelected and IsExpanded,but the style will not work

### ISSUE THREAD

**Issue by pengqi1991** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2049]
> [in the xaml ](url)

`<TreeView x:Name="treeView"  ItemsSource="{Binding EventModels}"  >
         <TreeView.ItemContainerStyle>
              <Style TargetType="{x:Type TreeViewItem}" >
                   <Setter Property="IsSelected" Value="{Binding IsSelected}"/>
                   <Setter Property="IsExpanded" Value="{Binding IsExpanded}"/>
          </Style>
           </TreeView.ItemContainerStyle>
           <TreeView.ItemTemplate>
                  <HierarchicalDataTemplate ItemsSource="{Binding Children}" DataType="{x:Type domain2:EventModel}">
                        <StackPanel Orientation="Horizontal">
                            <TextBlock VerticalAlignment="Center" FontSize="12" Text="{Binding Name}" Margin="2,0,0,0"> 
                                </TextBlock>
                            </StackPanel>
                        </HierarchicalDataTemplate>
                   </TreeView.ItemTemplate>
           <i:Interaction.Triggers>
              <i:EventTrigger EventName="SelectedItemChanged">
                     <i:InvokeCommandAction Command="{Binding SelectItemChangeCommand}"
                           CommandParameter="{Binding ElementName=treeView,Path=SelectedItem}"/>
               </i:EventTrigger>
            </i:Interaction.Triggers>
 </TreeView>`

**Comment by Keboo** [comment]
It looks like you are setting a style directly on the TreeViewItem and [overriding the default style](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#when-custom-style-is-applied-the-material-design-theme-is-lost).
I suspect you simply need to add a BasedOn to the TreeViewItem style.
```xaml
<Style TargetType="{x:Type TreeViewItem}" BasedOn="{StaticResource MaterialDesignTreeViewItem}">
```
