### ISSUE TITLE
some ideas.

### ISSUE THREAD

**Issue by HenJigg** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2063]
This is a great project, and I'm trying to make it into a video collection to share with WPF developers in China, for example: How do I use it? Design?
Because there is little content in this area, you are convenient in WPF and XAML which I think is very professional, if you have some special learning routes or materials, suggestions, etc.
I'd like to talk to you about my idea and be happy to promote it in China, but I don't seem to find your email address.

This is my email address : zhouhaogg789@outlook.com

Note: There are also your Youtube videos, which you hope will be translated and disseminated in China.

**Comment by Keboo** [comment]
Hi @HenJigg 

I do have some sample projects as well as a few blog posts that are linked on [this repository](https://github.com/Keboo/MaterialDesignInXaml.Examples). 
Currently my youtube videos are only in English. All of my videos should be marked with the [Creative Commons on YouTube](https://support.google.com/youtube/answer/2797468) which allows everyone to reuse and edit.

**Comment by Keboo** [comment]
Close for now, let me know if there is any more follow up
