### ISSUE TITLE
Set Clock minute resolution

### ISSUE THREAD

**Issue by exo-tw** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2065]
It would be nice if the minute resolution of the Clock control could be selected. So that it would e.g. snap to multiples of 5 minutes. Or 10, 15 or 30 minutes, or maybe even allow only full hours.
I rarely need the full 60 minute resolution, I practically never need to set 9:23, so it would be helpful if I had an easy way to snap the minutes to the selected increment (so 9:20 or 9:25 in my example).

**Comment by computamike** [comment]
so this is for the time picker?

**Comment by jespersh** [comment]
You'd be interested in #1035

**Comment by Keboo** [comment]
I believe this request is already covered by #1035. If there are additional requirements that should be considered please add them there.
