### ISSUE TITLE
Flipper without shadow border

### ISSUE THREAD

**Issue by Prophetebe** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2068]
Hi,

Is it a way to remove the border (or just the shadow) on a flipper?  

I put a button on each side of the flipper and I don't want to have border.

thank you.

**Comment by Keboo** [comment]
This appears to be a limitation with the [MaterialDesignCardFlipper](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Flipper.xaml)
The simplest solution would be to use the default style for the flipper (omit the `Style="{StaticResource MaterialDesignCardFlipper}"` if you have it), and set the BorderThickness property to 0.

However it does appear that being able to customize the shadow depth on the flipper is something that should be supported. If anyone wants to submit a pull request for it, it should simply be a template binding on the Card inside of the `MaterialDesignCardFlipper` style (linked above). This should allow someone to customize the depth of the shadow doing something like:
```xaml
<materialDesign:Flipper Style="{StaticResource MaterialDesignCardFlipper}" VerticalAlignment="Top"
                        materialDesign:ShadowAssist.ShadowDepth="Depth0">
...
</materialDesign:Flipper>
```

**Comment by Prophetebe** [comment]
Hi, without the style MaterialDesignCardFlipper, every content element are displayed strangly (font size are bigger for example).

**Comment by MalshaRajapaksha** [comment]
> Hi,
> 
> Is it a way to remove the border (or just the shadow) on a flipper?
> 
> I put a button on each side of the flipper and I don't want to have border.
> 
> thank you

border: none will remove the border all together.
