### ISSUE TITLE
DataGrid three state sorting option / reset sorting

### ISSUE THREAD

**Issue by valimaties** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2069]
Please consider to make a three state sort option in grid sorting. 
First click on header will sort ascending, second click will sort data descending, and the third will reset the sorting, and the `SortDirectionIndicator` will be invisible in this last case.

Regards,
Vali

**Comment by Keboo** [comment]
Thank you for the suggestion. However at this time that is the default behavior of the WPF data grid. As this library is designed to bring material design, there is not currently plans to extend the existing DataGrid behavior.
