### ISSUE TITLE
Rating Bar support fractional values

### ISSUE THREAD

**Issue by devriesb13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2073]
Hi there,

Can the rating bar handle displaying an average rating value (doubles) but let a user vote (integers) similar to how the SharePoint list items work?

Cheers Ben

**Comment by jespersh** [comment]
You mean like this?
![image](https://user-images.githubusercontent.com/1004198/94658390-06467c80-0303-11eb-88a5-a14637f9aba2.png)

**Comment by devriesb13** [comment]
Yes exactly, see my gif attachment for SharePoint version. Ignore the number 2, this is just a number of how many users have voted.

My thoughts around this would be. By default you see the average rating bound to some (double) value. When you hover over the rating bar, it turns on  eg "rating mode", then you can select a rating (integer) you want to give.

![2020-10-01_8-47-16](https://user-images.githubusercontent.com/10214916/94747760-0f971e00-03c3-11eb-990d-fcaa0dd81f50.gif)

**Comment by jespersh** [comment]
To answer your question then, that's a no sadly:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/1873f0d58929ededc8724bac3a68fa260dfd498a/MaterialDesignThemes.Wpf/RatingBar.cs#L65-L69

But I don't see why someone couldn't modify this to support halves

**Comment by Keboo** [comment]
Currently there is not support for fractional amounts. If someone would like to try and tackle this, I would be happy to accept a PR for it.

**Comment by Christiankoo** [comment]
Can i take this issue, please?

**Comment by Keboo** [comment]
@Christiankoo go for it. Let me know if you have any questions

**Comment by stojy** [comment]
hi @Christiankoo did you make any progress on fractional values?

**Comment by stojy** [comment]
After taking a quick look through the RatingBar code, perhaps a better solution might be a solution on the Slider control instead?  
The basic functionality I believe is already there with the left/right slider and discrete steps functionality.  You'd lose the funky animation of course, but I suspect this isn't essential.
