### ISSUE TITLE
Rename filled PasswordBox style

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2074]
The style `MaterialDesignFilledPasswordFieldPasswordBox` should be renamed to be `MaterialDesignFilledPasswordBox`

The style can be found [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml)

Update all usages in the demo app to use the new style name as well.

**Comment by DevanshCodes** [comment]
can I work on this?

**Comment by Keboo** [comment]
@DevanshCodes yes go for it

**Comment by DevanshCodes** [comment]
Hey @Keboo can you take a look at the PR?
