### ISSUE TITLE
Rename outlined Password box style

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2075]
The style `MaterialDesignOutlinedPasswordFieldPasswordBox` should be renamed to `MaterialDesignOutlinedPasswordBox`

The style can be found [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PasswordBox.xaml)

Update all usages in the demo app to use the new style name as well.

**Comment by Ahmeed2m** [comment]
Can I work on this
