### ISSUE TITLE
Renamed filled TextBox style

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2076]
The style `MaterialDesignFilledTextFieldTextBox` should be renamed to `MaterialDesignFilledTextBox`

The style can be found [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml)

Update all usages in the demo app to use the new style name as well.

**Comment by abuZayed15** [comment]
Can I give this issue a try? It's my first time contributing to an open source project

**Comment by Keboo** [comment]
@abuZayed15 yes go for it. If you have questions feel free to post them here, or on the [gitter chat](https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit)

**Comment by abuZayed15** [comment]
Great. I will take it. Is there documentation that would help me get the  MaterialDesignInXAMLToolkit up running in an IDE, like Visual Studio? Thank you for letting me have this issue
