### ISSUE TITLE
Renamed outlined TextBox style

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2078]
The style `MaterialDesignOutlinedTextFieldTextBox` should be renamed to `MaterialDesignOutlinedTextBox`

The style can be found [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml)

Update all usages in the demo app to use the new style name as well.

**Comment by DevanshCodes** [comment]
Can I take this?
