### ISSUE TITLE
Remove obsolete members

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2079]
There are several methods/class that have been flagged as obsolete is prior version. With the 4.0.0 release it is time to remove them. The following items should be removed:

- [ ] [DialogClosingEventArgs constructor](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/DialogClosingEventArgs.cs)
- [ ] [LargeArcConverter](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Converters/CircularProgressBar/LargeArcConverter.cs)
- [ ] [Expander Assist members](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/ExpanderAssist.cs#L34-L108)
- [ ] [Expander Styles](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Expander.xaml#L159-L173)
- [ ] [Icon](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Icon.cs)
- [ ] [IconType](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/IconType.cs)

**Comment by aniket786333** [comment]
That's good
