### ISSUE TITLE
Remove old theme resources

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2080]
With the 3.x releases the theming was redone and the brush names were adjusted. With the 4.0.0 release we will be removing these old theme resources. 

We should locate any remaining instances of these theme resources, update them, and remove the old `SecondaryAccent*` resource.

Update the following:
- [ ] `SecondaryAccentBrush` becomes `SecondaryHueMidBrush`
- [ ] `SecondaryAccentBrushColor` becomes `SecondaryHueMidBrushColor`
- [ ] `SecondaryAccentForegroundBrush` becomes `SecondaryHueMidForegroundBrush`
- [ ] `SecondaryHueMidForegroundBrushColor` becomes `SecondaryHueMidForegroundBrushColor`

Then remove all of the  `SecondaryAccent*` resources.

**Comment by abuZayed15** [comment]
Can I also take this one?
