### ISSUE TITLE
Rename validation theme resources

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2082]
Most of the theme resources are prefixed with "MaterialDesign" exception for `ValidationErrorBrush` and `ValidationErrorColor`. We should add this prefix to all usages of both the brush and the color.

[Usages of ValidationErrorBrush](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/search?q=ValidationErrorBrush)
[Usages of ValidationErrorColor](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/search?q=ValidationErrorColor)

**Comment by trevorcarter83** [comment]
@Keboo I can take this if you like.

**Comment by Keboo** [comment]
@trevorcarter83 thanks but it looks like there is already a PR for it
