### ISSUE TITLE
Rename ColorHelper to ColorAssist

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2083]
By default all of the extension method classes in this library end with the "Assist" suffix. We should update [ColorHelper](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignColors.Wpf/ColorManipulation/ColorHelper.cs) to be named `ColorAssist`.

**Comment by 4Rebin** [comment]
Hey Keboo,
I like to work with this issue.
