### ISSUE TITLE
Please add the "hacktoberfest" topic.

### ISSUE THREAD

**Issue by teo-tsirpanis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2103]
I want to make a contribution to this repository but I also want it to count against my contributions for [2020's Hacktoberfest](https://hacktoberfest.digitalocean.com/). But for this to happen, [the repository must have the `hacktoberfest` topic](https://github.com/digitalocean/hacktoberfest/pull/596).

**Comment by Keboo** [comment]
I have sent a message to the admins to request this change.
