### ISSUE TITLE
ColorZone not drawing shadows

### ISSUE THREAD

**Issue by Nextra** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2111]
ColorZone elements are currently not drawing shadows correctly. The Demo app shows this in at least two places:

- Main/top header bar
- "Shadow Header" example on the GroupBox page

I traced the issue back to #2058 where ClipToBounds was defaulted to "True" for the primary ColorZone style. Reverting this change in Generic.xaml gets shadows working again.

**Comment by Keboo** [comment]
That change inadvertently changes the root level ClipToBounds in addition to the one on the nested Border. You can work around this by simply settings `ClipToBounds="False"` on your ColorZone. I have updated the 4.0.0 to change the default so shadows will show by default.

**Comment by Nextra** [comment]
I was aware of that, but not sure how to properly combine the new demo bit from #2058 with shadows. Seems like that could only be done with some kind of attached helper?
