### ISSUE TITLE
Update ShowMeTheXAML to version 2.0.0

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2119]
ShowMeTheXAML just released a new 2.0.0 with some breaking changes.
The key differences is the `Key` properties on the XamlDisplay class was renamed to `UniqueKey`. We should update the version we are using to 2.0.0 and update all of the usages to using the new property. 

These dependencies are managed with [Paket](https://fsprojects.github.io/Paket/learn-how-to-use-paket.html) not NuGet directly so you will need to use paket to update and restore the dependency. Keep in mind there is a separate issue for updating paket (#2118) so the exact command needed will depend on if that work has been done.

**Comment by jespersh** [comment]
@Keboo what should one expect from this Uno.UI dependency defined in the nuspec file of SMTX?
```xaml
      <group targetFramework=".NETStandard2.0">
        <dependency id="Uno.UI" version="3.0.17" exclude="Build,Analyzers" />
      </group>
```

**Comment by Keboo** [comment]
The netstandard dependency should not be picked up by WPF since the .NET Framework and NET Core App dependencies should be a better match. I would not expect that to affect this project.
