### ISSUE TITLE
Cannot dynamically change the background color of the TreeViewItem during drag drop TreeViewItem

### ISSUE THREAD

**Issue by 42805578** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2135]
When drag drop a TreeViewItem over another TreeViewItem, I  want to change the background color of the target TreeViewItem, in my c# code, I set the background as below:
targetTreeViewItem.Background=Colors.Green;
but the background not change

Any advice?

**Comment by stigrune** [comment]
The background is set to transparent with no possible overrides in the default templates. 

This is a custom case and you can solve it by implementing your own custom TreeViewItem template that is used in your application. Base it of [MaterialDesignTreeViewItem in MaterialDesignTheme.TreeView.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d75bac11b6d25ad34c78e416b26727344da8c487/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TreeView.xaml#L279) and modify to your linking. It’s not 100% clear on what your need is, but I’m guessing you’re interested in changing the background color on the header at line 279. 

Another possible solution for you would be use WPF adorners to achieve a similar effect on dragover.

**Comment by Keboo** [comment]
This looks like a simple thing that could be fixed. Simply replacing the hard coded value (as indicated by @stigrune) with a TemplateBinding should fix it (ideally adding a corresponding UI test).
