### ISSUE TITLE
DialogHost not working at all

### ISSUE THREAD

**Issue by tomasfil** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2138]
Hello,

I have issue that the DialogHost is not showing anything at all.
Even if I set ``IsOpen="true"``, then nothing show up as well.

.net Core 3.1

Tested versions: 4.0.0-ci2156, 3.2.0

``
<Window x:Class="MEAC_Backup_UI.MainWindow"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:local="clr-namespace:MEAC_Backup_UI"
xmlns:views="clr-namespace:MEAC_Backup_UI.Views"
xmlns:viewModels="clr-namespace:MEAC_Backup_UI.ViewModels"
Name="Window_Main"
mc:Ignorable="d"
xmlns:md="http://materialdesigninxaml.net/winfx/xaml/themes"
Title="MainWindow" Height="450" Width="800">
    <md:DialogHost IsOpen="True">
        <md:DialogHost.DialogContent>
            <Button Content="Hi"></Button>
        </md:DialogHost.DialogContent>
        <Button Content="Hi"></Button>
    </md:DialogHost>
</Window>
``
![image](https://user-images.githubusercontent.com/34779382/96578635-c8bb8a80-12d5-11eb-81cd-124ad9428cdd.png)

**Comment by HeedfulCrayon** [comment]
How did you solve this?  I am having the same issue where the context (the "Hi" button in your case) isn't showing either
