### ISSUE TITLE
Cannot Rebuild The Project 

### ISSUE THREAD

**Issue by oSethoum** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2144]
# ERRORS WHEN TRYING TO REBUILD THE PROJECT

![image](https://user-images.githubusercontent.com/46224889/96734240-3e952400-13b2-11eb-9fae-9954650f9049.png)

**Comment by TysonMN** [comment]
Can you share the output of the build?

**Comment by oSethoum** [comment]
@TysonMN  

The output file is so long here's a link 
[output.txt](https://github.com/oSethoum/build-output/blob/master/output.txt)

I noticed these issues too in the dependencies, but all the dll's files are available and i referenced them, but still getting the same issues. 
![image](https://user-images.githubusercontent.com/46224889/96790637-03fdac80-13ef-11eb-98eb-6c2302e3072e.png)

**Comment by TysonMN** [comment]
The [output says](https://github.com/oSethoum/build-output/blob/f66454d1342251c03da0bb5304e1ab281b2b33c4/output.txt#L1512-L1513)

> Run "dotnet tool restore" to make the "paket" command available.
> ... The command "dotnet paket restore" exited with code 1.

Try running `dotnet tool restore`.

**Comment by oSethoum** [comment]
@TysonMN  Thanks, it's solved now the build was successful. 
The file **.config/dotnet-tools.json** was locked i think it's because i downloaded it as zip file and i didn't clone the project with git.

now the build is successful, but i didn't find the demo executable file in the debug folder, i can't run it either from vs studio. 
![image](https://user-images.githubusercontent.com/46224889/96808171-39ff5880-1410-11eb-96e8-32458f9f1148.png)

![image](https://user-images.githubusercontent.com/46224889/96808240-6024f880-1410-11eb-858c-aebb858d811a.png)

**Comment by TysonMN** [comment]
You are trying to execute the project `MaterialDesignThemes.Wpf`.  In the "Solution Explorer", right-click the project `MaterialDesignDemo` and select "Set as Startup Project".  Then try to run.

**Comment by oSethoum** [comment]
@TysonMN  Thank You so muc sir, am new to WPF and C# in general, i didn't notice that, you just taught me something ❤

**Comment by TysonMN** [comment]
Glad to help :)

I just created PR #2145, which will help to prevent situations like that were someone tries to execute a project that is not executable.

If all your issues are resolved, then you can close this issue.

**Comment by oSethoum** [comment]
All issues resolved thanks !.

**Comment by maye1115** [comment]
But what causes this problem?

**Comment by TysonMN** [comment]
I think it is the integration of `paket` and Visual Studio.  `paket` is definitely a more capable NuGet package manager, but my opinion is that it is not that much better to be worth the effort because of issues like this.
