### ISSUE TITLE
Can't change the icon kind programmatically

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2148]
I don't now why but when I do ` MyIcon.Kind = "SquareOutline"` in an event, my app doesn't start. So I put it in a try catch. My app now starts but it doesn't show me any exception. And the icon doesn't change when I do my event.

This is my icon in xaml 
`<materialDesign:PackIcon x:Name="ItemMaxIcon" Kind="SquareOutline" Height="15" Width="15" Margin="10 1"/>`

And this is my Icon change in the code
`ItemMaxIcon.Kind = "DockWindow"`

**Comment by Keboo** [comment]
I think the issue is you appear to be trying to set the `Kind` property to a string in the code behind. However, that property is of type `PackIconKind` so in code you should do something like this:
```
ItemMaxIcon.Kind = PackIconKind.DockWindow;
```
