### ISSUE TITLE
Duration Override is not passed between all Enqueue methods for Snackbars

### ISSUE THREAD

**Issue by pingu2k4** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2149]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/e799b0cbcef70f5d9be2e502223244bdb2d58783/MaterialDesignThemes.Wpf/SnackbarMessageQueue.cs#L194

This line is missing passing in the duration override. Anything passed to this overload of Enqueue for the duration override will be ignored.

**Comment by artipo** [comment]
Hi, Can I try solving this issue?
