### ISSUE TITLE
Text foreground in datepicker in colorzone wrong

### ISSUE THREAD

**Issue by jotunskij** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2152]
This is the same issue as #315 (which is closed), but my issues presist.

I'm running 3.2.0 and when I place a datepicker in a colorzone I get the following error, shown in image:
![dtp-color-zone](https://user-images.githubusercontent.com/1684523/97607561-7256f600-1a11-11eb-92f9-114f0eefa53a.PNG)

White text on white background. When switching to a dark theme, it works correctly.

**Comment by artipo** [comment]
I tried to replicate your issue with a simple setup, without success.

```xaml
<Window
    [...]>
    <Grid>
        <materialDesign:ColorZone Mode="Light" VerticalAlignment="Stretch">
            <DatePicker
                Style="{StaticResource MaterialDesignFloatingHintDatePicker}"
                VerticalAlignment="Top"
                Width="100"
                materialDesign:HintAssist.Hint="Pick Date" />
        </materialDesign:ColorZone>
    </Grid>
</Window>
```

![2020-10-30_10h02_27](https://user-images.githubusercontent.com/13442010/97680902-b55bac80-1a97-11eb-9155-644a619dcc05.png)

Please, can you share more of your code?

**Comment by jotunskij** [comment]
So, this is the code:
```xaml
        <materialDesign:ColorZone Mode="PrimaryDark" VerticalAlignment="Stretch">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="600"></ColumnDefinition>
                    <ColumnDefinition Width="*"></ColumnDefinition>
                    <ColumnDefinition Width="100"></ColumnDefinition>
                </Grid.ColumnDefinitions>
                <StackPanel Orientation="Horizontal">
                    <DatePicker Name="dtpGoToDate" SelectedDateChanged="dtpGoToDate_SelectedDateChanged" Margin="10 0 0 3" Width="130" Style="{StaticResource MaterialDesignFloatingHintDatePicker}" materialDesign:HintAssist.Hint="Datum"></DatePicker>
                 </StackPanel>
          </Grid>
```

It's contained in a UserControl. The following is relevant code from my App.xaml:

Common style used for all my usercontrols
```xaml
            <Style x:Key="StandardStyleUC" TargetType="{x:Type UserControl}">
                <Setter Property="Background" Value="{DynamicResource MaterialDesignPaper}" />
                <Setter Property="TextElement.Foreground" Value="{DynamicResource MaterialDesignBody}" />
                <Setter Property="TextElement.FontWeight" Value="Medium" />
                <Setter Property="TextElement.FontSize" Value="14" />
                <Setter Property="FontFamily" Value="pack://application:,,,/MaterialDesignThemes.Wpf;component/Resources/Roboto/#Roboto" />
            </Style>
```

MaterialDesign initializaiton code. The commented colors are because the users of the system are able to customize their theme colors (and light/dark) during runtime.

```xaml
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <!--ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Deeppurple.xaml" /-->
                <!--ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Green.xaml" /-->
                <ResourceDictionary>
                    <SolidColorBrush x:Key="PrimaryHueLightBrush" Color="#FFD9E1EA"/> 
                    <SolidColorBrush x:Key="PrimaryHueLightForegroundBrush" Color="#222222"/>
                    <SolidColorBrush x:Key="PrimaryHueMidBrush" Color="#698eb8"/>
                    <SolidColorBrush x:Key="PrimaryHueMidForegroundBrush" Color="#222222"/> 
                    <SolidColorBrush x:Key="PrimaryHueDarkBrush" Color="#FF344E7A"/>
                    <SolidColorBrush x:Key="PrimaryHueDarkForegroundBrush" Color="#ffffff"/>
                    <!-- accent -->
                    <SolidColorBrush x:Key="SecondaryAccentBrush" Color="#FFABCD66"/>
                    <SolidColorBrush x:Key="SecondaryAccentForegroundBrush" Color="#222222"/>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
```

Thanks for looking into this!

**Comment by artipo** [comment]
Ok so, it tooks a bit of time but here I am.

The problem is caused by a `ColorZone` with opposite `Mode` in respect to the theme.

As you can see, `DatePicker` 's `Popup` don't inherit `Background` color from the `ColorZone` control,
But instead inherit `Foreground` color.

So you're having a light `Background` (coming from the theme) and a white `Foreground` coming from the `ColorZone`.

At the moment there is really no solution, apart from getting rid of the `ColorZone`.
It is not possible (from my understandings) to apply `ColorZone` theming to a `DataPicker`.
Forcing `Foreground` is not viable either since you would have black `Foreground` (to be able to see it in the `Calendar`) on dark `Mode` `ColorZone`.

**Comment by Keboo** [comment]
I think @artipo description is correct. There is not a great solution when using the ColorZone. The ColorZone is largely intended to be a simple way to place swaths of theme colors in the app. As an alternative you can simply use the `Border` control and apply the appropriate theme brushes to it.

**Comment by jotunskij** [comment]
Thanks for the feedback! I'll try finding a way around it.
