### ISSUE TITLE
Flat and Outline Buttons Background are strange on Mouse Over

### ISSUE THREAD

**Issue by HClausing** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2159]
Hi all,

I've updated MDIX package on my experimental app to version 4.0.0-ci2206 (tried with 4.0.0-ci2191). After the update, all of my Flat and Outlined Buttons (default, with no Primary or Accent backgrounds) get's a strange background on mouse over. I think that Opacity on converter not worked.

Please take a look on example below:

![FlatAndOutlinedButtons](https://user-images.githubusercontent.com/15158923/97974685-b85fe100-1da6-11eb-8f74-98d51d5923cf.gif)

It happened in the first and the last two of the image.

**Comment by Keboo** [comment]
I will have a fix coming in for this later today. The issue appears related to localization.

**Comment by HClausing** [comment]
Right. Thank you so much for the help.
