### ISSUE TITLE
Add Support For .NET 5.0

### ISSUE THREAD

**Issue by smkanadl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2167]
As .NET 5 has finally arrived, are there any plans to support net5.0 or net5.0-windows as TFM in the nuget packages?

**Comment by Keboo** [comment]
Yes. I am planning on adding support shortly. However, it is worth mentioning that you can still reference the existing NuGet packages from a net5 app without issue.

**Comment by HClausing** [comment]
By the moment, I'm working with the MDIX packages normally on my .net5 WPF app.

**Comment by MichelMichels** [comment]
I am also developing WPF .NET 5.0 apps with the current library. Everything runs smooth.

**Comment by Keboo** [comment]
net 5 support should be in and working with the latest 4.2.1 release
