### ISSUE TITLE
Artifacts when displaying DialogHost

### ISSUE THREAD

**Issue by omllmo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2169]
Artifacts when displaying DialogHost
`<materialDesign:DialogHost Grid.Row="1" Grid.Column="1">
    <materialDesign:DialogHost.DialogContent>
                        <Grid>
                            <Grid.RowDefinitions>
                                <RowDefinition />
                                <RowDefinition Height="Auto"/>
                            </Grid.RowDefinitions>
                            <Grid Name="gridPhones" Margin="15">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto"/>
                                    <RowDefinition/>
                                    <RowDefinition/>
                                    <RowDefinition/>
                                </Grid.RowDefinitions>
                                <materialDesign:PackIcon Kind="PhoneLog" Height="25" Width="25"/>
                                <TextBlock Text="Òåëåôîííûå íîìåðà"
                                           Margin="30 2 0 10" VerticalAlignment="Bottom"
                                           FontSize="15"/>
                                <Border HorizontalAlignment="Stretch" VerticalAlignment="Bottom"
                                        BorderBrush="{StaticResource WindowTitleColorBrush}" BorderThickness="1" Height="1"/>
                                <StackPanel Orientation="Horizontal" Grid.Row="1" Margin="0 10 0 10">
                                    <ComboBox Name="cbPhones"
                                              Margin="0 0 10 0"
                                              MinWidth="100" FontSize="14"
                                              materialDesign:HintAssist.Hint="&lt;íå âûáðàí&gt;"
                                              VirtualizingPanel.IsVirtualizing="True">
                                        <ComboBox.ItemTemplate>
                                            <DataTemplate>
                                                <TextBlock Text="{Binding Converter={StaticResource phoneConverter}}" FontSize="14"/>
                                            </DataTemplate>
                                        </ComboBox.ItemTemplate>
                                    </ComboBox>
                                    <Button Name="btnPhoneAdd" Content="{materialDesign:PackIcon Kind=PhonePlus,Size=25}"
                                            ToolTip="Äîáàâèòü íîìåð òåëåôîíà" 
                                            Height="50"
                                            Style="{StaticResource MaterialDesignFlatButton}"
                                            Click="BTNPhoneAdd_Click"/>
                                    <Button Name="btnPhoneDel" Content="{materialDesign:PackIcon Kind=PhoneMinus,Size=25}"
                                            ToolTip="Óäàëèòü íîìåð òåëåôîíà" 
                                            Height="50"
                                            Style="{StaticResource MaterialDesignFlatButton}"
                                            Click="BTNPhoneDel_Click"/>
                                </StackPanel>
                                <DataGrid Name="dgPhonesEmployee"
                                          Grid.Row="2" FontSize="14"
                                          AutoGenerateColumns="False" CanUserDeleteRows="False" CanUserAddRows="False"
                                          ColumnHeaderStyle="{StaticResource MaterialDesignDataGridColumnHeaderSize}"
                                          VirtualizingPanel.ScrollUnit="Item"
                                          CellEditEnding="DGPhonesEmployee_CellEditEnding">
                                    <DataGrid.Columns>
                                        <DataGridTextColumn Header="Òåëåôîí" Binding="{Binding Nomer, Converter={StaticResource phoneConverter}}" IsReadOnly="True"/>
                                        <DataGridCheckBoxColumn Header="Îñíîâíîé" 
                                                                Binding="{Binding IS_Osnovnoj}"
                                                                ElementStyle="{StaticResource MaterialDesignDataGridCheckBoxColumnStyle}"
                                                                EditingElementStyle="{StaticResource MaterialDesignDataGridCheckBoxColumnEditingStyle}"/>
                                    </DataGrid.Columns>
                                </DataGrid>
                            </Grid>
                            <Button Name="btnCloseDhEmployee" Content="Çàêðûòü"
                                    Grid.Row="1" HorizontalAlignment="Right" Margin="5 5 15 15"
                                    Click="BTNCloseDhEmployee_Click"
                                    IsCancel="True"/>
                        </Grid>
    </materialDesign:DialogHost.DialogContent>
</materialDesign:DialogHost> `
![E1](https://user-images.githubusercontent.com/73269176/99227699-2a600d80-281e-11eb-8374-c72a8e90792f.png)

**Comment by mkruijver** [comment]
This is likely a duplicate of https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1198 and https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1097

See https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1097#issuecomment-434996088 for a workaround

**Comment by omllmo** [comment]
Thank you for your help
