### ISSUE TITLE
Set floating scale for HintAssist.HelperText

### ISSUE THREAD

**Issue by nejcgalof** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2170]
Adjustable font size for materialDesign:HintAssist.HelperText. materialDesign:HintAssist.FloatingScale change only materialDesign:HintAssist.Hint. Would be great to set somehow HelperText too.

**Comment by Keboo** [comment]
I believe the best fix for this issue is to include a new `HintAssist.HelperTexFontSize` attached property. This property should then be consumed on the various controls that also use `HelperText`.

**Comment by artipo** [comment]
I'll try to implements your guidelines.
