### ISSUE TITLE
Can't build MaterialDesignToolkit.Wpf.slnf

### ISSUE THREAD

**Issue by reyntjesr** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2172]
I did a git pull on the master branch and tried to build the project.

But now I get 12 errors like below:
`Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Data.DataSetExtensions;System.Security.Cryptography.Algorithms;System.Security.Cryptography.X509Certificates;xunit.abstractions;Microsoft.NETCore.Platforms;System.Net.Http;System.Security.Cryptography.Encoding;xunit.core;xunit.extensibility.execution;Microsoft.CSharp;xunit.assert;xunit.analyzers;xunit.extensibility.core.	MaterialDesignColors.Wpf.Tests
`

Any idea what went wrong?

```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by Keboo** [comment]
@reyntjesr can you check again on latest master? I just merged a change that I believe addresses it. In short we are using new central NuGet package management to try and keep things simple, but one of the projects was missing the needed references.

**Comment by reyntjesr** [comment]
The number of errors went down from 12 to 10 :-)

Below is a list of the rest of the errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Data.DataSetExtensions;AvalonEdit;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp;System.Data.DataSetExtensions;System.Text.Json;AvalonEdit;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp.	MahAppsDragablzDemo	

Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Data.DataSetExtensions;Microsoft.NETCore.Platforms;System.Net.Http;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp;System.Threading.Tasks;System.Globalization.Extensions;System.Reflection;System.Resources.ResourceManager;System.Diagnostics.Debug;runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Text.Encoding;System.Data.DataSetExtensions;runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Algorithms;System.Security.Cryptography.X509Certificates;System.Runtime.InteropServices;runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Primitives;System.IO;System.Text.Json;System.Collections.Concurrent;Microsoft.NETCore.Platforms;System.Security.Cryptography.OpenSsl;runtime.native.System;Microsoft.NETCore.Targets;System.Security.Cryptography.Cng;runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Net.Http;runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Encoding;System.Runtime.Numerics;System.Runtime.Handles;runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Diagnostics.DiagnosticSource;System.Runtime.Extensions;System.Security.Cryptography.Csp;System.Globalization.Calendars;ControlzEx;System.Globalization;System.Runtime;runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Collections;Microsoft.Xaml.Behaviors.Wpf;runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Diagnostics.Tracing;System.Linq;System.Threading;runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;Microsoft.CSharp;System.IO.FileSystem;runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.IO.FileSystem.Primitives;runtime.native.System.Security.Cryptography.OpenSsl;System.Net.Primitives;System.Reflection.Primitives;runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple;runtime.native.System.Security.Cryptography.Apple;runtime.native.System.Net.Http.	MaterialDesignThemes.MahApps	

Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Data.DataSetExtensions;Microsoft.NETCore.Platforms;System.Net.Http;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp;System.Threading.Tasks;System.Globalization.Extensions;System.Reflection;System.Resources.ResourceManager;System.Diagnostics.Debug;runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Text.Encoding;System.Data.DataSetExtensions;runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Algorithms;System.Security.Cryptography.X509Certificates;System.Runtime.InteropServices;runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Primitives;System.IO;System.Text.Json;System.Collections.Concurrent;Microsoft.NETCore.Platforms;System.Security.Cryptography.OpenSsl;runtime.native.System;Microsoft.NETCore.Targets;System.Security.Cryptography.Cng;runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Net.Http;runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Security.Cryptography.Encoding;System.Runtime.Numerics;System.Runtime.Handles;runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Diagnostics.DiagnosticSource;System.Runtime.Extensions;System.Security.Cryptography.Csp;System.Globalization.Calendars;ControlzEx;System.Globalization;System.Runtime;runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Collections;Microsoft.Xaml.Behaviors.Wpf;runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.Diagnostics.Tracing;System.Linq;System.Threading;runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl;Microsoft.CSharp;System.IO.FileSystem;runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl;System.IO.FileSystem.Primitives;runtime.native.System.Security.Cryptography.OpenSsl;System.Net.Primitives;System.Reflection.Primitives;runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl;runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple;runtime.native.System.Security.Cryptography.Apple;runtime.native.System.Net.Http.	MaterialDesignThemes.MahApps	

Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Data.DataSetExtensions;AvalonEdit;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp;System.Data.DataSetExtensions;System.Text.Json;AvalonEdit;ControlzEx;Microsoft.Xaml.Behaviors.Wpf;Microsoft.CSharp.	MahAppsDragablzDemo	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\obj\project.assets.json' doesn't have a target for 'net452'. Ensure that restore has run and that you have included 'net452' in the TargetFrameworks for your project.	MaterialDesignColors.Wpf	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MaterialDesignColors.Wpf\obj\project.assets.json' doesn't have a target for 'netcoreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project.	MaterialDesignColors.Wpf	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\obj\project.assets.json' doesn't have a target for 'netcoreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project.	MaterialDesignThemes.Wpf	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\obj\project.assets.json' doesn't have a target for 'net452'. Ensure that restore has run and that you have included 'net452' in the TargetFrameworks for your project.	MaterialDesignThemes.Wpf	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MainDemo.Wpf\obj\project.assets.json' doesn't have a target for 'netcoreapp3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project.	MaterialDesignDemo	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	

Error	NETSDK1005	Assets file 'C:\Users\rreij\OneDrive\Documenten\DotNet\Lib\Controls\MaterialDesignInXamlToolkit\MainDemo.Wpf\obj\project.assets.json' doesn't have a target for 'net472'. Ensure that restore has run and that you have included 'net472' in the TargetFrameworks for your project.	MaterialDesignDemo	C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241

**Comment by bombipappoo** [comment]
If you had previously built on the same working tree, run "git clean -Xfd" to remove the previous output.

**Comment by reyntjesr** [comment]
It works! Thank you!
