### ISSUE TITLE
PopupBox : Click twice to open a second PopupBox

### ISSUE THREAD

**Issue by Tenjim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2175]
Hi guys,

I have a app with several PopupBox in PopupMode="Click". 
I have an issue when I want to click to an other PopupBox. I need to click twice to switch on the second. 
First click to close the first popup and the second click to select the second popup.

For example in your demo app ( MaterialDesignInXamlToolkit\MainDemo.Wpf ) :

![demowpfApp](https://user-images.githubusercontent.com/11456289/99693436-a57a2b80-2a8b-11eb-9552-dd7308bc7d75.jpg)

When you click on the first popup on the top right (green button) and wanted to click to the burger menu on the top left (red button), you need two click.

There is any workaround about this issue ?

Thanks in advance,
Tenjim

**Comment by Erapchu** [comment]
Hi! Because it's a popup)
I think this is possible, but i found only issue when you set other PopupMode, except Click, you can't use a popup at all. You can find property named StaysOpen, but it false by default.

**Comment by Tenjim** [comment]
Yes, 
We use it as a menu display to expand and collapse. So we need to have this property (StayOpen) to false. to let us to open and close manually on click. It's only when switching popup to have that issue of double click.
