### ISSUE TITLE
DataGrid Resouce not found

### ISSUE THREAD

**Issue by seokhoyoun** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2178]
I made a datagrid with autogenerated column.
and it seems worked perfectly.
but I found an exception when I click datagridcells in datagrid. (first click is fine, click next cell, it happens)
exception message shows ```"System.Windows.ResourceDictionary Warning: 9 : Resource not found"```
I tried to add this to my UserControl Resources ```........../MaterialDesignTheme.DataGrid.xaml />``` 
but it's still happening. is there something I missed?

**Comment by Keboo** [comment]
Hi @seokhoyoun can you provide the full exception details or ideally a project that reproduces the issue?
