### ISSUE TITLE
resource could not be resolved in WPF in VS2019

### ISSUE THREAD

**Issue by WeixiangZhang** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2183]
Version: MaterialDesignTheme 3.2 via Nuget
VS2019: v16.8.2

I setup project following Getting Started. 
But the resources could not be resolved in designer, but it‘s ok when running.

And use VS2015 to open this VS2019 solution,  the resources can be resolved in designer.

How to fix this? Thanks.

![error](https://user-images.githubusercontent.com/11531781/100980128-bf356b80-357f-11eb-9fd6-3ddf648a8f6d.jpg)

![app](https://user-images.githubusercontent.com/11531781/100981223-78487580-3581-11eb-89e9-bab9df82817b.jpg)

**Comment by SandnerSoft** [comment]
Hello,

same issue here.

**Comment by Keboo** [comment]
A few follow up questions. 
1. `MaterialDesignIconButton` is an optional style, so you will need to explicitly reference the Buttons resource dictionary (example [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d36ee6658ef42d0d45c4c0d36838514c48f6f042/MainDemo.Wpf/Buttons.xaml#L18)). For more information on this see [this wiki page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#exception-cannot-find-resource-named-materialdesign).
2. What version of Visual Studio are you using? You can find this from the Help >> About Microsoft Visual Studio menu at the top. 
3. What version of .NET is your app targeting (.NET Framework, .NET Core 3.1, .NET 5)?

**Comment by WeixiangZhang** [comment]
@Keboo 
I followed Quick Start to setup.
![1](https://user-images.githubusercontent.com/11531781/101307496-99131280-3882-11eb-9092-9b1c107d6887.png)

VS2019 info:
![2](https://user-images.githubusercontent.com/11531781/101307511-a5976b00-3882-11eb-852b-710689c0250e.png)

Net framework info:
![3](https://user-images.githubusercontent.com/11531781/101307543-b34cf080-3882-11eb-9469-7269c2d7d406.png)

**Comment by WeixiangZhang** [comment]
@Keboo In my tests, this issue is caused by **x64 platform**.

In VS2019,  set platform to **x64** will cause this issue and even set back to **Any CPU or x86**, it will not recover.
Clean and rebuild resolution will not work.
![4](https://user-images.githubusercontent.com/11531781/101307753-26eefd80-3883-11eb-93ed-929673323985.png)

But in VS2015, set back to **Any CPU**, it works and resources could be resolved.

So when use VS2019, I must be very careful not to set platform to x64......
