### ISSUE TITLE
Add the ripple effect within the size range of the button

### ISSUE THREAD

**Issue by fei-678** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2184]
Hello.I want the button to achieve the water ripple effect, but not the water ripple of the entire screen, only the water ripple within the size range of the button.How  should  I do it?thank you .

**Comment by Keboo** [comment]
@fei-678 can you explain a bit more of what you are looking for? The existing button controls have the ripple effect and it should be constringed to be just within the size of the button.

**Comment by fei-678** [comment]
hello. Now that the project clicks on the button, the entire interface will flash, as if waves fill the entire interface. I don’t want this. I want to display waves within the size range of the button.Thank you.

**Comment by Keboo** [comment]
@fei-678 are you able to provide a project or screen recording of what you are seeing. I am not able to reproduce that issue.
