### ISSUE TITLE
Reuse PackIcon

### ISSUE THREAD

**Issue by phantomfuxor** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2185]
Is it possible to reuse Icons?

I have this snippet in resource dictionary.
![image](https://user-images.githubusercontent.com/175284/101150317-610c9500-3620-11eb-8656-328b67978a8f.png)

Then i create a window that merges that res dict, and has 2 buttons. Both buttons have content set by dynamicresource to that Key. 
In designer it looks fine. 
When i run the app first (left) button has icon, the right button doesn't.  Why?

**Comment by Keboo** [comment]
This is a common thing with WPF. If you put a control in a resource dictionary that is a single instance of the control. If you want to effectively have something you can stamp into different places. The trick here is to use a template and use that in multiple places. That is the generic way to solve the issue.
However if you are just concerned with PackIcons you could simply wrap up all of those properties in a single Style and apply that to different PackIcon instances.

**Comment by phantomfuxor** [comment]
Yes we've found out the solution to use x:Shared="false" in Resource dictionary which then makes the icon recreate on each retrieval, which works fine. It's a bit more memory use but not really a problem. I thought that PackIcon could be used as a Resource since it was using drawing techniques behind the scenes.

**Comment by Keboo** [comment]
Great! Yea that would work as well. The issue with a shared resource is it is using a full control to be able to allocate the space needed for rendering.
