### ISSUE TITLE
[HELP] All objects added to an IDictionary must have a Key attribute or some other type of key associated with them. 

### ISSUE THREAD

**Issue by Neon-Fox** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2194]
#I am getting this error:
All objects added to an IDictionary must have a Key attribute or some other type of key associated with them. 

https://prnt.sc/w4g43z

I am not sure how to fix this. Please answer or tell me on discord: Neon_ Fox#4237
(Ignore the error and warn count.. it is other stuff)

Code:
`        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>`

**Comment by Keboo** [comment]
@Neon-Fox it looks like you have both an implicit resource dictionary as well as an explicit one. 
Move the style that ends on line 1513 (and anything else) in the resource dictionary, **inside** of the resource dictionary you declared on line 1514.

**Comment by Neon-Fox** [comment]
> @Neon-Fox it looks like you have both an implicit resource dictionary as well as an explicit one.
> Move the style that ends on line 1513 (and anything else) in the resource dictionary, **inside** of the resource dictionary you declared on line 1514.

Thanks my dude. That worked.
