### ISSUE TITLE
ComboBox bottom shadow not display when bottom is on a textblock

### ISSUE THREAD

**Issue by VShawn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2199]
here is the demo app's screen short:

![image](https://user-images.githubusercontent.com/10143738/103207829-433e0180-493a-11eb-80e2-10483300d462.png)

![image](https://user-images.githubusercontent.com/10143738/103207841-4afda600-493a-11eb-89a9-ada2289f0026.png)

![image](https://user-images.githubusercontent.com/10143738/103207845-4df89680-493a-11eb-821e-da6d9bf92619.png)

**Comment by Erapchu** [comment]
![image](https://user-images.githubusercontent.com/37536541/105571558-67e39880-5d83-11eb-9426-2f7c8f57982c.png)
On my side all is fine. Last master commit for today.
Always visible.
![image](https://user-images.githubusercontent.com/37536541/105571607-d7f21e80-5d83-11eb-82d9-0b5adcdeee38.png)

**Comment by Erapchu** [comment]
I see that popup hasn't corner radius on your screenshots. Did you apply any additional libraries or set corner radius for popup somewhere?

**Comment by Keboo** [comment]
This is likely resolved with the Combobox redesign in the 4.2.1 release.
