### ISSUE TITLE
TabControl header layout is vertical when "TabStripPlacement" set to "Top" or "Bottom". Is "Horizontal" better?

### ISSUE THREAD

**Issue by johnny3577** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2200]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/aaa1a39a3a4f75d708d6a338de1902b5364a2f3e/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml#L377

**Comment by Keboo** [comment]
I believe this is fixed by #2181
