### ISSUE TITLE
Increase size of hit/touch target

### ISSUE THREAD

**Issue by TysonMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2207]
In my program at work, we are making WPF application that will be used on a touch screen.  As such, we think it would be useful if some of the hit targets (aka touch targets) for certain controls were a bit larger than their visual appearance.  For example, I think it would be better for touch screen users if the hit target of the thumb on a slider where larger.  I tried looking at the existing API, but I didn't see a way to make that change.

Is it possible to increase the size of hit targets?  Specifically, is it possible to increase the size of the hit target for the thumb of a slider?

**Comment by Erapchu** [comment]
Do you mean size of a point that can be dragged along the slider? For now i think you really can't increase a size of a thumb with an API of this framework. But you can increase width and height of thumb by customizing control template directly.
You can see how it implemented in
`MaterialDesignInXamlToolkit\MaterialDesignThemes.Wpf\Themes\MaterialDesignTheme.Slider.xaml`
And write your own template based on it for your purpose. For now ellipse of thumb have 12x12 px size.
I think, you may add your own attached property and change size of thumb in this control template. 
For example:

`public static readonly DependencyProperty SliderThumbSizeProperty = DependencyProperty.RegisterAttached(
            "SliderThumbSize", typeof(double), typeof(SliderAssist), new PropertyMetadata(12));`

And in xaml:

`Width="{TemplateBinding wpf:SliderAssist.SliderThumbSize}"
Height="{TemplateBinding wpf:SliderAssist.SliderThumbSize}"`

Just for example. And you may need to handle margin/padding properties.

**Comment by Keboo** [comment]
I believe @Erapchu is correct. Aside for rolling your own template for the thumb there is not a really an API exposed for increasing the hit target size. Typically the easiest way to do this is with an element that has a Transparent background (explicitly set to Transparent) so that the default [hit testing](https://docs.microsoft.com/dotnet/desktop/wpf/graphics-multimedia/hit-testing-in-the-visual-layer?view=netframeworkdesktop-4.8) will properly resolve to the correct element.

**Comment by Keboo** [comment]
Closing for now as the only real solution for a WPF touch based application is to adjust the size of the thumb. This is likely best achieved within individual applications rather than within this library.
