### ISSUE TITLE
Is it possible to change the hint of a textbox in the code behind ?

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2208]
I know I can change the hint of a textbox in the xaml code using
![image](https://user-images.githubusercontent.com/54487782/103787953-943aad80-503e-11eb-8ef1-98d231edd836.png)

I would like to know if it's possible to change the hint using the property in the code behind.

I can't find the hint property in the environment
![image](https://user-images.githubusercontent.com/54487782/103788239-e4b20b00-503e-11eb-9a05-09dffca1da4d.png)

Maybe I have to include something in the code. 

I don't know, that's why I'm asking this question.

Thank you.

**Comment by AmRo045** [comment]
Try this:
```c#
using MaterialDesignThemes.Wpf;

HintAssist.SetHint(SampleTextBox, "Awesome hint");
```

**Comment by Keboo** [comment]
You can also see the relevant WPF docs for it [here](https://docs.microsoft.com/dotnet/desktop/wpf/advanced/attached-properties-overview?view=netframeworkdesktop-4.8#attached-properties-in-code-) as well.

**Comment by Xaalek** [comment]
Thank you very much !
