### ISSUE TITLE
DataGrid Cell Editor loses material style when setting AutoGenerateColumns to False

### ISSUE THREAD

**Issue by hussain1368** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2210]
When `AutoGenerateColumns="True"` editor for cells has material design style. but when I set it to False and use `DataGrid.Columns` to define columns in the DataGrid the style changes.

![Captre](https://user-images.githubusercontent.com/36886947/104319083-fd6a6700-54fd-11eb-85c6-9ce774a782dc.PNG)

Thank you.

**Comment by HeilOliver** [comment]
I had exactly the same problem.
What was my mistake here is that a style was missing.

Each column must also have the style "MaterialDesignDataGridTextColumnEditingStyle".
Example:
```XML
<DataGridTextColumn
     EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnEditingStyle}"
     Binding="{Binding SomeProperty}" />
```

**Comment by Keboo** [comment]
This is by design. When using the DataGridTextColumn the editing style must be explicitly set.

**Comment by hussain1368** [comment]
Thank you @HeilOliver and @Keboo. It worked!
