### ISSUE TITLE
Display issue with the MaterialDesignFilled style on TextBox

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2213]
As you can see, the controls with the filled style have an issue. Space is reserved for the hint even if there is no hint

![image](https://user-images.githubusercontent.com/54487782/104741937-22ebb080-574a-11eb-9598-0d96f1895cac.png)

So we end up having to make a control bigger than 66 pixels (height) and with a big blank space above the text.

The style concerned is : `MaterialDesignFilledTextFieldTextBox`

I think there is the same issue with `ComboBox` and `DatePicker`

**Comment by Keboo** [comment]
@Xaalek are you apply to provide some code that reproduces the problem?

**Comment by Xaalek** [comment]
Just place a textbox and apply the MaterialDesignFilledTextFieldTextBox style on it

`<TextBox  Height="61" Margin="799,-6,140,0" Text="TextBox" VerticalAlignment="Top" Width="120" Style="{StaticResource MaterialDesignFilledTextFieldTextBox}"/>`

See what happens :

I put a textbox next to it, with the default style, to compare the two textbox


https://user-images.githubusercontent.com/54487782/105149794-3e690980-5b04-11eb-9193-fe4c60ca2165.mp4


https://user-images.githubusercontent.com/54487782/105149803-40cb6380-5b04-11eb-9927-b943f9d259e7.mp4

As you can see the text is cut off on the textbox with the filled style. So I think the problem come from the hint. Maybe some space is reserved for the hint even if there is no hint.

**Comment by MichelMichels** [comment]
Test with latest codebase:

![image](https://user-images.githubusercontent.com/6505319/105498455-86349000-5cc0-11eb-84d6-5c835dfbb183.png)

@Xaalek You have a static height set in your XAML of 23 and weird margin numbers on each TextBox. Maybe that has something to do with it.

**Comment by Xaalek** [comment]
@MichelMichels I have weird margin cause I dragged and dropped them. And for the height, I would like to have a height of 23p like the textbox with the default style. But I can't cause the text is cutted off. If I want to see the text not cutted off, I have to put a height of minimum 66p.

**Comment by MichelMichels** [comment]
Could you provide a test repository with this issue?

**Comment by Xaalek** [comment]
zip file of my project : https://drive.google.com/file/d/13jIwbpbYMSlD2naRMDRsXGnJPanEYK7m/view?usp=sharing

There is maybe a link to this issue https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2230

**Comment by pressacco** [comment]
Let me begin by saying that I am really impressed with this library. Thank you to all of those who contributed to the project!

---

It would be helpful if the documentation provided some guidance on how to implement the WPF default behavior for an editable `ComboBox`:

1. DO NOT display list of items when `ComboBox` is clicked.
   - The user can simply click the combo box and start typing without having the dropdown obstructing the UI.   
2. DO display list of items when `ComboBox` arrow is clicked.
   - When the user wants to see the list of options, they can explicitly request to see them by clicking the combo box arrow.

I am still relatively new to WPF, and the solution has escaped me.

### Additional Context

It appears that the *MaterialDesignInXaml* default behavior for a `IsEditable="True"` `ComboBox` is to:

- automatically display the list of dropdown items on `PreviewMouseDown` or `MouseLeftButtonDown`
