### ISSUE TITLE
Setting the SecondaryAccentBrush will not affect

### ISSUE THREAD

**Issue by hussain1368** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2214]
I am trying to set the background color of the button to red. I have done as below:
```
<Button Style="{StaticResource MaterialDesignRaisedAccentButton}">
    Delete
    <Button.Resources>
        <SolidColorBrush x:Key="SecondaryAccentBrush" Color="Red"/>
        <SolidColorBrush x:Key="SecondaryAccentForegroundBrush" Color="#FFFFFF"/>
    </Button.Resources>
</Button>
```
I also tried to set the value in App.xaml:
```
<ResourceDictionary>
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
        <!--<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />-->
    </ResourceDictionary.MergedDictionaries>

    <SolidColorBrush x:Key="SecondaryAccentBrush" Color="Red"/>
    <SolidColorBrush x:Key="SecondaryAccentForegroundBrush" Color="#FFFFFF"/>
</ResourceDictionary>
```
But still no affect. When I uncomment those two lines in the App.xaml the button turns light green (which is the default color for Accent button).

**Comment by Erapchu** [comment]
If you want to set background of only one button to red, you may set Background and BorderBrush properties to Red or SolidColorBrush with red color. 
If you want to make accent color of all application as red, just change it in merged dictionaries.
Don't put solid color brush in app.xaml. Set it in Windows.Resources or in merged dictionaries in app.xaml with your brushes.xaml resource dictionary for example.

**Comment by Keboo** [comment]
I agree with @Erapchu, does setting the Background, BorderBush to the colors to red meet your needs?

**Comment by hussain1368** [comment]
The problem solved by changing `SecondaryAccentBrush` to `SecondaryHueMidBrush`. Thank you
