### ISSUE TITLE
Multiple ripple effect on buttons like in MaterialSkin for WinForms

### ISSUE THREAD

**Issue by Erapchu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2219]
Ok, when you click on any control you may see only one ripple. Can we add multiple ripple effects?
For example I'll provide link to popular winforms material skin library: 
https://github.com/IgnaceMaes/MaterialSkin
When you double/tripple click on a button you may see two/three ripples.

**Comment by Keboo** [comment]
Currently no, there is nothing is this library that would support that. You may be able to implement something similar using the Ripple control, but it will likely take a few modifications. 
Given that the material design spec only shows a single ripple effect on a click this library is unlikely to add support for multiple ripples.
