### ISSUE TITLE
Snackbar Bug

### ISSUE THREAD

**Issue by HenJigg** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2226]
Transient blur

![1](https://user-images.githubusercontent.com/42528522/105711410-7c768b00-5f53-11eb-9397-25e3bda4b75c.gif)

**Comment by HenJigg** [comment]
[WpfApp1.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5866828/WpfApp1.zip)

**Comment by Erapchu** [comment]
Hello!
I think you need to define one more grid for snackbar.
`<Grid><Grid>Your content</Grid><Snackbar/>`
In that case snackbar will overlap your content and works like in demo app.
Vertical alignment of this control is bottom. And when you set snackbar in the second stretched row of grid then set VerticalAlignment="Center", it'll be centered.
Or bug with something else?

**Comment by Keboo** [comment]
@HenJigg I am not sure I understand the issue from your description. Can you elaborate more on the issue?

**Comment by HenJigg** [comment]
Sorry, what I want to express is that when the content is presented, the font will become blurred for an instant and then return to normal

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Diyari-Kurdi** [comment]
Set **TextOptions.TextFormattingMode** to **Display**

For example:
```
<materialDesign:Snackbar
            x:Name="Snackbar"
            MessageQueue="{materialDesign:MessageQueue}"
            TextOptions.TextFormattingMode="Display" />
```
