### ISSUE TITLE
Don't have color on mouse over on MaterialDesignFlatButton

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2230]
I don't know why but in my environment, I don't have a color on mouse over on button with the MaterialDesignFlatButton style.

Even if I use the code of the demo app, I don't have a color on mouse over.

![image](https://user-images.githubusercontent.com/54487782/105982788-121b3300-6098-11eb-9a78-bdbf09a59bd7.png)

![image](https://user-images.githubusercontent.com/54487782/105982590-c5375c80-6097-11eb-8a09-3ebadecb5c9b.png)

```
<Button Style="{StaticResource MaterialDesignFlatButton}" ToolTip="MaterialDesignFlatButton">
      ACCEPT
</Button>
```

I have MaterialDesignColors v1.2.7 and MaterialDesignThemes v3.2.0 installed.

**Comment by Keboo** [comment]
@Xaalek Is this occurring on the latest 3.2.0 release? Does it also occur with the latest code on the master branch?

**Comment by Xaalek** [comment]
@Keboo It's occuring in my project but not in the MaterialDesignInXamlToolkit-3.2.0. 
This source code works fine for me : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/archive/v3.2.0.zip

But if I take the exact same xaml page and put it in my project, the button issue occures.
Video of the problem
https://www.youtube.com/watch?v=lPzD_f0aYDg

**Comment by Xaalek** [comment]
I recreated my entire project and now it works
