### ISSUE TITLE
Styles & themes with default looks 

### ISSUE THREAD

**Issue by phantomfuxor** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2233]
Hi, this is more of a question then issue.

Are you going to add Keys to all the styles and templates?

It's really irritating that i have to create styles for every control and everything because your templates and styles override the default looks and behaviours.  I mean, I love your controls and all of it, but sometimes i have some of my styles, some of them just slightly alter the default versions of items, and somewhere i really just use the default items. But now i have to rewrite styles of each control due to overlapping.

Is it possible to evade that somehow  ? 

P.S. where can i see a roadmap or something like that? When do we expect 4.0.0?

**Comment by artipo** [comment]
I think that you could try to not import 
`<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />`
in your `app.xaml`. It's this file that override most of the default styles.
Then you could pick individually each style that you like, or create your own version of `MaterialDesignTheme.Defaults.xaml`.

**Comment by phantomfuxor** [comment]
Yes, but. If you want to override a style you have to add the default style to the app.xaml to have its BasedOn overridden, and then adding your own res. dict. to override that in app xaml.  

I thought it was possible to extract style from a namespace for BasedOn usage since i only want to override maybe a few controls.

**Comment by Keboo** [comment]
@phantomfuxor most of the controls have styles in their own resource dictionaries. Those resource dictionaries should not have any implicit styles so you should be able to reference the ones that you want without getting any implicit styles. 

The other thing to note is that technically all of the styles do have keys set on them. The implicit styles (the ones with just a TargetType, and no explicit x:Key), can be reference in your BasedOn by using the type. For example if you want to extend the default button style you can do something like this:

```XAML
<Style TargetType="Button" BasedOn="{StaticResource {x:Type Button}}">
...
</Style>
```
