### ISSUE TITLE
DataGrid keyboard navigation lose focus when pressing LEFT ARROW

### ISSUE THREAD

**Issue by eugeneli71** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2234]
Hi
  I am having this DataGrid keyboard navigation issue.
If the focus is in the first cell in the row, pressing the LEFT ARROW will lose focus, and can not focus.
 According to the  [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid_guidance/keyboard_navigation_selection), if the focus is in the first cell in the row, pressing the LEFT ARROW should does nothing.
Do you have any idea how to fix this ?

**Comment by Erapchu** [comment]
Hi
You can try to press DOWN arrow to re-focus data grid.
