### ISSUE TITLE
Button mouse hover cursos does not change

### ISSUE THREAD

**Issue by kimvlas** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2238]
Hi,

I don't know if it's an issue or just something that i'm missing in my solution.
When you place a Button or a combobox the mouse cursor changes from a pointer to a hand if you are hovering this control.

This only happens with me if i have those controls in a <materialDesign:DialogHost... >
But when i have this control on my "window or UserControl", this does not happen.
I have try's setting the property cursor, but no succes.
Excample:
 < Button Name="Import"  Grid.Row="1" Grid.Column="0" Margin="5" Width="200" Style="{DynamicResource MaterialDesignFlatButton}" Cursor="Hand" >

Does anybody know what the problem is with this?

**Comment by Keboo** [comment]
@kimvlas I am not able to replicate that behavior. In WPF the Cursor property is inherited down through the [visual tree](https://docs.microsoft.com/visualstudio/debugger/how-to-use-the-wpf-tree-visualizer?view=vs-2019). Look through your controls for one that sets the Cursor="Hand" (similar to your example code). I suspect it is getting set on a parent control and propagating down.

**Comment by kimvlas** [comment]
Hey,

I have test this with a new application, and the hand will be showned when i hover a button.
Then i checked the live property window, and indeed the cursor is there removed, why i still still don't know.
Now as a temperaly option, i have set the cursor hand with the mouseEnter and leave option.

thx for the resplay
