### ISSUE TITLE
Binding Error when clearing items

### ISSUE THREAD

**Issue by Jan-Magerl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2239]
This binding causes an error if items are removed from the collection of the data source.

System.Windows.Data Error: 4 : 
Cannot find source for binding with reference 
'RelativeSource FindAncestor, 
AncestorType='System.Windows.Controls.DataGridRow', 
AncestorLevel='1''. 
BindingExpression:Path=Foreground; 
DataItem=null; 
target element is 'DataGridCell' (Name=''); 
target property is 'Foreground' (type 'Brush')

In the prior Version 3.1.3 it works fine.

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/04f1326ce9ebb591ed99e21b226b9eb78eaab29a/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L221

**Comment by Keboo** [comment]
@Jan-Magerl  just to confirm, you are running the 3.2.0 release correct?

**Comment by Jan-Magerl** [comment]
> @Jan-Magerl just to confirm, you are running the 3.2.0 release correct?

correct

**Comment by Keboo** [comment]
@Jan-Magerl could you please re-test with the latest 4.0.0 release. I am currently not able to reproduce this issue. 
If you can reproduce it, could you provide a project that demonstrates the problem?

**Comment by MichelMichels** [comment]
No further feedback provided.
