### ISSUE TITLE
textbox will throw an exception under certain circumstances

### ISSUE THREAD

**Issue by SmRiley** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2246]
When WindowStyle="None", an exception will be triggered when the mouse presses down and crosses the border of the textbox
C#:
```C#
  public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Window_MouseMove(object sender, MouseEventArgs e)
        {
            if (e.LeftButton == MouseButtonState.Pressed)
            {
                DragMove();
            }
        }
    }
```
XAML:
```XAML
<Window x:Class="WpfApp1.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp1"
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        mc:Ignorable="d"
        WindowStyle="None"
        MouseMove="Window_MouseMove"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Border BorderBrush="LightGray" BorderThickness="1" Height="25" Width="120" CornerRadius="10">
            <TextBox VerticalAlignment="Center" Style="{StaticResource MaterialDesignComboBoxEditableTextBox}" materialDesign:HintAssist.Hint="搜索" FontSize="11" />
        </Border>
    </Grid>
</Window>
```
![image](https://user-images.githubusercontent.com/45205313/108056808-bc311e00-708c-11eb-9bc5-8f60f7643106.png)

**Comment by SmRiley** [comment]
Just found that you don't need to cross the border, just press and hold the mouse in the textbox and slide it

**Comment by Keboo** [comment]
This is actually not related to the material design library.  The `InvalidOperationException` still occurs in any WPF project. The reason is because when you call `DragMove()` on a Window it will suspend the Dispatcher for the Window. A more description error message for the exception might be "Cannot call DragMove while another drag operation is in process". When it starts dragging, the second mouse move event comes in from the TextBox and tries to trigger a second DragMove and that throws the exception. A simple fix would be to simply unregister for the MouseMove event until after the DragMove has completed. Like this:

```
private void Window_MouseMove(object sender, MouseEventArgs e)
{
    if (e.LeftButton == MouseButtonState.Pressed)
    {
        this.MouseMove -= Window_MouseMove;
        DragMove();
        this.MouseMove += Window_MouseMove;
    }
}
```

**Comment by SmRiley** [comment]
> 这实际上与材料设计库无关。这仍然发生在任何 WPF 项目中。原因是当您调用窗口时，它将挂起窗口的调度程序。异常的更描述错误消息可能是"在另一个拖动操作中无法调用 DragMove"。当它开始拖动时，第二个鼠标移动事件从 TextBox 进入，并尝试触发第二个 DragMove 并引发异常。一个简单的解决方法是简单地取消注册 MouseMove 事件，直到 DragMove 完成之后。喜欢这个：`InvalidOperationException``DragMove()`
> 
> ```
> private void Window_MouseMove(object sender, MouseEventArgs e)
> {
>     if (e.LeftButton == MouseButtonState.Pressed)
>     {
>         this.MouseMove -= Window_MouseMove;
>         DragMove();
>         this.MouseMove += Window_MouseMove;
>     }
> }
> ```

That's it,Thank you : )

**Comment by SmRiley** [comment]
As a reminder, MouseMove is not recommended to be set in Window, otherwise it will cause the scroll bar inside to hold down and drag the mouse to fail.
