### ISSUE TITLE
How disable CharacterCounter on TextBox

### ISSUE THREAD

**Issue by dannythegreat** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2247]
Hi,
after latest update, my textboxes show by default the character counter under the box.

To remove it, I tried to add a default style inside my xaml, like this:
`Style="{DynamicResource MaterialDesignTextBoxBase}"`

Unfortunately this not solve the problem. How I can disable min/max lenght counte? Thank you.

![Cattura](https://user-images.githubusercontent.com/15092413/108129917-1b078f00-70af-11eb-87c0-07a53569aaa1.JPG)

**Comment by Keboo** [comment]
Looks like you are wanting something similar to what was requested [here](https://twitter.com/jamesport079/status/1360858011267432449). 
Simply setting an empty style to the `TextFieldAssist.CharacterCounterStyle` property.

```xaml
<TextBox>
    <materialDesign:TextFieldAssist.CharacterCounterStyle>
        <Style TargetType="TextBlock" />
    </materialDesign:TextFieldAssist.CharacterCounterStyle>
</TextBox>
```

**Comment by dannythegreat** [comment]
> Looks like you are wanting something similar to what was requested [here](https://twitter.com/jamesport079/status/1360858011267432449).
> Simply setting an empty style to the `TextFieldAssist.CharacterCounterStyle` property.
> 
> ```
> <TextBox>
>     <materialDesign:TextFieldAssist.CharacterCounterStyle>
>         <Style TargetType="TextBlock" />
>     </materialDesign:TextFieldAssist.CharacterCounterStyle>
> </TextBox>
> ```

Thank you, but there is a way to disable to all Textboxes by xaml Style?

**Comment by Keboo** [comment]
Yes, you can create an [implicit style](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/fundamentals/styles-templates-overview?view=netdesktop-5.0#styles) targeting TextBoxes. You can put something like this in your App.xaml. 

```xaml
<Style TargetType="TextBox" BasedOn="{StaticResource MaterialDesignTextBox}">
    <Setter Property="materialDesign:TextFieldAssist.CharacterCounterStyle">
        <Setter.Value>
            <Style TargetType="TextBlock" />
        </Setter.Value>
    </Setter>
</Style>
```

**Comment by Keboo** [comment]
In the next release there will be a new attached property you can use to hide the character counter.

```xaml
<TextBox
    MaxLength=""10""
    materialDesign:TextFieldAssist.CharacterCounterVisibility=""Collapsed""
/>
```

**Comment by dannythegreat** [comment]
Thank you so much!

> Yes, you can create an [implicit style](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/fundamentals/styles-templates-overview?view=netdesktop-5.0#styles) targeting TextBoxes. You can put something like this in your App.xaml.
> 
> ```
> <Style TargetType="TextBox" BasedOn="{StaticResource MaterialDesignTextBox}">
>     <Setter Property="materialDesign:TextFieldAssist.CharacterCounterStyle">
>         <Setter.Value>
>             <Style TargetType="TextBlock" />
>         </Setter.Value>
>     </Setter>
> </Style>
> ```

**Comment by marcosgerene** [comment]
Hi everyone,

I had the same trouble and I did:

```
<Setter Property="materialDesign:TextFieldAssist.CharacterCounterStyle" Value="{x:Null}" />
```

Thank you all.

**Comment by 9helix** [comment]
can materialDesign:TextFieldAssist.CharacterCounterVisibility be set from code-behind?

**Comment by Keboo** [comment]
@9helix yes, this is just an attached property, you can see how to set these in code [here](https://learn.microsoft.com/dotnet/desktop/wpf/properties/attached-properties-overview?view=netdesktop-8.0&WT.mc_id=DT-MVP-5003472#attached-properties-in-code)
