### ISSUE TITLE
Breaking 5.0.0 Changes

### ISSUE THREAD

**Issue by Keboo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2255]
There is an existing `5.0.0` branch where these changes are being made. Once we are a little closer to the release this branch will be merged into `master`. Anyone is welcome to pick up tasks here and PR into the `5.0.0` branch.

This is a list of proposed breaking changes for the 5.0.0 release. Feedback welcome!

- [x] Remove `DrawerHostOpenMode.Model` (Added in 4.0.0, Obsolete in 4.1.0)
- [x] Remove `MaterialDesignScrollBarThumbVertical` and `MaterialDesignScrollBarThumbHorizontal` replace with `MaterialDesignScrollBarThumb`
- [x] Consider making [recommended theme color classes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MaterialDesignColors.Wpf/Recommended) static. 
  - Currently not possible because they implement the `ISwatch` interface.
- [x] Update ListBoxItem to use theme brush for hover color rather than deriving from the Foreground.
- [x] Update MenuItem to use theme brush for hover color rather than deriving from the Foreground.
- [x] There is a both usage of "Assist" and "Extensions" used. Consider standardizing on naming
- [x] Remove `MaterialDesignRaisedAccentButton` in favor of `MaterialDesignRaisedSecondaryButton`
- [x] Remove `MaterialDesignFlatAccentButton` in favor of `MaterialDesignFlatSecondaryButton`
- [x] Remove `MaterialDesignFlatAccentBgButton` in favor of `MaterialDesignFlatSecondaryMidBgButton`
- [x] Remove `MaterialDesignFloatingActionMiniAccentButton` in favor of `MaterialDesignFloatingActionMiniSecondaryButton`
- [x] Remove `MaterialDesignFloatingActionAccentButton` in favor of `MaterialDesignFloatingActionSecondaryButton`
- [x] Remove `ComboBoxPopupPlacement`
- [x] Remove obsolete members from `ComboBoxPopup`
- [x] Remove obsolete templates `PopupContentUpTemplate` and `PopupContentDownTemplate`
- [x] Remove obsolete brushes #2435 
- [x] Replace usages of "Accent" with "Secondary"
- [x] Remove "MaterialDesignNavigatilRailTabControl" it is replaced by "MaterialDesignNavigationRailTabControl"
- [x] Remove RatingBarButton.IsWithinSelectedValue property
- [x] Remove obsolete members from `FlyoutAssist`
- [x] Remove `ShadowDepth`
- [x] Remove `ShadowAssist.ShadowEdges`
- [x] Rename `ShadowEdgeConverter` to `ShadowOpacityMaskConverter` to better reflect its usage
- [x] Ensure all styles and brushes that contain the word "Accent" have been replaced with "Secondary"
- [x] Remove `PickerInnerPaddingConverter` (obsolete in PR #3181)
- [x] Rename all *Mixin classes to be *Extensions
- [x] Remove MaterialDesignTheme.Defaults.xaml in favor of people using either MaterialDesign2.Defaults.xaml or MaterialDesign3.Defaults.xaml
- [x] Ensure all removed obsolete styles exist in the Obsolete shim resource dictionary.

**Comment by MichelMichels** [comment]
I'm in favor of dropping the netcoreapp3.1 target framework moniker as it reached it's end-of-life on December 13th, 2022. I'll make a pull request for it.

**Comment by cjmurph** [comment]
I think there is some missing breaking changes around the removal of ITheme and IBaseTheme interfaces. Maybe this is not the place? I couldn't find any reference to the removal of these interfaces anywhere else in regards to 4.9 -> 5.0

**Comment by DavidCFreire** [comment]
> I think there is some missing breaking changes around the removal of ITheme and IBaseTheme interfaces. Maybe this is not the place? I couldn't find any reference to the removal of these interfaces anywhere else in regards to 4.9 -> 5.0

Same behavior here. Missing iTheme

**Comment by Keboo** [comment]
@cjmurph and @DavidCFreire thank you for pointing this out. I had overlooked this change in the large number of other 5.0 changes (I have updated the list above).
