### ISSUE TITLE
Buttons are blurry, really blurry when compared to a filterchip checkbox

### ISSUE THREAD

**Issue by honguyenminh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2259]
This is quite unreasonable since the filter chip checkbox is sharp and clean, while the buttons are blurry at the edge and also have redundant residue at corners, shown as curved lines around the button

And for the default button, there's a hole or a dot at the corner

You dont need any special code for this, example can be found right in the demo app. Or if you want a closer look, boot up any WPF project that have MDIX configured, drag a button into the designer, then zoom in and see it for yourself.
Any button can reproduce this. But the checkboxes are ok.

Screenshots of the buttons:

Filter chip heckbox vs button
![Checkbox vs button](https://user-images.githubusercontent.com/32929093/109021788-caff7c80-76ed-11eb-9973-517f4c1135ad.PNG)

DemoApp
![DemoApp](https://user-images.githubusercontent.com/32929093/109021825-d18df400-76ed-11eb-8145-a6546f34c732.PNG)

The gap at the corner of default button
![The gap at the corner of default button](https://user-images.githubusercontent.com/32929093/109022330-4cefa580-76ee-11eb-8f0f-ab0b32835304.PNG)

With corner radius = 20
![With corner radius = 20](https://user-images.githubusercontent.com/32929093/109022978-f2a31480-76ee-11eb-8f4f-cbc4d09e6860.png)

**Comment by Erapchu** [comment]
Hello!
Buttons are cached with DependencyProperty CacheModeProperty in ShadowAssist.
To avoid this you need to set CacheMode property to null (shadow assist).
![image](https://user-images.githubusercontent.com/37536541/109377641-150b7c80-78ff-11eb-89f3-e94cbad77f3d.png)

**Comment by honguyenminh** [comment]
If that's how to fix the blurryness, why the CacheMode isn't set to null by default?

And look closely, you can still see the border in a standard filled button. The border is the exact same color, so why can't we just hide it by default?

**Comment by Erapchu** [comment]
To remove border please try to set border thickness property to zero.
What about cache mode, I faced an issue with it:

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2260

**Comment by Erapchu** [comment]
Cache mode should improve performance. Without it buttons and other controls may invoke lags.You can see blurred buttons and other controls - this is like a bitmap rendered image.

**Comment by honguyenminh** [comment]
I knew that, but why isn't it set to zero by default
It's there for no reason, and is causing visual residue on small buttons
