### ISSUE TITLE
[documentation] MahApps integration broken

### ISSUE THREAD

**Issue by LabuzzMichal** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2261]
Hi, 

MahApps integration does not work anymore with latest version of MahApp.Metro (2.4.3). The problem is that some of the resource names have changed and colors from both libraries are mixed. For example right now instead of having in app.xaml

`          
<SolidColorBrush x:Key="WindowTitleColorBrush" Color="{DynamicResource Primary700}"/>
 `

we should have 

```
<SolidColorBrush x:Key="MahApps.Brushes.WindowTitle" Color="{DynamicResource Primary700}"/>
<SolidColorBrush x:Key="MahApps.Brushes.Accent" Color="{DynamicResource Primary700}"/>

```

This is one change I found quickly but for sure there is more. Is there anybody who already integrated new versions and is willing to share new resources definition ? :)

**Comment by LabuzzMichal** [comment]
Actually there is a list with these changes on mahapps documentation page https://mahapps.com/docs/guides/migration-to-v2.0
I can create a PR for that. Is it fine ?

**Comment by Keboo** [comment]
@LabuzzMichal yea if you want to put together a PR for it, that would be great!

**Comment by MichelMichels** [comment]
Closed due to staleness.
