### ISSUE TITLE
Null dialog identifier handling proposal

### ISSUE THREAD

**Issue by Yoooi0** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2262]
This is more of a discussion/proposal to current behavior of dialog identifiers.

The current code that selects the target dialog host to be shown selects all instances when you pass `null` identifier to `DialogHost.Show`:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/00c4f66c4d4effebb39eba0beefbc4ba797aab60/MaterialDesignThemes.Wpf/DialogHost.cs#L205

Obviously this works:
```csharp
<DialogHost>...</DialogHost>

DialogHost.Show(content);
```

But this will throw an exception:
```csharp
<DialogHost>...</DialogHost>
<DialogHost Identifier="Other">...</DialogHost>

DialogHost.Show(content);
```
The above throws because of the `dialogIdentifier == null` condition selecting all dialog instances requiring you to add an identifier to each dialog host:
```csharp
<DialogHost Identifier="Main">...</DialogHost>
<DialogHost Identifier="Other">...</DialogHost>

DialogHost.Show(content, "Main");
```

My proposal is to remove `dialogIdentifier == null` condition to allow having a dialog host without an identifier be treated like a root/main one. It will still throw an exception when users have multiple dialog hosts without identifiers.
Unless I'm not understanding some more complex scenario I dont see why that condition is there.

This might be a super minor issue but ive added a second dialog host specific to one control and its forcing me to update many previous calls to `DialogHost.Show`.

**Comment by Keboo** [comment]
I think this proposal is a good one. I think I would phrase the desired interaction this way: the `DialogHost.Show` will only throw an exception if there is more than one DialogHost that matches the identifier; even if this identifier is null.

**Comment by balakrx** [comment]
This change forces the Dialog.Show to always be invoked with a dialog identifier. If not it throws `an InvalidOperationException:`

`System.InvalidOperationException`
`  HResult=0x80131509`
` Message=No loaded DialogHost have an Identifier property matching dialogIdentifier ('') argument.`
`  Source=MaterialDesignThemes.Wpf`
`  StackTrace:`
`   at MaterialDesignThemes.Wpf.DialogHost.GetInstance(Object dialogIdentifier)`
`   at MaterialDesignThemes.Wpf.DialogHost.<Show>d__26.MoveNext()`
`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

Invoking the Dialog.Show from the code (other than code behind) now requires knowing the dialog identifier defined in the XAML. I was invoking the call in my view models and commands and they all now need a dialog identifier which is defined in the view forcing the ViewModel to know about the view. I only have one DialogHost at the root of my application. Do you have a recommendation for how I can decouple the ViewModel from knowing the View dialog identifier?

Thank you

**Comment by jcummings2** [comment]
> Do you have a recommendation for how I can decouple the ViewModel from knowing the View dialog identifier?

@Keboo 
I would also like to know the answer to this question. This change broke assumptions in our code that the first DialogHost found would be used if you didn't pass in a `dialogIdentifier` (that is, when the `dialogIdentier` is `null`).

**Comment by jcummings2** [comment]
> > Do you have a recommendation for how I can decouple the ViewModel from knowing the View dialog identifier?
> 
> @Keboo I would also like to know the answer to this question. This change broke assumptions in our code that the first DialogHost found would be used if you didn't pass in a `dialogIdentifier` (that is, when the `dialogIdentifier` is `null`).

After looking some more, it appears to be the answer that you cannot be agnostic about the `dialogIdentifier` if you are calling `DialogHost.Show` from the ViewModel with the exception (no pun intended) being if you have one and only one `DialogHost` without an identifier. I would be happy to be wrong about it though so please let me know if there is a way I missed.

However, if using a code-behind is fine then it turns out there are a set of extension methods named `ShowDialog()` for `Window` and `DependencyObject` that allow you to show a `DialogHost` without having to know its identifier. Since those extension methods search the visual tree, it doesn't care what the identifier is and simply uses the first one it finds.

Hope that helps someone else that is surprised by this behavior.
