### ISSUE TITLE
PackIcon is not visible - in Xaml Designer

### ISSUE THREAD

**Issue by SID9-HoneyBee** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2264]
Suddenly PackIcon's images are not showing in my project

Even if you use version 4.0 or version 3.2, it is the same.

I changed the build platform from AnyCPU to x64.

Is it just the reason?

![image](https://user-images.githubusercontent.com/76090330/109520048-26b37680-7aef-11eb-8005-c244c2972a76.png)

**Comment by Keboo** [comment]
@SID9-HoneyBee yes I believe this is a designer not handling x64 as you indicated above. This seems very similar to issue #787. I would recommend using the [Provide Feedback](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019) option in VS studio to report it.
