### ISSUE TITLE
[Feature request] TextBox validation with INotifyDataErrorInfo

### ISSUE THREAD

**Issue by database64128** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2269]
I'm using `ReactiveUI.Validation` to create validation rules for text fields. It supports [invoking `INotifyDataErrorInfo` for validation errors](https://github.com/reactiveui/ReactiveUI.Validation#inotifydataerrorinfo-support). Can we add support for that?

**Comment by Keboo** [comment]
`INotifyDataErrorInfo` should already be supported. You can see an example of it working [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/MVVM/MVVM.Validation). It has been a while since I have worked with ReactiveUI, but I would expect that it should work with this library simply by implementing the `INotifyDataErrorInfo` on your view model.

**Comment by database64128** [comment]
It doesn't seem to work with ReactiveUI bindings. You can reproduce using [this example](https://github.com/reactiveui/ReactiveUI.Validation#inotifydataerrorinfo-support) with minor modifications:

``` cs
public class SampleViewModel : ReactiveValidationObject
{
    public SampleViewModel()
    {
        this.ValidationRule(
            viewModel => viewModel.Name, 
            name => !string.IsNullOrEmpty(name),
            "Name shouldn't be null or empty.");
    }

    [Reactive]
    public string Name { get; set; }
}
```

``` cs
public partial class SampleView
{
    public SampleView()
    {
        InitializeComponent();
        ViewModel = new SampleViewModel();
        this.WhenActivated(disposables =>
        {
            this.Bind(ViewModel,
                viewModel => viewModel.Name,
                view => view.nameTextBox.Text)
                .DisposeWith(disposables);
        });
    }
}
```

``` xaml
<TextBox x:Name="nameTextBox"
         materialDesign:HintAssist.Hint="Enter your name here"/>
```

**Comment by lszczygielek** [comment]
My tests shows that `INotifyDataErrorInfo` and ReactiveUi works with regular XAML binding. Please look at their demo application - I asked about it and waiting for answer.

**Comment by database64128** [comment]
@lszczygielek Thanks for the heads up! Found your question: reactiveui/ReactiveUI.Validation#237

**Comment by database64128** [comment]
Question answered in reactiveui/ReactiveUI.Validation#237.
