### ISSUE TITLE
PackIcon can't show in my project 

### ISSUE THREAD

**Issue by Wuhaotiandl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2273]
I build a new project based on .net framework.
![image](https://user-images.githubusercontent.com/49547887/110640367-b8a43900-81eb-11eb-834e-81d2d4261025.png)
only have four files about PackIcon.
Then I want to use in another project. So...
![image](https://user-images.githubusercontent.com/49547887/110640566-e9846e00-81eb-11eb-861d-51f893923e0d.png)
However, the icon can't show ? why? 
If I only want to use the icon, how can I finish it ?

**Comment by Keboo** [comment]
@Wuhaotiandl it looks like you are trying to copy the pack icon code into your own project to just use that portion of it. What it appears you are missing the in the implicit style for the `PackIcon` icon control that instructs WPF on how the class should be rendered. You can see the style and template [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/Generic.xaml#L926-L949)
