### ISSUE TITLE
Is there a tutorial about the source code?

### ISSUE THREAD

**Issue by Wuhaotiandl** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2274]
Hi, When I read the source code, sometimes I found some styles or custom controls are too complex to understand, Like progressbar, ripple ? Is there a tutorial about the source code ?

**Comment by Keboo** [comment]
There is not a tutorial on the source code. However I do [live streams](https://www.youtube.com/playlist?list=PLBaQgIdwD_9MGxU6TR2Rm0FlqII0mWDks) once a week, and many of them are related to work on this library. Is there a particular topic you are interested in? I did do one [live stream](https://www.youtube.com/watch?v=T4U9ce8J93Q) specific to creating custom controls and templates; perhaps that is helpful?

**Comment by Keboo** [comment]
Closing for now, let me know if there are specific questions you have on the code
