### ISSUE TITLE
materialDesign: *** Not  found

### ISSUE THREAD

**Issue by NeonOdyssey** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2275]
I have been having an issue lately I can't get `xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes/"` to work. 
![image](https://user-images.githubusercontent.com/45792245/110856458-8fe57780-82af-11eb-9271-6935132b6bfe.png)

This can be reproduced by having this as your app.xaml (with materialDesignThemes and materialDesignColors )

```
<Application x:Class="updater.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:updater"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes/"
             Startup="Application_Startup">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:CustomColorTheme BaseTheme="Dark" PrimaryColor="#00e6cb" SecondaryColor="#e962d1"/>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

</Application>
```

If you require a repo please let me know and I can create one quickly

**Comment by Keboo** [comment]
@NeonOdyssey yes a repo that reproduces the problem would be very helpful.

Does the app still compile and run? Typically most error codes that start with "X" are design-time only and don't affect the running of the application.

**Comment by NeonOdyssey** [comment]
@Keboo I have created a [repo ](https://github.com/PixelPerfect-Studios/Testing-App/) with this issue.

**Comment by Keboo** [comment]
Found the issue. The XML namespace should not end in the forward slash.
So change this:
```xaml
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes/"
```
to be:
```xaml
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
```

**Comment by NeonOdyssey** [comment]
Omg I feel like an idiot 😅

**Comment by Keboo** [comment]
:) no problem I missed it initially too.
