### ISSUE TITLE
DialogHost CloseOnClickAway region should include more space next to the dialog

### ISSUE THREAD

**Issue by TysonMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2279]
The `MaterialDesignDemo` project contains five `DialogHost` samples.  The fourth one supports closing when "clicking away", which means clicking on the dimmed background.  However, not all locations cause the `DialogHost` to close when clicked.  The set of such locations might even be inconsistent across executions though it does seem consistent during a particular execution.

This is not blocking me in any way.  Not only am I not using this feature in my application at work but it even worked correctly in that application after I added it out of curiosity.

**Comment by Keboo** [comment]
@TysonMN from testing it, it appears that the areas that do not dismiss the dialog are all of the locations around the dialog that contain (even a tiny amount) of the shadow. Does this match with what you are seeing (moving further away should dismiss)?

**Comment by TysonMN** [comment]
Oh, yes.  That seems to be it.  I should have been able to figure that out.  Thanks for testing and adding that comment.
