### ISSUE TITLE
Missing DialogHostContent when opening DialogHost for the second time in a large application

### ISSUE THREAD

**Issue by TysonMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2285]
If the XAML contains a sufficiently large number of elements with certain types, then the content of a `DialogHost` is not displayed when opening the `DialogHost` for the second time (as well as all times after that).  An additional constraint is that the `DialogHostContent` must bind its `Visibility` and have the value match the `IsOpen` property of the `DialogHost` (i.e. `true` means `Visible` and `false` means `Collapsed`).

Although this incorrect behavior involves `DialogHost`, my guess is that neither `DialogHost` nor any other part of Material Design in XAML Toolkit is to blame.  This feels like a bug in WPF to me.  I did not try to create a reproduction that does not involve `DialogHost`, but that is an interesting direction to pursue.  See the section title "Additional information" below.

## Steps to reproduce
1. Create a local fork of [TysonMN/MissingDialogHostContent](https://github.com/TysonMN/MissingDialogHostContent)
2. Checkout one of the following branches: [`CheckBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/CheckBox), [`ComboBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/ComboBox), [`RadioButton`](https://github.com/TysonMN/MissingDialogHostContent/tree/RadioButton), or [`TextBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/TextBox)
3. Run the application
4. Click the button (that says `Open Dialog`)
5. Observe the text in the dialog that says `Hello World`
6. Click on the dimmed background (but not too close in order to avoid bug #2279)
7. Click the button again

## Expected behavior
The text `Hello World` should be visible (again, just like in step 5).  It should look like this animated GIF, which I created using the branch [`main`](https://github.com/TysonMN/MissingDialogHostContent/tree/main).

![2021-03-19_11-59-29_566](https://user-images.githubusercontent.com/34664007/111816226-96c14b00-88aa-11eb-9443-f0d3228ed09f.gif)

## Actual behavior
The text `Hello World` is not visible.  The whole screen is dimmed.  This behavior continues each time the dialog is closed and reopened.  This animated GIF shows the actual behavior when using the branch `CheckBox`.

![2021-03-19_12-03-34_568](https://user-images.githubusercontent.com/34664007/111816711-25ce6300-88ab-11eb-9263-0483b5099263.gif)

## Additional information
To help quantify how large is "sufficiently large", my reproduction repository contains several branches named after a type that extends `FrameworkElement`.  Each branch forks from `main` and has two commits of its own.  In the first comment, many of the corresponding element are added to the application.  On these first commits, following the reproduction steps leads to the "expected behavior".  In the second commit, an additional element of the same type is added.  On these second commits, following the reproduction steps leads to the "actual behavior".  For each element type, here are the quantities that give the expected and actual behaviors.

| Element Type | Expected Behavior | Actual Behavior |
| --------------- | -------------------- | ----------------- |
| [`CheckBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/CheckBox) | 144 | 145 |
| [`ComboBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/ComboBox) | 48 | 49 |
| [`RadioButton`](https://github.com/TysonMN/MissingDialogHostContent/tree/RadioButton) | 144 | 145 |
| [`TextBox`](https://github.com/TysonMN/MissingDialogHostContent/tree/TextBox) | 72 | 73 |

I tried reproducing the actual behavior using other elements types, but the other cases were more confusing.  I have a private reproduction in my application at work that involves `Button`s with its `Style` set to some `StaticResource` key, but I was unable to achieve the actual behavior via `Button`s without modifying their `Style`.

## Workaround

I have found one workaround.  See the branch [workaround_GridWithHeightWidth](https://github.com/TysonMN/MissingDialogHostContent/tree/workaround_GridWithHeightWidth).  It wraps the `DialogHostContent` in a `Grid` that has a fixed `Height` and `Width`.

**Comment by Keboo** [comment]
Really great bug report. Thank you!

**Comment by TysonMN** [comment]
> I did not try to create a reproduction that does not involve `DialogHost`, but that is an interesting direction to pursue.

I have now done this.  See https://github.com/dotnet/wpf/issues/4319.
