### ISSUE TITLE
Weird behavior of Field Clear Buttons

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2298]
I have a StackPanel that contains multiple fields. The user can display or not the StackPanel with a button.
This video shows what I'm trying to do :

https://user-images.githubusercontent.com/54487782/114159471-1ed4c680-9926-11eb-9454-a27b7ebe82bc.mp4

The visibility is changed in the code behind, in the button click event, like this :
```
Private Sub Button_Click(sender As Object, e As RoutedEventArgs)
        If StackPanelExtendSearch.Visibility = Visibility.Visible Then
            StackPanelExtendSearch.Visibility = Visibility.Collapsed
        Else
            StackPanelExtendSearch.Visibility = Visibility.Visible
        End If
End Sub
```
I want my StackPanel to be hidden by default. So I set his visibility to Collapsed in the XAML code

`<StackPanel x:Name="StackPanelExtendSearch" Visibility="Collapsed">`

But when I do this, a weird behavior occurs. 
The clear buttons are displayed when there is no text in my fields :

https://user-images.githubusercontent.com/54487782/114161213-1aa9a880-9928-11eb-8a9c-2971da7f6f34.mp4

The buttons don't disappear when I click on them. But they disappear when I type some text and remove it.

https://user-images.githubusercontent.com/54487782/114161951-e7b3e480-9928-11eb-8fa9-16d9772b402f.mp4

However, if I set a visible visibility on my StackPanel, clear buttons work properly.
But it's not what I want. I want my StackPanel to be Collapsed by default

**So I found a way to bypass this bug :**
- Not set a visibility on my StackPanel in the XAML code
`<StackPanel x:Name="StackPanelExtendSearch">`
- And set the collapsed visibility on my StackPanel in the Load event of my UserControl
```
Private Sub UserControl_Loaded(sender As Object, e As RoutedEventArgs)
        StackPanelExtendSearch.Visibility = Visibility.Collapsed
        ...
End Sub
```

This solution solves the problem, but I don’t think the clear buttons behavior is normal.

**Comment by Keboo** [comment]
Thank you for the good writeup. Which version of the library are you currently using?
Will need to dig into it, but it does look like a bug.

**Comment by Xaalek** [comment]
Here are the packages I'm using:
![image](https://user-images.githubusercontent.com/54487782/115832481-3d9d8780-a413-11eb-9605-eadf5f62d2c5.png)
I'm using the last version for each one.

**Comment by Xaalek** [comment]
Update : I don't have this bug anymore. 
I'm closing the issue.
