### ISSUE TITLE
Issue regarding DialogHost not working correctly when reopening application.

### ISSUE THREAD

**Issue by jordyvanraalte** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2302]
I have an issue regarding the position of the DialogHost. The code of the dialog goes as follows:

```
<materialDesign:DialogHost
                x:Name="WarningDialog"
                IsOpen="{Binding IsConfigDialogOpen}"
                Grid.Row="1"
                Grid.ColumnSpan="4">
                <materialDesign:DialogHost.DialogContent>
                    <materialDesign:Card  Width="500" Height="350" VerticalAlignment="Center" HorizontalAlignment="Center" Background="{StaticResource Secondary}">
                        <StackPanel Orientation="Vertical">
                            <materialDesign:PackIcon VerticalAlignment="Center" Foreground="White" HorizontalAlignment="Center" Kind="Alert" Width="64" Height="64" Margin="0,10,0,0"/>
                            <TextBlock Text="Waarschuwing!" FontSize="28" TextAlignment="Center" Margin="0,10,0,0" Foreground="White"/>
                            <TextBlock FontSize="18" TextAlignment="Center" Foreground="White" Margin="0,25,0,0">
                            Het configuratiebestand is gewijzigd. <LineBreak />
                            Dit kan invloed op de centrifuge hebben. <LineBreak />
                            Bij het klikken van de onderstaande knop <LineBreak />
                            zal het configuratiebestand ingeladen worden.
                            </TextBlock>
                            <Button Width="300" Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" Content="Laad" Margin="0,40,0,0"/>
                        </StackPanel>
                    </materialDesign:Card>
                </materialDesign:DialogHost.DialogContent>
</materialDesign:DialogHost>
``` 

A grid where the dialog is in:
```
<Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="50"/>
                <RowDefinition Height="*"/>
            </Grid.RowDefinitions>
</Grid>
```

The problem is, that I have a background service that checks if a certain file is changed. When this file is changed, the application must show a dialog (the application isn't visible yet). On opening the application the dialog should be centred in the application. However, the dialog has some weird behaviour. If the application isn't opened very fast the dialog isn't centred. Working with 2 displays is resulted in seeing the dialog on the second display.
Expected behaviour:
![afbeelding](https://user-images.githubusercontent.com/33465848/114749518-4fb46180-9d53-11eb-9bae-3c343a11b24c.png)
Behaviour when minimalised for a few seconds and using a second display:
![afbeelding](https://user-images.githubusercontent.com/33465848/114749798-986c1a80-9d53-11eb-9469-e6005ba79edf.png)
Behaviour when minimalised with no second display available:
![afbeelding](https://user-images.githubusercontent.com/33465848/114750066-dc5f1f80-9d53-11eb-9905-4548ba812c06.png)

I already tried to place the dialoghost in the main component of my page, however that didn't solve the issue.

**Comment by Keboo** [comment]
I suspect the issue here is that the default DialogHost host uses a [custom Popup control](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/PopupEx.cs). This control attempts to watch the host window for changes and reposition itself accordingly. I suspect there is likely an issue in this area of the code where it likely end up with either a wrong size or position and end up out of place. 
If you spend a little effort going through the visual tree and grabbing a reference to the popup control directly, it does have a `RefreshPosition` method that could be invoked. I suspect a fix for this may involve having the `DialogHost` invoke this at some point.

Are you able to provide a sample that reproduces the issue?
