### ISSUE TITLE
Cannot set PackIcon Kind in a DataTrigger

### ISSUE THREAD

**Issue by NoahLavelle** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2305]
I am trying to set the kind of a packicon based on whether or not the window is maximized. 
           
```
<materialDesign:PackIcon.Style>
    <Style TargetType="{x:Type materialDesign:PackIcon}">
        <Style.Triggers>
            <DataTrigger Binding="{Binding WindowState, RelativeSource={RelativeSource AncestorType=Window}}" Value="Normal">
                  <Setter Property="Kind" Value="WindowMaximize" />
               </DataTrigger>
           </Style.Triggers>

           <Setter Property="Kind" Value="WindowRestore" />
        </Style>
</materialDesign:PackIcon.Style>
```

I have this XAML, which works when the program is run but errors in Visual Studio editor. The error reads:
```The property "Kind" is not a dependency property. To be used in markup non-attached properties must be exposed on the target type with an accessable instance property "Kind". For attached properties, the declaring type must provide static "GetKind" and "SetKind" methods```

**Comment by Keboo** [comment]
This often a Visual Studio designer issue. However, in the latest version we have worked around the designer issue by making it a non-generic class. 

Can you provide your Visual Studio version and the version of this library you are using?

**Comment by NoahLavelle** [comment]
I am using Visual Studio Community 2019 16.9.4 and I am using version 0.1.6 of this library

**Comment by Keboo** [comment]
It looks like the problem is likely an VS designer issue with the `<Style TargetType="{x:Type materialDesign:PackIcon}">` if you drop the `x:Type` and just let the type converters handle it, it appears that will make the designer happier.
```XAML
<materialDesign:PackIcon.Style>
    <Style TargetType="materialDesign:PackIcon">
        <Style.Triggers>
            <DataTrigger Binding="{Binding WindowState, RelativeSource={RelativeSource AncestorType=Window}}" Value="Normal">
                  <Setter Property="Kind" Value="WindowMaximize" />
               </DataTrigger>
           </Style.Triggers>

           <Setter Property="Kind" Value="WindowRestore" />
        </Style>
</materialDesign:PackIcon.Style>
```
