### ISSUE TITLE
ComboBox control does not support virtualization

### ISSUE THREAD

**Issue by beefsteak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2307]
The combobox loading large amounts of data can cause the interface to freeze,I guess there is no support for  "VirtualizingStackPanel" in the style, Would you consider supporting this feature?

**Comment by Keboo** [comment]
This is already supported. You can see an example of it in the [demo application](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/ComboBoxes.xaml#L159-L182)
