### ISSUE TITLE
Add PlacementMode to DialogHost

### ISSUE THREAD

**Issue by Drise13** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2316]
Conversation context: https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit?at=609183bc963923553ae2d4d4

I'm looking for a way to control the placement of the dialog popup. Currently it seems to always center. For my application I'm looking for a `Top` mode, but I image other standard modes would be useful as well.

**Comment by MichelMichels** [comment]
Resolved with PR.
