### ISSUE TITLE
Menus have no shadow.

### ISSUE THREAD

**Issue by wdefender** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2320]
Menus have no shadow. The screenshot ist taken with Version 4.0.0 DemoApp, but latest sourcecode also behaves like this.
Testet with windows 10 Version 20H2. 
To fix it you probably have to add `margin=4` in materialdesigninxamltoolkit\materialdesignthemes.wpf\themes\materialdesigntheme.menu.xaml, eg. `<Border x:Name="SubMenuBorder" Margin="4" Background="{Binding Path=Background, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=MenuBase}}" Effect="{DynamicResource MaterialDesignShadowDepth1}" CornerRadius="2">`

![MenuWithoutShadow](https://user-images.githubusercontent.com/62835012/117796452-64e7b780-b24f-11eb-8229-417ac0795f3b.png)

**Comment by Xaalek** [comment]
You need to enable "Show shadows under windows" in the Windows Performance Options.

**Comment by Keboo** [comment]
Appears fixed in latest code.
![image](https://user-images.githubusercontent.com/952248/133910679-9c8e2546-fa4b-4679-939c-bdd499d9e2ec.png)
