### ISSUE TITLE
No loaded DialogHost instances when dialoghost is in root

### ISSUE THREAD

**Issue by jf-dynamics** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2321]
I am trying to add a reusable dialog host to my test app.
But unfortunately, the app always throws a **'No loaded DialogHost instances.'** exception.

The code is very simple.

**MainWindow.xaml**

```
    <views:MvxWindow
        ...
        >
        <materialDesign:DialogHost Identifier="RootDialog" />
    </views:MvxWindow>

```
**MainWindow.xaml.cs**

```
    public partial class MainWindow : MvxWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
```

**DashboardView.xaml**

```
    <views:MvxWpfView
         ...
         >
         ...
         <Button Content="ShowDialog"
                 Click="OnClick_ShowDialogAsync" /> 
         ...
    </views:MvxWpfView>
```

**DashboardView.xaml.cs**

```
    public partial class DashboardView : MvxWpfView
    {
                public HomeView()
                {
                    InitializeComponent();
                }
        
                private async void OnClick_ShowDialogAsync(object sender, RoutedEventArgs e)
                {
                    var view = new SampleDialog
                    {
                        DataContext = new SampleDialogViewModel()
                    };
        
                     await DialogHost.Show(view, "RootDialog", ExtendedOpenedEventHandler, ExtendedClosingEventHandler);
                }
    
                ...
    }
```

When I put this line:

`<materialDesign:DialogHost Identifier="RootDialog" />`

inside the **DashboardView.xaml** it works fine.

**Comment by jf-dynamics** [comment]
please see sample app on this repo to reproduce the above issue. https://github.com/jf-dynamics/SampleWPF

**Comment by Keboo** [comment]
Hi @jf-dynamics the issue is with how MvvmCross works. When it runs it replaces any window content that you may have specified. If you check your Window's `Content` property at the end of the constructor, you will see that it is an instance of `DashboardView` and not the `Grid` like what you specified in MainWindow.xaml.
