### ISSUE TITLE
Setting theme isn't working as expected when loading the Resources from a Window.

### ISSUE THREAD

**Issue by izzylys** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2322]
Hello!

I'm attempting to rework an app to _not_ put theme resource dictionaries in the `Application.Current.Resources` as the app is hosted within another app and adding themes affects all other apps within the host. To do this, I've simply added the  `Generic.xaml` to each user control's merged dictionaries.

This has all worked fine enough except when it comes to switching between light and dark themes. It seems that some text, cards, and text box outlines are now not being affected.

This is how I'm changing the theme since I can't use the `PaletteHelper` anymore. A bit hack-y I think to save a global handle on the resource dict, but honestly I wasn't really sure how else to do it in this situation... 😅
https://github.com/specklesystems/speckle-sharp/blob/9205be9bc33425fe9e64a9e3dc89a111f002551e/DesktopUI/DesktopUI/Settings/SettingsViewModel.cs#L88-L104

I also upgraded to the latest versions of the toolkit and colours to see if maybe it was a fixed issues, but I'm getting the same results.

Here's what it looks like
![dark themeing](https://user-images.githubusercontent.com/7717434/118254934-85a84b00-b4a3-11eb-86b1-428041536a13.gif)

And the project is [here](https://github.com/specklesystems/speckle-sharp/tree/izzy/desktopui-themes/DesktopUI) if you would like to run it (just run the `DesktopUI` proj within this repo). The `master` branch is how it worked before, and the linked branch is with the changes I've made.

Any advice on how to solve this or perhaps any guidance on a different approach would be really appreciated! Thanks in advance for your time ✨

**Comment by Erapchu** [comment]
Hello! You don't need to merge in Generic.xaml dictionary into your code in every user control. It should be merged automatically as far as I know in the same .dll library where controls/windows are exist. You can create something like ThemeManager or ThemeService and manipulate theme with it.
Master branch is ok, but Generic.xaml shouldn't be everywhere.

**Comment by izzylys** [comment]
Hey @Erapchu!

Thanks for responding, however I don't think that's true - at least not for my case. If I remove `Generic.xaml` from one of my user controls, the app does not launch due to `XamlParseExceptions`.

**Comment by izzylys** [comment]
Heya, the `Generic.xaml` contains all the material design themes (you can see it [here](https://github.com/specklesystems/speckle-sharp/blob/9205be9bc33425fe9e64a9e3dc89a111f002551e/DesktopUI/DesktopUI/Themes/Generic.xaml)). What I want is to apply these themes and swap between light and dark as you can see from the gif. 

I _don't_ want to put the theme resources in `Application.Current.Resources` which is what is happening on `master`. The code on `master` is breaking other applications within the host which is why I'm trying to change it on the branch I linked.

**Comment by Erapchu** [comment]
What is other applications within the host?
All shared dynamic resources (Colors for black/light theme) in this App instance are single.
I can answer later. Please, if you have some time, let me understand your project structure )

**Comment by izzylys** [comment]
Heya!

The other applications are out of our control, but it is common for them to be other unrelated WPF applications. This means I cannot put the theme resources in `Application.Current.Resources` because this will cause material design styling to be applied to the unrelated applications. Adding the theme resources to each window and user control works fine though! I am happy with this solution unless you have a better suggestion for where to add the resources?

The problem is that switching between the themes does not work nicely as you can see in the gif and I'm not really sure why. If you or anyone else can help me understand what is causing this, that would be super helpful!

**Comment by Keboo** [comment]
I pulled down the code and took a look. The issue is with your Themes\Generic.xaml resource dictionary. It is included in both your RootView.xaml as well as in your AllStreamsView.xaml. This is causing the issue when you switch themes because when you call SetTheme you are effectively changing out the theme brush resources at the RootView.xaml, however because AllStreamsView.xaml has its own copy of the brushes that have the same x:Key. When things like the card use DynamicResource to look up the brush, they will stop at the first instance of the brush they find; which in this case is the ones in AllStreamView.xaml.

Hope that helps.

**Comment by izzylys** [comment]
Hi @Keboo, thanks a lot for having a look - your explanation makes sense and I understand now why this wasn't working as expected! Much appreciated 👍

Do you have a suggestion on how the reference the `Generic.xaml` in each of the views in this scenario where there is no `App,xaml` and I can't use the `Application.Resources`? I've been struggling for a while now trying to find a workaround and thought adding the `Generic.xaml` to each user control would be it 😬

**Comment by Keboo** [comment]
I think I would suggest separating out two different type of resources you have; specifically separating color theming resource and style resource. Or to put it differently, separate the resources that are referenced as `DynamicResource` (Brushes, colors, etc) vs `StaticResource` (Styles, Templates, etc). 

Then in your `RootView.xaml` merge in both resources dictionaries. Then on other controls/xaml files you can bring in just the "static resource" resource dictionary without breaking color theming. 

You could take it a bit further as well and separate out the styles that have implicit style keys and only include those in your `Generic.xaml` and put the ones with specific keys in one or more resources dictionaries that can be merged in when they are needed.

**Comment by izzylys** [comment]
Thanks a lot for the advice - I tried this out and reworked some of my styling to accommodate the fact that I no longer have direct access to the Dynamic Resources and it works perfectly now!

Really appreciate your help on this issue 🎉
