### ISSUE TITLE
[TimePicker] - Error "Cannot create an instance of "TimePicker" in xaml designer

### ISSUE THREAD

**Issue by AlexinaO** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2324]
Hello Everybody,

This morning, I have the error mentionned in title in xaml designer in VS2019 associated to the error in error list "Can only base on a style with target type that is base type "clock".
I tried an update of the package nuggets but I have the same problem.

Thus I reinstall the old packages which worked fine yesterday
Packages used : MaterialDesignColors 1.2.7 and MaterialDesignThemes.wpf 3.2.0.

I rebuild my project but nothing, I clean and build and rebuild but the error remains.

What is weird is that time picker works fine when I start my project : I can see it, and set hour.

My code where I used TimePicker
`<GroupBox>
								<GroupBox.Header>
									<TextBlock Text="{DynamicResource TriggerTime}" FontWeight="Bold"/>
								</GroupBox.Header>
								<Grid>
									<materialDesign:TimePicker x:Name="tp_selectedHour"
															   Is24Hours="True" Language="fr-FR"
															   SelectedTimeFormat="Long" 
															   Text="{Binding Path=HourPeriodicity, UpdateSourceTrigger=Explicit}">
									</materialDesign:TimePicker>
								</Grid>
							</GroupBox>`

and of course in the window I declared material design like this
`xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"`

If you have a solution to see again the timepicker in xaml designer, please let me know.

For information, my project is in another project which have material design packages in the references.

Thank you per advance.
Alexina

**Comment by MichelMichels** [comment]
Are you still having this issue? I tried your code and as of now, this seems to be working fine.

**Comment by MichelMichels** [comment]
Closed due to inactivy and seemingly fixed.
