### ISSUE TITLE
Padding in MaterialDesignOutlinedTextBox

### ISSUE THREAD

**Issue by nelsonasousa** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2325]
Hi,
I'm trying to change the "Padding" property in MaterialDesignFloatingHintTextBox like this:

`    <Style x:Key="TextBoxTema" TargetType="{x:Type TextBox}" BasedOn="{StaticResource MaterialDesignOutlinedTextBox}">
      <Setter Property="Padding" Value="8"/>
<Setter Property="Background" Value="White"/>
</Style>`

But the "Padding" specification is not changed and I have to change it directly in the TextBox:
`<TextBox x:Name="TxtPathRetorno" 
                                 materialDesign:HintAssist.Hint="PASTA RETORNO" 
                                         materialDesign:HintAssist.Background="Transparent"
                                         Style="{StaticResource TextBoxTema}" 
                                         Padding="8"
                                 Width="320"/>`

However, if I do the same procedure for MaterialDesignOutlinedComboBox, it works perfectly:
`                                    <ComboBox x:Name="CboCNAB" 
                                  materialDesign:HintAssist.Hint="CNAB"
                                  Width="100"                                         
                                 materialDesign:HintAssist.Background="Transparent"
                                         Style="{StaticResource ComboBoxTema}"/>
`

Any idea how I should proceed? Thank you all!

**Comment by Keboo** [comment]
This should now be resolved. You can see the section in the demo app "Fields Line Up" as the UI test that these all work

**Comment by Int32Overflow** [comment]
@nelsonasousa Have you tested if it works for you now? I have the same problem, but for some reason it doesn't work with the new version either.
