### ISSUE TITLE
Add new ListBox style to make Navigation Bar like spec

### ISSUE THREAD

**Issue by StefanoRivolta-Previero** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2334]
https://material.io/components/navigation-drawer#usage

![firefox_jJKFdMgRYr](https://user-images.githubusercontent.com/58171461/119635452-fe989280-be13-11eb-8028-d9351400fb9a.png)

There should be a ListBox style that allows you to set selection colors and corner radius easily, so that something like the spec control can be achieved easily.

Also should be able to recreate navigation bars similar to those used by Google, eg:
![firefox_TPHXAoyRbp](https://user-images.githubusercontent.com/58171461/119636737-39e79100-be15-11eb-8ea6-7c42cb8ce7bd.png) ![firefox_gXZTo7MAZI](https://user-images.githubusercontent.com/58171461/119636650-20464980-be15-11eb-8efe-559dd37f5781.png)

**Comment by Xaalek** [comment]
I know it already exists in https://github.com/spiegelp/MaterialDesignExtensions
Maybe we should implement those control in MaterialDesignInXaml.
