### ISSUE TITLE
Dialog content background color is always white

### ISSUE THREAD

**Issue by igowshik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2337]
![image](https://user-images.githubusercontent.com/27288163/119674680-b0e45000-be3c-11eb-995e-910e93be4d21.png)
 Dialog content background is by default "MaterialDesignCardBackground". 
 Is there a way to override it ?

**Comment by StefanoRivolta-Previero** [comment]
If you only want to change the color, you can simply wrap all the content in a Grid, and change the Grid's background, like so:

![immagine](https://user-images.githubusercontent.com/58171461/119776991-eda85980-bec5-11eb-936c-737b4972a949.png) 
![immagine](https://user-images.githubusercontent.com/58171461/119777049-fe58cf80-bec5-11eb-9604-3c6341ed982d.png)

If instead you want the background to be transparent, I don't think it's possible right now.

**Comment by igowshik** [comment]
I do not use explicit color for the outermost element for this purpose. The expected result is like in the attached image below. 
Is it possible to achieve this ?

![image](https://user-images.githubusercontent.com/27288163/119823934-a46ffe00-bef5-11eb-8226-e1dcc90d5ce7.png)

**Comment by StefanoRivolta-Previero** [comment]
Right now I don't think so, but I see there's a PR (#2236) to fix this issue, so maybe next release?

**Comment by Keboo** [comment]
Hi @igowshik this is technically achievable today though the process is not very obvious, a little hacky, and there is a bit of a performance hit to enable it. Assuming you are using the default DialogHost style (and not the embedded one), what you want to do is make the dialog's popup control transparent. You then also need to modify the popup's background color to also be transparent (not something that is currently exposed) This will then allow you to put in content and achieve non-uniform edges; like that little right chevron in your screenshot. [I have a sample of doing this](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.CornerRadius) to enable non-uniform corner radiuses on the dialog host but could be reapplied to achieve any look you want for the dialog.

The PR #2236 probably needs to be revisited as well. The basic idea of it (to expose the background of brush for the popup's content) is good but the implementation needed some work and needed to get applied to the embedded style as well. Likely not too difficult to implement.
