### ISSUE TITLE
Mouse over animations on Contained Buttons are too long

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2339]
https://material.io/components/buttons
Compared to Material Design Specs, I find that the animation of the Contained Buttons (Raised buttons and FloatingAction buttons) is too long. Okay that’s a detail but every time I use these buttons I feel like my app is laggy. When in reality it is just the animation that is too long. I think it would be preferable for the mouse over animation to be instantaneous such as the FlatButtons and the OutlinedButtons.

**Comment by Erapchu** [comment]
Hello! Yes, it can be changed. So, if comparing with Specs, then need to improve animations for Ripple element too. They a little bit different, but let's start from your suggestion.

**Comment by Xaalek** [comment]
I have isolated the mouse over animation code from material.io.
You can check the result here https://xaalek.w3spaces.com/saved-from-Tryit-2022-03-21-n3xl2.html?bypass-cache=74310593
I'm trying to improve the animation in the library but I don't know if there is an equivalent in WPF for the function [cubic-bezier](https://www.w3schools.com/cssref/func_cubic-bezier.asp)
