### ISSUE TITLE
ComboBox within Menu Not Working Properly (v4.1.0)

### ISSUE THREAD

**Issue by drepamig** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2340]
Repo with demo of issue: `https://github.com/drepamig/MaterialDesignInXamlToolkit_ComboBox_in_Menu_Issue.git`

Hello, 

First off, thank you for a great project!

I noticed a possible regression in v4.1.0 since the issue is not present in v4.0.0. If you change the NuGet reference in the project linked above to `<PackageReference Include="MaterialDesignThemes" Version="4.0.0" />`, the behaviors return to normal.

**Quick summary:** If you place a ComboBox into a menu item with either the default inherited style or by explicitly defining `MaterialDesignComboBox` or `MaterialDesignFloatingHintComboBox`, you cannot make a single-click selection (i.e. click once to open the ComboBox and then click again to choose). You can make selections by click-and-hold.

While creating the demo for this issue, I noticed another issue. If you place a ComboBox with a style from `MaterialDesignFilledComboBox` or `MaterialDesignOutlinedComboBox`, the selection method works correctly but the selected item does not display in the ComboBox. 

I added a 3rd menu item with ComboBox having a style of `{x:Null}` to show that the unstyled ComboBox works normally. Additionally, I included a three ComboBoxes in a row below the menu to show they have normal behavior when not within a Menu.

**Comment by Keboo** [comment]
It appears that #2315 is the culprit for this issue. Will need to revisit that fix and add a test for this case. Thank you for the nice reproduction.
