### ISSUE TITLE
IconButton style replaces the background when mouse is over

### ISSUE THREAD

**Issue by StefanoRivolta-Previero** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2342]
When the mouse is over a MaterialDesignIconButton with a set background, like in the Demo app, the background gets swapped with a hard coded color (MaterialDesignFlatButtonClick), like this:
![o6RJRtf5t7](https://user-images.githubusercontent.com/58171461/120664278-19f64400-c48b-11eb-91eb-c677c5a73f8b.png) ![v4fCCiYQXm](https://user-images.githubusercontent.com/58171461/120664282-1b277100-c48b-11eb-9e3d-4fab1610d433.png)

![Q1V1HrSRB8](https://user-images.githubusercontent.com/58171461/120664437-35f9e580-c48b-11eb-89d2-39a7c1755327.png) ![L1gRgudDtQ](https://user-images.githubusercontent.com/58171461/120664446-36927c00-c48b-11eb-8a50-1bc6a5a8008d.png)

In my opinion it should be an overlay, maybe using the button foreground, like this:

![WCQjjvwQnV](https://user-images.githubusercontent.com/58171461/120665797-63935e80-c48c-11eb-974e-3f25ed228268.png) ![c81KiEUzQA](https://user-images.githubusercontent.com/58171461/120665807-642bf500-c48c-11eb-894d-a1c526385f6e.png)
![k09GKODsJb](https://user-images.githubusercontent.com/58171461/120665817-6726e580-c48c-11eb-9243-c2f52a4e44ef.png) ![ExIdWosc4x](https://user-images.githubusercontent.com/58171461/120665823-67bf7c00-c48c-11eb-86c2-7de8a668a6ba.png)
![Ytzsibgbkj](https://user-images.githubusercontent.com/58171461/120665827-68f0a900-c48c-11eb-8e9a-58fb3a139efa.png) ![s4wCX8wMYT](https://user-images.githubusercontent.com/58171461/120665835-6a21d600-c48c-11eb-8b7a-b3a02d6bbc95.png)

**Comment by Keboo** [comment]
Agreed, this is also inline with the [spec for the "TextButton"](https://material.io/components/buttons#text-button) which is what this is modeled after.
![image](https://user-images.githubusercontent.com/952248/122108644-471eec80-cdd1-11eb-8387-1ed3abdbf694.png)
