### ISSUE TITLE
Textbox showing char count and max length

### ISSUE THREAD

**Issue by Jonesie** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2345]
In v 4.1 Im seeing a character count / maxlength thing under text boxes:

![Screenshot from 2021-06-09 13-44-20](https://user-images.githubusercontent.com/3420249/121280106-d2a80180-c929-11eb-912b-517cf99dc90f.png)

This was not there in v 3.  I dont know what this is called so maybe it's a new feature but I really want it gone.

XAML is:

```
            <TextBox Margin="4 0" MaxLength="8"
              VerticalAlignment="Center"
               Visibility="{Binding Disconnected, Converter={StaticResource BoolToVis}}" Width="120">
              <Binding Path="ConnectionCode" UpdateSourceTrigger="PropertyChanged"/>
            </TextBox>
```

**Comment by Keboo** [comment]
There is an attached property you can set on the TextBox to hide it:
```XAML
materialDesign:TextFieldAssist.CharacterCounterVisibility="Collapsed"
```

Related: #2247

**Comment by Jonesie** [comment]
> There is an attached property you can set on the TextBox to hide it:
> 
> ```
> materialDesign:TextFieldAssist.CharacterCounterVisibility="Collapsed"
> ```
> 
> Related: #2247

Sweet thank u
