### ISSUE TITLE
Custom ValidationRule not firing

### ISSUE THREAD

**Issue by Frago9876543210** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2351]
**Demo repository that requires only nuget packages: [CustomValidationRuleEx](https://github.com/Frago9876543210/CustomValidationRuleEx)**

While creating custom validation rule I noticed that it fired only when application started. Then breakpoints are not called in that class:
```cs
using System.Globalization;
using System.Windows.Controls;

namespace CustomValidationRuleEx.Rules
{
    public class LoginValidationRule : ValidationRule
    {
        public override ValidationResult Validate(object value, CultureInfo cultureInfo)
        {
            return string.IsNullOrWhiteSpace((value ?? "").ToString()) //break point here
                ? new ValidationResult(false, "Login is required.")
                : ValidationResult.ValidResult;
        }
    }
}

```
If you try to type something validation rule also doesn't update
![image1](https://user-images.githubusercontent.com/13465245/121909091-471dde80-cd36-11eb-94b6-2481772ae3a2.png)

XAML code:
```xml
<TextBox
	x:Name="LoginTextBox"
	materialDesign:HintAssist.Hint="Login"
	materialDesign:HintAssist.IsFloating="True"
	Margin="10,12,10,10">
	<TextBox.Text>
		<Binding
			Path="Name"
			UpdateSourceTrigger="PropertyChanged">
			<Binding.ValidationRules>
				<domain:LoginValidationRule
					ValidatesOnTargetUpdated="True"
					xmlns:domain="clr-namespace:CustomValidationRuleEx.Rules"/>
			</Binding.ValidationRules>
		</Binding>
	</TextBox.Text>
</TextBox>
```

**Comment by Keboo** [comment]
The issue here is that the binding is failing so it never invokes the validation rule a second time. For binding to function it needs some value to actually bind to. For your example you can see this start to work if you do the following:
```C#
public partial class LoginPage : Page
{
    public LoginPage()
    {
        InitializeComponent();
        DataContext = new ViewModel();
    }
}

public class ViewModel
{
    public string Name { get; set; }
}
```

Note that though the above should be sufficient to see the validation rule function, for a real view model class you would likely want it to implement `INotifyPropertyChanged` or leverage some MVVM library.
