### ISSUE TITLE
Can anyone tell me how this space is made like this, can have a start and end time

### ISSUE THREAD

**Issue by wuhl508159280** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2354]
Can anyone tell me how this space is made like this, can have a start and end time[https://i.stack.imgur.com/huVkt.png](url)

**Comment by Keboo** [comment]
@wuhl508159280 that looks like a something that is built with the Calendar control. You can see some sample usage of it in the [demo app](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases) on the [Pickers page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Pickers.xaml).
