### ISSUE TITLE
Add ability to change Button animation duration + add OnHover animation

### ISSUE THREAD

**Issue by xMaxximum** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2355]
Hello, 
as the title suggests, this is a feature request. Right now the animations are too long for me. I would like to be able to change the animation duration. Also I would like to be able to create a OnHover animation.

Kind regards,

maxximum

**Comment by Keboo** [comment]
This looks like it is closely related to #2339 

As far as applying a hover animation, this is likely best done as part of a visual state transition. Unfortunately doing one of these would require copying in the existing template into your project and editing it to suit your needs (WPF templates are mostly an all or nothing situation).

**Comment by xMaxximum** [comment]
> As far as applying a hover animation, this is likely best done as part of a visual state transition.
How could I do this? 

> would require copying in the existing template into your project and editing it to suit your needs
I don't really see the problem when you can just expose the animation duration so the user could set it himself, but how would I proceed with copying the existing template then and then using my own?

**Comment by Xaalek** [comment]
The issue can be closed
