### ISSUE TITLE
How should I use the date control?

### ISSUE THREAD

**Issue by L-MAX6** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2358]
Gray button, no response when clicked,Where is this resource?
` Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"`

my code:
> ` <StackPanel Orientation="Horizontal">
                <TextBlock
                        Text="{Binding Date, StringFormat={}{0:yyyy-MM-dd HH:mm:ss}}"
                        VerticalAlignment="Center"
                        FontSize="24"/>
                <Button
                        Margin="8 0 0 0"
                        Content="..."
                        Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"
                        materialDesign:DialogHost.DialogOpenedAttached="CombinedDialogOpenedEventHandler"
                        materialDesign:DialogHost.DialogClosingAttached="CombinedDialogClosingEventHandler">
                    <Button.CommandParameter>
                        <Grid Margin="-1">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="*"/>
                                <RowDefinition Height="Auto"/>
                            </Grid.RowDefinitions>

                            <StackPanel
                                    Grid.Row="0"
                                    Orientation="Horizontal">
                                <Calendar
                                        x:Name="CombinedCalendar"
                                        Margin="-1 -4 -1 0"/>

                                <materialDesign:Clock
                                        x:Name="CombinedClock"
                                        DisplayAutomation="CycleWithSeconds"
                                        Is24Hours="True"/>
                            </StackPanel>

                            <StackPanel
                                    Grid.Row="1"
                                    Margin="8"
                                    HorizontalAlignment="Right"
                                    Orientation="Horizontal">
                                <Button
                                        Style="{DynamicResource MaterialDesignFlatButton}"
                                        Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}"
                                        CommandParameter="0"
                                        Content="CANCEL"/>

                                <Button
                                        Style="{DynamicResource MaterialDesignFlatButton}"
                                        Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}"
                                        CommandParameter="1"
                                        Content="OK"/>
                            </StackPanel>
                        </Grid>
                    </Button.CommandParameter>
                </Button>
            **</StackPanel>`**

**Comment by Keboo** [comment]
This looks like it is likely related to your usage of the `OpenDialogCommand`. I posted an update to the [wiki with details](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Routed-Commands).
