### ISSUE TITLE
When switching themes, some control fonts do not change color

### ISSUE THREAD

**Issue by HuMingYi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2360]
![{7ffaab9e-745f-40fb-b20d-9a3598a91667}](https://user-images.githubusercontent.com/49670368/124089218-47cca980-da86-11eb-9602-7036344dc92a.png)
![{f4b5e2af-188e-4144-8b80-c6d6230e7ea6}](https://user-images.githubusercontent.com/49670368/124089294-5b781000-da86-11eb-9739-8a945708a932.png)
Why do some fonts change color with the theme and the red area I marked doesn't?

**Comment by Keboo** [comment]
Hi @HuMingYi is that the normal demo application (I only ask because parts of the UI don't line up with what I am seeing).

There was a bug in the demo application where those TextBlocks were not properly using the `MaterialDesignBody` brush. I have just pushed up a fix for that.

**Comment by HuMingYi** [comment]
![{85457c82-6faa-4c85-b458-30b0a19f4e4a}](https://user-images.githubusercontent.com/49670368/124708557-0415ec00-df2d-11eb-9ffc-462dfff686ad.png)
![{9c58989e-3118-4865-a3d1-8f4dfebdd256}](https://user-images.githubusercontent.com/49670368/124708567-0710dc80-df2d-11eb-9782-3fdc2f3c0e03.png)

@Keboo In the demo, it behaved normally

This is my profile
`<Application x:Class="MaterialDesignInXamlDemo.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:MaterialDesignInXamlDemo"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                <ResourceDictionary>
                    
                    <ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.Indigo.xaml" />
                        
                        <materialDesign:BundledTheme BaseTheme="Inherit" PrimaryColor="DeepPurple" SecondaryColor="Lime"
                                             ColorAdjustment="{materialDesign:ColorAdjustment}" />

                    </ResourceDictionary.MergedDictionaries>
                    
                    <SolidColorBrush x:Key="PrimaryHueLightBrush" Color="{StaticResource Primary200}"/>
                    <SolidColorBrush x:Key="PrimaryHueLightForegroundBrush" Color="{StaticResource Primary200Foreground}"/>
                    <SolidColorBrush x:Key="PrimaryHueMidBrush" Color="{StaticResource Primary500}"/>
                    <SolidColorBrush x:Key="PrimaryHueMidForegroundBrush" Color="{StaticResource Primary500Foreground}"/>
                    <SolidColorBrush x:Key="PrimaryHueDarkBrush" Color="{StaticResource Primary700}"/>
                    <SolidColorBrush x:Key="PrimaryHueDarkForegroundBrush" Color="{StaticResource Primary700Foreground}"/>
                </ResourceDictionary>

               
                <ResourceDictionary>
                    
                    <ResourceDictionary.MergedDictionaries>
                        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Yellow.xaml" />
                    </ResourceDictionary.MergedDictionaries>

                    
                    <SolidColorBrush x:Key="SecondaryHueMidBrush" Color="{StaticResource Accent200}"/>
                    <SolidColorBrush x:Key="SecondaryHueMidForegroundBrush" Color="{StaticResource Accent200Foreground}"/>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

**Comment by HuMingYi** [comment]
@Keboo What is the version of the fix?

**Comment by Keboo** [comment]
I just push the change an hour ago. It hasn't gone out in a released version yet. You can see the change [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/35707ac9a990192e3e04a1627dbaf59067992638)

**Comment by HuMingYi** [comment]
@Keboo Thank you very much for your reply
