### ISSUE TITLE
Color adjustment in light mode with light colors doesn't work properly

### ISSUE THREAD

**Issue by StefanoRivolta-Previero** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2361]
When selecting light colors like yellow and teal in Light Mode, the colors become distorted like so:
![RMXqEH4Urb](https://user-images.githubusercontent.com/58171461/124091085-bfceab80-da55-11eb-9809-e540a8ed7909.png)

While, when I remove the `ColorAdjustment="{materialDesign:ColorAdjustment}"` from App.xaml, the colors work properly:
![MaterialDesignDemo_2OPUzzu19Y](https://user-images.githubusercontent.com/58171461/124091207-de34a700-da55-11eb-9e42-05c957c9bbdf.png)

Is this an intended behavior?

**Comment by Keboo** [comment]
Intended yes, but certainly not obvious. There was a feature that was added in the [4.0.0 release](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2106) that does automatic color correction to ensure that proper contrast between the foreground and background colors is maintained. This is an opt-in feature that you can set [and the demo app has it on by default](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml#L16).

However you do raise a good concern that there should probably be something in that UI that enables turning the feature on and off to make it more obvious what is happening.
