### ISSUE TITLE
Expander hittable area reduced

### ISSUE THREAD

**Issue by jdbriaris** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2364]
Prior to v4 it was possible to select any area of an expander and have it expand, i.e. the green box shows the area I can hit to have the expander open in v3 of the demo

![image](https://user-images.githubusercontent.com/9742752/124617678-09146600-de6f-11eb-9564-b769e9604e79.png)

With the latest version this appears to have been reduced to

![image](https://user-images.githubusercontent.com/9742752/124617888-36611400-de6f-11eb-9d8d-a404dc337c0f.png)

Is this the desired behaviour? I can't see anything on the material design io stipulating this in terms of behaviour and imo this degrades UX.

**Comment by Keboo** [comment]
This is likely an accidental bug.
