### ISSUE TITLE
Hi, If I only want to use button and card designs, how do I do it?

### ISSUE THREAD

**Issue by mummyildiz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2365]
When using MahApp in a project, I want to use button and card objects as a design. MaterialDesignInXamlToolkit affects all objects when I add it to the project.

that didn't happen;
![image](https://user-images.githubusercontent.com/5136066/124641569-894ec180-de97-11eb-82b9-8bc5ca1968b8.png)

**Comment by Erapchu** [comment]
Hello! You can define resource dictionaries and bundled theme in your Window/UserControl only resources and set Material Design styles for your button(s) and Card control.

**Comment by Erapchu** [comment]
MahApps Controls.xaml contains pre-defined set of resource dictionaries and default styles for controls. You need to remove Controls.xaml first and use only 

<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.Buttons.xaml" />
<Style x:Key="{x:Type Button}" BasedOn="{StaticResource MahApps.Styles.Button}" TargetType="{x:Type Button}" />

All other controls will be with default styles.

**Comment by mummyildiz** [comment]
Inspired by you, I tried this way. Worked
thank you

![image](https://user-images.githubusercontent.com/5136066/124704065-1deb0b00-defc-11eb-8e15-ee9444575b01.png)
