### ISSUE TITLE
On some computers without advanced graphic cards, the components transitions animation slow significantly the application. Is it possible to disable it or faster it ?

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2372]
On some computers without advanced graphic cards, the components transitions animation slow significantly the application. Is it possible to disable it or faster it ?

**Comment by Keboo** [comment]
This is a bit of a complicated answer. This is not the first time some animation/performance issues have come up. There are several things that can/do slow it down (see the linked #2377 for one example). 

There is a `TransitionAssist.DisableTransitions` attached property that you can set to false. However this property is not respected by all of the controls (it is used on Clock, ProgressBars, DialogHost, and DrawerHost) and so may only offer partial support.

I would love to expand it so it worked on all controls, but have not had the time to do a thorough review of all of them. It also is difficult to conditionally apply it to the built-in controls as it is often used as the input to a call to [VisualStateManager.GoToState](https://docs.microsoft.com/dotnet/api/system.windows.visualstatemanager.gotostate?view=net-5.0).

If you are able, could you share which controls/animations are causing the biggest issues for you?

**Comment by gitjsdr26** [comment]
Thank you Keboo,

Only `DialogHost`, `Expander` and `DrawerHost` are causing performance issues for my case.
I tried to use `TransitionAssist.DisableTransitions="True"` into `DialogHost` and `DrawerHost`.
It is well working for `DialogHost`. Now Dialog boxes are appearing and disappearing very fast.
But for `DrawerHost`, only the raising of my View in `DrawerHost.RightDrawerContent` is fast, but closing it is very slow. I can see a grey transition fader of the application background occuring.
`Expander` is not working.

**Comment by gitjsdr26** [comment]
I found a Dirty solution for my case that is, to put to 0 duration for some components :

- MaterialDesignTheme.Expander.xaml
`<Duration x:Key="ExpandDuration">0:0:0.0</Duration>
<Duration x:Key="CollapseDuration">0:0:0.0</Duration>
...
<KeyTime x:Key="ExpandKeyTime">0:0:0.0</KeyTime>
<KeyTime x:Key="CollapseKeyTime">0:0:0.0</KeyTime>`
- MaterialDesignTheme.TreeView.xaml
Set all Duration to 0
`Duration="0:0:0.0" `
- Generic.xaml
Add missing `Duration="0"` in `DoubleAnimation Storyboard.TargetName="PART_ContentCover"`
Otherwise, it is set to 1s. by default.
<Style TargetType="{x:Type local:DrawerHost}">
...
<VisualState x:Name="AllClosed">
  <Storyboard>
    <DoubleAnimation Storyboard.TargetName="PART_ContentCover" 
                     Storyboard.TargetProperty="Opacity" 
                     To="0" 
                     Duration="0"/>
    <BooleanAnimationUsingKeyFrames Storyboard.TargetName="PART_ContentCover" Storyboard.TargetProperty="IsHitTestVisible">
      <DiscreteBooleanKeyFrame Value="False" />
    </BooleanAnimationUsingKeyFrames>
  </Storyboard>
</VisualState>

This solved my performance issue.
Hopping it could help other.

**Comment by MooWeii** [comment]
> I found a Dirty solution for my case that is, to put to 0 duration for some components :
> 
> * MaterialDesignTheme.Expander.xaml
>   `<Duration x:Key="ExpandDuration">0:0:0.0</Duration> <Duration x:Key="CollapseDuration">0:0:0.0</Duration> ... <KeyTime x:Key="ExpandKeyTime">0:0:0.0</KeyTime> <KeyTime x:Key="CollapseKeyTime">0:0:0.0</KeyTime>`
> * MaterialDesignTheme.TreeView.xaml
>   Set all Duration to 0
>   `Duration="0:0:0.0" `
> * Generic.xaml
>   Add missing `Duration="0"` in `DoubleAnimation Storyboard.TargetName="PART_ContentCover"`
>   Otherwise, it is set to 1s. by default.
> 
> ```
> <Style TargetType="{x:Type local:DrawerHost}">
> ...
> <VisualState x:Name="AllClosed">
>   <Storyboard>
>     <DoubleAnimation Storyboard.TargetName="PART_ContentCover" 
>                      Storyboard.TargetProperty="Opacity" 
>                      To="0" 
>                      Duration="0"/>
>     <BooleanAnimationUsingKeyFrames Storyboard.TargetName="PART_ContentCover" Storyboard.TargetProperty="IsHitTestVisible">
>       <DiscreteBooleanKeyFrame Value="False" />
>     </BooleanAnimationUsingKeyFrames>
>   </Storyboard>
> </VisualState>
> ```
> 
> This solved my performance issue. Hopping it could help other.

Thanks a lot.This helps me.
