### ISSUE TITLE
Language support at runtime

### ISSUE THREAD

**Issue by saklanmazozgur** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2393]
Hello,

I am using the page design and content found in the demo. Having each page as a UserControl and adding them in the ViewModel looks fine.

But when I want to add language support, unfortunately it doesn't work. Is there a way to change the content of UserControl pages at runtime?

**Comment by saklanmazozgur** [comment]
The problem was with my code. Please don't be offended.

**Comment by Keboo** [comment]
No problem, glad you got it working
