### ISSUE TITLE
Elevation Support

### ISSUE THREAD

**Issue by jdbriaris** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2407]
The material design guidelines specify the concept of elevation, whereby the various application colours are "elevated" through a series of "dp" levels that give the effect of depth along the z-aixs (https://material.io/design/environment/elevation.html).

When in light theme this effect is primarily achieved through the use of shadows and the Figma Material Design Kit (https://www.figma.com/community/file/778763161265841481) depicts the following

![image](https://user-images.githubusercontent.com/9742752/130937573-4ceea08a-4724-48f4-abc3-339840a0f7cd.png)

i.e., 11 dp levels each of which have the same colour background (white) but varying drop shadow effect. The MaterialDesignInXamlToolkit does provide some support for this through 5 drop shadow effects (e.g. `MaterialDesignShadowDepth1`) specified here (https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d3a35aa701f921238c7c1e70d11e2815d35799db/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Shadows.xaml). This could be increased to the full complement of 11 dp levels.

When in dark theme the drop shadows have little effect, so material design counters this by altering the colour of the surface to make it appear closer to the light source (note: the drop shadows are still there in dark theme, just not obvious to the eye). Again, looking at the Figma Material Design Kit for the dark theme (https://www.figma.com/community/file/787036571667088922) we have

![image](https://user-images.githubusercontent.com/9742752/130938598-5a30579a-6391-4878-8f05-4d7fb12dc4dc.png)

i.e., 11 dp levels whereby the dropshadow effect is still present but now the colour of the component is made lighter as we move up the dp levels.

Would it be possible to augment some of the existing core brushes such as `MaterialDesignPaper`, `MaterialDesignCard`, `PrimaryHueMid` etc. with elevated brushes, e.g. `MaterialDesignPaper1dp`, `MaterialDesignPaper2dp` ... `MaterialDesignPaper24dp` and `PrimaryHueMid1dp`, `PrimaryHueMid2dp` etc. thereby providing more flexibility with respect to elevation? Possibly using the existing "Lighten" and "Darken" methods in the package?

**Comment by Keboo** [comment]
I think there is certainly room for improvement here. I think it would be good to increase the elevation (shadow) levels supported in this library to match the latest version of the spec. I think adding the additional brushes would be good as well. 
For the names of the brushes I would use "Background" rather than "Paper" in the names. Paper is the old name for the brushes and I expect to update it to be Background in a future version.

**Comment by wanjizheng** [comment]
So how to use this Elevation?
