### ISSUE TITLE
DatePicker header missing text and background

### ISSUE THREAD

**Issue by yosefmah** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2408]
Hello.

Following #2356 the DatePicker seems to be missing the header background and foreground.  The new customisable options for the Calendar do not work on the DatePicker.

![image](https://user-images.githubusercontent.com/19147840/130971706-cba321de-92ee-456c-a3fa-458ece3e0744.png)

**Comment by jamesport079** [comment]
I'm experiencing this issue too.
