### ISSUE TITLE
Circle boundary of button - corrupt after moving button

### ISSUE THREAD

**Issue by Krusty84** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2411]
Hi Dear Team,

I have a button

  ```
      <Button
            Style="{DynamicResource MaterialDesignIconButton}"
            ToolTip="MaterialDesignIconButton"
            Background="{StaticResource MaterialDesignTextFieldBoxBackground}" Margin="483,316,261,55" >
                <materialDesign:PackIcon
                     Kind="Play" />
        </Button>
```

In the preview mode - it looks right
But after compilation, circle boundary - corrupted:

![image](https://user-images.githubusercontent.com/44873126/131213414-6224250d-8871-4328-992e-724a0a5de913.png)

But, the buttons with circle boundary if they were not moved - looks right

![image](https://user-images.githubusercontent.com/44873126/131213518-01699813-83b1-4e2a-b428-7ce31f0d183d.png)

```
      <Button
  Style="{StaticResource MaterialDesignIconButton}"
  ToolTip="MaterialDesignIconButton"
  Background="{DynamicResource MaterialDesignTextFieldBoxBackground}">
            <materialDesign:PackIcon
    Kind="Play" />
        </Button>
```
Where is the difference?  - Margin!

MaterialDesignThemes 4.2.0-ci2657

Thanks

**Comment by Erapchu** [comment]
Hello! Why you need exactly that margin? Maybe buttons just are out of bounds some container?

**Comment by Keboo** [comment]
Looking at those margins it appears that the button was likely moved with the Visual Studio Designer. Though that is the default of the designer it is not a good way of doing positioning of elements as it does not allow for scaling or resizing of windows.

**Comment by MichelMichels** [comment]
Inactive issue.
