### ISSUE TITLE
Value is not updated when using "materialDesign:HintAssist.HasClearButton".

### ISSUE THREAD

**Issue by saklanmazozgur** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2420]
Hello,

I have a Textbox like below in MVVM design. If I press the Clear button in the Textbox, the value in the Textbox is deleted, but my Angle value does not change. There is no problem when I delete it with the normal keyboard key.

Is this an expected behavior? How can I update the Angle value to 0 or "" when I press the button.

```
<TextBox Width="160"
                Margin="10,0,0,0"
                 Style="{StaticResource MaterialDesignOutlinedTextBox}"
                 TextWrapping="Wrap"
                  materialDesign:HintAssist.Hint="{Binding ControlView_Angle, Source={StaticResource Resources}}"
                  materialDesign:TextFieldAssist.HasClearButton="True"
                  materialDesign:HintAssist.FloatingScale="1">
                  <TextBox.Text>
                           <Binding Path="Angle"
                                           UpdateSourceTrigger="PropertyChanged">
                                   <Binding.ValidationRules>
                                            <local:NotEmptyValidationRule ValidatesOnTargetUpdated="True" ValidationStep="UpdatedValue"/>
                                    </Binding.ValidationRules>
                            </Binding>
                 </TextBox.Text>
</TextBox>
```

**Comment by StefanoRivolta-Previero** [comment]
It should work. It works for me in this case:

```
  <TextBox Grid.Column="0" Grid.ColumnSpan="3" Grid.Row="1" Margin="10 20 10 0"
           Style="{StaticResource MaterialDesignOutlinedTextBox}" 
           IsEnabled="True" FontSize="20" 
           materialDesign:HintAssist.Hint="{lex:Loc New Value}" 
           Text="{Binding SetValue, UpdateSourceTrigger=PropertyChanged}"
           materialDesign:HintAssist.Background="{DynamicResource MaterialDesignCardBackground}"
           materialDesign:HintAssist.FloatingScale=".7"
           materialDesign:TextFieldAssist.HasClearButton="True"
           materialDesign:TextFieldAssist.SuffixText="{Binding Unit}"/>
```
Maybe the issue is somewhere else? Do you have the latest NuGet?

**Comment by saklanmazozgur** [comment]
@StefanoRivolta-Previero , I am using the latest version. Maybe it has something to do with the data type I'm binding. Float is bound to a data. What data type are you binding?

**Comment by StefanoRivolta-Previero** [comment]
Yeah, I'm using a `string `and converting in the ViewModel when I need the float value. 
The clear button sets the TexBox Text property to `null`, which I'm sure it's not a valid value for `float`. Maybe you could try using `float?` or `double?`
The question mark indicates that it's nullable. Or maybe you could try using `string `and doing a `float.Parse` or `float.TryParse`

**Comment by saklanmazozgur** [comment]
`float?` I use as. I'll probably do `string`. Thank you very much for your reply.
