### ISSUE TITLE
Why Is This Happening To My Buttons

### ISSUE THREAD

**Issue by ImmuneLion318** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2424]
A Source Wouldn't Be Needed Since To Replicate This Issue Just Add The RaisedButton Style To Any Button With A MDL2 Assets Icon The Issue Is When Using The MaterialRaisedButton Style My Button Icon Dosen't Seem To Appear Anymore
![image](https://user-images.githubusercontent.com/54381449/133558087-11ef2723-a264-40c6-9260-0d79fdcc135c.png)
![image](https://user-images.githubusercontent.com/54381449/133558098-b0439381-caab-48e6-9898-4adcb637ce40.png)
Its The Same When Debugging And Running

**Comment by JcMeilleurAt** [comment]
Same for me. Button don't appear. 
Combobox is default Style. 
Card is ok for me tho. 

But when I debug everything is ok. on my side tho

**Comment by Keboo** [comment]
I am not sure I understand the issue. Can you share how you are specifying the icon for the button. The following code works for me:

```xaml
<Button Style="{StaticResource MaterialDesignRaisedButton}">
    <Button.Content>
        <materialDesign:PackIcon Kind="Smiley" />
    </Button.Content>
</Button>
```

I would start by checking to make sure that you have setup your [color theme and window styles](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started#version-300-and-later) are setup properly

**Comment by Keboo** [comment]
Based on those screenshots it looks like the default styles are not getting included. 

Based on those screenshots it looks like the default implicit styles are not getting applied. Do you have this added in you App.xaml (like [this](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml#L27))? 

The other possibility. Have you added any new implicit styles (styles without an explicit `x:Key`) that target types like button? If you create implicit styles, and want to keep the material design style they need to be based on the material design styles (more info [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#when-custom-style-is-applied-the-material-design-theme-is-lost))

**Comment by JcMeilleurAt** [comment]
> Based on those screenshots it looks like the default styles are not getting included.
> 
> Based on those screenshots it looks like the default implicit styles are not getting applied. Do you have this added in you App.xaml (like [this](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/App.xaml#L27))?
> 
> The other possibility. Have you added any new implicit styles (styles without an explicit `x:Key`) that target types like button? If you create implicit styles, and want to keep the material design style they need to be based on the material design styles (more info [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#when-custom-style-is-applied-the-material-design-theme-is-lost))

Yes for the fist question. My App file is set like the link you send me. 

And as for the style. Yes I do have a lot whithout the x:key. But it's been like that for ages and it worked fine. 

Example of my Combobox Style inside m App.xaml. 

`             <ResourceDictionary>
                    <Style TargetType="ComboBox" BasedOn="{StaticResource MaterialDesignFloatingHintComboBox}">
                        <Setter Property="MinWidth" Value="200"/>
                        <Setter Property="Height" Value="40"/>
                        <Setter Property="Margin" Value="5"/>
                    </Style>
                </ResourceDictionary>` 

And the weird thing is that I don't have any Style in the App.xaml for a button and this is what disappear. 

Just finish some test with Visual Studio and I have some weird error that was not there days ago. I don't know if it's something related to some update that was done to some nugget package or windows update but when I look on internet. It seems to be a framework issues. 

![image](https://user-images.githubusercontent.com/77988688/133648008-7eb7ca1d-d0dc-44ea-b6a8-c5ffb86aba7f.png)

this is what I have in my UserControl and the error:
The Background Property don't exist in "http://shemas.microsoft.com/expression/blend/2008" namespace.

**Comment by Erapchu** [comment]
@JcMeilleurAt Do you mean that Visual Studio designer can't load your styles while you design the window? It's normal behavior for designer. If you want to design window with VS Designer and styles are not handled in design mode you need to include material design resources to your window in Window.Resources:
`<ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>`

So, after that, designer can fetch resources, but don't use it everywhere. 
Another solution is to design window after it loaded - VS 2019 already supports Hot Reload feature.

**Comment by JcMeilleurAt** [comment]
> @JcMeilleurAt Do you mean that Visual Studio designer can't load your styles while you design the window? It's normal behavior for designer. If you want to design window with VS Designer and styles are not handled in design mode you need to include material design resources to your window in Window.Resources:
> `<ResourceDictionary> <ResourceDictionary.MergedDictionaries> <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" /> <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" /> </ResourceDictionary.MergedDictionaries> </ResourceDictionary>`
> 
> So, after that, designer can fetch resources, but don't use it everywhere and remove resources when you finished.
> Another solution is to design window after it loaded - VS 2019 already supports Hot Reload feature.

Thanks Ill try that later today. 
The thing is, my screenshots comming from Rider. 
I try the same solution yesterday night at home and everything work fine in Rider. (Still have the issues / error in VS.) 
Ive been working on this solution with material design since last november and I never had any problem with the designer window before so that's a pretty weird behavior imo. 
The more I look around the more I think it's a Solution corruption or a framework issue not related to MaterialDesign. Since the same solution work perfectly  home and dont work on my work computer. 
Ill try to create another solution with only one view and see if I have the same problem. 
Ill let you know!

**Comment by JcMeilleurAt** [comment]
> @JcMeilleurAt Do you mean that Visual Studio designer can't load your styles while you design the window? It's normal behavior for designer. If you want to design window with VS Designer and styles are not handled in design mode you need to include material design resources to your window in Window.Resources: `<ResourceDictionary> <ResourceDictionary.MergedDictionaries> <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" /> <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" /> </ResourceDictionary.MergedDictionaries> </ResourceDictionary>`
> 
> So, after that, designer can fetch resources, but don't use it everywhere and remove resources when you finished. Another solution is to design window after it loaded - VS 2019 already supports Hot Reload feature.

Hi! I try it and it's working only for a part of the view. For example the combobox it's working but not the button. 
BUT 
Im working from home 2 days a week so the project is on Git and I transfert the solution from one computer to another multiple times a week. 
The project work perfectly on my personnal computer. I have this bug only on my work machine. 
And at Home I dont have thoses resourceDictionary. Everything is loading perfectly in the preview. 
But at work, I can't make it work. 

I don't understand why and I can't figure what's going on. 

Thanks 
Jc
