### ISSUE TITLE
Add ComboBoxAssist.MaxLength attached property in ComboBox to control MaxLength when IsEditable is set to True

### ISSUE THREAD

**Issue by jamesport079** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2442]
ComboBox with IsEditable set to true essentially behaves as a TextBox with an autosuggest dropdown list. A silly ommission in WPF is that MaxLength cannot be set in XAML for an editable ComboBox. 

I created an attached property to address this shortcoming. I strongly feel this can be integrated in this library in the form of  materialDesign:ComboBoxAssist.MaxLength="___" helper class. 

The code to implement it is pretty straightforward, essentially creating an attached property MaxLength and finding the TextBox part in ComboBox and setting MaxLength on TextBox. FindChild<T> does the magic to find the TextBox part of the editable ComboxBox. 

    private static void OnMaxLenghtChanged(DependencyObject obj, DependencyPropertyChangedEventArgs args)
    {
        if (obj is ComboBox comboBox)
        {
            comboBox.Loaded +=
              (s, e) =>
              {
                  DependencyObject? textBox = comboBox.FindChild<TextBox>("PART_EditableTextBox");
                  if (textBox == null)
                  {
                      return;
                  }

                  textBox.SetValue(TextBox.MaxLengthProperty, args.NewValue);
              };
        }
    }

If you think this is beyond the scope of this library I would at least suggest to add TextFieldAssist.CharacterCounterVisibility to be accessible in an editable ComboBox for the sake of consistency.

**Comment by Xaalek** [comment]
`FindChild` does not exist in the current context. Do you mean `FindName` ?

**Comment by jamesport079** [comment]
> 
sorry, here's the code for FindChild...

`public static class UIChildFinder
{
    /// <summary>
    /// Finds a Child of a given item in the visual tree. 
    /// </summary>
    /// <param name="parent">A direct parent of the queried item.</param>
    /// <typeparam name="T">The type of the queried item.</typeparam>
    /// <param name="childName">x:Name or Name of child. </param>
    /// <returns>The first parent item that matches the submitted type parameter. 
    /// If not matching item can be found, 
    /// a null parent is being returned.</returns>
    public static T? FindChild<T>(this DependencyObject parent, string childName)
       where T : DependencyObject
    {
        // Confirm parent and childName are valid. 
        if (parent == null) return null;

        T? foundChild = null;

        int childrenCount = VisualTreeHelper.GetChildrenCount(parent);
        for (int i = 0; i < childrenCount; i++)
        {
            var child = VisualTreeHelper.GetChild(parent, i);
            // If the child is not of the request child type child
            if (child is not T)
            {
                // recursively drill down the tree
                foundChild = FindChild<T>(child, childName);

                // If the child is found, break so we do not overwrite the found child. 
                if (foundChild != null) break;
            }
            else if (!string.IsNullOrEmpty(childName))
            {
                // If the child's name is set for search
                if (child is FrameworkElement frameworkElement && frameworkElement.Name == childName)
                {
                    // if the child's name is of the request name
                    foundChild = (T)child;
                    break;
                }
            }
            else
            {
                // child element found.
                foundChild = (T)child;
                break;
            }
        }

        return foundChild;
    }
}`

**Comment by Xaalek** [comment]
I made a pull request with the changes you suggested : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2661

**Comment by jamesport079** [comment]
Thank you 👍
