### ISSUE TITLE
How to use Tabcontrol in MaterialDesign Style in binding way.

### ISSUE THREAD

**Issue by lanpst** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2447]
**There is a good style with tabcontrol in MaterialDesign. But I find there is only code way to add tabitem.**

![image](https://user-images.githubusercontent.com/6269204/135192740-44385bac-7695-49ad-80f2-623124c3c31c.png)

**It is necessary for us to bind a source and i've tried but fail like this:**
**1 This is MainWindow with a TabControl setting with style  "MaterialDesignNavigatilRailTabControl".**

![image](https://user-images.githubusercontent.com/6269204/135192916-88777bb3-b1a2-4f5b-94c6-f0c3369f48e3.png)

**2 Navigate Command in MainWindowViewModel**

![image](https://user-images.githubusercontent.com/6269204/135193314-598f0912-dff3-4734-91f3-d263613406d6.png)
 
**3 Two Attributes (Icon and Title) for TabControl in SubPageViewModel**

![image](https://user-images.githubusercontent.com/6269204/135193408-6b701cc9-ca48-40d7-8e27-36b4c3295c50.png)

**4 When it start, the two button navigating 2 kinds of page. Click then but the icon and text is empty.**

![image](https://user-images.githubusercontent.com/6269204/135193207-c8d21978-b34c-43a9-96b6-b3d1c071589c.png)

**I've tried to read source code of MaterialDesign but fail. Would you please to help me to use tabcontrol in binding way?
Thank you!**

**Comment by StefanoRivolta-Previero** [comment]
I think you forgot to add an `ItemSource` to the `TabControl`, with the List of `TClientControlViewModel`

You'd need something like this in the MainViewModel:
```
private List<TClientControlViewModel> _source;

public List<TClientControlViewModel> Source
{
    get { return _source; }
    set { SetProperty(ref _source, value); }
}
```
And you then specify the ItemsSource in the TabControl like this: 
`ItemsSource = {Binding Source}`

**Comment by MichelMichels** [comment]
Closed due to no reply.
