### ISSUE TITLE
Is there a RangeSlider in MaterialDesignXamlToolkit that returns two values?

### ISSUE THREAD

**Issue by saklanmazozgur** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2468]
Hello,

The question is, is there a slider with upper and lower values as in the title? I've included a sample image below. If possible, can you show me how to do it? 
<img width="360" alt="unnamed" src="https://user-images.githubusercontent.com/52654922/137266036-1fc76ded-ec0e-486b-8de4-97375208e175.png">

Thank you.

**Comment by Keboo** [comment]
Yes, this is possible using the MahApps integration. You can see an example in the [MahApps Material Design demo project](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/Mah.xaml#L48-L60)
![image](https://user-images.githubusercontent.com/952248/137267038-e51f42f2-4bb9-4224-8f44-e8e1e2a84355.png)

There are a few things you need to do for this.
1. Include the [MahApps](https://www.nuget.org/packages/MahApps.Metro/) and the [MahApps Material Design integration package](https://www.nuget.org/packages/MaterialDesignThemes.MahApps)
2. Add the additional resource dictionaries. You can see a sample in that same demo app here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/App.xaml#L15-L25
3. Use the MahApps RangeSlider control.

**Comment by saklanmazozgur** [comment]
I guess TickFrequency is not working correctly. I am getting double values even though I set it as below. Is there anything else I should apply?

`<controls:RangeSlider Name="RangeSlider2" TickPlacement="BottomRight" Minimum="0" Maximum="255" TickFrequency="1"/>
            <TextBlock Text="{Binding ElementName=RangeSlider2, Path=LowerValue}" HorizontalAlignment="Left"/>
            <TextBlock Text="{Binding ElementName=RangeSlider2, Path=UpperValue}" HorizontalAlignment="Right"/>`

**Comment by Xaalek** [comment]
@saklanmazozgur  Check this out for double values https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2685

**Comment by Xaalek** [comment]
@saklanmazozgur please open a new issue if you still get an error plean
