### ISSUE TITLE
Chips with MVVM

### ISSUE THREAD

**Issue by jensdebernitzCGM** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2471]
I will use the Chips in WPF with MVVM

now I have the Problem that I have an ObservableCollection with Items in my ViewModel. 
The Itmes holds a itemName and a bool for the Selection.
This Collection I set in the Xaml to the ItemSource.

` public class ItemPresenter : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public void RaisePropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

        private string item;

        public string Item
        {
            get { return item; }
            set
            {
                item = value;
                this.RaisePropertyChanged("Item");
            }
        }

        private bool isSelected;

        public bool IsSelected
        {
            get { return isSelected; }
            set
            {
                isSelected = value;
                this.RaisePropertyChanged("IsSelected");
            }
        }
    }`

`                    <ListBox
                        x:Name="ListBoxFilterChips"
                        Margin="0,150,0,0"
                        ItemsSource="{Binding FilterChips, NotifyOnSourceUpdated=True}"
                        Style="{StaticResource MaterialDesignFilterChipPrimaryOutlineListBox}">
                        <ListBox.ItemTemplate>
                            <DataTemplate>
                                <TextBlock Text="{Binding Item}" />
                            </DataTemplate>
                        </ListBox.ItemTemplate>
                    </ListBox>`

this work with the Style for the Chips, but I will set the Selection from the Chips from the ViewModel. 

but I don't know how

**Comment by jensdebernitzCGM** [comment]
Dear sender, 

due to a ransomware attack and necessary security measures, CGM is temporarily not reachable in some regions via the usual eMail addresses and landline numbers. 
In these cases, please feel free to use SMS and mobile telephony of your individual contact persons, as far as they are known to you or inform yourself about further contact possibilities via the respective company or product page. 

Thank you for your understanding and best regards,
Your CGM Team

----------------------

Sehr geehrte Absenderin, 
sehr geehrter Absender,  

aufgrund einer Ransomware-Attacke und notwendiger Sicherheitsmaßnahmen, ist CGM in einigen Regionen vorübergehend nicht über die gewohnten eMail-Adressen und Festnetznummern erreichbar. 
Bitte nutzen Sie gerne in diesem Fall SMS und Mobilfunk-Telefonie Ihrer individuellen Ansprechpartner, soweit diese ihnen bekannt sind oder informieren Sie sich über die jeweilige Firmen- bzw. Produktseite über weitere Kontaktmöglichkeiten. 

Vielen Dank für Ihr Verständnis und freundliche Grüße, 
Ihr CGM-Team

**Comment by viktorrko** [comment]
Hello,
I'm facing a similiar issue as the original author of this issue. I followed @Erapchu 's advice and implemented it into my code. It looks good on first glance, but it's not completely right, as it creates another interactive element in the chip, which blocks selection of the ListBoxItem itself (excuse me, I don't know how to properly call it), as you can see in the GIF below:

![Recording 2024-05-12 at 17 35 35](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/48345204/c2c74a28-7c99-47c1-adb9-725c1d92e436)

My ListBox XAML looks like this:

<ListBox Style="{StaticResource MaterialDesignFilterChipPrimaryOutlineListBox}"
         Grid.Row="2"
         Padding="0"
         Margin="0,6,0,0"
         ItemsSource="{Binding DownloadOptions}">

    <ListBox.ItemContainerStyle>
        <Style TargetType="{x:Type ListBoxItem}"
               BasedOn="{StaticResource MaterialDesignFilterChipPrimaryOutlineListBoxItem}">
            <Setter Property="IsSelected"
                    Value="{Binding IsSelected}" />
        </Style>
    </ListBox.ItemContainerStyle>

    <ListBox.ItemTemplate>
        <DataTemplate>
            <ListBoxItem Content="{Binding Content}" />
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>

My ViewModel code is pretty much identical.

**Comment by EAyoubi** [comment]
<ListBox  ItemsSource="{Binding FilterChips}"  Style="{StaticResource MaterialDesignFilterChipPrimaryListBox}" >
                                    <ListBox.ItemContainerStyle>
                                        <Style  TargetType="{x:Type ListBoxItem}" BasedOn="{StaticResource MaterialDesignFilterChipPrimaryOutlineListBoxItem}" >
                                            <Setter Property="IsSelected"
                Value="{Binding IsSelected, Mode=TwoWay}" />
                                            <Setter Property="Content"
Value="{Binding Item, Mode=TwoWay}" />
                                        </Style>
                                    </ListBox.ItemContainerStyle>

                                </ListBox>
