### ISSUE TITLE
PackIcon enforce width

### ISSUE THREAD

**Issue by itschrono** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2484]
Hello, it seems some icons are wider than others so specifying same width and height can cause horizontal overflow...

Ok =
```xaml
<materialDesign:PackIcon
                x:Name="icon"
                VerticalAlignment="Center"
                Kind="{Binding Icon}"
                Height="24"
                Width="32" />
```
![image](https://user-images.githubusercontent.com/25153662/140542474-b13d1b0b-38b7-4c95-8791-f248206f50b7.png)

Not ok =
```xaml
<materialDesign:PackIcon
                x:Name="icon"
                VerticalAlignment="Center"
                Kind="{Binding Icon}"
                Height="32"
                Width="32" />
```
![image](https://user-images.githubusercontent.com/25153662/140542633-83bcb21a-cbc6-4a92-8298-ec2d14478414.png)

It's not urgent, I will stay at 24x32 for now.

**Comment by Keboo** [comment]
@itschrono can you provide the `Kind` values for those icons?

Right now the PackIcon values are auto generated on a daily basis, so it is a bit difficult to account for the variations within the icon data itself, however I do have some thoughts on how this might be better addressed.

**Comment by Erapchu** [comment]
All icons provided by PackIcon are located in box control. So, all of them have the same width and height from WPF perspective. But actually they're not the same when compare by pixel width/height of course.
If I'm not mistaken, you could set 24x24 size for icon - it should be the same like 24x32.

**Comment by itschrono** [comment]
@Keboo kind values are: FolderOpen, MonitorDashboard and Settings.

@Erapchu I need to constraint width AND height. 

Focus on PackIcon 32x32. Feel like some pixels could be drawn but are not.
![image](https://user-images.githubusercontent.com/25153662/140713495-319aa071-d671-4bf0-a0b8-5578d978ac5a.png)

**Comment by itschrono** [comment]
Ok nevermind I had this inside a ScrollViewer with a right padding which caused the pixel crop.... PackIcon works fine I guess.
