### ISSUE TITLE
Regression: ComboBox not opening popup on mouse click if IsEditable is true

### ISSUE THREAD

**Issue by michaelmairegger** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2488]
There is a regression issue with version 4.2.1 since it does not exist in version 4.1.0. As you can see in the two comparing gifs below the left ComboBox opens when clicking on any positon. Instead the right one opens only if you click on the undelining bar. Is this behavior intended. As for now the user behavior is a bit weird since it is not mouse friendly and hard to find the posistion where the combobox opens.

|v4.1.0|v4.2.1|
|---|---|
|![Library v4 1 0](https://user-images.githubusercontent.com/4341039/140962060-f57bc00a-874c-4f34-b6d4-c701eadadb5b.gif)|![Library v4 2 1](https://user-images.githubusercontent.com/4341039/140962089-7e28d389-fcf2-44b2-bd9e-c5af598e3021.gif)|

Possibly related to #2428

# Reproduction

It is important to note that the combobox has `IsEditable="True"`.

## Sample code:

The sample solution has two projects one for each version v410 and v420.
https://github.com/michaelmairegger/MaterialDesignInXamlToolkit-ComboBoxIssue

**Comment by MichelMichels** [comment]
It seems to be fixed in latest version. I will close this issue for now, feel free to reopen if I missed something.
