### ISSUE TITLE
Can't Import

### ISSUE THREAD

**Issue by vasivee** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2492]
![unknown](https://user-images.githubusercontent.com/89988125/141601819-0213bfb9-76ed-4cd3-a3f5-7adf3fa270e2.png)
**I''m trying to make something in VS 2019 and using Avalon Text Editor but after I import it in references and then in the tool box, I can't import it onto my grid, it pops up a security thing and I couldn't find a solution on google either, here's a screenshot https://imgur.com/a/Nj0MSOR**

**Comment by MichelMichels** [comment]
Could you in some way provide reproduction steps or a git repository?

**Comment by MichelMichels** [comment]
Closed due to inactivity.
