### ISSUE TITLE
Can't set DatePicker Background

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2504]
![image](https://user-images.githubusercontent.com/7858946/143787708-dfbf1e09-eacb-42a2-85b7-ba9cc758d70e.png)

**Comment by MichelMichels** [comment]
@Keboo do you leave this issue open until it's in a next release or can this be closed?
(I'd contact you through gitter, but I'm getting a 500 internal server error status code)

**Comment by Keboo** [comment]
Nope, not intentional. Typically will close issues once a PR is merged. GitHub can auto close items if one of the magic phrases is used in the description, and i sometimes forget to close issues.
