### ISSUE TITLE
Have you made a plan for a drop-down combobox tree

### ISSUE THREAD

**Issue by snowiceyeah** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2513]
![image](https://user-images.githubusercontent.com/43429385/144525033-7112f1b5-3565-499b-a25d-a19015a47104.png)

**Comment by MichelMichels** [comment]
I think this is out of scope for this library. I don't find any control resembling this one in the Material Design specs. I also don't think it would be intuitive as I can't fully workout from your screenshot how such a control should behave.

**Comment by MichelMichels** [comment]
Closed due to inactivity.
