### ISSUE TITLE
Error on compiling demo.....

### ISSUE THREAD

**Issue by TwoflexStudios** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2515]
I tried to compile MainDemoWPF to see the demo but it shows several errors is there a way to download the pure executable???
![image](https://user-images.githubusercontent.com/80816488/144788410-f2e34a1b-9380-407c-a773-3fea241ac1cd.png)

**Comment by DrHalfBaked** [comment]
Take it from [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/releases)

**Comment by Keboo** [comment]
When compiling from source, this repository will typically be using the latest C# features. At present, it [requires C# 10](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/Directory.Build.props#L7). This typically will mean Visual Studio 2022. Though I have not tested it, I suspect Visual Studio 2019, with the .NET 6 SDK installed will also work.

**Comment by MichelMichels** [comment]
.NET 6 and C#10 is not supported in Visual Studio 2019.

Official source: https://devblogs.microsoft.com/dotnet/announcing-net-6/
