### ISSUE TITLE
Combobox with country flags

### ISSUE THREAD

**Issue by Ares-87** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2521]
Hi all, I have a question, there is a way to show the flag of listed countries?
I have issues to set ItemsPanel template. Thank you in advance.

**Comment by MichelMichels** [comment]
You need to set the ItemTemplate and not the ItemsPanel template. This is not an issue that is specific to this library. You should ask this question on StackOverflow or WPF/XAML related forums.
