### ISSUE TITLE
Buttons are not clickable in Flipper in release 4.3.0

### ISSUE THREAD

**Issue by kunjiangkun** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2522]
<materialDesign:Flipper 
                Style="{StaticResource MaterialDesignCardFlipper}"
                IsEnabled="{Binding IsBusy, UpdateSourceTrigger=PropertyChanged,  Converter={StaticResource InverseBooleanConverter}}">
                <materialDesign:Flipper.FrontContent>
                    <Grid Height="{Binding PanelHeight}" Width="{Binding PanelWidth}">
                        <materialDesign:ColorZone Mode="PrimaryDark" VerticalAlignment="Stretch" materialDesign:ShadowAssist.ShadowDepth="Depth3">
                            <materialDesign:ColorZone.Background>
                                <ImageBrush ImageSource="/Stan;component/Metal.png"/>
                            </materialDesign:ColorZone.Background>
                            <Grid>
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="5" />
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="Auto"/>
                                </Grid.ColumnDefinitions>
                                <StackPanel Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" Orientation="Horizontal">
                                    <Button
                                        Style="{StaticResource MaterialDesignFloatingActionMiniButton}"
                                        materialDesign:ShadowAssist.ShadowDepth="Depth3"
                                        Background="{Binding ConnectBtnBackground, UpdateSourceTrigger=PropertyChanged}"
                                        ToolTip="Connect/DisConnect" Margin="5" Height="32" Width="32"
                                        Click="ConnectBtn_Click">
                                        <materialDesign:PackIcon
                                        Kind="{Binding ConnectIcon, UpdateSourceTrigger=PropertyChanged}"
                                        Height="18" Width="18" />
                                    </Button>
                                    <Button
                                        Style="{StaticResource MaterialDesignFloatingActionMiniButton}"
                                        IsEnabled="{Binding IsConnected}"
                                        materialDesign:ShadowAssist.ShadowDepth="Depth3"
                                        ToolTip="Reset" Margin="5" Height="32" Width="32"
                                        Click="ResetBtn_Click">
                                        <materialDesign:PackIcon Kind="Refresh" Height="18" Width="18" />
                                    </Button>
                                    <TextBlock 
                                        Text="{Binding Title}" Margin="5" FontSize="18" 
                                        VerticalAlignment="Center" FontWeight="Bold" Foreground="DarkGray"/>
                                </StackPanel>

**Comment by Xaalek** [comment]
Do you have the bug with the latest version of the package?
