### ISSUE TITLE
Make ComboBox easier to autocomplete text

### ISSUE THREAD

**Issue by Isayama-Kagura** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2523]
Although ComboBox can filter options by entering a prefix string, it cannot do so if the string is not a prefix. It will be better that ComboBox or Textbox can have the function of matching all options containing input characters, and only the given option can be input. As shown in the figures below：

![image](https://user-images.githubusercontent.com/30114848/145399440-6ddd1e2a-d5df-499c-a4dd-4e28b13a6a99.png)

![image](https://user-images.githubusercontent.com/30114848/145400524-d96e4c1d-e214-4ea5-8e64-07468a2b0b76.png)

**Comment by database64128** [comment]
Unfortunately this is how WPF's `TextSearch` works. For use cases like yours, you might want to implement your own search and filtering logic.

**Comment by MichelMichels** [comment]
Closed due to out of scope question.
