### ISSUE TITLE
How to turn on scroll on touch screen display for listview , datagrid ect ?

### ISSUE THREAD

**Issue by Wep4ik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2527]
I'm making an application for a market. The application should run on a POS with a touch screen, unfortunately, on testing, I saw that scrolling list, DataGrid, and other list-type controls don't work at all. It only selects the item that was presed.
How do I turn on touch scroll ?

**Comment by MichelMichels** [comment]
Is this something that is working for non-styled WPF DataGrids? I don't think there is a specific touch implementation in this library.

**Comment by Wep4ik** [comment]
> Is this something that is working for non-styled WPF DataGrids? I don't think there is a specific touch implementation in this library.

I found the problem. The problem was with the type of touch screen that I use for testing, I use one from slot machines that are more fast than one from POS. Every touch response as a selection and not as a scroll, on a normal pos it's working normally.
