### ISSUE TITLE
XAML  coding style guidelines

### ISSUE THREAD

**Issue by MichelMichels** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2531]
I'd like to propose to a coding style requirement for the XAML files in this library. As I'm a bit more invested in committing PRs, I see atm it is a bit all over the place. I added a screenshot of the coding style I'd like to be the default. 

![image](https://user-images.githubusercontent.com/6505319/146824004-8647b764-4c14-4c75-a2c5-0b8a63809fa1.png)

![image](https://user-images.githubusercontent.com/6505319/146824975-238bd49f-05f8-402f-a3dc-22e9d098c9ef.png)

Thoughts?

**Comment by Keboo** [comment]
Yes! I would very much love this. I have often thought about pulling in [XamlStyler](https://github.com/Xavalon/XamlStyler) for exactly this sort of thing. The hard part with VS setting is that it makes it quite difficult to keep settings in sync across different projects (this is one of my own personal problems as I work on many different projects). In an ideal world [.editorconfig would support XAML files](https://developercommunity.visualstudio.com/t/editorconfig-support-for-xaml-files/1078375) but for now I I am perfect happy to accept this suggestion. 

At a minimum, lets add this to the wiki under the [Compiling from Source page](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source) so that coding standards are documented somewhere. Then we can look at further option for pulling in XamlStyler (or similar) to help keep things consistent.

**Comment by Erapchu** [comment]
I love this code style! But XAML code may grow up approximately x2 (for example the last commit on that moment https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/c62bed496bfa82ed3e77a0bf0e6094da03a07ba4).
This is not a problem, the main purpose is ease of reading.

**Comment by database64128** [comment]
![image](https://user-images.githubusercontent.com/18757988/146877888-8f89ac8b-9a18-4d2f-8806-bb4b567f04fb.png)

Personally I prefer to line up the properties like this. Sometimes when there's not too many properties, it's more readable to keep the properties in one line.

**Comment by Erapchu** [comment]
Ok, we can use code style as @MichelMichels suggested, with keeping properties in one single line if it does not take up much space. Just for readability. 
If we will use position each attribute on a separate line completely, then code will grow up. For example I don't think that it's required to use separate lines for 

`<Setter Property="Background" Value="Transparent"/>
<Setter Property="BorderBrush" Value="Transparent"/>
<Setter Property="Width" Value="26"/>
<Setter Property="Height" Value="26"/>`

![image](https://user-images.githubusercontent.com/37536541/146886057-ea25e6fd-b7d0-4381-8d8d-a28dfe1bbef6.png)

Or

`<Grid.RowDefinitions>
  <RowDefinition Height="auto"/>
  <RowDefinition Height="*"/>
  <RowDefinition Height="auto"/>
</Grid.RowDefinitions>`

![image](https://user-images.githubusercontent.com/37536541/146886087-d8e8fc22-de2f-4e44-8360-767ff4cef53e.png)

**Comment by Erapchu** [comment]
I think exactly that code style is most readable - mix each attribute on separate line (ComboBoxPopup with a lot of attributes) and on a single line (MiltiBinding with 1-2 attributes):

![image](https://user-images.githubusercontent.com/37536541/146886971-7791b9e9-b847-4630-a25c-2410311304b6.png)

**Comment by MichelMichels** [comment]
@Erapchu I also think what you are proposing is more readable, but is there anyway to set this up in VS to format it this way with the CTRL K + D shortcut? This is how I let VS style my personal XAML to fix spaces and returns atm.

**Comment by Erapchu** [comment]
I think there's no shortcut for this automatic format.

**Comment by MichelMichels** [comment]
[XamlStyler](https://github.com/Xavalon/XamlStyler)  proposed by @Keboo  does exactly what you are describing, @Erapchu.

At first glance, it seems to put controls with more than 2 attributes on new lines. The controls with 1 or 2 attributes get placed on the same line. I'll use this extension in the meantime.

![image](https://user-images.githubusercontent.com/6505319/146985666-2cd5d9cd-1eeb-4551-825f-dd205147c1fd.png)

@Keboo shouldn't we put the coding guidelines in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Contribution-Guidelines instead?

**Comment by Keboo** [comment]
Oops yes that is probably a better place for it.

**Comment by MichelMichels** [comment]
I added a small section about coding style in the contribution guidelines. Someone should review the edit to make sure it's good enough.

**Comment by Keboo** [comment]
LGTM
