### ISSUE TITLE
It breaks the references when updating the MaterialDesignThemes version.

### ISSUE THREAD

**Issue by saklanmazozgur** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2545]
Hello,

I want to update MaterialDesignThemes version to 4.3.0 in my project.

When I update with Nuget it breaks the System.Windows.Forms reference used in the references in my project. I don't understand why this is causing it.

What is the wrong point?

**Comment by MichelMichels** [comment]
I'll need some more info to answer this question:
* is this .NET Framework or .NET? And which version?
* are you using any specific elements?
* which version is still working for you?

It would be easiest to give a demo app with the issue.

**Comment by saklanmazozgur** [comment]
I am using .NET Framework 4.7.2.
MaterialDesign 4.1.0 works fine.

I tried to reproduce the problem in the blank project but I couldn't reproduce it. I think it is caused by Visual Studio compilation when I upgrade.

If I can reproduce the problem, I will upload it here with a detailed explanation.

**Comment by MichelMichels** [comment]
Closed due to inactivity.
