### ISSUE TITLE
The Chinese input method that comes with win10 is not accurately positioned in DialogHost

### ISSUE THREAD

**Issue by qz347655378** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2547]
# The Chinese input method that comes with win10 is not accurately positioned in DialogHost

**Comment by Xaalek** [comment]
What is the expected behaviour?

**Comment by qz347655378** [comment]
I want the text selector to be positioned correctly to the position of the input box so it looks better

**Comment by qz347655378** [comment]
![QQ截图20220616095400](https://user-images.githubusercontent.com/54021540/173974452-dc6ffc17-97fe-4095-a4fd-8e813799c597.png)

**Comment by Xaalek** [comment]
How do you open this menu ?

**Comment by qz347655378** [comment]
Switch the input method that comes with win10 to Chinese Pinyin input method
