### ISSUE TITLE
Any plan to add FolderBrowserDialog/FileDialog?

### ISSUE THREAD

**Issue by philwu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2549]
Is there any plan to add FolderBrowserDialog and FileDialog?

**Comment by Keboo** [comment]
Currently no, these are a bit beyond the scope of the material design spec. However, there is a great [Material Designs Extensions](https://github.com/spiegelp/MaterialDesignExtensions) library that contains the.
