### ISSUE TITLE
Filled and outlined multi-line textboxes, horizontal scrollbar vertical alignment not stretched

### ISSUE THREAD

**Issue by Awsmolak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2556]
For multi-line textboxes, if you disable wrap and use a horizonal scrollbar, the scrollbar appears right below the last line of input text rather than at the bottom of the field.

![image](https://user-images.githubusercontent.com/15197249/148336265-c4dd15a5-7ebf-440e-b262-b17a98c91853.png)

**Comment by MichelMichels** [comment]
It doesn't behave like this if you use the `MinLines` and `MaxLines` property instead the `Height` attribute.

**Comment by Keboo** [comment]
I think that would probably be best. As a general rule, having a control behave in a similar manner to the default WPF controls is usually expected.
