### ISSUE TITLE
MaterialDesignOutlinedComboBox isn't showing selected items

### ISSUE THREAD

**Issue by PiousVenom** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2558]
MaterialDesignInXamlToolkit: Version 4.3
.NET 6
Visual Studio 2022: 17.0.4

I've added the style `MaterialDesignOutlinedComboBox` to my ComboBox, but when I select an item, nothing is shown. I've created a [test app](https://github.com/PiousVenom/MDIXTestApp) that has the same results.

**Comment by Keboo** [comment]
Bug reproduces nicely with the sample application. It also reproduces with the latest preview NuGet package (`4.4.0-ci45`).

**Comment by MichelMichels** [comment]
The problem lies in the static height set at 35. This doesn't play well with the default padding of the control. If you still want a height of 35, you should also set your padding to some value. 8 seems like a good fit.

**Comment by PiousVenom** [comment]
> The problem lies in the static height set at 35. This doesn't play well with the default padding of the control. If you still want a height of 35, you should also set your padding to some value. 8 seems like a good fit.

That was absolutely the problem. Thank you.

**Comment by MichelMichels** [comment]
@PiousVenom glad to help!
