### ISSUE TITLE
I think the ripple is not good

### ISSUE THREAD

**Issue by AYue2021** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2560]
https://www.mdui.org/docs/ripple
it's not same
In MDXamlToolKit,
if i click Button ,
it will replace the ripple (it's not  replace)

**Comment by Keboo** [comment]
Hi @AYue2021 that link appears to be another npm library.
The docs this library is based on can be found here: https://material.io/
Do note that Google recently released material design 3, and this library is planning on supporting it, but it will take some time. You can see the plan for that here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2475

**Comment by MichelMichels** [comment]
Closed due to out of scope.
