### ISSUE TITLE
DialogHost dialog disappear when window is top most and lose focus

### ISSUE THREAD

**Issue by a7medsalem** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2565]
I have a window with a dialog host, when I set window top most property to be true, and then click on other application, the dialog content disappear.

Is there any configuration I'm messing here ? I'm using version 4.0.0

# when window in focus
![image](https://user-images.githubusercontent.com/35755221/150657205-bae67341-32e1-493e-97fc-944d90833cc9.png)

# when window in out-of-focus 'by clicking on other application for example'
dialog content disappear
![image](https://user-images.githubusercontent.com/35755221/150657212-6349c507-b2d4-4792-844c-6826b6aafe23.png)

**Comment by a7medsalem** [comment]
Fixed in version 4.3.0

**Comment by a7medsalem** [comment]
Sorry for this confusing,
But when try version 4.3.0, well it worked at first, but when opening multiple instance of my app
first instance dialog disappear when I set topmost = true even if window is in focus

![image](https://user-images.githubusercontent.com/35755221/150657623-617786a2-2354-449c-ac94-3298aa2cb043.png)

**Comment by Erapchu** [comment]
Did you tried to set embedded style for dialog host control?

**Comment by Erapchu** [comment]
MaterialDesignEmbeddedDialogHost

**Comment by Keboo** [comment]
@a7medsalem when you are setting topmost, is that setting the flag on the dialog's parent window? If so, it is quite possible that the window is simply sitting on top of the dialog itself (since the dialog will be in a popup control which is its own window). If the suggestion above about using the embedded style "fixes" the issue, then I would suspect that the topmost flag on the window is the issue.

**Comment by a7medsalem** [comment]
> MaterialDesignEmbeddedDialogHost

Well, that works.

> @a7medsalem when you are setting topmost, is that setting the flag on the dialog's parent window? If so, it is quite possible that the window is simply sitting on top of the dialog itself (since the dialog will be in a popup control which is its own window). If the suggestion above about using the embedded style "fixes" the issue, then I would suspect that the topmost flag on the window is the issue.

Yes, it's the dialog parent window flag,
I set the embedded style and it worked, in version 4.3.0 and above, the problem were in-consistence, when I open 3 instance for example, the dialog appear in on or two windows and the other not, if I toggle the top most more times it may appear or disappear, and yes sometimes the dialog appears begin the window when I minimize it

**Comment by Xaalek** [comment]
Is the issue solved?

**Comment by a7medsalem** [comment]
> Is the issue solved? @a7medsalem

Solved by using MaterialDesignEmbeddedDialogHost.
