### ISSUE TITLE
Resource can't be added to application

### ISSUE THREAD

**Issue by its-mrarsikk** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2569]
# How to recreate
I added this nugget to solution, and inserted that part into `App.xaml`:
```xaml
<Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
```

# Errors popped up
This error (but with different files) pop ups 4 times:
```cs
XDG0062
Failed to load file or assembly 'MaterialDesignThemes.Wpf, Culture=neutral' or one of its dependencies.
The specified file cannot be found.
```

**Comment by Keboo** [comment]
Hi @its-mrarsikk 

XDG0062 Is a XAML designer issue, not actually a compiler issue (despite appearing as such in the error output).
A quick fix that often can address these issues, is close all tabs in Visual Studio, close and re-open Visual Studio then rebuild the project.

A couple additional questions:
- Which version of Visual Studio are you running?
- Which version of .NET is your app targeting?
- When you add a NuGet, do you see a PackageReference in your csproj file or is it added to a packages.config file?

**Comment by its-mrarsikk** [comment]
I sincerely apologize for making you wait for such a long time. Here are my answers:

1: 2022 Professional
2: 6.0.3 (numbers after 6 may be inaccurate)
3: In both

**Comment by Keboo** [comment]
Your answer to #3 is what interests me the most. Typically, you would _either have_ PackageReference or a packages.config. I am wondering if the presence of both is what is messing up the designer. If you are using PackageReference within your csproj, then it should be fine to remove the packages.config. 

A few follow-up things.
1. I am assuming that your project still compiles are runs? or are you seeing errors when it starts?
2. Are you able to share your csproj file? Based on the described state, is this a project that was upgraded, or is this a new project?
3. Can you check your package management settings (Tools>>Options>>NuGet Package Manager>>General)? I would expect the checkboxes for "Allow NuGet to download missing packages" and "Automatically check for missing packages during build in Visual Studio" to be checked. I would also expect the default package management format to be set to PackageReference. 
4. Can you run a build with detailed logging enabled (`dotnet build -v d`) and share the output?

**Comment by its-mrarsikk** [comment]
I really don't know how, but this error just fixed itself. I was restarting VS many times, but that times it was returning middle finger, but this time it just disappeared! Also, Keboo, you're a cool guy :)
