### ISSUE TITLE
Tooltips in popup disappear after a short delay in .NET6.0

### ISSUE THREAD

**Issue by sebaJoSt** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2574]
I tried to upgrade my app from .NET 5.0 to .NET6.0 and noticed this tooltip issue in popups:

## Expected behavior .NET 5.0
![Net5_0](https://user-images.githubusercontent.com/388152/152988834-9d54e22f-dc41-40a9-a5f5-81c46b440b70.gif)

## Behavior in .NET 6.0
![Net6_0](https://user-images.githubusercontent.com/388152/152988861-1502a37c-7dc2-45b4-9426-95b4d33411ca.gif)

Installed is latest version MaterialDesignThemes 4.4.0-ci74

**Comment by giganoide** [comment]
I have the same problem.

**Comment by Keboo** [comment]
Will check, but I suspect this is a WPF issue and not something fixable in this library. It appears there is working going on to address these. Also note you version of .NET 6 that you are running (`dotnet --list-runtimes`).

https://github.com/dotnet/core/issues/7268
https://github.com/dotnet/wpf/pull/6063
