### ISSUE TITLE
Can the IsCheked property of the ToggleButton be set to Indeterminate?

### ISSUE THREAD

**Issue by saklanmaz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2576]
Hi,

What I want to ask is actually I get the following error when I set the IsCheked property `{x:Null}` for the ToggleButton, which is explicitly stated in the title. Is there a way to use this feature?

```
IndeterminateCheck name cannot be found in the name scope of 'System.Windows.Controls.Grid'.
```

**Comment by StefanoRivolta-Previero** [comment]
I think the control you want is CheckBox. ToggleButton can't be set to null, but CheckBox can

**Comment by saklanmaz** [comment]
Yes there is for CheckBox but I need ToggleButton. Can you help if there is a way?

**Comment by MichelMichels** [comment]
@saklanmaz This question is out of scope for this library as it has nothing to do with Material Design in XAML.

The answer you seek, is found in the MSDN docs: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.togglebutton.ischecked?view=windowsdesktop-6.0
You need to set `IsThreeState` to true.
