### ISSUE TITLE
Exception Argument cannot be null in DataGrid using IDataErrorInfo and moving focus between cells in error and not in error.

### ISSUE THREAD

**Issue by gitjsdr26** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2586]
I got an Exception argument cannot be null when moving the focus with the mouse click between cells.
Continuing application execution crashed the application.

DataGrid DataContext is binded to an ObservableCollection with element using IDataErrorInfo interface.
DataGrid has the MaterialDesignDataGrid style.
I'm using MaterialDesign for XAML v4.3.0.

The Exception occured in the file `DataGridAssist.cs`, in the method `AllowDirectEditWithoutFocus()` on this line :
`dataGrid.CurrentCell = new DataGridCellInfo(dataGridCell);`

**DataGrid sample :**
![image](https://user-images.githubusercontent.com/60319431/155860456-89c66c3f-c709-4643-97ad-fc5d33bf6658.png)

**Exception in Visual Studio :**
![image](https://user-images.githubusercontent.com/60319431/155860468-35bee023-256f-46c1-98ac-bb1b4e042065.png)

**This is the Exception text :**
26/02/2022 22:45:25:065;Fatal;Global Exception catch : ExceptionObject=<System.ArgumentNullException: La valeur ne peut pas être null. Nom du paramètre : element  à System.Windows.Automation.Peers.UIElementAutomationPeer.FromElement(UIElement element)  à System.Windows.Controls.DataGrid.CellAutomationValueHolder.TrackValue()  à System.Windows.Controls.DataGrid.ReleaseCellAutomationValueHolders()  à System.Windows.Controls.DataGrid.OnExecutedCommitEdit(ExecutedRoutedEventArgs e)  à System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)  à System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)  à System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)  à System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)  à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)  à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)  à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)  à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)  à System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)  à System.Windows.Controls.DataGrid.EndEdit(RoutedCommand command, DataGridCell cellContainer, DataGridEditingUnit editingUnit, Boolean exitEditMode)  à System.Windows.Controls.DataGrid.OnCurrentCellChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)  à System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  à System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)  à System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)  à System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)  à System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)  à System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)  à MaterialDesignThemes.Wpf.DataGridAssist.AllowDirectEditWithoutFocus(Object sender, MouseButtonEventArgs mouseArgs) dans D:\PROJETS\Outils Externes\Jas Suite\branches\Superviseur WysiJas\Libraries\Material Design In XAML\MaterialDesignThemes.Wpf\DataGridAssist.cs:ligne 234  à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)  à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)  à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)  à System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)  à System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)  à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)  à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)  à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)  à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)  à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)  à System.Windows.Input.InputManager.ProcessStagingArea()  à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)  à System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)  à System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)  à System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)  à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)  à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)  à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)  à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)  à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)  à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)  à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)  à System.Windows.Application.RunDispatcher(Object ignore)  à System.Windows.Application.RunInternal(Window window)  à JasSuite.App.Main()>, sender=<Nom :JasSuite.exe Aucune stratégie de contexte. >;
Une exception non gérée du type 'System.ArgumentNullException' s'est produite dans PresentationCore.dll
La valeur ne peut pas être null.

**Comment by Keboo** [comment]
I am unfortunately not able to replicate this failure. Can you provide more details or an example project showing the exception?

**Comment by gitjsdr26** [comment]
I reproduced only one time this failure in Debug Mode.
Sorry, I tried to get maximum information above while this exception raised, but I've no more details to provide.
I thought it was possible to find clues by code analysis with the information provided.

**Comment by gitjsdr26** [comment]
Additional information :
MahApps is used in conjunction with Material Design XMAL to manage error notification.

**Comment by gitjsdr26** [comment]
I didn't reproduced this issue since las comment.
