### ISSUE TITLE
Outlined NumericUpDown not displayed correctly when disabled

### ISSUE THREAD

**Issue by Int32Overflow** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2592]
If the NumericUpDown with the style "MaterialDesignOutlinedNumericUpDown" was disabled (IsEnabled=false), then a wrong style is displayed.

**Versions:**
- MahApps.Metro: 2.4.9
- MaterialDesignThemes: 4.3.0
- MaterialDesignThemes.MahApps: 0.2.0

**Used Style:** `MaterialDesignOutlinedNumericUpDown`

**IsEnabled=true**
![grafik](https://user-images.githubusercontent.com/20139038/156523117-5b811faa-03f6-461e-a388-5545492412f6.png)

**IsEnabled=false**
![grafik](https://user-images.githubusercontent.com/20139038/156523181-aa224c85-48f9-4027-93cb-fbe4aa5be1ee.png)

**Comment by MichelMichels** [comment]
It seems to me that the NumericUpDown control is not supported by this repository. I don't know if this is still under active development.

**Comment by MichelMichels** [comment]
Closing due to staleness and out of scope.
