### ISSUE TITLE
DataGridComboBoxColumn.IsEditable displays error when exiting editing

### ISSUE THREAD

**Issue by Soraily** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2595]
IsEditable = True, enter the value of the ItemSource does not exist after submitting the cell display blank instead of entering the value.
The related content on the web does not solve this problem.
Please help me, thanks!

**Comment by Soraily** [comment]
Enter Test as shown below, Exit editing status is not displayed
![image](https://user-images.githubusercontent.com/56372650/157813398-ba5496db-71ef-4699-9b2d-faf1764029ca.png)

my xaml
```
                    <materialDesign:DataGridComboBoxColumn
                        TextBinding="{Binding Food}"
                        IsEditable="True">
                    </materialDesign:DataGridComboBoxColumn>
```

**Comment by Xaalek** [comment]
Since it's a combobox, you're not supposed to add values to the list.
IsEditable = True simply means that you can type with the keyboard to find a value in the ComboBox more easily

**Comment by Soraily** [comment]
> Since it's a combobox, you're not supposed to add values to the list. IsEditable = True simply means that you can type with the keyboard to find a value in the ComboBox more easily

Indeed . But the behavior of the data grid column is not consistent with the normal drop down box behavior. Is there any way to make IsEditable work properly in the data grid column as a normal combo box.

**Comment by Xaalek** [comment]
I don't know but if you want a real ComboBox you can use a DataGridTemplateColumn and put the ComboxBox you want inside
```
<DataGridTemplateColumn>
	<DataGridTemplateColumn.CellTemplate>
		<DataTemplate>
			<ComboBox IsEditable="True"/>
		</DataTemplate>
	</DataGridTemplateColumn.CellTemplate>
</DataGridTemplateColumn>
```
