### ISSUE TITLE
Error message for MaterialDesignOutlinedTextBox should has same margin/padding as HelperText

### ISSUE THREAD

**Issue by lszczygielek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2596]
Error message for `MaterialDesignOutlinedTextBox` should has same margin/padding as `HelperText`.

![helper-text](https://user-images.githubusercontent.com/41156511/158069693-2124370f-4597-42f7-81d3-04b23e3f946c.png)
![validation-error](https://user-images.githubusercontent.com/41156511/158069535-ceb2ec9c-b1f3-461e-8b7d-487371a49dcf.png)
```
<TextBox Style="{StaticResource MaterialDesignOutlinedTextBox}"
		 materialDesign:HintAssist.Hint="Category name*"
		 materialDesign:HintAssist.HelperText="*Required"/>
```

Side note: I think that the issue is connected with PR https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2217 that fixed the padding specification on Filled or Outlined TextBox style. Unfortunately it doesn't cover validation template.

**Comment by Xaalek** [comment]
The margin should also be corrected for other types of control. The margin is currently only correct on the textbox control. When we look at the password control, we notice that the margin is not good
![image](https://user-images.githubusercontent.com/54487782/159238564-75f8e1f1-c23e-413f-9664-40ea12b802c6.png)

**Comment by Xaalek** [comment]
The HelperText issue has been fixed https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2648

Now we need to solve the problem with the validation template.

- [x] HelperText template
- [ ] Validation template

**Comment by Xaalek** [comment]
The task is available if someone wants to solve the issue with the validation style

**Comment by nicolaihenriksen** [comment]
@Xaalek I believe the linked PR should solve the validation error margin issue.

**Comment by Xaalek** [comment]
@nicolaihenriksen From what I remember, the styling was incorrect for the outlined and filled fields. This was for the TextBox, Password, ComboBox, DatePicker and RickTextBox controls.
We should check if all the controls are in accordance with the specs https://material.io/components/text-fields

**Comment by nicolaihenriksen** [comment]
@Xaalek Indeed you are correct. I will push more commits to the PR fixing the remaining ones...
