### ISSUE TITLE
How do I modify the animation duration of Expander

### ISSUE THREAD

**Issue by shusongLu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2599]
I don't know how to cover ExpanderStyle
`<Duration x:Key="ExpandDuration">0:0:0.250</Duration>
    <Duration x:Key="CollapseDuration">0:0:0.200</Duration>`

**Comment by Erapchu** [comment]
Hello
1 option: use the same style (copy it to your resource dictionary) and set ExpandDuration
2 option: use the same style (copy it to your resource dictionary) and add property to style like ExpanderAssist.HeaderBackground, for example ExpanderAssist.ExpandDuration:

`<Setter Property="wpf:ExpanderAssist.ExpandDuration" Value="0:0:0.4" />`

And then just apply that style + set wpf:ExpanderAssist.ExpandDuration where you want it. Seems like it was planned but not implemented.
