### ISSUE TITLE
TabControl - TabItem Header text is not visible

### ISSUE THREAD

**Issue by viktorspacil** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2602]
Hi,
I tried to use TabControl in my project (using nuget, version 4.4.0-ci94) so I basically copied following example from the demo project:
```
<TabControl 
            materialDesign:ColorZoneAssist.Mode="PrimaryMid"
            Style="{StaticResource MaterialDesignFilledTabControl}">
    <TabItem Header="TAB 1">
        <TextBlock Margin="8"
                   Text="PrimaryMid Tab 1" />
    </TabItem>
    <TabItem Header="TAB 2">
        <TextBlock Margin="8"
                   Text="PrimaryMid Tab 2" />
    </TabItem>
</TabControl>
```

But the result is that header text (TAB 1, TAB 2) is not visible and also the bottom border of the TabItem is not visible when the tab is selected. There is some problem with the foreground (screenshot from my project):
![image](https://user-images.githubusercontent.com/6149217/158971987-f744e5cf-fd88-4cd9-99a6-63d5ab175491.png)

It should look like this (screenshot from demo project): 
![image](https://user-images.githubusercontent.com/6149217/158972335-ae262980-3d40-4de1-8d02-e1728cacef5d.png)

I am able to set the TabItem header text only like this:
```
<TabItem>
    <TabItem.Header>
        <StackPanel Orientation="Horizontal">
            <TextBlock Foreground="{DynamicResource PrimaryHueMidForegroundBrush}">Tab 1</TextBlock>
        </StackPanel>
    </TabItem.Header>
    <TextBlock Margin="8"
               Text="PrimaryMid Tab 1" />
</TabItem>
```

but this does not solve the problem with the missing (not visible) bottom border of the selected TabItem. Is it a bug or did I miss something? Thank you for any advice.

**Comment by shaggygi** [comment]
@viktorspacil This is a side question, but related to TabControl and styling.  I've been trying to use and not able to style like shown in the MaterialDesignTheme examples or what you've done above.

Seems like my app can't find the resource.  `Style="{StaticResource MaterialDesignFilledTabControl}"`

Is there something extra that needs to be added in App.xaml or elsewhere?

Any help is appreciated.

**Comment by ahmed-abdelrazek** [comment]
@shaggygi you need to use the pre-release nuget or compile the latest yourself from github

**Comment by shaggygi** [comment]
@ahmed-abdelrazek yup, that did the trick.  thank you.  any idea when the nuget version will be final release?

**Comment by ahmed-abdelrazek** [comment]
no, i guess when it's ready
we can ask @Keboo but i don't think we will get a better answer

**Comment by Keboo** [comment]
Hopefully the next release will be soon, I need to fix some of the deployment stuff (didn't realize I had broken it).

**Comment by Xaalek** [comment]
> The original problem still persists on released version 4.4.0 and even on 4.5.0-ci120. I have found out that when the application is running in the debug mode and I change the xaml on the fly (for example encapsulate TabControl to Grid) then the TabItem header text and bottom border pop out. When I stop and start the application again then problem is back. I have also found out that the style "MaterialDesignTabItem" (version 4.4.0) looks like this:
> 
> ```
> <Style x:Key="MaterialDesignTabItem" TargetType="{x:Type TabItem}">
>         <Setter Property="FocusVisualStyle" Value="{StaticResource FocusVisual}" />
>         <Setter Property="Foreground" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(TextElement.Foreground)}" />
>         <Setter Property="Padding" Value="16,12" />
>         <Setter Property="Height" Value="48" />
>         <Setter Property="MinWidth" Value="90" />
>         <Setter Property="MaxWidth" Value="360" />
>         <Setter Property="Feedback" Value="{DynamicResource MaterialDesignFlatButtonRipple}" />
>         <Setter Property="Mode" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Mode)}" />
>         <Setter Property="Background" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Background)}" />
>         <Setter Property="Foreground" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Foreground)}" />
>         <Setter Property="Template">
> ```
> 
> But when I am debugging the demo application the style "MaterialDesignTabItem" looks like this:
> 
> ```
> <Style x:Key="MaterialDesignTabItem" TargetType="{x:Type TabItem}">
>         <Setter Property="FocusVisualStyle" Value="{StaticResource FocusVisual}" />
>         <Setter Property="Foreground" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(TextElement.Foreground)}" />
>         <Setter Property="Padding" Value="16,12" />
>         <Setter Property="Height" Value="48" />
>         <Setter Property="MinWidth" Value="90" />
>         <Setter Property="MaxWidth" Value="360" />
>         <Setter Property="wpf:RippleAssist.Feedback" Value="{DynamicResource MaterialDesignFlatButtonRipple}" />
>         <Setter Property="wpf:ColorZoneAssist.Mode" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Mode)}" />
>         <Setter Property="wpf:ColorZoneAssist.Background" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Background)}" />
>         <Setter Property="wpf:ColorZoneAssist.Foreground" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(wpf:ColorZoneAssist.Foreground)}" />
>         <Setter Property="Template">
> ```
> 
> There is a difference in the setting of background/foreground instead of wpf:ColorZoneAssist.Background/wpf:ColorZoneAssist.Foreground".

Also `wpf:ColorZoneAssist.Mode` and `wpf:RippleAssist.Feedback`

**Comment by Keboo** [comment]
FWIW, the issue appears to be the foreground color not making to the content. I started work on a branch to fix it (mostly just a test for the moment). https://github.com/Keboo/MaterialDesignInXamlToolkit/tree/fix2602

**Comment by viktorspacil** [comment]
Hi,
I took todays master and tried  the fix. Text foreground problem (TabItem Header) is gone but the bottom border (current tab highlight) still persists, bottom border is still missing.

**Comment by GoranVDB** [comment]
Hi,

I encountered the same problem as [viktorspacil](https://github.com/viktorspacil) when using the default style (not filled) where the header text and the highlight of the selected item wasn't being shown. After updating to the latest pre-release the header text is now being shown but the background of the tabitems has changed to the PrimaryMid color and the highlight is indeed still missing.

**Comment by NeilMacMullen** [comment]
I've also noticed that the ContextMenu background appears to be missing.

**Comment by Xaalek** [comment]
@NeilMacMullen this is fixed in the latest 4.5.0 preview NuGet package

**Comment by NeilMacMullen** [comment]
Super - thanks @Xaalek

**Comment by SilentSammy** [comment]
This is a temporary workaround:

`    <TabControl Margin="10" Style="{DynamicResource MaterialDesignFilledTabControl}" >
        <TabControl.Resources>
            <Style TargetType="TextBlock" x:Key="HeaderText">
                <Setter Property="Foreground" Value="{DynamicResource MaterialDesignBody}" />
                <Setter Property="FontWeight" Value="Regular" />
                <Setter Property="FontSize" Value="18" />
                <Setter Property="FontFamily" Value="{DynamicResource MaterialDesignFont}" />
            </Style>
        </TabControl.Resources>
        <TabItem>
            <TabItem.Header>
                <TextBlock Text="Tab header text" Style="{StaticResource HeaderText}" />
            </TabItem.Header>
            <TextBlock Margin="8" Text="This tabitem has a textblock in its header.&#x0a;Every property in the style had to be manually set." />
        </TabItem>
     </TabControl>`
