### ISSUE TITLE
A Better Popup

### ISSUE THREAD

**Issue by KaiHuaDou** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2605]
I am developing an application that i want to use the menu like the Google Chrome, I am trying the things in this toolkit, but:
1. PopupBox has a good performance but i can't cascade them
2. Menu can cascade but i can't easily change the font or the color especially display the translation.
I hope there's a solution of this or a new control like this.

**Comment by Erapchu** [comment]
Hello!
Do you mean that menu?

![image](https://user-images.githubusercontent.com/37536541/159209973-7de271a1-aea8-4e1b-9726-621a614a315f.png)

You may use Menu control for it, set menu items inside. Please correct me if wrong. In the menu item template you need to set the same icon (three dots) and style it like in Google Chrome

**Comment by KaiHuaDou** [comment]
Thanks, i've try it and it works perfectly, but I found that the font and the color are not as same as another control, the color gots the problem like my another issue #2656. Because there are not so many menuitems, so i set them one by one, Are my color settings goes wrong?
```
<materialDesign:CustomColorTheme BaseTheme="Light" PrimaryColor="#FF1A73E8" SecondaryColor="Black">
    <materialDesign:CustomColorTheme.ColorAdjustment>
        <materialDesign:ColorAdjustment DesiredContrastRatio="1" Contrast="None" />
    </materialDesign:CustomColorTheme.ColorAdjustment>
</materialDesign:CustomColorTheme>
```

**Comment by Keboo** [comment]
Hi @KaiHuaDou did you setup the Window control correctly? Typically you will set it up using `Style="{StaticResource MaterialDesignWindow}" `. Typically this is what will setup most of the colors and fonts for all of the controls within the window. You can see an example of this [in the demo app](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/MainWindow.xaml#L17).

**Comment by KaiHuaDou** [comment]
Thank you very much , it works perfectly, I think this issue can be closed.
