### ISSUE TITLE
ContextMenu Background Changed Recently (After 4.4.0-ci94)

### ISSUE THREAD

**Issue by shaggygi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2613]
Appears the background for ContextMenu is now transparent after 4.4.0-ci94.  Also noticed this on the built-in one for TextBox.  Is there a recommended style?  

Before
![image](https://user-images.githubusercontent.com/2956825/159394625-8e4d599a-804e-4b44-ab10-55c5914ca4e3.png)

After
![image](https://user-images.githubusercontent.com/2956825/159394761-5ab3d7c7-0234-4249-98a5-353ef67090c1.png)

**Comment by Keboo** [comment]
Looks like a dup of #2606. It was fixed earlier today and the fix will be in tonight's nightly release.
