### ISSUE TITLE
TabControl multi-row broken after update 4.3.0 -> 4.4.0

### ISSUE THREAD

**Issue by JanZeman** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2616]
Hello,

I haven't touched UI part of my project for many months. I do however regularly update NuGet packages including MaterialDesignThemes - most of the time without any problems. Today I updated from 4.3.0 -> 4.4.0 and noticed the Settings page broken. It is one huge TabControl with many tabs - intended to show two rows of tabs. After the update it shrank to one row only which makes it user unfriendly. It is couple of years back I designed this page, I do not remember (and I do not see it in the current code) I had to do anything special to get multi-row support.

Please see the two images.

4.3.0:
![image](https://user-images.githubusercontent.com/1670470/159800286-96a77d1b-f71a-455d-9144-071d003a3245.png)

4.4.0:
![image](https://user-images.githubusercontent.com/1670470/159800314-d8b78aec-e44b-40dc-baf5-35f9b0d7be1b.png)

Is this an intended change and I have to do anything special in my client code or is it a bug?

**Comment by Awsmolak** [comment]
Found this while checking for a different issue. But the toolkit _just_ introduced the tabcontrol style. So now that is being set as the default style for TabControl. And the tabitems are in a uniform grid that can't wrap. I'm not exactly sure how to do this, but to go back to what you had you need to set the style back to the WPF default for TabControl

**Comment by JanZeman** [comment]
Hi @Awsmolak, thank you for the tip. It's been a while I touched the UI but I remembered it is possible to create default styles by right-clicking, Edit Template > Edit the copy... That gave me slightly different version of the sample you posted.

Applying this manually created default style made it back to normal - multi-row displayed nicely.

I however hesitate closing the bug as multi-row should be supported as a standard feature imho. Let you guys to decide...

**Comment by ahmed-abdelrazek** [comment]
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2603

**Comment by Keboo** [comment]
So for the material design, multiple rows of tabs are not expected (that is a WPF design feature), so if the original WPF look and behavior is desired going back to the original WPF style is the way to go. The above mentioned options certainly work, however, there is an even easier option. Simply declare empty implicit styles targeting both the `TabControl` and the `TabItem`.
```xaml
<Style TargetType="TabControl" />
<Style TargetType="TabItem" />
```
If you want that to apply to your entire app, you can put that the App.xaml (after the material design references). If you want it to apply to only a specific window, or control, you can place it in the Resources collection at whatever scope makes sense.
