### ISSUE TITLE
ContextMenu Styles Broken

### ISSUE THREAD

**Issue by Catalan-1ap** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2617]
The error occurred in the new version of package 4.4.0

[Repository with problem](https://github.com/Catalan-1ap/ReproduceMaterialDesignContextMenuError) 

## How to reproduce?

Right click on window area

## Expected Behaviour (4.3.0)
![](https://github.com/Catalan-1ap/ReproduceMaterialDesignContextMenuError/blob/master/blob/Expected.png?raw=true)

## Actual Behaviour (4.4.0)
![enter image description here](https://github.com/Catalan-1ap/ReproduceMaterialDesignContextMenuError/blob/master/blob/Actual.png?raw=true)

**Comment by Keboo** [comment]
Thank you for the reproduction repo. I believe this issue is already fix. Can you test with the latest 4.5.0 _preview_ NuGet package to confirm?

**Comment by Catalan-1ap** [comment]
> Thank you for the reproduction repo. I believe this issue is already fix. Can you test with the latest 4.5.0 _preview_ NuGet package to confirm?

Confirmed, in the preview version this is fixed, forgive me for not checking, its also a duplicate :(

**Comment by Keboo** [comment]
No problem. Happy coding!
