### ISSUE TITLE
As of V4.4.0 Treeview items not indented if no subitems are present

### ISSUE THREAD

**Issue by TinoMSoft** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2618]
After updating from version 4.3.0 to 4.4.0 the treeview items without subelement are no longer indented. In the release notes I could not find any TreeviewItem or hierarchical data template changes.

`<TreeView Grid.Column="0" 
                      Grid.Row="0"
                      Grid.RowSpan="2"
                      x:Name="DirectoryTreeView"
                      Margin="0,47,0,0" 
                      TreeViewItem.Expanded="TreeViewItem_OnExpanded"
                      TreeViewItem.Selected="TreeViewItem_OnSelected"
                      ItemsSource="{Binding Path=Directories}"
                      ContextMenu="{StaticResource DirectoryContextMenu}"
                      IsEnabled="{Binding Path=IsFoldersLoading, Converter={StaticResource BooleanNegateConverter}}">
                <TreeView.Resources>
                    <HierarchicalDataTemplate DataType="{x:Type models:DirectoryInfoModel}" ItemsSource="{Binding SubDirectories}">
                        <StackPanel Orientation="Horizontal">
                            <materialDesign:PackIcon Style="{StaticResource PackIconStyle}" Kind="FolderOpen" Width="20" Height="20" />
                            <TextBlock Text="{Binding Name}" Margin="0 2 0 0" />
                        </StackPanel>
                    </HierarchicalDataTemplate>
                </TreeView.Resources>
            </TreeView>`

![4 4](https://user-images.githubusercontent.com/26662029/160020066-c1c72de0-d1e8-4651-8a63-f8176d7628f9.png)
![4 3](https://user-images.githubusercontent.com/26662029/160020069-e3bacd05-381c-4e13-afeb-73e33573ed7d.png)
Can you please check this?

Tino

**Comment by slow-steps** [comment]
I think this is bad change and want to be rolled back.

**Comment by Keboo** [comment]
Reverting the default back to be hidden and added in a new attached property to allow people to change that default.
