### ISSUE TITLE
MaterialDesignTheme.PopupBox.xaml missing in the ResourceDictionary

### ISSUE THREAD

**Issue by Bayerischen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2619]
I'm trying to create a new PopupBox style based on MaterialDesignMultiFloatingActionPopupBox, I have read the source code so i know there is such a style in MaterialDesignThemes.Wpf\Themes\MaterialDesignTheme.PopupBox.xaml. But the IDE showed me that there is no such a resource called MaterialDesignMultiFloatingActionPopupBox. So i checked MaterialDesignTheme.Defaults.xaml and found that MaterialDesignTheme.PopupBox.xaml is not included in the ResourceDictionary.
So is this expected or just a mistake? Let me know if i did not make myself clear.

**Comment by Erapchu** [comment]
It's included in Generic.xaml - this resource dictionary for custom controls such as PopupBox. It includes styles that will be used on custom controls initializing

**Comment by Bayerischen** [comment]
> It's included in Generic.xaml - this resource dictionary for custom controls such as PopupBox. It includes styles that will be used on custom controls initializing

Thank you for the reply!

**Comment by Erapchu** [comment]
No problem. If you want to create new style based on MaterialDesignMultiFloatingActionPopupBox for example, you need to add 
 popupbox dictionary to your resource dictionary like here:

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.WindowCommands.xaml

**Comment by Bayerischen** [comment]
> No problem. If you want to create new style based on MaterialDesignMultiFloatingActionPopupBox for example, you need to add popupbox dictionary to your resource dictionary like here:
> 
> https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.MahApps/Themes/MaterialDesignTheme.MahApps.WindowCommands.xaml

thanks again, I'll have a try
