### ISSUE TITLE
UI display error

### ISSUE THREAD

**Issue by z2hteam** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2620]
When opening a command with the right mouse

![image](https://user-images.githubusercontent.com/78490340/160066860-306d5fe6-9be5-4c39-ba27-37022c327a4b.png)

**Comment by lszczygielek** [comment]
Probably fixed, but not released yet. https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2606

**Comment by Keboo** [comment]
Yep looks like it has been fixed. You can confirm with the latest preview NuGet package
