### ISSUE TITLE
Grey buttons, and icons are showing up as a white rectangle inside a yellow rectangle on the designer.

### ISSUE THREAD

**Issue by realrandombeans** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2622]
![image](https://user-images.githubusercontent.com/97028115/160241707-4da802ca-a26b-4cca-84cd-98e1d6cdf534.png)

For some reason, my icons are suddenly showing up like the image, and the buttons are discoloured. It only shows in the designer, but I'm not sure why it's like that. Please help.

![image](https://user-images.githubusercontent.com/97028115/160241753-2e1be7c1-9873-4048-bfed-7e2320d39974.png)
It's meant to look like this.

**Comment by Erapchu** [comment]
Hello
Did you merge resource dictionaries according wiki? https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start

**Comment by Xaalek** [comment]
@realrandombeans Do you still have this problem?

**Comment by MichelMichels** [comment]
Closed due to lack of response.
