### ISSUE TITLE
Snackbar with Message Box throws error in newer versions

### ISSUE THREAD

**Issue by SilentSammy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2627]
After version 3.1.3, if a snackbar's action is set to display a message box, and that message box is closed after the snackbar closes, the application will throw a "System.ObjectDisposedException: 'Safe handle has been closed'" exception.

Step 1
![image](https://user-images.githubusercontent.com/51086739/160832255-061e45c1-4df7-4778-987e-a64e24b7ad39.png)

Step 2
![image](https://user-images.githubusercontent.com/51086739/160832333-b27521e7-1278-4140-a9eb-2e6976d1b0ad.png)

Step 3
![image](https://user-images.githubusercontent.com/51086739/160832364-db263e23-0e20-4844-8d28-7dffdbac86ae.png)

Step 4 (After closing the message box)
![image](https://user-images.githubusercontent.com/51086739/160832427-2fa52424-d381-4307-8462-327d53b9a82d.png)

This exception is only thrown on versions after 3.1.3.
Maybe it's possible to add a bool argument to Enqueue() or a MessageQueue property to execute the older code?

Here's the link to the test app's repo: https://github.com/SilentSammy/SnackbarBug
Also attached is the project as a zip file just in case: [SnackbarBug.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/8380335/SnackbarBug.zip)

**Comment by Erapchu** [comment]
There's an error in code @Keboo 
SnackbarMessageQueue => CreateAndShowMessage => anonymous delegate snackbarMessage.ActionClick subscribe.
We dispose EventWaitHandle after some time and then call .Set() method on it - it's unsafe and application may shutdown immediately.
At least I suggest to add this check

```
if (++clickCount == 1)
    DoActionCallback(messageQueueItem);
if (actionClickWaitHandle.SafeWaitHandle.IsInvalid || actionClickWaitHandle.SafeWaitHandle.IsClosed)
    return;
actionClickWaitHandle.Set();
```
