### ISSUE TITLE
Margin and Padding of HelperText don't match the specs

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2633]
Margin and Padding of HelperText don't match the specs.
The HelperText should be aligned with the Text.
This correction have to be made on :
- FilledPassword
- FilledDatePicker
- FilledCombobox
- OutlinedPassword
- OutlinedDatePicker
- OutlinedCombobox

I have already fixed the problem for most of the styles by taking the example of this PR : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2217
You can check my changes here : https://github.com/Xaalek/MaterialDesignInXamlToolkit/commit/eca7a836ca8fe97c3ef2bb102c0e3f67e4dc4780
I just need to fix the problem for the FilledCombobox, but a trigger is missing in `MaterialDesignTheme.ComboBox.xaml` for the property `wpf:TextFieldAssist.HasFilledTextField`

Should I add this trigger in the template?

**Comment by Keboo** [comment]
Yes I am good simply adding in that trigger.

**Comment by Xaalek** [comment]
I tried to add 
```
<Trigger Property="wpf:TextFieldAssist.HasFilledTextField" Value="True">
      <Setter Property="Padding" Value="16 8 12 8" />
      <Setter TargetName="HelperTextWrapper" Property="Margin" Value="16 0 0 0" />
</Trigger>
```

in the `<ControlTemplate.Triggers>` tag, but it doesn't change the padding and margin of the HelperText
![image](https://user-images.githubusercontent.com/54487782/162790207-8508222b-0a20-4d48-a30c-6a659f1432df.png)

Do I have to change anything in the code behind to make it work?

**Comment by Keboo** [comment]
So a few things need to be changed for that trigger to work:
1. Make sure the trigger is being applied in the triggers section of the `MaterialDesignFloatingHintComboBoxTemplate` control template.
2. Make sure to give the `Canvas` around the help text the name "HelperTextWrapper"
3. In the `MaterialDesignFilledComboBox` style set the `TextFieldAssist.HasFilledTextField` attached property to true (was a little surprised this was missing).
4.

**Comment by Xaalek** [comment]
Thank you, I was missing this setter `<Setter Property="wpf:TextFieldAssist.HasFilledTextField" Value="True"/>`
