### ISSUE TITLE
Tab Item and Context Menu Not Show Correctly

### ISSUE THREAD

**Issue by rasoulia** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2637]
This Nuget Package cause 2 problems
1. Context Menu Background is Transparent
2. Tab Item Show White and i have to use materialdesignextensions
this is my App.XAML Code:
i use 4.4.0 Version of Package.
` 
<materialDesign:BundledTheme BaseTheme="Inherit" PrimaryColor="Grey" SecondaryColor="Teal" ColorAdjustment="{materialDesign:ColorAdjustment}"/>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign3.Defaults.xaml"/>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/Generic.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignExtensions;component/Themes/MaterialDesignDarkTheme.xaml" />
`

**Comment by xqyjlj** [comment]
Yes, I found this problem too, I'm now back to 4.3.0

**Comment by Keboo** [comment]
Both of these issues should now be fixed. The 4.5.0 preview package that will go out tonight will contain both fixes.
