### ISSUE TITLE
Large values using MaterialDesignDiscreteSlider will cause bad visual

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#264]
A large `Value` on the `Slider` control using the `MaterialDesignDiscreteSlider` style will cause the rendered control to look bad.

![slider](https://cloud.githubusercontent.com/assets/1139118/13138295/9c6de662-d626-11e5-81bb-98548310ce0c.gif)

It would be nice if the balloon would grow to ensure the content will fit.

**Comment by Gusdor** [comment]
I am struggling to get this style working at all. Has there been any update to this?
