### ISSUE TITLE
What is Presenoker?

### ISSUE THREAD

**Issue by SeynalKim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2645]
Every time I run the demo, my Windows Defender keeps alerting me about this `Presenoker`

**Comment by Keboo** [comment]
I am afraid I am going to need some more context. That word [does not appear within this repository](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/search?q=Presenoker), so I am not sure what you are seeing.

**Comment by ahmed-abdelrazek** [comment]
PUA:Win32/Presenoker "Potentially Unwanted Application" if you/your organization cranked your windows security up you might get that because the demo app isn't signed -try to run windows update- if you downloaded the demo from GitHub or compiled it yourself you shouldn't worry

if you got the demo from here didn't mess with windows default security settings and your windows is up to date you might have a bigger problem here

**Comment by SeynalKim** [comment]
I'm still investigating this issue. As of now, I tried to remove it as Windows Security suggested. Everything is up to date and I get the demo from here.

**Comment by SeynalKim** [comment]
I have no other machine to test the demo if I'll get the same notification from Windows Security. I also tried to scan my whole system and found nothing and I don't have any crack-software whatsoever in my machine. 

I'm running Windows 11 anyway.

**Comment by ahmed-abdelrazek** [comment]
scan your system with https://www.malwarebytes.com/mwb-download/thankyou also try https://support.microsoft.com/en-us/windows/help-protect-my-pc-with-microsoft-defender-offline-9306d528-64bf-4668-5b80-ff533f183d6c

**Comment by SeynalKim** [comment]
After manually scanning all my directories one by one, I found the culprit.

This [AVC (Any Video Converter) ](https://www.any-video-converter.com/en6/for_video_free/) that I downloaded years ago and synced to my OneDrive is the one that is being reported. But I'm not sure why my Windows Security is alerting me about it every time I run the demo.

**Comment by SeynalKim** [comment]
I'm closing this issue now as I think the problem is non-related.
