### ISSUE TITLE
The default alpha of foreground is 87%

### ISSUE THREAD

**Issue by KaiHuaDou** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2656]
I am trying to help one of my friend to use this toolkit, but he found that all of the label text's alpha are 87%, it means the color is #DD000000 not #FF000000, so the only possible solution is set them to 100% one by one. But there's hundreds of label at there, is there anything wrong?
![image](https://user-images.githubusercontent.com/74781268/164883478-0bcce244-0ecd-4aa8-9714-84bae1e5ea58.png)

**Comment by Xaalek** [comment]
It's an intended behavior.
The text opacity is described as follows in the specs :
https://material.io/design/color/text-legibility.html#text-backgrounds

**Comment by Keboo** [comment]
Hi @KaiHuaDou it sounds like what you are wanting is an [implicit style](https://michaelscodingspot.com/explicit-implicit-and-default-styles-in-wpf/) on label. This will let you define a color once and apply it to all labels within the application.

**Comment by Xaalek** [comment]
In App.xaml:
```
<Application.Resources>
<Style TargetType=“Label”>
<Setter Property=“Foreground” Value=“Black”/>
</Style>
</Application.Resources>
```
