### ISSUE TITLE
Outlined card style is missing

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2658]
As you can see in the specs, there is an outlined card style : 
https://material.io/components/cards

We don't have this style in the library. It would be nice to implement it.

**- Edit -**
- [ ] Create an Elevated style that matches the current style
- [ ] Create an Outlined style that matches the specs

**Comment by Keboo** [comment]
Agreed, this would be a nice addition.

**Comment by Xaalek** [comment]
So we have to create two styles for the card? One for the Elevated style and one for the Outlined style, right?

**Comment by Keboo** [comment]
Correct
