### ISSUE TITLE
ListView- How do we customize Padding of the Column Header?

### ISSUE THREAD

**Issue by SeynalKim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2665]
I've been trying to set the padding of the header to none or 0 but had no luck until now. 

Let's say I have a listview; 

                   <ListView
                        Name="TransactionListView"
                        Grid.Row="2"
                        Focusable="False">
                        <ListView.View>
                            <GridView>
                                <GridView.Columns>
                                    <GridViewColumn Header="COLUMN 1" />
                                    <GridViewColumn Header="COLUMN 2" />
                                    <GridViewColumn Header="COLUMN 3" />
                                    <GridViewColumn Header="COLUMN 4" />
                                    <GridViewColumn Header="COLUMN 5" />
                                    <GridViewColumn Header="COLUMN 6" />
                                </GridView.Columns>
                            </GridView>
                        </ListView.View>
                        <ListViewItem Content="Test item" Focusable="False" />
                    </ListView>

Now those headers with the default padding, I wanted to set it to 0 (none) or probably custom size later, how can I do that? 

In DataGrid there is ` materialDesign:DataGridAssist.ColumnHeaderPadding="0 0 0 0"` but this doesn't seem to work in ListView.

**Comment by danielcarlstrom** [comment]
Hi,

I had the same issue, think I found something that works for me, perhaps give it a shot.

I followed the wiki for override [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Overriding-Material-Design-Styles) but did some tweaks found in another issue, skipping the `x:Key` part. Not sure if it mattered.

Anyways, I added an override file: `MaterialDesignThemes.Overrides.xaml` in a separate folder.

![image](https://user-images.githubusercontent.com/5818195/166887660-53f39293-6b51-451a-8a5b-369f2635b569.png)

Then, added this to the file, setting the padding to 7 for the header:
```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"                                     
                    xmlns:materialDesign="clr-namespace:MaterialDesignThemes.Wpf;assembly=MaterialDesignThemes.Wpf">

    <Style BasedOn="{StaticResource MaterialDesignListView}" TargetType="{x:Type ListView}">
        <Setter Property="materialDesign:DataGridAssist.ColumnHeaderPadding" Value="7" />
    </Style>

</ResourceDictionary> 
```

Finally, added my custom override to be merged in `App.xaml`:
```xaml
<Application x:Class="WpfWebService.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             StartupUri="MainWindow.xaml"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
                <ResourceDictionary Source="ThemeOverride/MaterialDesignThemes.Overrides.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```

Result:
![image](https://user-images.githubusercontent.com/5818195/166889088-b4a92ac1-ce3f-42ad-87bd-0a1f448c6e5f.png)

I guess you tried something similar but perhaps targeted the wrong element? 

/Daniel

**Comment by SeynalKim** [comment]
> ```
> materialDesign:DataGridAssist.ColumnHeaderPaddin
> ```

I see, so I literally need to override it. It works, thanks! I hope this option becomes available in the future.
