### ISSUE TITLE
TabControl - Shadow drops behind Card in TabItem

### ISSUE THREAD

**Issue by avanbremen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2667]
First of all, thanks for creating an amazing toolkit!

When using the `TabControl` with for example `materialDesign:ShadowAssist.ShadowDepth="Depth2"` and in the TabControl a `TabItem` that contains a `ScrollViewer` and `materialDesign:Card`s, the card will appear in front of the TabControl header shadow when scrolling (tested with v.4.4.0 and v4.5.0).

When only using a Toolbar `ColorZone`, without a TabControl, the same shadow issue will occur. This however can easily be fixed by adding `Panel.ZIndex="1"` to the Toolbar ColorZone and `Panel.ZIndex="0"` to the content `ScrollViewer`. This was discussed in [issue 647](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/647).

When using a TabControl, setting a `Panel.Zindex` on the TabControl, TabItem, and/or TabItem Content will not fix this issue. Perhaps this issue can be fixed by setting the right `Panel.ZIndex` on the TabItem Header and Content in the TabControl Style in [MaterialDesignTheme.TabControl.xaml](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/b8fba1b5840c7a59f237d54c3d6d08cd2a82403b/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TabControl.xaml).

![mdix-tabcontrol-shadow-issue](https://user-images.githubusercontent.com/25454736/166522960-032808a7-f63e-4ce5-8c9a-b25d6db11e9e.jpg)
_TabControl with shadow that appears behind cards_

Kind regards and all the best,
Arjan

**Comment by Xaalek** [comment]
The style has changed a little bit since (https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2779). We should check if the issue is still relevant.
