### ISSUE TITLE
TabControl - for TabStripPlacement Left or Right all headers remain in the horizontal position

### ISSUE THREAD

**Issue by DrCQ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2672]
Hi,

thanks for fixing the background issue. This introduced a new bug for `TabItems ` with `TabStripPlacement `set to `Left `or `Right`. All headers remain in the horizontal position (in difference to the 4.4.0 version).

![grafik](https://user-images.githubusercontent.com/49019093/167256240-c6851fa7-3c89-444a-ad7f-b095f4cecc9a.png)

Regards,
Christoph

**Comment by nicolaihenriksen** [comment]
@Xaalek @Keboo 
Is this still an issue? There are `TabControl` samples in the demo application for all `TabStripPlacement` variations and they seem to work just fine. Am I missing something?

**Comment by Xaalek** [comment]
@nicolaihenriksen Yes thank you, this problem no longer exists. I close the issue.
