### ISSUE TITLE
UniformCornerRadius Card property does not limit content

### ISSUE THREAD

**Issue by maydoc** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2687]
Hello guys, I was noticing something strange in different versions in relation to Material Design Themes, in 4.1.0 when I used the UniformCornerRadius property the edges "cut" the content inside the Card, but in 4.5.0 this doesn't happen, like you can see in the image.

I used this to my advantage to make certain designs

![Prancheta 1](https://user-images.githubusercontent.com/70946246/167874683-c13092ed-db91-4e3a-91fa-249d9cb4bfe6.png)

My first issue, sorry for any mistakes

**Comment by Xaalek** [comment]
Can you provide the XAML code of your example please ?

**Comment by maydoc** [comment]
I'm sorry for answering so late

```
<Grid Margin="50">
      <materialDesign:Card Width="441" Height="234" UniformCornerRadius="35">
          <Image Source="img.jpg"/>
      </materialDesign:Card>
</Grid>
```
