### ISSUE TITLE
DataGrid MaterialDesignDataGridTextColumnPopupEditingStyle caret and select-all issues

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#270]
Couple of issues with MaterialDesignDataGridTextColumnPopupEditingStyle:
1.  Caret is at the very beginning of the Text Box and no way to relocate it (with mouse or keys).
2.  There's no Select All option under mouse right-click menu... only Cut/Copy/Paste.  Only way to select all is Ctrl+A

**Comment by samirem** [comment]
I experience the same issues.

**Comment by Keboo** [comment]
I am closing this, since 1 appears fixed in the latest 3.1.1 release. I have logged #1781 to track the context menu feature request.
