### ISSUE TITLE
ComboBox and MaterialDataGridComboBoxColumn have inconsistent arrow icon size

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#271]
![capture](https://cloud.githubusercontent.com/assets/16761301/13375556/d470981a-dd70-11e5-8268-0b18620023ee.PNG)

ComboBox size looks better IMO

**Comment by Keboo** [comment]
Agreed the DataGrid template should be updated so that the drop down arrows match the combo box.
