### ISSUE TITLE
Transition animation appears blank

### ISSUE THREAD

**Issue by Case-Closed-X** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2712]
### Bug explanation

After a quick click of two buttons, the transition animation appears blank as shown in the video. I'm not sure it's a problem.

### Version

4.5.0

https://user-images.githubusercontent.com/50199528/170613627-0b700fb9-e193-481d-a09f-ebe1a91e950c.mp4

**Comment by Xaalek** [comment]
What is the expected behavior ? @Case-Closed-X

**Comment by Erapchu** [comment]
Hello, yes it's a problem related to animations in transitions. I think need to look deeper to understand where animations are overlapping. As a result we have blank page when user click very fast

**Comment by Erapchu** [comment]
We set opacity to zero when animations completed. I can prepare changes. As fast fix you need to decrease animation duration

**Comment by Erapchu** [comment]
I can reproduce described behavior in Transitions menu in Demo app just by pressing left/right arrows on keyboard.

Do we really need to set opacity explicitly to zero in CircleWipe:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/3de22172ce4ec50e7d7416e5fd34806d7e415381/MaterialDesignThemes.Wpf/Transitions/CircleWipe.cs#L46
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/3de22172ce4ec50e7d7416e5fd34806d7e415381/MaterialDesignThemes.Wpf/Transitions/CircleWipe.cs#L55

and SlideOutWipe:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/3de22172ce4ec50e7d7416e5fd34806d7e415381/MaterialDesignThemes.Wpf/Transitions/SlideOutWipe.cs#L38

after animations completed? Those events are follow each other and they can setup opacity unpredictable.
I think we can remove set opacity in events, anyway it should be done by animations?

**Comment by Xaalek** [comment]
Seems to be an old issue
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/975
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/939
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1130
