### ISSUE TITLE
ColorPicker

### ISSUE THREAD

**Issue by MasterProger** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2718]
### Bug explanation

When calling the DragDelta event on the Thump element, an error occurs if the Thump element is captured from the edge and dragged.
We need to remove the error.

I fixed the bug by adding code in my project

`private void SpectrumPickerThumb_DragDelta(object sender, DragDeltaEventArgs e)
{
var thumb = e.Source as Thumb;
var left = Canvas.GetLeft(thumb) + e.HorizontalChange + startThumbOffset.X;
var top = Canvas.GetTop(thumb) + e.VerticalChange + startThumbOffset.Y;
ApplyThumbPosition(left, top);
 }`

`private void PART_SpectrumPickerThumb_DragStarted(object sender, DragStartedEventArgs e)
        {
            startThumbOffset.X = e.HorizontalOffset;
            startThumbOffset.Y = e.VerticalOffset;
        }`

`private void PART_SpectrumCanvas_MouseMove(object sender, MouseEventArgs e)
{
          if (e.LeftButton == MouseButtonState.Pressed)
            {
                if (!PART_SpectrumPickerThumb.IsDragging)
                {
                    var position = e.GetPosition(SpectrumCanvas);
                    ApplyThumbPosition(position.X, position.Y);
                }
            }
}`

### Version

4.5.0

**Comment by MasterProger** [comment]
Необходимо исправить возвращаемое значение Hsb
Вместо dooble значение 0.1xxxxx, нужно чтобы возвращалось целочисленное значение от 0 - 100

**Comment by MasterProger** [comment]
> What is the Thumb element? Do you mean [Slider](https://material.io/components/sliders) ?

A circle in the canvas element that we define and choose a color.

**Comment by nicolaihenriksen** [comment]
@MasterProger Could the issues you are/were experience possibly have been solved by PR #2895 which is included in the latest release? I cannot seem to find an exact match of the code you provided, but the code changed in the PR is very similar, and thus could possibly be what you were referring to?!
