### ISSUE TITLE
Option in main (left sandwich) menu to display fan RPM in fan control cards when hiding fan speed cards

### ISSUE THREAD

**Issue by 0x6A7232** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2730]
What it says on the tin.  Expanding the fan control card for a small RPM readout seems preferable to either having a second set of cards to rename and watch, or loosing RPM readout.  Great program BTW!  Saw you mentioned on JayzTwoCents.
PS if you wanted to make it fancy you could include options for displaying as a meter instead of numbers for RPM.  Or even a color shading of the card.  But that's just a random idea I had when typing this up.

**Comment by Keboo** [comment]
Hi @0x6A7232 I am not sure you have the right project. This project is just a material design styling library, I suspect you are looking for a different project that leverages this project.

**Comment by 0x6A7232** [comment]
Oops.  Yeah I was trying to send this to https://github.com/rem0o/fancontrol.releases , my bad... sorry!
