### ISSUE TITLE
Changing border thickness of "MaterialDesignOutlinedDatePicker"

### ISSUE THREAD

**Issue by washburnit** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2737]
### Bug explanation

HI,

how could I change the border thickness of the control in the subject?
I've set the control as follows:

<DatePicker Name="dtLavo" Width="180" Style="{StaticResource MaterialDesignOutlinedDatePicker}" HorizontalAlignment="Left" Margin="20" mdix:HintAssist.Hint="Data Creazione" FontFamily="Century Gothic" FontSize="15" BorderThickness="2"/>

but is seems that it has no effect (probably I'm not doing in the correct way).
Thank you, regards.

Roberto

### Version

4.5.0

**Comment by Xaalek** [comment]
I just checked and indeed, the feature is missing for `MaterialDesignOutlinedTimePicker` and `MaterialDesignOutlinedDatePicker`.

**Comment by washburnit** [comment]
Are you going to include that feature in a future update?

**Comment by Xaalek** [comment]
Maybe, I don't plan to work on it right now. I think it's an easy fix so if you ever want to work on it would be cool.
