### ISSUE TITLE
не находит путь

### ISSUE THREAD

**Issue by KevinMcWood** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2752]
### Bug explanation

Ошибка	XDG0062	Не удалось загрузить файл или сборку "MaterialDesignColors, Culture=neutral" либо одну из их зависимостей. Не удается найти указанный файл.

Ошибка	XDG0062	Не удалось загрузить файл или сборку "MaterialDesignColors, Culture=neutral" либо одну из их зависимостей. Не удается найти указанный файл.
	

### Version

3.2.0

**Comment by MichelMichels** [comment]
Can you answer following questions:
* Are you using Visual Studio 2022?
* Have you tried using the latest packages of MDIX?

**Comment by MichelMichels** [comment]
Closed due to no reaction of OP.
