### ISSUE TITLE
Hello i have different issues 

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2753]
Hello i have different issues

 1. First when set stay opened to true in popupox the popup take long time to close.

  2. Second issues in calendar when I change calendar display mode to decade by click on calendar header and select year in month view the select month have only white foreground color and not have background color.   

3. Third issues how can use different calendar style like hijri and Persian calendar in calendar without change ui culture info.

**Comment by MichelMichels** [comment]
Hi, @KHALED-LAKEHAL

Is it possible to create a git repository to showcase these issues? Thank you!

**Comment by Xaalek** [comment]
For calendar langage : https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/2754

**Comment by KHALED-LAKEHAL** [comment]
i use simple code without any modification

**Comment by MichelMichels** [comment]
> i use simple code without any modification

This could very well be, but if you want me to investigate your issues, I'd really like your version of the code.
