### ISSUE TITLE
TextBox and ComboBox with same Margin settings in same Grid don't look alike

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#276]
You can see that the lines don't line up horizontally and also the hint text in on different level.
I used Margin="3" for both and can't really fix it even by playing with margins.

![capture](https://cloud.githubusercontent.com/assets/16761301/13467442/46a5f12a-e06c-11e5-83fa-dcf4651ebbe3.PNG)

**Comment by ruslanfedoseenko** [comment]
the same issue with DatePicker.
For me it only reproduced at monitor with resolution 1366x768
on FullHD screen aligment seems to be good

**Comment by bebenins** [comment]
Just wanted to add...  Vertical Content alignment is also inconsistent between TextBox and ComboBox
All these miss alignments stand out when you switch between tabs that contain TextBox and ComboBoxes
![untitled](https://cloud.githubusercontent.com/assets/16761301/15939258/e8438d28-2e44-11e6-992c-df19e8a5efc0.png)

**Comment by mr-vapor** [comment]
![image](https://user-images.githubusercontent.com/28776933/29616970-7b44f69c-8813-11e7-99e7-2020af718062.png)

**Comment by CookiesAndCoffee** [comment]
Same problem here:
![differentunderlining](https://user-images.githubusercontent.com/26963852/29617069-cfa2ddc6-8813-11e7-9587-68756b48d55a.png)

Fixed it with ComboBox Padding="0 6 0 7"

**Comment by bebenins** [comment]
Fixed in 4.1.0 release
