### ISSUE TITLE
The request of Corners and Menus/Popups

### ISSUE THREAD

**Issue by EarzuChan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2766]
1. Can you add adjustable rounded borders to all (or more) controls? For button Controls, for example, I can't set rounded corners with different curvature (or I don't know the real way) , so that my application designs have different rounded corners with different curvature, affecting the visual uniformity, can I come up with a better solution?

2. Could you add the ability to create Popups and Menus using code, or is there a better solution? Now I add a menu Control with a width and height of 0 to the program, and then specify the Margin of that Control to move it around when I need to display the menu. This is not convenient if I have a better solution, i'll thank you.

**Comment by MichelMichels** [comment]
1. This could be done, but will be time consuming
2. You should use a WPF converter to control the Visibility of your menu, which is out of scope of this repository. It could also be that you want a ContextMenu, but this is not clear from your description.

**Comment by Keboo** [comment]
I will add a couple things to @MichelMichels answer.

1. For some controls, like button, there is a `ButtonAssist.CornerRadius` attached property you can set. There is not a concept of a global corner radius, each radius will need to be specified on each control types (and not all may have that option). Typically, WPF applications that want to apply this sort of theme globally will set them up in things like App.xaml (or a resource dictionary(ies) referenced by it). 

2. I am not sure what you mean by creating controls in code. Within WPF everything you can do in XAML can also be done in code. The Popup control (which is the base for things like Menus and ContextMenus) supports [several ways of setting the position](https://learn.microsoft.com/dotnet/desktop/wpf/controls/popup-overview?view=netframeworkdesktop-4.8#defining-the-popup-position)
