### ISSUE TITLE
Add a materialdesign:dialoghost overlay CornerRadius attribute

### ISSUE THREAD

**Issue by wj8400684** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2772]
![image](https://user-images.githubusercontent.com/39239954/178483468-bffea392-f5ae-438f-9e9e-1e69d129d857.png)

**Comment by Xaalek** [comment]
Hello, please make an effort on the writing

**Comment by wj8400684** [comment]
Add an overlay corner radius attribute to dialoghost！

**Comment by wj8400684** [comment]
When the dialog box opens, the border can display rounded corners！
