### ISSUE TITLE
Replace Obsolete ShadowDepth

### ISSUE THREAD

**Issue by Xaalek** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2774]
# ToDo
Since these values are now obolete in `ShadowAssist`:
- `Depth0`
- `Depth1`
- `Depth2`
- `Depth3`
- `Depth4`
-  `Depth5`

We need to replace them all in the library.

**Check this PR for more information: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/2765**

We should use these values instead:
- `Depth_0dp`
- `Depth_1dp`
- `Depth_2dp`
- `Depth_3dp`
- `Depth_4dp`
- `Depth_5dp`
- `Depth_6dp`
- `Depth_7dp`
- `Depth_8dp`
- `Depth_12dp`
- `Depth_16dp`
- `Depth_24dp`

There is no exact equivalence between the old `ShadowDepth` and the new ones. So we have to look at the [specs](https://material.io/design/environment/elevation.html) to know what the new replacement value is.

# Example
Here is a setter for the `MaterialDesignRaisedButton` style:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/a4a5cd21e328ce1e473811ad330a40e5f9ac1d55/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L48
As you can see, it still use the old `ShadowAssist` value (`Depth1`)

When we look at this [table](https://material.io/design/environment/elevation.html#default-elevations) in the specs, we can see that Contained button have an elevation of 2dp by default.

So we need to replace `Depth1` by `Depth_2dp` in that case.

**If you are not sure of the replacement value, please ask in this thread.**

**Comment by Xaalek** [comment]
@jizc Indeed, you raise an interesting point

**Comment by Keboo** [comment]
I think it makes sense to move to elevation. At minimum from a naming perspective, will help people understand
