### ISSUE TITLE
DatePicker l10n issue

### ISSUE THREAD

**Issue by michaelmairegger** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2775]
### Bug explanation

There is an issue with showing correct localization data. The long month name in the third line is not localized

![image](https://user-images.githubusercontent.com/4341039/178759019-d31510a7-c20a-4e7a-bfb3-6892b33cdaa5.png)

### Version

4.5.0

**Comment by Xaalek** [comment]
Check this out:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2318
