### ISSUE TITLE
DataGrid unable scroll

### ISSUE THREAD

**Issue by SiNcSaD** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#279]
as the picture shows，I can not scroll on DataGrid
![f1](https://cloud.githubusercontent.com/assets/17000388/13554805/8360916e-e3ec-11e5-9cee-110b1b4ec265.png)
![f2](https://cloud.githubusercontent.com/assets/17000388/13554806/8365d02a-e3ec-11e5-8bdb-a5b502129e52.png)

```
<DataGrid Name="DHT11DataGrid" Margin="8"
                  Grid.Row="1"  Grid.Column="0"
                      CanUserSortColumns="True" AutoGenerateColumns="False"
                      materialDesign:DataGridAssist.CellPadding="13 8 8 8"
                      materialDesign:DataGridAssist.ColumnHeaderPadding="8" VerticalScrollBarVisibility="Visible">
            <DataGrid.Columns>
                <materialDesign:MaterialDataGridTextColumn Binding="{Binding ID}"
                                                        MinWidth="150"
                                                        Header="ID"    
                                                        EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnPopupEditingStyle}" />
                <materialDesign:MaterialDataGridTextColumn Binding="{Binding DateTime}"
                                                        MinWidth="200"
                                                        Header="日期時間"
                                                        EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnPopupEditingStyle}" />
                <materialDesign:MaterialDataGridTextColumn Binding="{Binding Temperature}"
                                                        MinWidth="50"
                                                        Header="溫度"    
                                                        EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnPopupEditingStyle}" />
                <materialDesign:MaterialDataGridTextColumn Binding="{Binding Humidity}"
                                                        MinWidth="50"
                                                        Header="濕度"    
                                                        EditingElementStyle="{StaticResource MaterialDesignDataGridTextColumnPopupEditingStyle}" />
            </DataGrid.Columns>
        </DataGrid>
```

**Comment by ButchersBoy** [comment]
Hi,

If I set the MaxHeight on the DataGrids in the demo the scroll bar works OK.  

* Are you sure this is not due to your panel layout?
* Could you post an example?

Thanks,

James

**Comment by andrew-mi** [comment]
For anyone else with weird bugs related to this you can (as a workaround for prototyping or whatever) use a negative bottom margin to extend the height of the DataGrid further than the height of the window.
`Margin="0,0,0,-1000"`

I used this in hacking together a live standalone leaderboard display: and for smooth scrolling I was trying to extend this DataGrid fully (disabling the ScrollViewer within) then use a RenderTransform animation to move the whole UI Panel. This doesn't work if you don't know from the beginning how many items you have because you need to set the `-1000` value just right.
I say 'hacking together' because that is what it was: never do this in a real project.

Regards,
Andrew Mitchell

**Comment by Keboo** [comment]
Closing for now due to inactivity. If there is still an issue please re-open with details.

**Comment by lucasNewSharp** [comment]
I think my problem was the same as @SiNcSaD . Let's me try to explain what I think that happen and my solution.
When you have an UserControl with a full GridView Inside, the ScrollBar of the GridView does not apeear and a ScrollBar of the MainWindow Panel, who has the UserControl inside shows up. The problem with GridView is that when the mouse is on the GridView, the ScrollBar of the "MainWindow" gets disabled. My hack to the problem:

First you need a method to find the Main Window ScrollBar:


```
public static ScrollViewer GetScrollViewer(UIElement element)
{
    if (element == null) return null;

    ScrollViewer retour = null;
    for (int i = 0; i < VisualTreeHelper.GetChildrenCount(element) && retour == null; i++)
    {
        if (VisualTreeHelper.GetChild(element, i) is ScrollViewer)
        {
            retour = (ScrollViewer)(VisualTreeHelper.GetChild(element, i));
        }
        else
        {
            retour = GetScrollViewer(VisualTreeHelper.GetChild(element, i) as UIElement);
        }
    }
    return retour;
}
```

Then, on the UserControl you need assign the PreviewMouseWheel event of your DataGrid and do the scroll manually:

```
private void dgUsuarios_PreviewMouseWheel(object sender, MouseWheelEventArgs e)
{            
    var scroll = GetScrollViewer(Application.Current.MainWindow);

    if (scroll == null)
        return;

    scroll.ScrollToVerticalOffset(scroll.VerticalOffset - e.Delta);
}
```

This solve my problem, I hope that helps someone.
