### ISSUE TITLE
Allow MenuAssist.TopLevelMenuItemHeight to change the height of top level items (with no sub items)

### ISSUE THREAD

**Issue by michaldivis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2794]
I'm loving the better menu height control, mentioned in #2626 and merged here #2657, however, I'm missing one thing. The new `MenuAssist.TopLevelMenuItemHeight` doesn't affect menu items that have no sub items.

**Solution**
The problem can be solved by using the `MenuAssist.TopLevelMenuItemHeight` in the Trigger with value `TopLevelItem`. Now it's only being used in the Trigger `TopLevelHeader`.

I'm happy to take this one.

**Comment by Xaalek** [comment]
Indeed, you're right. Thanks for your feedback!

https://user-images.githubusercontent.com/54487782/179958017-8f197cf8-152c-4f31-a68c-85f0c5818719.mp4
