### ISSUE TITLE
ProgressBar overflows corner radius of containing Card

### ISSUE THREAD

**Issue by cidzoo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2796]
## Summary

I have a ProgressBar contained in a mdix Card that have corner radius set. Starting from v4.3.0, I've noticed that the ProgressBar now visually overflows the card corners. It may happen with other parent/child controls, but I didn't tested.

Is this an intended change or a regression? 

## Steps to Reproduce

Start from the MDIX getting started app. Add the card and progress bar.

### csproj

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.3.0" />
  </ItemGroup>

</Project>
```

### MainWindow.xaml

```xaml
[...]
<Grid>
        <materialDesign:Card Margin="50" UniformCornerRadius="10">
            <StackPanel>
                <DockPanel>
                    <ProgressBar DockPanel.Dock="Bottom" Height="20" />
                </DockPanel>
            </StackPanel>
        </materialDesign:Card>
    </Grid>
[..]
```

### Expected behavior 

Until **v4.2.1**, child control (progress bar) is visually included in the parent control (card). 

![image](https://user-images.githubusercontent.com/1251942/180008935-9c06f291-2124-4265-b164-3b379e4a40c3.png)

### Actual behavior 

Starting from **v4.3.0**, the child control overflows the parent card corners.

![image](https://user-images.githubusercontent.com/1251942/180009567-620d9afb-a3bb-4fe5-9f55-63f2f95916d7.png)

### Version

v4.3.0

**Comment by StefanoRivolta-Previero** [comment]
By default the card control was changed to not clip the content. Just put  `ClipContent="True"` on the card

**Comment by cidzoo** [comment]
@StefanoRivolta-Previero Indeed, it's now working again. Thanks!

To whom it may concern, it doesn't seems to be mentioned in any changelog or documentation afaik.
