### ISSUE TITLE
Each time Clicking On MenuItem it becomes wider and wider

### ISSUE THREAD

**Issue by mahdiataey** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2822]
### Bug explanation

Whenever I click on menuitem header it becomes wider and wider while the main page is full screen.
![image](https://user-images.githubusercontent.com/36917283/185780651-383255fc-f65f-4b7f-be01-6a1a510b6598.png)

### Version

4.5.0

**Comment by Xaalek** [comment]
Can you please provide us a test repo or xaml code. I don't really understand the problem.

**Comment by MichelMichels** [comment]
Closed due to no feedback.
