### ISSUE TITLE
WPF Datagrid extensions

### ISSUE THREAD

**Issue by Arnh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#283]
Hi James and All.

First Thanks for this awesome Toolkit.

Works very well :)

I'd like to request the follow:

1)
It is possible to add ColumnAlignment and Background in WPF Datagrid Column?
eg wpf:DataGridColumnAssistant { BackgroundColor; ColunmnAlignment } and so on??

2)
A complete manage of DataGrid Header.
eg:
Split horizontal, multiRow Header, MultiTitle, MultiCell and so on?

I know it is trivial to add, but could complete MaterialDesign DataGrid.

Thanks.

Arn

**Comment by Keboo** [comment]
Hi @Arnh 

1. In the latest version both of those properties are managed by manipulating the existing WPF elements for the data grid.

2. At present there are no plans to expand the data grid to support these features.
