### ISSUE TITLE
System.Windows.ResourceDictionary Warning: 9.

### ISSUE THREAD

**Issue by KC-MarKamp** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2833]
### Bug explanation

Hello everyone,

Just came across a lot of those messages in my output window: (Currently running on .NET Framework 4.8)
- System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MaterialDesignTextBoxBorder'
- System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='PrimaryHueMidBrush'
- System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MaterialDesignBody'
- System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MaterialDesignPaper'
- System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='MaterialDesignToolForeground'
- etc.

The way I call MaterialDesign is as following:
![image](https://user-images.githubusercontent.com/83206263/187386128-741270db-a1d0-4bb2-ad6e-73217aa7338f.png)

Is there anyone who can help me solve those errors? Thanks in advance!

With kind regards,

Mark

### Version

4.5.0

**Comment by Keboo** [comment]
Hi @KC-MarKamp are you able to provide the MSBuild log showing the errors?

**Comment by KC-MarKamp** [comment]
Hi @Keboo, first of all, thank you so much for replying. A while back, I updated the NuGet package to the latest stable. Since then, I have not seen these error messages appear again, so the problem seems to be already solved. I tried to reproduce the error messages but with little success. If I see these errors again, I will ask this question again. Thanks again!
