### ISSUE TITLE
Cursor state on PasswordBox selection

### ISSUE THREAD

**Issue by Erapchu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2835]
### Bug explanation

Please, lets implement the same fixes for PasswordBox like

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2831

### Version

4.5.0

**Comment by nicolaihenriksen** [comment]
Fix applied to `PasswordBox` styles as well.
