### ISSUE TITLE
Not able to use to materialdesign3 togglebutton style

### ISSUE THREAD

**Issue by soghomonyansargis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2837]
### Bug explanation

In app.xaml when I add ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign3.ToggleButton.xaml" 

getting this error Cannot locate resource 'themes/materialdesign3.togglebutton.xaml'.
Others for example MaterialDesign3.NavigationRail.xaml works well.

### Version

4.5

**Comment by soghomonyansargis** [comment]
![image](https://user-images.githubusercontent.com/42004684/187656486-0a5a715d-517b-45b6-ac37-8e6f7363a61b.png)

**Comment by SeynalKim** [comment]
Try this instead;

 `<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ToggleButton.xaml" />`

**Comment by jizc** [comment]
It hasn't been released yet. Look for it in the upcoming [4.6.0 release](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/milestone/38).

**Comment by Keboo** [comment]
This should be resolved now that 4.6.0 has been released.
