### ISSUE TITLE
Adjust the thickness of PackIcon

### ISSUE THREAD

**Issue by EvATive7** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2848]
**Is your feature request related to a problem? Please describe.**
As the title

**Describe the solution you'd like**
please add a parameter to control the thickness of Icon,tks:)

**Comment by nicolaihenriksen** [comment]
@EvATive7 It is not clear to me what you mean by "thickness of icon"? Is it the `Padding`/`Margin` properties (of type `Thickness`) that you are referring to? These should be directly settable on the `PackIcon` element.

If you are referring to the actual "content" of the icons, that is "vector graphics" auto-converted into `Paths` and as such I don't think there is an easy way to make the "content" thicker in that sense.

**Comment by EvATive7** [comment]
@nicolaihenriksen 
The thickness of the icon I said means that "the thickness of the icon lines"(or "the weight of the icon").When I visited material.io,I discovered that the weight of the icon are adjustable(the pic below prove it)
![image](https://user-images.githubusercontent.com/92893737/190549066-c306a03c-8392-49c1-8743-92f8679f10c5.png)
Sorry for my bad English＞︿＜

**Comment by Keboo** [comment]
Hi @EvATive7, unfortuently with the current WPF implementation there is not the option to modify the icons in the same way that other Material Design implementations do. The icons in this library are auto generated from https://materialdesignicons.com/. We would need to have alternate source data to work with in order for this to be possible.

**Comment by EvATive7** [comment]
OK I got it,thank you so much for your answer！
