### ISSUE TITLE
MaterialDesignTheme.MahApps.Flyout.xaml is missing from the nuget package

### ISSUE THREAD

**Issue by andrewcartwright1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#286]
If you include the MaterialDesignTheme.Mahapps nuget package and then include the following source in app.xaml it throws an error saying it cant be found: MaterialDesignTheme.MahApps.Flyout.xaml

Although the file is visible in the repo: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/tree/master/MaterialDesignThemes.MahApps/Themes

**Comment by ButchersBoy** [comment]
You cleaned your solution etc???  This still an issue?

**Comment by andrewcartwright1** [comment]
Yes this is still an issue

**Comment by ButchersBoy** [comment]
What version of MahApps you got installed?

**Comment by ButchersBoy** [comment]
I think there is something up with the dll/nuget, in that the package installs the latest full build of MahApps, but the .dll is expecting 1.2.0.0.

Need a nuget expert...I remember this happening last time the MahApps build ticked over.

**Comment by andrewcartwright1** [comment]
<package id="MahApps.Metro" version="1.3.0-ALPHA066" targetFramework="net452" />
  <package id="MahApps.Metro.SimpleChildWindow" version="1.3.0" targetFramework="net452" />
  <package id="MaterialDesignColors" version="1.1.2" targetFramework="net452" />
  <package id="MaterialDesignThemes" version="1.5.0-ci508" targetFramework="net452" />
  <package id="MaterialDesignThemes.MahApps" version="0.0.4" targetFramework="net452" />

Are the packages I'm using from both material and mahapps

**Comment by AuroraDysis** [comment]
And SetFlyoutOpenAction is now obsolete
https://github.com/MahApps/MahApps.Metro/commit/626df2c558a4e16d688e277019ca231c36d89995

**Comment by punker76** [comment]
@ButchersBoy I can look at this, maybe we should use paket manager everywhere ;-)

**Comment by Keboo** [comment]
This should be addressed in the latest version (though you do need to use preview packages until MahApps 2.0 releases)
