### ISSUE TITLE
Insertion point hides at the start of line while using right to left flow direction in "MaterialDesignOutlinedTextBox" style

### ISSUE THREAD

**Issue by samini3000** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2865]
[###]([url](![Untitled](https://user-images.githubusercontent.com/35727427/190896189-448f4cbc-5458-4071-9505-6255a34ef85e.png))) Bug explanation

I had a problem while I was using a text box in "MaterialDesignOutlinedTextBox" style in  my program. 
it works okay when I using left to right flow direction, but when I use the right to left flow direction the insertion point at start of line isn't displayed. this is my sample code: 
```
<TextBox Grid.Column="0" x:Name="FeedbackTextBox" Width="750" FontWeight="Bold"
                             materialDesign:ScrollViewerAssist.IsAutoHideEnabled="True"
                             FlowDirection="RightToLeft"
                             ScrollViewer.PanningMode="VerticalOnly"
                             Style="{DynamicResource  MaterialDesignOutlinedTextBox}" >
</TextBox>
```
there a point that this works okay on window 11 and the problem happeneds on windows 10.
I tried to change font weight  of insertion point but I couldn't find any way.
any help would be appreciated.
![Untitled](https://user-images.githubusercontent.com/35727427/190896259-34d4c293-bb6b-4b3b-99cb-ea05b3918c24.png)
### Version

4.5.0

**Comment by samini3000** [comment]
@nicolaihenriksen  many thanks for your response , I will check what you mentioned , what is your windows version?

**Comment by nicolaihenriksen** [comment]
> @nicolaihenriksen many thanks for your response , I will check what you mentioned , what is your windows version?

The screenshots I posted are from a Windows 10 machine which is the one you indicated to be the version experiencing the issue, right?

**Comment by samini3000** [comment]
@nicolaihenriksen  I commit my sample project here, https://github.com/samini3000/MaterialDesignTest/

**Comment by nicolaihenriksen** [comment]
@samini3000 I just cloned your repo and started the project. I cannot reproduce the issue there either. It looks correct in both RTL and LTR layouts:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/19572699/195548898-8edaa7cf-6021-4427-b26b-2540831cbd37.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/19572699/195548957-5990aaf2-b809-4527-9e0b-7f246bea46d8.png">

**Comment by nicolaihenriksen** [comment]
@samini3000 another thing I notice is that in your screenshot, the `TextBox` does not appear to have focus (the thick blue border is not applied), and as such the text cursor (`IBeam`) will not be visible.
