### ISSUE TITLE
Scrollbar invisible with custom colors definition

### ISSUE THREAD

**Issue by mrtnbrst** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2883]
### Description
When custom colors are used in App.xaml as described in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Custom-Palette-Hues#custom-colours, the scrollbar handles are invisible but they still work.

Everything works as expected with a bundled theme as described in https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start.

### Screenshots
![custom_colors_invisible_scrollbar_handles](https://user-images.githubusercontent.com/54993850/192496971-e0cc7fad-654d-4132-888a-03455c42157e.png)
custom colors

![bundled_theme_working_scrollbar](https://user-images.githubusercontent.com/54993850/192495810-e615ad50-fc30-4d3a-851a-2a4c8ff1c1ed.png)
bundled theme

### Files
[MaterialDesignBug.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/9654318/MaterialDesignBug.zip)
Zip file with project for bug reproduction, .NET 6 project, using Windows 10.0.19044 SR0.0

### To Reproduce
Uncomment this section in App.xaml
![2022-09-27 11_49_53-MaterialDesignBug (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/54993850/192495962-cb5bf6b3-b8e5-44ab-9896-7896c87fa8cb.png),
comment out the bundled theme for reproducing the bug.
Do it the other way around for the working example.
![2022-09-27 11_50_26-MaterialDesignBug (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/54993850/192497975-a19f9b67-96ae-4f22-ab0f-5c20512d9ac7.png)

### Version

4.6.1

**Comment by nickdollahz** [comment]
I added the MaterialDesignBody Brush and it seems to be working fine for me.
```
<SolidColorBrush x:Key="MaterialDesignBody" Color="#FF000000" />
```

Although I would recommend just defining the custom color theme and then redefining the brushes you wish to change as needed.
```
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <materialDesign:CustomColorTheme
                    BaseTheme="Light"
                    ColorAdjustment="{materialDesign:ColorAdjustment}"
                    PrimaryColor="#DD6134D9"
                    SecondaryColor="#5C5B5E"/>

                <ResourceDictionary>
                    <!--  primary  -->

                    <SolidColorBrush x:Key="PrimaryHueLightBrush" Color="#744CE0" />
                    <SolidColorBrush x:Key="PrimaryHueLightForegroundBrush" Color="#FFFFFF" />
                    <SolidColorBrush x:Key="PrimaryHueMidBrush" Color="#6134D9" />
                    <SolidColorBrush x:Key="PrimaryHueMidForegroundBrush" Color="#FFFFFF" />
                    <SolidColorBrush x:Key="PrimaryHueDarkBrush" Color="#4D1DCF" />
                    <SolidColorBrush x:Key="PrimaryHueDarkForegroundBrush" Color="#FFFFFF" />

                    <SolidColorBrush x:Key="SecondaryHueMidBrush" Color="#5C5B5E" />
                    <SolidColorBrush x:Key="SecondaryHueMidForegroundBrush" Color="#FFFFFF" />
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
```

**Comment by mrtnbrst** [comment]
Thanks for the quick response, it works
