### ISSUE TITLE
DataGridAssist.CellPadding has no effect

### ISSUE THREAD

**Issue by OTCH-Ronny** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2915]
### Bug explanation

I tried to set cell padding in my data grid but `<DataGrid md:DataGridAssist.CellPadding="0">` had no effect.
Hence I copied the whole style "MaterialDesignDataGridCell" into my `<DataGrid.CellStyle>`. Visual Studio then showed the following error:
![CellPaddingError](https://user-images.githubusercontent.com/104440044/196453595-87148feb-db8a-401f-8301-e1a2b9144150.png)

Then I modified the setter property of "Padding" to the following code:
```<Setter Property="Padding" Value="{Binding RelativeSource={RelativeSource AncestorType=DataGrid}, Path=(md:DataGridAssist.CellPadding)}" />```
After that the error was gone and cell padding was working as expected.

### Version

4.6.1 (NET 6)

**Comment by nicolaihenriksen** [comment]
@OTCH-Ronny The demo application contains a sample which sets custom paddings. Using the latest from the `master` branch I think it works as expected. I have tried modifying both `DataGridAssist.ColumnHeaderPadding` and `DataGridAssist.CellPadding`. Both changes are respected in the UI when running the demo application (`Data Grids` page):

`ColumnHeaderPadding=5`
`CellPadding=10`

![image](https://user-images.githubusercontent.com/19572699/200067181-939bb86d-d7c9-4b91-b38f-ec40446d9f58.png)

**Comment by OTCH-Ronny** [comment]
@nicolaihenriksen I used the demo app to reproduce my situation. If you define an implicit style in your code your style setter will win over the explicit property. Consider the following code:
```
<smtx:XamlDisplay UniqueKey="grids_3">
      <smtx:XamlDisplay.Resources>
        <Style TargetType="DataGridCell" BasedOn="{StaticResource MaterialDesignDataGridCell}">
          <Setter Property="materialDesign:DataGridAssist.CellPadding" Value="20" />
        </Style>
      </smtx:XamlDisplay.Resources>
      <DataGrid materialDesign:DataGridAssist.CellPadding="1"
                materialDesign:DataGridAssist.ColumnHeaderPadding="4 2 2 2"
                CanUserAddRows="False"
                CanUserSortColumns="False"
                ItemsSource="{Binding Items3}" />
</smtx:XamlDisplay>
```
The output will be the following:
![CustomPaddingNotEffective](https://user-images.githubusercontent.com/104440044/200323109-e64a65d0-5d89-4e1b-8f4f-914acb398cc8.jpg)

If I add the modified style setter for `Padding` as shown in my bug explanation the "nearest" `DataGridAssist.CellPadding` definition will win:
```
<smtx:XamlDisplay UniqueKey="grids_3">
      <smtx:XamlDisplay.Resources>
        <Style TargetType="DataGridCell" BasedOn="{StaticResource MaterialDesignDataGridCell}">
          <Setter Property="materialDesign:DataGridAssist.CellPadding" Value="20" />
          <Setter Property="Padding" Value="{Binding RelativeSource={RelativeSource AncestorType=DataGrid}, Path=(materialDesign:DataGridAssist.CellPadding)}" />
        </Style>
      </smtx:XamlDisplay.Resources>
      <DataGrid materialDesign:DataGridAssist.CellPadding="1"
                materialDesign:DataGridAssist.ColumnHeaderPadding="4 2 2 2"
                CanUserAddRows="False"
                CanUserSortColumns="False"
                ItemsSource="{Binding Items3}" />
</smtx:XamlDisplay>
```
![CustomPaddingEffective](https://user-images.githubusercontent.com/104440044/200325057-a425ea03-ed20-4bb1-8a02-bb5c6de6dbf7.jpg)

**Comment by nicolaihenriksen** [comment]
@OTCH-Ronny I am not sure I understand why you think there is a problem then?

The first statement in the issue description states that setting `DataGridAssist.CellPadding` on a `DataGrid` has no effect.. I believe it **does** have an effect. Setting `DataGridAssist.CellPadding` on the "custom padding" `DataGrid` in the demo tool affects the rendered UI.

The examples you give in your latest comment also both make perfect sense to me. In the first code sample, you apply the `DataGridAssist.CellPadding` directly in your `DataGridCell` style which will naturally overrule the one applied at the `DataGrid` level. In the second example, you then explicitly set the `Padding` on the `DataGridCell`, but you set it to a binding which picks the attached property value from the ancestor of type `DataGrid` (thus ignoring the value set in the line right above!). This is set to "1" and is naturally applied.

Am I missing something completely obvious here?

**Comment by OTCH-Ronny** [comment]
Thank you for your explanation! Now everything makes sense now.

The problem was I have modified my default style in my application for `DataGridCell` instead of `DataGrid` and I was wondering why setting `DataGridAssist.CellPadding` on `DataGrid` had no effect.
