### ISSUE TITLE
after set up , i dont see the and didnt hear the CPU fan 

### ISSUE THREAD

**Issue by wingback18** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2917]
### Bug explanation

pretty much, the software identifies all the fans, it says I need an RPM sensor, don't know what that is or how to get it .
after identifying the fans one by one, the CPU fan didn't appear at all, is that normal? or what do i do 

i have an asus tuf x570 with a 5800xt 

### Version

v133

**Comment by MichelMichels** [comment]
I think you posted this issue in the wrong repository. This project is about implement the Material Design styleguide in WPF.
