### ISSUE TITLE
Removing chevron icon from MaterialDesignExpander template clone doesn't work

### ISSUE THREAD

**Issue by LyndonGingerich** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2920]
### Bug explanation

Reproduction:
1. Create WPF project with dependency on MaterialDesignThemes; add `ResourceDictionary` to `App.xaml`
2. Clone `ExpanderRotateAngleConverter`
3. Clone `MaterialDesignExpander` from [the latest commit as of this post](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/2a38b2c70a5e851bc5b926e0641c1848e719d86b#diff-97e22f624b606a804baf0998d1b3d044f70f172503a6ace9bca4fb15bf7fe7fe), using aforementioned clone of `ExpanderRotateAngleConverter`
4. Add an expander to `MainWindow.xaml`
5. Remove `Style` of `MaterialDesignHorizontalHeaderStyle` from `ToggleButton` in the `Template` setter

Expected behavior: The expander no longer contains a chevron icon.
Actual behavior: The chevron icon persists.

Now, if I remove the style setters from `ControlTemplate.Triggers` as well, then the expander successfully reverts to looking horrible, but this discovery took a long time.

Could `MaterialDesignExpander` be rearranged so the triggers don't override my styling?

The attached reproduction uses `BasedOn` to eliminate non-template setters.

[ExpanderWithoutChevron.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/9854054/ExpanderWithoutChevron.zip)

**Comment by nicolaihenriksen** [comment]
@LyndonGingerich I just had a look at the solution in the ZIP you provided. It is correct that you have removed the `MaterialDesignHorizontalHeaderStyle` (default) `Style` from the `ToggleButton`. However, it is being re-applied in the `ControlTemplate.Triggers` section (see screenshot below).

Also, if you want to get rid of that particular `Style`, you should probably create your own `Style` that suits your needs; I don't think you will be happy with the result when it turns into a "standard" MDIX `ToggleButton` style :-)

![image](https://user-images.githubusercontent.com/19572699/200064824-95369c18-b1de-4ec5-9750-64e844e698fa.png)

**Comment by LyndonGingerich** [comment]
> @LyndonGingerich I just had a look at the solution in the ZIP you provided. It is correct that you have removed the `MaterialDesignHorizontalHeaderStyle` (default) `Style` from the `ToggleButton`. However, it is being re-applied in the `ControlTemplate.Triggers` section (see screenshot below).

> Now, if I remove the style setters from `ControlTemplate.Triggers` as well, then the expander successfully reverts to looking horrible, but this discovery took a long time.

Right, like I said.

> Also, if you want to get rid of that particular `Style`, you should probably create your own `Style` that suits your needs; I don't think you will be happy with the result when it turns into a "standard" MDIX `ToggleButton` style :-)

Already done so. I just thought that this project's code might benefit from deduplication. If the style is going to be set in the triggers anyway, why set it in the attributes?

**Comment by nicolaihenriksen** [comment]
@LyndonGingerich Ok I see, I totally misunderstood then :-D
