### ISSUE TITLE
Custom TabItem with button not working on selected tab (WPF)

### ISSUE THREAD

**Issue by Nils-Berghs** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2921]
### Bug explanation

For my application I needed a closable tab item, basic implementation is pretty easy:

```
<TabControl ItemsSource="{Binding TabItems}">
    <TabControl.ItemTemplate>
         <DataTemplate>
             <StackPanel Orientation="Horizontal" >
                 <TextBlock  Text="{Binding Header}"/>
                 <Button Command="{Binding CloseTab}" >
                     <md:PackIcon Kind="Close"/>
                 </Button>
              </StackPanel>
          </DataTemplate>
      </TabControl.ItemTemplate>
                
      <TabControl.ContentTemplate>
                   ....
      </TabControl.ContentTemplate>
</TabControl>
```

This works for all tabs items, except for the selected tab. 

Looking at the 'MaterialDesignTabItem' there is Rectangle 'PART_BackgroundSelection' that is overlayed on the tab item. The fill for this rect is set to 'Transparent' via TemplateBinding, and the only use for this rectangle is an animation on its opacity (which is odd given that it is a transparent rectangle).

I was able to fix it by defining a new style for my tabItems based on the MaterialDesignTabItem style (but it took some digging to find this):
```
<TabControl.Resources>
    <Style TargetType="TabItem" BasedOn="{StaticResource MaterialDesignTabItem}">
        <Setter Property="Background" Value="{x:Null}"/>
    </Style>
</TabControl.Resources>
```

A better solution, i think would be to set the IsHitTestVisible="False" on the rectangle. I'll gladly create a pull request for this if this approach is OK.

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
@Nils-Berghs You are always welcome to create a pull request with fixes/additions.

I just had a quick look at the style, and I believe the `PART_BackgroundSelection` has `IsHitTestVisible=true` on purpose. This "prevents" the user from getting any visual feedback (i.e. the ripple) when re-selecting the currently selected tab. It naturally also serves the purpose of showing a background color on the (selected) `TabItem` header.

If you simply set `IsHitTestVisible=true` on the `Rectangle` you will enable the ripple-effect on the selected tab. You could mitigate this by adding an extra property-setter in the `IsSelected=true` trigger which sets `RippleAssist.IsDisabled=true` on the element named `contentPresenter`. With that, I think you would maintain the current behavior while allowing content in the selected tab to be clicked without invoking the ripple effect.
