### ISSUE TITLE
Scroll of root panel is not working when hover over other panels

### ISSUE THREAD

**Issue by yarus** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2923]
### Bug explanation

In MaterialDesign Demo application (WPF) open Tabs page - it has vertical scrollbar since there are a lot of content inside.
No move your mouse to hover over any Tab header and try to use mouse wheel to scroll.

Expected Result:
Scrolling works as normal.

Actual Result:
Scrolling is not working at all.

If I move my mouse out from Tab header and hover over other content, scrolling seems to be working fine.

I noticed the same behavior for Expander control. If I hover over Expander header, scroll wont work.

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
Seems like a bug, as long as the mouse is not hovering (nested) scrollable content, scrolling should work as you expect in your description. Don't you agree @Keboo?

I will take a look at this.
