### ISSUE TITLE
CharacterCounterVisibility on PasswordBox

### ISSUE THREAD

**Issue by Maxhy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2935]
The addition of materialDesign:TextFieldAssist.CharacterCounterVisibility on TextBox was perfect, thanks a lot for that.
The original thread (#1607) talking about the implementation was thinking that such feature wasn't necessary on a PasswordBox, whereas it may even be more necessary as we cannot directly bind the password value from the control.

**Describe the solution you'd like**
Support materialDesign:TextFieldAssist.CharacterCounterVisibility on PasswordBox control to display a character count information at the bottom of the password input, just like for TextBox control.

**Describe alternatives you've considered**
Do it myself out of MaterialDesignInXaml, but it will not benefit from automation already existing with materialDesign:TextFieldAssist.CharacterCounterVisibility.

Thanks!

**Comment by nicolaihenriksen** [comment]
@Maxhy You **can** actually bind the password from the `PasswordBox` using `PasswordBoxAssist.Password="{Binding ...}"`. However, I still think this is a reasonable request, so I will look into it.

**Comment by nicolaihenriksen** [comment]
@Maxhy The "character counter" feature is available for `PasswordBox` in the latest nightly release. Give it a try if you have time 😃

**Comment by Maxhy** [comment]
This looks perfect. Much better with official support than with my ugly workaround.
Thanks a lot.

**Comment by Maxhy** [comment]
Out of subject but I've added your project to our internal list of open source libraries dependencies to support. I handle a company doing open source software for physical security and this project is used on one specific product. Because open source libraries usually have less visibilities than complete products, whereas the business model is similar even if not necessary developed for profits, it also has less revenues. We will try to redistribute a pourcentage of our revenues to such libraries, once a year. Just wanted to share, keep the good work!
