### ISSUE TITLE
Wide, filled TabControl's Tabitem is limited by its MaxWidth

### ISSUE THREAD

**Issue by mkrauter** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2942]
### Bug explanation

When using a wide, horizontal, filled `TabControl` with just few items, after a certain width the tab selection indicator line will not take up the entire space as the `TabItem`'s `MaxWidth` is set to 360, resulting:

![image](https://user-images.githubusercontent.com/11353865/201495931-32ead58e-0034-49ef-8e89-d516fba025af.png)

I am not sure about the expected behaviour, but I think (at least for the filled TabControls) the line should cover the entire fill.

I was able to quickly fix this by overriding `MaxWidth`:
```
<Style TargetType="{x:Type TabItem}" BasedOn="{StaticResource MaterialDesignTabItem}">
    <Setter Property="MaxWidth" Value="Infinity"/>
</Style>
```

![image](https://user-images.githubusercontent.com/11353865/201496283-7c455c6d-4c82-43bd-92b8-906facc55f83.png)

### Version

Latest master

**Comment by nicolaihenriksen** [comment]
@mkrauter I agree this seems odd. I am not really sure why there is a default `MaxWidth=360` in the style.

I can understand the `MinWidth`, but `MaxWidth` seems a bit much. I think the `MaxWidth` should probably **not** be set in the default style; allowing users to opt-in on a `MaxWidth` with a `Style` override similar to the one in the description (but actually setting a fixed width). @Keboo Thoughts?

**Comment by Keboo** [comment]
@nicolaihenriksen yea I agree, I think we should remove the `MaxWidth` from the style.
