### ISSUE TITLE
DataGridComboBoxEditableTextBox's CaretBrush does not follow color scheme

### ISSUE THREAD

**Issue by mkrauter** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2951]
### Bug explanation

When creating a datagrid with an editable combobox, its text cursor caret will not take up the normal foreground color:

![image](https://user-images.githubusercontent.com/11353865/202569517-dd1c4f9d-3510-45b4-9eb0-cd954f1e18a9.png)

As a solution I added `CaretBrush` to the `MaterialDesignDataGridComboBoxEditableTextBox` style in the source:
```
<Setter Property="CaretBrush" Value="{Binding RelativeSource={RelativeSource AncestorType={x:Type FrameworkElement}}, Path=(TextElement.Foreground)}" />
```
resulting:

![image](https://user-images.githubusercontent.com/11353865/202571929-38a2392b-3545-4573-9919-79cda4006702.png)

### Version

Latest master

**Comment by nicolaihenriksen** [comment]
@mkrauter Nice catch 👍 I added a PR with your fix.
