### ISSUE TITLE
Bug in transitions demo?

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#296]
Moving backwards and forward again at at certain step in the transitions demo will not trigger the transition. Moving backwards twice and then forward twice will trigger the transition. Not sure if this is a bug or not. I just noticed it while checking out the transitions demo for the first time. Looking good! 

![transitionbug](https://cloud.githubusercontent.com/assets/1139118/13818760/70af4b48-eb97-11e5-983c-346c3487cd09.gif)

**Comment by Keboo** [comment]
Looks to be resolved in the latest 4.2.1 release
