### ISSUE TITLE
Initalize takes too much time.

### ISSUE THREAD

**Issue by KaiHuaDou** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#2974]
### Bug explanation

I found that the loading of Material Design library almost takes 80% time when the application is starting.
There's no problem in 4.4.0, But effects in 4.6.1. In the worst time, it will take almost 10 seconds to load.

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
@KaiHuaDou Do you have a repo showcasing this issue? I don't see the issue with the demo app (on the latest from `master` branch). It loads up almost immediately.
