### ISSUE TITLE
DialogHost Disappearing

### ISSUE THREAD

**Issue by chrisklepeis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#299]
I'm using a third party docking control with view-model first.... the tabs are bound to a view model and the view is found with datatemplates.

I'm using one-way binding on the IsOpen property of DialogHost. It works when I'm viewing the specific tab, but when I go to another tab then come back it doesn't appear, even though the property bound to IsOpen is still true.

I imagine this is something moreseo related to view model first and not the third party docking control (actiprosoftware).

**Comment by ButchersBoy** [comment]
I am guessing that the (actipro?) tab control is unloading the DialogHost when you switch tabs.  The you switch back, the DialogHost is reloading, but if IsOpen is set to true at load time the dialog doesn't auto open.

Can you confirm this?

**Comment by chrisklepeis** [comment]
Yes, that's correct. Since it would have to reload, I imagine that the opening animation would trigger again as well, which probably isn't expected behavior... well to me anyway. Not sure if there's a way to prevent animation on loading if IsOpen is already set to true or not.

**Comment by Keboo** [comment]
This is likely fixed in the latest 3.1.1 release. Closing for now, let me know if there is still an issue.
