### ISSUE TITLE
Is it possible to embed ElementStyle & EditingElementStyle in Style?

### ISSUE THREAD

**Issue by hxhgxy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3009]
![DG1](https://user-images.githubusercontent.com/37101628/209428318-7f1d7733-7904-431d-a6fb-889185705909.png)

**MD DataGrid, we have to set the column ElementStyle and EditingElementStyle in application view.
Is it possible to put everything in DataGrid Style below？**

![DG2](https://user-images.githubusercontent.com/37101628/209428478-95095165-c60f-411f-870e-e620c45f4712.png)

**Comment by nicolaihenriksen** [comment]
@hxhgxy I am not really sure I understand your use case. The `ElementStyle` and `EditingElementStyle` are bound to a particular instance of a column (definition). If you move these up to the parent `DataGrid` (style), that would effectively mean all cells should use the same styles?

I guess that there could be a use case for such a scenario, but I would assume you would then use the same column type (e.g. `DataGridTextColumn`) for all the columns? In which case you could probably define a shared style for these columns which applies the styles that you want. I don't think you can avoid specifying the `DataGrid.Columns` column (type) collection.

Anyway, it is a bit unclear to me what you're trying to accomplish, so please elaborate a bit if possible. Thanks.

**Comment by hxhgxy** [comment]
Yes, from the control application point of view, I may agree the current MD design for DataGrid may be the best way to fit for various purpose. What I want is the minimize the work at front view. And the most important thing is that I cannot make it successful. So, just from technical point of view, how to make it work by including ElementStyle and EditingElementStyle in style?

(If referring to MahApps DataGrid, no need to set ElementStyle in front view, but i cannot use clear button in DataGridComboBoxColumn.)

Thank you!

**Comment by nicolaihenriksen** [comment]
@hxhgxy I have thought about your comment above a lot, and I think I understand what you are asking now...

I think that your final goal is **not** having to specify `ElementStyle` and `EditingElementStyle` in the XAML of your view code, is that correct? You basically want the column to "default" to the styles you have defined in the XAML above?

Looking at the current MDIX code, these styles are in fact applied by default, but **only** if you use `AutoGenerateColumns=True` which of course is not always desirable.

In your example above, you're using both the BCL `DataGridTextColumn` and the MDIX `DataGridTextColumn` (derived type). I believe, if we are to make this work, you must use the MDIX version. With that said, simply using the MDIX version **does not** set the default styles, and as such you still have to apply them yourself. This is **not** the case for the MDIX `DataGridComboBoxColumn` (derived type) however; there we actually explicitly override the default values (see [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/f075b3091b642981589d088033873b3a5835db31/MaterialDesignThemes.Wpf/DataGridComboBoxColumn.cs#L7-L11)).

@Keboo Perhaps we should consider overriding the default styles for all of the MDIX derived column types similar to the way it is done in [DataGridComboBoxColumn](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/f075b3091b642981589d088033873b3a5835db31/MaterialDesignThemes.Wpf/DataGridComboBoxColumn.cs#L43-L67), although I don't think the way it is done there is the most elegant way to do it.

**Comment by hxhgxy** [comment]
“I think that your final goal is not having to specify ElementStyle and EditingElementStyle in the XAML of your view code, is that correct? You basically want the column to "default" to the styles you have defined in the XAML above?”
Yes, you are correct. Exactly, i want to have the same result but no need to specify ElementStyle and EditingElementStyle.

I hope you can make it. thanks!

**Comment by nicolaihenriksen** [comment]
> Yes, you are correct. Exactly, i want to have the same result but no need to specify ElementStyle and EditingElementStyle.

I have an open PR (#3033) which aims to solve this issue. It hopefully should make it into the library in a future release.

**Comment by hxhgxy** [comment]
that's great, thank you! look forward to the upgraded release!
