### ISSUE TITLE
DatePicker and TimePicker need i18n, RTL support

### ISSUE THREAD

**Issue by jdf3** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#301]
Needs treatment like #300.
- [ ] DatePicker
- [x] TimePicker

**Comment by jdf3** [comment]
See details in #302 for examples that would need to be addressed

**Comment by Keboo** [comment]
Time picker should be addressed by #1207

**Comment by Keboo** [comment]
Looks to be resolved in latest 4.2.1 release
