### ISSUE TITLE
The button is used in the detail row of the table and needs to be clicked twice to trigger the button

### ISSUE THREAD

**Issue by HBolck** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3013]
### Bug explanation

I added a column of buttons to the DataGrid and found that clicking the button required two clicks to trigger the button. My guess is that every time I click on a cell, the contents are redrawn.
Here is my xaml.

``` xaml
<DataGrid Grid.Row="1" Margin="2" FontSize="16" AutoGenerateColumns="False" CanUserAddRows="False" CanUserResizeColumns="False" 
                      CanUserResizeRows="False" Height="320" 
                      GridLinesVisibility="All" Focusable="False"
                      ItemsSource="{Binding JKDeviceList}" VirtualizingPanel.IsVirtualizing="True"
                      SelectionMode="Single" Background="Transparent" BorderThickness="1">
                    <DataGrid.Columns>                        
                        <DataGridTemplateColumn Width="180" ClipboardContentBinding="{x:Null}" Header="操作管理" >
                            <DataGridTemplateColumn.CellTemplate>
                                <DataTemplate>
                                    <StackPanel Orientation="Horizontal" VerticalAlignment="Center" HorizontalAlignment="Center">
                                        <Button Content="编辑" VerticalAlignment="Center" Margin="5" Foreground="White"
                                                Focusable="False"/>
                                        <Button Content="删除" VerticalAlignment="Center" Foreground="White"
                                                Focusable="False"/>
                                    </StackPanel>
                                </DataTemplate>
                            </DataGridTemplateColumn.CellTemplate>
                        </DataGridTemplateColumn>
                    </DataGrid.Columns>
                    <!--行标题样式-->
                    <DataGrid.ColumnHeaderStyle>
                        <Style TargetType="DataGridColumnHeader" BasedOn="{StaticResource MaterialDesignDataGridColumnHeader}">
                            <Setter Property="HorizontalContentAlignment" Value="Center"/>
                            <Setter Property="Padding" Value="3"/>
                            <Setter Property="BorderThickness" Value="0 0 0 1" />
                            <Setter Property="BorderBrush" Value="#bababa" />
                        </Style>
                    </DataGrid.ColumnHeaderStyle>
                </DataGrid>
```

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
@HBolck I am not really able to reproduce the issue you claim is present. The sample code you provided does not seem to have any click event handler (or command) so how do you know the button is not clicked? Do you have a small sample where the issue reproduces?

If I modify the demo app to include a button in the `DataGridTemplateColumn.CellTemplate` in `DataGrids.xaml` for example. I can then wire up a Click event handler which just calls `MessageBox.Show()` and that works as expected. A single click on the button shows the message box.

**Comment by HBolck** [comment]
I think maybe the code I provided is incomplete. I'll adjust it and you can have a look. I'll upload a simple demo.



---- Replied Message ----
| From | Nicolai ***@***.***> |
| Date | 01/02/2023 21:44 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MaterialDesignInXAML/MaterialDesignInXamlToolkit] The button is used in the detail row of the table and needs to be clicked twice to trigger the button (Issue #3013) |

@HBolck I am not really able to reproduce the issue you claim is present. The sample code you provided does not seem to have any click event handler (or command) so how do you know the button is not clicked? Do you have a small sample where the issue reproduces?

If I modify the demo app to include a button in the DataGridTemplateColumn.CellTemplate in DataGrids.xaml for example. I can then wire up a Click event handler which just calls MessageBox.Show() and that works as expected. A single click on the button shows the message box.

**Comment by HBolck** [comment]
I readjusted my code and made a demo. You can have a look at it.
![image](https://user-images.githubusercontent.com/65228544/210675887-62b29786-39e3-416a-a7a0-30af6069d13a.png)
[MaterialDataGridDemo.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/10348412/MaterialDataGridDemo.zip)

**Comment by HBolck** [comment]
![image](https://user-images.githubusercontent.com/65228544/210677011-0606c488-9c39-4e6a-8ee3-a8c52d93d160.png)
I found that when the cell was selected for the first time, the button did not work well. When I clicked the button, it seemed that I clicked on the cell, as if there was a mask on it. After clicking again or the current cell is already clicked, clicking the button again will take effect.
@nicolaihenriksen

**Comment by nicolaihenriksen** [comment]
> I found that when the cell was selected for the first time, the button did not work well. When I clicked the button, it seemed that I clicked on the cell, as if there was a mask on it. After clicking again or the current cell is already clicked, clicking the button again will take effect.

The provided sample reproduces the issue. Thanks! I will dig into it when I have some time...

**Comment by HBolck** [comment]
Ok .Thank you.
![FB9B407BB4BFD2AE79AD116A6812471D](https://user-images.githubusercontent.com/65228544/210735598-55428dd2-687f-4d7c-b224-9c89950478e0.png)

@nicolaihenriksen

**Comment by nicolaihenriksen** [comment]
@HBolck This bug was actually fixed in the latest release 4.7.0 which was released today. It was previously reported in issue #2898.

As a workaround for your sample project, you can add `IsReadOnly="True"` to your column definition to make this work with the 4.6.1 release as well. I hope this solves your issue.

**Comment by HBolck** [comment]
Thank you. I didn't think of this property before. I'll try it tomorrow.



---- Replied Message ----
| From | Nicolai ***@***.***> |
| Date | 01/05/2023 21:52 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MaterialDesignInXAML/MaterialDesignInXamlToolkit] The button is used in the detail row of the table and needs to be clicked twice to trigger the button (Issue #3013) |

@HBolck This bug was actually fixed in the latest release 4.7.0 which was released today. It was previously reported in issue #2898.

As a workaround for your sample project, you can add IsReadOnly="True" to your column definition to make this work with the 4.6.1 release as well. I hope this solves your issue.

**Comment by HBolck** [comment]
@nicolaihenriksen  
I tried using the property IsReadOnly="True" and found it worked. However, I don't quite understand why this is used. Literally, I understand whether a cell has a read-only status. In this way, the read-only attribute of the cell is enabled. Maybe there is a problem with my way of understanding. However, the problem has been solved. Thank you very much.
![image](https://user-images.githubusercontent.com/65228544/210905100-160a42a4-a6fb-4755-b645-76f7af6ce1d1.png)

**Comment by nicolaihenriksen** [comment]
@HBolck I can try to explain what is happening. I am actually not 100% sure that the material.io specification has any details about editing cells in a data grid, but in MDIX it has been decided that in an editable `DataGrid`, cell editing should be started with a single mouse click, as opposed to a non-MDIX `DataGrid` where a double-click is needed. [This attached property setter](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/621a87473f60cb35229ce3aa7a8ffac84dc9d94d/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DataGrid.xaml#L556) is what hooks that up.

So what happens in a `DataGrid` when a cell should be edited is that it swaps out the `DataTemplate` rendering the cell contents (i.e. the "view"). This basically means it switches from the `ElementStyle` to the `EditingElementStyle` and thus basically swaps out the contents (while maintaining the same `DataContext`).

When you set `IsReadOnly=True` on the column, you basically bail out of the MDIX custom "start editing cell" logic; see [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/621a87473f60cb35229ce3aa7a8ffac84dc9d94d/MaterialDesignThemes.Wpf/DataGridAssist.cs#L225-L230). That is why it works.

In MDIX version 4.7.0 there was added another guard in this method in order to bail out if the column type is `DataGridTemplateColumn`; see [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/621a87473f60cb35229ce3aa7a8ffac84dc9d94d/MaterialDesignThemes.Wpf/DataGridAssist.cs#L235-L240). This is why `IsReadOnly=True` is **not** needed for version 4.7.0.

**Comment by HBolck** [comment]
ok I get it. Thanks.
 @reply+APRU6ADC7KZ3ALDVWJ2EU4GBYUTA3EVBNHHFUGT6BM  



---- Replied Message ----
| From | Nicolai ***@***.***> |
| Date | 01/06/2023 18:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [MaterialDesignInXAML/MaterialDesignInXamlToolkit] The button is used in the detail row of the table and needs to be clicked twice to trigger the button (Issue #3013) |

@HBolck I can try to explain what is happening. I am actually not 100% sure that the material.io specification has any details about editing cells in a data grid, but in MDIX it has been decided that in an editable DataGrid, cell editing should be started with a single mouse click, as opposed to a non-MDIX DataGrid where a double-click is needed. This attached property setter is what hooks that up.

So what happens in a DataGrid when a cell should be edited is that it swaps out the DataTemplate rendering the cell contents (i.e. the "view"). This basically means it switches from the ElementStyle to the EditingElementStyle and thus basically swaps out the contents (while maintaining the same DataContext).

When you set IsReadOnly=True on the column, you basically bail out of the MDIX custom "start editing cell" logic; see here. That is why it works.

In MDIX version 4.7.0 there was added another guard in this method in order to bail out if the column type is DataGridTemplateColumn; see here. This is why IsReadOnly=True is not needed for version 4.7.0.
