### ISSUE TITLE
MaterialDesignThemes.Wpf.dll has wrong version in 4.7.0 package

### ISSUE THREAD

**Issue by starkna** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3029]
### Bug explanation

The version of the MaterialDesignThemes.Wpf.dll assembly included in the 4.7.0 package is 1.0.1, which is incorrect.  The version included in the previous 4.6.1 package was correctly set at 4.6.1.  This causes an incompatibility when trying to use this latest package in conjunction with MaterialDesignExtensions, which has a dependency of version 3.2 or greater.

### Version

4.7.0

**Comment by Keboo** [comment]
@starkna I can see that the dll is not properly versions (thanks for the report!), but I am curious to understand where the dependency issue lies. I can see that the MaterialDesignExtensions _NuGet_ package has a 3.2.0 or greater dependency, but this version dependency should only be based on NuGet versions not the version of the library inside of it.

**Comment by starkna** [comment]
@Keboo When I try to update our application's reference to the MaterialDesign package, we get the following error.  The issue seems to be that MaterialDesignExtensions ends up pulling in 3.2 from its package reference, and this causes an issue since the version we directly reference in your library is only at 1.0.  

We had to rollback our package update for this reason, so looking forward to the 4.7.1 package release.  Thanks for the quick attention and great work on this library!

Error	CS1705	Assembly 'MaterialDesignExtensions' with identity 'MaterialDesignExtensions, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c5ebccebe084d64f' uses 'MaterialDesignThemes.Wpf, Version=3.2.0.1979, Culture=neutral, PublicKeyToken=df2a72020bd7962a' which has a higher version than referenced assembly 'MaterialDesignThemes.Wpf' with identity 'MaterialDesignThemes.Wpf, Version=1.0.1.0, Culture=neutral, PublicKeyToken=df2a72020bd7962a'	Mmm.Ocsd.Dds.App	C:\Projects\LavaTMP\Source\dds\main\src\Mmm.Ocsd.Dds.App\CSC	1	N/A
