### ISSUE TITLE
Demo app - "Select all" checkbox not working in DataGrid demo

### ISSUE THREAD

**Issue by nicolaihenriksen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3032]
### Bug explanation

In the Data Grid demo page of the demo app, the "Select all" is not working as expected.

The XAML for the broken check box column can be found [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/621a87473f60cb35229ce3aa7a8ffac84dc9d94d/MainDemo.Wpf/DataGrids.xaml#L46-L60).

![SelectAll](https://user-images.githubusercontent.com/19572699/211202912-25606f51-10b6-4aac-9bb1-7232fb41c0dc.gif)

### Version

4.7.0

**Comment by Hadramet** [comment]
Hello, I am a developer who is learning WPF . I am interested in fixing this issue. Let me know if I am able to proceed with the fix? Thank you.

**Comment by nicolaihenriksen** [comment]
@Hadramet sure, you are very welcome to fork the repository, fix it there, and then create a Pull Request back to this origin repository. Contributions are always welcome and appreciated 👍
