### ISSUE TITLE
Importing Just ComboBox Fails

### ISSUE THREAD

**Issue by adamhewitt627** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3049]
### Bug explanation

I want to pull in a few Material controls, but I'm not ready to let MDIX drive the entire application. While the below approach works for a `CheckBox` or `RadioButton` it fails on `ComboBox`.

**ERROR:** `Exception: Cannot find resource named 'MaterialDesignThemes.Wpf.ComboBoxPopup`.

```xml
<Application.Resources>
  <ResourceDictionary>
    <ResourceDictionary.MergedDictionaries>
      <materialDesign:BundledTheme BaseTheme="Light" PrimaryColor="DeepPurple" SecondaryColor="Lime" />

      <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ComboBox.xaml" />

      <!-- WORKAROUND: Import this as well, problem goes away
      <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.ToolBar.xaml" />
      -->
    </ResourceDictionary.MergedDictionaries>

    <Style TargetType="{x:Type ComboBox}" BasedOn="{StaticResource MaterialDesignComboBox}" />
  </ResourceDictionary>
</Application.Resources>
```

### Version

4.7.1

**Comment by Keboo** [comment]
As part of the 5.0.0 code generation, it would be nice to generate UI tests that, assert that all resource dictionaries can be loaded independently.

**Comment by adamhewitt627** [comment]
[MdixComboRepro.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/10787501/MdixComboRepro.zip)

Full repro project.
