### ISSUE TITLE
Add a way to leave MaterialDesignDiscreteSlider number visible at all times

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#305]
The slider itself I mean.  There are instances when it's essential to know what the current selection is

**Comment by Keboo** [comment]
Currently no, that is controlled by a trigger on the IsDragging property on the thumb itself. Though certainly possible to implement, it doesn't appear to follow the normal material design specificiation. Typically if you want to keep the value visible, you bind a TextBlock's Text (or similar) to the Value of the slider.
