### ISSUE TITLE
Floating hint textblock cut off for right-aligned fields

### ISSUE THREAD

**Issue by yosefmah** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3055]
### Bug explanation

Bug possibly introduced with #3041 

When setting a HorizontalContentAlignment to right, the hint is cut off as it matches the width of the entered text.

![image](https://user-images.githubusercontent.com/19147840/213723783-8e14ae3c-5b2e-4f26-8c91-72ad2e81210b.png)

When entering longer text, the hint expands to show the full text but given the width of the Textbox it should always be visible.

![image](https://user-images.githubusercontent.com/19147840/213723942-7edaa70f-2585-48b3-8bff-d9abe135989b.png)

### Version

4.7.1

**Comment by nicolaihenriksen** [comment]
@yosefmah You are absolutely correct that #3041 has introduced a regression. This is how it was before (which IMO is actually also misaligned, but that is a different issue):
![BeforeFix](https://user-images.githubusercontent.com/19572699/213771290-97624e9e-5d6d-48a6-9f03-1409d9b2bad3.gif)

And this it how it works after:
![AfterFix](https://user-images.githubusercontent.com/19572699/213771358-97fc4e79-f0a5-4c3f-badb-e765ceaf1729.gif)

I'll look into fixing it.

**Comment by yosefmah** [comment]
Thanks for looking into this @nicolaihenriksen 

I actually think the problem is broader than I originally stated - it seems to impact `HorizontalContentAlignment="Left" ` and `HorizontalContentAlignment="Center"` as well.  Only `HorizontalContentAlignment="Stretch"` seems to not be affected.

**Comment by nicolaihenriksen** [comment]
> I actually think the problem is broader than I originally stated

I agree. And as you can see in the linked draft PR, I actually think we should revert the changes until we have a proper fix. I still believe the old implementation has issues, but not "as severe" as the new implementation. I'm currently waiting for some feedback from @Keboo about what to do about this (in the linked PR). Maybe he has a trick up his sleeve to solve it...
