### ISSUE TITLE
Header of the TabControl disappears after switching of the Visibility property

### ISSUE THREAD

**Issue by DrCQ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3063]
### Bug explanation

I use two `<UserControls>` sharing the same position in the Grid and being controlled by the Visibility property. With the current version 4.7.0 and 4.7.1 the `<TabControl>` header disappears after changing the Visibility of the hosting control from Visible to Collapsed and Visible again. I tested all available MaterialDesign Style versions and header positions with the same result.

My current workaround is: 
`<TabControl matD:ColorZoneAssist.Mode="PrimaryMid" TabStripPlacement="Right" Style="{x:Null}">` 
removing the Style definition. This workaround is "confirming" a bug in the TabControl (header) Style. 

### Version

4.7.1

**Comment by nicolaihenriksen** [comment]
This regression was introduced with 6be496b24b70c4a2b247a80d45e9f65ba6eb2be5. I will work on a fix for it...
