### ISSUE TITLE
[Help] MaterialDesignFloatingHintTextBox' resource not found

### ISSUE THREAD

**Issue by builuc1998** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3066]
### Bug explanation

I got the error MaterialDesignFloatingHintTextBox' resource not found after running debug and stopping it. the first time when opening the design it's normal but after running the app and stopping it got an error like this how to fix it.

### before
![before](https://user-images.githubusercontent.com/32072191/215499166-48ffa802-5048-4506-98c1-c2d5f99b33de.png)

### after
![after](https://user-images.githubusercontent.com/32072191/215499189-2eeee0e5-734f-4122-802b-cb2f88f39c2c.png)

### Version

4.7.1

**Comment by Asivaprasadam** [comment]
@builuc1998, this could be a **Styling** issue, based on appearance. It's possible that the _style_ isn't correctly bound to the control.

Can you confirm if the material design namespace was included or if any styling XAML is not omitted? 

Additionally, can you also confirm whether this is a designer-only issue and not a problem during rum time?

**Comment by MichelMichels** [comment]
Closed due to staleness.

**Comment by CallMeDang123** [comment]
sửa được chưa ông ơi
