### ISSUE TITLE
Can we implement TopMust feature for DialogHost?

### ISSUE THREAD

**Issue by mummyildiz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3068]
Can we implement TopMust feature for DialogHost?

**Comment by Keboo** [comment]
Can you describe what you are hoping to do with it? Are you just wanting to make the Popup control within the DialogHost top most?

**Comment by mummyildiz** [comment]
I am sorry. I replied late due to the disaster in Turkey. I'm trying to solve it with another method. thank you for your time.
