### ISSUE TITLE
Material Design 3 TextBox Height

### ISSUE THREAD

**Issue by LejlaBrkic123** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3076]
### Bug explanation

Hi, 
Why is not possible to put smaller height of textBox. I got smaller textBox but I can't write anything inside and also I don' see bottom line when the size is reduced. 

    <Style x:Key="NVDefaultTextBox" TargetType="TextBox"
           BasedOn="{StaticResource MaterialDesignOutlinedTextBox}">
        <Setter Property="FontSize" Value="16"/>
        <Setter Property="FontFamily" Value="Roboto"/>
        <Setter Property="FontWeight" Value="Medium"/>
        <Setter Property="Height" Value="32"/>
        <Setter Property="MinWidth" Value="48"/>
        <Setter Property="materialDesign:TextFieldAssist.DecorationVisibility" Value="Hidden"/>
        <Setter Property="materialDesign:TextFieldAssist.TextFieldCornerRadius" Value="4"/>
        <Setter Property="materialDesign:TextFieldAssist.UnderlineCornerRadius" Value="1" />
    </Style>

![image](https://user-images.githubusercontent.com/124668523/217202005-3eb4f695-7feb-4b0b-8d80-6c5e625b18a4.png)

### Version

Material Design 3

**Comment by nicolaihenriksen** [comment]
I think what you're experiencing here is the same issue as #3058. Since you're relying on the `MaterialDesignOutlinedTextBox` style, there is a trigger in the template which sets a specific padding. So although you set a different height, the padding still kicks in.

**Comment by LejlaBrkic123** [comment]
So it is working if I inline padding., like this <TextBox Style="{StaticResource NVDefaultTextBox}" IsEnabled="True" Padding="5"/>

> I think what you're experiencing here is the same issue as #3058. Since you're relying on the `MaterialDesignOutlinedTextBox` style, there is a trigger in the template which sets a specific padding. So although you set a different height, the padding still kicks in.

**Comment by nicolaihenriksen** [comment]
That is correct. I suspect this is because it reserves space for the floating hint. Whereas the outlined style already has the border which is where the hint will float to.

![PaddingIssue](https://user-images.githubusercontent.com/19572699/217486345-a8901f3a-d3b9-41b8-ba62-606e9411396d.gif)

**Comment by nicolaihenriksen** [comment]
@LejlaBrkic123 And I forgot to mention that you can of course disable the floating hint if you want to. Simply add `HintAssist.IsFloating=False` to the element (or the style). If you do that, I think you should get the padding you want.
