### ISSUE TITLE
Filled textBox

### ISSUE THREAD

**Issue by LejlaBrkic123** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3087]
### Bug explanation

Is it possible to set background color to transparent of the MaterialDesignFilledTextBox, I have tried but didn't managed to that, and it will be great to have it :) 
I have created my own style based on MaterialDesignFilledTextBox in different xaml as ResourceDictionary.

### Version

4.7.0

**Comment by nicolaihenriksen** [comment]
@LejlaBrkic123 Funny enough, this actually suffers from a very similar problem as the padding issue which was resolved in issue #3076 that you created. So currently your best option is to manually "override" the colors that the template uses. You could add the entries below to a ResourceDictionary to override the defaults:

```xaml
<SolidColorBrush x:Key="MaterialDesignTextFieldBoxBackground" Color="Transparent" />
<SolidColorBrush x:Key="MaterialDesignTextFieldBoxHoverBackground" Color="Transparent" />
```

Just to be clear, setting the `Background` in a style **does** work for the `FloatingHint` and `Outlined` styles, just not for the `Filled` style.

I know that @Keboo is working hard on a refactoring of the brushes and in doing so he hopes to expose a lot more flexibility over specific brushes. I think after that refactor, the keys used in the code snippet above will be obsoleted (but may still work), but you should have some new ones to achieve a similar result I would expect.

**Comment by LejlaBrkic123** [comment]
Hi yes I know, I have used outlined textBox in some cases, but I need and this one filled type with little bit changed style. I have used this styling 
    <Style x:Key="NVDefaultFilledTextBox" TargetType="TextBox"
           BasedOn="{StaticResource MaterialDesignFilledTextBox}">
        <Setter Property="FontSize" Value="12"/>
        <Setter Property="FontFamily" Value="Roboto"/>
        <Setter Property="Height" Value="32"></Setter>
        <Setter Property="MinWidth" Value="48"></Setter>
        <Setter Property="Foreground" Value="{StaticResource Primary800SolidColorBrush}"></Setter>
        <Setter Property="materialDesign:TextFieldAssist.DecorationVisibility" Value="Hidden"/>
        <Setter Property="materialDesign:TextFieldAssist.UnderlineCornerRadius" Value="0" />
        <Setter Property="VerticalAlignment" Value="Top"/>
        <Setter Property="VerticalContentAlignment" Value="Top"/>
        <Setter Property="HorizontalContentAlignment" Value="Left"/>
    </Style>
</ResourceDictionary>

And for result I have 
![image](https://user-images.githubusercontent.com/124668523/218983772-fe383b76-163d-4599-97d0-cf36ede407e3.png)

And for some reason I don't have underline visible when the textBox is disabled. 
When I add the code what did you suggest, like this 
       <Style.Resources>
            <SolidColorBrush x:Key="MaterialDesignTextFieldBoxBackground" Color="Transparent" />
            <SolidColorBrush x:Key="MaterialDesignTextFieldBoxHoverBackground" Color="Transparent" />
        </Style.Resources>
        <Style.Triggers>
            <Trigger Property="IsEnabled" Value="False">
                <Setter Property="Background" Value="{StaticResource PrimaryHueLightBrush}"></Setter>
                <Setter Property="Foreground" Value="{StaticResource Primary400SolidColorBrush}"></Setter>
            </Trigger>
        </Style.Triggers>
        
I have this result 
![image](https://user-images.githubusercontent.com/124668523/218985692-01de73eb-b153-4a13-8006-b382843ff27c.png)

The enabled one looks great, but disabled can look better :) 
Thank you for you help, you are very helpful to me. 
Soon I will have one more question for styling of toggle button, but I will try first by myself.

**Comment by LejlaBrkic123** [comment]
@nicolaihenriksen Thank you very much. You help me a lot. Yes, I defined that color in other resource file for colors. 
I don't know how I missed that property for decoration visibility. It is ok now. 
I don't have any more question for textBox but I will write you for toggle button, I have few questions.

**Comment by nicolaihenriksen** [comment]
> I don't have any more question for textBox but I will write you for toggle button, I have few questions.

Does that mean that this isn't really an issue and should be closed?

Also, if you have questions for how to use the toolkit, you should consider using the [Discussions](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions) tab rather than creating an issue.

**Comment by LejlaBrkic123** [comment]
I couldn't set background color on transparent, that's why I put it as a bug. Ofcourse It should be closed.
Ok I will set these kind of questions on Discussions from now on.
