### ISSUE TITLE
Checkbox IsChecked=False background color

### ISSUE THREAD

**Issue by SeynalKim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3121]
Can you please extend CheckBox with the possibility to set the background color when `IsChecked=False`?

The problem is when the parent has a dark background, the checkbox is not very visible in an unchecked state.

Currently, my solution is;

```
<Grid>
	<Grid.ColumnDefinitions>
		<ColumnDefinition Width="auto" />
        </Grid.ColumnDefinitions>
        <Border
		Grid.Column="0"
                Width="19"
                Height="19"
                Margin="8,0,8,0"
                HorizontalAlignment="Left"
                Background="{StaticResource BrushWhite}"
                CornerRadius="2" />
         <CheckBox
                     Grid.Column="0"
                     Margin="5,0,8,0"
                     md:CheckBoxAssist.CheckBoxSize="25"
                     IsChecked="true"
                     Style="{StaticResource MaterialDesignCheckBox}">
               <CheckBox.Content>
		       <TextBlock
			      Margin="0,0,0,2"
                              FontSize="16"
                              FontWeight="Bold"
                              Text="ENABLED" />
               </CheckBox.Content>
          </CheckBox>
</Grid>
```

### Version

4.5.0

**Comment by nicolaihenriksen** [comment]
@SeynalKim Can I ask you to provide some images/screenshots/mockups of what it is you would like to control. Based on the code above, it seems it is the background of the whole `CheckBox` control (tick and text), not just the background of the tick?

And if that is the case, don't you have other contrast issues (text color vs background color)? What I am hinting at, is that this seems like symptom treatment, where the real problem I would assume is probably in the overall theming/coloring of your application. If you add some more context, it may be easier to understand your use case. Thanks.

**Comment by SeynalKim** [comment]
@nicolaihenriksen for example, this one. In `IsChecked=False` with its dark background color.

![checkbox1](https://user-images.githubusercontent.com/9017938/223382596-f45fae27-f152-473c-9ad4-c6ddae8d7d8f.PNG)

With the approach above, it will now look this way which is also what I want.

![checkbox2](https://user-images.githubusercontent.com/9017938/223382946-1d2c7820-1ce8-4642-a8b2-45b637786054.PNG)

**Comment by nicolaihenriksen** [comment]
@SeynalKim So this `CheckBox` does not have anything set for the `Content`. Based on the outline of the "tick"-part I would assume your `TextElement.Foreground` is something similar (i.e. dark/black) which would be very hard to read on the dark background. This is why I think you must have some other contrast issues and I struggle to see how just being able to control the `Background` of the "tick"-part in a `CheckBox` would solve those issues.
