### ISSUE TITLE
HintAssist.Hint text is cut-off

### ISSUE THREAD

**Issue by reyntjesr** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3124]
### Bug explanation

I am currently stuck to version 4.6.1 of materialdesignthemes.  This is how my
textboxes with MaterialDesignFloatingHintTextBox Style look now.
[](url)
![Version4-6-1](https://user-images.githubusercontent.com/1846197/223076992-be7ec305-de33-4ccd-9bef-bf771734d648.png)
If I try to upgrade to a later version than 4.6.1 the HintAssist.Hint texts is cut-off
![Version4-8-0](https://user-images.githubusercontent.com/1846197/223077365-40311872-05b9-41bc-8592-7ac5fb2e7a9f.png)

I didn't change the MaterialDesignFloatingHintTextBox style in the example above much. The problem persists if I use the standard MaterialDesignFloatingHintTextBox  style.
```
            <Style TargetType="{x:Type TextBox}" BasedOn="{StaticResource MaterialDesignFloatingHintTextBox}">
                <Setter Property="Margin" Value="20 10 20 10" />
                <Setter Property="FontWeight" Value="DemiBold" />
                <Setter Property="FontSize" Value="16" />
                <Setter Property="materialDesign:ValidationAssist.FontSize" Value="12" />
            </Style>
```
The problem looks a bit like these issues, but these are closed:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/3055
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2686

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
@reyntjesr The `Grid` below is what lays our your `TextBox` controls, and I think this is what needs to be tweaked.

```xaml
<Grid Margin="20">
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="Auto"/>
        <ColumnDefinition Width="Auto"/>
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
        <RowDefinition Height="Auto"/>
    </Grid.RowDefinitions>
    <TextBlock Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" Text="{x:Static Properties:Resources.SelectedFiles}"/>
    <ItemsControl Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="2" ItemsSource="{Binding Files}" VerticalAlignment="Top"/>
    <TextBox Grid.Row="2" Grid.Column="0" x:Name="labAssInitials"  materialDesign:HintAssist.Hint="{Binding LabAssistantInitialsText}"
             Text="{Binding CurrentExtraInfo.LabAssistantInitials, UpdateSourceTrigger=PropertyChanged}"/>
    <TextBox Grid.Row="3" Grid.Column="0" x:Name="physAssInitials"  materialDesign:HintAssist.Hint="{Binding PhysAssistantInitialsText}"
             Text="{Binding CurrentExtraInfo.PhysAssistantInitials, UpdateSourceTrigger=PropertyChanged}"/>
    <TextBox Grid.Row="4" Grid.Column="0" x:Name="physicianInitials"  materialDesign:HintAssist.Hint="{Binding PhysicianInitialsText}"
             Text="{Binding CurrentExtraInfo.PhysicianInitials, UpdateSourceTrigger=PropertyChanged}"/>
    <TextBox Grid.Row="5" Grid.Column="0" x:Name="remarks"  materialDesign:HintAssist.Hint="{x:Static Properties:Resources.Remarks}"
             TextWrapping="Wrap" AcceptsReturn="True">
        <TextBox.Text>
            <Binding Path="CurrentExtraInfo.Remarks" Mode="TwoWay" UpdateSourceTrigger="PropertyChanged">
            </Binding>
        </TextBox.Text>
    </TextBox>
    <Button Grid.Row="6" Grid.Column="0" Content="Resend files"
            HorizontalAlignment="Left"
            Command="{Binding Path=ResendFilesCommand}" 
            Height="25" Width="Auto" Padding="10,1,10,1"
            Visibility="Collapsed"></Button>
</Grid>
```

Firstly, it defines 2 columns which are both set to auto-size (i.e. `Width="Auto"`) which will cause the grid to only take up the space it needs and since the `TextBox` instances don't have an explicit `Width`, they too will shrink down to fit their content.

Secondly, it does not seem like the second column is used for anything? Unless something is left out in the provided code.

I think you should set `Width="*"` on the first column to allow the column containing the text boxes to fill the entire available width of its parent container. I suspect this is the culprit of your issue.

**Comment by reyntjesr** [comment]
Thanks for your help!
I tried setting the ColumnDefinition of the first column to "*".
I also tried removing the second column and the controls with Grid.ColumnSpan="2". When I run my program now the width of the textboxes are almost totally collapsed until I start typing something in the textboxes.

As I said I, have this issue with all the textboxes in the three programs I'm developing and also when I change the TextBox style from MaterialDesignFloatingHintTextBox to MaterialDesignOutlinedTextBox or MaterialDesignFilledTextBox.

So in my programs the width of the textbox of materialdesignthemes versions higher than 4.6.1 only depend on the width of the Text field and not on the HintAssist.Hint width anymore.

**Comment by nicolaihenriksen** [comment]
@reyntjesr The `TextBox` width should not depend on the width of the hint text, because the hint text is rendered in a `Canvas` that is moved (e.g. "floated") and scaled and as such cannot be considered "part" of the `TextBox`. It "kindof" worked that way in the v. 4.6.1 and earlier, but it didn't work properly and thus was changed.

If setting the column to "*" does not solve your issue, then you have a similar issue further up the visual tree. In the code below I have - for demonstration purposes - hardcoded the width of a `Grid` to something wider than the content of the `TextBox` hints. As you can see, the `TextBox` fills the available space. I added a green background to the grid just to indicate the bounds.

```xaml
<Grid Width="300" Background="LightGreen">
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="*" />
    <ColumnDefinition Width="Auto" />
  </Grid.ColumnDefinitions>
  <Grid.RowDefinitions>
    <RowDefinition Height="Auto"/>
    <RowDefinition Height="Auto"/>
    <RowDefinition Height="Auto"/>
  </Grid.RowDefinitions>

  <TextBlock Text="Some TextBlock" Grid.Column="0" Grid.ColumnSpan="2" Margin="5" />

  <TextBox Grid.Column="0" Grid.Row="1" materialDesign:HintAssist.Hint="Short hint" Margin="5" />
  <TextBox Grid.Column="0" Grid.Row="2" materialDesign:HintAssist.Hint="A longer hint text" Margin="5" />
</Grid>
```

![image](https://user-images.githubusercontent.com/19572699/223136442-0a3348c9-d4e0-400d-9646-ff75005ddd49.png)

So either you need to adjust the `ScrollViewer` in your user control to take up the available space (perhaps wrap it in a `Grid` or use `HorizontalAlignment="Stretch"` or similar), or you need to go up to where you actually use a `ReactiveUserControl` and see which container you're placing that in. [Snoop](https://github.com/snoopwpf/snoopwpf) is an excellent tool for debugging issues like this and will allow you to pin-point which element is causing the limited width you're seeing.

**Comment by reyntjesr** [comment]
Of course the size of the textbox should depend on the size of the hint. The hint gives information about what should be filled in the textbox. Is there anyone who only wants to show half the hint? 
I don't think a technical reason like the hint text being rendered in a Canvas, changes the fact that someone who writes a hint wants to show the whole hint. 

As I said I have several programs that all use a lot of textboxes. I have to manually set a MinWidth on all of them now. And when I change the program to another language I have to check for text cut-offs again. 
This is all very inconvenient.

**Comment by nicolaihenriksen** [comment]
> Of course the size of the textbox should depend on the size of the hint. 

I disagree. The hint is **optional** extra information. Also, once you start typing anything in the `TextBox`, the hint is either collapsed or scaled+floated depending on the style; would you really want your UI to shrink your text boxes as soon as they gain keyboard focus?
I consider the hint and the helper text to be very similar in this regard, and I don't think either of them should influence the size of the `TextBox`, on the contrary I think they should respect it - they are after all both optional.

If you really want your hint/helper to be the determining factor for the `Width` of the `TextBox`, I would suggest you write a behavior which can set the width of the text box based on the width of the hint text - possibly using a binding and a converter. This behavior can be applied globally to affect all text boxes, but that of course requires you to have hint/helper on **all** of them. However, I don't think this is the right approach.

> As I said I have several programs that all use a lot of textboxes. I have to manually set a MinWidth on all of them now. And when I change the program to another language I have to check for text cut-offs again.

To me, this sound like a more general layout issue in your application. If you allow everything in your visual tree to "size to content", I think you're asking for trouble. Also, setting `MinWidth` on the text boxes - to me - seems like the wrong place to "fix the issue". I would do it on a parent container element instead.

> I don't think a technical reason like the hint text being rendered in a Canvas, changes the fact that someone who writes a hint wants to show the whole hint.

On this point we somewhat agree. I would expect the complete hint to be shown if there is room for it in the space reserved for the `TextBox`. A fixed `Width` or  `MaxWidth` property in any visual ancestor may have been set, at which point you may or may not see the complete hint (perhaps it fits when it is floated and scaled down).
If no specific space is reserved for the `TextBox` (i.e. "size to content"), I would expect it to behave like any other `UIElement` (including a standard-style WPF `TextBox`) which means it should collapse down to a width (and possibly height) of 0 - or very close to it - when it has no content; again I don't consider the hint text content.

**Comment by Tokter** [comment]
I think both views have merit. But the main problem is that the behavior changed. Before the TextBox would show the hint, now it's cut off. If you update to the latest version, you suddenly encounter this issue.

That should probably be mentioned as a breaking change somewhere.
