### ISSUE TITLE
Potential memory leak in ScrollViewerAssist

### ISSUE THREAD

**Issue by chris-crowther** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3130]
### Bug explanation

Views containing a `TabControl` using any style based on `MaterialDesignTabControlBase` are never garbage collected due to a problem in `ScrollViewerAssist` when the attached property `SupportHorizontalScroll` is enabled.

`ScrollViewerAssist` registers a `HwndSourceHook` to handle Win32 messages but never unregisters it.

This shows the memory snapshot from my application (class names obfuscated for reasons of paranoia and over-zealous corporate IT security).
![image](https://user-images.githubusercontent.com/28536141/223762716-b53af130-69e0-49b4-bcec-339b138465dc.png)

PR to follow!

### Version

4.8.0

**Comment by Keboo** [comment]
I think a similar issue likely exists with `BubbleVerticalScroll` as well. Good catch.

**Comment by chris-crowther** [comment]
I'm happy to create a PR for this if you like.

**Comment by Keboo** [comment]
That would be great. Thank you.

**Comment by chris-crowther** [comment]
It looks like I don't have permission to push a branch. Could somebody let me in?

**Comment by Keboo** [comment]
You want to [create your own fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks) of the repository. Do the work there. Then [submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) with the changes.
