### ISSUE TITLE
Swatch theme problem?

### ISSUE THREAD

**Issue by kuangxj** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3132]
### Bug explanation

When switching themes using The Palette Helper, nested UI does not refresh in time. My structure is Winow include UserControl,and UserControl include another UserControl(font color does not refresh ).

Look here!

![image](https://user-images.githubusercontent.com/46349033/224227241-c8643132-2179-4a90-ad38-40d8e9fa25de.png)

### Version

4.8.1-ci186

**Comment by DXR1DXR** [comment]
Same here (4.8.0 for net framework).

**Comment by DXR1DXR** [comment]
Found temporary solution.
Above MainWindow class type:
`private readonly PaletteHelper _paletteHelper = new PaletteHelper();`
Right before application starts (In the end of MainWindow class) type:
`Application.Current.MainWindow.Visibility = Visibility.Collapsed;
Task.Run(() => temp_fix());`
and this method will look like this:
`private void temp_fix()
 {
     ToggleBaseColour(!ProgramSettings.isDarkTheme);
     ToggleBaseColour(ProgramSettings.isDarkTheme);
     Application.Current.MainWindow.Visibility = Visibility.Visible;
 }`
ToggleBaseColour:
`private void ToggleBaseColour(bool isDark)
 {
     ITheme theme = _paletteHelper.GetTheme();
     IBaseTheme baseTheme = isDark ? new MaterialDesignDarkTheme() : (IBaseTheme)new MaterialDesignLightTheme();
     theme.SetBaseTheme(baseTheme);
     _paletteHelper.SetTheme(theme);
 }`
This should resolve it temporarily.

**Comment by kuangxj** [comment]
Let me test

> 找到了临时解决方案。以上 MainWindow 类类型：
> 
> ```
> private readonly PaletteHelper _paletteHelper = new PaletteHelper();
> ```
> 
> 在应用程序启动之前（在 MainWindow 类的末尾）键入：
> 
> ```
> Application.Current.MainWindow.Visibility = Visibility.Collapsed;
> Task.Run(() => temp_fix());
> ```
> 
> 此方法将如下所示：
> 
> ```
> private void temp_fix()
>  {
>      ToggleBaseColour(!ProgramSettings.isDarkTheme);
>      ToggleBaseColour(ProgramSettings.isDarkTheme);
>      Application.Current.MainWindow.Visibility = Visibility.Visible;
>  }
> ```
> 
> 切换基色：
> 
> ```
> private void ToggleBaseColour(bool isDark)
>  {
>      ITheme theme = _paletteHelper.GetTheme();
>      IBaseTheme baseTheme = isDark ? new MaterialDesignDarkTheme() : (IBaseTheme)new MaterialDesignLightTheme();
>      theme.SetBaseTheme(baseTheme);
>      _paletteHelper.SetTheme(theme);
>  }
> ```
> 
> 这应该暂时解决它。

Hi, let me finish the test and reply,thanks.
