### ISSUE TITLE
Can not change theme in a third party app

### ISSUE THREAD

**Issue by thanhsol** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3148]
### Bug explanation

I tried to change the theme according to the demo but replaced something to use it in a third-party app but it didn't work

Demo:
![image](https://user-images.githubusercontent.com/111832365/227833119-cc528b4f-2b74-48af-a086-747c4ca3e99f.png)

My file:
![image](https://user-images.githubusercontent.com/111832365/227833307-5841b9ec-db32-4050-892f-69d562642c19.png)

### Version

4.8.0

**Comment by nicolaihenriksen** [comment]
@thanhsol I may be missing some context here to give you any reasonable advice. However, typically when dealing with multiple assemblies and resources defined in either of them, you typically want to use "fully qualified" [pack URIs](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/app-development/pack-uris-in-wpf?view=netframeworkdesktop-4.8#referenced-assembly-resource-file). So something along the lines (or a variant of) this:

`pack://application:,,,/ReferencedAssembly;component/ResourceFile.xaml`

**Comment by ThanhWolfz** [comment]
Thank you, I tried but it doesn't work
![image](https://user-images.githubusercontent.com/43706221/230261849-98ad55a4-7125-4af6-8dbd-0eea7e4a0ba8.png)
![image](https://user-images.githubusercontent.com/43706221/230261990-5473afaf-253e-4cc5-a5d8-fb2deb6c5754.png)

**Comment by Keboo** [comment]
Hi @ThanhWolfz,
It looks like from your code samples you are simply changes the resources inside of `myResourceDictionary` but that resource dictionary is not attached to your window in anyway so the change will not have an effect. As @nicolaihenriksen said, it is difficult to say what needs to be done just from those code snippets. However, what you want to do, is use the main resource dictionary for your third-party application. Based on your last screenshot, I am assuming that your top level resource dictionary will probably be `Window.Resources`. This is the resource dictionary instance that you want to use for the calls to  `ResourceDictionaryExtensions.GetTheme` and `ResourceDictionaryExtension.SetTheme`.

**Comment by ThanhWolfz** [comment]
I tried to get/set the theme in code behind and it worked
![image](https://user-images.githubusercontent.com/43706221/230811808-a2309e50-4b39-4586-8954-9110591506be.png)

**Comment by Erapchu** [comment]
Maybe this can help to set theme:
https://github.com/Erapchu/SinglePass.WPF/blob/master/SinglePass.WPF/Services/ThemeService.cs
