### ISSUE TITLE
XamlParseException when loading MDIX in WinForms application

### ISSUE THREAD

**Issue by yang-0201** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3156]
### Bug explanation

when my winform project try to use the WPF which has [MaterialDesignInXamlToolkit] and report this problem, can this use like that?
how can I solve it

### Exception stacktrace
System.Windows.Markup.XamlParseException   Message=“在“System.Windows.StaticResourceExtension”   Source=PresentationFramework   StackTrace:    在 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)    在 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)    在 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)    在 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)  : Exception: 无法找到名为“MaterialDesignOutlinedTextBox”的资源。资源名称区分大小写。

#### Google translate of exception message
Exception: The resource named 'MaterialDesignOutlinedTextBox' could not be found. Resource names are case sensitive.

### Version

4.8.0

**Comment by Keboo** [comment]
@yang-0201 have you referenced the appropriate resource dictionary as indicated in the FAQ? https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/FAQ#exception-cannot-find-resource-named-materialdesign
