### ISSUE TITLE
The window went black on clicking after idling for a long period of time

### ISSUE THREAD

**Issue by Hsy-Gayhub** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3157]
### Bug explanation

I'm writing a multi-page WPF application. But once it has idled for about 1.5 hours, the application will either go black or the new pages can't be rendered correctly, is there any solution?

### Version

4.8.0

**Comment by Keboo** [comment]
@Hsy-Gayhub unfortunately, I will need more details than that to be able to know what is going on. Are you able to provide a sample application that reproduces the behavior?

**Comment by DavidCFreire** [comment]
I had similar issues and the hide function of WPF Windows was the issue, closing the first window and then open the second solved the problem

#2473

**Comment by Hsy-Gayhub** [comment]
I‘m now trying this #2386 ,hopefully it will solve my problem

**Comment by Keboo** [comment]
Let me know how it works out. The `CacheMode` has been in there for a while, but it is perfectly possible that it is the cause. For many of the styles you can control it by setting the `ShadowAssist.CacheMost={x:Null}`. However, there are still several (RatingBar, Slider, ToolBar) where it doesn't expose control over it. It may end up being prudent to expose some attached property to disable it in those cases as well.
