### ISSUE TITLE
System.Runtime.InteropServices.COMException (0x80004006)

### ISSUE THREAD

**Issue by lindadamama** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3163]
### Bug explanation

errcode：System.Runtime.InteropServices.COMException (0x80004006)
I am not sure what component is missing from this error when using Flipper in WPF

### Version

.net 6.0

**Comment by Keboo** [comment]
@lindadamama are you able to provide a repository that reproduces this issue?
