### ISSUE TITLE
Using the DialogHost.Show() pop-up box causes the TabItem to be destroyed

### ISSUE THREAD

**Issue by luy710** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3164]
### Bug explanation

There is a menu button on the main page, click to open the tab page, and there is a button click in the tab page Use DialogHost.Show() to pop up the box, causing the TabItem to be destroyed

code:
https://github.com/luy710/TestDialogBug

### Version

4.6.1

**Comment by nicolaihenriksen** [comment]
@luy710 There were some changes in this area in recent releases. Have you tried with a newer version of MaterialDesignThemes? I tried your test app, but it looks a bit strange. Upgrading to the newer version did however seem to have some effect. Can you verify if that solves it on your end? Thanks.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/19572699/231446759-12a237d8-cd90-491c-a846-3956e361ebb1.png">

**Comment by luy710** [comment]
@nicolaihenriksen Thank you very much, after upgrading to the latest version, the problem is perfectly solved！
