### ISSUE TITLE
Filled Text Box hint position

### ISSUE THREAD

**Issue by tanguyhardion** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3174]
### Bug explanation

The hint of the filled text box doesn't seem to be in the right position:

![image](https://user-images.githubusercontent.com/45904983/234317839-28c4bd3a-f64d-40f2-93ec-d6a1e7d9b182.png)
![image](https://user-images.githubusercontent.com/45904983/234318386-962b3d5d-61d6-4b2e-ba08-6bb7e37e663d.png)

For reference, here is an outlined text box with the same code, which has the right alignment:

![image](https://user-images.githubusercontent.com/45904983/234318681-136949f8-5f99-4b8d-8799-9897d5cbfd78.png)

My code:
```xaml
<TextBox Style="{StaticResource MaterialDesignFilledTextBox}"
                             materialDesign:HintAssist.Hint="Path"
                             materialDesign:HintAssist.IsFloating="True"
                             materialDesign:TextFieldAssist.HasLeadingIcon="True"
                             materialDesign:TextFieldAssist.LeadingIcon="DatabaseOutline"
                             Margin="15 0 0 0"
                             FontSize="15"
                             Padding="12 8"
                             Height="56"
                             Foreground="{DynamicResource OnBackground}" />
```

I tried using TextBoxViewMargin but without much success.

### Version

4.8.0

**Comment by nicolaihenriksen** [comment]
@tanguyhardion I just had a brief look at this. The `TextBox` styles in MDIX seem to have been designed for "their default size". This means that when you start modifying things like `Padding`, `FontSize`, and `Height` (in particular), the hint and icon placements are affected in ways that do not always look good. I have tested your code going all the way back to version 4.0.0 where the leading icon was introduced, and all versions have (different) issues.

There has recently been done some work refactoring the `SmartHint` and the placement of it. Some of that is not yet released, but even on the latest (not released) code, there are still issues when using the code you provided. When I have some time, I will look into adding a bit better support for things like this, although I believe it will be difficult to land a solution that works perfectly in all scenarios.

**Comment by nicolaihenriksen** [comment]
@tanguyhardion In the code you provided, you are explicitly setting `FontSize`. This is one of the remaining issues that I did not tackle 100% in the PR that was merged. You may run into issues with it, especially if you combine it with `Height` and `VerticalContentAlignment` properties.

If you do use some custom values, you can always play around with setting a custom `HintAssist.FloatingOffset` as well. This will allow you full control of the (relative) placement of the floated hint. The default is (0,-16) I believe, and this is a special value which receives special handling. So if you want custom handling, you need to set it to something different. In the rare case that you actually need it to be manually positioned at (0,-16) you can probably just set the value to (0, -16.001) or something like that to avoid the "special handling case"; This is a side-effect of a somewhat unfortunate default value of the DP in my opinion, but there are probably reasons for it being the way it is.
