### ISSUE TITLE
Transparent ComboBox Popup

### ISSUE THREAD

**Issue by SchreinerK** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3187]
### Bug explanation

I have a new app and I wonder why the popup is transtparent by default. Currently it is not usable in this way.

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/4082338/408e5d70-a992-4a2f-b6d4-71eb7252bfc1)

I use the MaterialDesignInXamlToolkitt for the first time  und I did not found a way to set the background for the popup without to copy and adapt the complete ComboBox template.  ComboBox Background has no effect to the popup.

### Version

4.8.0

**Comment by MichelMichels** [comment]
Could you provide a working code sample? I cannot replicate this behavior.
