### ISSUE TITLE
nuget version 4.8.1

### ISSUE THREAD

**Issue by mzy666888** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3189]
### Bug explanation

release version: 4.9.0 on github ,but version:4.8.1 on nuget?

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@Keboo Is this a missing step in the now nearly fully automated release flow? I am guessing [this part](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/53ceabd525a48e25017d7f17ea8501e396366dcb/.github/workflows/get_versions.yml#L26) needs to be updated to the version/milestone which you manually enter as a parameter to the workflow?

**Comment by Keboo** [comment]
@nicolaihenriksen yes this is the stage that failed due to permissions. I am going to do it manually.

**Comment by Keboo** [comment]
Ok 4.9.0 should be published now. Though GitHub is having issues this morning so things are going a little slower.

**Comment by nicolaihenriksen** [comment]
> @nicolaihenriksen yes this is the stage that failed due to permissions. I am going to do it manually.

Note to self: Always watch [Kevins latest stream](https://www.twitch.tv/kitokeboo) **before** asking questions that have already been answered 😛
