### ISSUE TITLE
MaterialDesign:HintAssist.Foreground

### ISSUE THREAD

**Issue by MeisterBaum** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3226]
### Bug explanation

It is not possible to change the Color of the materialDesign:HintAssist.Foreground in XAML C# WPF.

Try it out:
```
                    <ComboBox
                              Margin="30,10,30,0"
                              VerticalAlignment="Top"
                              materialDesign:HintAssist.Foreground="Red"
                              materialDesign:HintAssist.HelperText="Component" />

```

### Version

4.8.1

**Comment by nicolaihenriksen** [comment]
@MeisterBaum So there are 2 string properties on `HintAssist` which are relevant here. `HintAssist.Hint` and `HintAssist.HelperText`. They are sort of similar, but not the same. The hint resides inside of the element (`ComboBox` in this case), and the helper text is displayed below the element.

The `HintAssist.Foreground` seems to be used for the `HintAssist.Hint` and there is not a dedicated property for the foreground of the helper text. However, you can set `HintAssist.HelperTextStyle` which is a style, and there you can override the `Foreground` to your liking.

Can you confirm that things work as expected if you take the above into account?

**Comment by Keboo** [comment]
On the note of changing colors, there is work in progress for the 5.0.0 to redo all of the color theming to help enable things like this.

**Comment by MeisterBaum** [comment]
> @MeisterBaum So there are 2 string properties on `HintAssist` which are relevant here. `HintAssist.Hint` and `HintAssist.HelperText`. They are sort of similar, but not the same. The hint resides inside of the element (`ComboBox` in this case), and the helper text is displayed below the element.
> 
> The `HintAssist.Foreground` seems to be used for the `HintAssist.Hint` and there is not a dedicated property for the foreground of the helper text. However, you can set `HintAssist.HelperTextStyle` which is a style, and there you can override the `Foreground` to your liking.
> 
> Can you confirm that things work as expected if you take the above into account?

I understand your explaination. But i why it is possible to change the opacity of HelperText with materialDesing:HintAssist.Opacity? 

This should also not work then either

**Comment by nicolaihenriksen** [comment]
> But why it is possible to change the opacity of HelperText with materialDesing:HintAssist.Opacity?

That is a great question! It seems there is some misalignment regarding which properties affect what...

**Comment by MeisterBaum** [comment]
> > But why it is possible to change the opacity of HelperText with materialDesing:HintAssist.Opacity?
> 
> That is a great question! It seems there is some misalignment regarding which properties affect what...

Yeah and this is the reason why im so confused about this. I understand that you want to give a Hint and a HelperText. But something here was mixed together. Some Properties are for both and some Properties are for only for Hint. This is not really good in my opinion, i would recommend to fix this in the future.
