### ISSUE TITLE
MaterialDataGridComboBoxColumn display nothing

### ISSUE THREAD

**Issue by jebissey** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3232]
### Bug explanation

A very little program created with code from MaterialDesignToolKit shows no combobox
![2023-06-01_11h26_53](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/8895244/12c619b9-eee6-4369-a5fd-1a3934e5ee5c)
[MaterialDesignPoc.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/11623526/MaterialDesignPoc.zip)

### Version

4.9

**Comment by jebissey** [comment]
Thanks to 
https://thomaslevesque.fr/2011/03/21/wpf-comment-faire-un-binding-dans-les-cas-o-on-nhrite-pas-du-datacontext/
![2023-06-01_13h33_44](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/8895244/41f818a4-2765-417d-a2c6-8f2e854e986c)
[MaterialDesignPoc.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/11624646/MaterialDesignPoc.zip)

I added BindingProxy class.
A nearly equivalent class seems to exist in MaterialDesign.
I wonder what is missing in the first program.

**Comment by nicolaihenriksen** [comment]
@jebissey I took a look at your first program, and I was able to fix the issue by moving the code below out of `MainWindowView.xaml` and into `App.xaml` instead:

```xaml
<ResourceDictionary>
    <ResourceDictionary.MergedDictionaries>
        <materialDesign:CustomColorTheme BaseTheme="Light" PrimaryColor="ForestGreen" SecondaryColor="DarkGreen" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.DataGrid.xaml" />
    </ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
```

I think @Keboo looked into a similar issue at some point, but I don't recall if he came to a conclusion as to why it does not work "at the window level".
