### ISSUE TITLE
ListBox toggle can be unselected

### ISSUE THREAD

**Issue by jurot8** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3235]
### Bug explanation

ListBox in toggle mode:

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/79969466/b5a77639-3789-4740-9f7f-768b2737c7bf)

should not be able to get into the state
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/79969466/6a287bb7-da5c-407c-85ec-faaa958d537a)

Now when I click the selected item, it is unselected.

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
I don't really see this as a bug, but more as a feature request. I'm sure there are scenarios where you want to be able to deselect all items, just as there are cases where you want to be able to toggle more than one item on (e.g. setting `ListBox.SelectionMode=Multiple`).

I guess one option would be to introduce a `ListBoxAssist.CanUserUntoggleLastItem` attached property which simply disregards the click if there is only a single item selected, and the user tries to untoggle it. Proposals for a better name for the AP are much appreciated!

**Comment by jurot8** [comment]
This is sample from you MaterialDesignDemo and it really doesn't make a sense to have 'none' alignment :) 

I think, that it should be the default behavior. Otherwise I don't see the point of grouping the toggle buttons using ListBox. I would use standard toggle buttons.
