### ISSUE TITLE
Windows 11 - Smart App Control

### ISSUE THREAD

**Issue by hathawcs** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3239]
Windows 11 is introducing Smart App Control. One of the security checks for apps is ensuring that the app and its binaries are signed. Because MaterialDesignInXamlToolkit does not sign its binaries, software using it will be blocked from running when Smart App Control is enabled.

Please sign DLLs produced for MaterialDesignInXamlToolkit.

https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

Note: my project is using v3.2.0 of MaterialDesignThemes due to a dependency on .NET v4.5.

**Comment by nicolaihenriksen** [comment]
@hathawcs To my knowledge, the assemblies ARE signed. Perhaps they were not signed in version 3.2.0, that I do not know.

**Comment by nicolaihenriksen** [comment]
> Both 3.20 and 4.8.0 do not have digital signatures. I believe they are strongly named though

Ah yes, my mistake. The key.snk is used for strong naming of course, not digital signatures.

**Comment by ahmed-abdelrazek** [comment]
even if the project start signing new releases i don't think they will go back and sign old versions and re-release them
you might still have the same problem

**Comment by hathawcs** [comment]
> even if the project start signing new releases i don't think they will go back and sign old versions and re-release them you might still have the same problem

That may be, but all of the software using MaterialDesignInXaml will fail to run when Smart App Control is enabled as it stands now. If the signing isn't backported to previous releases, users of MaterialDesignInXaml that can't update for "reasons" will be put in a bind.

**Comment by ahmed-abdelrazek** [comment]
> > even if the project start signing new releases i don't think they will go back and sign old versions and re-release them you might still have the same problem
> 
> That may be, but all of the software using MaterialDesignInXaml will fail to run when Smart App Control is enabled as it stands now. If the signing isn't backported to previous releases, users of MaterialDesignInXaml that can't update for "reasons" will be put in a bind.

you assuming that everyone that's going to run a software that uses this library is using windows 11 and/or going to enable this feature
also if it was that important to you and you are going to sign your app anyway your best option might be forking the library build and sign it yourself for your app

**Comment by MichelMichels** [comment]
Closed due to staleness
