### ISSUE TITLE
Ability to disable shadows under Slider control to use this control as an indicator

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3251]
In our company sometimes we are using Slider controls as indicators, for example - a thermometer.
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/16761301/733585f1-22ef-49d5-bb55-99c1b6343e13)

Unfortunately when you are looking at the entire UI, it looks as if these sliders are there to use as a setting.  It would be awesome to be able to disable the shadow to make it look more like an indicator rather than something you need to slide with a mouse.

Not sure what the best implementation would be.  IMO if `IsHitTestVisible` is `false` then the shadow should not be there but maybe it warrants a different setting or entirely new control name.

Thank you.

**Comment by nicolaihenriksen** [comment]
@bebenins I think you can accomplish this already. You can disable the control (`IsEnabled=False`) to disallow user input or you can use `IsHitTestVisible=False` in you want to "disable" it but maintain the colors.

With regards to the drop shadow, you can remove that by setting the `ElevationAssist.Elevation=Dp0`.

```xaml
<Slider
    Maximum="50"
    Minimum="0"
    Value="25"
    IsHitTestVisible="False"
    materialDesign:ElevationAssist.Elevation="Dp0" />
```

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/a0be519d-37fd-4593-8e38-8a4a8930c283)

**Comment by bebenins** [comment]
@nicolaihenriksen Nice!  I totally forgot about this Dp setting.  All I needed.  Thank you!
