### ISSUE TITLE
Changing WPF Border background is not working 

### ISSUE THREAD

**Issue by L-Dlbcq** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3252]
### Bug explanation

Hi everyone,

I'm making a WPF C# app with MaterialDesignThemes and i'm trying to change primary color. Everythings working properly but the border background of the window is not changing anymore. Did someone know how to solve that problem ?

### Version

4.9.0

**Comment by MichelMichels** [comment]
Closed due to staleness and no repository provided.
