### ISSUE TITLE
After applying the binding rule, the text box is unable to input decimal points.

### ISSUE THREAD

**Issue by AniFacer** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3257]
### Bug explanation

       <TextBox materialDesign:HintAssist.Hint="StartPos" Style="{StaticResource MaterialDesignFloatingHintTextBox}">
                                    <TextBox.Text>
                                        <Binding Path="StartPos" UpdateSourceTrigger="PropertyChanged" >
                                            <Binding.ValidationRules>
                                                <ValidationRule:NumericValidationRule ValidatesOnTargetUpdated="True" />
                                            </Binding.ValidationRules>
                                        </Binding>
                                    </TextBox.Text>
                                </TextBox>

### Version

4.9

**Comment by jbooth88** [comment]
I think this is related to the WPF binding engine, not specific to MaterialDesignInXamlToolkit or any applied ValidationRules. 

Using UpdateSourceTrigger="PropertyChanged" tells the WPF binding to update the data bound property each time the text field changes (after each keystroke in most common cases). When a user inputs a decimal point the string gets converted into a number and back to a string without the decimal point immediately, giving the illusion that the text box wasn't accepting decimal input at all.

You can test this on your own by copy+pasting these numeric strings into your text box: 

10.005
10.000

if the second paste operation changes 10.000 to 10 then my assumption is probably correct. I've encountered this issue before in my own projects, and the solutions I've found were to either use UpdateSourceTrigger="LostFocus" or apply a reasonable delay to wait for the users to stop typing (in the past I've used 500ms)
