### ISSUE TITLE
PopupBox.AnimateChildrenIn should respect TransitionAssist.DisableTransitions

### ISSUE THREAD

**Issue by MBesuden** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3270]
**Is your feature request related to a problem? Please describe.**
I tried to use the popupbox with a custom background (instead of card from the standard popupbox style). Multiple entries are displayed including multiple buttons with icons. When opening the popupbox, all buttons (and icons) seem to fly in from top to bottom of the popupbox (final position is correct).

Minimal working example (tested with MaterialDesignThemes version 4.5.0 and 4.9.0 with .NET 6 and a standard wpf project):

MainWindow:

```
<Window x:Class="MaterialDesignPopUpTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:MaterialDesignPopUpTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800"

        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        xmlns:collections="clr-namespace:System.Collections;assembly=System.Runtime"
        xmlns:system="clr-namespace:System;assembly=System.Runtime"
        TextElement.Foreground="{DynamicResource MaterialDesignBody}"
        Background="{DynamicResource MaterialDesignPaper}"
        TextElement.FontWeight="Medium"
        TextElement.FontSize="14"
        FontFamily="{materialDesign:MaterialDesignFont}">
  <Window.Resources>
    <collections:ArrayList x:Key="Container">
      <system:String>First</system:String>
      <system:String>Second</system:String>
      <system:String>Third</system:String>
      <system:String>Fourth</system:String>
    </collections:ArrayList>
  </Window.Resources>

  <StackPanel Orientation="Horizontal">
    <materialDesign:PopupBox PopupMode="Click"
                             VerticalAlignment="Top"
                             materialDesign:RippleAssist.IsDisabled="True"
                             StaysOpen="True"
                             Style="{StaticResource MaterialDesignMultiFloatingActionPopupBox}"
                             Background="Transparent"
                             BorderBrush="Transparent"
                             PlacementMode="BottomAndAlignCentres">
      <materialDesign:PopupBox.ToggleContent>
        <materialDesign:PackIcon
          Kind="Accounts"
          VerticalAlignment="Center"
          Width="32"
          Height="32" />
      </materialDesign:PopupBox.ToggleContent>
      <materialDesign:PopupBox.PopupContent>
        <StackPanel>
          <Grid HorizontalAlignment="Center" Background="Transparent">
            <Polygon Points="0,24 12,0, 24,24"
                     Fill="{DynamicResource MaterialDesignCardBackground}"
                     materialDesign:ShadowAssist.ShadowDepth="Depth4" />
          </Grid>
          <materialDesign:Card>
          <ScrollViewer VerticalScrollBarVisibility="Visible"
                        HorizontalScrollBarVisibility="Disabled">
            <ItemsControl ItemsSource="{StaticResource Container}">
              <ItemsControl.ItemTemplate>
                <DataTemplate>
                  <Border x:Name="Border"
                          Padding="8"
                          Margin="8 0 0 0"
                          BorderThickness="0 0 0 1"
                          BorderBrush="{StaticResource MaterialDesignDivider}">
                    <Grid MinWidth="150">
                      <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="8*" />
                        <ColumnDefinition Width="1*" />
                      </Grid.ColumnDefinitions>
                      <StackPanel Grid.Column="0" Margin="8 0 0 0">
                        <TextBlock Text="{Binding }"
                                   FontWeight="Bold"
                                   TextTrimming="WordEllipsis"
                                   TextWrapping="Wrap">
                        </TextBlock>
                        <TextBlock Text="{Binding }"
                                   TextTrimming="WordEllipsis"
                                   TextWrapping="Wrap" />
                      </StackPanel>
                      <Button Grid.Column="1">
                        <materialDesign:PackIcon Kind="Close" Height="18" Width="18" />
                      </Button>
                    </Grid>
                  </Border>
                </DataTemplate>
              </ItemsControl.ItemTemplate>
            </ItemsControl>
          </ScrollViewer>
          </materialDesign:Card>
        </StackPanel>
      </materialDesign:PopupBox.PopupContent>
    </materialDesign:PopupBox>
  </StackPanel>
</Window>
```

**Describe the solution you'd like**
Check if transitions are disabled for popupbox via the transition assist. E.g.:

```
private void AnimateChildrenIn(bool reverse)
{
  if (TransitionAssist.GetDisableTransitions(this))
  {
    return;
  }
  [...]
}

```

**Describe alternatives you've considered**
Considered writing a new custom style for the popupbox to disable button animations while also allowing to use custom components without relying on the Card in the standard popupbox style.

**Additional context**

https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/6214866/06f56d77-4680-4385-8edb-a332a2a48c2a

**Comment by nicolaihenriksen** [comment]
@MBesuden Thank you very much for the detailed description and suggested solution. I am not opposed, per say, to applying the fix you propose, although I could have a slight concern that the `TransitionAssist.DisableTransitions` is not the ideal property to use for this. Since this is a custom control, it may be worth simply exposing a dependency property directly on the `PopupBox` to disable this particular behavior. Naming is hard, but hopefully having a dedicated DP for this could also make it more "self-documenting". It will definitely increase discoverability because it resides directly on the control and does not require a consumer to be aware of the attached DP on the `TransitionAssist` class.

Perhaps something like `PopupBox.AnimateChildrenWhenOpening` which defaults to `true` to retain the current behavior?

**Comment by MBesuden** [comment]
Thanks for your answer.
For me the issue was that it was unclear why the buttons (icons) were animated. The `PopupBox.AnimateChildrenIn` is very implicit because it assumes that the `ContentControl` of the PopupBox has a specific name.

I think an additional property like you suggested would really increase the discoverability. Although the solution for my specific problem was a simple style which allows to completely customize the `PopupBox`content. The standard style always includes a `Card` and the only other style includes the implicit animation.

I honestly would like to see both, an easy discoverable property to make the functionality more explicit and a simple customizable style (which can be the base style for the `PopupBox` with included `Card`).
