### ISSUE TITLE
Radio button colors

### ISSUE THREAD

**Issue by Harmless05** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3309]
### Bug explanation

I cannot change radio button's unselected color. It always stays this dark greenish color. The selected color does change but has a slightly different hue to it than other buttons.

In combination with radio buttons I use this style: MaterialDesignChoiceChipRadioButton

- Radio button labeled "Home" is selected
- Radio button labeled "About" is unselected
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/88204341/80927ba1-799b-4f49-90ad-5e02bb38fc20)

### Version

4.9.0

**Comment by MichelMichels** [comment]
Please provide a test repository.
