### ISSUE TITLE
The mainwindow appears briefly blank at startup before loading the content

### ISSUE THREAD

**Issue by NeverMorewd** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3322]
### Bug explanation

There is same issue in MaterialDesignDemo

### Version

4.9.0

**Comment by Keboo** [comment]
Are you able to provide a screen recording of the behavior. I am seeing little to no delay at startup and consequently never see the blank window.

**Comment by NeverMorewd** [comment]
![20231103165030_rec_](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/10544200/a59984ae-a289-43e7-a62e-65dbf14f9485)

**Comment by 1592363624** [comment]
你们是真的细节 我都没觉得这是什么问题

**Comment by MichelMichels** [comment]
Closing due to limited information.
