### ISSUE TITLE
Hope to support the Avalonia！！！

### ISSUE THREAD

**Issue by AniFacer** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3323]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pypykim** [comment]
hope too

**Comment by Keboo** [comment]
There is already a fork of this repo to support Avalonia. You can find it here. https://github.com/AvaloniaCommunity/Material.Avalonia
