### ISSUE TITLE
Radio buttons active area overlaps

### ISSUE THREAD

**Issue by Nils-Berghs** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3331]
### Bug explanation

In WPF if you create a some radiobuttons in grid rows or in a vertical stack panel without vertical margins, the active area of the different buttons overlap.
This means that there is a region on the upper button that actually selects the next button (assuming that the upper button is declared first in xaml). When adjusting the Z index of the radio button it is possible to reverse it (i.e. part of the lower button selects the upper one).

```
<RadioButton Grid.Row="0" Content="Click my upper half to select me"/>
<RadioButton Grid.Row="1" Content="Click my upper half, or the bottom half of the button above, to select me"/>
<RadioButton Grid.Row="2" Content="Click me anywhere, or the bottom half of the button above, to select me"/>
```

Note that half is slightly exaggerated (maybe bottom third)

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@Nils-Berghs I tried to reproduce what you've described here, but I don't see the issue you're describing. Could you provide a sample repo/app that reproduces the issue?

![RadioButtons](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/7df0e312-17a6-44bd-8360-363e3f70680f)

**Comment by Nils-Berghs** [comment]
@nicolaihenriksen when clicking on the text as in your sample, it works correctly, the problem occurs when clicking on the buttons itself

![radiobuttons](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/23696465/63c4d502-9018-48a5-b51a-cf0d9d7f573d)

**Comment by nicolaihenriksen** [comment]
@Nils-Berghs Will try to reproduce it again...
