### ISSUE TITLE
The error message still shows up after uninstalling MaterialDesignThemes, saying “Could not load file or assembly ‘MaterialDesignThemes.Wpf’.”

### ISSUE THREAD

**Issue by 434977268** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3332]
### Bug explanation

I used to reference MaterialDesignThemes, but I uninstalled it later through Nuget. However, when I start my program, it still prompts "Could not load file or assembly ‘MaterialDesignThemes.Wpf’. I checked my packages.config and there is no content with MaterialDesignThemes characters. I don’t know where it is not uninstalled cleanly. 
The following is all the content in my packages.config file:
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="CommunityToolkit.Mvvm" version="8.0.0" targetFramework="net48" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="6.0.0" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="12.0.1" targetFramework="net48" />
  <package id="NPOI" version="2.5.6" targetFramework="net48" />
  <package id="Portable.BouncyCastle" version="1.8.9" targetFramework="net48" />
  <package id="Revit.Async" version="2.0.1" targetFramework="net48" />
  <package id="SharpZipLib" version="1.3.3" targetFramework="net48" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net48" />
  <package id="System.ComponentModel.Annotations" version="5.0.0" targetFramework="net48" />
  <package id="System.Memory" version="4.5.5" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net48" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net48" />
  <package id="System.Windows.Interactivity.WPF" version="2.0.20525" targetFramework="net48" />
</packages>

### Version

4.9.0

**Comment by Keboo** [comment]
Are you able to share an example project that reproduces this behavior?

**Comment by Davey-vS-02** [comment]
This is probably just Visual Studio. There is something called an Intellesense cache and it will sometimes "hold onto" errors even when the necessary code is deleted. A quick restart of the program usually fixes this. I have no idea if this is the problem and I'll need to have it in front of me before I can give you a useful solution, but hope this helps.
