### ISSUE TITLE
PopupBox with Menu cascading

### ISSUE THREAD

**Issue by jurot8** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3348]
### Bug explanation

I have PopupBox with Menu as follows:

  ```
 <md:PopupBox>
     <Menu>
       <Menu.ItemsPanel>
         <ItemsPanelTemplate>
           <StackPanel />
         </ItemsPanelTemplate>
       </Menu.ItemsPanel>

       ......


    <MenuItem Header="Parent">
         <MenuItem Header="Child" />
    </MenuItem>
```
....
</Menu>
</md:PopupBox>

The result:
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/79969466/58b95535-3a6f-406d-9252-bec4b907c0fc)

...it is not cascading - the Parent-item doesn't have the arrow to open the Child.

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@jurot8 Although this may seem like an issue with MDIX, I don't see it that way. The `PopupBox` allows you to specify content which is shown inside of a `Popup`. If/when you simply place a `Menu` element directly in there, it will act the same as if you placed it directly in a `Window`; namely by adding a clickable "button" for the root level `MenuItem` which in turn will open a `Popup` (similar to a `ContextMenu`) with its child `MenuItem(s)`. So this is the result you're getting with your current code.

Based on your screen shot, it seems like you could benefit from just using a normal `Button` and then popping a `ContextMenu` when it is clicked. You could fairly easily encapsulate this into a custom control for better reuse.

Some XAML like this:
```xaml
<Button Click="MyButton_OnClick">
  <Button.Resources>
    <ContextMenu x:Key="ButtonMenu" Placement="Bottom">
      <MenuItem Header="Parent">
        <MenuItem Header="Child" />
      </MenuItem>
    </ContextMenu>
  </Button.Resources>
  <materialDesign:PackIcon Kind="MoreVert" />
</Button>
```
and a bit of code-behind with the click handler like this:
```csharp
private void MyButton_OnClick(object sender, RoutedEventArgs e)
{
    if (sender is not Button button)
        return;

    var menu = (ContextMenu) button.FindResource("ButtonMenu");
    menu.PlacementTarget = button;
    menu.IsOpen = true;
}
```

End result is something like this (you could style the button any way you want):
![CustomPopupBox](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/ea728e19-33c9-4c1e-8c5a-bc7eb2d0e2a3)

**Comment by nicolaihenriksen** [comment]
> If you do a custom control...

Perhaps this is not trivial for everyone, so I decided to add a quick example in here.

Custom control could look like this:
```csharp
public class MyPopupButton : Button
{
    public static readonly DependencyProperty PopupContentProperty = DependencyProperty.Register(
        nameof(PopupContent), typeof(ContextMenu), typeof(MyPopupButton), new PropertyMetadata(default(ContextMenu)));

    public ContextMenu? PopupContent
    {
        get { return (ContextMenu) GetValue(PopupContentProperty); }
        set { SetValue(PopupContentProperty, value); }
    }

    protected override void OnClick()
    {
        if (PopupContent is null)
            return;

        PopupContent.PlacementTarget = this;
        PopupContent.IsOpen = true;
    }
}
```
And usage from XAML would then be something like this:
```xaml
<local:MyPopupButton Style="{StaticResource MaterialDesignPopupBoxButton}">
  <local:MyPopupButton.PopupContent>
    <ContextMenu Placement="Bottom">
      <MenuItem Header="Parent">
        <MenuItem Header="Child" />
      </MenuItem>
    </ContextMenu>
  </local:MyPopupButton.PopupContent>
  <materialDesign:PackIcon Kind="MoreVert" />
</local:MyPopupButton>
```
Here I have simply used the `MaterialDesignPopupBoxButton` style to make it appear similar to the `PopupBox`, again you can add your own flavor to it.

End result will look something like this:
![CustomPopupBox2](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/a20bf6f6-6306-4d8e-838b-d4799ffbde4f)

**Comment by jurot8** [comment]
Thanks, that's exactly what I need.
