### ISSUE TITLE
ListBox control does not clear itself when binded collection gets cleared

### ISSUE THREAD

**Issue by paul-vinogradov** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#335]
![image](https://cloud.githubusercontent.com/assets/10684499/14427891/6dfb5014-ffff-11e5-9e17-dec37a703098.png)
![image](https://cloud.githubusercontent.com/assets/10684499/14427895/734f8bd4-ffff-11e5-92f5-ea45bf264fcd.png)
When you clear the list they stay like this. Adding new items to them still leaves them as they have N amount of items. Only expanding them again fixes this. Or adding more or equal items

**Comment by ButchersBoy** [comment]
Hi, I've knocked up a basic example and the expanders collapse.  This may depend on your markup.  Can you please post a repo.

**Comment by Imhotebkin** [comment]
OK, I will do that when I get to work (thursday).

There is just a list that is binded to an ObservableColletion which i clear with "a.clear()". Nothig really special. It's quite odd that you don't have that problem

**Comment by Imhotebkin** [comment]
@ButchersBoy sorry for the big delay, I was out of town. I modified the Lists example to demonstrate the lists not deleting items. Here is the repo https://github.com/Imhotebkin/MaterialDesignInXamlToolkit

**Comment by w-syss** [comment]
This is no longer happening and can be closed.
@Keboo

**Comment by Keboo** [comment]
Thanks @w-syss 
Closing for now. Please let me know if this is still an issue
