### ISSUE TITLE
Card Padding Issue (2xPadding)

### ISSUE THREAD

**Issue by ali-zare** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3357]
### Bug explanation

MaterialDesignTheme.Card.xaml --> Card Style --> Card ControlTemplate --> TemplateBinding Padding, has happened twice
...
<Border x:Name="PART_ClipBorder" Padding="{TemplateBinding Padding}" ...
<ContentPresenter x:Name="ContentPresenter" Margin="{TemplateBinding Padding}" ...
...

### Version

4.9.0

**Comment by StefanoRivolta-Previero** [comment]
I've also noticed this problem in v5.0 as well. 

### How to reproduce

Add this code in your app:

```
<StackPanel Grid.Column="1" HorizontalAlignment="Center"  VerticalAlignment="Center">
  <materialDesign:Card  Width="100" Height="100" Padding="6">
    <Border Background="red"/>
  </materialDesign:Card>
  <Border Background="{StaticResource MaterialDesign.Brush.Card.Background}"
          Width="100" Height="100" CornerRadius="4" Margin="0 10 0 0" Padding="6"
          Effect="{StaticResource MaterialDesignElevationShadow1}">
    <Border Background="red"/>
  </Border>
</StackPanel>
```
Despite both the card and border having 6 padding, the card padding is double the border one:

![0pLiUPWsQQ](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/58171461/b4327b65-dad1-489a-bcb4-1e52cd2152b8)

I'll try to fix it

### Version

5.0.0
