### ISSUE TITLE
Flipper doesn't apply changed theme

### ISSUE THREAD

**Issue by dand751801** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3360]
## Summary

Changing the theme (light/dark) has no effect on component `Flipper` when it's background face is visible.

### Detected the following specs
- MDIX Demo 4.9 (untouched EXE)
- (also in my own project (.net6 WPF, MDIX 4.9)
- Windows 10 22H2 / Windows 11 22H2

### Steps to reproduce
- Start Demo
- Go to "Cards" page
- Rotate the Flipper Card, i. e. "James Willoc" User Card
- Go to "Color Tool" page
- Switch theme (It is unimportant which theme is active)
- Go back to "Cards" page
- *Expected result:* 
  - All components are rendered with the new theme color
- *Actual result:* Cards are rendered with 
  - Cards are rendered with the new theme color
  - Unflipped Flippers are also rendered with the new theme color
  - But: Rotated Flipper is still rendered with the old theme color

### Screen recording
![MDIX_Flipper](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/60128881/3b41fccd-4f73-4719-9b58-bba4fa0a6926)

### References
#694 

### Version

4.9

**Comment by Keboo** [comment]
This is a known bug with the flipper due to the 3d stuff that it uses. I have related issues already flagged to try and address with the 5.0 release.

**Comment by Keboo** [comment]
This is "fixed" in 5.0 with the new default flipper following the theme. There is still a classic flipper that has this bug because it is not fixable with the way it does the flip animation and is there for people who ant to preserve that look.
