### ISSUE TITLE
DatePicker Clear Button doesn't work

### ISSUE THREAD

**Issue by hxhgxy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3369]
### Bug explanation

If set HasClearButton, it show correctly, but it doesn't work.

### Version

latest

**Comment by nicolaihenriksen** [comment]
@hxhgxy Can you elaborate on how you think it isn't working?

In the current implementation, the clear button will clear the `DatePicker.SelectedDate` property. This is what is being verified in UI tests and I have confirmed this is working.

What does not work, and what I suspect you may be referring to, is entering arbitrary text (including valid a valid date) into the `TextBox` and the clicking the clear button. I guess this could possibly be added as an enhancement if needed. The clear button currently ONLY works if the "backing property" has been set.

You will however notice, that if you tab out of the `TextBox`, with invalid text in there, it will automatically clear it.

**Comment by nicolaihenriksen** [comment]
@hxhgxy So I went ahead a created a PR because it does feel a little silly that the clear button only has an effect in some cases and not in others.

**Comment by hxhgxy** [comment]
Thanks! let me try.

**Comment by hxhgxy** [comment]
> @hxhgxy Can you elaborate on how you think it isn't working?
> 
> In the current implementation, the clear button will clear the `DatePicker.SelectedDate` property. This is what is being verified in UI tests and I have confirmed this is working.
> 
> What does not work, and what I suspect you may be referring to, is entering arbitrary text (including valid a valid date) into the `TextBox` and the clicking the clear button. I guess this could possibly be added as an enhancement if needed. The clear button currently ONLY works if the "backing property" has been set.
> 
> You will however notice, that if you tab out of the `TextBox`, with invalid text in there, it will automatically clear it.

yes, you are right. It works if I select a date. It doesn't work if I type text into it. but it disappeared after press tab.
