### ISSUE TITLE
Can't visit 'Quick Start' link in github Wiki

### ISSUE THREAD

**Issue by PieceOfFall** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3392]
### When I tryed visiting the link 'Quick Start',it alerted the warning message below:
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/85009059/1d22aaf9-61ab-45b9-96b5-66065dcf9c7c)

### Version

4.5.0

**Comment by ElieTaillard** [comment]
@Keboo We no longer have the right to modify the wiki. Has anything changed recently?

**Comment by PieceOfFall** [comment]
Nope.Everything is okay now

**Comment by ElieTaillard** [comment]
I still have the issue

**Comment by Keboo** [comment]
I will look into this. We had some issue with lots of bad modifications to the wiki so I turn off outside contributions. But I can look at reverting that.

**Comment by ElieTaillard** [comment]
Okay, I understand. However, the page obviously no longer exists, or we no longer have access to it.
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Super-Quick-Start

**Comment by Keboo** [comment]
Yep sorry, it was removed because its contents no longer applied. I have updated to wiki removing the direct references to it and pointing to useful docs.
