### ISSUE TITLE
ScrollViewerAssist TreeView

### ISSUE THREAD

**Issue by jbooth88** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3398]
### Bug explanation

I think the attached properties in MaterialDesignThemes.Wpf.ScrollViewerAssist do not apply to the TreeView control. 

As an example, if I add the following code to the control template defined in MaterialDesignTreeView, setting IgnorePadding=False starts to have an effect:

`wpf:ScrollViewerAssist.IgnorePadding="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(wpf:ScrollViewerAssist.IgnorePadding)}"` 

This might not be limited to TreeView? idk. MaterialDesignListBox doesn't appear to have them set in the control template either, so maybe this is by design?

### Version

4.9

**Comment by Keboo** [comment]
This is likely just an oversight. It is difficult to keep up with all of the attached properties and making sure they are properly applied in all cases.

**Comment by corvinsz** [comment]
This issue has been open for a while, and from what I understand it isn't hard to fix.
But just for me to clarify: is the fix for this issue to slap the AP `wpf:ScrollViewerAssist.IgnorePadding="True"` on every `ScrollViewer` inside of the MDIX Style Templates?

**Comment by corvinsz** [comment]
@Keboo I think this issue can be closed because it was fixed in the PR #3717

**Comment by Keboo** [comment]
ah thank you!
