### ISSUE TITLE
[FR] DatePicker: Only select month and year/only year

### ISSUE THREAD

**Issue by tim-gromeyer** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3402]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I would like to be able to use `DatePicker` to only select a month and year or only the year. It could be added to ``DatePickerAssist`

**Describe alternatives you've considered**
Use a combobox with range of year

**Additional context**

**Comment by nih-milestone** [comment]
@tim-gromeyer Currently, MDIX is simply "restyling" the built-in `DatePicker`. What you're requesting here seems more like a new custom control? I mean I don't suspect you want to re-use the current UI for the `DatePicker` in a scenario where you only want to select a year?

I guess what I am asking is whether you could elaborate a little on what it is you want? Screenshots of similar controls, wireframe mockups or similar?

Thanks

**Comment by nicolaihenriksen** [comment]
@tim-gromeyer Currently, MDIX is simply "restyling" the built-in `DatePicker`. What you're requesting here seems more like a new custom control? I mean I don't suspect you want to re-use the current UI for the `DatePicker` in a scenario where you only want to select a year?

I guess what I am asking is whether you could elaborate a little on what it is you want? Screenshots of similar controls, wireframe mockups or similar?

Thanks
