### ISSUE TITLE
Position of Hint and ClearButton in fields by FontSize=20

### ISSUE THREAD

**Issue by EdTyu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3418]
### Bug explanation

from Version 4.8.1 the position of the hint in combobox and clear button in input fields are wrong by FontSize=20
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/51865923/632a1d13-e132-4b27-8330-ec8b7ca343ee)

### Version

4.8.1, 4.9.0

**Comment by nicolaihenriksen** [comment]
@EdTyu @Keboo I agree that this is a bug, however I think it may not be straightforward to fix without breaking something else.

The changes that went in version 4.8.1 introduced a quite large refactoring around the placement of the SmartHint. There are **MANY** factors that affect where the icons, hints, pre-/suffix text elements should be placed, many of these were not taken into account before version 4.8.1 (stuff like `Control.Height`, `Control.Padding`, `Control.Margin`, `Control.VerticalContentAlignment`, `SmartHint.FloatingScale`, and others). Taking the font size into account as well is probably doable to some extent, but if anyone takes a stab at this, please keep the other properties in mind. The page shown here ("Fields line up") does not lend itself very well to testing those capabilities. A better page to use is "Smart Hint" where you can control a lot more stuff. And as you will notice, on there it actually states that only the default font size is currently (correctly) supported; so this could be considered as a known issue (although we probably should have had an open issue for it).

One "quick fix" for the icons that do not line up is to set `VerticalContentAlignment=Center`. Perhaps this should be the default in the styles.

As for the floated hint, the font size probably needs to be taken (better) into account when calculating the offset. However, here you can also work around it by setting a custom offset via `HintAssist.FloatingOffset=<offset>` to get the appearance you want.

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/152629458/32f52c19-a91c-4faf-a77a-1d1b6e2ca8ab)

**Comment by nicolaihenriksen** [comment]
I believe this has been resolved with the refactoring of the `SmartHint`. If not, please re-open the issue.
