### ISSUE TITLE
Cannot Locate Resource Dictionary "<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Accent/MaterialDesignColor.Lime.xaml"/> in Version 5.0.0-ci479"

### ISSUE THREAD

**Issue by MeshkaM** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3422]
### Bug explanation

when i updated my Nuget package of MaterialDesignThemes from 4.9.0 to 5.0.0-ci479 i got an exception saying 'Cannot locate...' the above resource. When i again reverted to version 4.9.0, everything worked fine, What can it be?

### Version

5.0.0-ci479

**Comment by Keboo** [comment]
There is work to replace all usages of "Accent" with "Secondary" if you do that replacement in the path it should work.
