### ISSUE TITLE
Change MaterialDesignSwitchToggleButton Track background

### ISSUE THREAD

**Issue by alcsdn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3427]
### Bug explanation

Hello everyone!

I need to change the background color of the MaterialDesignSwitchToggleButton when isChecked=True. 

I tried defining a Style based on your Toggle with a trigger, and I noticed that it correctly changes the color of the Thumb (in green), but my intention was to change the color of the Track. 

Actual behavior:
![Toggle Actual](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/119860462/7a11c0c0-3a58-413a-b72d-b6538271c04f)

What I want to achieve:
![Toggle Correct](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/119860462/70c9a9b6-3f02-48aa-848f-10267b24b07e)

Is there a straightforward way to accomplish this?

Any help would be appreciated.
Best regards

### Version

4.9.0

**Comment by JLdgu** [comment]
MaterialDesignInXAML3 has a ToggleButton similar to the one you want.

**Comment by nicolaihenriksen** [comment]
@alcsdn I believe you can accomplish this by setting modifying the values of these attached properties:

`ToggleButtonAssist.SwitchTrackOnBackground`
`ToggleButtonAssist.SwitchTrackOffBackground`
