### ISSUE TITLE
OutlinedRevealPasswordBox's reveal icon not vertically centered

### ISSUE THREAD

**Issue by 9helix** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3440]
### Bug explanation

I noticed that in the demo app 4.9.0 the reveal icon is correctly aligned with the text inside the box for all passwordboxes except for the OutlinedRevealPasswordBox. It looks like this. 
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/62692130/6bc7a67e-000e-41b6-a53a-696434916642)

That same alignment is also on the clear button.
Is there going to be a fix for this? 
In #2812 I saw the workaround, but it is not working for me. Here is how I implemented it in my code:
```xaml
                <PasswordBox VerticalAlignment="Center" materialDesign:TextFieldAssist.HasClearButton="True" FontSize="15" Style="{StaticResource MaterialDesignOutlinedRevealPasswordBox}">
                    <PasswordBox.Resources>
                        <Style TargetType="materialDesign:PackIcon" BasedOn="{StaticResource {x:Type materialDesign:PackIcon}}">
                            <Setter Property="VerticalAlignment" Value="Center" />
                        </Style>
                    </PasswordBox.Resources>
                    <materialDesign:HintAssist.Hint>
                        <!--some controls-->
                    </materialDesign:HintAssist.Hint>
                </PasswordBox>
```
Am I missing something?

### Version

4.9.0

**Comment by JLdgu** [comment]
This is not actually a bug but an 'Optical illussion' feature brought to you by Mk I Eye Ball Inc.

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/114992499/508477bc-a2d4-4b37-9980-262b44f33310)

There is a single pixel gap above each fuchsia line in the included image, edited from the original included with this issue.

That said you can get the effect you want by adjusting the ```VerticalContentAligment``` of the ```PasswordBox```, not the ```VerticalAligment``` of the ```PackIcon```.
```xaml
<PasswordBox materialDesign:HintAssist.HelperText="Not bound password"
             materialDesign:HintAssist.Hint="Password"
             materialDesign:TextFieldAssist.HasClearButton="True"
             IsEnabled="{Binding ElementName=RevealPasswordOutlinedEnabled, Path=IsChecked}"
             Style="{StaticResource MaterialDesignOutlinedRevealPasswordBox}"
             VerticalContentAlignment="Bottom"/>
```
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/114992499/3ebc6989-eb14-4e30-90c4-52deb10fb197)
