### ISSUE TITLE
DataGridCell VerticalAlignment Issue

### ISSUE THREAD

**Issue by antoine-carpentier** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3445]
### Bug explanation

When I change the value of the `DataGridCell` `VerticalAlignment` property to `Top` or `Center`, a line appears under my cell.

```
<DataGrid.Resources>
    <Style TargetType="DataGridCell" 
           BasedOn="{StaticResource MaterialDesignDataGridCell}">
        <Setter Property="VerticalAlignment" Value="Stretch" />
    </Style>
</DataGrid.Resources>
```

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/81534267/a26e72e4-bde8-4499-8d57-28e755d1e541)

```
<DataGrid.Resources>
    <Style TargetType="DataGridCell" 
           BasedOn="{StaticResource MaterialDesignDataGridCell}">
        <Setter Property="VerticalAlignment" Value="Center" />
    </Style>
</DataGrid.Resources>
```

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/81534267/20e56be4-00cb-434b-9845-07639a5c3644)

### Version

4.7.0

**Comment by antoine-carpentier** [comment]
The issue ended up not related To Material Design.

**Comment by OMGCHEN** [comment]
> 最终发现这个问题与 Material Design 无关。


I encountered the same issue. When I set the RowHeight and configured VerticalAlignment for the cell style, why do extra border lines appear? And why did you say it has nothing to do with Material Design? How did you resolve this problem? 

```
        <DataGrid Grid.Row="3" Grid.Column="1" Background="Transparent" 
                  ItemsSource="{Binding Group.AtQCList}"
                  Style="{StaticResource MaterialDesignDataGrid}"
                  AutoGenerateColumns="False"
                  IsReadOnly="True"
                  RowHeight="50"
                  md:DataGridAssist.SelectedCellBorderBrush="Transparent">
            <DataGrid.CellStyle>
                <Style TargetType="DataGridCell" BasedOn="{StaticResource MaterialDesignDataGridCell}">
                    <Setter Property="VerticalAlignment" Value="Center" />
                </Style>
            </DataGrid.CellStyle>
            <DataGrid.Columns>
                <DataGridTextColumn Header="Name" Binding="{Binding Name}">
                </DataGridTextColumn>
                <DataGridTextColumn Header="Mobile" Binding="{Binding Mobile}" />
            </DataGrid.Columns>
        </DataGrid>
```


<img width="691" height="97" alt="Image" src="https://github.com/user-attachments/assets/71400469-8214-4926-a9d2-1ca42ccc5438" />


If I leave VerticalAlignment as its default value Stretch, the display works fine, but the cell content cannot be vertically centered.

<img width="689" height="96" alt="Image" src="https://github.com/user-attachments/assets/be8f2565-6deb-45c8-90f9-f548b76cd466" />
