### ISSUE TITLE
Combox context user HorizontalContentAlignment="Center" is invalid

### ISSUE THREAD

**Issue by sapoiuyt** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3447]
### Bug explanation

Combox context user HorizontalContentAlignment="Center" is invalid

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@sapoiuyt Can you provide a little more context? In the demo app, the horizontal centering seems to work fine...

![ComboBoxes](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/82934409-b88a-47f7-921c-e08fb11d22a4)

**Comment by nicolaihenriksen** [comment]
@sapoiuyt Could it possibly be the same as this issue: #3433? It seems plausible that is what you're experiencing, and I have added a PR to fix it.

**Comment by Keboo** [comment]
Closing under the assumption that #3458 resolved the issue, if not please let us know
