### ISSUE TITLE
DialogHost focus problem

### ISSUE THREAD

**Issue by alexachso** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3450]
### Bug explanation

I have a root DialogHost in the MainWindow. I use it to pop custom dialogs for the user to interact with when a decision must be made about something. In one of my custom user control that the dialog host must have as content is a simple combobox for the user to choose from. With the latest prerelease the dialog host loses focus instantly when the popup of the combobox is opened.
In 4.9.0 there is no problem. 
I think the bug has been introduced with this P-R : [Fix dialog focus #3249](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/3249)

It was mentioned in this issue : [Sometimes dialoghost doesn't have focus. #2912](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2912)

I have made a simple app using the keboo.wpf template to see for yourself. Change the Nuget package for 4.9.0 and there is no issue. Then, switch to the latest prerelease and you will not be able to choose an item from the combobox. 
[DialogHostIssue.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/14180067/DialogHostIssue.zip)

### Version
5.0.0-ci528

**Comment by Keboo** [comment]
Fixed by #3451
