### ISSUE TITLE
Change Combobox Popup Top and Bottom Margin

### ISSUE THREAD

**Issue by arman-hpp** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3462]
I use wpf MaterialDesignInXamlToolkit combobox in my project. I want to change combobox popup top and bottom margin. please add this feature

**Comment by nicolaihenriksen** [comment]
@arman-hpp Can you elaborate a little bit on what exactly it is you would like? Is it the `ComboBox` itself you want to control `Margin` (or probably `Padding` I assume)? Or is it on the drop-down content? Or perhaps even the individual items in the drop-down content?

If you can elaborate a bit more on what you're trying to achieve, it will be easier to give some advice/guidance.
