### ISSUE TITLE
Combobox not centering the selected item

### ISSUE THREAD

**Issue by mouawadma** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3471]
### Bug explanation

This is I think the same problem as was reported in #897 . that was marked as complete but I am still having this issue.

Installed themes uisng Nuget, using .net framework 4.7.2.

# The Issue
When I set `HorizontalContentAlignment` to `Center` for a combo box. It does not center the selected item

code
```
<ComboBox HorizontalContentAlignment="Center"
          Width="200">
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
</ComboBox>
```

result
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/94063112/5d5fc252-1ef7-475c-a7ea-ce8107064096)

# Expected behavior
When `HorizontalContentAlignment` is set to center, it should center everything (this is the default behavior of WPF as I tested using no MDIX). I have temporarily fixed this by overriding the style for the content presenter using the following code

code
```
<ComboBox HorizontalContentAlignment="Center"
          Width="200">
    <ComboBox.Resources>
        <Style TargetType="ContentPresenter">
            <Setter Property="HorizontalAlignment"
                    Value="Center" />
        </Style>
    </ComboBox.Resources>
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
    <ComboBoxItem Content="Test1" />
</ComboBox>
```

result
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/94063112/05eed24f-c958-425f-886c-7000430a0c50)

### Version

4.9.0

**Comment by nicolaihenriksen** [comment]
@mouawadma I can confirm this issue is present in the `4.9.0` release and prior, but it no longer reproduces in `5.0.0`. Can you confirm this on your end and close the issue if so?
