### ISSUE TITLE
AutoSuggestBox style and demo app issues

### ISSUE THREAD

**Issue by nicolaihenriksen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3476]
### Bug explanation

It seems the AutoSuggestBox is having some issues. The layout in the demo app (`Fields` page) is not ideal, and there also appears to be an issue with the outlined style (hint text is displayed twice).

**UPDATE**: Checking out the commit (9be7c3d6c3fafdd28fff442723dc3bb8954eafe7) where the PR merged to master (in detached HEAD state), I can see the same issue. So it would appear it has been like this on main since it merged.

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/52e85400-2eac-413e-9d06-ae1a53742742)

### Version

5.0.0

**Comment by nicolaihenriksen** [comment]
@AbderrahmaneAhmam Would you care to take a look at this issue?

**Comment by AbderrahmaneAhmam** [comment]
> @AbderrahmaneAhmam Would you care to take a look at this issue?

Hello, I am currently working on resolving this issue.
