### ISSUE TITLE
MaterialDesignThemes5.0.0 missing "themes/materialdesigntheme.defaults.xaml" file

### ISSUE THREAD

**Issue by ChangXiang-Kong** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3485]
### Bug explanation

Issue:
I created a WPF project and download the MaterialDesignThemes5.0.0 to my project, 
when I introduced MaterialDesign resoureces and startup the project, 
it arised an Exception 【IOException: 找不到资源“themes/materialdesigntheme.defaults.xaml”。】
![QQ20240309134247](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/33409360/788c3d84-216d-49db-abf4-0978edd5186e)

Solution:
I uninstalled the MaterialDesignThemes5.0.0 and try to download MaterialDesignThemes4.9.0, then I startup the project, it worked
![MO@)7PL%4O`_A {TS`DBXWQ](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/33409360/7e417aa8-5aaa-4020-9598-b9db00aae958)

### Version

V5.0.0

**Comment by Keboo** [comment]
This is expected with the 5.0.0 release. You need to change to either using the MaterialDesign2 or MaterialDesign3 defaults instead. See the migration guide here: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/3466

**Comment by AndreeHub** [comment]
Can you guys at least update the documentation for this. I lost 4 days thinking it was something wrong with the compiling, building process :(

**Comment by Keboo** [comment]
Yea I am looking at getting things updated, and you should see the content changing over the next week or two.

**Comment by bebenins** [comment]
@Keboo couple of questions, I'm sorry if off-topic.  I have been super busy with work and haven't updated to new MD for a long time.
1. Is there still an active group message board where people discuss issues/suggestions/asking quick questions?  I remember there used to be one but I forgot how to get there.
2. I have the following issue https://stackoverflow.com/questions/78163188/materialdesignmahappsbundledtheme-is-gone-with-5-0-0-release-but-still-works-in 

I would ask this on a message board not to spam the Issue log but like I said, I even forgot how to get there
Any help really appreciated.  Thanks!

**Comment by Keboo** [comment]
@bebenins great to hear from you.

1. You can find a message board on discord: https://discord.keboo.dev

2. Which version of `MaterialDesignThemes.MahApps` are you referencing? I am noticing that my pipeline does not appear to have published the full release of the NuGet package (a bug I will see about fixing soon). In the meantime you should be able to grab the latest preview package with 5.0.0 just fine.

**Comment by bebenins** [comment]
@Keboo Thank you!  It was stupid me, I remove this reference entirely from my base DLL.  Totally forgot the dependencies.
I might have a couple more questions but I will read out on discord.  But in any case I'm running 5.0!
Thanks!
