### ISSUE TITLE
DataGridColumn Regressed To The System Style

### ISSUE THREAD

**Issue by BenMendel** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3488]
### Bug explanation

On version 4.9.0, when using a DataGridCheckBoxColumn in a DataGrid, the checkbox style was the same as defined in the MDIX library. In 4.9.0 demo:
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/146622307/511f5f6c-86af-4123-8fd3-b24be2520816)

While in version 5.0.0, the ComboBox style looks like the system default and does not inherit the ComboBox style from MDIX library. In 5.0.0 demo:
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/146622307/886d5c4b-4394-4188-aead-c3dc94afb6cc)

### Version

5.0.0

**Comment by Keboo** [comment]
Thank you for pointing this out. I have put in a fix that will be in the 5.1.0 nightly release coming out later tonight.
