### ISSUE TITLE
Gives Error while Taking in Secondary Colors Resource

### ISSUE THREAD

**Issue by AshwinPrksh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3489]
### Bug explanation

According to the tutorial, I have copied all the Resource Dictionary Commands to App.xaml but while compiling, its giving me an IOExceptionError: Cannot locate resource 'themes/recommended/accent/materialdesigncolor.green.xaml'. 

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/142385893/3f3afdad-cb51-42cc-80f9-48d3cd9c0759)

### Version

5.0.0

**Comment by AshwinPrksh** [comment]
I didn't see the new release guide. No need for further inspection

**Comment by Keboo** [comment]
No problem. Happy coding!
