### ISSUE TITLE
Cant switch themes after updating to 5.0

### ISSUE THREAD

**Issue by Jonesie** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3493]
### Bug explanation

I have the following code to switch between dark and light themes.  Since updating to 5.0 this no longer works.  Theme.Dark and Theme.Light dont exist any more.  Also swatch.AccentExemplarHue is gone.  I cant remember where I got this code from but it was working.  The Advanced theming page in the wiki will also be incorrect now.

```
var sp = new SwatchesProvider();
var swatch = sp.Swatches.FirstOrDefault(p => p.Name == "deeppurple");
if (swatch != null)
{
  var darkTheme = Theme.Create(Theme.Dark, swatch.ExemplarHue.Color, swatch.AccentExemplarHue.Color);
  var lightTheme = Theme.Create(Theme.Light, swatch.ExemplarHue.Color, swatch.AccentExemplarHue.Color);
  new PaletteHelper().SetTheme(_darkTheme ? darkTheme : lightTheme);
}
```

### Version

5.0

**Comment by jbooth88** [comment]
I don't know if it's the "right way", but try this

```
var newTheme = _darkTheme ? BaseTheme.Dark : BaseTheme.Light;
var colorKey = nameof(MaterialDesignColor.DeepPurple);
var swatchProvider = new SwatchesProvider();
var swatch = swatchProvider.Swatches.FirstOrDefault(x => string.Equals(x.Name, colorKey, StringComparison.OrdinalIgnoreCase));
if (swatch != null)
{
    var paletteHelper = new PaletteHelper();
    var theme = paletteHelper.GetTheme();
    theme.SetBaseTheme(newTheme);
    theme.SetPrimaryColor(swatch.ExemplarHue.Color);
    theme.SetSecondaryColor(swatch.SecondaryExemplarHue?.Color ?? swatch.ExemplarHue.Color); //nullable SecondaryExemplarHue? I don't know what to do here.
    paletteHelper.SetTheme(theme);
}
```

**Comment by Keboo** [comment]
It is actually slightly easier to do in the 5.0 release.

You still need to get an instance of the `Theme`. This will typically be done with `PaletteHelper.GetTheme()` or the `GetTheme()` extension method on `ResourceDictionary`. Once you have that theme instance you can switch between Light/Dark themes simply by calling `SetDarkTheme()`/`SetLightTheme()` directly on it, which will update the internal brushes with the corresponding values. Finally, to apply the theme, you will need to call `PaletteHelper.SetTheme(Theme)` or more generically the `SetTheme()` extension method on `ResourceDictionary`.

**Comment by Jonesie** [comment]
Thanks people :)

This works:
```
var ph = new PaletteHelper();
var theme = ph.GetTheme();
if (theme != null)
{
  if (_darkTheme)
    theme.SetDarkTheme();
  else
    theme.SetLightTheme();
  ph.SetTheme(theme);
}
```
