### ISSUE TITLE
NullVisibilityConverter and InvertedNullVisibilityConverter is missing after upgrade to 5.0

### ISSUE THREAD

**Issue by dsalalex** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3494]
### Bug explanation

NullVisibilityConverter and InvertedNullVisibilityConverter is missing after upgrade to 5.0

### Version

5.0

**Comment by Keboo** [comment]
These were replaced by the more generic `MaterialDesignThemes.Wpf.Converters.NullableToVisibilityConverter` (source [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/239fd797a63e198bb846849f874486b9bb5d0559/MaterialDesignThemes.Wpf/Converters/NullToVisibilityConverter.cs)). It supports specifying the `Visibility` values that null or not null should return.

**Comment by dsalalex** [comment]
@Keboo Thanks!
