### ISSUE TITLE
Add method overload for ShowDialog extension with identifier

### ISSUE THREAD

**Issue by Myliak** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3503]
**Is your feature request related to a problem? Please describe.**
It's rather simple problem, when iterating through xaml object tree, it would be nice to define identifier which must be on found DialogHost, so if multiple are present, it chooses correct one

**Describe the solution you'd like**
Create an overload method that accepts string identifier, exactly as is in DialogHost.ShowDialog

**Describe alternatives you've considered**
I don't think there are any, except for using only one dialoghost (so I take this as low prio)

**Comment by MichelMichels** [comment]
Could you explain a bit better what you'd like to be added? The code in `DialogHost.Show(...)` already accepts an identifier. I think I'm missing some information.

**Comment by Myliak** [comment]
No problem, there are two variations of how to open Dialog window in code:
1. `DialogHost.Show(...)` as you said - [Wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs#dialoghostshow)
2. `.Show(...)` Extension, which does not have the identifier overload - [Wiki](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Dialogs#show-extension-method)

The second one is the one I would like to add overload to :)

**Comment by MichelMichels** [comment]
@Myliak I submitted a PR. Would you check if this adds the functionality you need?
