### ISSUE TITLE
Wiki: Some button style keys are outdated

### ISSUE THREAD

**Issue by Pixel-Pile** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3505]
Hi,  I noticed a small issue with the wiki. If i understood correctly you're supposed to open an issue or discussion before making changes to the wiki. I had to choose between feature request and bug report when opening an issue. I chose feature request because that seemed more relaxed. 

The wiki has pages listing all styles of an control. Some Button and ToggleButton styles are outdated, they still contain "Accent" althougt they were renamed to "Secondary".

The outdated [Button styles](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Button-Styles) are:
- MaterialDesignRaisedAccentButton
- MaterialDesignFloatingActionAccentButton

The outdated [ToggleButton styles](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Toggle-Button-Styles) are:
- MaterialDesignActionAccentToggleButton

**Comment by MichelMichels** [comment]
Hi, this is indeed the old naming style. I'll look into fixing this asap.

**Comment by MichelMichels** [comment]
I edited the wiki with the right naming convention. I'd advise using the demo app for the latest and most up-to-date showcase of this library instead of the wiki. Imo the wiki needs a bit of love and polish to reach the same quality that the demo app offers.
