### ISSUE TITLE
Wrong size and wrong 'look and feel' for ToggleButton with Style="{StaticResource MaterialDesignSwitchToggleButton}"

### ISSUE THREAD

**Issue by DrCQ** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3508]
### Bug explanation

After migration from 4.9.x to 5.0.0 the appearance of the standard `ToggleButton` with standard style `(MaterialDesignSwitchToggleButton)` is changed and wrong. The button looks different as shown in the demo application. The size is bigger and the circle is located inside the ellipse. Changing the width or height value of the `ToggleButton`  is changing the visibility of the control and is cutting parts of the button. To scale the appearance of the `ToggleButton` an `ViewBox` control must be used.
Expected look: 
<img width="164" alt="ToggleButton-demo" src="https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/49019093/f2492019-b38f-407b-9412-13c164de3e97">
Current look:
<img width="86" alt="ToggleButton-buggy" src="https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/49019093/abc42f85-dfee-4ed0-8c26-332eb7289132"> On the left: standard view, on the right: inside the `ViewBox`

### Version

5.0.0

**Comment by DrCQ** [comment]
I just compiled the original code and all `ToggleButton`'s looks wrong.
<img width="634" alt="ToggleButton-new demo" src="https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/49019093/6c382f3a-14e6-4b2b-92a0-46e3e939af1c">

**Comment by Keboo** [comment]
@DrCQ that looks like you are using the new Material Desing 3 styles. This new look is expected and correct, as it is designed to match the change from Material Desing 2 to Material Design 3 specification (https://m3.material.io/components/switch/overview).

If you want the old look back, in your App.xaml you can select if you would prefer the material design 2 styles, by using that default resource dictionary.

```xaml
        <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign2.Defaults.xaml" />

```

**Comment by DrCQ** [comment]
Thanks, my mistake.
