### ISSUE TITLE
Improve Snackbar feature so that multiple messages can display simultaneously

### ISSUE THREAD

**Issue by ChangXiang-Kong** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3509]
### **Current Snackbar Feature:**
Only one message can be displayed when the button is clicked multiple times, as follows:

![PixPin_2024-03-31_02-23-04](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/33409360/88de8d4d-37b8-4ee4-b477-5dc677baa385)

### **Expected Snackbar Feature:**
Click the button multiple times to display multiple messages at the same time, as follows:

![PixPin_2024-03-31_02-47-47](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/33409360/79bdeb47-6c43-4151-92d8-7ba513248bf9)

hope this gif can give you some inspiration 😊

**Comment by Keboo** [comment]
The design of a material design snackbar explicitly states that only one should be shown at a time.

> Frequency
> Only one snackbar may be displayed at a time.

https://m3.material.io/components/snackbar/guidelines#ae0935b0-a14e-4dec-8c3c-2c0809acffeb


What Element is showing there is a new control entirely (it appears they call it a "Message" which is different from a snackbar. I would not be opposed to accepting a PR for this type of control, but it is a bit out of scope of what this library aims to bring.

**Comment by ChangXiang-Kong** [comment]
@Keboo  Thanks for your answer, message notification is a nice and  necessary feature in application. 
The use case for the Snackbar control has some limitations, and it can be extended into a more comprehensive message notification feature.
