### ISSUE TITLE
Floating Action Popup Box - UI issue after click mouse over

### ISSUE THREAD

**Issue by amoamare** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#351]
Current result
After clicking on the element the animation immediately reverts back to original icon state 
![image](https://cloud.githubusercontent.com/assets/15149902/14749324/b9014880-0873-11e6-903c-b520c4eb8106.png)

Expected result
Is to keep the toggle checked icon until user leaves the icon
![image](https://cloud.githubusercontent.com/assets/15149902/14749356/d98ae232-0873-11e6-85bf-1013e714ba3c.png)

**Comment by ButchersBoy** [comment]
I'm not sure I agree.  If you have a popup (i.e a series of smaller action buttons) then clicking will close the popup (and re-open).  If you have custom OnConntent - like  you your picture - that you are going to respond to, then the likelyhood is you are then going to jump to another action for the user to interact with; a new screen or dialog etc.

What is your use case?

**Comment by amoamare** [comment]
My use case was based on googles own Material UI. In inbox.google.com when you hover over the + compose and click on it, it does not change after clicking on it. You must leave the compose button for it to switch back. This is similar to a few other of their desktop or web apps for computer. 

Yes if you have a custom OnContent it works as intended. 
But if you do something similar to inbox where you are updating the underlying content this does not change until that user leaves the compose.


It's hard to demonstrate in an image
![image](https://cloud.githubusercontent.com/assets/15149902/15059579/574b5dfa-12d8-11e6-85c3-621ac464ab3c.png)

**Comment by ButchersBoy** [comment]
OK, fair-enough; I can see that now.

**Comment by mgnslndh** [comment]
What is the proposed solution for this issue? Not sure I understand, but it seems to me that there is a need for the FAB to support two behaviours?

**Comment by Keboo** [comment]
I am thinking this can probably be closed. 
From the [docs](https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions)

> Upon press, the FAB remains visible and emits a stack of related actions. If the FAB is tapped is pressed in this state, it should either initiate its default action or close the speed dial actions.

As far as I can tell, if you use a popup box (like what is done in the [demo](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Home.xaml#L139-L178)). It appears to match the desired behavior. 

Anything I have missed?

**Comment by mgnslndh** [comment]
I think that is the proper behaviour as well. But @amoamare mentions a behaviour of a button in Google Inbox that I can no longer find. Perhaps we can close and or request more details.

> But if you do something similar to inbox where you are updating the underlying content this does not change until that user leaves the compose.

**Comment by Keboo** [comment]
Agreed. Closing for now. If anyone is facing this issue please provide additional detail as to the expected behavior.
