### ISSUE TITLE
Need to update website

### ISSUE THREAD

**Issue by HJ0216** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3523]
### Bug explanation

Hello!

I'm using Material Design Themes v5.0.0 with Framework .NET 8.0.

I need some guidance on the code snippet that goes into app.xaml for a version of 5.0.0 on the homepage.

```xml
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign3.Defaults.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Primary/MaterialDesignColor.DeepPurple.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/Recommended/Secondary/MaterialDesignColor.Lime.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

1. MaterialDesignTheme.Defaults.xaml -> MaterialDesign3.Defaults.xaml
2. Accent/MaterialDesignColor.Lime.xaml -> Secondary/MaterialDesignColor.Lime.xaml

I don't know why, but when i used Accent, I couldn't get the xaml to apply.

### Version

5.0.0

**Comment by Keboo** [comment]
Unfortunately, I do not actually have control over the web site. It has been out of date for a while, and we have moved the content into this repository where we can keep it updated.
