### ISSUE TITLE
Can not be used under Wndows 2016 Standard

### ISSUE THREAD

**Issue by yuexueyang** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3524]
### Bug explanation

I Create an App using verision 5.0.0, but can not start it on machine running windows 2016 standard, and then I run your demo application, it can not start too. I tested this case under .net8 and .net6.

![Weixin Screenshot_20240415135622](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/112361878/357c43e9-7543-4027-8e87-1ceaad27bf7e)
![Weixin Screenshot_20240415135719](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/112361878/4942f806-f394-4457-8228-dab885f95552)

### Version

5.0.0

**Comment by Keboo** [comment]
Can you open the Windows Event Viewer and see if there are any errors logged there? Often when an app fails to start it, it is because there is an unhandled exception during startup.

**Comment by yuexueyang** [comment]
Yes, there is an exception recorded,  and more information for your reference: my application did not use the new style introduced in 5.0, but still use the style of 4.X, below is my code in app.xaml, it works fine in windows 10 profesional, but also failed on Windows 10 Enterprise LTSC.
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/112361878/e65a023c-b178-4d38-a600-a212b9a82e6e)

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/112361878/97d8240b-9f89-4b13-8d99-53b72f302de6)

**Comment by Keboo** [comment]
Thank you. I believe this should be addressed by this PR: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/3531
