### ISSUE TITLE
Event Handler Leak on every button click - System.Windows.VisualStateManager+<>c__DisplayClass12_0 

### ISSUE THREAD

**Issue by VibinKesavan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3539]
### Bug explanation

Hi, 
I am using this package in my app, and while I was doing memory profiling of the app using dotmemory, I am getting 
Event handlers leak  

Type: System.Windows.VisualStateManager+<>c__DisplayClass12_0
Retained Size: 3,360
Count: 105

Every button click is creating a handler leak, so far its not breaking the app, but I through of raising it so that we can fix it. can you please help ? 

### Version

5.0.0

**Comment by nicolaihenriksen** [comment]
@VibinKesavan Could you share a sample application where you can see this leak? In a very simple app with just a MDIX styled button, I do not see this leak.

Many factors could influence the outcome, so if you don't have a sample application, please elaborate on which particular style of button is used, which bindings are set up and so on. Thanks.
