### ISSUE TITLE
TransitionContent removes Command Binding

### ISSUE THREAD

**Issue by LoRdPMN** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#354]
Firstly, thanks for such great toolkit!

I think I found a bug (or am I doing something wrong?), when trying to animate a Button, if I do this:

```

<md:TransitioningContent>
    <md:TransitioningContent.OpeningEffects>
        <md:TransitionEffect Kind="SlideInFromLeft" Duration="00:00:00.8" />
        <md:TransitionEffect Kind="FadeIn" Duration="00:00:00.8" />
    </md:TransitioningContent.OpeningEffects>
    <Button x:Name="PART_ButtonSave" Content="Salvar" Width="100" Command="{Binding SaveCommand, ElementName=Root}" />
</md:TransitioningContent>
```

The transition works, but the Command Binding doesn't work anymore. If I remove all the transition code, without changing anything else the binding works normally:

`<Button x:Name="PART_ButtonSave" Content="Salvar" Width="100" Command="{Binding SaveCommand, ElementName=Root}" />`

**Comment by ButchersBoy** [comment]
What is "Root"?

**Comment by LoRdPMN** [comment]
This button belongs to an user control, "Root" is a name given to the <UserControl> tag (root element of this xaml file), SaveCommand is a DependencyProperty of the user control (so I can bind a command to it whenever I use the user control).

Basically the button is binding to a property of the user control that it belongs to.

**Comment by LoRdPMN** [comment]
I had this problem again, but without the button being the direct child of the transition, and also with a contentpresenter, so I tried to find a workaround and/or discover the source of the problem.

When I tried to change the source of the binding from an ElementName to a RelativeSource it worked normally, so I think something is clearing the binding when its source is an ElementName, I tried to find something in the toolkit source code, but I am new to WPF and could not find the root of the problem.

Here is a sample that loses the binding (it doesn't when not a TransitionContent child)

```
<md:TransitioningContent Grid.Row="1">
	<md:TransitioningContent.OpeningEffects>
		<md:TransitionEffect Kind="SlideInFromBottom" Duration="00:00:00.5"/>
		<md:TransitionEffect Kind="FadeIn" Duration="00:00:00.5"/>
	</md:TransitioningContent.OpeningEffects>
	<md:ColorZone x:Name="PART_ButtonsHost" Mode="PrimaryLight" Padding="10">
		<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" b:Spacing.Horizontal="5" >
			<Button x:Name="PART_ButtonSave" Style="{StaticResource MaterialDesignRaisedButton}" Command="{Binding ElementName=CRUDRoot, Path=ViewModel.SaveCommand}" IsDefault="True">
				<StackPanel Orientation="Horizontal" b:Spacing.Horizontal="2">
					<md:PackIcon Kind="ContentSave" VerticalAlignment="Center"/>
					<TextBlock Text="Salvar"/>
				</StackPanel>
			</Button>
		</StackPanel>
	</md:ColorZone>
</md:TransitioningContent>
```

And here the same controls working, but using RelativeSource:

```
<md:TransitioningContent Grid.Row="1">
	<md:TransitioningContent.OpeningEffects>
		<md:TransitionEffect Kind="SlideInFromBottom" Duration="00:00:00.5"/>
		<md:TransitionEffect Kind="FadeIn" Duration="00:00:00.5"/>
	</md:TransitioningContent.OpeningEffects>
	<md:ColorZone x:Name="PART_ButtonsHost" Mode="PrimaryLight" Padding="10">
		<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" b:Spacing.Horizontal="5" >
			<Button x:Name="PART_ButtonSave" Style="{StaticResource MaterialDesignRaisedButton}" Command="{Binding RelativeSource={RelativeSource AncestorType={x:Type local:RepositoryCRUD}}, Path=ViewModel.SaveCommand}" IsDefault="True">
				<StackPanel Orientation="Horizontal" b:Spacing.Horizontal="2">
					<md:PackIcon Kind="ContentSave" VerticalAlignment="Center"/>
					<TextBlock Text="Salvar"/>
				</StackPanel>
			</Button>
		</StackPanel>
	</md:ColorZone>
</md:TransitioningContent>
```
I don't know if using ElementName is a bad practice, but i think there should no difference at this scenario.

**Comment by alexandredsimoes** [comment]
Same here.
Looses all binding 
[Transition Issues.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/444966/Transition.Issues.zip)

**Comment by bebenins** [comment]
The simplest way to reproduce this issue:
<DockPanel>
                <materialDesign:TransitioningContent>
                    <Grid>
                        <CheckBox x:Name="checkBox"/>
                    </Grid>
                </materialDesign:TransitioningContent>
                <materialDesign:TransitioningContent>
                    <Grid>
                        <CheckBox Margin="30,0,0,0" IsChecked="{Binding ElementName=checkBox, Path=IsChecked}"/>
                    </Grid>
                </materialDesign:TransitioningContent>
            </DockPanel>

**Comment by bebenins** [comment]
The simplest way to reproduce this issue

`<DockPanel>
                <materialDesign:TransitioningContent>
                    <Grid>
                        <CheckBox x:Name="checkBox"/>
                    </Grid>
                </materialDesign:TransitioningContent>
                <materialDesign:TransitioningContent>
                    <Grid>
                        <CheckBox Margin="30,0,0,0" IsChecked="{Binding ElementName=checkBox, Path=IsChecked}"/>
                    </Grid>
                </materialDesign:TransitioningContent>
            </DockPanel>`

**Comment by Insire** [comment]
Just encountered this problem aswell. @ButchersBoy do you need a Repo for this?

**Comment by ButchersBoy** [comment]
Yes, always helps, takes previous time setting up scenarios for every bug.

**Comment by Insire** [comment]
Alright, i reused my trusty [TestApp](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp). The ElementBinding Fails with a [ToggleButton(x:Name="DetailViewToggleButton")](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp/blob/master/TestApp/MainWindow.xaml#L209) in line [235](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp/blob/master/TestApp/MainWindow.xaml#L235) and line [243](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp/blob/master/TestApp/MainWindow.xaml#L243) in the MainWindow.xaml

**Comment by MichelMichels** [comment]
I tested this bug report with the last version of MDIX and could not reproduce this bug. Closed.
