### ISSUE TITLE
SplitButton style

### ISSUE THREAD

**Issue by jbooth88** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3549]
### Bug explanation

Some button properties in the new materialDesign:SplitButton control are unable to be changed without overriding the ButtonStyle. 

For example, altering the font size affects the popup, but the left button (PART_LeftButton) is stuck at 14pt.
I don't know if this is a bug or by design. 

### Version

5.0

**Comment by nicolaihenriksen** [comment]
@jbooth88 seems like a bug to me. We should probably forward some additional common, non-inheritable, properties (like `FontSize`) down to the nested button [here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/dd9c6f9f908dc92d8aa4692727de05ea6d6d6a40/src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SplitButton.xaml#L49-L61).

**Comment by Keboo** [comment]
So right now the `ButtonStyle` is what is used to configured the internal buttons. If we do template bindings (which I _think_ might be the right answer), then anything with a template binding can't be set via that style. 

I am thinking we might want to just obsolete that property and use template bindings for everything as that is a more common use case. Thoughts?

**Comment by nicolaihenriksen** [comment]
@Keboo So the `SplitButton.ButtonStyle` DP, in my mind, is an implementation detail. It is really only public to allow for consumers to copy-paste-modify the style and still have it compile. The same result could have been achieved without a DP, but simply a well-known resource key (this approach is used for the `DatePicker`; [see here](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/dd9c6f9f908dc92d8aa4692727de05ea6d6d6a40/src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.DatePicker.xaml#L180-L182)), or an attached property.

The DP serves a single purpose: Mapping an MDIX `SplitButton` style to the corresponding MDIX `Button` style. E.g.:
`MaterialDesignFlatDarkSplitButton` -> `MaterialDesignFlatDarkButton`,
`MaterialDesignOutlinedLightSplitButton` -> `MaterialDesignOutlinedLightButton`,
etc.

As such, I think it is fair to simply forward the "common properties" through via `TemplateBindings` just like it is [already doing for a number of the properties](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/dd9c6f9f908dc92d8aa4692727de05ea6d6d6a40/src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.SplitButton.xaml#L51-L57). "Common properties" probably covers any property that is intended to have a visual (and/or possibly behavioral) effect that is relevant to the `SplitButton`.
