### ISSUE TITLE
Update the wiki: Broken Links in Project Wiki

### ISSUE THREAD

**Issue by 5TFG4** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3553]
### Description
Hello, I've noticed that some of the file links in the project's wiki are broken. For instance, the link to the "Toolkit's Demo" in the [Getting-Started](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started) page points to an incorrect URL. It seems that the issue might have occurred because the linked files were moved out of the `src` directory.

### Examples of Broken Links
- ["Toolkit's Demo" link](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Getting-Started#aftermath) in Getting-Started page: [Broken link](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/tree/master/MainDemo.Wpf)

### Proposed Solution
I have corrected these links in my fork of the repository. You can review the changes here: [My Fork](https://github.com/5TFG4/MaterialDesignInXamlToolkit)

### Suggested Next Steps
I would appreciate it if the maintainers could review my changes and consider merging them into the main repository. If any further modifications or discussions are needed, please let me know. 

### Version

5.0.0

**Comment by 5TFG4** [comment]
I just found out that almost all the links in both DocumentationLink.cs in [MainDemo.Wpf](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/src/MainDemo.Wpf/Domain/DocumentationLink.cs) and [MaterialDesign3.Demo.Wpf](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/src/MaterialDesign3.Demo.Wpf/Domain/DocumentationLink.cs) are broken in the same way.

**Comment by Keboo** [comment]
Great catches, and thank you for your fork. Let me dig in and we will see about getting all of these updated. We recently reorganized the repo, which appears to the source of many of the link breaks.

**Comment by Keboo** [comment]
Thank you, I believe all of these should now be fixed. If there are any more remaining broken ones please let me know
