### ISSUE TITLE
Suggest adding a multi selection combo box control

### ISSUE THREAD

**Issue by shengzhijie** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3560]
Hello, I suggest adding a multi selection combo box control.
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/12422953/e01c8982-4166-4130-87b3-d10f021fb95f)

**Comment by nicolaihenriksen** [comment]
This has been requested before, but is not in scope. Closing.

See #3354
