### ISSUE TITLE
The Dark Theme cannot be displayed properly

### ISSUE THREAD

**Issue by xunmeng2002** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3567]
### Bug explanation

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/7625156/ae356165-19da-4b23-9e17-21a92192a984)

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/7625156/31a7e7d2-a776-4b1a-8644-ad563167df3e)

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/7625156/84add2b2-1be4-45f9-8af5-787bd93ebd25)

[WpfApp7.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/15373189/WpfApp7.zip)

### Version

5.0.0

**Comment by xunmeng2002** [comment]
TabControl: Headers for inactive Tab pages cannot be displayed
ListBox control: The contents of the child items of the control cannot be displayed

**Comment by Keboo** [comment]
Thank you for the nice reproduction project. In this case, the issue is that the Window is not properly themed which is why when switching to Dark theme, the background and foreground of the text both become while. If you add `Style="{StaticResource MaterialDesignWindow}"` to your MainWindow you will see the problem is fixed.

**Comment by xunmeng2002** [comment]
> Thank you for the nice reproduction project. In this case, the issue is that the Window is not properly themed which is why when switching to Dark theme, the background and foreground of the text both become while. If you add `Style="{StaticResource MaterialDesignWindow}"` to your MainWindow you will see the problem is fixed.

Thank you. This problem is solved.
