### ISSUE TITLE
WPF UI Freezes after resuming from lock screen when window contains a Slider

### ISSUE THREAD

**Issue by Talwynox** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3568]
### Bug explanation

I ran into same the problem as mentioned #559. The Problem only occurs when the second Window contains a Slider.
It looks like the CacheMode Binding fix from [7a7b8288607a6c3454c26db15e86ed5e50049423#diff-6f37d49b71e30496135fff458ed93d9e76ed9b0c931c244b6eccb1c2889e17e ](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/commit/7a7b8288607a6c3454c26db15e86ed5e50049423#diff-6f37d49b71e30496135fff458ed93d9e76ed9b0c931c244b6eccb1c2889e17e3) was not implemented for the Slider. 

### Version

5.0

**Comment by nicolaihenriksen** [comment]
@Talwynox Nice catch! There also seemed to be a forgotten update in the `RatingBar`, so I am updating that as well for consistency.
