### ISSUE TITLE
Disabled style of the TextBox and ComboBox are different

### ISSUE THREAD

**Issue by v2codes** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3571]
### Bug explanation

Disabled style of the TextBox and ComboBox box are different.
Set the IsEnable property to false, the underline of TextBox is dashed. But the ComboBox is solid.
Like this: 
### Screenshot
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/32858631/a71a798d-adb2-482c-b050-30bd1aeab64c)

### Code
``` 
<TextBox Width="180" Margin="40,0" materialDesign:HintAssist.Hint="disabled" IsEnabled="False" />
<ComboBox Width="180" materialDesign:HintAssist.Hint="please select" materialDesign:HintAssist.IsFloating="False" IsEnabled="False">
    <ComboBoxItem Content="Apple" IsSelected="True" />
</ComboBox>
```
### Framework Version
- .NET 8.0 
- WPF Application

### Version

5.0.0

**Comment by Keboo** [comment]
I am not able to replicate this with the latest nightly release. Are you able to provide a more complete solution?

From looking at it, it appears in your screenshot that the ComboBox would be the incorrect one with the solid line. The solid line should only be occurring when the ComboBox has the `MaterialDesignFilledComboBox` style. Is it possible, that your background color is the same, obscuring the difference that would normally be there with the filled style?

**Comment by v2codes** [comment]
I know why,  I using MaterialDesignThemes v5.0.0， MaterialDesignColors v3.0.0-ci633.  This causes the style to be different.
Upgrade MaterialDesignThemes to 5.0.1-ci633 is ok.

By the way , how can I set Textbox with solid line when it is  disabled?  
Thank's for your help.

**Comment by v2codes** [comment]
@Keboo  Thanks for your reply.
