### ISSUE TITLE
TreeListView: ArgumentOutOfRange expanding items via the data context

### ISSUE THREAD

**Issue by tenatus** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3572]
### Bug explanation

The TreeListView is a great replacement for WPF's TreeView but I discovered that there can be a serious issue (application crash) when expanding nodes programmatically (using a bound view model property).

I added this functionality to the demo application as an example of the issue: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/compare/master...tenatus:MaterialDesignInXamlToolkit:treelistbug

To reproduce:
1. Run the demo app
2. Select the Tree page
3. Click the new 'expand all items' button for the multi-select tree view
4. BUG: The application crashes (ArgumentOutOfRangeException)

### Version

5.0

**Comment by Keboo** [comment]
Thank you for the easy repro example. Put in a fix for it. It will be in the next nightly release.
