### ISSUE TITLE
Context menus are blurry

### ISSUE THREAD

**Issue by EsaHeinonen** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3601]
### Bug explanation

Context menus are rendered blurry. This becomes quite apparent when a ScaleTransform is applied to the context menu to enlarge the text:

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/32793333/339e599f-3d61-40e4-9b17-5b6b66ec5178)

Here's a repo to demonstrate the issue:
https://github.com/EsaHeinonen/MDIXTest1

### Version

5.0.1-ci662

**Comment by MichelMichels** [comment]
@EsaHeinonen  PR #3616 also fixes this issue. For the time being, you can manually force this by setting following on your `ContextMenu`:

```xaml
<ContextMenu materialDesign:ShadowAssist.CacheMode="{x:Null}" ... />
```
