### ISSUE TITLE
Transitions don't work when Loaded event is binded to command

### ISSUE THREAD

**Issue by osekj** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3602]
### Bug explanation

`
<i:EventTrigger EventName="Loaded">
    <i:InvokeCommandAction Command="{Binding LoadedCommand}" />
</i:EventTrigger>
`

When having `Loaded` event binded to ViewModel's command transitions are not fired. Removing the mentioned binding helps.

### Version

4.9

**Comment by MichelMichels** [comment]
Could you elaborate? Where is this code residing?

**Comment by osekj** [comment]
Sorry for the late response as my concept have changed and it was no longer needed, I have since finished upgrading to 5.0 and trying it once more everything works fine and animation can be seen.
