### ISSUE TITLE
MaterialDesignRaisedButton's Indicator is not  visible when button initial Visibility="Collapsed"

### ISSUE THREAD

**Issue by zhuzixian** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3604]
### Bug explanation

Button Visibility initial value is "Collapsed"，then changed to "Visible"，the Indicator is not visible. Modifying the following code can fix the bug
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/2361234/ff7b06f7-1751-4cd1-aefd-a0eaa50db98c)

` Width="{TemplateBinding Width}"`

### Version

5.0.0

**Comment by nicolaihenriksen** [comment]
@zhuzixian Can you elaborate a bit on the issue you're seeing? I cannot seem to reproduce it.

With the following XAML:
```xaml
<Button Content="Toggle Hide/Show Button Visibility"
        Click="ToggleVisibilityButton_OnClick" />
<Button x:Name="HiddenButton"
        Visibility="Collapsed"
        Content="Hidden Button"
        materialDesign:ButtonProgressAssist.Minimum="0"
        materialDesign:ButtonProgressAssist.Maximum="10"
        materialDesign:ButtonProgressAssist.Value="8"
        materialDesign:ButtonProgressAssist.IsIndicatorVisible="True" />
```

And this click handler in the code-behind:
```csharp
private void ToggleVisibilityButton_OnClick(object sender, RoutedEventArgs e)
    => HiddenButton.Visibility = HiddenButton.Visibility == Visibility.Collapsed ? Visibility.Visible : Visibility.Collapsed;
```

I get the following result which I believe is correct behavior?

![ButtonProgress](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/19572699/b0d8674f-a8e6-45c5-a628-798b600ea54a)

**Comment by zhuzixian** [comment]
This issue occurred in one of my projects，but I can't reproduce it through demo code，If analyzed from a code perspective is not a bug，please close this issue，I will report again when it reproduce.
