### ISSUE TITLE
Blurry `ToggleButton`

### ISSUE THREAD

**Issue by MichelMichels** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3612]
Following line makes the `ToggleButton` thumb blurry (the circle that switches side when toggling the button.

```xaml
<AdornerDecorator CacheMode="{Binding RelativeSource={RelativeSource Self}, Path=(wpf:ShadowAssist.CacheMode)}">
```
[Link to line in source code](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/8972991e16f3c5061ea7e003c6e236fc1bfc3267/src/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ToggleButton.xaml#L464)

This binding on `CacheMode` seems at first hand also completely unnecessary, as this value can't be set in any way: 
* The `AdornerDecorator` has no name
* The `AdornerDecorator` is inside the style template

The value will always be the default value of `ShadowAssist.CacheMode`, which seems to be following value `new BitmapCache { EnableClearType = true, SnapsToDevicePixels = true }`.

When I remove the `CacheMode` setting, the circle renders crisp and sharp.

|With `CacheMode` set|Without `CacheMode` set|
|---|---|
|![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/6505319/9401be9c-9939-4c02-b37e-610707ea9e5c)|![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/6505319/928e6f70-60a2-4e0a-b8e5-f1955d3cc6f4)|

**Comment by nicolaihenriksen** [comment]
@MichelMichels Probably related to changes for this and prior issue mentioned in there #3568.

The CacheMode can actually be set, because the attached property is inheritable and thus could be set/cleared on the ToggleButton which would affect the adorner.

Probably worth visiting to see if the recent changes from explicit CacheMode to the AP binding has other similar side-effects (other controls) we just haven't caught.

**Comment by MichelMichels** [comment]
ofcourse, I forgot about I heritable properties. I knew I missed something. What would be the most appropriate way to fix this?

**Comment by nicolaihenriksen** [comment]
@MichelMichels I am not really sure actually. I would like to hear @Keboo opinion on the matter...

**Comment by MichelMichels** [comment]
@nicolaihenriksen I made a test repository with the Nuget packages to check whether the `ShadowAssist.Cachemode` is inherited, and this does not seem to be the case. Did I do something wrong? https://github.com/MichelMichels/MDIXTestApp/tree/togglebutton-cachemode-bug

**Comment by MichelMichels** [comment]
@nicolaihenriksen, so I revisited my test app and added a case where I set `ShadowAssist.CacheMode` equal to `{x:Null}`. This seems to clear the blurryness, and indeed gets inherited!

![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/6505319/0d9b267d-6da0-4ccd-90b3-27337df1ae02)

**Comment by MichelMichels** [comment]
Also, when increasing the `RenderAtScale` from 1 to 3, the bluryness also dissappears while (I guess) still retaining the caching ability. Documentation found at https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.bitmapcache?view=windowsdesktop-8.0

**Comment by nicolaihenriksen** [comment]
@MichelMichels yes I just ran your sample app, and was confused why you did not think it was inheriting 😄 

I think the confusion perhaps comes from the fact that the attached property has a default value which makes things blurry 😢 Looking that the doc link you posted, perhaps the default value should be changed to something more appropriate where `RenderAtScale` is increased?

**Comment by MichelMichels** [comment]
@nicolaihenriksen yes, I think maybe a default setting of 2 or 3 should be better. The test was run on a monitor with resolution 1920x1200. Which seems to me a common resolution. Maybe we could try to write a test to measure the rendering time increase for these values? I must say I'm not that familiar with testing should cases.

**Comment by nicolaihenriksen** [comment]
@MichelMichels I must also admit that my knowledge of `BitmapCache` in general, and more so, testing of rendering performance in that regards, is not something I am familiar with either. I think your suggestion seems viable, perhaps make a PR with the change, point out in the description why you're making this change and that you think maybe some level of testing is needed. Perhaps @Keboo is more experienced in this area than us, and can provide some valuable input.

**Comment by MichelMichels** [comment]
Perfect, I'll submit a PR tonight (CET 1900 or later)

**Comment by MichelMichels** [comment]
@nicolaihenriksen `RenderAtScale` with higher value than 1 seems to create jagged edges for controls when they are small (like the default width of a ToggleButton). So in my PR I choose to remove the preset value altogether by setting it to `null`.
