### ISSUE TITLE
Multiple NumericUpDown controls not displaying correctly

### ISSUE THREAD

**Issue by corvinsz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3617]
### Bug explanation

When having multiple `NumericUpDown` controls on a page only the last control actually displays the content of the increase and decrease button correctly. 

I uploaded a project showcasing the bug: https://github.com/corvinsz/MDIXNumericUpDownBug

Here is my code:
```xaml
<Grid>
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <materialDesign:NumericUpDown />
        <materialDesign:NumericUpDown />
        <materialDesign:NumericUpDown />
    </StackPanel>
</Grid>
```

Result:
![image](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/assets/43533385/20d36e7c-3fc3-4c03-85bf-ea529d29f8de)

Am I perhaps doing something wrong?

### Version

5.1

**Comment by nicolaihenriksen** [comment]
This was fixed with this recent PR #3615
