### ISSUE TITLE
DataGridAssist.ColumnHeaderPadding may be applied twice

### ISSUE THREAD

**Issue by redcurry** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#362]
When I set DataGridAssist.ColumnHeaderPadding, the displayed padding is actually twice of what I set it to. I discovered this when I had a control with equal padding as the DataGrid cells that was outside of the DataGrid. The paddings didn't match unless I halved the paddings of the column headers. It was also obvious that the header paddings were too large for the values I gave it.

**Comment by redcurry** [comment]
Oops. It looks like only DataGridAssist.ColumnHeaderPadding is the problem, not CellPadding. I'll update the issue.

**Comment by TysonMN** [comment]
Can you provide link to a repository or attach a ZIP with executable code containing the behavior that you describe?

**Comment by redcurry** [comment]
Sorry, I'm no longer working on the project with the issue and I no longer have access to the code. You may close this issue if you want.

**Comment by Keboo** [comment]
Closing for now. If anyone comes across details for it, please comment.
