### ISSUE TITLE
ListView issue with ScrollViewer/ItemsPanelTemplate

### ISSUE THREAD

**Issue by imadenis** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3620]
### Bug explanation

Ticket  #3579 ( https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/3579 ) introduced a breaking behavior in my application. 

Having a ListView with a Style that targets the ItemsPanel, the ScrollViewer is not visible anymore at the bottom.

I have made a repo to demonstrate the bug:

https://github.com/imadenis/MaterialDesignBug 

I have pinpointed the issue to come from the <Style.Trigger> introduced at line 159
MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ScrollViewer.xaml

### Version

5.1.0

**Comment by nicolaihenriksen** [comment]
@JorisCleVR I am tagging you here because at first glance it seems this was introduced by the padding PR you submitted. Would you have time to look at the issue? If not, no worries, we'll get around to it eventually.

**Comment by JorisCleVR** [comment]
@nicolaihenriksen It seems that during my PR the IgnorePadding property of the ScrollViewerAssist accidently changed to false by default. I created a PR to fix this: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/3622
