### ISSUE TITLE
TabControl - please add something similar to TabablzControl HeaderPrefixContent or at least ability to set margin in ContentContol

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3633]
This is really all I was looking for, but done "properly" with some sort of Assist or a derivative of TabControl.

![image](https://github.com/user-attachments/assets/ff6e2677-7d81-4b8e-abda-c484fd8ef445)
![image](https://github.com/user-attachments/assets/56b01807-5a7c-4bc1-a01e-d1d7715391d6)

I have a set of tools fully dependent on MDInXAML library and currently rely on Dragablz `TabablzControl` to set margin like this:
```
`                        <dragablz:TabablzControl.HeaderPrefixContent>
                            <Grid Margin="130,0,0,0"/>
                        </dragablz:TabablzControl.HeaderPrefixContent>`
```

Unfortunately with 5.x release there were breaking changes to colors and even the demo app doesn't show the underline on the selected `TabablzControl` tab.
In any case, this feature (custom Margin in `HeaderPanel`) would be a nice addition natively instead of relying on Dragablz if this is all you are looking for.  I'm not looking to set an entire content... at least ability to set a custom Margin.

Thank you!

**Comment by nicolaihenriksen** [comment]
@bebenins That seems like a reasonable addition. I'll spin up a PR adding a `TabAssist.HeaderPanelMargin` attached property and see what the others maintainers say.

**Comment by bebenins** [comment]
Thank you for such a quick change!
