### ISSUE TITLE
MinHeight of SplitButton not working

### ISSUE THREAD

**Issue by corvinsz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3635]
### Bug explanation

When setting the `MinHeight` property of the `SplitButton` the property is not applied to the control.
I'm not sure if this is a bug or intended, but I couldn't think of a plausible reason for this not to work.

Here is my code:
```xaml
<Grid>
    <materialDesign:SplitButton MinHeight="500"
                                HorizontalAlignment="Center"
                                VerticalAlignment="Center"
                                Content="Split Button" />
</Grid>
```

Result:
![image](https://github.com/user-attachments/assets/8d8608b1-37be-40c7-96ca-048cb3c1fd40)

### Version

5.1

**Comment by nicolaihenriksen** [comment]
@corvinsz I think this is probably a side-effect of most of the default styles of MDIX having a hardocded `Height` property (to give it a reasonable default look).

If you simply opt-out of that default value, I think you should get what you want:

```xaml
<Grid>
    <materialDesign:SplitButton MinHeight="200"
                                Height="NaN"
                                HorizontalAlignment="Center"
                                VerticalAlignment="Center"
                                Content="Split Button" />
</Grid>
```

The above XAML produces this `SplitButton`:
![image](https://github.com/user-attachments/assets/8456f485-5857-4f30-a7f3-30ad445fec7a)

**Comment by corvinsz** [comment]
@nicolaihenriksen this is exactly what I want! I didn't know you could opt-out the default value like that.
Thank you for your help!
