### ISSUE TITLE
Hint does not being repositioned to the top left corner if the textbox has preconfigured text

### ISSUE THREAD

**Issue by bardur1234** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3636]
### Bug explanation

I upgraded recently to the latest version of Material Design and found out that hints in outlined textboxes are not moving up left side when the text is prepopulated (with Binding), when the presentation is showing. It works if there is no text and I am entering it.

I upgraded Material Design from version 4.9 to 5.1 and started experiencing the issue.

![image](https://github.com/user-attachments/assets/c26d6e47-e137-41d6-958b-2d5441b639be)

### Version

5.1

**Comment by nicolaihenriksen** [comment]
@bardur1234 I am unable to reproduce this issue (on the latest code at least). Can you share a bit of XAML so I can see if anything there could be causing this behavior.

With this XAML:
```xaml
<TextBox Style="{StaticResource MaterialDesignOutlinedTextBox}"
         materialDesign:HintAssist.Hint="My hint"
         Text="{Binding TextFromViewModel}" />
```
I get this result.
![image](https://github.com/user-attachments/assets/6231870c-c288-49a9-ac89-337d6fa24fdb)

I have tried: 1) setting a default value for `ViewModel.TextFromViewModel` having a default value, 2) setting a value set in the constructor, and 3) setting a value set after the `Loaded` event has fired in the UI. They all work as expected.

**Comment by bardur1234** [comment]
Hello Nicolai,

Thank you for your quick response.

In my case, I created a User Control TextBoxWithUndoButton, which is being used in many other User Controls. The "hint" text is set in those User Controls. The "text" value of the text box is also being delivered from the User Controls. I am attaching one of the User Controls that include the Text Box.

Hope you will be able to reproduce the issue with my files.

I downgraded to version 5.0 from 5.1 to check if the issue exists in that version and can confirm that with version 5.0 I didn't experience that issue.

Regards,
Vladislav
________________________________

**Comment by nicolaihenriksen** [comment]
> I downgraded to version 5.0 from 5.1 to check if the issue exists in that version and can confirm that with version 5.0 I didn't experience that issue.

So, version 5.1 did include a major refactoring of the `SmartHint`, especially regarding the placement of the hint. That could explain why you see the difference. But unfortunately I am still not able to reproduce it in any way shape or form.

The code you have pasted in the response above is taken quite a bit out of context, and is difficult for me to decipher anything from (it does not compile without other needed bits). I am however noticing your use of `async/await` in many places. I'll try a few other things down that path to see if I can reproduce the issue.

Simply wrapping the `TextBox` in a `UserControl` exposing a `DependencyProperty` for both the text and hint works fine for me.

A couple of things I noticed in your code:
* You're overriding `OnInitialized()`, and in there you're calling `InitializeComponent()`. Is there a particular reason for this? The typical approach would be to have a default constructor which invokes `InitializeComponent()`. Manually calling it after the control indicates that is HAS BEEN initialized, seems like a wrong order...
* Use of `async/await` is spread throughout the provided code, and some methods that return a `Task`, and have the `async` keyword in the method signature are not using the `await` keyword in the method body?! Does that code compile, as-is, on your side? Again, it seems to be taken out of context...

**Comment by nicolaihenriksen** [comment]
@bardur1234 You wouldn't happen to be setting `HintAssist.FloatingOffset` explicitly in your code would you? If so, the value set will take precedence and basically opt-out of the automatically calculated floating offset.

**Comment by bardur1234** [comment]
Hello Nicolai,

No, I am not using HintAssist.FloatingOffset.

Regards,
Vladislav
________________________________

**Comment by nicolaihenriksen** [comment]
@bardur1234 Would you be able to share some of your XAML, or possibly even a small demo repo with code that reproduces this? I am unable to reproduce it with the information given above.
