### ISSUE TITLE
产生Invalid HSB values异常后

### ISSUE THREAD

**Issue by ourplan9000** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3639]
### Bug explanation

发生错误后 ColorPicker无法再使用

### Version

4.8

**Comment by ElieTaillard** [comment]
Could you please provide a more detailed explanation of the bug? If possible, it would be very helpful if you could explain it in English and include any relevant screenshots. This will help us understand the issue better and assist you more effectively.
