### ISSUE TITLE
material Design TextBox Hint readablity while change Theme WPF C#

### ISSUE THREAD

**Issue by abbaslele** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3647]
I wanted to add two dark and light modes to my project using Material Design and the color palette section in the demo that I added to my project. The problem here is that some items such as the hint in the text boxes are black after changing the mode to dark and cannot be seen. Or, for example, the text of the combo boxes is not readable. Like the picture below:

![Screenshot 2024-08-13 163330](https://github.com/user-attachments/assets/4788bb84-6e17-4543-85c2-2da1497b917a)    ![Screenshot 2024-08-13 163343](https://github.com/user-attachments/assets/7ca38e5e-0d86-449d-933c-75c016eb8ab7)

Should I add another item to my `project?`

I saw the fields section in the program demo, but I didn't understand how these colors change. is as follows:

![Screenshot 2024-08-13 163534](https://github.com/user-attachments/assets/90a1f13a-f200-4507-9ac9-27dde5e8b9cf)    ![Screenshot 2024-08-13 163549](https://github.com/user-attachments/assets/0586e5ca-a810-4bdf-8d81-e4824d171eaa)

As it is clear in the above photo, the hint text box is not readable in dark mode

The code I wrote for this project is as follows:

```
<materialDesign:Card  UniformCornerRadius="16" Margin="8" materialDesign:ElevationAssist.Elevation="Dp12" Grid.Row="0" Grid.Column="1" FlowDirection="RightToLeft">
    <StackPanel Margin="8">
        <Label Content="میزان حساسیت" Margin="8"/>
        <Separator Margin="8"/>
        <ComboBox Margin="8" Style="{StaticResource MaterialDesignFilledComboBox}">
            <ComboBoxItem Content="ناحیه 1" IsSelected="True" />
            <ComboBoxItem Content="ناحیه 2"/>
            <ComboBoxItem Content="ناحیه 3"/>
            <ComboBoxItem Content="ناحیه4"/>
        </ComboBox>
        <TextBox
            MaxWidth="400" Margin="8" materialDesign:HintAssist.Hint="مقدار حساسیت" Style="{StaticResource MaterialDesignFilledTextBox}" />
    </StackPanel>
</materialDesign:Card>
```

I refrain from putting the codes of the color palette section due to the amount of text, but I have not made any changes to the values ​​or models of this section.
Thank you for your help

**Comment by nicolaihenriksen** [comment]
@abbaslele Can you elaborate a bit on how you toggle the theme in your app? Also, which version of MDIX are you consuming?

When I toggle the theme in the demo app, there does not seem to be any issues:
![ThemeChange](https://github.com/user-attachments/assets/74f6eee1-7091-466d-aa40-3a3f2b25cf9d)

**Comment by abbaslele** [comment]
Hello @nicolaihenriksen .
I Used MDIX Version 5.0.0.
I used the palette controller in the app demo and didn't change it.
I will put the list of classes and models that I have taken from the main program solution here:

- ThemeSettingsViewModel.cs

- ThemeSettings.xaml

- PaletteSelectorViewModel.cs

- PaletteSelector.xaml

- Palette.xaml

Of course, I did not make any changes in these files and codes and added them to my project.
As you said, this problem does not exist in the demo program of your project, and the readability of the text is easily maintained in the dark Theme, but it is not like this in my project, and I cannot see the text inside these items.
If you need more clarifications, please let me know and I will send them to you.

**Comment by nicolaihenriksen** [comment]
@abbaslele Ok that is fine. Can you give an example of the code you execute when you toggle the theme? I assume you have a button with either an `EventHandler` or a bound `ICommand` which then "does something". That is what I am interested in, because it seems some elements respect the change but not all which is weird. I am also noticing the "non-western" characters, so could you specify which `CultureInfo` you're running under?

**Comment by abbaslele** [comment]
The code used to change the theme must be the same as the example of the demo program itself, and what is related to changing the theme is as follows:
**ThemeSettings.xaml**
```
<ToggleButton Margin="8,0,16,0" IsChecked="{Binding IsDarkTheme}" />
```

**ThemeSettings.xaml.cs**
```
public partial class ThemeSettings : UserControl
    {
        public ThemeSettings()
        {
            DataContext = new ThemeSettingsViewModel();
            InitializeComponent();
        }
    }
```


**ThemeSettingsViewModel.cs**
```
        private  bool _isDarkTheme;
        public  bool IsDarkTheme
        {
            get => _isDarkTheme;
            set
            {
                if (SetProperty(ref _isDarkTheme, value))
                {
                    ModifyTheme(theme => theme.SetBaseTheme(value ? BaseTheme.Dark : BaseTheme.Light));
                }
            }
        }


        private static void ModifyTheme(Action<Theme> modificationAction)
        {
            var paletteHelper = new PaletteHelper();
            Theme theme = paletteHelper.GetTheme();

            modificationAction?.Invoke(theme);

            paletteHelper.SetTheme(theme);
        }

```
Of course, let me remind that all these codes and classes are from the main directory of the program.

In the demo program, I saw that they did not use style or any other item to change the theme, and I thought that the theme change happens automatically for the elements that use the material library.

And for your second question, I have to say yes, I used Persian culture as follows in my program:

**App.xaml.cs**
```
public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            CultureInfo cultureInfo = new CultureInfo("fa-IR");
            CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
            CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
            Thread.CurrentThread.CurrentCulture = cultureInfo;
            Thread.CurrentThread.CurrentUICulture = cultureInfo;
        }
    }
```

**Comment by abbaslele** [comment]
After searching for an answer and not getting a result about the problem in this case, I was able to fix the problem manually with the following solution and I came to a conclusion by using the binding and the library itself.
The solution ahead is the correct answer to the question.
I first created an object model using a global model from the `ThemeSettingsViewModel.cs` (The setting view model theme is the same as the Material Design library and no changes have been made to it) like this:
```
public class GlobalSettingModel
{
        public GlobalSettingModel()
        {
        }

        private ThemeSettingsViewModel tsvm;
        public ThemeSettingsViewModel mTSVM
        {
            get { return tsvm; }
            set { tsvm = value; }
        }

        private static GlobalSettingModel mInstance;
        public static GlobalSettingModel getInstance()
        {
            if (mInstance == null)
            {
                mInstance = new GlobalSettingModel();
            }
            return mInstance;
        }
}
```
Then I wrote the following code in the desired class and implemented a converter to connect the theme to the color:

```
//Connect Data Context to Controls
    public partial class ChartPageView : Page
    {
        
        public ChartPageView()
        {
            InitializeComponent();
            ...
            uZoneName_ComboBox.DataContext = GlobalSettingModel.getInstance().mTSVM;
            uThresholdValue_Text.DataContext = GlobalSettingModel.getInstance().mTSVM;
        }
    }

//Converter Implementation
    public class ForegroundConverterForIcons : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            if (value != null)
            {
                if ((bool)value)
                {
                    return (Brush)Brushes.White;
                }
                else
                {
                    return (Brush)Brushes.Black;
                }
            }
            else
            {
                return (Brush)Brushes.Black;
            }
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return DependencyProperty.UnsetValue;
        }

    }

```

Now we can do the following binding in our Xaml file:
```
//Using resources in the Page
<Page.Resources>
        <ResourceDictionary>
            <local:ForegroundConverterForIcons x:Key="ForegroundConverterForIcons" />
        </ResourceDictionary>
    </Page.Resources>
//using binding in Controls
<ComboBox Margin="8" Style="{StaticResource MaterialDesignFilledComboBox}" Name="uZoneName_ComboBox" Foreground="{Binding IsDarkTheme , Converter={StaticResource ForegroundConverterForIcons}}">
                            <ComboBoxItem Content="ناحیه 1" IsSelected="True" />
                            <ComboBoxItem Content="ناحیه 2"/>
                            <ComboBoxItem Content="ناحیه 3"/>
                            <ComboBoxItem Content="ناحیه4"/>
                        </ComboBox>
                        
                        <TextBox
                            MaxWidth="400" Margin="8" Name="uThresholdValue_Text" Foreground="{Binding IsDarkTheme , Converter={StaticResource ForegroundConverterForIcons}}"
                            materialDesign:HintAssist.Hint="مقدار حساسیت"                            
                            Style="{StaticResource MaterialDesignFilledTextBox}" />
```
After performing the following steps, we can use the text box and other controls in a readable manner so that all items change color after changing the theme color.
The display of the controls after changing the color is as follows:

![Light Theme Display][1]  ![Dark Theme Display][2]


  [1]: https://i.sstatic.net/ArxTHA8J.png
  [2]: https://i.sstatic.net/26qVwwuM.png
