### ISSUE TITLE
IndexOutOfRangeException in VS 2022 17.12.0 Preview 1.0 with .Net8

### ISSUE THREAD

**Issue by SpaceTimee** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3649]
### Bug explanation

After I upgraded Visual Studio 2022 to 17.12.0 Preview 1.0, my WPF .Net8 project throws an exception when running to `InitializeComponent();` in the constructor of MainWindow. (No problems before the upgrade)

The debug output:
> Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll

The details of the exception:
> System.Windows.Markup.XamlParseException
>   HResult=0x80131501
>   Message=“设置属性“System.Windows.FrameworkElement.Style”时引发了异常。”，行号为“11”，行位置为“60”。
>   Source=PresentationFramework
>   StackTrace:
>    at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
>    at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
>    at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
>    at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
>    at Sheas_Cealer.Wins.MainWin.InitializeComponent() in E:\Git-Repository\Sheas-Cealer\Wins\MainWin.xaml:line 1
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> IndexOutOfRangeException: Index was outside the bounds of the array.

I tried every possible code change but nothing worked until I commented out the code for overriding default Material Design styles in the App.xaml, more specifically the Setters in there:
```xaml
<Style x:Key="CommonWindow" TargetType="{x:Type Window}">
    <!--<Setter Property="Background" Value="{DynamicResource MaterialDesignBackground}" />
    <Setter Property="Foreground" Value="{DynamicResource MaterialDesignBody}" />-->
</Style>

<Style BasedOn="{StaticResource MaterialDesignRaisedButton}" TargetType="{x:Type Button}">
    <!--<Setter Property="Height" Value="Auto" />
    <Setter Property="Width" Value="Auto" />-->
</Style>
```

Also I found that setting the framework to .Net9 solved the exception as well.

I tried MaterialDesignThemes 5.0.0, 5.1.0 and the latest prerealease and the test results above remain unchanged.

Other env info:
> Win11 x64
> Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview - Version 17.12.0 Preview 1.0
> 0 Errors, 0 Warnings, 0 Messages

### Version

5.1.0

**Comment by corvinsz** [comment]
@SpaceTimee I am **unable** to reproduce this bug under the following circumstances:
- .NET 8 WPF Project
- MDIX 5.1.0
- Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.12.0 Preview 1.0
- Applying the default styles you provided in the `App.xaml`
- Win11

Is it possible you provide or double check the code in your `MainWindow`? Unless I have missed something obvious here, I doubt it is a problem with the library itself.

**Comment by SpaceTimee** [comment]
It was probably caused by the lack of .Net 8 SDK.
I solved the problem by installing a .Net 8 SDK. The VS Installer seemed to automatically replace my .Net 8 SDK with the .Net 9.0.100-preview.7.24407.12 SDK during the upgrade.
