### ISSUE TITLE
Under TextBox MaterialDesignFilledTextBox style TextFieldAssist.DecorationVisibility hide underline, disable the control shows underline

### ISSUE THREAD

**Issue by KashimuraBaka** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3672]
### Bug explanation

```
<TextBox
    Width="140"
    Height="36"
    Padding="6,2"
    HorizontalAlignment="Center"
    materialDesign:TextFieldAssist.DecorationVisibility="Collapsed"
    materialDesign:TextFieldAssist.TextFieldCornerRadius="4"
    FontSize="12"
    Foreground="{DynamicResource MaterialDesign.Brush.Foreground}"
    IsEnabled="True"
    Style="{StaticResource MaterialDesignFilledTextBox}"
    Text="TextBox Message" />
```

|  IsEnabled = true  | IsEnabled = false |
|  ----  | ----  |
| ![image](https://github.com/user-attachments/assets/a611d493-7662-48c3-9e51-36fee5e8e395) | ![image](https://github.com/user-attachments/assets/9fdaee56-39c1-4dd8-8bfa-206db36d4fef) |

in the end, the only way to hide the underline style is to set the TextFieldAssist.HasOutlinedTextField = True property.
but Hint text styles are affected.
![image](https://github.com/user-attachments/assets/450da7a9-3e6c-4ef3-8945-3db014b346ee)

### Version

5.1.0

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen Sorry, i may not have explained it well enough.
I just want to hide the underline completely, which works fine in normal situations.
But when the textbox is disabled, the hide underline property doesn't work.

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka So when you say you want it completely removed and "which works fine in normal situations". How are you able to hide it completely (when not disabled)? I mean the control basically has 2 "underlines" for the `MaterialDesignFloatingHintTextBox` and `MaterialDesignFilledTextBox` styles: a "fixed one" and "an animated one". How are you currently removing the "fixed one"? I don't see it removed in any of the screenshots you have posted.

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen Current TextBox contains two types of underlines, `Border` and `OutLine `style underlines. 
The current problem is hiding the outline underline.
If you look closely, you'll see another bold underline below the disabled component.
and the problem is even more pronounced when you set the textbox radius.

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen Yes, I am now troubled with setting the animation style underline.
Setting hidden and radius styles will not be affected

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka I still don't quite understand exactly what you mean 😞

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen Emm, i suddenly at a loss for words.
Is to set the `TextFieldAssist.DecorationVisibility="Collapsed"` property to hide the animated underline. 
![image](https://github.com/user-attachments/assets/249de81c-49c7-45d2-859d-8ea0438b8de9)
But after setting `IsEnabled = false`, `TextFieldAssist.DecorationVisibility="Collapsed"` doesn't work at all.

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka As I mentioned above, the `TextFieldAssist.DecorationVisibility` **only** operates on the animated underline!

In case you want to hide the non-animated underline, you should set `TextBox.BorderThickness=0` as the control respects this property. See https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/212#issuecomment-171991848

The rounded corners are not "respected" on the bottom corners because that is not how the Material Design spec uses rounding; they only apply to the top-left and top-right corners in the spec. See https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/1790#issuecomment-623056150

So I really don't see an issue, if you still see one, you will need to elaborate further.

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen My current requirement is to set the border only, without animating the underline. 
I have set the textbox property to hide the animated underline. 
But after disabling the control the animated underline is shown directly.
As shown in the image above, the red box shows the animated underline.

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka The image you should above is NOT the animated underline! That is the default `TextBox.BorderThickness` that kicks in.

If I understand you correctly, you want the underline when enabled, but NOT when disabled? In that case you should probably amend your style with a trigger that sets `TextBox.BorderBrush=Transparent` when `IsEnabled=False`. You can also modify the `TextBox.BorderThickness`, but that will cause your control to have a slightly different height when toggling between enabled/disabled.

This is a disabled `TextBox` with `TextBox.BorderBrush=Transparent`:
![image](https://github.com/user-attachments/assets/934a0e63-d473-4bc0-bb24-3f6b719654e4)
![image](https://github.com/user-attachments/assets/8bbc9776-219f-4bb5-ae70-063e155cc159)

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen You can try the following code to visualize the problem.
```
<DockPanel HorizontalAlignment="Center">
    <TextBox
        Width="140"
        Height="36"
        Padding="6,2"
        HorizontalAlignment="Center"
        materialDesign:TextFieldAssist.DecorationVisibility="Collapsed"
        materialDesign:TextFieldAssist.TextFieldCornerRadius="10"
        FontSize="12"
        Foreground="{DynamicResource MaterialDesign.Brush.Foreground}"
        IsEnabled="True"
        Style="{StaticResource MaterialDesignFilledTextBox}"
        Text="a" />
    <TextBox
        Width="140"
        Height="36"
        Margin="5,0,0,0"
        Padding="6,2"
        HorizontalAlignment="Center"
        materialDesign:TextFieldAssist.DecorationVisibility="Collapsed"
        materialDesign:TextFieldAssist.TextFieldCornerRadius="10"
        FontSize="12"
        Foreground="{DynamicResource MaterialDesign.Brush.Foreground}"
        IsEnabled="False"
        Style="{StaticResource MaterialDesignFilledTextBox}"
        Text="b" />
</DockPanel>
```

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen But I want to hide the animated underline completely, instead of setting the rounded corners property.
Setting the rounded corners is so that you can see that the animated underline is not hidden.

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka Let's ignore the rounded corners.

I don't think I can explain it in more detail than this:
There are 2 underlines!
* A non-animated underline which is controlled exclusively by `TextBox.BorderThickness` and `TextBox.BorderBrush`. This has NOTHING to do with the `TextFieldAssist.DecorationVisibility`
* An animated underline which is controlled exclusively by the `TextFieldAssist.DecorationVisibility` attached property.

When `IsEnabled=False` the animated underline is no longer in use (because this only operates on got/lost focus).

The `TextFieldAssist.DecorationVisibility` I believe was added explicitly to avoid having  the animated underline in cases where the `TextBox` resides in places where it is undesirable to have the animation. See the links in my comments above as they touch on this topic.

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen I've read that,  Mr. Keboo only states that the bottom square is the spec.
But he didn't explicitly state that IsEnabled = false to show animated underlines is also the spec.
This property is set to hidden, and should be hidden when disabled.

**Comment by nicolaihenriksen** [comment]
@KashimuraBaka This is the image you posted:
![371380232-249de81c-49c7-45d2-859d-8ea0438b8de9](https://github.com/user-attachments/assets/6b74d182-a639-4f65-8189-200f7eb8b3b7)

The underline marked in the red there IS NOT the animated underline!! It is the normal `TextBox.BorderThickness` and `TextBox.BorderBrush` the affects the line shown there!

Look at this XAML where I simply change the style to change the `TextBox.BorderBrush` to `Transparent` when `TextBox.IsEnabled=False` as I mentioned in my comment above:
```xaml
<StackPanel>
  <StackPanel.Resources>
    <Style x:Key="MyCustomMaterialDesignFilledTextBox" TargetType="TextBox" BasedOn="{StaticResource MaterialDesignFilledTextBox}">
      <Style.Triggers>
        <Trigger Property="IsEnabled" Value="False">
          <Setter Property="BorderBrush" Value="Transparent" />
        </Trigger>
      </Style.Triggers>
    </Style>
  </StackPanel.Resources>
  <CheckBox x:Name="MyCheckbox" IsChecked="True" Content="TextBox.IsEnabled" Margin="0,0,0,10" />
  <TextBox
    Width="140"
    HorizontalAlignment="Center"
    materialDesign:TextFieldAssist.DecorationVisibility="Collapsed"
    Foreground="{DynamicResource MaterialDesign.Brush.Foreground}"
    IsEnabled="{Binding ElementName=MyCheckbox, Path=IsChecked}"
    Style="{StaticResource MyCustomMaterialDesignFilledTextBox}"
    Text="Hello World"/>
</StackPanel>
```
When toggling enabled state, the underline disappears as I suspect is what you want.
![StyleTrigger](https://github.com/user-attachments/assets/a5774135-7055-4753-84a7-f65dcd4133a5)

**Comment by KashimuraBaka** [comment]
@nicolaihenriksen Yes, it also made me realize what was causing the style to display incorrectly.
Thanks for the reply.
