### ISSUE TITLE
Style problems with version 5.1.0

### ISSUE THREAD

**Issue by FrancescaPlz** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3673]
### Bug explanation

Hello everyone, I updated Material to the new version 5.1.0 and it removed most all of automatic styles that I had before. For example for the buttons (styles like MaterialDesignRaisedButton don't work) and other elements. What can I do? Also when I tried to add new elements, they appear without styles. Is there something that can I do for fix the situation?

### Version

5.1.0

**Comment by corvinsz** [comment]
@FrancescaPlz I'm guessing you are upgrading from an older version (pre 5.0)? If so, make sure to check the [5.0.0 Migration Guide](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/discussions/3466).

Most likely you'll just have to change your app.xaml to use the new defaults dictionary:

```xaml
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesign2.Defaults.xaml" />
```

**Comment by FrancescaPlz** [comment]
Thank you, I resolved the problem
