### ISSUE TITLE
The Menu has no border

### ISSUE THREAD

**Issue by omllmo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3676]
### Bug explanation

![1](https://github.com/user-attachments/assets/75f38963-dbc7-4883-aeec-5931b3d289bd)
![2](https://github.com/user-attachments/assets/49e87001-3a70-4508-b7a1-86a955912631)

### Version

5.1

**Comment by corvinsz** [comment]
@omllmo are you sure you are using the correct version of the library (NuGet package/Release version)?

I am unable to reproduce your problem:
![image](https://github.com/user-attachments/assets/1edb0486-c66c-408e-ba36-e165260c8f5f)

Did you apply any styles to your `MenuItem`?

**Comment by omllmo** [comment]
On another computer it works without any problems. So it's something else. The issue is resolved. Thank you.
