### ISSUE TITLE
ListBox SelectionChanged is not triggered anymore (used to work in at least 4.x release)

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3677]
### Bug explanation

Not sure when this changed but I just noticed this after switching the last project we have to 5.x release.
Basically I have a ListBox with a single item and I'm trying to emulate a CheckBox behavior.  Nothing crazy here... this is a common suggestion on how to achieve this.

This is my code (I also attached it as a project).
This still works with 4.7.1 release but not with the latest release.
Event gets triggered at init time but after that - silence.

[MD_5.0_ListBoxButtonTest.zip](https://github.com/user-attachments/files/17099344/MD_5.0_ListBoxButtonTest.zip)

```
<ListBox SelectedIndex="{Binding SelectedHalSensorUpdateToggleIndex}" SelectionChanged="ButtonToggleHalSensorUpdate_SelectionChanged">
    <ListBoxItem ToolTip="Periodic sensor update">
        <materialDesign:PackIcon Kind="Repeat"/>
    </ListBoxItem>
</ListBox>
```

---

```
    public partial class MainWindow : Window, INotifyPropertyChanged
    {
        private int _selectedHalSensorUpdateToggleIndex;
        public int SelectedHalSensorUpdateToggleIndex
        {
            get => _selectedHalSensorUpdateToggleIndex;
            set { _selectedHalSensorUpdateToggleIndex = value; OnPropertyChanged(); }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public MainWindow()
        {
            DataContext = this;
            InitializeComponent();
        }

        private void ButtonToggleHalSensorUpdate_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            bool great = true;
        }
    }
```

### Version

5.1.1-ci753

**Comment by corvinsz** [comment]
@bebenins can you double check if the `ListBox` behaves correctly on the 4.7.1 version?
I'm pretty sure the default WPF `ListBox` does not throw the `SelectionChanged` event when clicking on an already selected `ListBoxItem`.

Also (maybe I'm just lacking context, but) it seems to me that a `ListBox` with a single item is not the correct tool for this job. Have you considered using a `ToggleButton` or `CheckBox` with a Style/Template if a certain look is desired?

**Comment by bebenins** [comment]
Update - this looks to be a new behavior in the latest .NET release.  I guess it makes sense not to trigger SelectionChanged if there' only one item in the list.
I agree that it's an ugly solution but I need a `CheckBox` in my `ToolBar` that looks consistent with other buttons.  I guess I can make this a feature request.
Thank you

**Comment by bebenins** [comment]
This is a new .NET WPF behavior... need a workaround but in any case, this is not a MD bug.

**Comment by corvinsz** [comment]
> I need a `CheckBox` in my `ToolBar` that looks consistent with other buttons.

As I mentioned you might want to look into either "Styles" or defining a custom `Template` for most likely `CheckBoxes`.
In my opinion Styles are easier to start with if you are a "beginner", however I only see the `Button` as a possible solution for this if you want to exclusively use Styles.
With custom Templates on the other hand you can use a `CheckBox` and make it look however you want.

**Comment by bebenins** [comment]
Need new control instead as a better solution
