### ISSUE TITLE
Binding PackIconKind to Badged Badge does not work (displays icon enum instead)

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3686]
### Bug explanation

This is what it looks like on GUI:
![image](https://github.com/user-attachments/assets/65554374-c6a1-48ed-855f-ea8e94fc7491)

```
        private PackIconKind _localIpAddressBadge = PackIconKind.AboutCircle;
        public PackIconKind LocalIpAddressBadge
        {
            get { return _localIpAddressBadge; }
            set { _localIpAddressBadge = value; OnPropertyChanged(); }
        }
```

```
<md:Badged Badge="{Binding LocalIpAddressBadge}">
    <Button>
        <md:PackIcon Kind="Ip"/>
    </Button>
</md:Badged>
```

When you assign PackIconKind directly in XAML as in demo - all good.

### Version

5.1.1-ci753

**Comment by nicolaihenriksen** [comment]
@bebenins There isn't an issue here. The `Badged.Badge` property is simply displayed in a `ContentControl` so if you supply an enumeration, it will simply display a string. If you supply a visual element, that will be displayed "as is".

I think what you're aiming for is probably something along these lines where you place a `PackIcon` (visual element) in the `Badged.Badge` property, and then making the binding to your enumeration in there instead.

```xaml
<materialDesign:Badged>
  <materialDesign:Badged.Badge>
    <materialDesign:PackIcon Kind="{Binding LocalIpAddressBadge}" />
  </materialDesign:Badged.Badge>
  <Button>
    <materialDesign:PackIcon Kind="Ip"/>
  </Button>
</materialDesign:Badged>
```
