### ISSUE TITLE
Calendar displays incomplete information.

### ISSUE THREAD

**Issue by aqingGitHub** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3688]
### Bug explanation

As shown in the following figure, the Calendar displays incomplete information. And I hope to maintain consistency with the PC system language. How can I implement it?  Thanks!
![image](https://github.com/user-attachments/assets/9e93b999-2d27-4ee9-9501-d9d61baa9c65)

### Version

5.1.0

**Comment by aqingGitHub** [comment]
Sorry, the font size is too large due to the global setting of relevant styles in App.xaml

But how should I set it to be consistent with the PC system language.

**Comment by corvinsz** [comment]
@aqingGitHub as you evaluated correctly, this is a "bug" because you have set a global style for `TextBlocks` in which you apply a larger (than normal) font size.


You also mention the "PC system language":
> But how should I set it to be consistent with the PC system language.

I am confused what the systems language have to do with the font size of your app (?).
