### ISSUE TITLE
Different background for hint in TextBox and ComboBox

### ISSUE THREAD

**Issue by omllmo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#3710]
### Bug explanation

The background of the hint is different from the background of the element on which the ComboBox or TextBox element is placed.
![Hint](https://github.com/user-attachments/assets/c2405df1-30e5-4a8d-805a-0b2399569b0c)

### Version

5.1.1-ci795

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
