### ISSUE TITLE
Xamarin Forms support

### ISSUE THREAD

**Issue by eventgenius** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#381]
Hi, Great work!! Do you plan on bringing this magic to Xamarin Forms?

**Comment by ButchersBoy** [comment]
Uhm...when I can retire from the day job and focus all my efforts on UWP and Xamarin...

**Comment by quicoli** [comment]
James, I would like to help you on this :)
Em 27/05/2016 09:38, "James Willock" <notifications@github.com> escreveu:

**Comment by EndlessDelirium** [comment]
This would be great. XF 3.6 comes with Visuals (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/) and there already is a nuget package that provides material design visuals for iOS and Android - but not UWP (https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/)

**Comment by Keboo** [comment]
Xamarin.Forms is not supported by this library. Given that [Xamarin.Forms supports material design](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual#:~:text=Xamarin.Forms%20Material%20Visual%201%20Initialize%20Material%20Visual.%20After,Material%20Visual.%20...%203%20Customize%20Material%20Visual.%20) through their Visual API this library is not planning support for it.
