### ISSUE TITLE
At design time, when IsOpen="true", the DialogHost content stay over all windows

### ISSUE THREAD

**Issue by rogamaral** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#384]
The DialogHost content stay over all windows:

![Image1](https://github.com/rogamaral/DialogHostTest/blob/master/DialogHostTest/DesignIssue.png)

and sometimes misplaced:

![Image2](https://github.com/rogamaral/DialogHostTest/blob/master/DialogHostTest/DesignIssue_1.png)

This [project](https://github.com/rogamaral/DialogHostTest/tree/master/DialogHostTest) reproduces the issue.

**Comment by Keboo** [comment]
Unfortunately this is a designer issue that is not easily addressed within this library.
