### ISSUE TITLE
DatePicker Selected foreground invisible

### ISSUE THREAD

**Issue by aguingand** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#385]
Hello,
![alt](http://i.imgur.com/Yon5H6r.jpg)

Here is the sample repo 
https://github.com/aguingand/PickerIssue

**Comment by hedata** [comment]
+1 Same Problem

**Comment by Leojet86** [comment]
+1 it's 2018 and same problem, any idea?

**Comment by Keboo** [comment]
This appears to be fixed in the latest 4.2.1 release
