### ISSUE TITLE
Package needs to be compatible with .Net Framework 4.6

### ISSUE THREAD

**Issue by McDoubleNoPicle** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#391]
package installation failed when tried on a project with framework 4.6 and needs to be compatible.

**Comment by beto-rodriguez** [comment]
There.shoumd be a version for 4.6 I will see what is going on here I am sure I compiled it for 4.6 too

**Comment by McDoubleNoPicle** [comment]
Hi Alberto,

Yeah it was keep failing on me on 4.6 using VS 2015. I had to revert my
Project to 4.5 and then it worked.

Thanks.

**Comment by amoamare** [comment]
This does work with 4.6 and 4.6.1 on VS 2015 Professional. 

I have three projects using latest nuget package on 4.6 and 4.6.1

**Comment by ButchersBoy** [comment]
@McDoubleNoPicle how did you try installing the package? Nuget Console?  GUI?

**Comment by McDoubleNoPicle** [comment]
Thanks for checking in. I was also using latest Nuget package but project
had 4.6 error using VS 2015.

Could it be due to VS 2015 community edition that I am using. ? I highly
doubt it.

Thanks.

**Comment by Insire** [comment]
using:
Nuget: Install-Package MaterialDesignThemes -Pre
Visual Studio 2015 Community Edition Update 2

new project
- .Net 4.6 => compiles
- .Net 4.6.1 => compiles too

**Comment by McDoubleNoPicle** [comment]
Thanks for confirming it. I am not sure what could have gone wrong on my
end.

**Comment by dgadelha** [comment]
It's because when you change the framework you need to update/[reinstall](https://docs.nuget.org/consume/reinstalling-packages) your NuGet packages, so NuGet downloads the latest DLL compliant with your target framework.

**Comment by Keboo** [comment]
Appears to be fixed
