### ISSUE TITLE
Problem with handling primary toggle button action in PopupBox

### ISSUE THREAD

**Issue by DominikPalo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#411]
I'm using the PopupBox component in my app, but I need to attach a command also on primary toggle button, which by default closes a popup. My expected behaviour is: When I place mouse over a `PART_Toggle`, popup is opened, but clicking on this button instead of closing popup executes my command. So, I copied the `MaterialDesignMultiFloatingActionPopupBox` style to my project and changed the line:

```
<ToggleButton x:Name="PART_Toggle" Style="{StaticResource ToggleButtonStyle}" 
 IsChecked="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=IsPopupOpen, Mode=TwoWay}"...
```

to

```
<ToggleButton x:Name="PART_Toggle" Style="{StaticResource ToggleButtonStyle}"
 Command="{Binding MyPrimaryCommand}"... 
```

but now, `MyPrimaryCommand` is executed only on second click on the ToggleButton and first click still closes the popup. It is possible to handle also first click without making changes in the `PopupBox` class?

**Comment by Keboo** [comment]
I realize this is quite old but wanted to give an answer. This is best accomplished by using your own Button (not a toggle button), and implementing the hover to open your own Popup. The PopupBox control is not a good fit for that behavior.
