### ISSUE TITLE
PopupEx makes dialoghost windows pop up on top of other applications

### ISSUE THREAD

**Issue by mrfrostfire** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#413]
When using DialogHost it should be placed on top of everything inside the ownerwindow, but not outside the ownerwindow. But since PopupEx is set to use TopMost instead of NoTopMost, it will make the pop up on top of other applications. This is handled with the window deactivated call, where it sets it to NoTopMost. But if the dialog is opened when the ownerwindow is not the active window, the dialog will instead popup as TopMost over other applications.

This should be able to get fixed by setting the initial state to TopMost/NoTopMost based on the current state of the window instead of always setting it to TopMost as default.

**Comment by rgonzalezVW** [comment]
Also, when using DialogHost and debugging, the dialog remains on top of VisualStudio, making it really anoying. 
The TopMost state should be removed, or at least, make it optional, please!

**Comment by FINDarkside** [comment]
Any solution to this?

**Comment by Keboo** [comment]
There are a couple things here. First `PopupEx` is coming from [another repository](https://github.com/ControlzEx/ControlzEx) so any changes to it would have to start there. There is an [alternate DialogHost template](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/760) that is scheduled to be released as part of the 2.5.0 release that will place the dialog as part of the visual tree _within_ the window.

**Comment by JamesCoyle** [comment]
Is there an ETA on this update?
