### ISSUE TITLE
DrawerHost's overlay doesn't affect on ValidationError 

### ISSUE THREAD

**Issue by l1pton17** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#419]
![image](https://cloud.githubusercontent.com/assets/5460448/16136572/73cd6860-3434-11e6-8cce-7831d0dd6eaf.png)

**Comment by Keboo** [comment]
This is fixed in the 4.2.1 release. However, it will not overlap if `ValidationAssist.UsePopup="True"` is set. This is by design.
