### ISSUE TITLE
Menu in LeftDrawerContent

### ISSUE THREAD

**Issue by leovictor** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#422]
Hi,
how can I put a menu with submenus in a LeftDrawerContent? Is it possible?

**Comment by Keboo** [comment]
@leovictor take a look [at this example](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/Menu/Menu.HorizonalDisplay) let me know if this is not what you are describing.
