### ISSUE TITLE
Circular ProgressBar : Disable extra rotation

### ISSUE THREAD

**Issue by ceparth** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#431]
There should be an option to disable the extra rotation in circular progressbar which causes it to spinning instead of steady the starting point.

**Comment by DeleteIT** [comment]
If you mean on a deterministic bar, you can make that the case with an edit to `\MaterialDesignThemes.Wpf\Converters\CircularProgressBar\RotateTransformConverter.cs`.
Returning Binding.DoNothing will keep the progress bar from rotating, but the transition from indeterminate looks awful.

**Comment by Keboo** [comment]
This is now controlled by the attached properties `ButtonProgressAssist.IsIndicatorVisible="True"` and `materialDesign:ButtonProgressAssist.Value="50"`
