### ISSUE TITLE
PopupBox background color

### ISSUE THREAD

**Issue by gpasnik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#432]
Hi, I'm using dark theme of the MaterialDesignInXamlToolkit and the background color of PopupBox is the same as the background of the Window (it uses the MaterialDesignPaper brush). 
On Light theme it was nice, because there were shadows around the popup and it was easy to distinguish popup from the rest of content, on dark theme is sometimes confusing.
Is there any easy way to change the background of popupbox? I've tried to set "Background" property but it was not that.

For a temporary workaround I've just overrided the MaterialDesignPaper brush in the scope of grid which contains this popup.

```
<Grid.Resources>
    <SolidColorBrush x:Key="MaterialDesignPaper" Color="#FF647076" />
</Grid.Resources>
```

But as I said it is temporary solution and I'm looking for a correct way how to change it.

**Comment by mgnslndh** [comment]
It seems to me that the Background property is not really used and probably could be bound to the card background to achieve what you want. Works for me when I tried it.

But then I thought you could just wrap your content in a border or slap a color on the background of your content. But it seems like there is a default padding on the top and bottom of the popup card. Changing this would probably be a breaking change.

I'll let @ButchersBoy have his say on this before submitting any PR.

**Comment by Keboo** [comment]
In the 4.2.1 release the PopupBox background should follow the appropriate theme color
