### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by sagevpremium** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#437]
Hi, can you tell me step by step how to use dialogs in Code-behind?

Btw. thx so much for the new version of md, where hint size is finally like font size :)

**Comment by coder2000** [comment]
Or in a ViewModel? The only method I found is the command and I would like to have my buttons do other things than just close the dialog.

**Comment by coder2000** [comment]
I just call the command at the end of my own actions.

**Comment by Mrxx99** [comment]
I know this is old, but that this has an answer and can be closed:
