### ISSUE TITLE
FlyoutHeaderFontSize

### ISSUE THREAD

**Issue by sagevpremium** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#438]
Hi, i have this issue.
Exception: Cannot find resource named 'FlyoutHeaderFontSize'. Resource names are case sensitive.

**Comment by mgnslndh** [comment]
That resource is located in https://github.com/MahApps/MahApps.Metro/blob/e8236324ba086e250e7da9be85cf668d8f8dbd97/MahApps.Metro/Styles/Fonts.xaml

Make sure you include that resource dictionary in your App.xaml:

```
<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
```

**Comment by Keboo** [comment]
Resource no longer exists in the current version of the code.
