### ISSUE TITLE
Transitioner OpeningEffect(s) wont be executed the second time

### ISSUE THREAD

**Issue by uPloraX** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#441]
Hello,
I got the issue with the Transitioner, that the second views (index 1) opening effect will be correctly animated the first time, but the second time not, only the ripple is applied. The third view (index 2) works fine.

Here you can see it (the Card with back and forward buttons is the second view with index 1):

![wpf_transition](https://cloud.githubusercontent.com/assets/20383017/16714157/5895b0c2-46bb-11e6-8452-ca0fea38aca1.gif)

Transitioner:

```
            <materialDesign:Transitioner HorizontalAlignment="Stretch"
                                         VerticalAlignment="Stretch"
                                         AutoApplyTransitionOrigins="True"
                                         ItemsSource="{Binding Views}"
                                         SelectedIndex="{Binding CurrentViewIndex}" />
```

Example View Content (UserControl):

```
    <materialDesign:TransitioningContent>
        <materialDesign:TransitioningContent.OpeningEffects>
            <materialDesign:TransitionEffect Duration="0:0:0.6" Kind="SlideInFromBottom" />
            <materialDesign:TransitionEffect Duration="0:0:0.6" Kind="FadeIn" />
        </materialDesign:TransitioningContent.OpeningEffects>
        <materialDesign:Card MinWidth="200" MinHeight="200">
            <Grid>
                <Button Command="{x:Static materialDesign:Transitioner.MovePreviousCommand}" Content="BACK" />
            </Grid>
        </materialDesign:Card>
    </materialDesign:TransitioningContent>
```

What could cause the issue and how I can fix it?
Thanks!

**Comment by jasonwurzel** [comment]
I kind of have the same problem, with a simple setup: 
Transitioner with two slides, going back and forth between them. the first time the OpeningEffect of TransitioningContent is executed, but then no more. The documentation above the OpeningEffect Property in TransitioningContentBase says: 
"/// Gets or sets the transition to run when the content is loaded and made visible."
Is it because the content is not made hidden when not on screen? (so it is neither loaded nor made visible the other times...).
Below my little testing snippet:

		<materialDesign:Transitioner x:Name="Transitioner0" SelectedIndex="0" Grid.Row="1">
			<materialDesign:TransitionerSlide>
				<materialDesign:TransitionerSlide.ForwardWipe>
					<materialDesign:CircleWipe />
				</materialDesign:TransitionerSlide.ForwardWipe>
				<materialDesign:TransitionerSlide.BackwardWipe>
					<materialDesign:CircleWipe />
				</materialDesign:TransitionerSlide.BackwardWipe>
				<materialDesign:TransitioningContent OpeningEffect="{materialDesign:TransitionEffect FadeIn, Duration=0:0:3}">
					<DockPanel>
						<TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="22">Spock</TextBlock>
						<Button x:Name="ChangeButtonForward">Forward</Button>
					</DockPanel>
				</materialDesign:TransitioningContent>
			</materialDesign:TransitionerSlide>
			<materialDesign:TransitionerSlide>
				<materialDesign:TransitionerSlide.ForwardWipe>
					<materialDesign:CircleWipe />
				</materialDesign:TransitionerSlide.ForwardWipe>
				<materialDesign:TransitionerSlide.BackwardWipe>
					<materialDesign:CircleWipe />
				</materialDesign:TransitionerSlide.BackwardWipe>
				<materialDesign:TransitioningContent OpeningEffect="{materialDesign:TransitionEffect FadeIn, Duration=0:0:3}">
					<DockPanel>
						<TextBlock HorizontalAlignment="Center" VerticalAlignment="Center" FontSize="22">Checkov</TextBlock>
						<Button x:Name="ChangeButtonBack">Backward</Button>
					</DockPanel>
				</materialDesign:TransitioningContent>
			</materialDesign:TransitionerSlide>
		</materialDesign:Transitioner>


(The Buttons' Clicks are handled/bound in code behind, there I just set the SelectedIndex to 1 / 0

**Comment by wongjiahau** [comment]
Actually I notice this issue as well in the Demo project.

**Comment by Xaalek** [comment]
Old issue, please open a new one if the bug is still there
