### ISSUE TITLE
ComboBox inside DataGridTemplateColumn

### ISSUE THREAD

**Issue by SvilenSh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#461]
If you place ComboBox inside DataGridTemplateColumn without specifying 
`Style="{StaticResource MaterialDesignDataGridComboBox}"`
The popup appear with transparency and have background equal to the container background.
The screen:
![screen](https://cloud.githubusercontent.com/assets/3659134/17514696/af4459c6-5e3c-11e6-817c-b5abee4c8f4a.png)
The code:

```
<DataGrid ItemsSource="{Binding GridSource}" AutoGenerateColumns="False">
    <DataGrid.Columns>
        <DataGridTemplateColumn Header="Row">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <TextBlock Text="{Binding RowNumber}" />
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
        </DataGridTemplateColumn>
        <DataGridTemplateColumn Header="Combobox Test">
            <DataGridTemplateColumn.CellTemplate>
                <DataTemplate>
                    <ComboBox ItemsSource="{Binding ComboBoxItems}">
                    </ComboBox>
                </DataTemplate>
            </DataGridTemplateColumn.CellTemplate>
        </DataGridTemplateColumn>
    </DataGrid.Columns>
</DataGrid>
```

This happens in version 2.0.
In version 1.0 it works just fine.

**Comment by G-monitor** [comment]
same and i get error like 
```System.Windows.ResourceDictionary Warning: 9 : Resource not found; ResourceKey='PrimaryHueMidBrush'```
PS: DataGridCheckBoxColumn has no style too.

**Comment by Keboo** [comment]
This styling behavior is the reason for the `DataGridComboBoxColumn`.
