### ISSUE TITLE
Issue With Combobox FlowDirection

### ISSUE THREAD

**Issue by MidianMhd** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#468]
Excuse Me ... 
Thank you for this great work ... but there is an issue with the combobox.
It appears When I use a ComboBox inside a grid or window that has a FlowDirection property set to RTL
and for some reason I want the FlowDirection of the Combobox to be LTR
In this situation the selected item disappears from top of popup !!!

---

```
<Window FlowDirection = "RightToLeft" --- here>
<Grid  FlowDirection = RightToLeft" --- or here >
        <ComboBox FlowDirection = "LeftToRight" >
            <ComboBoxItem Content="صباحا" IsSelected="True" />
            <ComboBoxItem Content="مساء" />
        </ComboBox>

    </Grid>
</Window>
```

**Comment by KHALED-LAKEHAL** [comment]
Fix the problem in this https://docs.microsoft.com/en-us/answers/questions/60012/wpf-combobox-righttoleft-error.html
thanks

**Comment by MichelMichels** [comment]
I spend around 15 minutes around with a sample app, tried many different setups and couldn't replicate this bug. I don't think this has anything to do with the MaterialDesignInXAML library.

**Comment by Keboo** [comment]
Closing for now. If there are more details feel free to re-open.
