### ISSUE TITLE
Vertical slider with IsSelectionRangeEnabled=true, bad selectionrange width

### ISSUE THREAD

**Issue by Echtelion** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#503]
Bug : 

<Slider TickFrequency="1" Orientation="Vertical" TickPlacement="BottomRight"
                                    Minimum="0" Maximum="10" Value="5" 
                                    IsSelectionRangeEnabled="True" SelectionEnd="5" SelectionStart="0" />

The central range indicator as a Height of 4.0, instead of a Width of 4.0.

Optional Feature Request :
Is it possible to have an option to hide this central indicator ? Or to place it between the range indicators (not centered) ?
Thanks.

**Comment by Keboo** [comment]
This appears to be fixed in the 4.2.1 release
