### ISSUE TITLE
MaterialDesignMultiFloatingActionAccentPopupBox accessible and visible even if button is not visible

### ISSUE THREAD

**Issue by Insire** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#504]
I got the following problem:
- I'm using MahApps.Metro Window and Flyout and the default Dark Theme from this Toolkit
- I have multiple Flyouts that use the same template to let the user quickly access some listboxes and edit the items in them
- for quickaccess to the corresponding action on the listbox i added a MaterialDesignMultiFloatingActionAccentPopupBox with a bunch of buttons that are bound to some ICommands
- those buttons are at the same spot when i expand the flyout, so are their popups

**DefaultView** (notice the slightly lighter rectangle in the middle - i call this popup for now):
![testapp vshost_2016-09-22_17-32-30](https://cloud.githubusercontent.com/assets/11455827/18754970/c4a4cf0a-80ea-11e6-92fb-fb35d4a8f528.png)

**Bug** When i put the mouse cursor where the popup would be if i expand one of the flyouts
![testapp vshost_2016-09-22_17-32-37](https://cloud.githubusercontent.com/assets/11455827/18755155/54a3beb8-80eb-11e6-87ad-acb48b20b42e.png)

What i get when i expand the flyout (as expected)
![testapp vshost_2016-09-22_17-32-46](https://cloud.githubusercontent.com/assets/11455827/18755181/6e86f84a-80eb-11e6-991a-ccd655fca66d.png)

I really like the MaterialDesignMultiFloatingActionAccentPopupBox, but sadly this makes it barely usable. I also noticed that the popup doesnt update if the button gets moved for example.

[Example Repo](https://github.com/Insire/MaterialDesignInXamlToolkitTestApp)

**Comment by ButchersBoy** [comment]
Ha, interesting, because: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.PopupBox.xaml#L329

I should be able to make adjust this "trick"/workaround for the dark theme so you don't see the box.

As for the positioning when used on the flyout, I'll have to do some more investigation.

**Comment by Sergey-Terekhin** [comment]
I have such bug if XAML designer with PopupBox is opened in background

**Comment by garzajp93** [comment]
Has there been any workaround for this issue?
