### ISSUE TITLE
Image Loading Animations

### ISSUE THREAD

**Issue by MovGP0** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#518]
I am wondering how to animate the loading of images while [rendering Opacity, Exposure and Saturation effects properly](https://material.google.com/patterns/loading-images.html). 

So far I wasn't able to find an appropriate shader/animation in the library. I think it should be possible to compose an appropriate effect using the [Expression Blend SDK](https://www.nuget.org/packages/Microsoft.Expression.Blend.SDK.WPF/)'s [ColorToneEffect Class](https://msdn.microsoft.com/en-us/library/microsoft.expression.media.effects.colortoneeffect.aspx). 

Unfortunately it seems to be only available in WPF and not in UWP. So there may be the need to write a custom HLSL shader.

**Comment by ButchersBoy** [comment]
Yeah, currently no support for such things...and I'm not sure there will be; at least not in the near future.

**Comment by MovGP0** [comment]
We might be able to provide our own shaders. Unfortunately, I haven't figured it out yet, but it seems doable with some help. 

### Opacity

Opacity seems to be the easiest on the list, since it comes with any WPF control. Animation of it should be trivial using a `Trigger` and a `Storyboard`, containing a `DoubleAnimation`. We will need an [EasingFunction](https://msdn.microsoft.com/en-us/library/ee308751.aspx) to resemble the higher speed of the transition in the middle (ie. `<CubicEase EasingMode="EaseInOut" />`). 

### Greyscale 

Here is example code for a grayscale effect: 

**GreyscaleEffect.hlsl**

````cpp
sampler2D implicitInput : register(s0);
float factor : register(c0);

float4 main(float2 uv : TEXCOORD) : COLOR
{
	float4 color = tex2D(implicitInput, uv);
	float gray = color.r * 0.3 + color.g * 0.59 + color.b *0.11;

	float4 result;
	result.r = (color.r - gray) * factor + gray;
	result.g = (color.g - gray) * factor + gray;
	result.b = (color.b - gray) * factor + gray;
	result.a = color.a;

	return result;
}
````

See also: [Reference for HLSL](https://msdn.microsoft.com/en-us/library/windows/desktop/bb509638.aspx)

**Build**
`fxc.exe` is part of the [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) located in `${env:ProgramFiles(x86)}\Windows Kits\10\bin\x86\`

```powershell
fxc.exe /T ps_2_0 /E main /Fo "GrayscaleEffect.ps" "GrayscaleEffect.hlsl" 
```

*Hint:* Add the `*.ps` file to the project as `Resource` with `Do not copy`. 

**GreyscaleEffect.cs**

```csharp
public class GrayscaleEffect : ShaderEffect
    {
        private static readonly PixelShader Shader = new PixelShader
        {
            UriSource = Global.GetPackUri("Shaders/GrayscaleEffect.ps")
        };

        public GrayscaleEffect()
        {
            PixelShader = Shader;

            UpdateShaderValue(InputProperty);
            UpdateShaderValue(DesaturationFactorProperty);
        }

        public static readonly DependencyProperty InputProperty = RegisterPixelShaderSamplerProperty("Input", typeof(GrayscaleEffect), 0);
        public Brush Input
        {
            get { return (Brush)GetValue(InputProperty); }
            set { SetValue(InputProperty, value); }
        }

        public static readonly DependencyProperty DesaturationFactorProperty = DependencyProperty.Register("DesaturationFactor", typeof(double), typeof(GrayscaleEffect), new UIPropertyMetadata(0.0, PixelShaderConstantCallback(0), CoerceDesaturationFactor));
        public double DesaturationFactor
        {
            get { return (double)GetValue(DesaturationFactorProperty); }
            set { SetValue(DesaturationFactorProperty, value); }
        }

        private static object CoerceDesaturationFactor(DependencyObject d, object value)
        {
            var effect = (GrayscaleEffect)d;
            var newFactor = (double)value;

            if (newFactor < 0.0 || newFactor > 1.0)
            {
                return effect.DesaturationFactor;
            }

            return newFactor;
        }
    }

   internal static class Global
    {
        /// <summary>
        /// Helper method for getting a "pack://" URI for a given relative file based on the
        /// assembly that this class is in.
        /// </summary>
        public static Uri GetPackUri(string relativeFile)
        {
            return new Uri($"pack://application:,,,/{AssemblyShortName};component/{relativeFile}");
        }

        private static string AssemblyShortName
        {
            get
            {
                if (_assemblyShortName != null)
                    return _assemblyShortName;

                var assembly = typeof(Global).Assembly;
                _assemblyShortName = assembly.ToString().Split(',')[0];
                return _assemblyShortName;
            }
        }
        private static string _assemblyShortName;
    }
```

**Usage**

Since effects are nested to the image/button/etc., it might be tricky to apply the animation to it. So I'd implement a custom control that has a custom `DependentProperty` that can be animated (`double` with an `FrameworkPropertyMetadata.AffectsRender` setting). The `DesaturationFactor` of the `GrayscaleEffect` can then bind to that property in the XAML code. 

## Opacity 

This one is something that I haven't fully understood yet. There seems to be some reference code like [here](http://www.gamedev.net/topic/505641-color-saturation-filter-in-hlsl/) or [here](https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/MiniEngine/Core/Shaders/AdaptExposureCS.hlsl), but with my current lack of insight it might be tricky. 

Besides that, implementing the `ShaderEffect` should be straight-forward.

**Comment by Keboo** [comment]
Closing for now as this is not something that is likely to be directly supported within this library.
