### ISSUE TITLE
TransitioningContent add ability to bind or run when required

### ISSUE THREAD

**Issue by maciz84** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#522]
It would be great to be able to to bind or choose when to run a transition. At the moment the default is to always run on load, but it would be great if we can choose when to start a transition.

A use case scenario would be to disable transitions when updating a collection as some collections update frequently and the transitions would be off putting for the user. So via MVVM binding it would be nice to have a dependancy property where we can bind to transition enabled = true or false kind of thing?

**Comment by maciz84** [comment]
Hi,

You instructed me to add comments in an existing issue instead of the Gitter chat room. Anyway would it be possible to bind the materialDesign:IndexedItemOffsetMultiplierExtension to a property in my ViewModel as means of working around this issue?

**Comment by maciz84** [comment]
And sorry for irritating you as I think I made you angry as I don't know what the rules are about what to comment and what not to in the Gitter chat room:( Sorry James you are doing your best and you get idiots like myself not conforming...I do sincerely apologise.

**Comment by ButchersBoy** [comment]
ha, I'm not irritated :)

To be honest, I just can't remember half the things going on :) and time is always in short supply

**Comment by maciz84** [comment]
Phewww I was worried for a second:) Also do you accept donations from a company? My MD wanted to contribute towards your project?

**Comment by ButchersBoy** [comment]
https://pledgie.com/campaigns/31029

Many thanks!

**Comment by maciz84** [comment]
No worries will do this ASAP

**Comment by maciz84** [comment]
Hi @ButchersBoy ,

I finally managed to get the donation in phewww a few minutes ago under the name of markcvrs:). I had a problem with PayPal but all is good now. Hopefully I can keep giving at every new release..that is my plan.

Just wanted to thank you once again for a great toolkit and as for my other promise of a testimonial and images etc...could you please tell me where to send the stuff to i.e. email address?
