### ISSUE TITLE
Can't use MaterialDesignTheme.MahApps.Defaults.xaml

### ISSUE THREAD

**Issue by clementpoiret** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#523]
Hi,

I'm actually trying to use a rangeslider (mahapps control) but it has the original mahapps design? I know that I need to add the resource to App.xaml like here : https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MahMaterialDragablzMashUp/App.xaml

Unfortunately MaterialDesignTheme.MahApps.Defaults.xaml doesn't exist even with the latest nuget package MaterialDesignTheme.MahApps. Do you know why ? Thanks a lot ! 
![screenshot 17](https://cloud.githubusercontent.com/assets/10899984/19649592/b0879cfc-9a06-11e6-90e2-a89360e8c105.png)

**Comment by pinki** [comment]
I've got the same problem with `<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Defaults.xaml" />`.

**Comment by Insire** [comment]
Make sure to have all the necessary nuget packages installed
![devenv_2016-12-06_23-16-19](https://cloud.githubusercontent.com/assets/11455827/20946227/32fa0420-bc0a-11e6-9812-7f28affa47fc.png)

**Comment by furiousbuilder** [comment]
It happened even with these packages installed

**Comment by ButchersBoy** [comment]
I will try and look at this soon...

**Comment by furiousbuilder** [comment]
It's an old issue but if my memory is good, I need to use the dictionnary for each controls (like  MaterialDesignTheme.Flyouts.xaml) instead of Defaults

**Comment by Keboo** [comment]
No longer an issue in the 4.2.1 release
