### ISSUE TITLE
The dialog doesn't play nice with the ListView

### ISSUE THREAD

**Issue by TKharaishvili** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#534]
With the dark theme selected, the `ListView` placed inside a `DialogHost` and it's background set to `Transparent`(or any other regular value), opening the dialog makes the ListView appear as white for some reason.

Here's a link to a repo demonstrating this issue:
https://github.com/TKharaishvili/MaterialDesignInXamlToolkit.BugReport

And the screens:

Dialog closed:
![opened](https://cloud.githubusercontent.com/assets/4363170/19940371/dc433ad6-a145-11e6-9059-b7ee3c2ee1d6.PNG)

Dialog opened:
![closed](https://cloud.githubusercontent.com/assets/4363170/19940386/eb98d6a8-a145-11e6-9835-6bc35caee8ae.PNG)

You can see the ListView on the background turning white.

Btw, thank you very much for this project. It put the fun back into writing xaml for me :)

**Comment by MairwunNx** [comment]
Maybe i can help you. Simple binding Background property to CardBackground.

`Background="{DynamicResource MaterialDesignCardBackground}"`

And it maybe be works. Anyway, it works for me to solve this problem. 👍

**Comment by Lorymi** [comment]
@MairwunNx Thanks.
But my problem is something else.

Is normal 
![3333232](https://user-images.githubusercontent.com/22388644/47955256-6c58e680-dfaa-11e8-836e-4064d9f8170f.PNG)

When Dialog is open
![3333251](https://user-images.githubusercontent.com/22388644/47955264-7a0e6c00-dfaa-11e8-9ebd-997874bc0b77.PNG)

Why does the Listview background color change?

**Comment by MairwunNx** [comment]
@Lorymi hmm, i don't know how you help. Show you xaml code.

**Comment by Lorymi** [comment]
@MairwunNx  @Keboo 

![32322](https://user-images.githubusercontent.com/22388644/47962684-88ee3080-e035-11e8-856f-f4a0aa1ca88a.PNG)

My code:

` <Page.Resources>

        <Style x:Key="lvStyle" TargetType="{x:Type ListView}">
            <Setter Property="VirtualizingStackPanel.IsVirtualizing" Value="True"/>
            <Setter Property="VirtualizingStackPanel.VirtualizationMode" Value="Recycling"/>
            <Style.Triggers>
                <DataTrigger Binding="{Binding IsLoading}" Value="True">
                    <Setter Property="ListView.Cursor" Value="Wait"/>
                </DataTrigger>
            </Style.Triggers>
        </Style>
    </Page.Resources>`



` <ListView x:Name="ViewFollowers" VerticalAlignment="Top" Style="{DynamicResource lvStyle}" ScrollViewer.HorizontalScrollBarVisibility="Disabled" Margin="20,100,20,0" Background="{x:Null}" Foreground="{x:Null}" BorderBrush="{x:Null}">
                    <ItemsControl.ItemsPanel>
                        <ItemsPanelTemplate>
                            <WrapPanel />
                        </ItemsPanelTemplate>
                    </ItemsControl.ItemsPanel>
                    <ListBox.ItemTemplate>
                        <DataTemplate >
                            <materialDesign:Card materialDesign:ShadowAssist.ShadowDepth="Depth2" Width="150" Height="180" HorizontalAlignment="Stretch" UniformCornerRadius="2" Background="{DynamicResource MaterialDesignPaper}">
                            </materialDesign:Card>
                        </DataTemplate>
                    </ListBox.ItemTemplate>
                <ListView.ItemContainerStyle>
                    <Style TargetType="ListViewItem">
                        <Setter Property="BorderThickness" Value="0"/>
                        <Setter Property="Margin" Value="0,10,8,0"/>
                        <Setter Property="Padding" Value="0"/>
                        <Setter Property="Background" Value="{x:Null}"/>
                    </Style>
                </ListView.ItemContainerStyle>
            </ListView>`




`await DialogHost.Show(new Dialogs.RemoveFollower() { DataContext = ((Button)sender).DataContext },"RootDialog");`

**Comment by TKharaishvili** [comment]
@Keboo no problem. I'll check it out a bit later and close the issue.

**Comment by TKharaishvili** [comment]
@Keboo updating to version 2.5.0 does work. 
If other participants of the discussion have their problems fixed too, I'll be happy to close the issue.

**Comment by Keboo** [comment]
@TKharaishvili thanks for testing. Closing for now. If updating to 2.5.0 does not resolve someone's issue please re-open.
