### ISSUE TITLE
ValidationErrorTemplate hardcoded background

### ISSUE THREAD

**Issue by JamesIrish** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#539]
Hi,

Any chance of changing `MaterialDesignValidationErrorTemplate` to not use a set value for it's background?

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml#L24

https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ValidationErrorTemplate.xaml#L39

![image](https://cloud.githubusercontent.com/assets/608370/20032738/fd785ffc-a388-11e6-8a5f-c5abd8869d82.png)

Thanks,
James

**Comment by EdonGashi** [comment]
Agree, it's noticeable when placing fields on cards now that they use different background

**Comment by ButchersBoy** [comment]
Hey guys, if anyone can dig out the Google spec, or get a decent RGB we can put a brush in Light & Dark. Xaml

**Comment by EdonGashi** [comment]
Is transparent an option here? We can't know against what background controls will be placed

**Comment by JamesIrish** [comment]
The spec doesn't detiail that specifically:  https://material.google.com/components/text-fields.html#text-fields-required-fields  +section below

I think transparent is the way to go.  Any reason it's specified at all?    Seems odd which makes me suspect it's there for a reason!

Will copy the template into my solution and give it a go...

**Comment by JamesIrish** [comment]
Both setting to Transparent & removing the property work for both lines listed above.

![image](https://cloud.githubusercontent.com/assets/608370/20185033/7ca0ee48-a762-11e6-8646-0fa198d4b134.png)

Haven't spotted any side effects.  Wouldn't mind integrating this could you, save creating a PR - pretty minor 😃 
Cheers
James

**Comment by ButchersBoy** [comment]
FYI the second element link posted by @JamesIrish is a little more tricky.  This is a popup, so transparent isnt going to work.  (There are two flavours of the validation template.)

**Comment by Keboo** [comment]
This is now handled with the `ValidationAssist.Background` attached property
