### ISSUE TITLE
DataGridAssist.EnableEditBoxAssist enables editing when DataGrid.IsReadOnly=true

### ISSUE THREAD

**Issue by maximcus** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#546]
With commit 66da08e (resolving issue #100) was introduced this problem: by default `CheckBox` controls in `DataGridCheckBoxColumn` and `ComboBox `controls in `DataGridComboBoxColumn `will be editable when `DataGrid.IsReadOnly=true`. This is happening because of `DataGridAssist.EnableEditBoxAssist` DependencyProperty.

I think that if code associated with `DataGridAssist.EnableEditBoxAssist` will only work when `IsReadOnly` property of DataGrid and respective DataGridColumns is false, then this issue will not arise.

**Comment by w-syss** [comment]
This is no longer happening and can be closed.
@Keboo
