### ISSUE TITLE
Date Picker - MaterialDesignFloatingHintDatePicker margin issue

### ISSUE THREAD

**Issue by elvince** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#554]
Hi,

If you are using MaterialDesignFloatingHintDatePicker on a date picker within a stackpanel. You will see that the hint value will be over the previous element of the stack panel.
We don't have this issue with MaterialDesignFloatingHintTextBox where the height is managed properly.

I saw that in your sample you add Margin="0 16 0 0" to fix this, but this should be set within the style and not on all date picker.

Thanks,

**Comment by Keboo** [comment]
This appears to be resolved in the 4.2.1 release
