### ISSUE TITLE
HintAssist.FloatingScale and ComboBox

### ISSUE THREAD

**Issue by pinki** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#570]
Hi,
is there a way to get FloatingScale work with ComboBoxes?

**Comment by jr2424** [comment]
I believe this is related to issue #547. I do not believe the MaterialDesignTheme.ComboBox.xaml wpf:SmartHint is binding to the appropriate properties on the TemplatedParent. The FloatingOffset is also not working due to this.

**Comment by Keboo** [comment]
Also #988

**Comment by Keboo** [comment]
Resolved by #899
