### ISSUE TITLE
The DecorationHint doesn't work for ComboBox

### ISSUE THREAD

**Issue by ngodugu** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#585]
The TextFieldAssist.DecorationVisibility="Hidden" doesn't turn off the decoration for a combobox.

Below is the reproducible XAML
`  <ComboBox Grid.Row="5" Grid.Column="3" materialDesign:HintAssist.Hint="Search" materialDesign:TextFieldAssist.DecorationVisibility="Hidden" IsEditable="True" Style="{StaticResource MaterialDesignFloatingHintComboBox}"
                  Margin="0 8 0 8">
            <ComboBoxItem IsSelected="True">Apple</ComboBoxItem>
            <ComboBoxItem>Banana</ComboBoxItem>
            <ComboBoxItem>Pear</ComboBoxItem>
            <ComboBoxItem>Orange</ComboBoxItem>
        </ComboBox>`

**Comment by lezzi** [comment]
If I understand correctly, you should use **TextFieldAssist.DecorationVisibility** together with **BorderThickness="0"**.

**Comment by Keboo** [comment]
Fixed in latest 4.2.1 release
