### ISSUE TITLE
ComboBox Visual Glitch when not using DataBinding

### ISSUE THREAD

**Issue by andy-bond** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#601]
## Explanation of Issue

In my test project, I attempted to put a simple StackPanel object inside a ComboBoxItem. 
The StackPanel contained only a MaterialDesignPackIcon and a TextBlock. 
Even though the SelectedIndex was set on the ComboBox (confirmed to actually be working in the CodeBehind), the ComboBox would not render the StackPanel until the ComboBox was activated/dropped-down.

Here is the code in question:

```
<ComboBoxItem Name="XLS">
    <StackPanel Margin="8 0 0 0" Orientation="Horizontal">
        <materialDesign:PackIcon Kind="FileExcel"/>
        <TextBlock Margin="8 0 0 0">Microsoft Excel Spreadsheet</TextBlock>
    </StackPanel>
</ComboBoxItem>
<ComboBoxItem Name="DOC">
    <StackPanel Margin="8 0 0 0" Orientation="Horizontal">
        <materialDesign:PackIcon Kind="FileWord"/>
        <TextBlock Margin="8 0 0 0">Microsoft Word Document</TextBlock>
    </StackPanel>
</ComboBoxItem>
<ComboBoxItem Name="PDF">
    <StackPanel Margin="8 0 0 0" Orientation="Horizontal">
        <materialDesign:PackIcon Kind="FilePdf"/>
        <TextBlock Margin="8 0 0 0">Portable Document Format</TextBlock>
    </StackPanel>
</ComboBoxItem>
```

I could have instead used the following for the error to **not** occur:

```
<ComboBoxItem Name="XLS">Microsoft Excel Spreadsheet</ComboBoxItem>
<ComboBoxItem Name="DOC">Microsoft Word Document</ComboBoxItem>
<ComboBoxItem Name="PDF">Portable Document Format</ComboBoxItem>
```

I also found that by DataBinding an object, I would avoid this issue (see How NOT to Reproduce section)

## How to Reproduce

Visual Glitch Repository: [Here](https://github.com/andybond006/MaterialDesign-ComboBoxVisualGlitch)

- Download and Open
- Run Application
- Click the PopupBox in Right Corner
- Click Settings
- In the dialog, click the item on the left that says: "Report Settings"
- You will notice the ComboBox does not show anything in the ComboBox
- In the Code Behind, however, an item is selected (the default item which is set the Settings.Settings)

## How NOT to Reproduce

Repository that uses DataBinding: [Here](https://github.com/andybond006/MaterialDesign-ComboBoxVisualGlitch-DataBinding)

- Same Steps
- The item **will** appear correctly in the ComboBox

## Screenshots

Here is an example of the issue:

![glitch](https://cloud.githubusercontent.com/assets/10934345/22264456/03178536-e246-11e6-87e3-b16516e3d297.png)

Here is what is should look like (this is from the DataBinding example repo):

![no-glitch](https://cloud.githubusercontent.com/assets/10934345/22264469/0fdabc48-e246-11e6-855e-be83a56a00fd.png)

**Comment by MichelMichels** [comment]
Fixed by #1681. I reviewed that the coding is working as expected.
