### ISSUE TITLE
DataGrid Select All button unexpected behaviour

### ISSUE THREAD

**Issue by ruslanfedoseenko** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#61]
Sample XAML

```
        <GroupBox Grid.Row="1"
                  Grid.Column="0">
            <DataGrid IsReadOnly="True"
                          ItemsSource="{Binding Items}"
                          SelectedValue="{Binding SelectedItem,
                                                  Mode=TwoWay}"/>
        </GroupBox>
```

I have Binding Errors in Console 

```
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-0.288220551378446' BindingExpression:Path=CellsPanelHorizontalOffset; DataItem='DataGrid' (Name=''); target element is 'Button' (Name=''); target property is 'Width' (type 'Double')
```

First thing to reproduse issue: you should have enough rows in DataGrid to make the horithontal scroll bar at the bottom appear;
To reproduce it just move handle of horithontal scroll bar in any dirrection.
You'll see that scroll bar left button with arrow and all data grid start jumping(Due to appearing of select all button).
Here is screenshot when button appears
![image](https://cloud.githubusercontent.com/assets/4517707/9957878/9adedc08-5e0c-11e5-84f3-0ca40d56af51.png)
Now it is Collapsed
![image](https://cloud.githubusercontent.com/assets/4517707/9957890/cbf62f44-5e0c-11e5-8331-ca148b41aa7d.png)

**Comment by ButchersBoy** [comment]
Wasn't able to reproduce the flickering, but the row header (not column header) wasn't displaying correctly.  I've defaulted it to off, but if you enable it it now forces a minimum width which should stop it bouncing around.

I'm not happy with the style of the select all button so i'll try and come back to it.

**Comment by ButchersBoy** [comment]
Help wanted to tidy up select all/row header buttons...a bit out of alignment.

**Comment by SuicSoft** [comment]
This should be fixed

**Comment by james-c-m-kim** [comment]
Do you need any help to test this out?

**Comment by ButchersBoy** [comment]
I haven't looked at this for ages...I think it still Probably needs tidying up

**Comment by Keboo** [comment]
@ButchersBoy from reading the comments it is not clear to me what else needs to be done for this. I am happy to submit a PR. Any guidance?

**Comment by Keboo** [comment]
This appears to already be addressed. Closing for now.
