### ISSUE TITLE
DialogHost MouseOver bug(?)

### ISSUE THREAD

**Issue by Carlj28** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#642]
I have problem with DialogHost, I want to subscribe to MouseLeave event that is on parent control that contains my custom DialogHost it executes when mouse is over DialogHost body and Mouse.DirectlyOver is returning null, sample can be found in [this](https://github.com/Carlj28/MaterialDesignDialogHostBug) repo.

**Comment by Keboo** [comment]
This is by design since the default dialog is shown in a popup control. In the latest 4.2.1 release there is an embedded dialog host that will work, however it limits the size of the dialog to fix within the containing DialogHost
