### ISSUE TITLE
DialogHost freezing

### ISSUE THREAD

**Issue by Carlj28** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#644]
[**Source**](https://github.com/Carlj28/MaterialDesignDialogHostFreezing)

Steps to reproduce:
1. Click "Open sub window"
2. Click "Open DH"
3. Close "Sub window" (close is overriden, it actualy hides)
```
        private void Window_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            this.Hide();
            e.Cancel = true;
        }
```
4. DialogHost is still open after closing (hiding) parent window
![2017-03-02 14_02_40-](https://cloud.githubusercontent.com/assets/4525831/23508232/ffa5c6d8-ff50-11e6-9ccc-666270a66957.png)
![2017-03-02 14_03_00-](https://cloud.githubusercontent.com/assets/4525831/23508239/05eb6fd4-ff51-11e6-86a7-b630fd66f535.png)

5. Click "Open sub window"
6. Click "Open DH" and DialogHost is now frozen

This occurs when parent window of DialogHost is Hidden instead of closing.

**Comment by Keboo** [comment]
For now, we are not planning on handling hiding the dialog when the window is hidden. As an alternative there is an optional DialogHost style called `MaterialDesignEmbeddedDialogHost` which will put the dialog as part of the window rather than as a popup
