### ISSUE TITLE
Using MaterialDesign:DialogHost.CloseDialogCommand closes all open Dialogs

### ISSUE THREAD

**Issue by Lewissss** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#648]
Scenario:

- Have a user control that is a dialog host.
- The dialog opened up by the form above is also a dialog host.
- When this host opens its dialog, calling the CloseDialogCommand will close both its parent, and its parent parent. 

Not sure if this is an issue, or intended design.

**Comment by Tyrrrz** [comment]
Not exactly sure what the setup is, but if you're opening multiple dialogs within each other, it's worth noting that MaterialDesign recommends to avoid that ([Ctrl+F 'Dialogs should avoid'](https://material.io/guidelines/components/dialogs.html#dialogs-behavior)).

**Comment by james-c-m-kim** [comment]
Just curious, what is the scenario where you require dialog-on-dialog? Maybe you need to just push additional content to the existing dialog? Or maybe what you need is more of a (stackable) toaster?

**Comment by ButchersBoy** [comment]
Probably we need to had a Handled thingy when trapping the even so it doesnt bubble up further.

**Comment by MichelMichels** [comment]
It seems someone already made this change and didn't close the issue:

```csharp
private void CloseDialogHandler(object sender, ExecutedRoutedEventArgs executedRoutedEventArgs)
{
    if (executedRoutedEventArgs.Handled) return;

    InternalClose(executedRoutedEventArgs.Parameter);

    executedRoutedEventArgs.Handled = true;
}
```
Code is from MaterialDesignThemes.Wpf.DialogHost line 841.
