### ISSUE TITLE
Request: Bottom Navigation Bar

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#652]
Request for a new control or style for "Bottom Navigation" as per the specs at https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage

Perhaps we could name it "Navigation Bar" if it will be "location independent". I guess it could be used on the top as well.

Possible starting points:

* TabControl
* Dragablz
* ListBox

## Gitter Chat Background

> Magnus Lindhe @mgnslndh Feb 16 11:30
> @ButchersBoy Would you consider a ListBox style for https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-usage?
> 
> James Willock @ButchersBoy Feb 16 11:31
> I've been thinking about this the last few days... Currently considering whether to use a TabControl, or Dragablz...
> 
> Magnus Lindhe @mgnslndh Feb 16 11:34
> Ah, I was thinking about that as well. But i'm using the Transitioner for my main view and the buttons control the slide index
> Having a ListBox gives that flexibility to separate the selection and what happens on selection
> But it would also be nice to have a Tab like control as well
> The actual button styles should be reusable so one could have both?
>  
> 
> Magnus Lindhe @mgnslndh Feb 16 11:39
> Today I'm using simple buttons but I would like to move away from abusing the floating action button.
> 
> James Willock @ButchersBoy Feb 16 16:08
> @mgnslndh interesting that you are using the Transitioner... Cool... Food for thought. Let me just dwell on it a bit.

## Inspiration

![bottombar_material_io](https://cloud.githubusercontent.com/assets/1139118/23784731/ebc35b26-0563-11e7-9e64-ffb8a40d7683.gif)

https://material.uplabs.com/posts/betterbottombar

**Comment by MichelMichels** [comment]
This can be closed as there's an implementation for it. See:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/1051#issuecomment-926776673
