### ISSUE TITLE
Under Dark theme, in a ColorZone with Mode=Inverted: results in DatePicker with black dates on black background

### ISSUE THREAD

**Issue by james-c-m-kim** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#675]
My window uses the dark theme, primary color=teal, accent color=pink.

Within a groupbox, I have an ItemsControl with an ItemTemplate that contains a colorzone with mode=inverted. Inside of that colorzone, I have a grid which renders white (as desired), and contains various fields, all rendering nicely except for the DatePicker. When I click on the date picker button, the calendar that pops up renders the header as expected (teal), but the resultant background is dark text on dark background.

Sample enclosed...
[WpfApp1.zip](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/902936/WpfApp1.zip)

**Comment by Keboo** [comment]
Hi @james-c-m-kim 
If you move these line from MainWindow.xaml into App.xaml it will work as expected.
```XAML
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/materialdesigntheme.dark.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/materialdesigntheme.defaults.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/themes/recommended/primary/materialdesigncolor.teal.xaml" />
<ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/themes/recommended/accent/materialdesigncolor.pink.xaml" />
```

The issue is you are loading them as part of the window, but you need to load a color theme prior to loading your main window.

**Comment by james-c-m-kim** [comment]
Ahh, that will be problematic, as I am working on a plug-in control,
without access to App.xaml. The App.xaml is located in a different dll
(totally different project than mine) and it only does windows management.
Is there any way to manage this via some "elegant" codebehind?

I've been able to workaround this with some event-driven code, but it's a
bit of nasty work (aka not quite elegant, lol)...!

**Comment by Keboo** [comment]
@james-c-m-kim Sure you can do it in the code behind. Assuming the hosting application is WPF, something like this in the MainWindow constructor (must be before the InitializeComponent call).
```C#
if (Application.Current != null)
{
    Application.Current.Resources.MergedDictionaries.Add(new ResourceDictionary{Source = new Uri("pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/materialdesigntheme.dark.xaml") });
    Application.Current.Resources.MergedDictionaries.Add(new ResourceDictionary{Source = new Uri("pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/materialdesigntheme.defaults.xaml") });
    Application.Current.Resources.MergedDictionaries.Add(new ResourceDictionary{Source = new Uri("pack://application:,,,/MaterialDesignColors;component/themes/recommended/primary/materialdesigncolor.teal.xaml") });
    Application.Current.Resources.MergedDictionaries.Add(new ResourceDictionary{Source = new Uri("pack://application:,,,/MaterialDesignColors;component/themes/recommended/accent/materialdesigncolor.pink.xaml") });
}
```

If the hosting application is not a WPF application, you may need to instantiate your own App context and add the resources to that.

**Comment by james-c-m-kim** [comment]
Sweet - thanks!
