### ISSUE TITLE
Datepicker Not Support Persian Calendar "fa-IR"

### ISSUE THREAD

**Issue by babakgm** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#677]
Hi
shamsi calendar add to windows since windows 10
I try change datepicker language to farsi when my windows calendar is shamsi and Gregorian

` <DatePicker  Language="fa-IR" FlowDirection="RightToLeft" />`

but in both local time have this error

>Specified time is not supported in this calendar. It should be between 03/22/0622 00:00:00 (Gregorian date) and 12/31/9999 23:59:59 (Gregorian date), inclusive.
 
plz add shamsi calendar "fa-IR"

**Comment by alijey** [comment]
Having the same problem... Looking at the source codes, it looks like it only supports Gregorian

**Comment by jaywha** [comment]
Seeing as how Google also added this [feature](https://plus.google.com/u/0/+Gmail/posts/L6RA2WyFfYQ), I'd say this could fit with the Contribution Guidelines point:
> "... Custom controls for Google specified components _where no parallel exists in WPF_, or where existing WPF controls cannot be sufficiently styled to meet the Google specification."

That being said, I found an older [WPF control](https://www.codeproject.com/Articles/43521/PersianDate-and-Some-WPF-Controls-For-It) that helps with the concept of the calendar (which was new to me) and could serve as an alternative for now.

Hope this helps.

**Comment by jespersh** [comment]
Keep an eye on https://github.com/dotnet/wpf/issues/226 (.netcore wpf)

**Comment by Keboo** [comment]
Appears fixed in the latest 4.2.1 release
