### ISSUE TITLE
Placing a ColorZone at the top of a dialog will produce a sliver of white background in the corners

### ISSUE THREAD

**Issue by mgnslndh** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#678]
@andybond006 reported this issue [in the chat](https://gitter.im/ButchersBoy/MaterialDesignInXamlToolkit?at=584975240da034021b853950)

> Also, not sure if you can see in that image or not, but it looks like the ColorZone doesn't reach the end of the Card on the right side or the upper left corner. There seems to be a sliver of white background visible.

![image](https://cloud.githubusercontent.com/assets/1139118/24840269/77591306-1d6a-11e7-8944-2a4c07c1be06.png)

**Comment by james-c-m-kim** [comment]
Does snoop show what's going on?

**Comment by Insire** [comment]
Can we get a repro for this? I'm failing to reproduce the issue when modifying the MaterialDesignDemo.

**Comment by mgnslndh** [comment]
I've put up a repo here where I try to show the glitch. I'm currently not being able to show the exact same behaviour but I can show a glitch using a `ColorZone` in a `Card` or a `GroupBox`. Could be related.

https://github.com/mgnslndh/MaterialDesignInXamlToolkit-678

![image](https://user-images.githubusercontent.com/1139118/31575097-122e885e-b0df-11e7-8e22-0a9ac8c0f0c4.png)

![image](https://user-images.githubusercontent.com/1139118/31575129-df771ac4-b0df-11e7-8e0f-e33dd3b3e80c.png)

![image](https://user-images.githubusercontent.com/1139118/31575138-19e07fd4-b0e0-11e7-96cf-08c22acb258a.png)

**Comment by MichelMichels** [comment]
This seems fixed. It's possible this is device-related and could be fixed by using `UseLayoutRounding` on your `Window`. There's also a `SnapToDevicePixels` you can set to fix some obscure rendering related to WPF.
