### ISSUE TITLE
Visual Studio Opens Popup Box Content In Design Time

### ISSUE THREAD

**Issue by Talha-T** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#686]
It is the exact location when app starts on another page.

![image](https://cloud.githubusercontent.com/assets/25489715/25087303/84c840c2-2376-11e7-85f3-316828798116.png)

**Comment by ButchersBoy** [comment]
Guess we need to add a little designer detection and disable the popups

**Comment by MichelMichels** [comment]
I can't recreate this bug, assuming it is fixed by now.
