### ISSUE TITLE
[Bug|missing feature] Flipper prevents content from changing colors on switching palette

### ISSUE THREAD

**Issue by Insire** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#694]
Reproduction:
- start MaterialDesignDemo app from the Demos folder in the solution
- switch to Cards view and check color of the Flipper and its child ColorZone being violet and lime accent
- then change palette in palette view to a different color for accent and primary
- switch back to Cards view

**Expectation:**
- Flipper and its child ColorZone have the selected colors

**Result:**
- Flipper and its child ColorZone still have the old colors (violet and lime)

The issue can be verified in my own [project](https://github.com/Insire/Maple) too
- start the app
- click the globe in the window header
- view with flipper opens
- click brush in window header
- change color in the opening view for primary and accent
- click globe again
- flipper still has the same color

**Comment by Insire** [comment]
Here are some more information on the problem. 

I did some looking around on google, and from my limited understanding of the matter, it seems that there is no easy universal way to update dynamic resources in an animation. The common approach seems to be to handcode the original animation and additionally handcode the animation for the color change in code behind. Obviously thats not a viable approach for a control library.

Does anyone have a better insight on the topic? Did i miss something? This is a really cool control and it would be sad if it would have such limited functionality.

**Comment by Aangbaeck** [comment]
I'm missing this badly as well. As it is now, the user has to select a theme and then restart the app for flippers to follow theme.

**Comment by Tide** [comment]
This bug is still present.  Has anyone found a workaround/fix?

**Comment by ChrisLawford** [comment]
I would love to know if anyone has a workaround for this aswell. I was wondering if there is anyway to get the theme colour from the Palette selector but had no luck.

**Comment by Keboo** [comment]
Flagging this for review with the 2.5.0 release. This just means I will spend some time digging into the cause of the issue (maybe fixing depending on what it is) prior to releasing 2.5.0.

**Comment by sebaJoSt** [comment]
I think this is still open. I tried to implement the flipper in my own app, but the colors are not updated when switching from light to dark mode and vice versa. The latest MaterialDesignDemo app shows the same behaviour.

**Comment by bee-eater** [comment]
Push

**Comment by Xaalek** [comment]
I'm going to check that
