### ISSUE TITLE
HintAssist

### ISSUE THREAD

**Issue by Paley01** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#708]
Have you removed HintAssist? 

I am using:

  <package id="MahApps.Metro" version="1.5.0" targetFramework="net461" />
  <package id="MaterialDesignColors" version="1.1.2" targetFramework="net461" />
  <package id="MaterialDesignThemes" version="1.5.0.523" targetFramework="net461" />
  <package id="MaterialDesignThemes.MahApps" version="0.0.10" targetFramework="net461" />

**Comment by ButchersBoy** [comment]
Nope.

**Comment by Paley01** [comment]
Weird. I can't find it at all.

**Comment by Paley01** [comment]
Ah - when I installed MaterialDesignThemes.MahApps it installed an old version of MaterialDesignThemes
