### ISSUE TITLE
materialDesign:Card's shadow does not work

### ISSUE THREAD

**Issue by zhaiyuhan** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#735]
i use materialDesign:Card,i want use it's shadow effect,but it does not work
like
<materialDesign:Card materialDesign:ShadowAssist.ShadowDepth="Depth5" Padding="32" Height="242" Width="283"/>

**Comment by ButchersBoy** [comment]
Hi, I'm seeing this:

![image](https://user-images.githubusercontent.com/658107/27797370-4aa04324-6005-11e7-8484-e473520e59e1.png)

```
<UserControl>
    <materialDesign:Card materialDesign:ShadowAssist.ShadowDepth="Depth5" Padding="32" Height="242" Width="283">
        <TextBlock Margin="32">Hello World</TextBlock>
    </materialDesign:Card>
</UserControl>
```

Could there be something above/around your card causing the shadow to clip?  Can you most more XAML?

**Comment by zhaiyuhan** [comment]
Thank u very much
