### ISSUE TITLE
Snackbar won't show up immediately after Enqueue is called

### ISSUE THREAD

**Issue by wongjiahau** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#738]
I am expecting a snackbar to show up the latest content if Enqueue is called, however if Enqueue is called a few times in a very short period of time (say 1 second), the latest call on Enqueue won't have result immediately, instead there are delay. 
Should have added a property for snackbar : 
ShowEnqueuedContentImmediately = "True"
Or 
ShowEnqueuedContentDelay = "0"

**Comment by avdynut** [comment]
Yes, there definitely should be this option.

**Comment by jespersh** [comment]
That doesn't sound like a queue to me...

**Comment by Keboo** [comment]
This is now handled with the `SnackbarMessageQueue.Enqueue` and passing the `durationOverride`. This duration can be set to zero.
