### ISSUE TITLE
Left Menu bar 

### ISSUE THREAD

**Issue by Maradaehne** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#740]
# PLEASE READ BEFORE POSTING AN ISSUE

# This is a place for issues.  Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. 

My time is limited and .Zip files, code snippets and partial examples are often a time sink.  GitHub also provides great communication and code review tools which can be utilised.

# HOW TO POST A GOOD SAMPLE.  Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc.  If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages".  If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward.  I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Comment by Maradaehne** [comment]
Hi i wondered if it is possible with the drawerhost to achive a menu bar on the left side like in this example: 

[https://www.richmediagallery.com/#](url)

What I want to have is that 

1. nothing from the main view should be overlayed or grayed out/disabled.
2. the menu slides in and stays open until it will be closed by a click to the hamburger or a close button in the host.

If this cannot be realized by the drawer host is there another way to this?
I thought about a expander, but maybe you know a better way.

Thanks

**Comment by Keboo** [comment]
This is not what the DrawerHost is meant to do. I think you are on right path with the Expander. I would start by looking over the [Expander example](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Expander.xaml#L87) in the sample application. You likely will need to build out the rest of the code from there.
