### ISSUE TITLE
HintProxyFabric.RegisterBuilder - Designer setup to avoid not implemented errors?

### ISSUE THREAD

**Issue by elvince** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#742]
Hi,

I had to write a new builder for the HintProxy.
I call HintProxyFabric.RegisterBuilder in my App.xaml.cs file and everything is working properly in runtime.

In xaml designer, it raises a "NotImplementedException". I understand where comes the error as HintProxyFabric is raising it when no builder are found for the control. 

So where should I write the HintProxyFabric.RegisterBuilder to avoid the designer error and get the control working in design mode?

Thanks,

**Comment by rbeurskens** [comment]
Same if I call HintProxyFabric.RegisterBuilder in the static constructor of my custom control.

**Comment by Keboo** [comment]
fixed by #2438
