### ISSUE TITLE
Front size of resizable card is wrong if explicitely set

### ISSUE THREAD

**Issue by tanguykurylo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#744]
If the front size on a flippable card is set explicitly in XAML and is different than the back size, the front size is computed smaller than intended and squashed vertically.
![squashed card](https://user-images.githubusercontent.com/16517108/28022145-8f0d585a-658a-11e7-98a7-c9317ed23b69.PNG)

[Link to the demo repository:](https://github.com/tanguykurylo/DemoResizableCards)

**Comment by Xaalek** [comment]
The behavior has change since but their is still bugs with the flipper. The issue https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/2729 will  probably fix this one.
