### ISSUE TITLE
Palette Helper

### ISSUE THREAD

**Issue by David-Loving** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#748]
I am style our application with the Material design styles.  The PaletteHelper class has a ready large design flaw if you want to add custom or limit the number of swatches.  The SwatchesProvider supports adding a custom assembly that controls the swatches but there is no way to pass this information in to the PaletteHelper, as it news up the SwatchesProvider  in every method it is used.  

public Palette QueryPalette()
{
    var swatchesProvider = new SwatchesProvider();

This either need to pass into the method as a parameter or a property on the class.

**Comment by ButchersBoy** [comment]
Hi, you can suggest your changes in a PR and I will review them.

**Comment by Keboo** [comment]
Many of these concerns are being mitigated with various theming improvements that occurred in the 3.x releases
