### ISSUE TITLE
ProgressBar animation not work when include in DataTempalte

### ISSUE THREAD

**Issue by joffreynorsys** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#770]
Hello,

When i put a progress bar as data template in content template, the animation don't start

```xml
 <DataTemplate x:Key="AwaitableProgressBar">
        <ProgressBar IsIndeterminate="true" Style="{StaticResource MaterialDesignCircularProgressBar}"  Value="0" />
    </DataTemplate>
```
```xml
   <Button ContentTemplate="{StaticResource AwaitableProgressBar}" ... />
```

**Comment by varunvasisht84** [comment]
Hello Joffery,
I think the animation works. I just checked. The only catch is that both the button and progress have the same color. Try changing the color of Button say,

<Button Background="Aqua" ContentTemplate="{StaticResource AwaitableProgressBar}"/>

varun

**Comment by varunvasisht84** [comment]
<Button Background="Aqua" ContentTemplate="{StaticResource AwaitableProgressBar}"/>

**Comment by Bennith** [comment]
Yes I have tested and agree with Varun,

Animation will show when you change the background of the button to be different to the colour of the progress bar.

_Standard button & progress bar background probably set by default to use Accent Colour_

**Comment by joffreynorsys** [comment]
oh sorry for the delay. Yes it's because of the same color. It work fine.

Thank you
