### ISSUE TITLE
24th Minute shows up as 0 on Clock Picker

### ISSUE THREAD

**Issue by CameronAavik** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#775]
I was looking through the code to see how the Clock Picker was done and noticed a small bug on review:
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Clock.cs#L320

On this line, if the value is 24, then it sends through as 0, however this is expected behaviour when we want to show the 24th minute. I reproduced this issue on the demo app:

![image](https://user-images.githubusercontent.com/5800980/29484628-fd14b89e-8505-11e7-9134-58e3433b67fd.png)

**Comment by wongjiahau** [comment]
This is a real bug. I had tested it too.

**Comment by Keboo** [comment]
Fixed by #1155
