### ISSUE TITLE
Transitions and Frame

### ISSUE THREAD

**Issue by SuplenC** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#784]
I couldn't make it work together. Tried to combine the ExpandIn animation from transitions and Frame but couldn't manage it to work. Tried to use the TransitioningContent instead of Frame, tried to put the Frame inside TransitioningContent, tried to put the Frame inside Transitioner. I would like not to use the Transitioner and add/remove a new Frame everytime, is there a way to combine those two?

**Comment by Keboo** [comment]
Closing this issue for now as there are not enough details here. If this is still an issue a reproduction project would be helpful in demonstrating the problem.
