### ISSUE TITLE
Combobox doesn't have same text field padding as TextBox

### ISSUE THREAD

**Issue by maciz84** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#801]
Hi,

I have noticed that the ComboBox and TextBox don't have the same padding and margins for the hint and textfields respectively. This causes the controls to look disjointed if stacked up next to each other.

Here is the link to a repo:

[https://github.com/maciz84/WpfApplication6](url)

**Comment by Keboo** [comment]
Adding some screen shots:

![image](https://user-images.githubusercontent.com/952248/30652527-72e1964c-9ddd-11e7-927e-79dcf6295c86.png)

![image](https://user-images.githubusercontent.com/952248/30652546-810d295c-9ddd-11e7-8873-589ed26578c4.png)

Unfortunately I am not able to re-create the issue. Perhaps a system specific issue?

**Comment by maciz84** [comment]
@Keboo it appears to be the case. I can see you are using Windows 10?? I will try and test it on Windows 10 machine and see the results

**Comment by Keboo** [comment]
@maciz84 yes let me know. I only have Windows 10 machines that I work on. What is the system configuration (OS, Display, DPI) of the system where you see the issue?

**Comment by Keboo** [comment]
Resolving for now, as there is now a page in the demo app to ensure all of the fields line up properly..
