### ISSUE TITLE
Unlimited Content Height/Width in Expander Control

### ISSUE THREAD

**Issue by JonathanSchafer** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#803]
I noticed this issue when placing a ScrollViewer inside of MaterialDesign's Expander. The ScrollViewer does not work inside of the Expander due to it having infinite height/width. This behavior is equivalent to putting a ScrollViewer in a grid with the height set to "auto" instead of "*". 

This works perfectly when using the default Expander. I tried numerous workarounds before trying to reproduce it with the bare minimum and realizing it was the MaterialDesign Expander.

Demo: https://github.com/JonathanSchafer/DemoMaterialDesignExpanderContentSizingIssue

**Comment by Keboo** [comment]
Fixed by #1434
