### ISSUE TITLE
Something went wrong with Demo projects in VS 2017 WPF solution

### ISSUE THREAD

**Issue by JeffRockatansky** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#804]
So, I've downloaded .zip from master branch, unpacked it, opened "MaterialDesignToolkit.WPF" solution in my Visual Studio 2017 (v 15.3.5) and got 25 errors like "The name does not exist in the namespace"

Is something wrong with VS or it could be fixed by downloading something? 
![materialdesignxamltoolkit_demo_errors](https://user-images.githubusercontent.com/26058495/30872818-c786080a-a304-11e7-8533-1b6b796bbcfd.png)

**Comment by ButchersBoy** [comment]
What's the very first error?

**Comment by JeffRockatansky** [comment]
The name "TabablzControl" does not exist in the namespace "clr-namespace:Dragablz;assembly=Dragablz".
In App.xaml

**Comment by Keboo** [comment]
@JeffRockatansky i would suspect that dependencies are missing. After attempting to build the solution (packet and the dependencies should download as part of the build process), check and see if there packages directory in the same folder as the solution.

If it is missing try [turning up your build output](https://blogs.msdn.microsoft.com/david_kidder/2013/10/14/crank-up-your-visual-studio-build-output-to-11/) to at least Detailed and examine the output. I suspect some other error is actually what is causing the issue.

**Comment by JeffRockatansky** [comment]
@Keboo 
Packages folder is empty huh. But it's present in the same folder as solution :D 
Output has a big scary wall of text. Didn't find anything useful yet.

**Comment by Keboo** [comment]
If you expand the references in MapAppsDragablzDemo (the project showing the errors in your screenshot) does it show that all of the references have resolved?

Should look like this (no little yellow triangles on any of the references).

![image](https://user-images.githubusercontent.com/952248/30875639-fdc7290a-a2a8-11e7-8e87-5a353b61aaa5.png)

**Comment by JeffRockatansky** [comment]
![materialdesignxamltoolkit_demo_references](https://user-images.githubusercontent.com/26058495/30876298-a0faa528-a30f-11e7-9ee5-215c660f30b7.png)
How to fix "yellow triangles" of Dragablz and MahApps.Metro? (Is it actually Dragon Ball Z reference?)

**Comment by Keboo** [comment]
If you are not wanting to use the MahApps/Dragablz stuff, no you don't need and can simply unload it.

**Comment by JeffRockatansky** [comment]
Ok
TY and sorry :D

**Comment by JeffRockatansky** [comment]
So, if I need Dragablz features to look at in demo, I need to clone Dragablz, compile it and add it's .dll in References of this Material wpf demo?

**Comment by JeffRockatansky** [comment]
And what if I need them both in my own project, but not the Metro one?

**Comment by JeffRockatansky** [comment]
Tried to add 3 different .DLL's for each of Dragablz and MahApps.Metro for Material + Dragablz Demo. Ones from "Package" folder, others - from masters of sources compiled on my PC. Tried 40 and 45 versions. "Build successful" every time, but it crashes with error or in debug enters Break point state.

**Comment by ButchersBoy** [comment]
You should never need to recompile anything.  

Ideally you should start new projects and add any combination of Material Design, Dragablz, MahApps, via _nuget_.

As for the demo.  I have just retested.  Downloaded a clean .zip (normally I do a "git clone" from cmd line).  Opened in VS2017, compiled, ran.  All references were OK, project ran fine.  You _will_ see some errors in the designer.  That is VS.  But ignore these for now; the project should run.

**Comment by Aycom366** [comment]
i downloaded the material design themes just now for my vs 2017 and on loading the project, i got 
 these errors 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.	MaterialDesignColors.Wpf.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	112	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\kenny folder\Setups\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\paket.exe" restore" exited with code 1.	MaterialDesignThemes.Wpf.Tests	C:\kenny folder\Setups\MaterialDesignInXamlToolkit-master\MaterialDesignInXamlToolkit-master\.paket\Paket.Restore.targets	171	

and  also, some material design themes choose not to load...always writting load failed

Am using VS 2017, .net core 2.1

**Comment by Keboo** [comment]
@Aycom366 see https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Compiling-From-Source
You will need VS2019 and .NET Core 3.1 to compile from source.

**Comment by mey1k** [comment]
I can't run MahAppsDragablzDemo
it occurs System.Windows.Baml2006.TypeConverterMarkupExtension Exception
