### ISSUE TITLE
[WPF Demo project] Some XAML windows and pages are not visible in VS 2017 Design window with exeption. 

### ISSUE THREAD

**Issue by JeffRockatansky** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#807]
![image](https://user-images.githubusercontent.com/26058495/30958264-074dc494-a456-11e7-8579-b966fcf42831.png)
Demo still compiles well and works, but I cannot access Design view of some MaterialDesignDemo pages and windows. Visual Studio throws exception and errors. But xaml files themselves have some complex layouts without errors, only this thing -  ResourceDictionary Source="longass link"/ with blue waving line.
![image](https://user-images.githubusercontent.com/26058495/30959097-957a4998-a458-11e7-8cea-0fc8555b4416.png)
On hover it says "Value cannot be null. Parameter name: item"
Also some errors. 
![image](https://user-images.githubusercontent.com/26058495/30958850-cb7a8b76-a457-11e7-9a2a-f6c1ee9ed1cb.png)

Home.xaml throws "Invalid markup. Check the Error List for more information." in Design view.

Is it common behavior and should be like that? Or there are some potential fixes?

**Comment by wongjiahau** [comment]
@JeffRockatansky It is common, I had this issue as well, but I'm not really dependent on the Visual Studio Designers, so I'm fine with it.

**Comment by JeffRockatansky** [comment]
But is it going to be fixed any time soon?

**Comment by Keboo** [comment]
@JeffRockatansky currently I don't think anyone is working on it, but PRs are always welcome. 

If anyone is interested in tackling this, I suspect the problem will boil down to some code in a control's constructor that should not be run at design time. You can do a check using:
```C#
if (System.ComponentModel.DesignerProperties.GetIsInDesignMode(this))
{
    //Design mode specific code
}
else
{
    //Code that should not be run in design mode here
}
```

**Comment by JeffRockatansky** [comment]
Some people think it could be Visual Studio's fault or "quality".

**Comment by Keboo** [comment]
@JeffRockatansky that is certainly part of the issue. The VS designer has several known flaws. However, I don't think this specific case is one of them (though I have not spent much time looking into it, so I could be wrong).

**Comment by issam1975** [comment]
yes the xaml designer have some serious issues .

the good news is that MS is working on it :)
https://blogs.msdn.microsoft.com/visualstudio/2017/09/11/a-significant-update-to-the-xaml-designer/

the bad news is that it's only for UWP not WPF for the moment :(  

the other good news is that xaml designer for WPF will be fixed as well after UWP one is good . :)

everything is in the blog post ... and comments :p.
