### ISSUE TITLE
The idea to extend the style of the ripple effect as in Windows 10

### ISSUE THREAD

**Issue by ORRNY66** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#810]
I really like your work. I like to use your Material Design.
I got the idea to extend the style of the ripple effect. Something similar to Windows 10 Fluent Design , see the picture

![gif](https://user-images.githubusercontent.com/5471789/31059481-4b6da9d2-a703-11e7-8730-5b9b30c7ae9c.gif)

**Comment by Keboo** [comment]
Currently no. the intent is to stick as close to google's Material Design spec. The fluent design is an alternate paradigm people can adopt as they se fit.
