### ISSUE TITLE
ComboBoxes don't support IsReadOnly

### ISSUE THREAD

**Issue by aalex675** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#822]
ComboBox styles do not seem to support IsReadOnly or IsEnabled. When these properties are set the user is able to interact with the controls normally. The issue can be seen in the Material Design demo, by adding either of these properties to the "OS" combobox:
```
        <TextBlock Grid.Row="1" Grid.Column="2" VerticalAlignment="Center" Margin="16 0 8 0">OS</TextBlock>
        <ComboBox Grid.Row="1" Grid.Column="3" materialDesign:HintAssist.Hint="OS" IsReadOnly="True">
            <ComboBoxItem>Android</ComboBoxItem>
            <ComboBoxItem>iOS</ComboBoxItem>
            <ComboBoxItem>Linux</ComboBoxItem>
            <ComboBoxItem>Windows</ComboBoxItem>
        </ComboBox>
```

The control will still allow the user to edit the selection.

**Comment by llifon** [comment]
I've tried this out and I don't see any issues. Unless you can provide a repository, I think you're misunderstanding how `IsReadOnly` works; that is... it only works alongside `IsEditable`. Here is a great link to the API that shows a matrix for these two properties:
https://msdn.microsoft.com/en-us/library/system.windows.controls.combobox.isreadonly(v=vs.110).aspx

As for `IsEnabled`, the style works as it should:
![IsEnabled = false](https://i.gyazo.com/898aa3ee6ecad126a37fda9df1eb8f07.png7)

**Comment by Keboo** [comment]
Closing as this appears to be working as designed.
