### ISSUE TITLE
Timepicker bug with 24h format

### ISSUE THREAD

**Issue by ghost** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#826]
Hi, 

we found a problem with the timepicker in 24h format. 

We use two timepickers in our wpf control. If we change the value for one of them the wrong time format for the other is set. You can see this in your expample application, too as it's shown in this video:
https://giant.gfycat.com/UnsungOldArgusfish.webm

Is there a workaround for it?

**Comment by Keboo** [comment]
Fixed by #992
