### ISSUE TITLE
Circular Progress Bar Rotate Animation "Bug"

### ISSUE THREAD

**Issue by axd2201** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#827]
As i promised here is a example project to demonstrate the animation bug i promised and discussed with with James Willock on gitter chat.

Repository link:
https://github.com/axd2201/MaterialDesignXAMLProgressBarAnimationBug

Feel free to edit the title or anything on this issue

**Comment by Keboo** [comment]
Hi @axd2201 can you explain the animation problem that you are seeing?

Here is the behavior that I am seeing when I run the sample.
![example](https://user-images.githubusercontent.com/952248/31783255-7bd2ad04-b4b2-11e7-917b-a9f49b4d62db.gif)

To summarize:
While `IsIntermediate="True"` the circular progress bar animates and spins.
While `IsIntermediate="False"` the circular progress stops animating and displays the value as a portion of the circle. The starting and ending position of the section of circle that are displayed, do adjust exactly which portion of the circle are displayed, but it does not continue spinning. If you stop your timer at any value you will see that it is not animating.

**Comment by axd2201** [comment]
Shouldnt the progress bar move like this ?

https://i.imgur.com/240klwa.png
(Paint skillz too good)

Instead of that "Intermediate" animation it does while increasing the bar ?

**Comment by Keboo** [comment]
I don't think so. Take a look at the determinate Circular demo [here](https://material.io/guidelines/components/progress-activity.html)

**Comment by axd2201** [comment]
Well i didn't know the original material design circular progress bar animation with value looked like that, IMO it doesn't serve its purpose of showing the progress, you cant "guess" how much % it is, i would rather prefer the "static" way i tried yo show you with my paint skillz, if you could kindly send me the namespace where the style of the circular progress bar is on the project so i could make a Pull Request or make my own little modified version if the pull request doesn't get accepted, i would be very happy.

Thank you for your time and answering me

**Comment by Keboo** [comment]
Sure, the current circular style is [here](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ProgressBar.xaml#L126-L243). 
I suspect what you want to do it look at what the `LargeArcConverter` and `ArcEndPointConverter` are doing. 
Certainly open a PR with a second circular progress bar style that has a template that behaves the way you expect. Then we can see what other think about it.

**Comment by axd2201** [comment]
@Keboo I got what i wanted and it works better than i expected, but the XAML code is a little bit of a mess and i dont know where to fix it as i am not familiar with the project but i hope it is a easy fix for you guys, i commented where i changed it and added TODOs

Gif Example:
https://streamable.com/vwnwt

PR Link:
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/pull/829

**Comment by Keboo** [comment]
Fixed by #829
