### ISSUE TITLE
Combine DatePicker and TimePicker in single popup

### ISSUE THREAD

**Issue by peererror** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#830]
HI all, 
Is there a way to combine  DatePicker and Timepicker in same popup from there user can select date and time together and press ok or cancel  

![datetime](https://user-images.githubusercontent.com/12954109/31931965-54e5d53a-b8be-11e7-8131-f04294fc3052.png)

**Comment by Keboo** [comment]
Hi @peererror yes this is certainly possible. The Calendar and Clock controls can be put together like any other controls to achieve the look that you want. What you want to do is simply build up a view that contains both a Calendar control and a Clock control. 

Using the [demo application as a starting point](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Pickers.xaml#L59-L76), you can do something like this:

```XAML
<Button Margin="8 0 0 0" Content="..." 
              Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}"
              materialDesign:DialogHost.DialogOpenedAttached="CalendarDialogOpenedEventHandler"
              materialDesign:DialogHost.DialogClosingAttached="CalendarDialogClosingEventHandler">
    <Button.CommandParameter>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="Auto" />
            </Grid.ColumnDefinitions>
            <Border Background="{DynamicResource PrimaryHueMidBrush}" Grid.ColumnSpan="2" Grid.Column="0" Grid.Row="0" VerticalAlignment="Top" />
            <Calendar x:Name="Calendar" Margin="-1 34 -1 0" Grid.Column="0" Grid.Row="0"/>
            <materialDesign:Clock DisplayAutomation="Cycle" x:Name="Clock2" Grid.Column="1" Grid.Row="0"/>
            <StackPanel Grid.Row="1" Margin="8" HorizontalAlignment="Right" Orientation="Horizontal" Grid.Column="0" Grid.ColumnSpan="2">
                <Button Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" CommandParameter="1" Style="{DynamicResource MaterialDesignFlatButton}">OK</Button>
                <Button Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}" CommandParameter="0" Style="{DynamicResource MaterialDesignFlatButton}">CANCEL</Button>
            </StackPanel>
        </Grid>
    </Button.CommandParameter>
</Button>
```

**Comment by peererror** [comment]
@Keboo  this solves the issues ..

**Comment by jasoncurley** [comment]
Hi @Keboo, I tried putting a Clock and Calendar together as above but there is a weird issue with it. If you select a date on the calendar, you have to click the clock before it responds to input again. So after you select the date, you have to click the clock twice to select the time. When the dialog first appears, and also after clicking the clock, there's no problem with it. I've tried in many different contexts, so it should be easy enough to reproduce.

**Comment by jasoncurley** [comment]
Found the problem. It's because the WPF Calendar control hogs the mouse capture:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/b4413872-59d0-4a06-9d20-8d21de126dc6/calendar-not-losing-focus-wpf-40?forum=wpf&prof=required

If anyone else finds this my solution was to add event handlers for SelectedDatesChanged and DisplayModeChanged for the Calendar and call Mouse.Capture(null).

**Comment by Keboo** [comment]
@jasoncurley good find. From your comment, can this issue now be closed?

**Comment by jasoncurley** [comment]
Since it's not an issue with the MaterialDesign toolkit, I would say yes,
