### ISSUE TITLE
Unable to run demo project with VS2015

### ISSUE THREAD

**Issue by sarul84** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#832]
Hi,
I downloaded code from Git and try to run it using VS2015 but it is throwing lot of error. Do I need any other version?

**Comment by Insire** [comment]
it says in the [readme](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit#-source-code)

> To load the source project you will need Visual Studio 2017. Don't worry if you have an earlier version, you can still use the compiled assemblies from NuGet (Install-Package MaterialDesignThemes). There are two demo projects in the solution, restore the NuGet packages and fire them both up. One is a "pure" Material Design project, the other illustrates how to combine with Dragablz & MahApps.

**Comment by wongjiahau** [comment]
@sarul84 Please use Visual Studio 2017, I faced the same error last time when I used VS 2015, the main problem is due to the usage of C#7.0 syntax which is unsupported in VS2015.

**Comment by Keboo** [comment]
As per docs this project always requires latest VS
