### ISSUE TITLE
Menu shadow missing in windows server with classic theme

### ISSUE THREAD

**Issue by Tonghua-Li** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#839]
.net framework 4.5.2

![image](https://user-images.githubusercontent.com/1747556/32612198-ab4cc77a-c535-11e7-8047-280dff59226a.png)

the margin=4 fixed this issue in materialdesigninxamltoolkit\materialdesignthemes.wpf\themes\materialdesigntheme.menu.xaml

`<Border x:Name="SubMenuBorder"
                                    Margin="4"
                                    Background="{Binding Path=Background, RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=MenuBase}}"
                                    Effect="{DynamicResource MaterialDesignShadowDepth1}"
                                    CornerRadius="2">`
![image](https://user-images.githubusercontent.com/1747556/32613471-fd07f208-c538-11e7-908b-522d216334ec.png)

**Comment by MichelMichels** [comment]
Could I fix this without touching the existing source code? I have the same issue on a windows server 2016.

**Comment by Keboo** [comment]
This is not something that can be fixed within this library if the window's setting for disabling shadows is turned off. https://www.msftnext.com/disable-window-shadows-windows-10/
