### ISSUE TITLE
codebehind problem

### ISSUE THREAD

**Issue by ghost** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#842]
hey 
while I'm writing a code-behind to add a control to the main grid like this
`        private void Button_MouseDoubleClick(object sender, MouseButtonEventArgs e)`
        `{`
            `Button gr = new Button() { Height = 50, Width = 100 };`
            `Random rn = new Random();`
           ` gr.Margin = new Thickness(rn.Next(0, 100), rn.Next(0, 100), rn.Next(0, 100), rn.Next(0, 100));`
            `blabla.Children.Add(gr);`
       ` }`

the program stops in this line ` Button gr = new Button() { Height = 50, Width = 100 };` after executing it 
and doesn't finish executing the rest of the method but the UI still responsive

**Comment by Keboo** [comment]
I am afraid I cannot reproduce this issue. Can you please provide a small sample project that reproduces the issue?

**Comment by Keboo** [comment]
Closing for now due to inactivity. If there is still an issue please re-open with details.
