### ISSUE TITLE
DialogHost Dialog shown outside of form

### ISSUE THREAD

**Issue by Symbai** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#846]
Showing a dialog while the form (dialoghost) is in background/minimized causes the dlalog to be displayed on the screen like a standalone window.

To reproduce you need to trigger a dialog while your form is in background, possibly via timer.
Expected result would be the dialoghost form either gets focused / brought back from background, or the dialog appears in dialoghost form but not shown on screen.

**Comment by Keboo** [comment]
This appears to be a bug. The DialogHost [watches the parent Windows activation events](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/DialogHost.cs#L684-L701) and attempts to hide/show the dialog based on those. 
It seems that the best fix for this is for similar logic to be applied to the dialog [before it is shown](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/DialogHost.cs#L239).
