### ISSUE TITLE
DatePicker visual state of blackout dates not set correctly

### ISSUE THREAD

**Issue by aakashc31** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#854]
Hi,

Following is a description of a bug I hit.

**Bug**: Visual state of blacked out dates in DatePicker do not refresh correctly.

**Minimalistic Repo** link for reproducing the bug - [https://github.com/aakashc31/DatePickerMaterialDesign](url)
It just sets the startDate, endDate and BlackoutDates in the datepicker object. 

**Repro steps**
1. Run the app, and open the calendar from date picker. You'll see 4,5 and 16th November are not available for selection and their color is disabled (lower opacity?)
2. Now navigate to October, and then back to November. The disabled color is gone, all dates in November look the same. Although they're not available for selection, you'll have to hover over them to understand that they're blacked out. 

Thanks,
Aakash

**Comment by Keboo** [comment]
Fixed in the latest 4.2.1 release
