### ISSUE TITLE
Warning using a card with a progress bar

### ISSUE THREAD

**Issue by topcatarg** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#856]
You can see the problem at https://github.com/topcatarg/warningonmaterialdesign.

After pushing the button, the view will render the card with the bar progress. A warning if showed on the output windows:

System.Windows.Media.Animation Warning: 6 : 'TestWarning.exe' (CLR v4.0.30319: TestWarning.exe): 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_es_31bf3856ad364e35\PresentationFramework.resources.dll' cargado. El módulo se compiló sin símbolos.
Unable to perform action because the specified Storyboard was never applied to this object for interactive control.; Action='Remove'; Storyboard='System.Windows.Media.Animation.Storyboard'; Storyboard.HashCode='10750772'; Storyboard.Type='System.Windows.Media.Animation.Storyboard'; TargetElement='System.Windows.Controls.ProgressBar Minimum:0 Maximum:100 Value:50'; TargetElement.HashCode='31700771'; TargetElement.Type='System.Windows.Controls.ProgressBar'

This is only a warning, the "programs" continue to work without problem.

**Comment by lamposu** [comment]
I met the same issue in visual studio **professional** 2017(2), but not happen in visual studio **Community** 2017

**Comment by greuelpirat** [comment]
I get the same warning spaming debug output. Would be nice if this could be fixed.
