### ISSUE TITLE
Is the stepper component on the roadmap?

### ISSUE THREAD

**Issue by ver0nikadataformers** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#863]
Link: https://material.io/guidelines/components/steppers.html

Is there any plan to include a stepper into one of the upcomming releases?

**Comment by stealthcold** [comment]
I'm not sure, but @spiegelp  extended this library with a Stepper implementation: https://github.com/spiegelp/MaterialDesignExtensions

**Comment by ver0nikadataformers** [comment]
thank you very much for the hint - I'll have a look!

**Comment by spiegelp** [comment]
@ver0nikadataformers  Hi, the Stepper in [https://github.com/spiegelp/MaterialDesignExtensions](https://github.com/spiegelp/MaterialDesignExtensions) is a complex version heavily using MVVM to provide data validation hooks. It would crash the scope of this library. The Stepper in this project is a simple implementation based on TabControl and does not provide these features. Therefore it is easier to use .

**Comment by ver0nikadataformers** [comment]
I already saw that upon review. And for my project I only need the simple stepper tabcontrol - but thank you very much for your answer!

**Comment by AmitBhatnagar24** [comment]
@spiegelp 

> **The Stepper in this project** is a simple implementation based on TabControl and does not provide these features. Therefore it is easier to use .

Where is the stepper in this (MDIX) project?

**Comment by Keboo** [comment]
Closing for now, this is provided by the Material Design Extensions library.
