### ISSUE TITLE
Feature request. Control colors specided by Dark or Light thems.

### ISSUE THREAD

**Issue by Vick-edit** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#864]
I have a lot of charts in my project, Most charts have color with transparency that must be sensitive ot light/dark theme. I have ot use some workaround to convert stored theme's brushes to colors for creating new brushes with transparency level.

If there were base colors in addition to brushes - it would be very useful.
[MaterialDesignTheme.Dark.xaml](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Dark.xaml#L5)

Or here we can add ability to swap users own dark/ligh them brushes
[PaletteHelper.cs](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/PaletteHelper.cs#L15-L41)

If it corresponds to your ideas about how your library should work, I could add this functionality.

**Comment by Keboo** [comment]
Resolved by #923
