### ISSUE TITLE
TransitioningContent OpeningEffect

### ISSUE THREAD

**Issue by LazyCuteLion** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#865]
I  have 2 pages:
page1,page2
page1 has child "TransitioningContent" ,and the OpeningEffect work's well when applaction loaded,
when page1=>page2 and page2=>page1,the "OpeningEffect" does not work!

 the "MaterialDesignDemo" app ,"Transitions" tab ,last example.
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Transitions.xaml
the same problem:
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/441

**Comment by Keboo** [comment]
Closing as a duplicate of #441
