### ISSUE TITLE
DialogHost : IndexOutOfRangeException

### ISSUE THREAD

**Issue by NothingFaceX** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#871]
Hi , I'm working with dialoghost and I get this error everytime even in MaterialDesign Demo : IndexOutOfRangeException: Index was outside the bounds of the array.
Is that a bug ? I use VS2017 and win 10

**Comment by ButchersBoy** [comment]
Hi, how do I reproduce this in the demo?
