### ISSUE TITLE
DialogHost Loaded Event

### ISSUE THREAD

**Issue by Volker123** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#875]
Hello,

if the Loaded event of a DialogHost element is fired multiple times, the element shows up in the LoadedInstances Container of that element multiple times, leading to a 'Multiple viable DialogHost' error.

As a fix, the OnLoaded method can be extended as follows:

```
        private bool FirstLoadEvent = true;

        private void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
        {
            if (FirstLoadEvent)
            {
                FirstLoadEvent = false;
                LoadedInstances.Add(this);
            }
        }
```

**Comment by Keboo** [comment]
Fixed by #2440
