### ISSUE TITLE
Implementation Snackbar in MVVM

### ISSUE THREAD

**Issue by wojtekPortugal** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#878]
Hello I have a problem with implementation Snackbar? I mean implementation that respects MVVM. Not code behind style like in this project. I tried all I know but still without success. I want achieve same function like in your project but not with code behind. Does it exist some solution how to do that? I checked WIKI https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Snackbar but description is not clear. At least not for me.  Thank you for your reponse

**Comment by JohnJosuaPaderon** [comment]
Create a MessageQueue property in your ViewModel, then bind to MessageQueue property of Snackbar in your View.

**Comment by Keboo** [comment]
@wojtekPortugal you can also see an example [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/SnackBar/Snackbar.MVVM)
