### ISSUE TITLE
ButtonProgressAssist.IsIndicatorVisible - progress still slightly visible after toggling False -> True -> False

### ISSUE THREAD

**Issue by bebenins** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#881]
When the app initializes, the progress indicator is not visible by default (set to False).... All good.
But when you toggle `IsIndicatorVisible` False -> True -> False then it tries to be invisible but you can still see like half a pixel of rotating progress circle.

This code is basically copy/paste from demo with exception of binding IsIndicatorVisible.
```
<Button Style="{StaticResource MaterialDesignFloatingActionAccentButton}" Click="ButtonStart_Click"
                    materialDesign:ButtonProgressAssist.IsIndeterminate="True"
                    materialDesign:ButtonProgressAssist.IsIndicatorVisible="{Binding IsProcessing}"
                    materialDesign:ButtonProgressAssist.Value="-1">
</Button>
```

**Comment by bebenins** [comment]
![example](https://user-images.githubusercontent.com/16761301/35062295-d634c34c-fb91-11e7-93cd-c63b7d73f637.gif)

**Comment by KaizerT** [comment]
Any updates on this? I'm currently experiencing it

**Comment by sanke** [comment]
Seems that MaterialDesignFloatingActionMiniButton styles ProgressBar does not have binding for visibility  https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/980ff7bd7f0d8ac56d15b944c41a677db8bf630f/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L220-L234
It should also contain:
`Visibility="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=(wpf:ButtonProgressAssist.IsIndicatorVisible), Converter={StaticResource BooleanToVisibilityConverter}}"`
