### ISSUE TITLE
Clock / Date picker possibly using incorrect palette when used in dialog

### ISSUE THREAD

**Issue by BrendanReilly** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#888]
When using the time picker overlay inside of an open dialog, the minute and hour numbers seem to be still using the foreground colour of base palette (rather than dark foreground text inherited from the dialog).

**Comment by Xaalek** [comment]
Is it still relevant ?
If this is the case, please provide us some xaml so that we can test
