### ISSUE TITLE
Animation Issues

### ISSUE THREAD

**Issue by Nziner** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#890]
Good afternoon. Are there any system requirements for animations?
In particular, the dependence on DirectX and video card drivers is of interest.

My problem is that when testing the application on different machines the program was launched on Windows 10, 8.1, 7. **But on the one machine** where Windows 7 is installed, the frame rate is very low, about the same if you set `Timeline.DesiredFrameRateProperty.OverrideMetadata (typeof (Timeline), new FrameworkPropertyMetadata {DefaultValue = 5});`

**I attached information about the system.**
Perhaps there are no drivers on the video card. The thing is, I can not install them, because I can not install them. A computer with limited rights, but it would be desirable to be compatible with the largest number of computers.
[DxDiag-userPC.txt](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/files/1668674/DxDiag-userPC.txt)

**Animations that lag:**
- click on the button
- typing text in the textbox
- opening modal/popup window
- progress bar
- etc

_P.S. Sorry for my bad English. And thanks for help!_

**Comment by ahausmann** [comment]
According to the diagnostics file there is a) no graphics driver installed and b) the monitor is being detected as 1Hz (instead of 60Hz).
