### ISSUE TITLE
Not able to run this. I opened this MaterialDesignToolkit.Wpf solution file. as i built the project it gave about 100s of error. Could anyone help me with this. Thanks.

### ISSUE THREAD

**Issue by anshu4590** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#891]
# PLEASE READ BEFORE POSTING AN ISSUE

# This is a place for issues.  Questions are better asked in the Gitter chat room.

# Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. 

My time is limited and .Zip files, code snippets and partial examples are often a time sink.  GitHub also provides great communication and code review tools which can be utilised.

# HOW TO POST A GOOD SAMPLE.  Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc.  If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages".  If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward.  I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

**Comment by anshu4590** [comment]
This is first time i am using git. i guess just already told my whole issue in heading section.

**Comment by Keboo** [comment]
Are you using VS2017. The codes uses some of the new C# 7 syntax and will not compile with older versions of Visual Studio. See [this wiki](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Visual-Studio-Versions-&-.Net-4.0-Compatibility#visual-studio-versions) for more details

**Comment by anshu4590** [comment]
i guess that's the solution. I updated my framework and got half of the errors resolved. Anyhow there are still 60-65 error that i m trying to resolve.
Thanks budd for solution.

**Comment by Keboo** [comment]
@anshu4590 what are the errors your are seeing? I use the solution constantly, it should be compiling without any errors.

**Comment by anshu4590** [comment]
![capture](https://user-images.githubusercontent.com/20014094/36141423-a71c4e38-10ca-11e8-9d44-000018c12096.PNG)

**Comment by anshu4590** [comment]
![capture](https://user-images.githubusercontent.com/20014094/36141517-fc370480-10ca-11e8-9c04-6dc6dddfd47a.PNG)

**Comment by punker76** [comment]
@anshu4590 Do you really use VS 2017?

**Comment by Allough** [comment]
@anshu4590 Try opening a **fresh** copy of the solution with VS 2017. If you opened it in an older version first, then "updated" it to 2017, you can run into a lot of errors like this.

**Comment by punker76** [comment]
@anshu4590 Any news???

**Comment by anshu4590** [comment]
I m not using VS 2017. i m using VS 2015. Anyhow i have latest framework, so it should work. I got it working by creating a new separate project and implementing and creating the same class files and other files. Anyway thanks for support and suggestions.

**Comment by anshu4590** [comment]
Is that so? Actually i can't update VS because i m working and its my company's system. So i have to live with that. Anyhow i get it working on VS2015. I can upload on drive and share link if you want or even anybody else have VS2015 wants that.
Thanks for help buddy.

**Comment by jespersh** [comment]
I *think* you can update Roslyn in 2015 to use C#7 features, but you'll still get intellisense error (red swiggly lines)
