### ISSUE TITLE
Highlight Default button

### ISSUE THREAD

**Issue by cmeeren** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#900]
Currently, a window's default button (the one activated by pressing Enter anywhere) is not highlighted in any way. This is contrary to the default Windows/WPF style, where the default button is clearly indicated - as you can see below, the text box has focus, and the Ok button is highlighted since that's the one activated by Enter:

![image](https://user-images.githubusercontent.com/7766733/36355559-5a9f69f4-14e5-11e8-8da7-49356e4bb6a3.png)

I would like for default buttons to be indicated in some way in the Material Design in XAML Toolkit. An example of how to do it is to go to [this Material-UI demo page](http://www.material-ui.com/#/components/flat-button) and tab onto the first (flat) button - it then looks like this:

![image](https://user-images.githubusercontent.com/7766733/36355535-16e32070-14e5-11e8-82cb-0ae436bc674b.png)

(It then animates on hover as opposed to just filling with color, as it does when it doesn't have focus.)

Could this be a good way to style default flat buttons?

Also see [this UX Stack Exchange question I asked about this](https://ux.stackexchange.com/q/115950/112286).

**Comment by MichelMichels** [comment]
In my applications I differentiate by using a different style. For example a flat style for cancel buttons and an outlined style for buttons I think the user will likely use in that scenario.

I'll close this issue as I don't see anyone implementing anything like this soon, but feel free to submit a PR!
