### ISSUE TITLE
RatingBar rate command

### ISSUE THREAD

**Issue by olegsavelos** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#907]
RatingBar is missing a command that should be called once rating changed.
I understand that we could use two way binding to get rating once value changed but that would be problematic in cases when you need to call an asynchronous or long running code.

**Comment by jespersh** [comment]
You couldn't achieve the same by doing the command in the property setting with Execute?

**Comment by olegsavelos** [comment]
Yes of course but it would be anti pattern.
Ideally if command is attached to control it should be checked if command can execute and only then call execute method and set rating value.
This would follow the usual workflow of wpf controls.

**Comment by Keboo** [comment]
There is now a SelectRatingCommand as well as a ValueChanged event that can be used to accomplish this

**Comment by bayarmanlai** [comment]
hi @Keboo , Can you provide a piece of code for how to use SelectRatingCommand?

**Comment by Keboo** [comment]
@bayarmanlai sure, here is one. https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/RatingBar/RatingBar.SelectRatingCommand
