### ISSUE TITLE
Need Info : A clear Wiki about creating a dialog with custom content

### ISSUE THREAD

**Issue by Amine-Smahi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#914]
I followed the MaterialDesign Xam Toolkit Wiki page about the dialogs, but i still can't understand anything
* Where put the code ?
* What is the code to write ?

**Comment by Tide** [comment]
Look here https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Dialogs

Then download the source for this project and look at how the demo shows dialogs.

**Comment by Amine-Smahi** [comment]
I did @Tide, it's still not clear, i even don't know where to add the code

**Comment by Insire** [comment]
The dialog system is very flexible, so there is no *one* way to deal with this. You can check the demo app from this repo for some ideas, but in the end you have to pick and choose an approach that fits into your app. MDIXT does not force you to use one particular way.

I have a pet project of my own, where i leverage the dialog system myself, so if you want, i can link that to you.

**Comment by Keboo** [comment]
@Amine-Smahi as @Insire said it is a pretty flexible control that lets you use it several different ways.
There are really two main concepts with it:
1. The DialogHost is a control that needs to wrap all of the controls that you want the popup dialog to sit on top of. Typically this means placing it near the root of your Window.
2. The DialogContent property contains the contents of the popup dialog.

You can see one simple example [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.Example). You can also look at the code in the demo application [XAML](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Dialogs.xaml), and [Code behind](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/blob/master/MainDemo.Wpf/Dialogs.xaml.cs)

**Comment by marvac** [comment]
For anyone still wandering around trying to get this to work, the easiest way is by using the code-behind approach. If your project calls for a different paradigm, you'll have to use one of the outlined examples in the mentioned link.

First, wrap a `DialogHost` control around the content you want to gray out/disable. Let's just say that it's going to be the entire window:

```
<Window x:Class=...
        xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
        ...>
    <materialDesign:DialogHost x:Name="MainDialogHost">
        <Grid>
            <!-- Window contents here -->
        </Grid>
    </materialDesign:DialogHost>
</Window>
```

Now go create a new UserControl and call it something like `OkCancelDialog`. This dialog will just have some text and an OK and CANCEL button:

```
<UserControl x:Class=...
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             ...>
    <StackPanel Margin="16">
        <TextBlock Text="Save Changes?" HorizontalAlignment="Center" FontSize="16" />

        <StackPanel HorizontalAlignment="Center" Orientation="Horizontal" Margin="8">
            <Button Command="materialDesign:DialogHost.CloseDialogCommand"
                    IsCancel="True"
                    Content="CANCEL"
                    Style="{StaticResource MaterialDesignFlatButton}">
                <Button.CommandParameter>
                    <system:Boolean xmlns:system="clr-namespace:System;assembly=mscorlib">False</system:Boolean>
                </Button.CommandParameter>
            </Button>

            <Button Command="materialDesign:DialogHost.CloseDialogCommand"
                    IsDefault="True"
                    Content="OK"
                    Style="{StaticResource MaterialDesignRaisedButton}">
                <Button.CommandParameter>
                    <system:Boolean xmlns:system="clr-namespace:System;assembly=mscorlib">True</system:Boolean>
                </Button.CommandParameter>
            </Button>
        </StackPanel>
    </StackPanel>
</UserControl>
```

and then we can call this dialog from code-behind, but you need to make sure your method is `async` so we can await the return value of the dialog:

```
private async void DoSomething(object sender, RoutedEventArgs e)
{
    var saveResult = (bool)await DialogHost.Show(new OkCancelDialog(), "MainDialogHost");
    if (saveResult)
    {
        //OK button was pressed
    }
}
```

This is just a simple example. In reality, you would likely pass a viewmodel to the dialog, use bindings to set the message and button text, and add a callback for the `DialogClosing` event, but this should at least get you started.

**Comment by Keboo** [comment]
@marvac great example. I have been putting together small examples of using MDIX [here](https://github.com/Keboo/MaterialDesignInXaml.Examples). Would you be interested in submitting a PR with your example(s)?

**Comment by bebenins** [comment]
Nice thanks!
Would also be nice to see an example on how to await on a different thread (not Main thread).  I mean, you get  "The calling thread must be STA, because many UI components require this." exception and I'm not sure how to route this dialog popup to Main thread.
Thanks!

**Comment by marvac** [comment]
@Keboo I'll submit a PR later today
@bebenins I'll look into that, but it may be a problem for another day

**Comment by Keboo** [comment]
New [blog post](https://intellitect.com/material-design-in-xaml-dialog-host/) on using the DialogHost
