### ISSUE TITLE
Show Error Message in Textbox

### ISSUE THREAD

**Issue by gwynn-1** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#917]
I have a Textbox that I just want user's input is numeric, I use Validation Rule then I custom ErrorTemplate but I can't show any message in Template. This is my Textbox:
`<TextBox Margin="100,20,100,0"`
`                     x:Name="txbSDT"`
`                     FontSize="14"`
`                     FontFamily="/CoffeeHome;component/CoffeeHomeFont/#Roboto"`
`                     materialDesign:HintAssist.Hint="Số điện thoại"`
`                     Style="{StaticResource MaterialDesignFloatingHintTextBox}"`
`                     Validation.ErrorTemplate="{StaticResource textBoxErrorTemplate}">`
`                <TextBox.Text>`
`                    <Binding Path="Staff.Sdt" UpdateSourceTrigger="PropertyChanged">`
`                        <Binding.ValidationRules>`
`                            <validation:NumericValidation PropertyName="Số điện thoại" `                                     `ValidatesOnTargetUpdated="True"/>`
 `                       </Binding.ValidationRules>`
`                    </Binding>`
`                </TextBox.Text>`
`            </TextBox>`

And this is my ErrorTemplate:
`<ControlTemplate x:Key="textBoxErrorTemplate">`
`                <StackPanel>`
`                    <Border BorderBrush="Red" BorderThickness="1">`
`                        <AdornedElementPlaceholder Name="a" />`
`                    </Border>`
 `                   <TextBlock Foreground="Red" Text="{Binding [0].ErrorContent}"/>`
`                </StackPanel>`
`            </ControlTemplate>`

In the preview of Visual Studio I can still see the message but when I build and test the message doesn't show. I can't understand, is it because of the default of Material Design ? If someone can help me out, I will very grateful

**Comment by quicoli** [comment]
Hello

The default material design template for textbox already has a error
template... You don't need supply one.

Maybe what is missing is validateondataerrors = true in your binding

**Comment by supernhok13** [comment]
Yeah !! I've already tried that but it's not working. :(
And how to use the default material design template for error ?? I want my textbox has a error message below it whenever validation fail, but I haven't found any solution.

**Comment by supernhok13** [comment]
Thank you guys for helping me !! I finally fixed the bug. Actually I just need to wrap textbox in AdornedDecorator so the ErrorTemplate could render. How silly I am :)

**Comment by Keboo** [comment]
@supernhok13 Excellent. I assume this issue can be closed now?

**Comment by MichelMichels** [comment]
Closed due to inactivity
