### ISSUE TITLE
I wanna button background set to transparent in treeview.

### ISSUE THREAD

**Issue by PlumpMath** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#920]
no transparent button.
I wanna button background set to transparent in treeview.

Thanks~*;

**Comment by PlumpMath** [comment]
solve: 
https://stackoverflow.com/questions/17814308/treeview-shows-blue-for-selected-item

**Comment by MichelMichels** [comment]
Closed due to inactivity.
