### ISSUE TITLE
Binding-Error with ListBoxItem style

### ISSUE THREAD

**Issue by Symxn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#922]
Hello,

there is a issue with the properties "HorizontalContentAlignment" and "VerticalContentAlignment" in conjunction with the ListBoxItem style. This is the error message which is shown in the Output-Window:

![error](https://user-images.githubusercontent.com/37656980/37765209-e7f77dc2-2dc3-11e8-95da-20a83ca22aca.png)

This error occurs if the ItemsSource of the ListBox is binded to a ObservableCollection an their elements change.
The error message is not displayed when I do the following:

`            <Style TargetType="{x:Type ListBoxItem}"
                   BasedOn="{StaticResource {x:Type ListBoxItem}}">
                <Setter Property="HorizontalContentAlignment"
                        Value="Left" />
                <Setter Property="VerticalContentAlignment"
                        Value="Top" />
            </Style>`

But that is not a good solution.
I hope that this bug will be corrected. Thanks! :)

Sorry for my bad English. :D

**Comment by TysonMN** [comment]
Here are the two error messages as text.
```
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'ListViewItem' (Name=''); target property is 'VerticalContentAlignment' (type 'VerticalAlignment')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'ListViewItem' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
```

**Comment by TysonMN** [comment]
These relative bindings are defined on lines 31 and 32
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/d75bac11b6d25ad34c78e416b26727344da8c487/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ListBox.xaml#L27-L32

**Comment by TysonMN** [comment]
Here is a [GitHub repository containing a minimal working example](https://github.com/TysonMN/MaterialDesignInXamlToolkit_922).  Any time an item is removed, the two binding warnings are displayed in the "Output" window of Visual Studio.

**Comment by Keboo** [comment]
Uploading sample project for historical reference.
[MaterialDesignInXamlToolkit_922-main.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5405991/MaterialDesignInXamlToolkit_922-main.zip)

**Comment by TysonMN** [comment]
I think I have a fix too.  I will continue working on this tomorrow.

**Comment by TysonMN** [comment]
PR #2142 fixes this issue.  In the meantime, here is a workaround that anyone can use right now.  It combines the fix in the PR with the way to [override default styles set by MDinXAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/wiki/Overriding-Default-Styles).

```xaml
<Style BasedOn="{StaticResource MaterialDesignListBox}" TargetType="{x:Type ListBox}">
  <Setter Property="ItemContainerStyle" Value="{StaticResource MaterialDesignListBoxItem}" />
</Style>
```

**Comment by TysonMN** [comment]
> Uploading sample project for historical reference.
> [MaterialDesignInXamlToolkit_922-main.zip](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/files/5405991/MaterialDesignInXamlToolkit_922-main.zip)

I was planning on attaching a ZIP after I thought this issue is resolved (and I delete that repo).  I thought you prefered a GitHub repo like that over an attached ZIP since the [new issue template](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/issues/new) says
> Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem. 
>
> My time is limited and .Zip files, code snippets and partial examples are often a time sink.  GitHub also provides great communication and code review tools which can be utilised.
> ...
> Post a full GitHub repository. Not a zip file, half baked snippet etc. ...

Sorry for not also attaching a ZIP of the MWE.
