### ISSUE TITLE
TextBox RightToLeft FlowDirection

### ISSUE THREAD

**Issue by nclwgn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#924]
The TextBox with the property `FlowDirection="RightToLeft"` won't respond properly to text inputs:

* When writing a normal text with common alphanumeric characters, all works well:
![image](https://user-images.githubusercontent.com/37672436/37794306-e6a8c080-2def-11e8-8ea1-b80d2495407a.png)

* However, when inserting special characters the order goes wrong:
![image](https://user-images.githubusercontent.com/37672436/37794434-30faf932-2df0-11e8-911a-7e809992315d.png)

![image](https://user-images.githubusercontent.com/37672436/37794464-4fa4232c-2df0-11e8-8c93-5495a29cf835.png)

![image](https://user-images.githubusercontent.com/37672436/37794528-7dd5d61e-2df0-11e8-92fd-3cf60f048273.png)

* Finally, an error occurs when moving the pointer with the arrows in the keyboard.

![image](https://user-images.githubusercontent.com/37672436/37794591-ace53f8a-2df0-11e8-9620-0e4a61b18f90.png)

![image](https://user-images.githubusercontent.com/37672436/37794626-cb8fcdba-2df0-11e8-96f0-aec262eab5d8.png)

This `TextBox` in the XAML code is represented by the following code:
```cs
                <TextBox x:Name="NewUserNameTextBox"
                         HorizontalAlignment="Left"
                         Height="25"
                         Margin="87,62,0,0"
                         TextWrapping="Wrap"
                         Text="{Binding NewUserNameTextBox.Text}"
                         IsEnabled="{Binding NewUserNameTextBox.IsEnabled}"
                         VerticalAlignment="Top"
                         Width="151"
                         FlowDirection="RightToLeft" />
```

Thanks in advance for the great open-source project! Hope my explanation helped

**Comment by ahmedflix25** [comment]
i think what you are looking for is HorizontalContentAlignment and not the FlowDirection

`<TextBox x:Name="NewUserNameTextBox"
                         HorizontalAlignment="Left"
                         Height="25"
                         Margin="87,62,0,0"
                         TextWrapping="Wrap"
                         Text="{Binding NewUserNameTextBox.Text}"
                         IsEnabled="{Binding NewUserNameTextBox.IsEnabled}"
                         VerticalAlignment="Top"
                         Width="151"
                         HorizontalContentAlignment="Right" />`
