### ISSUE TITLE
NuGet Installation

### ISSUE THREAD

**Issue by HekMe** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#935]
Hey,
i've received this error at the end of installation sequence

Install-Package : Could not install package 'MaterialDesignColors 1.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.
0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author
.
At line:1 char:1
+ Install-Package MaterialDesignThemes
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Is it just my problem?

**Comment by redbaty** [comment]
Hmm welp, this should be pretty self explanatory, I think the minimum requirement for MaterialDesignColors 1.1.2 is .NET Framework 4.5, is there something else going on that I'm missing?

**Comment by Keboo** [comment]
Hi @HekMe 
@redbaty is correct. There is no official support for projects targeting .NET 4.0. There is an older branch that you could build from source. More details on the [wiki here](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Visual-Studio-Versions-&-.Net-4.0-Compatibility).
