### ISSUE TITLE
TimePicker always show 24 hours - it is not possible to limit hours range

### ISSUE THREAD

**Issue by bermanguy** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#940]
It is not possible to limit the displayed hours range in TimePicker as it is possible to do in DatePicker.
In DatePicker, there are 2 properties to limit time range - DisplayDateStart & DisplayDateEnd.
TimePicker should support same functionality.

**Comment by Keboo** [comment]
@bermanguy this should be resolved by #1207.
There are several properties you can play with to change the way the time picker is displaying. Language will control the time format specifier (usually `:`) and the AM/PM designators (in some culture this will simply be an empty string). The `SelectedTimeFormat` will indicate if it should be a short or long time format (typically whether you want to see a leading 0 or not). The `Is24Hours` will force it to use a 24 hour clock. The `WithSeconds` will determine if it displays seconds as well.

Let me know if this does not resolve your request.
