### ISSUE TITLE
 Selected items are not highlighted

### ISSUE THREAD

**Issue by baikimi** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#943]
![dti 1hnl 1g xj2 u_q n](https://user-images.githubusercontent.com/17607439/39615099-d1f4aefa-4fa6-11e8-933b-e06faca42446.png)

**Comment by Leojet86** [comment]
I have the same issue. 
[https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/issues/385]

**Comment by Leojet86** [comment]
Are you using MVVMLight?

When I create a blank WPF project, and test the DatePicker it works. 
but if I do the same in a blank MVVMLight WPF451, it doesn't.

**Comment by Xaalek** [comment]
Can't reproduce. Please open a new issue if you still have the problem.
