### ISSUE TITLE
Close a Dialog

### ISSUE THREAD

**Issue by ghost** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#944]
i have this code:

        <materialDesign:DialogHost DialogClosing="Sample2_DialogHost_OnDialogClosing">
            <Button  materialDesign:DialogHost.DialogClosingAttached="Sample2_DialogHost_OnDialogClosing"
		          Content="Login"  Command="{Binding RunExtendedDialogCommand}"
	                  IsEnabled="True" x:Name="btnLogin"
	                  Margin="80,359,82,259" 	materialDesign:ShadowAssist.ShadowDepth="Depth1"  Click="btnLogin_Click" HorizontalAlignment="Center"  Width="328" Height="Auto">

                <Button.CommandParameter>
                    <StackPanel Margin="16">
                        <ProgressBar Style="{DynamicResource MaterialDesignCircularProgressBar}" HorizontalAlignment="Center" Margin="16" IsIndeterminate="True" Value="0" />
                        <Button x:Name="assadas" Style="{StaticResource MaterialDesignFlatButton}" IsCancel="True" 
                                            Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}"
                                            CommandParameter="Sample2Cancel"
                                            HorizontalAlignment="Center">CANCEL</Button>
                    </StackPanel>
                </Button.CommandParameter>
            </Button>
        </materialDesign:DialogHost>

how i can close this with code in C#?

**Comment by jespersh** [comment]
Of the top of my head.. Attach to DialogOpen(ing) and you can "save" the `Session` (look at the event args to find it).
You can then call `Session.Close();`

**Comment by MichelMichels** [comment]
Closed due to inactivity.
