### ISSUE TITLE
PopupBox cannot open reliably when nested in two TabControls

### ISSUE THREAD

**Issue by philius44** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#945]
Created a github Repo to reproduce this, you can find it here: https://github.com/philius44/PopupInTabControl.git

Steps to Reproduce:
"Header" TabItem - "test" TabItem is preselected when running the App, a PopupBox Floating Action Button is shown.
hover over PopupBox -> opens as Expected
Select "Header" -> "test2" -> hover - >opens as Expected
Select "Header1" -> "test" -> hover - >opens as Expected
Select "Header1" -> "test2" -> hover - >opens as Expected
Select "Header" -> "test2" -> hover - >opens as Expected
Select "Header" -> "test -> hover -> PopupBox shows animation but does not open.

**Comment by braca** [comment]
I have the same issue, @philius44 did you find a way to fix it?

**Comment by Keboo** [comment]
@philius44 thank you for the bug report and repro project.

**Comment by Keboo** [comment]
@philius44 or @braca this should be fixed in the laster 2.5.1.-ci1273 (or later) release. Let me know if there are still issues.
