### ISSUE TITLE
Card has double Margin (Bug?)

### ISSUE THREAD

**Issue by Symxn** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#947]
Hello!

If I apply margin on a card, it also gets a padding with the same value.
Is this the case or a bug?

![card - margin](https://user-images.githubusercontent.com/37656980/39626467-46df7eb6-4fa2-11e8-906c-4c428590c9ef.png)

Thank you for your help!

**Comment by Keboo** [comment]
Looks like a bug to me. Will submit a PR shortly.
