### ISSUE TITLE
Overriding style not working,why?

### ISSUE THREAD

**Issue by BuildSoftwareBetter** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#956]
i use the same key **MaterialDesignRaisedButton** override the Button style,like this : 
`<Style x:Key="MaterialDesignRaisedButton" BasedOn="{StaticResource MaterialDesignRaisedButton}" TargetType="ButtonBase">
        <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
    </Style>`
I have merged this into App.xaml,but not working,and i am not find other use the same method to override the style,who can show me the demo?

I want to use the method like **[Overriding Default Styles](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/wiki/Overriding-Default-Styles)** section in **Wiki**,what should I do?

**Comment by Streissi** [comment]
if you want to set `Property="FocusVisualStyle"` to all buttons you have to write an application wide style like this: `<Style BasedOn="{StaticResource MaterialDesignRaisedButton}" TargetType="Button">
                <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
            </Style>` but if you only apply no focus visual style to some buttons use a different `x:Key` than the MaterialDesignXamlToolkit uses like: `<Style x:Key="MyButton" BasedOn="{StaticResource MaterialDesignRaisedButton}" TargetType="ButtonBase">
                <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
            </Style>`

**Comment by Streissi** [comment]
did you merged the overrided style in the application resources in your app.xaml?

**Comment by Streissi** [comment]
hi @BuildSoftwareBetter i testet the overriding default styles and it works great. seems there is a little typo or something in your app.xaml to merge the two styles
