### ISSUE TITLE
Setting HorizontalContentAlignment to Right/Center on a MaterialDesignFloatingHintTextBox leads to shifting Hint during text entry

### ISSUE THREAD

**Issue by MCBTay** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#963]
Below is a short example illustrating the issue.  As long as your Text is shorter than your Hint, all is well.  But when your Text exceeds your Hint, the Hint begins shifting to stay with the start of the text.  I've also provided a screenshot.

![image](https://user-images.githubusercontent.com/952248/171213674-a6a5b8c7-891c-4bb4-bc3c-a102217d1b98.png)

```
<TextBox 
	Style="{StaticResource MaterialDesignFloatingHintTextBox}"
	materialDesign:HintAssist.Hint="Some Hint Text"
	HorizontalContentAlignment="Right"
	Text="Short" />

<TextBox 
	Style="{StaticResource MaterialDesignFloatingHintTextBox}"
	materialDesign:HintAssist.Hint="Some Hint Text"
	HorizontalContentAlignment="Right"
	Text="Longer, more verbose text" />
```

**Comment by Xaalek** [comment]
I think you should use `FlowDirection="RightToLeft"` instead of `HorizontalContentAlignment="Right"`.

![image](https://user-images.githubusercontent.com/54487782/170842717-651c126a-ce81-443c-ae67-124be2475670.png)

Is this what you are looking for?
