### ISSUE TITLE
Multi selection combobox

### ISSUE THREAD

**Issue by Rainson12** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#965]
First of all thank you for this great project. It is really awesome! I am trying to build a multi select combobox. Sadly I really struggle with it. What I have done is, copying the styles from the combobox and added a datatemplate with a checkbox for the combobox and some attached properties to save the SelectedItemS. For whatever reason i can not get the Hint stuff working with the custom combobox. Is there any plan to integrate multi selection into the combobox?

**Comment by Keboo** [comment]
Hi @Rainson12 
Sorry for the long delay but no, there are currently no plans for this is not default functionality for the combobox. 
The two possible solutions for this. First do something with the item template (which it sounds like you did), the second option would be to build something using the PopupBox control.

**Comment by aristen** [comment]
Hey @Rainson12 
Did you ever get your multi select to work ? 
We are currently trying to implement the same component and ran into the same issues with the SmartHint.

@Keboo could you expand on the two possibilities you mentioned and point us in the right direction ? We are not the greatest wpf/xaml developers so any help would be greatly appreciated :)

**Comment by Rainson12** [comment]
@aristen yea i got it working - part of. It works good enough that you can use it. This is the code:


`<UserControl x:Class="Controls.MultiSelectComboBox.MultiSelectComboBox"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:Indivumed.HRM.Controls.MultiSelectComboBox"
             xmlns:materialDesign="http://materialdesigninxaml.net/winfx/xaml/themes"
             xmlns:converters="clr-namespace:MaterialDesignThemes.Wpf.Converters;assembly=MaterialDesignThemes.Wpf"
             xmlns:valueConverters="clr-namespace:Indivumed.HRM.ValueConverters"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">

    <ComboBox
        x:Name="MultiSelectCombo"  
        SnapsToDevicePixels="True"
        OverridesDefaultStyle="True"                
        
        ScrollViewer.HorizontalScrollBarVisibility="Auto"
        materialDesign:HintAssist.IsFloating="True"
        PreviewKeyDown="MultiSelectCombo_OnPreviewKeyDown"
        ScrollViewer.VerticalScrollBarVisibility="Auto"
        Text="{Binding Path=Text,RelativeSource={RelativeSource Mode=FindAncestor, AncestorType=UserControl}}"
        ScrollViewer.CanContentScroll="True" SelectionChanged="MultiSelectCombo_SelectionChanged">
        <ComboBox.ItemContainerStyle>
            <Style  TargetType="{x:Type ComboBoxItem}">
                <Setter Property="SnapsToDevicePixels" Value="True" />
                <Setter Property="Margin" Value="0" />
                <Setter Property="HorizontalContentAlignment" Value="{Binding HorizontalContentAlignment, RelativeSource={RelativeSource AncestorType={x:Type ItemsControl}}}" />
                <Setter Property="VerticalContentAlignment" Value="{Binding VerticalContentAlignment, RelativeSource={RelativeSource AncestorType={x:Type ItemsControl}}}" />
                <Setter Property="Background" Value="Transparent" />
                <Setter Property="BorderBrush" Value="Transparent" />
                <Setter Property="BorderThickness" Value="0" />
                <Setter Property="FocusVisualStyle" Value="{StaticResource FocusVisual}" />
                <Setter Property="Template" Value="{StaticResource MaterialDesignComboBoxItemTemplate}" />
            </Style>
            
        </ComboBox.ItemContainerStyle>
        <ComboBox.ItemTemplate>
            <DataTemplate>
                <CheckBox Content="{Binding Title}"
                          IsChecked="{Binding Path=IsSelected, Mode=TwoWay}"
                          Click="CheckBox_Click"  Padding="16 8" />
            </DataTemplate>
        </ComboBox.ItemTemplate>
        <ComboBox.Template>
            <ControlTemplate TargetType="{x:Type ComboBox}">
                <Grid x:Name="templateRoot"
              Background="{TemplateBinding Background}"
              SnapsToDevicePixels="True">
                    <Grid x:Name="InnerRoot">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*" />
                            <ColumnDefinition Width="0" MinWidth="{DynamicResource {x:Static SystemParameters.VerticalScrollBarWidthKey}}" />
                        </Grid.ColumnDefinitions>
                        <ToggleButton x:Name="toggleButton"
                              Grid.ColumnSpan="2"
                              Background="{TemplateBinding Background}"
                              BorderBrush="{TemplateBinding BorderBrush}"
                              BorderThickness="{TemplateBinding BorderThickness}"
                              IsChecked="{Binding IsDropDownOpen, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}}"
                              Style="{StaticResource MaterialDesignComboBoxToggleButton}"/>
                        <Grid HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                      VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                      Margin="{TemplateBinding Padding}"
                      SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"
                      UseLayoutRounding="{TemplateBinding UseLayoutRounding}">
                            <Grid x:Name="InputRoot"
                          HorizontalAlignment="Left">
                                <ContentPresenter x:Name="contentPresenter"
                                                  Content="{Binding Path=Text, RelativeSource={RelativeSource TemplatedParent}}"
                                                  ContentStringFormat="{TemplateBinding SelectionBoxItemStringFormat}"
                                                  ContentTemplate="{TemplateBinding SelectionBoxItemTemplate}"
                                                  ContentTemplateSelector="{TemplateBinding ItemTemplateSelector}"
                                                  IsHitTestVisible="False"/>
                                
                                <TextBox x:Name="PART_EditableTextBox"
                                 IsReadOnly="{Binding IsReadOnly, RelativeSource={RelativeSource TemplatedParent}}"
                                 HorizontalAlignment="Left"
                                 HorizontalContentAlignment="Stretch"
                                 Style="{StaticResource MaterialDesignComboBoxEditableTextBox}"
                                 CaretBrush="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=BorderBrush}"                                 
                                 Visibility="Collapsed" />
                                
                                <materialDesign:SmartHint x:Name="Hint"                                             
                                       HintProxy="{Binding RelativeSource={RelativeSource TemplatedParent}, Converter={x:Static converters:HintProxyFabricConverter.Instance}}"                                       
                                       FontSize="{TemplateBinding FontSize}"
                                       SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"
                                       UseLayoutRounding="{TemplateBinding UseLayoutRounding}"
                                       UseFloating="{Binding Path=(materialDesign:HintAssist.IsFloating), RelativeSource={RelativeSource TemplatedParent}}"
                                       HintOpacity="{Binding Path=(materialDesign:HintAssist.HintOpacity), RelativeSource={RelativeSource TemplatedParent}}"                                                          
                                       Hint="{TemplateBinding materialDesign:HintAssist.Hint}" />
                            </Grid>
                        </Grid>
                        <Line x:Name="DashedLine" Grid.ColumnSpan="2" VerticalAlignment="Bottom"
                      Visibility="{Binding Path=IsEnabled, RelativeSource={RelativeSource Self}, Converter={StaticResource InverseBoolToVisConverter}}"
                      StrokeThickness="1.25" StrokeDashArray="1,2.5" StrokeDashCap="Round"
                      X1="0" X2="{Binding ActualWidth, ElementName=toggleButton}" Y1="0" Y2="0" 
                      Stroke="{TemplateBinding BorderBrush}" Opacity="0.56" />
                        <materialDesign:Underline x:Name="Underline"
                               Grid.ColumnSpan="2"
                               IsActive="{Binding ElementName=PART_EditableTextBox, Path=IsKeyboardFocused}"
                               Visibility="{Binding Path=(materialDesign:TextFieldAssist.DecorationVisibility), RelativeSource={RelativeSource TemplatedParent}}"/>

                        <materialDesign:ComboBoxPopup x:Name="PART_Popup"
                                   
                                   AllowsTransparency="true"
                                   Focusable="False"
                                   HorizontalOffset="-11.5"
                                   IsOpen="{Binding IsDropDownOpen, Mode=TwoWay, RelativeSource={RelativeSource TemplatedParent}}"
                                   PlacementTarget="{Binding ElementName=templateRoot}"
                                   SnapsToDevicePixels="True"
                                   UseLayoutRounding="True"
                                   Placement="Custom"
                                   PopupAnimation="Fade"
                                   VerticalOffset="0"
                                   DefaultVerticalOffset="5"
                                   DownVerticalOffset="-15.5"
                                   UpVerticalOffset="15"
                                   ClassicMode="{Binding Path=(materialDesign:ComboBoxAssist.ClassicMode), RelativeSource={RelativeSource TemplatedParent}}"
                                   UpContentTemplate="{StaticResource PopupContentUpTemplate}"
                                   DownContentTemplate="{StaticResource PopupContentDownTemplate}"
                                   ClassicContentTemplate="{StaticResource PopupContentClassicTemplate}">
                            <ContentControl>
                                <ScrollViewer MaxHeight="{TemplateBinding MaxDropDownHeight}"
                                      Background="{Binding Background, ElementName=PART_Popup}">
                                    <ItemsPresenter x:Name="ItemsPresenter" KeyboardNavigation.DirectionalNavigation="Contained" Margin="10" />
                                </ScrollViewer>
                            </ContentControl>
                        </materialDesign:ComboBoxPopup>
                    </Grid>
                </Grid>
                <ControlTemplate.Triggers>
                    <Trigger SourceName="PART_Popup" Property="PopupPlacement" Value="{x:Static materialDesign:ComboBoxPopupPlacement.Classic}">
                        <Setter Property="ItemContainerStyle" Value="{StaticResource MaterialDesignComboBoxItemStyle}" />
                    </Trigger>
                    <Trigger SourceName="PART_Popup" Property="IsOpen" Value="True">
                        <Setter Property="Background" TargetName="templateRoot" Value="{Binding Background, ElementName=PART_Popup}" />
                    </Trigger>
                    <Trigger Property="IsEnabled" Value="False">
                        <Setter TargetName="templateRoot" Property="Opacity" Value="0.56"/>
                        <Setter TargetName="toggleButton" Property="BorderBrush" Value="Transparent"/>
                    </Trigger>
                    <Trigger Property="IsEditable" Value="True">
                        <Setter TargetName="PART_EditableTextBox" Property="Visibility" Value="Visible" />
                        <Setter TargetName="Underline" Property="Visibility" Value="{Binding Path=(materialDesign:TextFieldAssist.DecorationVisibility), RelativeSource={RelativeSource TemplatedParent}}" />
                        <Setter TargetName="contentPresenter" Property="Visibility" Value="Collapsed" />
                    </Trigger>
                    <Trigger Property="materialDesign:HintAssist.IsFloating" Value="True">
                        <Setter TargetName="InnerRoot" Property="Margin" Value="0 11.5 0 0" />
                    </Trigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition Property="IsEditable" Value="False"/>
                            <Condition Property="IsDropDownOpen" Value="True"/>
                        </MultiTrigger.Conditions>
                        <Setter TargetName="Underline" Property="Visibility" Value="Hidden"/>
                        <Setter TargetName="toggleButton" Property="BorderBrush" Value="Transparent"/>
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition SourceName="Hint" Property="IsContentNullOrEmpty" Value="False" />
                            <Condition Property="materialDesign:HintAssist.IsFloating" Value="True" />
                            <Condition Property="IsKeyboardFocusWithin" Value="True" />
                        </MultiTrigger.Conditions>
                        <Setter TargetName="Hint" Property="Foreground" Value="{DynamicResource PrimaryHueMidBrush}" />
                        <Setter TargetName="Hint" Property="HintOpacity" Value="1" />
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition Property="materialDesign:HintAssist.IsFloating" Value="True" />
                            <Condition SourceName="Hint" Property="IsHintInFloatingPosition" Value="True" />
                            <Condition Property="IsKeyboardFocusWithin" Value="True" />
                        </MultiTrigger.Conditions>
                        <Setter TargetName="Hint" Property="Foreground" Value="{DynamicResource PrimaryHueMidBrush}" />
                        <Setter TargetName="Hint" Property="HintOpacity" Value="1" />
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition SourceName="Hint" Property="IsContentNullOrEmpty" Value="False" />
                            <Condition SourceName="PART_EditableTextBox" Property="IsKeyboardFocused" Value="True" />
                        </MultiTrigger.Conditions>
                        <Setter TargetName="Hint" Property="Foreground" Value="{DynamicResource PrimaryHueMidBrush}" />
                        <Setter TargetName="Hint" Property="HintOpacity" Value="1" />
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition SourceName="Hint" Property="IsContentNullOrEmpty" Value="False" />
                            <Condition Property="IsDropDownOpen" Value="True" />
                        </MultiTrigger.Conditions>
                        <Setter TargetName="Hint" Property="Foreground" Value="{DynamicResource PrimaryHueMidBrush}" />
                        <Setter TargetName="Hint" Property="HintOpacity" Value="1" />
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition Property="IsGrouping" Value="true" />
                            <Condition Property="VirtualizingPanel.IsVirtualizingWhenGrouping" Value="false" />
                        </MultiTrigger.Conditions>
                        <Setter Property="ScrollViewer.CanContentScroll" Value="false" />
                    </MultiTrigger>
                    <Trigger Property="IsKeyboardFocused" Value="true">
                        <Setter TargetName="Underline" Property="IsActive" Value="True"/>
                    </Trigger>
                    <Trigger Property="Validation.HasError" Value="true">
                        <Setter Property="BorderBrush" Value="{DynamicResource ValidationErrorBrush}"/>
                        <Setter TargetName="Underline" Property="Background" Value="{DynamicResource ValidationErrorBrush}"/>
                    </Trigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition Property="IsMouseOver" Value="true" />
                            <Condition Property="Validation.HasError" Value="true" />
                        </MultiTrigger.Conditions>
                        <Setter Property="BorderBrush" Value="{DynamicResource ValidationErrorBrush}"/>
                        <Setter TargetName="Underline" Property="Background" Value="{DynamicResource ValidationErrorBrush}"/>
                    </MultiTrigger>
                    <MultiTrigger>
                        <MultiTrigger.Conditions>
                            <Condition Property="IsMouseOver" Value="true" />
                            <Condition Property="Validation.HasError" Value="false" />
                        </MultiTrigger.Conditions>
                        <Setter Property="BorderBrush" Value="{DynamicResource PrimaryHueMidBrush}"/>
                        <Setter TargetName="Underline" Property="Background" Value="{DynamicResource PrimaryHueMidBrush}"/>
                    </MultiTrigger>
                </ControlTemplate.Triggers>
            </ControlTemplate>
            
        </ComboBox.Template>
    </ComboBox>
</UserControl>
`


.cs class:
`/// <summary>
    /// Interaction logic for MultiSelectComboBox.xaml
    /// </summary>
    public partial class MultiSelectComboBox : UserControl
    {

        private ObservableCollection<Node> _nodeList;
        public MultiSelectComboBox()
        {
            InitializeComponent();
            _nodeList = new ObservableCollection<Node>();
            Items = new ObservableCollection<MultiSelectComboBoxItem>();
            Items.CollectionChanged += Items_CollectionChanged;
        }

        private void Items_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
        {
            OnItemsSourceChanged(this, new DependencyPropertyChangedEventArgs(ItemsProperty, e.OldItems, e.NewItems));
        }

        #region Dependency Properties

        public static readonly DependencyProperty ItemsSourceProperty =
             DependencyProperty.Register("ItemsSource", typeof(IList), typeof(MultiSelectComboBox), new FrameworkPropertyMetadata(null,
        new PropertyChangedCallback(MultiSelectComboBox.OnItemsSourceChanged)));

        public static readonly DependencyProperty SelectedItemsProperty =
         DependencyProperty.Register("SelectedItems", typeof(IList), typeof(MultiSelectComboBox), new FrameworkPropertyMetadata(null,
     new PropertyChangedCallback(MultiSelectComboBox.OnSelectedItemsChanged)));

        public static readonly DependencyProperty TextProperty =
           DependencyProperty.Register("Text", typeof(string), typeof(MultiSelectComboBox), new UIPropertyMetadata(string.Empty, new PropertyChangedCallback(MultiSelectComboBox.OnTextChanged)));


        public ObservableCollection<MultiSelectComboBoxItem> Items
        {
            get { return (ObservableCollection<MultiSelectComboBoxItem>)GetValue(ItemsProperty); }
            set { SetValue(ItemsProperty, value); }
        }
        public static readonly DependencyProperty ItemsProperty =
            DependencyProperty.Register("ItemsProperty", typeof(ObservableCollection<MultiSelectComboBoxItem>), typeof(MultiSelectComboBox), new UIPropertyMetadata(null));


        public static readonly DependencyProperty SelectedValuePathProperty = DependencyProperty.Register("SelectedValuePath", typeof(string), typeof(MultiSelectComboBox), new UIPropertyMetadata(string.Empty));
        public static readonly DependencyProperty DisplayMemberPathProperty = DependencyProperty.Register("DisplayMemberPath", typeof(string), typeof(MultiSelectComboBox), new UIPropertyMetadata(string.Empty));


        public ICommand Command
        {
            get { return (ICommand)GetValue(CommandProperty); }
            set { SetValue(CommandProperty, value); }
        }

        public static readonly DependencyProperty CommandProperty = DependencyProperty.Register(
            "Command",
            typeof(ICommand),
            typeof(MultiSelectComboBox),
            new PropertyMetadata(null, OnCommandPropertyChanged));

        private static void OnCommandPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            MultiSelectComboBox control = d as MultiSelectComboBox;
            if (control == null) return;

        }

        public IList ItemsSource
        {
            get
            {
                var items = (IList)GetValue(ItemsProperty);
                if (items != null && items.Count > 0)
                    return items;
                var itemSource = (IList)GetValue(ItemsSourceProperty);
                return itemSource;
            }
            set
            {
                SetValue(ItemsSourceProperty, value);
            }
        }

        public IList SelectedItems
        {
            get { return (IList)GetValue(SelectedItemsProperty); }
            set
            {
                SetValue(SelectedItemsProperty, value);
            }
        }

        public string Text
        {
            get
            {
                return (string)GetValue(TextProperty);
            }
            set
            {
                SetValue(TextProperty, value);
            }
        }

        public string SelectedValuePath
        {
            get { return (string)GetValue(SelectedValuePathProperty); }
            set { SetValue(SelectedValuePathProperty, value); }
        }

        public string DisplayMemberPath
        {
            get { return (string)GetValue(DisplayMemberPathProperty); }
            set { SetValue(DisplayMemberPathProperty, value); }
        }
        #endregion

        #region Events
        private static void OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            MultiSelectComboBox control = (MultiSelectComboBox)d;
            control.DisplayInControl();
        }

        private static void OnSelectedItemsChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            MultiSelectComboBox control = (MultiSelectComboBox)d;

            control.SelectNodes();
            control.SetText();
        }
        private static void OnTextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {

            //var test = SelectedItems;
            MultiSelectComboBox control = (MultiSelectComboBox)d;
            if (control.SelectedItems != null)
            {

                StringBuilder displayText = new StringBuilder();
                foreach (Node s in control._nodeList)
                {
                    if (s.IsSelected == true)
                    {
                        displayText.Append(s.Title);
                        displayText.Append(',');
                    }
                }
                var text = (displayText.ToString().TrimEnd(new char[] { ',' }));
                if (e.NewValue.ToString() != text)
                {
                    d.SetValue(TextProperty, text);
                }
            }
            //control.SelectNodes();
            //control.SetText();

        }

        private void CheckBox_Click(object sender, RoutedEventArgs e)
        {
            CheckBox clickedBox = (CheckBox)sender;

            int _selectedCount = 0;
            foreach (Node s in _nodeList)
            {
                if (s.IsSelected)
                    _selectedCount++;
            }
            //if (_selectedCount == _nodeList.Count - 1)
            //    _nodeList.FirstOrDefault(i => i.Title == "All").IsSelected = true;
            //else
            //    _nodeList.FirstOrDefault(i => i.Title == "All").IsSelected = false;
            SetSelectedItems();
            SetText();

        }
        #endregion


        #region Methods
        private void SelectNodes()
        {
            if (SelectedItems == null)
                return;
            foreach (var node in _nodeList)
            {
                node.IsSelected = SelectedItems.Cast<object>().Any(x => x.GetType().GetProperties().FirstOrDefault(y => y.Name == SelectedValuePath).GetValue(x)?.ToString() == node.Key);
            }
        }

        private void SetSelectedItems()
        {
            if (SelectedItems == null)
            {
                var listType = this.ItemsSource.GetType();


                var instance = Activator.CreateInstance(listType);
                //typeof()
                SelectedItems = (IList)instance;
            }

            SelectedItems.Clear();
            foreach (Node node in _nodeList)
            {
                if (node.IsSelected)
                {
                    if (this.ItemsSource.Count > 0)
                    {
                        var item = this.ItemsSource.Cast<object>().FirstOrDefault(x => x.GetType().GetProperties().FirstOrDefault(y => y.Name == SelectedValuePath).GetValue(x)?.ToString() == node.Key);
                        SelectedItems.Add(item);
                    }

                }
            }
            
            ICommand command = this.Command;

            if (command != null && command.CanExecute(null))
                command.Execute(SelectedItems);
        }

        private void DisplayInControl()
        {
            if (_nodeList != null && this.ItemsSource != null)
            {
                _nodeList.Clear();
                //if (this.ItemsSource.Count > 0)
                //    _nodeList.Add(new Node("All"));
                foreach (var keyValue in this.ItemsSource)
                {
                    var displayTextKey = keyValue.GetType().GetProperties().FirstOrDefault(x => x.Name == DisplayMemberPath);
                    var displayTextKeyValue = displayTextKey.GetValue(keyValue);

                    var idKey = keyValue.GetType().GetProperties().FirstOrDefault(x => x.Name == SelectedValuePath);
                    var idKeyValue = idKey.GetValue(keyValue);

                    Node node = new Node(idKeyValue?.ToString(), displayTextKeyValue?.ToString());
                    _nodeList.Add(node);
                }
                MultiSelectCombo.ItemsSource = _nodeList;
            }
        }

        private void SetText()
        {
            if (this.SelectedItems != null)
            {
                StringBuilder displayText = new StringBuilder();
                foreach (Node s in _nodeList)
                {
                    if (s.IsSelected == true)
                    {
                        displayText.Append(s.Title);
                        displayText.Append(',');
                    }
                }
                this.Text = displayText.ToString().TrimEnd(new char[] { ',' });
            }
        }


        #endregion

        private void MultiSelectCombo_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key != Key.Tab)
                e.Handled = true;
        }

        private async void MultiSelectCombo_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            ComboBox combo = (ComboBox)sender;
            if (combo.SelectedItem != null && combo.SelectedItem is Node node)
            {
                e.Handled = true;
                node.IsSelected = true;
                //combo.SelectedItem = null;
                SetSelectedItems();
                SetText();
                // var test = (combo.Parent as dynamic).Text;
                //Task.Run(() =>
                //{
                //    Task.Delay(100);
                //    SetText();
                //    combo.Text = "dasasda";
                //    var test = (combo.Parent as dynamic).Text;
                //});

                //this.Text = "test";
                //var test = combo.Text;
            }

        }
    }

    public class Node : INotifyPropertyChanged
    {

        private string _title, _key;
        private bool _isSelected;
        #region ctor
        public Node(string key, string title)
        {
            Title = title;
            Key = key;
        }
        #endregion

        #region Properties
        public string Key
        {
            get
            {
                return _key;
            }
            set
            {
                _key = value;
                NotifyPropertyChanged("Key");
            }
        }
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
                NotifyPropertyChanged("Title");
            }
        }
        public bool IsSelected
        {
            get
            {
                return _isSelected;
            }
            set
            {
                _isSelected = value;
                NotifyPropertyChanged("IsSelected");
            }
        }
        #endregion

        public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }

    }`

**Comment by aristen** [comment]
Hey @Rainson12 
I really appreciate it, i was starting to pull out my hair in pure frustration :)

I tried to c/p your solution but i seems like i am missing the `MultiSelectComboBoxItem` class. I assume this is a homebrewed object ? What does it hold ?

And again, thanks for the reply!

**Comment by Rainson12** [comment]
@aristen 
yea you were right. Its used in a project. Heres the data model and some usage example:

```
public class MultiSelectComboBoxItem
    {
        public string Key { get; set; }

        public string Value { get; set; }
    }
```



`<multiSelectComboBox:MultiSelectComboBox  Grid.Column="2" Grid.Row="27"  materialDesign:HintAssist.Hint="Department" SelectedValuePath="Id" DisplayMemberPath="Name" ItemsSource="{Binding Departments}" SelectedItems="{Binding SelectedEmployee.Departments}" Command="{Binding SelectedDepartmentChangedCommand}" />`

or with static data:


```
<multiSelectComboBox:MultiSelectComboBox materialDesign:HintAssist.Hint="WeeklyWorkingTime"  Margin="0 20 0 0"  SelectedValuePath="Key" DisplayMemberPath="Value" SelectedItems="{Binding FilterSettings.WeeklyWorkingTime}" >
                                    <multiSelectComboBox:MultiSelectComboBox.Items>
                                        <ControlModels:MultiSelectComboBoxItem Key="LessThan40" Value="&lt; 40"></ControlModels:MultiSelectComboBoxItem>
                                        <ControlModels:MultiSelectComboBoxItem Key="40" Value="40"></ControlModels:MultiSelectComboBoxItem>
                                    </multiSelectComboBox:MultiSelectComboBox.Items>
                                </multiSelectComboBox:MultiSelectComboBox>
```

**Comment by aristen** [comment]
Thanks! I got it to work :)

**Comment by thanhhaidev** [comment]
Hi @Rainson12 , @Keboo , @aristen , @henon 

When I dropdown and I select an element, I cannot check the checkbox, when I choose the 2nd time, I can check it. Is there any solution to this problem?

Tks!

**Comment by henon** [comment]
Yes. I think the problem here is that the mouse is captured. There is a way to fix it by explicitly releasing the mouse capture but I won't go investigating this. Maybe you can find it out yourself? Hope it helps.

**Comment by Insire** [comment]
Found this issue while trying to create a multi selectable combobox myself today and chose a different approach.

I tried to keep my code minimal, while keeping most of the code from this toolkit. If you are interested, i uploaded a working sample targetting .NET 7 [here](https://github.com/Insire/MDIX_ClearButtonCommand)

Key takeaways from my approach are, that 
- i subclassed the combobox, so that i can control the creation of the ItemContainer (i create ContentControls instead of ComboBoxItems)
- copied the ControlTemplate from the vanilla ComboBoxItem from this toolkit and adjusted a trigger condition
- used that Copy of the ControlTemplate as base of a new ControlTemplate for a ContentControl
- copied all StyleSetters from the ``MaterialDesignComboBoxItemStyle`` and used them as default for the Style of my ``ComboBox.ItemContainerStyle``
- Multi-Select-Logic has been implemeted via MVVM/ViewModels and CommunityToolkit.MVVM
