### ISSUE TITLE
Windows form host showing in Datagrid but not in DialogHost.

### ISSUE THREAD

**Issue by hemanthkrishna9** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#967]
When using this DLL [IPAddressControl`](https://www.nuget.org/packages/IPAddressControl/) is made for forms 
in WPF like

 `<TextBlock Style="{StaticResource MaterialDesignDisplay1TextBlock}" TextWrapping="Wrap" HorizontalAlignment="Center">Database servers</TextBlock>
            <WindowsFormsHost Width="120">
                <ipBox:IPAddressControl   />
            </WindowsFormsHost>`

It is showing correctly as 
![image](https://user-images.githubusercontent.com/17428404/41353824-f94d695c-6f3a-11e8-800b-e2e7866ec760.png)

But while the same element , If I am using in Dialoghost it is not showing. `   <Button  Command="{x:Static materialDesign:DialogHost.OpenDialogCommand}" Margin="0 20 0 0"
                            Width="140" HorizontalAlignment="Right">Add New Server
                        <Button.CommandParameter>
                            <StackPanel Margin="16">
                                <TextBlock>Add a new Server</TextBlock>
                                

                        
                        <StackPanel x:Name="ipStack">
                            <WindowsFormsHost Width="120">
                                <ipBox:IPAddressControl x:Name="IPAddresss"   />

                            </WindowsFormsHost>

                        </StackPanel>
                        <TextBox wpf:HintAssist.Hint="Notes" Style="{StaticResource MaterialDesignTextAreaTextBox}"                             
                           VerticalScrollBarVisibility="Auto"  Margin="0 15 0 0" FontSize="16" Grid.Row="2" MaxLength="500" Width="400"
                            VerticalAlignment="Top" Height="100" AcceptsReturn="True" TextWrapping="Wrap">
                            <TextBox.Text>
                                <Binding Path="Notes" UpdateSourceTrigger="PropertyChanged"> </Binding>
                            </TextBox.Text>
                        </TextBox>

                        <StackPanel Orientation="Horizontal" HorizontalAlignment="Right" >
                                    <Button Style="{StaticResource MaterialDesignFlatButton}" IsDefault="True"                                            
                                            Command="{Binding AddnewCommand}"> Add </Button>
                                    <Button Style="{StaticResource MaterialDesignFlatButton}" IsCancel="True" 
                                            Command="{x:Static materialDesign:DialogHost.CloseDialogCommand}">Cancel</Button>
                                </StackPanel>
                            </StackPanel>
                        </Button.CommandParameter>

                    </Button>`
![image](https://user-images.githubusercontent.com/17428404/41353880-1fc881d4-6f3b-11e8-871d-c734a7959fc0.png)
![image](https://user-images.githubusercontent.com/17428404/41353886-24a37ace-6f3b-11e8-9812-0033c02cd6ec.png)

**Comment by optivolveiqbal** [comment]
Hi, I also encounter the same issue here

**Comment by jespersh** [comment]
You'll need to add the ResourceDictionary inside the DialogHost if it isn't inside App.xaml.

**Comment by Keboo** [comment]
I suspect the problem is because you declare your UI elements inside of the Button.CommandParameter which then gets moved inside of a Popup control. I would suggest moving the XAML for the dialog outside of the Button.CommandParameter and instead declare them using DataTemplates. This will prevent the WindowFormsHost from being moved between different visual trees. 
You can see an example of this [here](https://github.com/Keboo/MaterialDesignInXaml.Examples/tree/master/DialogHost/DialogHost.FromViewModel)

**Comment by Pineapplemachinesystems** [comment]
I have the same problem. We need some help.

**Comment by MichelMichels** [comment]
See previous comment for fix.
