### ISSUE TITLE
Can't install on WPF for windows 10 IOT

### ISSUE THREAD

**Issue by RosiersRobin** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#969]
Hi,

I just ade a fresh Universal app with target version `Windows 10 Creators update (10.0; Build 15063)` and tried to install the `MaterialDesignThemes (Latest Stable 2.4.0.1044)` NuGet package. But that gives me the following error:

```
Package MaterialDesignColors 1.1.2 is not compatible with uap10.0.15063 (UAP,Version=v10.0.15063) / win10-x64. Package MaterialDesignColors 1.1.2 supports: net45 (.NETFramework,Version=v4.5)
```

How can I resolve that issue?

**Comment by TekuSP** [comment]
Did you try compiling it from Github? Like downloading sources and compiling them for your target platform?

**Comment by RosiersRobin** [comment]
Yes I tried that too, it doesn't work :(

**Comment by jespersh** [comment]
The IoT version of Windows 10 lets you target UWP, not WPF.
The "MaterialDesignColors" of the UWP package is embedded in MaterialDesignThemes.Uwp package: https://github.com/ButchersBoy/MaterialDesignInXamlToolkit/tree/master/MaterialDesignThemes.Uwp/Themes

**Comment by Keboo** [comment]
As @jespersh pointed out, this library only supports WPF not UWP.
