### ISSUE TITLE
No instances loaded DialogHost

### ISSUE THREAD

**Issue by TalagramKiri** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#970]
Hi
I want to display a dialog

this my code:

`
<UserControl x:Class="Wingram.Dialogs.Loading"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             mc:Ignorable="d" 
            >
    <ProgressBar Width="24" Height="24" Margin="16"
                 Style="{DynamicResource MaterialDesignCircularProgressBar}"
                 IsIndeterminate="True"
                 Value="33"/>
</UserControl>
     <ProgressBar Width="24" Height="24" Margin="16"
                 Style="{DynamicResource MaterialDesignCircularProgressBar}"
                 IsIndeterminate="True"
                 Value="33"/>
</UserControl>`

and this code for open dialog on click event a button

`      var view = new Loading { };
            var result = await DialogHost.Show(view);`

but this return error: No instances loaded DialogHost

please help me!

**Comment by jespersh** [comment]
Could you provide a tiny repo example? Your intentions are unclear

**Comment by Keboo** [comment]
Closing for now, unless there is more feedback. The likely issue is there are no DialogHost instances loaded in the UI.
