### ISSUE TITLE
Dialogs & ValidatesOnDataErrors

### ISSUE THREAD

**Issue by LiptonDev** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#971]
After opening several times in a row the dialogue stops working ValiditEnDataError, or rather disappears text under TextBox.

First open:
![first open](http://dl4.joxi.net/drive/2018/06/17/0004/2389/268629/29/63ae398afa.png)

Second open:
![second open](http://dl3.joxi.net/drive/2018/06/17/0004/2389/268629/29/f90501b7bb.png)

Sorry for my bad English.

**Comment by Xaalek** [comment]
I close the issue. Not enough information and the screenshots are no longer available
