### ISSUE TITLE
PackIcon on Button

### ISSUE THREAD

**Issue by Dragoneel009** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#972]
I have problem with material Pack Icon because when i use in on the buttons or any of objects may icon become half or not align center even i use the vertical and horizontal alignment or verticalcontent and horizontalcontent alignment.. Pack Icon size always small even i set it 64x64 
![wpf1](https://user-images.githubusercontent.com/39989412/41593984-75c17d1c-73f4-11e8-9a76-ce959c3f5aa1.png)

**Comment by o14547** [comment]
<materialDesign:PackIcon Kind="Gift">
                        <materialDesign:PackIcon.LayoutTransform>
                            <ScaleTransform CenterX="0.5" CenterY="0.5" ScaleX="2" ScaleY="2"/>
                        </materialDesign:PackIcon.LayoutTransform>
                    </materialDesign:PackIcon>

**Comment by lanmanck** [comment]
how to use icon and text on the same button?

**Comment by o14547** [comment]
> how to use icon and text on the same button?
        <Button Height="32" Width="96">
            <StackPanel Orientation="Horizontal">
                <materialDesign:PackIcon Kind="Gift"/>
                <TextBlock Text="text"/>
            </StackPanel>
        </Button>

**Comment by Keboo** [comment]
@Dragoneel009 can you please provide some code that replicates the issue.

**Comment by Keboo** [comment]
Closing for now. If anyone has reproduction steps please comment below.

**Comment by MatveyBykovsky** [comment]
@Keboo Hi! I'm not sure, but seems like I have the same issue. Please, let me know if somesthing is wrong from my side.
![image](https://github.com/user-attachments/assets/fd3d3e5e-89c8-45af-a12e-a966ec5f31f5)
