### ISSUE TITLE
How to validate PasswordBox

### ISSUE THREAD

**Issue by cureMooooonlight** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#977]
I used like this。
![image](https://user-images.githubusercontent.com/30659479/41967439-36b2e016-7a34-11e8-9d40-d734533e6340.png)
But it's not work.

**Comment by proxact** [comment]
Hi, you can find solution in this tutorial
[http://www.wpftutorial.net/PasswordBox.html](http://www.wpftutorial.net/PasswordBox.html)

**Comment by Keboo** [comment]
@cureMooooonlight there are a couple things going on here.
1. You are binding to the DataContext of the password box. This is not the same as binding to the Password property (which is what you are wanting to validate. Take a look at [this blog]() for information on MVVM and bindings.
2. The `Password` property of the PasswordBox is not a dependency property and is not directly bindable so you wont be able to apply a validation rule directly to it.

The link @proxact gave is a very good one and should get you the result you desire.
