### ISSUE TITLE
ElementHost DatePicker Selected/Current Date not displayed properly

### ISSUE THREAD

**Issue by uPloraX** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#987]
Hey there,
I want to display a DatePicker inside an ElementHost in a Windows Forms application, but I get the issue that the SelectedDate and CurrentDate are not readable, because the numbers won't be shown.

![issue](https://user-images.githubusercontent.com/20383017/42798994-655bd1fe-8996-11e8-90f6-a95829cffa92.png)
The 21 is where the mouse gets hovered*

[GitHub Repo example](https://github.com/uPloraX/MaterialDesignInXamlToolkit_DatePicker_WinForms_Issue)

**Comment by xDestinatioNx** [comment]
As a quick fix you can comment out the `ObjectAnimationUsingKeyFrames` for the `Selected` and `Today` visual states.

Here is a example [repo](https://github.com/jsanalytics/MaterialDesignDatePicker) by @jsanalytics
