### ISSUE TITLE
ComboBox :HintAssist.FloatingScale

### ISSUE THREAD

**Issue by dhongki** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#988]
Hello, I am trying to create a combobox with floating text label and wanted to make the floating hintassist more bigger just like what we can do textbox but it is not working? Any Suggestion?

![image](https://user-images.githubusercontent.com/28613377/42864803-3a994db6-8a9a-11e8-8f9b-9ccf0a0316c2.png)

**Comment by Keboo** [comment]
It looks like the hint on [ComboBox](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.ComboBox.xaml#L434-L441) is missing several properties that were implemented on [TextBox](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.TextBox.xaml#L71-L80).
Namely `FloatingOffset`, `FloatingScale`, and `Padding`

**Comment by Keboo** [comment]
Resolved by #899
