### ISSUE TITLE
materialDesign:TimePicker lost hh:mm:ss on binding

### ISSUE THREAD

**Issue by polipo** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#989]
*MaterialDesign last NUGET package 1.1.3 and Themes 2.4.0.1044*

I have a xaml page binding controls on viewmodel with properties i have
two properties DateTime?, the first bind on DateTimePicker and the second on TimePickerControl
The two get{} properties takes a value from same DateTime variable, the set i use different logic for
union the two info datepart and timepart.

If i open the form and don't focus on TimePicker
when retrieve the property set it LOST the information about hour, minute and second but not the date part (dmy).

Thanks

                    //XAML
                    <StackPanel Orientation="Horizontal" Grid.Row="0" Grid.Column="1" >
                        <DatePicker x:Name="dteAcquisitionTime" Text="{Binding Path=AcquisitionDate, Mode=TwoWay}" Width="Auto" VerticalAlignment="Bottom" Margin="5 0 0 0" materialDesign:HintAssist.Hint="{Binding lblAcquisitionTime}" materialDesign:HintAssist.IsFloating="True" MinWidth="90"/>
                        <materialDesign:TimePicker x:Name="dteAcquisitionHour" Text="{Binding Path=AcquisitionTime, Mode=TwoWay, StringFormat='HH:mm:ss'}" Is24Hours="True" materialDesign:HintAssist.Hint="" materialDesign:HintAssist.IsFloating="False" Width="Auto" MinWidth="60" VerticalAlignment="Bottom" Margin="5 0 0 0"/>
                    </StackPanel>

        //VIEW MODEL//
        public DateTime? AcquisitionTime
        {
            get
            {
                return _record.AcquisitionTime;
            }
            set
            {
                DateTime? retValue = null;
                if (AcquisitionDate.HasValue == true)
                {
                    retValue = new DateTime(AcquisitionDate.Value.Year, AcquisitionDate.Value.Month, AcquisitionDate.Value.Day);
                }

                if (retValue.HasValue && value.HasValue == true)
                {
                    //bug in TimePicker materialDesign control
                    if (value.Value.Hour == 0 & value.Value.Minute == 0 & value.Value.Second == 0)
                    {
                        var time = _control.dteAcquisitionHour.Text.Split(':');
                        retValue = retValue.Value.AddSeconds(double.Parse(time[2]));
                        retValue = retValue.Value.AddMinutes(double.Parse(time[1]));
                        retValue = retValue.Value.AddHours(double.Parse(time[0]));
                    }
                    else
                    {
                        retValue = retValue.Value.AddSeconds(value.Value.Second);
                        retValue = retValue.Value.AddMinutes(value.Value.Minute);
                        retValue = retValue.Value.AddHours(value.Value.Hour);
                    }

                }
                _record.AcquisitionTime = retValue;
            }
 public DateTime? AcquisitionDate
        {
            get
            {
                return _record.AcquisitionTime;
            }
            set
            {
                DateTime? retValue = null;
                if (value.HasValue == true)
                {
                    retValue = new DateTime(value.Value.Year, value.Value.Month, value.Value.Day);
                }
                if (AcquisitionTime.HasValue == true)
                {
                    if (retValue.HasValue)
                    {
                        retValue = retValue.Value.AddSeconds(AcquisitionTime.Value.Second);
                        retValue = retValue.Value.AddMinutes(AcquisitionTime.Value.Minute);
                        retValue = retValue.Value.AddHours(AcquisitionTime.Value.Hour);
                    }
                }
                _record.AcquisitionTime = retValue;
            }
        }

**Comment by Streissi** [comment]
hi i have some questions to your issue:

- Is the datetime `_record.AcquisitionTime` already set and you lost the time information?
- Are you setting the time before the date is set?

If you set your time before you set the date with your code, no time would be set.

**Comment by Xaalek** [comment]
I don't think the string format is needed.
Maybe, you just need to add the `WithSeconds` property.
`<materialDesign:TimePicker Is24Hours="True" WithSeconds="True"/>`
