### ISSUE TITLE
How can i remove the corners and shadows of button

### ISSUE THREAD

**Issue by yunhai2009** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#990]
hi  , How can i remove the corners and shadows of button

**Comment by jespersh** [comment]
The cornerradius is hardcoded to 2: https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L49 
At which point you might as well code your own button style (copy the MaterialDesignRaisedButton) and remove the parts you don't need.

**Comment by Keboo** [comment]
Just to complete the answer. The Shadows are controlled with the `ShadowAssist.ShadowDepth` attached property. If you set this to Depth0, that will remove the shadow.
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/Themes/MaterialDesignTheme.Button.xaml#L35
