### ISSUE TITLE
change Transitioner Index with code in C#

### ISSUE THREAD

**Issue by almas3s** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#995]
hi. with this Command can change Transitioner Index in xaml

`<Button x:Name="btnBack" Command="{x:Static materialDesign:Transitioner.MovePreviousCommand}" Width="120" >       
</Button>`

 now how i can change Transitioner Index in C# ?

**Comment by Keboo** [comment]
@almas3s `Trasitioner` derives from `Selector` and as such has a `SelectedIndex` property you can use.
So:
```C#
var transitioner = new Transitioner();
...
transitioner.SelectedIndex = Math.Min(transitioner.Items.Count - 1, transitioner.SelectedIndex + 1); //Move next
transitioner.SelectedIndex = Math.Max(0, transitioner.SelectedIndex - 1);
```

**Comment by almas3s** [comment]
@Keboo thank you.
But I use many UserControls in my TransitionerSlide.
and your code not work in event Click button on my UserControls

this works to Move Next:

` Transitioner.MoveNextCommand.Execute(null, null);`

but this not work for Previous:

`Transitioner.MovePreviousCommand.Execute(null, null);`


and this is my Transitioner:

` <materialDesign:Transitioner HorizontalAlignment="Stretch" VerticalAlignment="Stretch" SelectedIndex="0" AutoApplyTransitionOrigins="True">
        <materialDesign:TransitionerSlide>
            <Singup:One />
        </materialDesign:TransitionerSlide>
        <materialDesign:TransitionerSlide>
            <Singup:Two />
        </materialDesign:TransitionerSlide>
</materialDesign:Transitioner>`

**Comment by Keboo** [comment]
@almas3s when I change my example to use button click methods, and execute the commands as you indicated, the move next and move previous work just fine for me. Can you provide a sample project that reproduces the failure?

**Comment by almas3s** [comment]
@Keboo hi again.
I found the problem!
i used this code in MouseUp a StackPanel event:

`Transitioner.MovePreviousCommand.Execute(null, null);`

and now i put this code to click event a Button and this Works fine !
Although I did not understand why !

**Comment by Keboo** [comment]
@almas3s Was the MouseUp event handler firing? The MouseUp event is a bubbling event, which means if a control inside of the stackpanel marks the event as "handled" it will never reach the stack panel. You can use [snoop](https://github.com/cplotts/snoopwpf) to watch the routed events to see which elements are handling the event.
