### ISSUE TITLE
Corner Radius of DrawerHost content

### ISSUE THREAD

**Issue by Pekshev** [MaterialDesignInXAML/MaterialDesignInXamlToolkit#998]
Is the any way to set corner radius of drawer host? 
![image](https://user-images.githubusercontent.com/12638819/43644180-8b8065ea-9736-11e8-82fd-4eef3b3381b8.png)

**Comment by Keboo** [comment]
@Pekshev yes, in WPF you can accomplish this with the Clip property. This actually applies to any WPF control There is a great [write up](https://wpfspark.wordpress.com/2011/06/08/clipborder-a-wpf-border-that-clips/) on doing a custom border class that makes setting this up easily.
